<a href="https://colab.research.google.com/github/KaptainKris92/HuggingFace_RL_Course/blob/main/notebooks/unit1/LunarLander_v3_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LunarLander PPO experiments

This notebook provides a reusable workflow for training, evaluating, comparing and publishing PPO agents for `LunarLander-v3`.

## Core concepts

The environment gives the agent an eight-value observation describing the lander's position, velocity, angle, angular velocity and leg contact. The agent chooses one of four engine actions.

PPO uses an **actor–critic** architecture:

- The **actor** (`pi`) produces a probability distribution over actions.
- The **critic** (`vf`) estimates the expected future return from the current state.
- PPO uses the critic to estimate whether an action performed better or worse than expected, then updates the actor while clipping excessively large policy changes.

Important parameters:

- `gamma`: how strongly future rewards contribute to the return.
- `gae_lambda`: the bias–variance and temporal-credit-assignment trade-off in advantage estimation. It is not the exploration/exploitation setting.
- `ent_coef`: encourages exploration by preventing the actor from becoming deterministic too early.
- `net_arch`: controls the hidden-layer sizes of the actor and critic.

Models are compared on the same fixed evaluation seeds. By default, a candidate replaces the current Hugging Face model only when its fixed-seed mean reward is higher.

#### Installs and imports

In [1]:
!apt-get update -qq
!apt-get install -y -qq swig cmake ffmpeg xvfb libgl1

%pip install -q \
    "stable-baselines3[extra]==2.9.0" \
    "gymnasium[box2d]==1.3.0" \
    "huggingface-hub<2" \
    pyvirtualdisplay

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package swig4.0.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../swig4.0_4.0.2-1ubuntu1_amd64.deb ...
Unpacking swig4.0 (4.0.2-1ubuntu1) ...
Selecting previously unselected package swig.
Preparing to unpack .../swig_4.0.2-1ubuntu1_all.deb ...
Unpacking swig (4.0.2-1ubuntu1) ...
Setting up swig4.0 (4.0.2-1ubuntu1) ...
Setting up swig (4.0.2-1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.6/187.6 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 70.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 48.1 MB/s eta 0:00:00

In [2]:
from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Sequence
import json
import os
import shutil
import textwrap

import gymnasium as gym
import numpy as np
import pandas as pd

from huggingface_hub import (
    HfApi,
    hf_hub_download,
    notebook_login,
)
from huggingface_hub.utils import (
    EntryNotFoundError,
    RepositoryNotFoundError,
)

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    EvalCallback,
)
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor

from pyvirtualdisplay import Display
from IPython.display import Video, display


if not os.environ.get("DISPLAY"):
    virtual_display = Display(
        visible=False,
        size=(1400, 900),
    )
    virtual_display.start()

    print(
        "Virtual display started:",
        virtual_display.is_alive(),
    )
else:
    print("Using existing display:", os.environ["DISPLAY"])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Virtual display started: True

## Flip model

The plan for this model is to have the same architecture as before, but to change the environment's reward function to reward doing a full 360 degree flip before landing safely.

### Reward wrapper

In [3]:
%%writefile /content/flip_landing_reward_wrapper_v2.py

from __future__ import annotations

import math

import gymnasium as gym
import numpy as np


DEFAULT_REWARD_CONFIG = {
    "flip_landing_bonus": 750.0,
    "rotation_progress_bonus": 150.0,
    "flip_completion_bonus": 200.0,
    "recovery_bonus": 100.0,
    "failed_landing_penalty": 150.0,
    "required_rotations": 1.0,
    "upright_tolerance_radians": 0.30,
    "recovery_angular_velocity_tolerance": 0.50,
    "pre_flip_original_reward_weight": 0.25,
    "post_flip_original_reward_weight": 1.0,
    "post_flip_shaping_weight": 1.0,
    "post_flip_shaping_gamma": 0.995,
    "post_flip_shaping_clip": 10.0,
    "post_flip_center_weight": 50.0,
    "post_flip_horizontal_speed_weight": 30.0,
    "post_flip_angle_weight": 20.0,
    "post_flip_angular_speed_weight": 10.0,
    "post_flip_leg_contact_weight": 10.0,
    "rotation_direction": 1,
    "landing_without_flip_penalty": 300.0,
    "no_flip_terminal_penalty": 300.0,
    "post_flip_vertical_speed_weight": 30.0,
    "landing_zone_half_width": 0.20,   # Tighten once model learns to land in/close to zone
    "outside_zone_landing_penalty": 1_000.0,
    "post_flip_zone_excess_weight": 200.0,
    "post_flip_target_vx_gain": 0.50,
    "post_flip_max_target_vx": 0.35,
}


class FlipLandingRewardWrapper(gym.Wrapper):
    """
    Stage-aware LunarLander objective:

    1. Complete one full rotation in the selected direction.
    2. Arrest the spin and recover to an upright attitude.
    3. Re-centre, stabilise and land safely.

    The original eight-value observation is extended with:
    - signed rotation progress in [-1, 1];
    - a flip-completed flag;
    - a post-flip-recovery-completed flag.

    Post-flip recovery uses a potential-difference reward based on
    horizontal position, horizontal speed, attitude, angular speed,
    and leg contact. This rewards improvement rather than repeatedly
    paying the agent simply for occupying a favourable state.
    """

    def __init__(
        self,
        env: gym.Env,
        *,
        flip_landing_bonus: float = 750.0,
        rotation_progress_bonus: float = 150.0,
        flip_completion_bonus: float = 200.0,
        recovery_bonus: float = 100.0,
        no_flip_terminal_penalty: float = 0.0,
        failed_landing_penalty: float = 150.0,
        required_rotations: float = 1.0,
        upright_tolerance_radians: float = 0.30,
        recovery_angular_velocity_tolerance: float = 0.50,
        pre_flip_original_reward_weight: float = 0.25,
        post_flip_original_reward_weight: float = 1.0,
        post_flip_shaping_weight: float = 1.0,
        post_flip_shaping_gamma: float = 0.995,
        post_flip_shaping_clip: float = 10.0,
        post_flip_center_weight: float = 50.0,
        post_flip_horizontal_speed_weight: float = 30.0,
        post_flip_angle_weight: float = 20.0,
        post_flip_angular_speed_weight: float = 10.0,
        post_flip_leg_contact_weight: float = 10.0,
        rotation_direction: int = 1,
        landing_without_flip_penalty: float = 300.0,
        post_flip_vertical_speed_weight: float = 30.0,
        landing_zone_half_width: float = 0.20, # Tighten once model learns to land in/close to zone
        outside_zone_landing_penalty: float = 1_000.0,
        post_flip_zone_excess_weight: float = 200.0,
        post_flip_target_vx_gain: float = 0.50,
        post_flip_max_target_vx: float = 0.35,
    ):
        super().__init__(env)

        self.flip_landing_bonus = float(flip_landing_bonus)
        self.rotation_progress_bonus = float(
            rotation_progress_bonus
        )
        self.flip_completion_bonus = float(
            flip_completion_bonus
        )
        self.recovery_bonus = float(recovery_bonus)
        self.no_flip_terminal_penalty = float(
            no_flip_terminal_penalty
        )
        self.failed_landing_penalty = float(
            failed_landing_penalty
        )

        self.required_rotation = (
            2.0 * math.pi * float(required_rotations)
        )
        self.required_rotations = float(required_rotations)
        self.upright_tolerance_radians = float(
            upright_tolerance_radians
        )
        self.recovery_angular_velocity_tolerance = float(
            recovery_angular_velocity_tolerance
        )

        self.pre_flip_original_reward_weight = float(
            pre_flip_original_reward_weight
        )
        self.post_flip_original_reward_weight = float(
            post_flip_original_reward_weight
        )

        self.post_flip_shaping_weight = float(
            post_flip_shaping_weight
        )
        self.post_flip_shaping_gamma = float(
            post_flip_shaping_gamma
        )
        self.post_flip_shaping_clip = float(
            post_flip_shaping_clip
        )
        self.post_flip_center_weight = float(
            post_flip_center_weight
        )
        self.post_flip_horizontal_speed_weight = float(
            post_flip_horizontal_speed_weight
        )
        self.post_flip_angle_weight = float(
            post_flip_angle_weight
        )
        self.post_flip_angular_speed_weight = float(
            post_flip_angular_speed_weight
        )
        self.post_flip_leg_contact_weight = float(
            post_flip_leg_contact_weight
        )

        self.post_flip_vertical_speed_weight = float(
            post_flip_vertical_speed_weight
        )

        self.rotation_direction = int(rotation_direction)

        self.previous_angle = 0.0
        self.cumulative_rotation = 0.0
        self.maximum_rotation_progress = 0.0
        self.flip_completed = False
        self.recovery_completed = False
        self.previous_post_flip_potential: float | None = None
        self.landing_without_flip_penalty = float(
            landing_without_flip_penalty
        )

        self.landing_zone_half_width = float(
            landing_zone_half_width
        )

        self.outside_zone_landing_penalty = float(
            outside_zone_landing_penalty
        )

        self.post_flip_zone_excess_weight = float(
            post_flip_zone_excess_weight
        )

        self.post_flip_target_vx_gain = float(
            post_flip_target_vx_gain
        )

        self.post_flip_max_target_vx = float(
            post_flip_max_target_vx
        )

        base_space = env.observation_space

        if not isinstance(base_space, gym.spaces.Box):
            raise TypeError(
                "The wrapped environment must have a Box "
                "observation space."
            )

        extra_low = np.asarray(
            [-1.0, 0.0, 0.0],
            dtype=np.float32,
        )
        extra_high = np.asarray(
            [1.0, 1.0, 1.0],
            dtype=np.float32,
        )

        self.observation_space = gym.spaces.Box(
            low=np.concatenate(
                [
                    base_space.low.astype(np.float32),
                    extra_low,
                ]
            ),
            high=np.concatenate(
                [
                    base_space.high.astype(np.float32),
                    extra_high,
                ]
            ),
            dtype=np.float32,
        )

                if required_rotations <= 0:
            raise ValueError("required_rotations must be positive.")

        if rotation_direction not in (-1, 1):
            raise ValueError(
                "rotation_direction must be either -1 or 1."
            )

        if not 0.0 <= post_flip_shaping_gamma <= 1.0:
            raise ValueError(
                "post_flip_shaping_gamma must be in [0, 1]."
            )

        if post_flip_shaping_clip <= 0:
            raise ValueError(
                "post_flip_shaping_clip must be positive."
            )

        if not 0.0 < landing_zone_half_width < 1.0:
            raise ValueError(
                "landing_zone_half_width must be "
                "between 0 and 1."
            )

        if outside_zone_landing_penalty < 0.0:
            raise ValueError(
                "outside_zone_landing_penalty "
                "must not be negative."
            )

    @staticmethod
    def _wrap_angle(angle: float) -> float:
        """Wrap an angle to [-pi, pi]."""

        return float(
            np.arctan2(
                np.sin(angle),
                np.cos(angle),
            )
        )

    def _signed_rotation_progress(self) -> float:
        return float(
            np.clip(
                self.cumulative_rotation
                / self.required_rotation,
                -1.0,
                1.0,
            )
        )

    def _augment_observation(
        self,
        observation: np.ndarray,
    ) -> np.ndarray:
        return np.concatenate(
            [
                np.asarray(
                    observation,
                    dtype=np.float32,
                ),
                np.asarray(
                    [
                        self._signed_rotation_progress(),
                        float(self.flip_completed),
                        float(self.recovery_completed),
                    ],
                    dtype=np.float32,
                ),
            ]
        )

    def _post_flip_potential(
        self,
        observation: np.ndarray,
    ) -> float:
        """
        Higher values represent safer post-flip states.

        LunarLander-v3 observation positions:
        0 x position, 2 x velocity, 4 angle, 5 angular velocity,
        6 left-leg contact and 7 right-leg contact.
        """

        x_position = float(
            observation[0]
        )

        y_position = float(
            observation[1]
        )

        horizontal_speed = float(
            observation[2]
        )

        vertical_speed = float(
            observation[3]
        )

        wrapped_angle = abs(
            self._wrap_angle(
                float(observation[4])
            )
        )

        angular_speed = abs(
            float(observation[5])
        )

        leg_contacts = (
            float(observation[6] > 0.5)
            + float(observation[7] > 0.5)
        )

        # Distance beyond the two landing-zone flags.
        zone_excess = max(
            abs(x_position)
            - self.landing_zone_half_width,
            0.0,
        )

        # When left of the pad, target positive horizontal
        # velocity. When right of the pad, target negative
        # horizontal velocity. Close to the centre, target
        # velocity approaches zero.
        target_horizontal_speed = float(
            np.clip(
                -self.post_flip_target_vx_gain
                * x_position,
                -self.post_flip_max_target_vx,
                self.post_flip_max_target_vx,
            )
        )

        horizontal_speed_error = abs(
            horizontal_speed
            - target_horizontal_speed
        )

        # Increase the importance of entering the landing
        # zone as the lander approaches the ground.
        near_ground_factor = float(
            np.clip(
                1.0
                - max(y_position, 0.0)
                / 0.75,
                0.0,
                1.0,
            )
        )

        effective_zone_weight = (
            self.post_flip_zone_excess_weight
            * (1.0 + near_ground_factor)
        )

        return float(
            -self.post_flip_center_weight
            * abs(x_position)

            -effective_zone_weight
            * zone_excess

            -self.post_flip_horizontal_speed_weight
            * horizontal_speed_error

            -self.post_flip_vertical_speed_weight
            * abs(vertical_speed)

            -self.post_flip_angle_weight
            * wrapped_angle

            -self.post_flip_angular_speed_weight
            * angular_speed

            +self.post_flip_leg_contact_weight
            * leg_contacts
        )

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict | None = None,
    ):
        observation, info = self.env.reset(
            seed=seed,
            options=options,
        )

        self.previous_angle = float(observation[4])
        self.cumulative_rotation = 0.0
        self.maximum_rotation_progress = 0.0
        self.flip_completed = False
        self.recovery_completed = False
        self.previous_post_flip_potential = None

        info = dict(info)
        info.update(
            {
                "flip_completed": False,
                "recovery_completed": False,
                "rotation_progress": 0.0,
                "rotations_completed": 0.0,
                "rotation_progress_reward": 0.0,
                "flip_completion_reward": 0.0,
                "recovery_reward": 0.0,
                "post_flip_shaping_reward": 0.0,
                "flip_landing_bonus": 0.0,
                "terminal_adjustment": 0.0,
            }
        )

        return self._augment_observation(observation), info

    def step(self, action):
        (
            observation,
            original_reward,
            terminated,
            truncated,
            info,
        ) = self.env.step(action)

        current_angle = float(observation[4])
        angular_velocity = float(observation[5])

        angle_change = self._wrap_angle(
            current_angle - self.previous_angle
        )
        self.previous_angle = current_angle

        directed_change = (
            self.rotation_direction * angle_change
        )
        self.cumulative_rotation += directed_change

        rotation_progress = float(
            np.clip(
                self.cumulative_rotation
                / self.required_rotation,
                0.0,
                1.0,
            )
        )

        new_progress = max(
            0.0,
            rotation_progress
            - self.maximum_rotation_progress,
        )
        progress_reward = (
            self.rotation_progress_bonus
            * new_progress
        )
        self.maximum_rotation_progress = max(
            self.maximum_rotation_progress,
            rotation_progress,
        )

        completion_reward = 0.0

        if (
            rotation_progress >= 1.0
            and not self.flip_completed
        ):
            self.flip_completed = True
            completion_reward = (
                self.flip_completion_bonus
            )

        wrapped_angle = abs(
            self._wrap_angle(current_angle)
        )
        upright = (
            wrapped_angle
            <= self.upright_tolerance_radians
        )

        recovery_reward = 0.0

        if (
            self.flip_completed
            and not self.recovery_completed
            and upright
            and abs(angular_velocity)
            <= self.recovery_angular_velocity_tolerance
        ):
            self.recovery_completed = True
            recovery_reward = self.recovery_bonus

        post_flip_shaping_reward = 0.0
        post_flip_potential = None

        if self.flip_completed:
            post_flip_potential = (
                self._post_flip_potential(observation)
            )

            if self.previous_post_flip_potential is None:
                self.previous_post_flip_potential = (
                    post_flip_potential
                )
            else:
                potential_difference = (
                    self.post_flip_shaping_gamma
                    * post_flip_potential
                    - self.previous_post_flip_potential
                )
                post_flip_shaping_reward = float(
                    np.clip(
                        self.post_flip_shaping_weight
                        * potential_difference,
                        -self.post_flip_shaping_clip,
                        self.post_flip_shaping_clip,
                    )
                )
                self.previous_post_flip_potential = (
                    post_flip_potential
                )

        left_leg_contact = bool(observation[6] > 0.5)
        right_leg_contact = bool(observation[7] > 0.5)

        x_position = float(
            observation[0]
        )

        inside_landing_zone = bool(
            abs(x_position)
            <= self.landing_zone_half_width
        )

        stable_landing = bool(
            terminated
            and float(original_reward) > 0.0
            and left_leg_contact
            and right_leg_contact
            and upright
        )

        # "Safe landing" now means stable and
        # between the landing-zone boundaries.
        landed_safely = bool(
            stable_landing
            and inside_landing_zone
        )

        episode_finished = bool(
            terminated or truncated
        )

        terminal_adjustment = 0.0
        outcome = "in_progress"

        if (
            self.flip_completed
            and landed_safely
        ):
            terminal_adjustment = (
                self.flip_landing_bonus
            )

            outcome = (
                "flip_and_safe_landing"
            )

        elif episode_finished:
            if not self.flip_completed:
                if stable_landing:
                    terminal_adjustment = -(
                        self.landing_without_flip_penalty
                    )

                    outcome = (
                        "stable_landing_without_flip"
                    )

                else:
                    terminal_adjustment = -(
                        self.no_flip_terminal_penalty
                    )

                    outcome = (
                        "episode_ended_without_flip"
                    )

            elif (
                stable_landing
                and not inside_landing_zone
            ):
                terminal_adjustment = -(
                    self.outside_zone_landing_penalty
                )

                outcome = (
                    "flip_and_stable_landing_"
                    "outside_zone"
                )

            else:
                terminal_adjustment = -(
                    self.failed_landing_penalty
                )

                outcome = (
                    "flip_but_failed_landing"
                )

        original_weight = (
            self.post_flip_original_reward_weight
            if self.flip_completed
            else self.pre_flip_original_reward_weight
        )

        modified_reward = (
            original_weight * float(original_reward)
            + progress_reward
            + completion_reward
            + recovery_reward
            + post_flip_shaping_reward
            + terminal_adjustment
        )

        info = dict(info)
        info.update(
            {
                "original_reward": float(original_reward),
                "rotation_progress": rotation_progress,
                "rotation_progress_reward": progress_reward,
                "flip_completion_reward": completion_reward,
                "recovery_reward": recovery_reward,
                "post_flip_shaping_reward": (
                    post_flip_shaping_reward
                ),
                "post_flip_potential": post_flip_potential,
                "cumulative_rotation": (
                    self.cumulative_rotation
                ),
                "rotations_completed": (
                    self.cumulative_rotation
                    / (2.0 * math.pi)
                ),
                "flip_completed": self.flip_completed,
                "recovery_completed": (
                    self.recovery_completed
                ),
                "landed_safely": landed_safely,
                "original_reward_weight": original_weight,
                "terminal_adjustment": (
                    terminal_adjustment
                ),
                "flip_landing_bonus": (
                    self.flip_landing_bonus
                    if outcome
                    == "flip_and_safe_landing"
                    else 0.0
                ),
                "custom_outcome": outcome,
                "stable_landing": stable_landing,
                "inside_landing_zone": (
                    inside_landing_zone
                ),
                "horizontal_position": (
                    x_position
                ),
            }
        )

        return (
            self._augment_observation(observation),
            modified_reward,
            terminated,
            truncated,
            info,
        )


def make_flip_lander(
    *,
    render_mode: str | None = None,
    reward_config: dict | None = None,
) -> gym.Env:
    """
    Build the exact environment used for training and evaluation.

    Pass the same reward_config to the uploader so the Hub model card
    records the environment accurately.
    """

    config = {
        **DEFAULT_REWARD_CONFIG,
        **(reward_config or {}),
    }

    base_env = gym.make(
        "LunarLander-v3",
        render_mode=render_mode,
    )

    return FlipLandingRewardWrapper(
        base_env,
        **config,
    )

Writing /content/flip_landing_reward_wrapper_v2.py

In [4]:
from copy import deepcopy
from pathlib import Path
import importlib

import flip_landing_reward_wrapper_v2 as flip_wrapper

# Important when the module has previously been imported in this runtime.
importlib.reload(flip_wrapper)

DEFAULT_REWARD_CONFIG = (
    flip_wrapper.DEFAULT_REWARD_CONFIG
)
FlipLandingRewardWrapper = (
    flip_wrapper.FlipLandingRewardWrapper
)
make_flip_lander = (
    flip_wrapper.make_flip_lander
)

REWARD_WRAPPER_PATH = Path(
    "/content/flip_landing_reward_wrapper_v2.py"
)

base_reward_config = deepcopy(
    DEFAULT_REWARD_CONFIG
)

base_reward_config[
    "post_flip_shaping_gamma"
] = 0.999


flip_acquisition_config = {
    **base_reward_config,

    # Make discovering the flip worthwhile.
    "rotation_progress_bonus": 300.0,
    "flip_completion_bonus": 500.0,

    # Retain some position and velocity guidance,
    # but prevent ordinary landing from winning.
    "pre_flip_original_reward_weight": 0.15,
    "post_flip_original_reward_weight": 1.0,

    "landing_without_flip_penalty": 300.0,
    "no_flip_terminal_penalty": 100.0,

    # During acquisition, a flip followed by a crash
    # must still be recognised as progress.
    "failed_landing_penalty": 0.0,

    "recovery_bonus": 100.0,
    "post_flip_shaping_weight": 0.5,

    "flip_landing_bonus": 1_000.0,
}


flip_landing_config = {
    **flip_acquisition_config,

    # Keep the flip rewards. Reducing them risks
    # catastrophic forgetting of the rotation.
    "rotation_progress_bonus": 300.0,
    "flip_completion_bonus": 500.0,

    # The requested post-flip landing multiplier.
    "post_flip_original_reward_weight": 3.0,

    "recovery_bonus": 250.0,
    "post_flip_shaping_weight": 1.5,

    # Once the flip is learned, crashes should
    # become significantly unattractive.
    "failed_landing_penalty": 400.0,

    # Exclusive reward for completing both stages.
    "flip_landing_bonus": 1_500.0,
}

flip_in_zone_config = {
    **flip_landing_config,

    # The current flip and recovery rewards remain
    # unchanged to preserve the learned rotation.
    "rotation_progress_bonus": 300.0,
    "flip_completion_bonus": 500.0,
    "recovery_bonus": 250.0,

    # Landing zone is approximately between
    # observation x=-0.20 and x=+0.20.
    "landing_zone_half_width": 0.20,

    # Stable off-zone landings must no longer
    # receive the success return.
    "outside_zone_landing_penalty": 1_000.0,

    # Stronger post-flip pad acquisition.
    "post_flip_center_weight": 120.0,
    "post_flip_zone_excess_weight": 200.0,

    # Allow purposeful lateral movement towards
    # the centre rather than demanding vx=0.
    "post_flip_horizontal_speed_weight": 40.0,
    "post_flip_target_vx_gain": 0.50,
    "post_flip_max_target_vx": 0.35,

    # Slightly stronger recovery shaping.
    "post_flip_shaping_weight": 2.0,
    "post_flip_shaping_clip": 20.0,

    # Keep the exclusive in-zone success bonus.
    "flip_landing_bonus": 1_500.0,
}


def make_flip_acquisition_lander(
    *,
    render_mode: str | None = None,
):
    return make_flip_lander(
        render_mode=render_mode,
        reward_config=(
            flip_acquisition_config
        ),
    )


def make_flip_landing_lander(
    *,
    render_mode: str | None = None,
):
    return make_flip_lander(
        render_mode=render_mode,
        reward_config=(
            flip_landing_config
        ),
    )

def make_flip_in_zone_lander(
    *,
    render_mode: str | None = None,
):
    return make_flip_lander(
        render_mode=render_mode,
        reward_config=(
            flip_in_zone_config
        ),
    )

### Upload checkpoint to HuggingFace

In [5]:
from pathlib import Path

from huggingface_hub import HfApi
from stable_baselines3.common.callbacks import (
    BaseCallback,
)


class HubCheckpointCallback(
    BaseCallback
):
    def __init__(
        self,
        *,
        repo_id: str,
        every_timesteps: int = 1_000_000,
        verbose: int = 1,
    ):
        super().__init__(verbose)

        self.repo_id = repo_id
        self.every_timesteps = int(
            every_timesteps
        )
        self.next_upload = int(
            every_timesteps
        )
        self.api = HfApi()

        self.local_path = Path(
            "/content/"
            "latest_flip_checkpoint.zip"
        )

    def _on_step(self) -> bool:
        if (
            self.num_timesteps
            < self.next_upload
        ):
            return True

        step = int(
            self.num_timesteps
        )

        self.model.save(
            str(self.local_path)
        )

        self.api.upload_file(
            path_or_fileobj=str(
                self.local_path
            ),
            path_in_repo=(
                "training-checkpoints/"
                f"ppo_flip_{step}_steps.zip"
            ),
            repo_id=self.repo_id,
            repo_type="model",
            commit_message=(
                f"Save training checkpoint "
                f"at {step:,} steps"
            ),
        )

        if self.verbose:
            print(
                "Uploaded Hub checkpoint:",
                f"{step:,} steps",
            )

        while (
            self.next_upload
            <= step
        ):
            self.next_upload += (
                self.every_timesteps
            )

        return True

### Model loading ane evaluation

In [6]:
def load_ppo_model(
    model_or_path: PPO | str | Path,
    *,
    device: str = "cpu",
) -> PPO:
    """Return an existing PPO object or load one from disk."""

    if isinstance(model_or_path, PPO):
        return model_or_path

    model_path = Path(model_or_path)

    if not model_path.exists():
        raise FileNotFoundError(
            f"Model not found: {model_path}"
        )

    return PPO.load(
        str(model_path),
        device=device,
    )

### Training function

In [7]:
# New training function
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any
import json

import gymnasium as gym

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    EvalCallback,
)
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor


def train_ppo_experiment(
    *,
    experiment_name: str,
    total_timesteps: int,
    env_id: str = "LunarLander-v3",
    env_factory: Callable[[], gym.Env] | None = None,
    env_kwargs: dict[str, Any] | None = None,
    n_envs: int = 16,
    seed: int = 42,
    actor_layers: Sequence[int] = (64, 64),
    critic_layers: Sequence[int] = (64, 64),
    learning_rate: float = 3e-4,
    n_steps: int = 1024,
    batch_size: int = 64,
    n_epochs: int = 4,
    gamma: float = 0.999,
    gae_lambda: float = 0.98,
    ent_coef: float = 0.01,
    clip_range: float = 0.2,
    eval_every_timesteps: int = 50_000,
    checkpoint_every_timesteps: int = 100_000,
    n_eval_episodes: int = 20,
    output_root: str | Path = "/content/rl-experiments",
    device: str = "cpu",
    verbose: int = 1,
    extra_callbacks: Sequence[
        BaseCallback
    ] | None = None,
    initial_model_path: (
        str | Path | None
    ) = None,
) -> dict[str, Any]:
    """
    Train a PPO actor–critic model.

    env_factory
        Optional callable that returns a custom Gymnasium environment.
        Use this for the flip-reward environment.

    The function saves:
    - periodic safety checkpoints;
    - the checkpoint with the highest evaluation mean;
    - the model from the final training timestep;
    - the complete training configuration.
    """

    if not experiment_name.strip():
        raise ValueError(
            "experiment_name must not be empty."
        )

    if total_timesteps <= 0:
        raise ValueError(
            "total_timesteps must be positive."
        )

    if n_envs <= 0:
        raise ValueError(
            "n_envs must be positive."
        )

    env_kwargs = dict(env_kwargs or {})

    if env_factory is not None and env_kwargs:
        raise ValueError(
            "Use either env_factory or env_kwargs, not both. "
            "Put custom environment arguments inside the factory."
        )

    output_dir = (
        Path(output_root)
        / experiment_name
    )
    best_model_dir = (
        output_dir
        / "best_model"
    )
    checkpoint_dir = (
        output_dir
        / "checkpoints"
    )
    evaluation_dir = (
        output_dir
        / "evaluations"
    )

    for directory in (
        best_model_dir,
        checkpoint_dir,
        evaluation_dir,
    ):
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    configuration = {
        "experiment_name": experiment_name,
        "env_id": env_id,
        "environment_factory": (
            getattr(
                env_factory,
                "__name__",
                None,
            )
            if env_factory is not None
            else None
        ),
        "env_kwargs": env_kwargs,
        "total_timesteps": total_timesteps,
        "n_envs": n_envs,
        "seed": seed,
        "actor_layers": list(actor_layers),
        "critic_layers": list(critic_layers),
        "learning_rate": learning_rate,
        "n_steps": n_steps,
        "batch_size": batch_size,
        "n_epochs": n_epochs,
        "gamma": gamma,
        "gae_lambda": gae_lambda,
        "ent_coef": ent_coef,
        "clip_range": clip_range,
        "eval_every_timesteps": (
            eval_every_timesteps
        ),
        "checkpoint_every_timesteps": (
            checkpoint_every_timesteps
        ),
        "n_eval_episodes": n_eval_episodes,
        "device": device,
        "initial_model_path": (
            str(initial_model_path)
            if initial_model_path is not None
            else None
        ),
    }

    config_path = (
        output_dir
        / "training_config.json"
    )

    config_path.write_text(
        json.dumps(
            configuration,
            indent=2,
        ),
        encoding="utf-8",
    )

    # Create standard or customised environments.
    if env_factory is None:
        train_env = make_vec_env(
            env_id,
            n_envs=n_envs,
            seed=seed,
            env_kwargs=env_kwargs,
        )

        eval_env = Monitor(
            gym.make(
                env_id,
                **env_kwargs,
            )
        )

    else:
        train_env = make_vec_env(
            env_factory,
            n_envs=n_envs,
            seed=seed,
        )

        eval_env = Monitor(
            env_factory()
        )

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=str(
            best_model_dir
        ),
        log_path=str(
            evaluation_dir
        ),
        eval_freq=max(
            eval_every_timesteps // n_envs,
            1,
        ),
        n_eval_episodes=n_eval_episodes,
        deterministic=True,
        render=False,
        verbose=1,
    )

    checkpoint_callback = CheckpointCallback(
        save_freq=max(
            checkpoint_every_timesteps // n_envs,
            1,
        ),
        save_path=str(
            checkpoint_dir
        ),
        name_prefix=experiment_name,
        verbose=2,
    )

    callbacks = [
        eval_callback,
        checkpoint_callback,
        *(extra_callbacks or []),
    ]

    policy_kwargs = {
        "net_arch": {
            "pi": list(actor_layers),
            "vf": list(critic_layers),
        }
    }

    if initial_model_path is None:
        model = PPO(
            policy="MlpPolicy",
            env=train_env,
            learning_rate=learning_rate,
            n_steps=n_steps,
            batch_size=batch_size,
            n_epochs=n_epochs,
            gamma=gamma,
            gae_lambda=gae_lambda,
            ent_coef=ent_coef,
            clip_range=clip_range,
            policy_kwargs=policy_kwargs,
            device=device,
            seed=seed,
            verbose=verbose,
        )

        reset_num_timesteps = True

    else:
      model = PPO.load(
          str(initial_model_path),
          env=train_env,
          device=device,

          # Override selected training settings
          # for the refinement phase.
          learning_rate=learning_rate,
          n_steps=n_steps,
          batch_size=batch_size,
          n_epochs=n_epochs,
          gamma=gamma,
          gae_lambda=gae_lambda,
          ent_coef=ent_coef,
          clip_range=clip_range,
      )

      reset_num_timesteps = False

    try:
        model.learn(
            total_timesteps=total_timesteps,
            callback=callbacks,
            progress_bar=True,
            reset_num_timesteps=(
                reset_num_timesteps
            ),
        )

        final_model_stem = (
            output_dir
            / "final_model"
        )

        model.save(
            str(final_model_stem)
        )

    finally:
        train_env.close()
        eval_env.close()

    best_model_path = (
        best_model_dir
        / "best_model.zip"
    )
    final_model_path = (
        output_dir
        / "final_model.zip"
    )
    evaluations_path = (
        evaluation_dir
        / "evaluations.npz"
    )

    if not best_model_path.exists():
        raise FileNotFoundError(
            "EvalCallback did not create best_model.zip. "
            "Check that training reached at least one "
            "evaluation interval."
        )

    print("Best model:", best_model_path)
    print("Final model:", final_model_path)
    print("Configuration:", config_path)

    return {
        "experiment_name": experiment_name,
        "output_dir": output_dir,
        "best_model_path": best_model_path,
        "final_model_path": final_model_path,
        "evaluations_path": evaluations_path,
        "config_path": config_path,
        "configuration": configuration,
    }

### Evaluation function

In [8]:
import numpy as np
import pandas as pd


def evaluate_flip_model(
    model_or_path,
    *,
    reward_config: dict,
    n_episodes: int = 100,
    starting_seed: int = 20_000,
    deterministic: bool = True,
):
    """
    Evaluate the flip-recover-land agent over fixed seeds.
    """

    if n_episodes <= 0:
        raise ValueError(
            "n_episodes must be positive."
        )

    model = load_ppo_model(
        model_or_path
    )

    episode_rows = []

    for episode_number in range(
        n_episodes
    ):
        seed = (
            starting_seed
            + episode_number
        )

        env = make_flip_lander(
            reward_config=reward_config
        )

        try:
            observation, _ = env.reset(
                seed=seed
            )

            terminated = False
            truncated = False

            shaped_reward_total = 0.0
            original_reward_total = 0.0
            episode_steps = 0
            final_info = {}

            while not (
                terminated or truncated
            ):
                action, _ = model.predict(
                    observation,
                    deterministic=deterministic,
                )

                # LunarLander-v3 uses Discrete(4).
                action = int(
                    np.asarray(
                        action
                    ).item()
                )

                (
                    observation,
                    shaped_reward,
                    terminated,
                    truncated,
                    info,
                ) = env.step(action)

                shaped_reward_total += float(
                    shaped_reward
                )

                original_reward_total += float(
                    info.get(
                        "original_reward",
                        shaped_reward,
                    )
                )

                episode_steps += 1
                final_info = dict(info)

            flip_completed = bool(
                final_info.get(
                    "flip_completed",
                    False,
                )
            )

            recovery_completed = bool(
                final_info.get(
                    "recovery_completed",
                    False,
                )
            )

            landed_safely = bool(
                final_info.get(
                    "landed_safely",
                    False,
                )
            )

            custom_outcome = str(
                final_info.get(
                    "custom_outcome",
                    "unknown",
                )
            )

            flip_and_landed = (
                custom_outcome
                == "flip_and_safe_landing"
            )

            stable_landing = bool(
                final_info.get(
                    "stable_landing",
                    False,
                )
            )

            inside_landing_zone = bool(
                final_info.get(
                    "inside_landing_zone",
                    False,
                )
            )

            episode_rows.append(
                {
                    "seed": seed,
                    "shaped_reward": (
                        shaped_reward_total
                    ),
                    "original_reward": (
                        original_reward_total
                    ),
                    "steps": episode_steps,
                    "flip_completed": (
                        flip_completed
                    ),
                    "recovery_completed": (
                        recovery_completed
                    ),
                    "landed_safely": (
                        landed_safely
                    ),
                    "flip_and_landed": (
                        flip_and_landed
                    ),
                    "flip_bonus": float(
                        final_info.get(
                            "flip_landing_bonus",
                            0.0,
                        )
                    ),
                    "rotations_completed": float(
                        final_info.get(
                            "rotations_completed",
                            0.0,
                        )
                    ),
                    "terminal_adjustment": float(
                        final_info.get(
                            "terminal_adjustment",
                            0.0,
                        )
                    ),
                    "custom_outcome": (
                        custom_outcome
                    ),
                    "stable_landing": stable_landing,
                    "inside_landing_zone": (
                        inside_landing_zone
                    ),
                    "outside_zone_landing": (
                        stable_landing
                        and not inside_landing_zone
                    ),
                }
            )

        finally:
            env.close()

    episodes = pd.DataFrame(
        episode_rows
    )

    shaped_rewards = episodes[
        "shaped_reward"
    ].to_numpy(dtype=float)

    original_rewards = episodes[
        "original_reward"
    ].to_numpy(dtype=float)

    flip_mask = episodes[
        "flip_completed"
    ]

    if flip_mask.any():
        recovery_given_flip_rate = float(
            episodes.loc[
                flip_mask,
                "recovery_completed",
            ].mean()
        )

        landing_given_flip_rate = float(
            episodes.loc[
                flip_mask,
                "flip_and_landed",
            ].mean()
        )
    else:
        recovery_given_flip_rate = 0.0
        landing_given_flip_rate = 0.0

    summary = {
        "n_episodes": int(n_episodes),

        "mean_shaped_reward": float(
            shaped_rewards.mean()
        ),
        "std_shaped_reward": float(
            shaped_rewards.std()
        ),
        "shaped_course_score": float(
            shaped_rewards.mean()
            - shaped_rewards.std()
        ),
        "min_shaped_reward": float(
            shaped_rewards.min()
        ),
        "max_shaped_reward": float(
            shaped_rewards.max()
        ),

        "mean_original_reward": float(
            original_rewards.mean()
        ),
        "std_original_reward": float(
            original_rewards.std()
        ),
        "original_course_score": float(
            original_rewards.mean()
            - original_rewards.std()
        ),
        "min_original_reward": float(
            original_rewards.min()
        ),
        "max_original_reward": float(
            original_rewards.max()
        ),

        "original_reward_200_rate": float(
            np.mean(
                original_rewards >= 200.0
            )
        ),
        "flip_completion_rate": float(
            episodes[
                "flip_completed"
            ].mean()
        ),
        "recovery_completion_rate": float(
            episodes[
                "recovery_completed"
            ].mean()
        ),
        "recovery_given_flip_rate": (
            recovery_given_flip_rate
        ),
        "safe_landing_rate": float(
            episodes[
                "landed_safely"
            ].mean()
        ),
        "flip_landing_rate": float(
            episodes[
                "flip_and_landed"
            ].mean()
        ),
        "landing_given_flip_rate": (
            landing_given_flip_rate
        ),
        "stable_landing_rate": float(
            episodes[
                "stable_landing"
            ].mean()
        ),

        "inside_landing_zone_rate": float(
            episodes[
                "inside_landing_zone"
            ].mean()
        ),

        "outside_zone_landing_rate": float(
            episodes[
                "outside_zone_landing"
            ].mean()
        ),
    }

    print("Flip model evaluation")
    print("---------------------")
    print(
        "Mean shaped reward:",
        f"{summary['mean_shaped_reward']:.2f}",
    )
    print(
        "Mean original reward:",
        f"{summary['mean_original_reward']:.2f}",
    )
    print(
        "Completed a full rotation:",
        f"{summary['flip_completion_rate']:.1%}",
    )
    print(
        "Recovered after the flip:",
        f"{summary['recovery_completion_rate']:.1%}",
    )
    print(
        "Recovery rate given a flip:",
        f"{summary['recovery_given_flip_rate']:.1%}",
    )
    print(
        "Landed safely:",
        f"{summary['safe_landing_rate']:.1%}",
    )
    print(
        "Flipped and landed safely:",
        f"{summary['flip_landing_rate']:.1%}",
    )
    print(
        "Landing rate given a flip:",
        f"{summary['landing_given_flip_rate']:.1%}",
    )

    return {
        "summary": summary,
        "episodes": episodes,
    }

### HuggingFace login

In [9]:
from huggingface_hub import notebook_login

notebook_login()

### Train model

In [10]:
# Clean progress display
from rich import get_console

console = get_console()

# Rich versions that store a single active display.
active_live = getattr(console, "_live", None)

if active_live is not None:
    try:
        active_live.stop()
    except Exception:
        try:
            console.clear_live()
        except Exception:
            pass

# Newer Rich versions that store a stack of displays.
live_stack = getattr(console, "_live_stack", None)

if live_stack:
    while live_stack:
        active_live = live_stack[-1]

        try:
            active_live.stop()
        except Exception:
            try:
                console.clear_live()
            except Exception:
                break

print("Rich live display cleared.")

Rich live display cleared.

In [11]:
hub_checkpoint_callback = (
    HubCheckpointCallback(
        repo_id=(
            "KaptainKris/"
            "ppo-LunarLander-v3-flip"
        ),
        every_timesteps=1_000_000,
    )
)

#### Train Phase A (flip)

In [12]:
phase_a_run = train_ppo_experiment(
    experiment_name=(
        "ppo_lunarlander_flip_phase_a"
    ),
    total_timesteps=10_000_000,

    env_factory=(
        make_flip_acquisition_lander
    ),

    n_envs=16,
    seed=42,

    actor_layers=(128, 128),
    critic_layers=(128, 128),

    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    n_epochs=4,
    gamma=0.999,
    gae_lambda=0.98,
    ent_coef=0.03,
    clip_range=0.2,

    eval_every_timesteps=50_000,
    checkpoint_every_timesteps=100_000,
    n_eval_episodes=20,

    extra_callbacks=[
        hub_checkpoint_callback
    ],

    device="cpu",
)

Using cpu device

<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning:
datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects
to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 90.8     |
|    ep_rew_mean     | -110     |
| time/              |          |
|    fps             | 3152     |
|    iterations      | 1        |
|    time_elapsed    | 5        |
|    total_timesteps | 16384    |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 95          |
|    ep_rew_mean          | -78.7       |
| time/                   |             |
|    fps                  | 2134        |
|    iterations           | 2           |
|    time_elapsed         | 15          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.011606754 |
|    clip_fraction        | 0.0868      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.38       |
|    explained_variance   | 0.00352     |
|    learning_rate        | 0.0003      |
|    loss                 | 379         |
|    n_updates            | 4           |
|    policy_gradient_loss | -0.00325    |
|    value_loss           | 1.4e+03     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 92.2        |
|    ep_rew_mean          | -61         |
| time/                   |             |
|    fps                  | 1924        |
|    iterations           | 3           |
|    time_elapsed         | 25          |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.011221902 |
|    clip_fraction        | 0.128       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.35       |
|    explained_variance   | 0.58        |
|    learning_rate        | 0.0003      |
|    loss                 | 134         |
|    n_updates            | 8           |
|    policy_gradient_loss | -0.00592    |
|    value_loss           | 373         |
-----------------------------------------

Eval num_timesteps=50000, episode_reward=51.03 +/- 223.32

Episode length: 69.00 +/- 19.37

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 69          |
|    mean_reward          | 51          |
| time/                   |             |
|    total_timesteps      | 50000       |
| train/                  |             |
|    approx_kl            | 0.011082446 |
|    clip_fraction        | 0.145       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.31       |
|    explained_variance   | 0.766       |
|    learning_rate        | 0.0003      |
|    loss                 | 51.1        |
|    n_updates            | 12          |
|    policy_gradient_loss | -0.0106     |
|    value_loss           | 156         |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 102      |
|    ep_rew_mean     | -36      |
| time/              |          |
|    fps             | 1796     |
|    iterations      | 4        |
|    time_elapsed    | 36       |
|    total_timesteps | 65536    |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 87.5        |
|    ep_rew_mean          | -20         |
| time/                   |             |
|    fps                  | 1779        |
|    iterations           | 5           |
|    time_elapsed         | 46          |
|    total_timesteps      | 81920       |
| train/                  |             |
|    approx_kl            | 0.011614483 |
|    clip_fraction        | 0.126       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.24       |
|    explained_variance   | 0.824       |
|    learning_rate        | 0.0003      |
|    loss                 | 50.5        |
|    n_updates            | 16          |
|    policy_gradient_loss | -0.0107     |
|    value_loss           | 130         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 89.1        |
|    ep_rew_mean          | 37.6        |
| time/                   |             |
|    fps                  | 1749        |
|    iterations           | 6           |
|    time_elapsed         | 56          |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.010522922 |
|    clip_fraction        | 0.128       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.17       |
|    explained_variance   | 0.474       |
|    learning_rate        | 0.0003      |
|    loss                 | 70.8        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0077     |
|    value_loss           | 915         |
-----------------------------------------

Eval num_timesteps=100000, episode_reward=54.52 +/- 169.56

Episode length: 76.90 +/- 43.80

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 90.6     |
|    ep_rew_mean     | 48.2     |
| time/              |          |
|    fps             | 1654     |
|    iterations      | 7        |
|    time_elapsed    | 69       |
|    total_timesteps | 114688   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 96.6        |
|    ep_rew_mean          | 64.1        |
| time/                   |             |
|    fps                  | 1644        |
|    iterations           | 8           |
|    time_elapsed         | 79          |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.003520697 |
|    clip_fraction        | 0.00502     |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | 0.64        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.4e+03     |
|    n_updates            | 28          |
|    policy_gradient_loss | -0.00191    |
|    value_loss           | 4.06e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 96           |
|    ep_rew_mean          | 102          |
| time/                   |              |
|    fps                  | 1657         |
|    iterations           | 9            |
|    time_elapsed         | 88           |
|    total_timesteps      | 147456       |
| train/                  |              |
|    approx_kl            | 0.0031384102 |
|    clip_fraction        | 0.00299      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.06        |
|    explained_variance   | 0.645        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 32           |
|    policy_gradient_loss | -0.00118     |
|    value_loss           | 4.6e+03      |
------------------------------------------

Eval num_timesteps=150000, episode_reward=-210.21 +/- 69.10

Episode length: 118.25 +/- 41.23

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | -210         |
| time/                   |              |
|    total_timesteps      | 150000       |
| train/                  |              |
|    approx_kl            | 0.0025022817 |
|    clip_fraction        | 0.00214      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.724        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.37e+03     |
|    n_updates            | 36           |
|    policy_gradient_loss | -0.000227    |
|    value_loss           | 4.83e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 100      |
|    ep_rew_mean     | 71.4     |
| time/              |          |
|    fps             | 1622     |
|    iterations      | 10       |
|    time_elapsed    | 100      |
|    total_timesteps | 163840   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 102          |
|    ep_rew_mean          | 111          |
| time/                   |              |
|    fps                  | 1622         |
|    iterations           | 11           |
|    time_elapsed         | 111          |
|    total_timesteps      | 180224       |
| train/                  |              |
|    approx_kl            | 0.0015073402 |
|    clip_fraction        | 0.00502      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.03        |
|    explained_variance   | 0.696        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.31e+03     |
|    n_updates            | 40           |
|    policy_gradient_loss | 0.000178     |
|    value_loss           | 4.3e+03      |
------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 95.3          |
|    ep_rew_mean          | 92.2          |
| time/                   |               |
|    fps                  | 1621          |
|    iterations           | 12            |
|    time_elapsed         | 121           |
|    total_timesteps      | 196608        |
| train/                  |               |
|    approx_kl            | 0.00075570284 |
|    clip_fraction        | 0.000626      |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.994        |
|    explained_variance   | 0.752         |
|    learning_rate        | 0.0003        |
|    loss                 | 1.99e+03      |
|    n_updates            | 44            |
|    policy_gradient_loss | -0.000483     |
|    value_loss           | 5.27e+03      |
-------------------------------------------

Eval num_timesteps=200000, episode_reward=-156.63 +/- 233.69

Episode length: 131.60 +/- 84.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | -157         |
| time/                   |              |
|    total_timesteps      | 200000       |
| train/                  |              |
|    approx_kl            | 0.0016335575 |
|    clip_fraction        | 0.00243      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.972       |
|    explained_variance   | 0.807        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.13e+03     |
|    n_updates            | 48           |
|    policy_gradient_loss | -0.000768    |
|    value_loss           | 4.52e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 103      |
|    ep_rew_mean     | 87.1     |
| time/              |          |
|    fps             | 1594     |
|    iterations      | 13       |
|    time_elapsed    | 133      |
|    total_timesteps | 212992   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 116          |
| time/                   |              |
|    fps                  | 1602         |
|    iterations           | 14           |
|    time_elapsed         | 143          |
|    total_timesteps      | 229376       |
| train/                  |              |
|    approx_kl            | 0.0020732267 |
|    clip_fraction        | 0.00415      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.985       |
|    explained_variance   | 0.771        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.38e+03     |
|    n_updates            | 52           |
|    policy_gradient_loss | -0.000576    |
|    value_loss           | 6.34e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 83.1        |
| time/                   |             |
|    fps                  | 1605        |
|    iterations           | 15          |
|    time_elapsed         | 153         |
|    total_timesteps      | 245760      |
| train/                  |             |
|    approx_kl            | 0.005838505 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.97       |
|    explained_variance   | 0.774       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.55e+03    |
|    n_updates            | 56          |
|    policy_gradient_loss | -0.000105   |
|    value_loss           | 6.45e+03    |
-----------------------------------------

Eval num_timesteps=250000, episode_reward=-177.63 +/- 88.17

Episode length: 107.50 +/- 38.70

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | -178         |
| time/                   |              |
|    total_timesteps      | 250000       |
| train/                  |              |
|    approx_kl            | 0.0045632846 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.993       |
|    explained_variance   | 0.75         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.37e+03     |
|    n_updates            | 60           |
|    policy_gradient_loss | -0.000406    |
|    value_loss           | 6.84e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 66.9     |
| time/              |          |
|    fps             | 1588     |
|    iterations      | 16       |
|    time_elapsed    | 165      |
|    total_timesteps | 262144   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 72.9         |
| time/                   |              |
|    fps                  | 1590         |
|    iterations           | 17           |
|    time_elapsed         | 175          |
|    total_timesteps      | 278528       |
| train/                  |              |
|    approx_kl            | 0.0061135488 |
|    clip_fraction        | 0.0222       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1           |
|    explained_variance   | 0.765        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.63e+03     |
|    n_updates            | 64           |
|    policy_gradient_loss | -0.00217     |
|    value_loss           | 5.61e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 100          |
|    ep_rew_mean          | 62.3         |
| time/                   |              |
|    fps                  | 1595         |
|    iterations           | 18           |
|    time_elapsed         | 184          |
|    total_timesteps      | 294912       |
| train/                  |              |
|    approx_kl            | 0.0032733907 |
|    clip_fraction        | 0.00598      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.04        |
|    explained_variance   | 0.803        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.79e+03     |
|    n_updates            | 68           |
|    policy_gradient_loss | -0.00045     |
|    value_loss           | 5.3e+03      |
------------------------------------------

Eval num_timesteps=300000, episode_reward=-134.89 +/- 173.87

Episode length: 113.25 +/- 41.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | -135         |
| time/                   |              |
|    total_timesteps      | 300000       |
| train/                  |              |
|    approx_kl            | 0.0016178177 |
|    clip_fraction        | 0.000351     |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.841        |
|    learning_rate        | 0.0003       |
|    loss                 | 826          |
|    n_updates            | 72           |
|    policy_gradient_loss | -0.000458    |
|    value_loss           | 3.41e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 109      |
|    ep_rew_mean     | 96.9     |
| time/              |          |
|    fps             | 1584     |
|    iterations      | 19       |
|    time_elapsed    | 196      |
|    total_timesteps | 311296   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 107          |
|    ep_rew_mean          | 158          |
| time/                   |              |
|    fps                  | 1586         |
|    iterations           | 20           |
|    time_elapsed         | 206          |
|    total_timesteps      | 327680       |
| train/                  |              |
|    approx_kl            | 0.0010453891 |
|    clip_fraction        | 3.05e-05     |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.01        |
|    explained_variance   | 0.815        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.73e+03     |
|    n_updates            | 76           |
|    policy_gradient_loss | -0.000817    |
|    value_loss           | 5.06e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 82           |
| time/                   |              |
|    fps                  | 1586         |
|    iterations           | 21           |
|    time_elapsed         | 216          |
|    total_timesteps      | 344064       |
| train/                  |              |
|    approx_kl            | 0.0017447971 |
|    clip_fraction        | 0.00183      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1           |
|    explained_variance   | 0.828        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.27e+03     |
|    n_updates            | 80           |
|    policy_gradient_loss | -0.000293    |
|    value_loss           | 4.23e+03     |
------------------------------------------

Eval num_timesteps=350000, episode_reward=-9.02 +/- 258.27

Episode length: 104.30 +/- 42.42

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | -9.02       |
| time/                   |             |
|    total_timesteps      | 350000      |
| train/                  |             |
|    approx_kl            | 0.002787094 |
|    clip_fraction        | 0.0137      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1          |
|    explained_variance   | 0.81        |
|    learning_rate        | 0.0003      |
|    loss                 | 2.36e+03    |
|    n_updates            | 84          |
|    policy_gradient_loss | -0.000857   |
|    value_loss           | 4.32e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 106      |
|    ep_rew_mean     | 113      |
| time/              |          |
|    fps             | 1575     |
|    iterations      | 22       |
|    time_elapsed    | 228      |
|    total_timesteps | 360448   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 97.8         |
|    ep_rew_mean          | 132          |
| time/                   |              |
|    fps                  | 1577         |
|    iterations           | 23           |
|    time_elapsed         | 238          |
|    total_timesteps      | 376832       |
| train/                  |              |
|    approx_kl            | 0.0018797554 |
|    clip_fraction        | 6.1e-05      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.01        |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.18e+03     |
|    n_updates            | 88           |
|    policy_gradient_loss | -0.000623    |
|    value_loss           | 3.56e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 96.8         |
|    ep_rew_mean          | 102          |
| time/                   |              |
|    fps                  | 1583         |
|    iterations           | 24           |
|    time_elapsed         | 248          |
|    total_timesteps      | 393216       |
| train/                  |              |
|    approx_kl            | 0.0027632166 |
|    clip_fraction        | 0.00272      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.03        |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.38e+03     |
|    n_updates            | 92           |
|    policy_gradient_loss | -0.000187    |
|    value_loss           | 3.83e+03     |
------------------------------------------

Eval num_timesteps=400000, episode_reward=-104.70 +/- 234.21

Episode length: 113.85 +/- 44.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | -105         |
| time/                   |              |
|    total_timesteps      | 400000       |
| train/                  |              |
|    approx_kl            | 0.0061314167 |
|    clip_fraction        | 0.00528      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.02        |
|    explained_variance   | 0.866        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.61e+03     |
|    n_updates            | 96           |
|    policy_gradient_loss | -0.0021      |
|    value_loss           | 3.69e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 108      |
|    ep_rew_mean     | 116      |
| time/              |          |
|    fps             | 1571     |
|    iterations      | 25       |
|    time_elapsed    | 260      |
|    total_timesteps | 409600   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 124          |
| time/                   |              |
|    fps                  | 1570         |
|    iterations           | 26           |
|    time_elapsed         | 271          |
|    total_timesteps      | 425984       |
| train/                  |              |
|    approx_kl            | 0.0049298992 |
|    clip_fraction        | 0.00273      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.976       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.47e+03     |
|    n_updates            | 100          |
|    policy_gradient_loss | -0.00191     |
|    value_loss           | 4.47e+03     |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 107        |
|    ep_rew_mean          | 79.8       |
| time/                   |            |
|    fps                  | 1570       |
|    iterations           | 27         |
|    time_elapsed         | 281        |
|    total_timesteps      | 442368     |
| train/                  |            |
|    approx_kl            | 0.00454221 |
|    clip_fraction        | 0.0186     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.962     |
|    explained_variance   | 0.845      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.91e+03   |
|    n_updates            | 104        |
|    policy_gradient_loss | -0.000562  |
|    value_loss           | 5.96e+03   |
----------------------------------------

Eval num_timesteps=450000, episode_reward=-52.76 +/- 302.36

Episode length: 133.50 +/- 91.17

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 134          |
|    mean_reward          | -52.8        |
| time/                   |              |
|    total_timesteps      | 450000       |
| train/                  |              |
|    approx_kl            | 0.0019148102 |
|    clip_fraction        | 0.00107      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.987       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.52e+03     |
|    n_updates            | 108          |
|    policy_gradient_loss | 0.000352     |
|    value_loss           | 4.09e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 113      |
|    ep_rew_mean     | 155      |
| time/              |          |
|    fps             | 1558     |
|    iterations      | 28       |
|    time_elapsed    | 294      |
|    total_timesteps | 458752   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 104         |
|    ep_rew_mean          | 110         |
| time/                   |             |
|    fps                  | 1563        |
|    iterations           | 29          |
|    time_elapsed         | 303         |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.003561828 |
|    clip_fraction        | 0.00473     |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.02       |
|    explained_variance   | 0.859       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.77e+03    |
|    n_updates            | 112         |
|    policy_gradient_loss | -0.000579   |
|    value_loss           | 4.04e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 101         |
|    ep_rew_mean          | 121         |
| time/                   |             |
|    fps                  | 1565        |
|    iterations           | 30          |
|    time_elapsed         | 314         |
|    total_timesteps      | 491520      |
| train/                  |             |
|    approx_kl            | 0.002555755 |
|    clip_fraction        | 0.00618     |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.03e+03    |
|    n_updates            | 116         |
|    policy_gradient_loss | -0.0013     |
|    value_loss           | 3.69e+03    |
-----------------------------------------

Eval num_timesteps=500000, episode_reward=-88.80 +/- 286.46

Episode length: 137.80 +/- 56.19

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 138         |
|    mean_reward          | -88.8       |
| time/                   |             |
|    total_timesteps      | 500000      |
| train/                  |             |
|    approx_kl            | 0.005997313 |
|    clip_fraction        | 0.0105      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | 0.863       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.52e+03    |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00173    |
|    value_loss           | 4.08e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 113      |
|    ep_rew_mean     | 161      |
| time/              |          |
|    fps             | 1554     |
|    iterations      | 31       |
|    time_elapsed    | 326      |
|    total_timesteps | 507904   |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 120        |
|    ep_rew_mean          | 137        |
| time/                   |            |
|    fps                  | 1556       |
|    iterations           | 32         |
|    time_elapsed         | 336        |
|    total_timesteps      | 524288     |
| train/                  |            |
|    approx_kl            | 0.00282596 |
|    clip_fraction        | 0.00301    |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.01      |
|    explained_variance   | 0.857      |
|    learning_rate        | 0.0003     |
|    loss                 | 3.22e+03   |
|    n_updates            | 124        |
|    policy_gradient_loss | -0.00162   |
|    value_loss           | 4.47e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 135          |
| time/                   |              |
|    fps                  | 1559         |
|    iterations           | 33           |
|    time_elapsed         | 346          |
|    total_timesteps      | 540672       |
| train/                  |              |
|    approx_kl            | 0.0034036175 |
|    clip_fraction        | 0.000854     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.975       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.53e+03     |
|    n_updates            | 128          |
|    policy_gradient_loss | -0.00131     |
|    value_loss           | 3.8e+03      |
------------------------------------------

Eval num_timesteps=550000, episode_reward=-40.87 +/- 267.43

Episode length: 102.85 +/- 63.47

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | -40.9        |
| time/                   |              |
|    total_timesteps      | 550000       |
| train/                  |              |
|    approx_kl            | 0.0019995766 |
|    clip_fraction        | 4.58e-05     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.974       |
|    explained_variance   | 0.853        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.43e+03     |
|    n_updates            | 132          |
|    policy_gradient_loss | -0.000413    |
|    value_loss           | 5.04e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 111      |
|    ep_rew_mean     | 127      |
| time/              |          |
|    fps             | 1555     |
|    iterations      | 34       |
|    time_elapsed    | 358      |
|    total_timesteps | 557056   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 107          |
|    ep_rew_mean          | 172          |
| time/                   |              |
|    fps                  | 1557         |
|    iterations           | 35           |
|    time_elapsed         | 368          |
|    total_timesteps      | 573440       |
| train/                  |              |
|    approx_kl            | 0.0037801263 |
|    clip_fraction        | 0.00671      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.998       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11e+03     |
|    n_updates            | 136          |
|    policy_gradient_loss | -0.000281    |
|    value_loss           | 3.19e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 110          |
|    ep_rew_mean          | 151          |
| time/                   |              |
|    fps                  | 1558         |
|    iterations           | 36           |
|    time_elapsed         | 378          |
|    total_timesteps      | 589824       |
| train/                  |              |
|    approx_kl            | 0.0056031416 |
|    clip_fraction        | 0.00462      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.992       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.00166     |
|    value_loss           | 4.03e+03     |
------------------------------------------

Eval num_timesteps=600000, episode_reward=-311.92 +/- 759.47

Episode length: 125.75 +/- 80.01

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | -312         |
| time/                   |              |
|    total_timesteps      | 600000       |
| train/                  |              |
|    approx_kl            | 0.0021499912 |
|    clip_fraction        | 0.00217      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.97        |
|    explained_variance   | 0.895        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.53e+03     |
|    n_updates            | 144          |
|    policy_gradient_loss | -0.000771    |
|    value_loss           | 3.39e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 105      |
|    ep_rew_mean     | 176      |
| time/              |          |
|    fps             | 1549     |
|    iterations      | 37       |
|    time_elapsed    | 391      |
|    total_timesteps | 606208   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 148          |
| time/                   |              |
|    fps                  | 1549         |
|    iterations           | 38           |
|    time_elapsed         | 401          |
|    total_timesteps      | 622592       |
| train/                  |              |
|    approx_kl            | 0.0058527403 |
|    clip_fraction        | 0.00591      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.951       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.7e+03      |
|    n_updates            | 148          |
|    policy_gradient_loss | -0.00211     |
|    value_loss           | 3.69e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 165          |
| time/                   |              |
|    fps                  | 1554         |
|    iterations           | 39           |
|    time_elapsed         | 410          |
|    total_timesteps      | 638976       |
| train/                  |              |
|    approx_kl            | 0.0018760532 |
|    clip_fraction        | 0.00218      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.925       |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.64e+03     |
|    n_updates            | 152          |
|    policy_gradient_loss | 8.35e-05     |
|    value_loss           | 4.42e+03     |
------------------------------------------

Eval num_timesteps=650000, episode_reward=-44.71 +/- 283.45

Episode length: 114.65 +/- 45.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 115          |
|    mean_reward          | -44.7        |
| time/                   |              |
|    total_timesteps      | 650000       |
| train/                  |              |
|    approx_kl            | 0.0028869302 |
|    clip_fraction        | 0.00328      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.933       |
|    explained_variance   | 0.892        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.85e+03     |
|    n_updates            | 156          |
|    policy_gradient_loss | -0.000233    |
|    value_loss           | 4.61e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 136      |
| time/              |          |
|    fps             | 1548     |
|    iterations      | 40       |
|    time_elapsed    | 423      |
|    total_timesteps | 655360   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 116          |
| time/                   |              |
|    fps                  | 1548         |
|    iterations           | 41           |
|    time_elapsed         | 433          |
|    total_timesteps      | 671744       |
| train/                  |              |
|    approx_kl            | 0.0039016437 |
|    clip_fraction        | 0.00201      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.969       |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.89e+03     |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.000149    |
|    value_loss           | 4.65e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 205          |
| time/                   |              |
|    fps                  | 1548         |
|    iterations           | 42           |
|    time_elapsed         | 444          |
|    total_timesteps      | 688128       |
| train/                  |              |
|    approx_kl            | 0.0033880412 |
|    clip_fraction        | 0.00775      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.964       |
|    explained_variance   | 0.874        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.8e+03      |
|    n_updates            | 164          |
|    policy_gradient_loss | -0.000564    |
|    value_loss           | 3.6e+03      |
------------------------------------------

Eval num_timesteps=700000, episode_reward=63.81 +/- 278.64

Episode length: 96.15 +/- 43.08

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.2         |
|    mean_reward          | 63.8         |
| time/                   |              |
|    total_timesteps      | 700000       |
| train/                  |              |
|    approx_kl            | 0.0019804728 |
|    clip_fraction        | 0.0025       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.988       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 519          |
|    n_updates            | 168          |
|    policy_gradient_loss | -0.000244    |
|    value_loss           | 3.57e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 173      |
| time/              |          |
|    fps             | 1543     |
|    iterations      | 43       |
|    time_elapsed    | 456      |
|    total_timesteps | 704512   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 160         |
| time/                   |             |
|    fps                  | 1547        |
|    iterations           | 45          |
|    time_elapsed         | 476         |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.004696265 |
|    clip_fraction        | 0.00375     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.992      |
|    explained_variance   | 0.897       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.32e+03    |
|    n_updates            | 176         |
|    policy_gradient_loss | -0.000519   |
|    value_loss           | 3.51e+03    |
-----------------------------------------

Eval num_timesteps=750000, episode_reward=-0.21 +/- 264.05

Episode length: 112.15 +/- 56.57

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -0.206       |
| time/                   |              |
|    total_timesteps      | 750000       |
| train/                  |              |
|    approx_kl            | 0.0040521547 |
|    clip_fraction        | 0.0069       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.968       |
|    explained_variance   | 0.846        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.12e+03     |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.00178     |
|    value_loss           | 4.41e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 109      |
|    ep_rew_mean     | 140      |
| time/              |          |
|    fps             | 1542     |
|    iterations      | 46       |
|    time_elapsed    | 488      |
|    total_timesteps | 753664   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 182          |
| time/                   |              |
|    fps                  | 1542         |
|    iterations           | 47           |
|    time_elapsed         | 499          |
|    total_timesteps      | 770048       |
| train/                  |              |
|    approx_kl            | 0.0045548235 |
|    clip_fraction        | 0.0142       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.966       |
|    explained_variance   | 0.891        |
|    learning_rate        | 0.0003       |
|    loss                 | 729          |
|    n_updates            | 184          |
|    policy_gradient_loss | -0.00224     |
|    value_loss           | 3.12e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 194          |
| time/                   |              |
|    fps                  | 1542         |
|    iterations           | 48           |
|    time_elapsed         | 509          |
|    total_timesteps      | 786432       |
| train/                  |              |
|    approx_kl            | 0.0007078955 |
|    clip_fraction        | 1.53e-05     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.931       |
|    explained_variance   | 0.828        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.72e+03     |
|    n_updates            | 188          |
|    policy_gradient_loss | -6.16e-05    |
|    value_loss           | 5.73e+03     |
------------------------------------------

Eval num_timesteps=800000, episode_reward=-60.74 +/- 353.77

Episode length: 134.90 +/- 77.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 135          |
|    mean_reward          | -60.7        |
| time/                   |              |
|    total_timesteps      | 800000       |
| train/                  |              |
|    approx_kl            | 0.0030065097 |
|    clip_fraction        | 0.00824      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | 0.867        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.46e+03     |
|    n_updates            | 192          |
|    policy_gradient_loss | -0.00202     |
|    value_loss           | 4.52e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 209      |
| time/              |          |
|    fps             | 1537     |
|    iterations      | 49       |
|    time_elapsed    | 522      |
|    total_timesteps | 802816   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 112         |
|    ep_rew_mean          | 204         |
| time/                   |             |
|    fps                  | 1542        |
|    iterations           | 50          |
|    time_elapsed         | 531         |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.003529673 |
|    clip_fraction        | 0.00446     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.933      |
|    explained_variance   | 0.872       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.62e+03    |
|    n_updates            | 196         |
|    policy_gradient_loss | -0.000246   |
|    value_loss           | 4.21e+03    |
-----------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 126           |
|    ep_rew_mean          | 196           |
| time/                   |               |
|    fps                  | 1543          |
|    iterations           | 51            |
|    time_elapsed         | 541           |
|    total_timesteps      | 835584        |
| train/                  |               |
|    approx_kl            | 0.00086346536 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.965        |
|    explained_variance   | 0.872         |
|    learning_rate        | 0.0003        |
|    loss                 | 1.21e+03      |
|    n_updates            | 200           |
|    policy_gradient_loss | 0.000121      |
|    value_loss           | 4.35e+03      |
-------------------------------------------

Eval num_timesteps=850000, episode_reward=41.02 +/- 333.59

Episode length: 105.95 +/- 40.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 106          |
|    mean_reward          | 41           |
| time/                   |              |
|    total_timesteps      | 850000       |
| train/                  |              |
|    approx_kl            | 0.0025124114 |
|    clip_fraction        | 0.00182      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.959       |
|    explained_variance   | 0.891        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.33e+03     |
|    n_updates            | 204          |
|    policy_gradient_loss | -0.000359    |
|    value_loss           | 4.47e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 113      |
|    ep_rew_mean     | 213      |
| time/              |          |
|    fps             | 1538     |
|    iterations      | 52       |
|    time_elapsed    | 553      |
|    total_timesteps | 851968   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 108          |
|    ep_rew_mean          | 194          |
| time/                   |              |
|    fps                  | 1539         |
|    iterations           | 53           |
|    time_elapsed         | 564          |
|    total_timesteps      | 868352       |
| train/                  |              |
|    approx_kl            | 0.0030743796 |
|    clip_fraction        | 0.00455      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.948       |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.01e+03     |
|    n_updates            | 208          |
|    policy_gradient_loss | -0.00116     |
|    value_loss           | 5.01e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 114         |
|    ep_rew_mean          | 166         |
| time/                   |             |
|    fps                  | 1541        |
|    iterations           | 54          |
|    time_elapsed         | 574         |
|    total_timesteps      | 884736      |
| train/                  |             |
|    approx_kl            | 0.006084645 |
|    clip_fraction        | 0.0131      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.952      |
|    explained_variance   | 0.902       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.09e+03    |
|    n_updates            | 212         |
|    policy_gradient_loss | -0.00193    |
|    value_loss           | 3.67e+03    |
-----------------------------------------

Eval num_timesteps=900000, episode_reward=-87.56 +/- 308.21

Episode length: 147.75 +/- 84.17

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 148          |
|    mean_reward          | -87.6        |
| time/                   |              |
|    total_timesteps      | 900000       |
| train/                  |              |
|    approx_kl            | 0.0058476264 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.952       |
|    explained_variance   | 0.897        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45e+03     |
|    n_updates            | 216          |
|    policy_gradient_loss | -0.000775    |
|    value_loss           | 3.71e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 208      |
| time/              |          |
|    fps             | 1535     |
|    iterations      | 55       |
|    time_elapsed    | 586      |
|    total_timesteps | 901120   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 154          |
| time/                   |              |
|    fps                  | 1538         |
|    iterations           | 56           |
|    time_elapsed         | 596          |
|    total_timesteps      | 917504       |
| train/                  |              |
|    approx_kl            | 0.0023828293 |
|    clip_fraction        | 0.00285      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.952       |
|    explained_variance   | 0.871        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.36e+03     |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.000227    |
|    value_loss           | 4.44e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 189         |
| time/                   |             |
|    fps                  | 1538        |
|    iterations           | 57          |
|    time_elapsed         | 606         |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.003518334 |
|    clip_fraction        | 0.00371     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.948      |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.67e+03    |
|    n_updates            | 224         |
|    policy_gradient_loss | -0.0015     |
|    value_loss           | 4.38e+03    |
-----------------------------------------

Eval num_timesteps=950000, episode_reward=144.32 +/- 306.30

Episode length: 128.55 +/- 47.64

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 129          |
|    mean_reward          | 144          |
| time/                   |              |
|    total_timesteps      | 950000       |
| train/                  |              |
|    approx_kl            | 0.0043198275 |
|    clip_fraction        | 0.00473      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.93        |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 841          |
|    n_updates            | 228          |
|    policy_gradient_loss | -0.000674    |
|    value_loss           | 3.96e+03     |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 159      |
| time/              |          |
|    fps             | 1533     |
|    iterations      | 58       |
|    time_elapsed    | 619      |
|    total_timesteps | 950272   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 217          |
| time/                   |              |
|    fps                  | 1534         |
|    iterations           | 59           |
|    time_elapsed         | 629          |
|    total_timesteps      | 966656       |
| train/                  |              |
|    approx_kl            | 0.0034127547 |
|    clip_fraction        | 0.00517      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.93        |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 741          |
|    n_updates            | 232          |
|    policy_gradient_loss | -0.00152     |
|    value_loss           | 3.18e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 197         |
| time/                   |             |
|    fps                  | 1537        |
|    iterations           | 60          |
|    time_elapsed         | 639         |
|    total_timesteps      | 983040      |
| train/                  |             |
|    approx_kl            | 0.001580329 |
|    clip_fraction        | 0           |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.925      |
|    explained_variance   | 0.863       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.45e+03    |
|    n_updates            | 236         |
|    policy_gradient_loss | -0.000354   |
|    value_loss           | 4.03e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 110         |
|    ep_rew_mean          | 183         |
| time/                   |             |
|    fps                  | 1538        |
|    iterations           | 61          |
|    time_elapsed         | 649         |
|    total_timesteps      | 999424      |
| train/                  |             |
|    approx_kl            | 0.003185167 |
|    clip_fraction        | 0.000565    |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.929      |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.16e+03    |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.000152   |
|    value_loss           | 3.44e+03    |
-----------------------------------------

Eval num_timesteps=1000000, episode_reward=68.49 +/- 341.31

Episode length: 124.60 +/- 54.90

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 125          |
|    mean_reward          | 68.5         |
| time/                   |              |
|    total_timesteps      | 1000000      |
| train/                  |              |
|    approx_kl            | 0.0057297805 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.29e+03     |
|    n_updates            | 244          |
|    policy_gradient_loss | -0.00219     |
|    value_loss           | 4.07e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

Uploaded Hub checkpoint: 1,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 242      |
| time/              |          |
|    fps             | 1520     |
|    iterations      | 62       |
|    time_elapsed    | 667      |
|    total_timesteps | 1015808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 233          |
| time/                   |              |
|    fps                  | 1524         |
|    iterations           | 63           |
|    time_elapsed         | 677          |
|    total_timesteps      | 1032192      |
| train/                  |              |
|    approx_kl            | 0.0014134212 |
|    clip_fraction        | 0.000214     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.92        |
|    explained_variance   | 0.864        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.88e+03     |
|    n_updates            | 248          |
|    policy_gradient_loss | -4.14e-06    |
|    value_loss           | 4.93e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 216          |
| time/                   |              |
|    fps                  | 1525         |
|    iterations           | 64           |
|    time_elapsed         | 687          |
|    total_timesteps      | 1048576      |
| train/                  |              |
|    approx_kl            | 0.0075539295 |
|    clip_fraction        | 0.014        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.936       |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.35e+03     |
|    n_updates            | 252          |
|    policy_gradient_loss | -0.00214     |
|    value_loss           | 3.93e+03     |
------------------------------------------

Eval num_timesteps=1050000, episode_reward=-22.46 +/- 236.30

Episode length: 126.60 +/- 46.08

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 127         |
|    mean_reward          | -22.5       |
| time/                   |             |
|    total_timesteps      | 1050000     |
| train/                  |             |
|    approx_kl            | 0.004984528 |
|    clip_fraction        | 0.00636     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.913      |
|    explained_variance   | 0.872       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.47e+03    |
|    n_updates            | 256         |
|    policy_gradient_loss | -0.00112    |
|    value_loss           | 5.07e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 245      |
| time/              |          |
|    fps             | 1523     |
|    iterations      | 65       |
|    time_elapsed    | 699      |
|    total_timesteps | 1064960  |
---------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 120           |
|    ep_rew_mean          | 247           |
| time/                   |               |
|    fps                  | 1525          |
|    iterations           | 66            |
|    time_elapsed         | 708           |
|    total_timesteps      | 1081344       |
| train/                  |               |
|    approx_kl            | 0.00096731656 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.921        |
|    explained_variance   | 0.889         |
|    learning_rate        | 0.0003        |
|    loss                 | 1.85e+03      |
|    n_updates            | 260           |
|    policy_gradient_loss | 7.82e-06      |
|    value_loss           | 4.15e+03      |
-------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 114          |
|    ep_rew_mean          | 192          |
| time/                   |              |
|    fps                  | 1529         |
|    iterations           | 67           |
|    time_elapsed         | 717          |
|    total_timesteps      | 1097728      |
| train/                  |              |
|    approx_kl            | 0.0022092487 |
|    clip_fraction        | 0.000275     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.927       |
|    explained_variance   | 0.902        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28e+03     |
|    n_updates            | 264          |
|    policy_gradient_loss | -0.000295    |
|    value_loss           | 3.16e+03     |
------------------------------------------

Eval num_timesteps=1100000, episode_reward=200.05 +/- 331.39

Episode length: 110.25 +/- 39.76

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 200          |
| time/                   |              |
|    total_timesteps      | 1100000      |
| train/                  |              |
|    approx_kl            | 0.0026055234 |
|    clip_fraction        | 0.00764      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.899       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.46e+03     |
|    n_updates            | 268          |
|    policy_gradient_loss | -0.00176     |
|    value_loss           | 4.09e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 259      |
| time/              |          |
|    fps             | 1527     |
|    iterations      | 68       |
|    time_elapsed    | 729      |
|    total_timesteps | 1114112  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 243         |
| time/                   |             |
|    fps                  | 1529        |
|    iterations           | 69          |
|    time_elapsed         | 738         |
|    total_timesteps      | 1130496     |
| train/                  |             |
|    approx_kl            | 0.002135363 |
|    clip_fraction        | 0.00351     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.908      |
|    explained_variance   | 0.856       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.45e+03    |
|    n_updates            | 272         |
|    policy_gradient_loss | -0.000155   |
|    value_loss           | 4.88e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 238          |
| time/                   |              |
|    fps                  | 1532         |
|    iterations           | 70           |
|    time_elapsed         | 748          |
|    total_timesteps      | 1146880      |
| train/                  |              |
|    approx_kl            | 0.0062547135 |
|    clip_fraction        | 0.00525      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.902       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 945          |
|    n_updates            | 276          |
|    policy_gradient_loss | -0.00167     |
|    value_loss           | 3.4e+03      |
------------------------------------------

Eval num_timesteps=1150000, episode_reward=51.67 +/- 241.98

Episode length: 120.05 +/- 37.32

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 120         |
|    mean_reward          | 51.7        |
| time/                   |             |
|    total_timesteps      | 1150000     |
| train/                  |             |
|    approx_kl            | 0.005105457 |
|    clip_fraction        | 0.00789     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.933      |
|    explained_variance   | 0.886       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.45e+03    |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.000415   |
|    value_loss           | 4.11e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 208      |
| time/              |          |
|    fps             | 1532     |
|    iterations      | 71       |
|    time_elapsed    | 759      |
|    total_timesteps | 1163264  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 230          |
| time/                   |              |
|    fps                  | 1534         |
|    iterations           | 72           |
|    time_elapsed         | 768          |
|    total_timesteps      | 1179648      |
| train/                  |              |
|    approx_kl            | 0.0010127339 |
|    clip_fraction        | 0            |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.927       |
|    explained_variance   | 0.876        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.84e+03     |
|    n_updates            | 284          |
|    policy_gradient_loss | 0.000158     |
|    value_loss           | 3.96e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 257          |
| time/                   |              |
|    fps                  | 1536         |
|    iterations           | 73           |
|    time_elapsed         | 778          |
|    total_timesteps      | 1196032      |
| train/                  |              |
|    approx_kl            | 0.0025041923 |
|    clip_fraction        | 0.00148      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.903       |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.68e+03     |
|    n_updates            | 288          |
|    policy_gradient_loss | -0.000834    |
|    value_loss           | 4.98e+03     |
------------------------------------------

Eval num_timesteps=1200000, episode_reward=187.48 +/- 263.00

Episode length: 120.25 +/- 39.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 187          |
| time/                   |              |
|    total_timesteps      | 1200000      |
| train/                  |              |
|    approx_kl            | 0.0030772435 |
|    clip_fraction        | 0.0071       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.909       |
|    explained_variance   | 0.907        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.31e+03     |
|    n_updates            | 292          |
|    policy_gradient_loss | -0.000768    |
|    value_loss           | 3.19e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 226      |
| time/              |          |
|    fps             | 1533     |
|    iterations      | 74       |
|    time_elapsed    | 790      |
|    total_timesteps | 1212416  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 202          |
| time/                   |              |
|    fps                  | 1537         |
|    iterations           | 75           |
|    time_elapsed         | 799          |
|    total_timesteps      | 1228800      |
| train/                  |              |
|    approx_kl            | 0.0024231686 |
|    clip_fraction        | 0.0043       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.904       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.93e+03     |
|    n_updates            | 296          |
|    policy_gradient_loss | -0.00101     |
|    value_loss           | 4.15e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 205         |
| time/                   |             |
|    fps                  | 1539        |
|    iterations           | 76          |
|    time_elapsed         | 809         |
|    total_timesteps      | 1245184     |
| train/                  |             |
|    approx_kl            | 0.001295316 |
|    clip_fraction        | 0.000229    |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.886      |
|    explained_variance   | 0.894       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.81e+03    |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.000309   |
|    value_loss           | 3.7e+03     |
-----------------------------------------

Eval num_timesteps=1250000, episode_reward=193.95 +/- 338.12

Episode length: 120.65 +/- 44.38

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 121         |
|    mean_reward          | 194         |
| time/                   |             |
|    total_timesteps      | 1250000     |
| train/                  |             |
|    approx_kl            | 0.006036791 |
|    clip_fraction        | 0.0157      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.903      |
|    explained_variance   | 0.897       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.9e+03     |
|    n_updates            | 304         |
|    policy_gradient_loss | -0.00177    |
|    value_loss           | 3.88e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 215      |
| time/              |          |
|    fps             | 1537     |
|    iterations      | 77       |
|    time_elapsed    | 820      |
|    total_timesteps | 1261568  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 236          |
| time/                   |              |
|    fps                  | 1539         |
|    iterations           | 78           |
|    time_elapsed         | 830          |
|    total_timesteps      | 1277952      |
| train/                  |              |
|    approx_kl            | 0.0033051586 |
|    clip_fraction        | 0.000763     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.867        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.91e+03     |
|    n_updates            | 308          |
|    policy_gradient_loss | -0.000382    |
|    value_loss           | 4.21e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 249          |
| time/                   |              |
|    fps                  | 1542         |
|    iterations           | 79           |
|    time_elapsed         | 838          |
|    total_timesteps      | 1294336      |
| train/                  |              |
|    approx_kl            | 0.0019982776 |
|    clip_fraction        | 0.00926      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11e+03     |
|    n_updates            | 312          |
|    policy_gradient_loss | -0.00148     |
|    value_loss           | 4.38e+03     |
------------------------------------------

Eval num_timesteps=1300000, episode_reward=85.45 +/- 275.83

Episode length: 131.50 +/- 57.36

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 132        |
|    mean_reward          | 85.4       |
| time/                   |            |
|    total_timesteps      | 1300000    |
| train/                  |            |
|    approx_kl            | 0.00446738 |
|    clip_fraction        | 0.004      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.873     |
|    explained_variance   | 0.884      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.55e+03   |
|    n_updates            | 316        |
|    policy_gradient_loss | -0.00129   |
|    value_loss           | 3.27e+03   |
----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 241      |
| time/              |          |
|    fps             | 1540     |
|    iterations      | 80       |
|    time_elapsed    | 850      |
|    total_timesteps | 1310720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 226          |
| time/                   |              |
|    fps                  | 1541         |
|    iterations           | 81           |
|    time_elapsed         | 860          |
|    total_timesteps      | 1327104      |
| train/                  |              |
|    approx_kl            | 0.0011820989 |
|    clip_fraction        | 0.000305     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.866       |
|    explained_variance   | 0.866        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.8e+03      |
|    n_updates            | 320          |
|    policy_gradient_loss | -0.000177    |
|    value_loss           | 4.12e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 283          |
| time/                   |              |
|    fps                  | 1542         |
|    iterations           | 82           |
|    time_elapsed         | 870          |
|    total_timesteps      | 1343488      |
| train/                  |              |
|    approx_kl            | 0.0024044896 |
|    clip_fraction        | 0            |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.882        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 324          |
|    policy_gradient_loss | -0.000646    |
|    value_loss           | 4.42e+03     |
------------------------------------------

Eval num_timesteps=1350000, episode_reward=182.53 +/- 228.05

Episode length: 125.15 +/- 37.80

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 125          |
|    mean_reward          | 183          |
| time/                   |              |
|    total_timesteps      | 1350000      |
| train/                  |              |
|    approx_kl            | 0.0036168036 |
|    clip_fraction        | 0.0114       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.86        |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.5e+03      |
|    n_updates            | 328          |
|    policy_gradient_loss | -0.000794    |
|    value_loss           | 4.43e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 300      |
| time/              |          |
|    fps             | 1540     |
|    iterations      | 83       |
|    time_elapsed    | 882      |
|    total_timesteps | 1359872  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 256         |
| time/                   |             |
|    fps                  | 1543        |
|    iterations           | 84          |
|    time_elapsed         | 891         |
|    total_timesteps      | 1376256     |
| train/                  |             |
|    approx_kl            | 0.005402831 |
|    clip_fraction        | 0.00262     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.871      |
|    explained_variance   | 0.864       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.65e+03    |
|    n_updates            | 332         |
|    policy_gradient_loss | -0.00116    |
|    value_loss           | 4.55e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 235          |
| time/                   |              |
|    fps                  | 1544         |
|    iterations           | 85           |
|    time_elapsed         | 901          |
|    total_timesteps      | 1392640      |
| train/                  |              |
|    approx_kl            | 0.0043411804 |
|    clip_fraction        | 0.00322      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.07e+03     |
|    n_updates            | 336          |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 3.85e+03     |
------------------------------------------

Eval num_timesteps=1400000, episode_reward=218.08 +/- 252.79

Episode length: 137.70 +/- 40.17

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 138          |
|    mean_reward          | 218          |
| time/                   |              |
|    total_timesteps      | 1400000      |
| train/                  |              |
|    approx_kl            | 0.0012210757 |
|    clip_fraction        | 0.000107     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.822       |
|    explained_variance   | 0.852        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.16e+03     |
|    n_updates            | 340          |
|    policy_gradient_loss | -0.000623    |
|    value_loss           | 5.01e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 1542     |
|    iterations      | 86       |
|    time_elapsed    | 913      |
|    total_timesteps | 1409024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 270          |
| time/                   |              |
|    fps                  | 1543         |
|    iterations           | 87           |
|    time_elapsed         | 923          |
|    total_timesteps      | 1425408      |
| train/                  |              |
|    approx_kl            | 0.0011080299 |
|    clip_fraction        | 0.00313      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.46e+03     |
|    n_updates            | 344          |
|    policy_gradient_loss | 0.000246     |
|    value_loss           | 3.25e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 294          |
| time/                   |              |
|    fps                  | 1546         |
|    iterations           | 88           |
|    time_elapsed         | 932          |
|    total_timesteps      | 1441792      |
| train/                  |              |
|    approx_kl            | 0.0014678102 |
|    clip_fraction        | 0.00438      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.863       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.04e+03     |
|    n_updates            | 348          |
|    policy_gradient_loss | -0.000432    |
|    value_loss           | 3.7e+03      |
------------------------------------------

Eval num_timesteps=1450000, episode_reward=315.16 +/- 224.10

Episode length: 106.00 +/- 29.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | 315         |
| time/                   |             |
|    total_timesteps      | 1450000     |
| train/                  |             |
|    approx_kl            | 0.006446138 |
|    clip_fraction        | 0.00801     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.868      |
|    explained_variance   | 0.838       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.33e+03    |
|    n_updates            | 352         |
|    policy_gradient_loss | -0.00183    |
|    value_loss           | 5.29e+03    |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 264      |
| time/              |          |
|    fps             | 1544     |
|    iterations      | 89       |
|    time_elapsed    | 943      |
|    total_timesteps | 1458176  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 292          |
| time/                   |              |
|    fps                  | 1546         |
|    iterations           | 90           |
|    time_elapsed         | 953          |
|    total_timesteps      | 1474560      |
| train/                  |              |
|    approx_kl            | 0.0013026779 |
|    clip_fraction        | 1.53e-05     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.851       |
|    explained_variance   | 0.862        |
|    learning_rate        | 0.0003       |
|    loss                 | 857          |
|    n_updates            | 356          |
|    policy_gradient_loss | -0.000591    |
|    value_loss           | 4.16e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 244          |
| time/                   |              |
|    fps                  | 1547         |
|    iterations           | 91           |
|    time_elapsed         | 963          |
|    total_timesteps      | 1490944      |
| train/                  |              |
|    approx_kl            | 0.0059818774 |
|    clip_fraction        | 0.0181       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.864        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.22e+03     |
|    n_updates            | 360          |
|    policy_gradient_loss | -0.00202     |
|    value_loss           | 4.77e+03     |
------------------------------------------

Eval num_timesteps=1500000, episode_reward=159.61 +/- 269.97

Episode length: 111.25 +/- 28.77

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 111         |
|    mean_reward          | 160         |
| time/                   |             |
|    total_timesteps      | 1500000     |
| train/                  |             |
|    approx_kl            | 0.003394843 |
|    clip_fraction        | 0.014       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.861      |
|    explained_variance   | 0.889       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.39e+03    |
|    n_updates            | 364         |
|    policy_gradient_loss | -0.00063    |
|    value_loss           | 4.04e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 253      |
| time/              |          |
|    fps             | 1546     |
|    iterations      | 92       |
|    time_elapsed    | 974      |
|    total_timesteps | 1507328  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 310         |
| time/                   |             |
|    fps                  | 1548        |
|    iterations           | 93          |
|    time_elapsed         | 983         |
|    total_timesteps      | 1523712     |
| train/                  |             |
|    approx_kl            | 0.004457961 |
|    clip_fraction        | 0.00464     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.864      |
|    explained_variance   | 0.857       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.01e+03    |
|    n_updates            | 368         |
|    policy_gradient_loss | -0.000647   |
|    value_loss           | 4.95e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 291          |
| time/                   |              |
|    fps                  | 1549         |
|    iterations           | 94           |
|    time_elapsed         | 993          |
|    total_timesteps      | 1540096      |
| train/                  |              |
|    approx_kl            | 0.0054662675 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.832        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.65e+03     |
|    n_updates            | 372          |
|    policy_gradient_loss | -0.00402     |
|    value_loss           | 5.51e+03     |
------------------------------------------

Eval num_timesteps=1550000, episode_reward=251.55 +/- 237.42

Episode length: 129.00 +/- 36.92

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 129          |
|    mean_reward          | 252          |
| time/                   |              |
|    total_timesteps      | 1550000      |
| train/                  |              |
|    approx_kl            | 0.0026378161 |
|    clip_fraction        | 0.00748      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.866       |
|    explained_variance   | 0.902        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.78e+03     |
|    n_updates            | 376          |
|    policy_gradient_loss | 6.43e-05     |
|    value_loss           | 3.73e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 301      |
| time/              |          |
|    fps             | 1548     |
|    iterations      | 95       |
|    time_elapsed    | 1005     |
|    total_timesteps | 1556480  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 244         |
| time/                   |             |
|    fps                  | 1551        |
|    iterations           | 96          |
|    time_elapsed         | 1013        |
|    total_timesteps      | 1572864     |
| train/                  |             |
|    approx_kl            | 0.004269584 |
|    clip_fraction        | 0.0103      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.879      |
|    explained_variance   | 0.913       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.95e+03    |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.000664   |
|    value_loss           | 3.01e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 317         |
| time/                   |             |
|    fps                  | 1552        |
|    iterations           | 97          |
|    time_elapsed         | 1023        |
|    total_timesteps      | 1589248     |
| train/                  |             |
|    approx_kl            | 0.004464784 |
|    clip_fraction        | 0.00946     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.842       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.57e+03    |
|    n_updates            | 384         |
|    policy_gradient_loss | -0.00153    |
|    value_loss           | 5.74e+03    |
-----------------------------------------

Eval num_timesteps=1600000, episode_reward=333.07 +/- 223.49

Episode length: 135.50 +/- 29.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 136          |
|    mean_reward          | 333          |
| time/                   |              |
|    total_timesteps      | 1600000      |
| train/                  |              |
|    approx_kl            | 0.0051360186 |
|    clip_fraction        | 0.00696      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 895          |
|    n_updates            | 388          |
|    policy_gradient_loss | -0.00128     |
|    value_loss           | 3.94e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 244      |
| time/              |          |
|    fps             | 1550     |
|    iterations      | 98       |
|    time_elapsed    | 1035     |
|    total_timesteps | 1605632  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 284         |
| time/                   |             |
|    fps                  | 1551        |
|    iterations           | 99          |
|    time_elapsed         | 1045        |
|    total_timesteps      | 1622016     |
| train/                  |             |
|    approx_kl            | 0.001107027 |
|    clip_fraction        | 0           |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.855      |
|    explained_variance   | 0.839       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.13e+03    |
|    n_updates            | 392         |
|    policy_gradient_loss | -0.000339   |
|    value_loss           | 4.99e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 284          |
| time/                   |              |
|    fps                  | 1553         |
|    iterations           | 100          |
|    time_elapsed         | 1054         |
|    total_timesteps      | 1638400      |
| train/                  |              |
|    approx_kl            | 0.0032077539 |
|    clip_fraction        | 0.00439      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.845       |
|    explained_variance   | 0.884        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.97e+03     |
|    n_updates            | 396          |
|    policy_gradient_loss | -0.00134     |
|    value_loss           | 4.61e+03     |
------------------------------------------

Eval num_timesteps=1650000, episode_reward=351.34 +/- 225.99

Episode length: 122.95 +/- 28.76

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 123         |
|    mean_reward          | 351         |
| time/                   |             |
|    total_timesteps      | 1650000     |
| train/                  |             |
|    approx_kl            | 0.004640701 |
|    clip_fraction        | 0.0164      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.863      |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.94e+03    |
|    n_updates            | 400         |
|    policy_gradient_loss | -0.000815   |
|    value_loss           | 3.66e+03    |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 244      |
| time/              |          |
|    fps             | 1552     |
|    iterations      | 101      |
|    time_elapsed    | 1065     |
|    total_timesteps | 1654784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 287          |
| time/                   |              |
|    fps                  | 1553         |
|    iterations           | 102          |
|    time_elapsed         | 1075         |
|    total_timesteps      | 1671168      |
| train/                  |              |
|    approx_kl            | 0.0039656563 |
|    clip_fraction        | 0.0133       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.848       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 850          |
|    n_updates            | 404          |
|    policy_gradient_loss | -0.00281     |
|    value_loss           | 4.54e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 117         |
|    ep_rew_mean          | 272         |
| time/                   |             |
|    fps                  | 1554        |
|    iterations           | 103         |
|    time_elapsed         | 1085        |
|    total_timesteps      | 1687552     |
| train/                  |             |
|    approx_kl            | 0.002493289 |
|    clip_fraction        | 0.00392     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.831      |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | 568         |
|    n_updates            | 408         |
|    policy_gradient_loss | 0.000149    |
|    value_loss           | 3.05e+03    |
-----------------------------------------

Eval num_timesteps=1700000, episode_reward=231.03 +/- 290.92

Episode length: 106.65 +/- 27.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | 231          |
| time/                   |              |
|    total_timesteps      | 1700000      |
| train/                  |              |
|    approx_kl            | 0.0022758697 |
|    clip_fraction        | 0.00111      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.861        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.65e+03     |
|    n_updates            | 412          |
|    policy_gradient_loss | -0.000618    |
|    value_loss           | 4.82e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 257      |
| time/              |          |
|    fps             | 1554     |
|    iterations      | 104      |
|    time_elapsed    | 1096     |
|    total_timesteps | 1703936  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 329          |
| time/                   |              |
|    fps                  | 1555         |
|    iterations           | 105          |
|    time_elapsed         | 1105         |
|    total_timesteps      | 1720320      |
| train/                  |              |
|    approx_kl            | 0.0027922892 |
|    clip_fraction        | 0.000977     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.833       |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.36e+03     |
|    n_updates            | 416          |
|    policy_gradient_loss | -5.11e-05    |
|    value_loss           | 4.65e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 287          |
| time/                   |              |
|    fps                  | 1556         |
|    iterations           | 106          |
|    time_elapsed         | 1115         |
|    total_timesteps      | 1736704      |
| train/                  |              |
|    approx_kl            | 0.0017268877 |
|    clip_fraction        | 0.00116      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.82e+03     |
|    n_updates            | 420          |
|    policy_gradient_loss | -0.000807    |
|    value_loss           | 5.15e+03     |
------------------------------------------

Eval num_timesteps=1750000, episode_reward=148.86 +/- 274.79

Episode length: 119.45 +/- 38.03

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 149          |
| time/                   |              |
|    total_timesteps      | 1750000      |
| train/                  |              |
|    approx_kl            | 0.0045481436 |
|    clip_fraction        | 0.0148       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.806       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.54e+03     |
|    n_updates            | 424          |
|    policy_gradient_loss | -0.00149     |
|    value_loss           | 4.79e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 344      |
| time/              |          |
|    fps             | 1554     |
|    iterations      | 107      |
|    time_elapsed    | 1127     |
|    total_timesteps | 1753088  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 333          |
| time/                   |              |
|    fps                  | 1555         |
|    iterations           | 108          |
|    time_elapsed         | 1137         |
|    total_timesteps      | 1769472      |
| train/                  |              |
|    approx_kl            | 0.0046760794 |
|    clip_fraction        | 0.00377      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.846       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.78e+03     |
|    n_updates            | 428          |
|    policy_gradient_loss | -0.00139     |
|    value_loss           | 3.79e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 326          |
| time/                   |              |
|    fps                  | 1558         |
|    iterations           | 109          |
|    time_elapsed         | 1145         |
|    total_timesteps      | 1785856      |
| train/                  |              |
|    approx_kl            | 0.0058285277 |
|    clip_fraction        | 0.00847      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.838       |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.25e+03     |
|    n_updates            | 432          |
|    policy_gradient_loss | -0.00168     |
|    value_loss           | 4.66e+03     |
------------------------------------------

Eval num_timesteps=1800000, episode_reward=241.92 +/- 238.76

Episode length: 122.60 +/- 29.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 242          |
| time/                   |              |
|    total_timesteps      | 1800000      |
| train/                  |              |
|    approx_kl            | 0.0025488285 |
|    clip_fraction        | 0.00221      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.16e+03     |
|    n_updates            | 436          |
|    policy_gradient_loss | -0.000439    |
|    value_loss           | 4.38e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 324      |
| time/              |          |
|    fps             | 1557     |
|    iterations      | 110      |
|    time_elapsed    | 1157     |
|    total_timesteps | 1802240  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 1557        |
|    iterations           | 111         |
|    time_elapsed         | 1167        |
|    total_timesteps      | 1818624     |
| train/                  |             |
|    approx_kl            | 0.004069427 |
|    clip_fraction        | 0.012       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.824      |
|    explained_variance   | 0.871       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.38e+03    |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.00171    |
|    value_loss           | 4.47e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 334         |
| time/                   |             |
|    fps                  | 1559        |
|    iterations           | 112         |
|    time_elapsed         | 1176        |
|    total_timesteps      | 1835008     |
| train/                  |             |
|    approx_kl            | 0.003884913 |
|    clip_fraction        | 0.00955     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.828      |
|    explained_variance   | 0.859       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.81e+03    |
|    n_updates            | 444         |
|    policy_gradient_loss | -0.0019     |
|    value_loss           | 4.74e+03    |
-----------------------------------------

Eval num_timesteps=1850000, episode_reward=210.88 +/- 245.22

Episode length: 130.40 +/- 32.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 130         |
|    mean_reward          | 211         |
| time/                   |             |
|    total_timesteps      | 1850000     |
| train/                  |             |
|    approx_kl            | 0.005349341 |
|    clip_fraction        | 0.0147      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.838      |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.14e+03    |
|    n_updates            | 448         |
|    policy_gradient_loss | -0.00145    |
|    value_loss           | 5.17e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 1558     |
|    iterations      | 113      |
|    time_elapsed    | 1188     |
|    total_timesteps | 1851392  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 318         |
| time/                   |             |
|    fps                  | 1559        |
|    iterations           | 114         |
|    time_elapsed         | 1197        |
|    total_timesteps      | 1867776     |
| train/                  |             |
|    approx_kl            | 0.004090557 |
|    clip_fraction        | 0.0154      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.801      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.87e+03    |
|    n_updates            | 452         |
|    policy_gradient_loss | -0.00105    |
|    value_loss           | 3.89e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 117         |
|    ep_rew_mean          | 264         |
| time/                   |             |
|    fps                  | 1560        |
|    iterations           | 115         |
|    time_elapsed         | 1207        |
|    total_timesteps      | 1884160     |
| train/                  |             |
|    approx_kl            | 0.004333825 |
|    clip_fraction        | 0.00638     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.818      |
|    explained_variance   | 0.86        |
|    learning_rate        | 0.0003      |
|    loss                 | 2.06e+03    |
|    n_updates            | 456         |
|    policy_gradient_loss | -0.000698   |
|    value_loss           | 5.26e+03    |
-----------------------------------------

Eval num_timesteps=1900000, episode_reward=283.51 +/- 226.08

Episode length: 119.00 +/- 23.36

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 284          |
| time/                   |              |
|    total_timesteps      | 1900000      |
| train/                  |              |
|    approx_kl            | 0.0034646136 |
|    clip_fraction        | 0.0106       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.834       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.4e+03      |
|    n_updates            | 460          |
|    policy_gradient_loss | -0.00223     |
|    value_loss           | 5.68e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_1900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 285      |
| time/              |          |
|    fps             | 1559     |
|    iterations      | 116      |
|    time_elapsed    | 1218     |
|    total_timesteps | 1900544  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 311         |
| time/                   |             |
|    fps                  | 1561        |
|    iterations           | 117         |
|    time_elapsed         | 1227        |
|    total_timesteps      | 1916928     |
| train/                  |             |
|    approx_kl            | 0.005668343 |
|    clip_fraction        | 0.008       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.81       |
|    explained_variance   | 0.873       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.04e+03    |
|    n_updates            | 464         |
|    policy_gradient_loss | -0.00143    |
|    value_loss           | 5.01e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 270         |
| time/                   |             |
|    fps                  | 1562        |
|    iterations           | 118         |
|    time_elapsed         | 1237        |
|    total_timesteps      | 1933312     |
| train/                  |             |
|    approx_kl            | 0.004867389 |
|    clip_fraction        | 0.0196      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.803      |
|    explained_variance   | 0.887       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.72e+03    |
|    n_updates            | 468         |
|    policy_gradient_loss | -0.00112    |
|    value_loss           | 4.52e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 1563        |
|    iterations           | 119         |
|    time_elapsed         | 1246        |
|    total_timesteps      | 1949696     |
| train/                  |             |
|    approx_kl            | 0.004124031 |
|    clip_fraction        | 0.016       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.801      |
|    explained_variance   | 0.823       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.11e+03    |
|    n_updates            | 472         |
|    policy_gradient_loss | -0.00195    |
|    value_loss           | 6.11e+03    |
-----------------------------------------

Eval num_timesteps=1950000, episode_reward=302.15 +/- 221.69

Episode length: 120.35 +/- 33.17

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 120         |
|    mean_reward          | 302         |
| time/                   |             |
|    total_timesteps      | 1950000     |
| train/                  |             |
|    approx_kl            | 0.003195385 |
|    clip_fraction        | 0.00325     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.814      |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.79e+03    |
|    n_updates            | 476         |
|    policy_gradient_loss | -0.000776   |
|    value_loss           | 5.01e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 343      |
| time/              |          |
|    fps             | 1562     |
|    iterations      | 120      |
|    time_elapsed    | 1258     |
|    total_timesteps | 1966080  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 353         |
| time/                   |             |
|    fps                  | 1564        |
|    iterations           | 121         |
|    time_elapsed         | 1267        |
|    total_timesteps      | 1982464     |
| train/                  |             |
|    approx_kl            | 0.004476747 |
|    clip_fraction        | 0.0233      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.805      |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 497         |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.00155    |
|    value_loss           | 3.41e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 262          |
| time/                   |              |
|    fps                  | 1565         |
|    iterations           | 122          |
|    time_elapsed         | 1276         |
|    total_timesteps      | 1998848      |
| train/                  |              |
|    approx_kl            | 0.0050787292 |
|    clip_fraction        | 0.00987      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.861        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.72e+03     |
|    n_updates            | 484          |
|    policy_gradient_loss | -0.00196     |
|    value_loss           | 5.35e+03     |
------------------------------------------

Eval num_timesteps=2000000, episode_reward=226.12 +/- 285.32

Episode length: 115.30 +/- 31.47

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 115         |
|    mean_reward          | 226         |
| time/                   |             |
|    total_timesteps      | 2000000     |
| train/                  |             |
|    approx_kl            | 0.003026043 |
|    clip_fraction        | 0.00172     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.755      |
|    explained_variance   | 0.869       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.95e+03    |
|    n_updates            | 488         |
|    policy_gradient_loss | -0.000799   |
|    value_loss           | 5.16e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 2,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 307      |
| time/              |          |
|    fps             | 1558     |
|    iterations      | 123      |
|    time_elapsed    | 1293     |
|    total_timesteps | 2015232  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 344         |
| time/                   |             |
|    fps                  | 1559        |
|    iterations           | 124         |
|    time_elapsed         | 1302        |
|    total_timesteps      | 2031616     |
| train/                  |             |
|    approx_kl            | 0.001946286 |
|    clip_fraction        | 0.00795     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.774      |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | 898         |
|    n_updates            | 492         |
|    policy_gradient_loss | -0.000216   |
|    value_loss           | 4.1e+03     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 355          |
| time/                   |              |
|    fps                  | 1560         |
|    iterations           | 125          |
|    time_elapsed         | 1312         |
|    total_timesteps      | 2048000      |
| train/                  |              |
|    approx_kl            | 0.0034282769 |
|    clip_fraction        | 0.00206      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.95e+03     |
|    n_updates            | 496          |
|    policy_gradient_loss | -0.000801    |
|    value_loss           | 5.57e+03     |
------------------------------------------

Eval num_timesteps=2050000, episode_reward=300.11 +/- 231.22

Episode length: 124.85 +/- 30.50

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 125          |
|    mean_reward          | 300          |
| time/                   |              |
|    total_timesteps      | 2050000      |
| train/                  |              |
|    approx_kl            | 0.0015133704 |
|    clip_fraction        | 0.00223      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.59e+03     |
|    n_updates            | 500          |
|    policy_gradient_loss | -0.000531    |
|    value_loss           | 3.93e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 354      |
| time/              |          |
|    fps             | 1559     |
|    iterations      | 126      |
|    time_elapsed    | 1323     |
|    total_timesteps | 2064384  |
---------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 127           |
|    ep_rew_mean          | 344           |
| time/                   |               |
|    fps                  | 1561          |
|    iterations           | 127           |
|    time_elapsed         | 1332          |
|    total_timesteps      | 2080768       |
| train/                  |               |
|    approx_kl            | 0.00076251477 |
|    clip_fraction        | 0.00255       |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.78         |
|    explained_variance   | 0.872         |
|    learning_rate        | 0.0003        |
|    loss                 | 1.64e+03      |
|    n_updates            | 504           |
|    policy_gradient_loss | -8.37e-05     |
|    value_loss           | 4.37e+03      |
-------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 344         |
| time/                   |             |
|    fps                  | 1562        |
|    iterations           | 128         |
|    time_elapsed         | 1342        |
|    total_timesteps      | 2097152     |
| train/                  |             |
|    approx_kl            | 0.005747851 |
|    clip_fraction        | 0.0175      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | 0.893       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.12e+03    |
|    n_updates            | 508         |
|    policy_gradient_loss | -0.0013     |
|    value_loss           | 3.73e+03    |
-----------------------------------------

Eval num_timesteps=2100000, episode_reward=285.82 +/- 255.97

Episode length: 118.95 +/- 27.20

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 286          |
| time/                   |              |
|    total_timesteps      | 2100000      |
| train/                  |              |
|    approx_kl            | 0.0057030683 |
|    clip_fraction        | 0.0249       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.799       |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.14e+03     |
|    n_updates            | 512          |
|    policy_gradient_loss | -0.0016      |
|    value_loss           | 4.31e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 324      |
| time/              |          |
|    fps             | 1560     |
|    iterations      | 129      |
|    time_elapsed    | 1354     |
|    total_timesteps | 2113536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 294          |
| time/                   |              |
|    fps                  | 1564         |
|    iterations           | 131          |
|    time_elapsed         | 1372         |
|    total_timesteps      | 2146304      |
| train/                  |              |
|    approx_kl            | 0.0051646777 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.82e+03     |
|    n_updates            | 520          |
|    policy_gradient_loss | -0.00115     |
|    value_loss           | 5.12e+03     |
------------------------------------------

Eval num_timesteps=2150000, episode_reward=393.28 +/- 180.88

Episode length: 114.60 +/- 19.55

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 115          |
|    mean_reward          | 393          |
| time/                   |              |
|    total_timesteps      | 2150000      |
| train/                  |              |
|    approx_kl            | 0.0039829505 |
|    clip_fraction        | 0.00893      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.77        |
|    explained_variance   | 0.882        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.75e+03     |
|    n_updates            | 524          |
|    policy_gradient_loss | -0.00208     |
|    value_loss           | 4.14e+03     |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 366      |
| time/              |          |
|    fps             | 1563     |
|    iterations      | 132      |
|    time_elapsed    | 1383     |
|    total_timesteps | 2162688  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 335          |
| time/                   |              |
|    fps                  | 1564         |
|    iterations           | 133          |
|    time_elapsed         | 1393         |
|    total_timesteps      | 2179072      |
| train/                  |              |
|    approx_kl            | 0.0033961018 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.84e+03     |
|    n_updates            | 528          |
|    policy_gradient_loss | -0.00138     |
|    value_loss           | 4.87e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 311          |
| time/                   |              |
|    fps                  | 1566         |
|    iterations           | 134          |
|    time_elapsed         | 1401         |
|    total_timesteps      | 2195456      |
| train/                  |              |
|    approx_kl            | 0.0022561029 |
|    clip_fraction        | 0.0111       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.5e+03      |
|    n_updates            | 532          |
|    policy_gradient_loss | -0.000305    |
|    value_loss           | 3.78e+03     |
------------------------------------------

Eval num_timesteps=2200000, episode_reward=380.26 +/- 171.04

Episode length: 120.85 +/- 28.70

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 121          |
|    mean_reward          | 380          |
| time/                   |              |
|    total_timesteps      | 2200000      |
| train/                  |              |
|    approx_kl            | 0.0029535152 |
|    clip_fraction        | 0.0133       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.59e+03     |
|    n_updates            | 536          |
|    policy_gradient_loss | -0.00178     |
|    value_loss           | 4.46e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 353      |
| time/              |          |
|    fps             | 1564     |
|    iterations      | 135      |
|    time_elapsed    | 1413     |
|    total_timesteps | 2211840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 327          |
| time/                   |              |
|    fps                  | 1565         |
|    iterations           | 136          |
|    time_elapsed         | 1423         |
|    total_timesteps      | 2228224      |
| train/                  |              |
|    approx_kl            | 0.0035502806 |
|    clip_fraction        | 0.00468      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.24e+03     |
|    n_updates            | 540          |
|    policy_gradient_loss | 1.54e-06     |
|    value_loss           | 4.66e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 311         |
| time/                   |             |
|    fps                  | 1565        |
|    iterations           | 137         |
|    time_elapsed         | 1433        |
|    total_timesteps      | 2244608     |
| train/                  |             |
|    approx_kl            | 0.003908475 |
|    clip_fraction        | 0.015       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.788      |
|    explained_variance   | 0.871       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.82e+03    |
|    n_updates            | 544         |
|    policy_gradient_loss | -0.00154    |
|    value_loss           | 4.78e+03    |
-----------------------------------------

Eval num_timesteps=2250000, episode_reward=238.08 +/- 235.97

Episode length: 112.00 +/- 26.29

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 238          |
| time/                   |              |
|    total_timesteps      | 2250000      |
| train/                  |              |
|    approx_kl            | 0.0055177878 |
|    clip_fraction        | 0.0108       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.797       |
|    explained_variance   | 0.824        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.42e+03     |
|    n_updates            | 548          |
|    policy_gradient_loss | -0.00213     |
|    value_loss           | 6.43e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 327      |
| time/              |          |
|    fps             | 1564     |
|    iterations      | 138      |
|    time_elapsed    | 1445     |
|    total_timesteps | 2260992  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 362          |
| time/                   |              |
|    fps                  | 1566         |
|    iterations           | 139          |
|    time_elapsed         | 1454         |
|    total_timesteps      | 2277376      |
| train/                  |              |
|    approx_kl            | 0.0041152844 |
|    clip_fraction        | 0.00893      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.874        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.76e+03     |
|    n_updates            | 552          |
|    policy_gradient_loss | -0.00118     |
|    value_loss           | 4.86e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 342         |
| time/                   |             |
|    fps                  | 1567        |
|    iterations           | 140         |
|    time_elapsed         | 1463        |
|    total_timesteps      | 2293760     |
| train/                  |             |
|    approx_kl            | 0.004811921 |
|    clip_fraction        | 0.0146      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.794      |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 844         |
|    n_updates            | 556         |
|    policy_gradient_loss | -0.00124    |
|    value_loss           | 3.41e+03    |
-----------------------------------------

Eval num_timesteps=2300000, episode_reward=307.62 +/- 269.35

Episode length: 105.00 +/- 26.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 105          |
|    mean_reward          | 308          |
| time/                   |              |
|    total_timesteps      | 2300000      |
| train/                  |              |
|    approx_kl            | 0.0038704574 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.77        |
|    explained_variance   | 0.896        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.98e+03     |
|    n_updates            | 560          |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 3.15e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 301      |
| time/              |          |
|    fps             | 1566     |
|    iterations      | 141      |
|    time_elapsed    | 1474     |
|    total_timesteps | 2310144  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 355          |
| time/                   |              |
|    fps                  | 1567         |
|    iterations           | 142          |
|    time_elapsed         | 1483         |
|    total_timesteps      | 2326528      |
| train/                  |              |
|    approx_kl            | 0.0005881643 |
|    clip_fraction        | 0.000198     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.898        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.57e+03     |
|    n_updates            | 564          |
|    policy_gradient_loss | -0.000297    |
|    value_loss           | 4.14e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 354          |
| time/                   |              |
|    fps                  | 1569         |
|    iterations           | 143          |
|    time_elapsed         | 1493         |
|    total_timesteps      | 2342912      |
| train/                  |              |
|    approx_kl            | 0.0023608112 |
|    clip_fraction        | 0.00966      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.828        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.92e+03     |
|    n_updates            | 568          |
|    policy_gradient_loss | -0.00124     |
|    value_loss           | 5.94e+03     |
------------------------------------------

Eval num_timesteps=2350000, episode_reward=364.68 +/- 206.10

Episode length: 122.85 +/- 34.20

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 365          |
| time/                   |              |
|    total_timesteps      | 2350000      |
| train/                  |              |
|    approx_kl            | 0.0013712835 |
|    clip_fraction        | 0.000687     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 572          |
|    policy_gradient_loss | 0.000115     |
|    value_loss           | 3.64e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 330      |
| time/              |          |
|    fps             | 1567     |
|    iterations      | 144      |
|    time_elapsed    | 1505     |
|    total_timesteps | 2359296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 322          |
| time/                   |              |
|    fps                  | 1568         |
|    iterations           | 145          |
|    time_elapsed         | 1514         |
|    total_timesteps      | 2375680      |
| train/                  |              |
|    approx_kl            | 0.0024851977 |
|    clip_fraction        | 0.00807      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 4.92e+03     |
|    n_updates            | 576          |
|    policy_gradient_loss | -0.000764    |
|    value_loss           | 5.1e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 371         |
| time/                   |             |
|    fps                  | 1570        |
|    iterations           | 146         |
|    time_elapsed         | 1523        |
|    total_timesteps      | 2392064     |
| train/                  |             |
|    approx_kl            | 0.004032415 |
|    clip_fraction        | 0.0107      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.761      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.03e+03    |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.00131    |
|    value_loss           | 4.9e+03     |
-----------------------------------------

Eval num_timesteps=2400000, episode_reward=307.67 +/- 250.43

Episode length: 120.45 +/- 30.26

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 308          |
| time/                   |              |
|    total_timesteps      | 2400000      |
| train/                  |              |
|    approx_kl            | 0.0028667967 |
|    clip_fraction        | 0.00778      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.777       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.99e+03     |
|    n_updates            | 584          |
|    policy_gradient_loss | -0.00121     |
|    value_loss           | 3.83e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 331      |
| time/              |          |
|    fps             | 1569     |
|    iterations      | 147      |
|    time_elapsed    | 1534     |
|    total_timesteps | 2408448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 344          |
| time/                   |              |
|    fps                  | 1570         |
|    iterations           | 148          |
|    time_elapsed         | 1544         |
|    total_timesteps      | 2424832      |
| train/                  |              |
|    approx_kl            | 0.0047175274 |
|    clip_fraction        | 0.00793      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.754       |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.16e+03     |
|    n_updates            | 588          |
|    policy_gradient_loss | -0.000838    |
|    value_loss           | 3.79e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 355         |
| time/                   |             |
|    fps                  | 1571        |
|    iterations           | 149         |
|    time_elapsed         | 1553        |
|    total_timesteps      | 2441216     |
| train/                  |             |
|    approx_kl            | 0.002339624 |
|    clip_fraction        | 0.00403     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.767      |
|    explained_variance   | 0.897       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.61e+03    |
|    n_updates            | 592         |
|    policy_gradient_loss | -0.000749   |
|    value_loss           | 3.65e+03    |
-----------------------------------------

Eval num_timesteps=2450000, episode_reward=357.61 +/- 171.27

Episode length: 121.70 +/- 25.29

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | 358          |
| time/                   |              |
|    total_timesteps      | 2450000      |
| train/                  |              |
|    approx_kl            | 0.0065506194 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.793       |
|    explained_variance   | 0.811        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.83e+03     |
|    n_updates            | 596          |
|    policy_gradient_loss | -0.00257     |
|    value_loss           | 6.56e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 329      |
| time/              |          |
|    fps             | 1570     |
|    iterations      | 150      |
|    time_elapsed    | 1564     |
|    total_timesteps | 2457600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 337          |
| time/                   |              |
|    fps                  | 1572         |
|    iterations           | 151          |
|    time_elapsed         | 1573         |
|    total_timesteps      | 2473984      |
| train/                  |              |
|    approx_kl            | 0.0028150892 |
|    clip_fraction        | 0.00922      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.83e+03     |
|    n_updates            | 600          |
|    policy_gradient_loss | -0.000175    |
|    value_loss           | 3.56e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 354          |
| time/                   |              |
|    fps                  | 1572         |
|    iterations           | 152          |
|    time_elapsed         | 1583         |
|    total_timesteps      | 2490368      |
| train/                  |              |
|    approx_kl            | 0.0023576485 |
|    clip_fraction        | 0.00822      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.45e+03     |
|    n_updates            | 604          |
|    policy_gradient_loss | -0.00148     |
|    value_loss           | 5.52e+03     |
------------------------------------------

Eval num_timesteps=2500000, episode_reward=328.53 +/- 152.69

Episode length: 126.20 +/- 25.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 329          |
| time/                   |              |
|    total_timesteps      | 2500000      |
| train/                  |              |
|    approx_kl            | 0.0055155563 |
|    clip_fraction        | 0.00627      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.857        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.01e+03     |
|    n_updates            | 608          |
|    policy_gradient_loss | -0.00107     |
|    value_loss           | 4.92e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 318      |
| time/              |          |
|    fps             | 1571     |
|    iterations      | 153      |
|    time_elapsed    | 1594     |
|    total_timesteps | 2506752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 384          |
| time/                   |              |
|    fps                  | 1573         |
|    iterations           | 154          |
|    time_elapsed         | 1603         |
|    total_timesteps      | 2523136      |
| train/                  |              |
|    approx_kl            | 0.0039766943 |
|    clip_fraction        | 0.0121       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.904        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 612          |
|    policy_gradient_loss | -0.000788    |
|    value_loss           | 3.53e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 332          |
| time/                   |              |
|    fps                  | 1574         |
|    iterations           | 155          |
|    time_elapsed         | 1612         |
|    total_timesteps      | 2539520      |
| train/                  |              |
|    approx_kl            | 0.0019207299 |
|    clip_fraction        | 0.0024       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.53e+03     |
|    n_updates            | 616          |
|    policy_gradient_loss | -0.000108    |
|    value_loss           | 4.27e+03     |
------------------------------------------

Eval num_timesteps=2550000, episode_reward=276.25 +/- 230.19

Episode length: 126.65 +/- 36.07

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 127         |
|    mean_reward          | 276         |
| time/                   |             |
|    total_timesteps      | 2550000     |
| train/                  |             |
|    approx_kl            | 0.003072503 |
|    clip_fraction        | 0.00246     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.797      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.74e+03    |
|    n_updates            | 620         |
|    policy_gradient_loss | -0.000876   |
|    value_loss           | 5.02e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 333      |
| time/              |          |
|    fps             | 1573     |
|    iterations      | 156      |
|    time_elapsed    | 1624     |
|    total_timesteps | 2555904  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 384          |
| time/                   |              |
|    fps                  | 1574         |
|    iterations           | 157          |
|    time_elapsed         | 1633         |
|    total_timesteps      | 2572288      |
| train/                  |              |
|    approx_kl            | 0.0019419041 |
|    clip_fraction        | 0.00539      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.76e+03     |
|    n_updates            | 624          |
|    policy_gradient_loss | -0.000227    |
|    value_loss           | 4.6e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 308         |
| time/                   |             |
|    fps                  | 1576        |
|    iterations           | 158         |
|    time_elapsed         | 1641        |
|    total_timesteps      | 2588672     |
| train/                  |             |
|    approx_kl            | 0.001898681 |
|    clip_fraction        | 0.0036      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.806      |
|    explained_variance   | 0.889       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.97e+03    |
|    n_updates            | 628         |
|    policy_gradient_loss | -0.000322   |
|    value_loss           | 4.19e+03    |
-----------------------------------------

Eval num_timesteps=2600000, episode_reward=388.67 +/- 231.63

Episode length: 118.65 +/- 26.51

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 389          |
| time/                   |              |
|    total_timesteps      | 2600000      |
| train/                  |              |
|    approx_kl            | 0.0035863696 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.833        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.18e+03     |
|    n_updates            | 632          |
|    policy_gradient_loss | -0.00246     |
|    value_loss           | 6.05e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 349      |
| time/              |          |
|    fps             | 1575     |
|    iterations      | 159      |
|    time_elapsed    | 1653     |
|    total_timesteps | 2605056  |
---------------------------------
---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 124       |
|    ep_rew_mean          | 310       |
| time/                   |           |
|    fps                  | 1576      |
|    iterations           | 160       |
|    time_elapsed         | 1662      |
|    total_timesteps      | 2621440   |
| train/                  |           |
|    approx_kl            | 0.0049839 |
|    clip_fraction        | 0.0186    |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.762    |
|    explained_variance   | 0.85      |
|    learning_rate        | 0.0003    |
|    loss                 | 2.81e+03  |
|    n_updates            | 636       |
|    policy_gradient_loss | -0.00275  |
|    value_loss           | 5.18e+03  |
---------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 359          |
| time/                   |              |
|    fps                  | 1577         |
|    iterations           | 161          |
|    time_elapsed         | 1672         |
|    total_timesteps      | 2637824      |
| train/                  |              |
|    approx_kl            | 0.0043866457 |
|    clip_fraction        | 0.0198       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.773       |
|    explained_variance   | 0.897        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.37e+03     |
|    n_updates            | 640          |
|    policy_gradient_loss | -0.00092     |
|    value_loss           | 3.56e+03     |
------------------------------------------

Eval num_timesteps=2650000, episode_reward=242.72 +/- 260.27

Episode length: 113.00 +/- 32.03

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 113         |
|    mean_reward          | 243         |
| time/                   |             |
|    total_timesteps      | 2650000     |
| train/                  |             |
|    approx_kl            | 0.002528416 |
|    clip_fraction        | 0.0109      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.757      |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.97e+03    |
|    n_updates            | 644         |
|    policy_gradient_loss | -0.00219    |
|    value_loss           | 5.33e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 410      |
| time/              |          |
|    fps             | 1577     |
|    iterations      | 162      |
|    time_elapsed    | 1682     |
|    total_timesteps | 2654208  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 348          |
| time/                   |              |
|    fps                  | 1578         |
|    iterations           | 163          |
|    time_elapsed         | 1692         |
|    total_timesteps      | 2670592      |
| train/                  |              |
|    approx_kl            | 0.0051544835 |
|    clip_fraction        | 0.0163       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.748       |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.36e+03     |
|    n_updates            | 648          |
|    policy_gradient_loss | -0.00183     |
|    value_loss           | 3.97e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 373          |
| time/                   |              |
|    fps                  | 1579         |
|    iterations           | 164          |
|    time_elapsed         | 1701         |
|    total_timesteps      | 2686976      |
| train/                  |              |
|    approx_kl            | 0.0026556528 |
|    clip_fraction        | 0.008        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.763       |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.41e+03     |
|    n_updates            | 652          |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 4.19e+03     |
------------------------------------------

Eval num_timesteps=2700000, episode_reward=417.79 +/- 139.99

Episode length: 123.05 +/- 29.34

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 123        |
|    mean_reward          | 418        |
| time/                   |            |
|    total_timesteps      | 2700000    |
| train/                  |            |
|    approx_kl            | 0.00545122 |
|    clip_fraction        | 0.01       |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.788     |
|    explained_variance   | 0.885      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.57e+03   |
|    n_updates            | 656        |
|    policy_gradient_loss | -0.000954  |
|    value_loss           | 4.09e+03   |
----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 362      |
| time/              |          |
|    fps             | 1578     |
|    iterations      | 165      |
|    time_elapsed    | 1712     |
|    total_timesteps | 2703360  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 385         |
| time/                   |             |
|    fps                  | 1579        |
|    iterations           | 166         |
|    time_elapsed         | 1721        |
|    total_timesteps      | 2719744     |
| train/                  |             |
|    approx_kl            | 0.004387471 |
|    clip_fraction        | 0.0217      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.788      |
|    explained_variance   | 0.9         |
|    learning_rate        | 0.0003      |
|    loss                 | 1.68e+03    |
|    n_updates            | 660         |
|    policy_gradient_loss | -0.00168    |
|    value_loss           | 3.21e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 373          |
| time/                   |              |
|    fps                  | 1580         |
|    iterations           | 167          |
|    time_elapsed         | 1731         |
|    total_timesteps      | 2736128      |
| train/                  |              |
|    approx_kl            | 0.0025887154 |
|    clip_fraction        | 0.00397      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.82         |
|    learning_rate        | 0.0003       |
|    loss                 | 3e+03        |
|    n_updates            | 664          |
|    policy_gradient_loss | -0.00117     |
|    value_loss           | 6.06e+03     |
------------------------------------------

Eval num_timesteps=2750000, episode_reward=328.01 +/- 241.52

Episode length: 109.40 +/- 25.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | 328          |
| time/                   |              |
|    total_timesteps      | 2750000      |
| train/                  |              |
|    approx_kl            | 0.0058714207 |
|    clip_fraction        | 0.0285       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.789        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.52e+03     |
|    n_updates            | 668          |
|    policy_gradient_loss | -0.00271     |
|    value_loss           | 6.57e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 380      |
| time/              |          |
|    fps             | 1579     |
|    iterations      | 168      |
|    time_elapsed    | 1742     |
|    total_timesteps | 2752512  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 374          |
| time/                   |              |
|    fps                  | 1580         |
|    iterations           | 169          |
|    time_elapsed         | 1751         |
|    total_timesteps      | 2768896      |
| train/                  |              |
|    approx_kl            | 0.0031587407 |
|    clip_fraction        | 0.00816      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.21e+03     |
|    n_updates            | 672          |
|    policy_gradient_loss | -0.000636    |
|    value_loss           | 3.88e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 361         |
| time/                   |             |
|    fps                  | 1581        |
|    iterations           | 170         |
|    time_elapsed         | 1760        |
|    total_timesteps      | 2785280     |
| train/                  |             |
|    approx_kl            | 0.005118918 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.776      |
|    explained_variance   | 0.917       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.1e+03     |
|    n_updates            | 676         |
|    policy_gradient_loss | -0.00171    |
|    value_loss           | 2.88e+03    |
-----------------------------------------

Eval num_timesteps=2800000, episode_reward=488.05 +/- 200.52

Episode length: 111.15 +/- 26.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 111         |
|    mean_reward          | 488         |
| time/                   |             |
|    total_timesteps      | 2800000     |
| train/                  |             |
|    approx_kl            | 0.003693313 |
|    clip_fraction        | 0.00464     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.791      |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.92e+03    |
|    n_updates            | 680         |
|    policy_gradient_loss | -0.000873   |
|    value_loss           | 3.98e+03    |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 355      |
| time/              |          |
|    fps             | 1581     |
|    iterations      | 171      |
|    time_elapsed    | 1772     |
|    total_timesteps | 2801664  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 373         |
| time/                   |             |
|    fps                  | 1581        |
|    iterations           | 172         |
|    time_elapsed         | 1781        |
|    total_timesteps      | 2818048     |
| train/                  |             |
|    approx_kl            | 0.005209942 |
|    clip_fraction        | 0.0107      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.781      |
|    explained_variance   | 0.857       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.54e+03    |
|    n_updates            | 684         |
|    policy_gradient_loss | -0.00208    |
|    value_loss           | 5.61e+03    |
-----------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 125           |
|    ep_rew_mean          | 395           |
| time/                   |               |
|    fps                  | 1583          |
|    iterations           | 173           |
|    time_elapsed         | 1790          |
|    total_timesteps      | 2834432       |
| train/                  |               |
|    approx_kl            | 0.00039165854 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.765        |
|    explained_variance   | 0.894         |
|    learning_rate        | 0.0003        |
|    loss                 | 1.6e+03       |
|    n_updates            | 688           |
|    policy_gradient_loss | 3.57e-05      |
|    value_loss           | 3.77e+03      |
-------------------------------------------

Eval num_timesteps=2850000, episode_reward=358.24 +/- 217.96

Episode length: 116.10 +/- 31.52

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 116         |
|    mean_reward          | 358         |
| time/                   |             |
|    total_timesteps      | 2850000     |
| train/                  |             |
|    approx_kl            | 0.003971521 |
|    clip_fraction        | 0.00864     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.792      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.28e+03    |
|    n_updates            | 692         |
|    policy_gradient_loss | -0.00105    |
|    value_loss           | 4.29e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 383      |
| time/              |          |
|    fps             | 1582     |
|    iterations      | 174      |
|    time_elapsed    | 1801     |
|    total_timesteps | 2850816  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 352          |
| time/                   |              |
|    fps                  | 1582         |
|    iterations           | 175          |
|    time_elapsed         | 1811         |
|    total_timesteps      | 2867200      |
| train/                  |              |
|    approx_kl            | 0.0053795907 |
|    clip_fraction        | 0.03         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.22e+03     |
|    n_updates            | 696          |
|    policy_gradient_loss | -0.00179     |
|    value_loss           | 3.78e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 362          |
| time/                   |              |
|    fps                  | 1583         |
|    iterations           | 176          |
|    time_elapsed         | 1820         |
|    total_timesteps      | 2883584      |
| train/                  |              |
|    approx_kl            | 0.0033235103 |
|    clip_fraction        | 0.0047       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.24e+03     |
|    n_updates            | 700          |
|    policy_gradient_loss | -0.00127     |
|    value_loss           | 6.27e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 387         |
| time/                   |             |
|    fps                  | 1585        |
|    iterations           | 177         |
|    time_elapsed         | 1829        |
|    total_timesteps      | 2899968     |
| train/                  |             |
|    approx_kl            | 0.006746024 |
|    clip_fraction        | 0.0191      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.781      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.76e+03    |
|    n_updates            | 704         |
|    policy_gradient_loss | -0.00219    |
|    value_loss           | 5.18e+03    |
-----------------------------------------

Eval num_timesteps=2900000, episode_reward=438.86 +/- 259.89

Episode length: 109.65 +/- 22.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 439          |
| time/                   |              |
|    total_timesteps      | 2900000      |
| train/                  |              |
|    approx_kl            | 0.0032317329 |
|    clip_fraction        | 0.00723      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.858        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.06e+03     |
|    n_updates            | 708          |
|    policy_gradient_loss | -0.000387    |
|    value_loss           | 4.5e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_2900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 336      |
| time/              |          |
|    fps             | 1584     |
|    iterations      | 178      |
|    time_elapsed    | 1840     |
|    total_timesteps | 2916352  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 397         |
| time/                   |             |
|    fps                  | 1585        |
|    iterations           | 179         |
|    time_elapsed         | 1849        |
|    total_timesteps      | 2932736     |
| train/                  |             |
|    approx_kl            | 0.003312793 |
|    clip_fraction        | 0.00853     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.772      |
|    explained_variance   | 0.818       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.23e+03    |
|    n_updates            | 712         |
|    policy_gradient_loss | -0.00141    |
|    value_loss           | 6.38e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 360         |
| time/                   |             |
|    fps                  | 1586        |
|    iterations           | 180         |
|    time_elapsed         | 1858        |
|    total_timesteps      | 2949120     |
| train/                  |             |
|    approx_kl            | 0.004330635 |
|    clip_fraction        | 0.0225      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.911       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.56e+03    |
|    n_updates            | 716         |
|    policy_gradient_loss | -0.0017     |
|    value_loss           | 3.12e+03    |
-----------------------------------------

Eval num_timesteps=2950000, episode_reward=401.31 +/- 263.97

Episode length: 115.00 +/- 27.68

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 115         |
|    mean_reward          | 401         |
| time/                   |             |
|    total_timesteps      | 2950000     |
| train/                  |             |
|    approx_kl            | 0.004589344 |
|    clip_fraction        | 0.013       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.782      |
|    explained_variance   | 0.866       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.76e+03    |
|    n_updates            | 720         |
|    policy_gradient_loss | -0.00194    |
|    value_loss           | 4.4e+03     |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 348      |
| time/              |          |
|    fps             | 1586     |
|    iterations      | 181      |
|    time_elapsed    | 1869     |
|    total_timesteps | 2965504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 400          |
| time/                   |              |
|    fps                  | 1586         |
|    iterations           | 182          |
|    time_elapsed         | 1879         |
|    total_timesteps      | 2981888      |
| train/                  |              |
|    approx_kl            | 0.0025454778 |
|    clip_fraction        | 0.00177      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.761       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.98e+03     |
|    n_updates            | 724          |
|    policy_gradient_loss | -0.000387    |
|    value_loss           | 5.44e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 417          |
| time/                   |              |
|    fps                  | 1587         |
|    iterations           | 183          |
|    time_elapsed         | 1889         |
|    total_timesteps      | 2998272      |
| train/                  |              |
|    approx_kl            | 0.0012555559 |
|    clip_fraction        | 0.000198     |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.9          |
|    learning_rate        | 0.0003       |
|    loss                 | 2.04e+03     |
|    n_updates            | 728          |
|    policy_gradient_loss | -0.000172    |
|    value_loss           | 3.1e+03      |
------------------------------------------

Eval num_timesteps=3000000, episode_reward=459.61 +/- 124.11

Episode length: 128.00 +/- 26.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 460          |
| time/                   |              |
|    total_timesteps      | 3000000      |
| train/                  |              |
|    approx_kl            | 0.0018384332 |
|    clip_fraction        | 0.00645      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28e+03     |
|    n_updates            | 732          |
|    policy_gradient_loss | -0.000235    |
|    value_loss           | 3.96e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 3,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 367      |
| time/              |          |
|    fps             | 1583     |
|    iterations      | 184      |
|    time_elapsed    | 1903     |
|    total_timesteps | 3014656  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 383         |
| time/                   |             |
|    fps                  | 1583        |
|    iterations           | 185         |
|    time_elapsed         | 1913        |
|    total_timesteps      | 3031040     |
| train/                  |             |
|    approx_kl            | 0.002015592 |
|    clip_fraction        | 0.00931     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.793      |
|    explained_variance   | 0.852       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.11e+03    |
|    n_updates            | 736         |
|    policy_gradient_loss | -6.18e-05   |
|    value_loss           | 5e+03       |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 392         |
| time/                   |             |
|    fps                  | 1585        |
|    iterations           | 186         |
|    time_elapsed         | 1921        |
|    total_timesteps      | 3047424     |
| train/                  |             |
|    approx_kl            | 0.002354913 |
|    clip_fraction        | 0.00241     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.79       |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.3e+03     |
|    n_updates            | 740         |
|    policy_gradient_loss | -0.000767   |
|    value_loss           | 4.71e+03    |
-----------------------------------------

Eval num_timesteps=3050000, episode_reward=363.22 +/- 247.49

Episode length: 116.70 +/- 26.47

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 363          |
| time/                   |              |
|    total_timesteps      | 3050000      |
| train/                  |              |
|    approx_kl            | 0.0026875162 |
|    clip_fraction        | 0.00299      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.883        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.68e+03     |
|    n_updates            | 744          |
|    policy_gradient_loss | -0.000516    |
|    value_loss           | 3.91e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 402      |
| time/              |          |
|    fps             | 1584     |
|    iterations      | 187      |
|    time_elapsed    | 1933     |
|    total_timesteps | 3063808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 421          |
| time/                   |              |
|    fps                  | 1585         |
|    iterations           | 188          |
|    time_elapsed         | 1943         |
|    total_timesteps      | 3080192      |
| train/                  |              |
|    approx_kl            | 0.0034813692 |
|    clip_fraction        | 0.00311      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.2e+03      |
|    n_updates            | 748          |
|    policy_gradient_loss | -0.000447    |
|    value_loss           | 4.1e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 397         |
| time/                   |             |
|    fps                  | 1585        |
|    iterations           | 189         |
|    time_elapsed         | 1952        |
|    total_timesteps      | 3096576     |
| train/                  |             |
|    approx_kl            | 0.001891071 |
|    clip_fraction        | 0.00813     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | 0.844       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.57e+03    |
|    n_updates            | 752         |
|    policy_gradient_loss | -0.000301   |
|    value_loss           | 4.64e+03    |
-----------------------------------------

Eval num_timesteps=3100000, episode_reward=421.59 +/- 203.50

Episode length: 114.10 +/- 25.04

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | 422          |
| time/                   |              |
|    total_timesteps      | 3100000      |
| train/                  |              |
|    approx_kl            | 0.0005081817 |
|    clip_fraction        | 0.00227      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.17e+03     |
|    n_updates            | 756          |
|    policy_gradient_loss | 0.000333     |
|    value_loss           | 4.43e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 394      |
| time/              |          |
|    fps             | 1585     |
|    iterations      | 190      |
|    time_elapsed    | 1963     |
|    total_timesteps | 3112960  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 389         |
| time/                   |             |
|    fps                  | 1586        |
|    iterations           | 191         |
|    time_elapsed         | 1972        |
|    total_timesteps      | 3129344     |
| train/                  |             |
|    approx_kl            | 0.003930245 |
|    clip_fraction        | 0.0058      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.769      |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08e+03    |
|    n_updates            | 760         |
|    policy_gradient_loss | -0.000387   |
|    value_loss           | 5.43e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 388          |
| time/                   |              |
|    fps                  | 1586         |
|    iterations           | 192          |
|    time_elapsed         | 1982         |
|    total_timesteps      | 3145728      |
| train/                  |              |
|    approx_kl            | 0.0048223343 |
|    clip_fraction        | 0.0135       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.762       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55e+03     |
|    n_updates            | 764          |
|    policy_gradient_loss | -0.00119     |
|    value_loss           | 4.07e+03     |
------------------------------------------

Eval num_timesteps=3150000, episode_reward=397.33 +/- 242.07

Episode length: 114.05 +/- 26.20

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | 397          |
| time/                   |              |
|    total_timesteps      | 3150000      |
| train/                  |              |
|    approx_kl            | 0.0022585709 |
|    clip_fraction        | 0.00873      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.758       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11e+03     |
|    n_updates            | 768          |
|    policy_gradient_loss | -0.00152     |
|    value_loss           | 4.31e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 418      |
| time/              |          |
|    fps             | 1586     |
|    iterations      | 193      |
|    time_elapsed    | 1993     |
|    total_timesteps | 3162112  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 407         |
| time/                   |             |
|    fps                  | 1587        |
|    iterations           | 194         |
|    time_elapsed         | 2001        |
|    total_timesteps      | 3178496     |
| train/                  |             |
|    approx_kl            | 0.003164322 |
|    clip_fraction        | 0.014       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | 0.89        |
|    learning_rate        | 0.0003      |
|    loss                 | 915         |
|    n_updates            | 772         |
|    policy_gradient_loss | -0.000452   |
|    value_loss           | 3.74e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 403          |
| time/                   |              |
|    fps                  | 1588         |
|    iterations           | 195          |
|    time_elapsed         | 2011         |
|    total_timesteps      | 3194880      |
| train/                  |              |
|    approx_kl            | 0.0021943036 |
|    clip_fraction        | 0.00471      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.761       |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.83e+03     |
|    n_updates            | 776          |
|    policy_gradient_loss | -0.000735    |
|    value_loss           | 4.45e+03     |
------------------------------------------

Eval num_timesteps=3200000, episode_reward=338.88 +/- 218.74

Episode length: 116.25 +/- 22.81

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 339          |
| time/                   |              |
|    total_timesteps      | 3200000      |
| train/                  |              |
|    approx_kl            | 0.0045535546 |
|    clip_fraction        | 0.0245       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.77        |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.12e+03     |
|    n_updates            | 780          |
|    policy_gradient_loss | -0.00214     |
|    value_loss           | 4.63e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 400      |
| time/              |          |
|    fps             | 1587     |
|    iterations      | 196      |
|    time_elapsed    | 2022     |
|    total_timesteps | 3211264  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 376          |
| time/                   |              |
|    fps                  | 1588         |
|    iterations           | 197          |
|    time_elapsed         | 2031         |
|    total_timesteps      | 3227648      |
| train/                  |              |
|    approx_kl            | 0.0048722625 |
|    clip_fraction        | 0.0268       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.775       |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.82e+03     |
|    n_updates            | 784          |
|    policy_gradient_loss | -0.00119     |
|    value_loss           | 3.32e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 420         |
| time/                   |             |
|    fps                  | 1589        |
|    iterations           | 198         |
|    time_elapsed         | 2040        |
|    total_timesteps      | 3244032     |
| train/                  |             |
|    approx_kl            | 0.002434058 |
|    clip_fraction        | 0.005       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.761      |
|    explained_variance   | 0.842       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.86e+03    |
|    n_updates            | 788         |
|    policy_gradient_loss | -0.000724   |
|    value_loss           | 5.2e+03     |
-----------------------------------------

Eval num_timesteps=3250000, episode_reward=479.45 +/- 246.09

Episode length: 108.65 +/- 23.21

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | 479          |
| time/                   |              |
|    total_timesteps      | 3250000      |
| train/                  |              |
|    approx_kl            | 0.0044388054 |
|    clip_fraction        | 0.0187       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.767       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 575          |
|    n_updates            | 792          |
|    policy_gradient_loss | -0.000807    |
|    value_loss           | 3.71e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 380      |
| time/              |          |
|    fps             | 1588     |
|    iterations      | 199      |
|    time_elapsed    | 2052     |
|    total_timesteps | 3260416  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 387         |
| time/                   |             |
|    fps                  | 1588        |
|    iterations           | 200         |
|    time_elapsed         | 2062        |
|    total_timesteps      | 3276800     |
| train/                  |             |
|    approx_kl            | 0.003235746 |
|    clip_fraction        | 0.00125     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.787      |
|    explained_variance   | 0.824       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.19e+03    |
|    n_updates            | 796         |
|    policy_gradient_loss | -0.000676   |
|    value_loss           | 4.55e+03    |
-----------------------------------------

Eval num_timesteps=3300000, episode_reward=388.73 +/- 217.22

Episode length: 111.90 +/- 28.02

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 389          |
| time/                   |              |
|    total_timesteps      | 3300000      |
| train/                  |              |
|    approx_kl            | 0.0024308946 |
|    clip_fraction        | 0.00359      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.785       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.67e+03     |
|    n_updates            | 804          |
|    policy_gradient_loss | 0.000155     |
|    value_loss           | 3.9e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 387      |
| time/              |          |
|    fps             | 1589     |
|    iterations      | 202      |
|    time_elapsed    | 2082     |
|    total_timesteps | 3309568  |
---------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 120           |
|    ep_rew_mean          | 371           |
| time/                   |               |
|    fps                  | 1590          |
|    iterations           | 203           |
|    time_elapsed         | 2091          |
|    total_timesteps      | 3325952       |
| train/                  |               |
|    approx_kl            | 0.00083657645 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.783        |
|    explained_variance   | 0.832         |
|    learning_rate        | 0.0003        |
|    loss                 | 2.52e+03      |
|    n_updates            | 808           |
|    policy_gradient_loss | 0.00015       |
|    value_loss           | 5.66e+03      |
-------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 420          |
| time/                   |              |
|    fps                  | 1590         |
|    iterations           | 204          |
|    time_elapsed         | 2101         |
|    total_timesteps      | 3342336      |
| train/                  |              |
|    approx_kl            | 0.0035643803 |
|    clip_fraction        | 0.00595      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.857        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.88e+03     |
|    n_updates            | 812          |
|    policy_gradient_loss | -0.000558    |
|    value_loss           | 4.49e+03     |
------------------------------------------

Eval num_timesteps=3350000, episode_reward=414.18 +/- 215.74

Episode length: 131.85 +/- 31.04

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | 414          |
| time/                   |              |
|    total_timesteps      | 3350000      |
| train/                  |              |
|    approx_kl            | 0.0048744716 |
|    clip_fraction        | 0.0063       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.854        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.09e+03     |
|    n_updates            | 816          |
|    policy_gradient_loss | -0.000648    |
|    value_loss           | 4.45e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 382      |
| time/              |          |
|    fps             | 1589     |
|    iterations      | 205      |
|    time_elapsed    | 2113     |
|    total_timesteps | 3358720  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 383         |
| time/                   |             |
|    fps                  | 1590        |
|    iterations           | 206         |
|    time_elapsed         | 2121        |
|    total_timesteps      | 3375104     |
| train/                  |             |
|    approx_kl            | 0.003116848 |
|    clip_fraction        | 0.0083      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.794      |
|    explained_variance   | 0.909       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.35e+03    |
|    n_updates            | 820         |
|    policy_gradient_loss | -2.6e-05    |
|    value_loss           | 2.89e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 386         |
| time/                   |             |
|    fps                  | 1591        |
|    iterations           | 207         |
|    time_elapsed         | 2131        |
|    total_timesteps      | 3391488     |
| train/                  |             |
|    approx_kl            | 0.005372219 |
|    clip_fraction        | 0.0111      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | 0.832       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.43e+03    |
|    n_updates            | 824         |
|    policy_gradient_loss | -0.00139    |
|    value_loss           | 5.89e+03    |
-----------------------------------------

Eval num_timesteps=3400000, episode_reward=365.25 +/- 212.19

Episode length: 116.00 +/- 26.12

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 365          |
| time/                   |              |
|    total_timesteps      | 3400000      |
| train/                  |              |
|    approx_kl            | 0.0033876947 |
|    clip_fraction        | 0.00807      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.774       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 932          |
|    n_updates            | 828          |
|    policy_gradient_loss | -0.000827    |
|    value_loss           | 3.93e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 381      |
| time/              |          |
|    fps             | 1590     |
|    iterations      | 208      |
|    time_elapsed    | 2143     |
|    total_timesteps | 3407872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 376          |
| time/                   |              |
|    fps                  | 1591         |
|    iterations           | 209          |
|    time_elapsed         | 2152         |
|    total_timesteps      | 3424256      |
| train/                  |              |
|    approx_kl            | 0.0038494444 |
|    clip_fraction        | 0.0151       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.761       |
|    explained_variance   | 0.927        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.44e+03     |
|    n_updates            | 832          |
|    policy_gradient_loss | -0.000732    |
|    value_loss           | 2.49e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 425          |
| time/                   |              |
|    fps                  | 1592         |
|    iterations           | 210          |
|    time_elapsed         | 2160         |
|    total_timesteps      | 3440640      |
| train/                  |              |
|    approx_kl            | 0.0014767001 |
|    clip_fraction        | 0.00316      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.784        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.06e+03     |
|    n_updates            | 836          |
|    policy_gradient_loss | -0.000495    |
|    value_loss           | 6.76e+03     |
------------------------------------------

Eval num_timesteps=3450000, episode_reward=445.18 +/- 189.42

Episode length: 115.95 +/- 26.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 445          |
| time/                   |              |
|    total_timesteps      | 3450000      |
| train/                  |              |
|    approx_kl            | 0.0021465095 |
|    clip_fraction        | 0.00966      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.873        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.2e+03      |
|    n_updates            | 840          |
|    policy_gradient_loss | -0.00106     |
|    value_loss           | 4.13e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 392      |
| time/              |          |
|    fps             | 1591     |
|    iterations      | 211      |
|    time_elapsed    | 2172     |
|    total_timesteps | 3457024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 394          |
| time/                   |              |
|    fps                  | 1591         |
|    iterations           | 212          |
|    time_elapsed         | 2181         |
|    total_timesteps      | 3473408      |
| train/                  |              |
|    approx_kl            | 0.0028200953 |
|    clip_fraction        | 0.0033       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.758       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.26e+03     |
|    n_updates            | 844          |
|    policy_gradient_loss | -0.000405    |
|    value_loss           | 3.66e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 397         |
| time/                   |             |
|    fps                  | 1593        |
|    iterations           | 213         |
|    time_elapsed         | 2190        |
|    total_timesteps      | 3489792     |
| train/                  |             |
|    approx_kl            | 0.004366193 |
|    clip_fraction        | 0.00746     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.745      |
|    explained_variance   | 0.808       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.17e+03    |
|    n_updates            | 848         |
|    policy_gradient_loss | -0.0014     |
|    value_loss           | 5.83e+03    |
-----------------------------------------

Eval num_timesteps=3500000, episode_reward=489.02 +/- 150.80

Episode length: 116.60 +/- 23.24

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 489         |
| time/                   |             |
|    total_timesteps      | 3500000     |
| train/                  |             |
|    approx_kl            | 0.004831644 |
|    clip_fraction        | 0.0194      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.756      |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.09e+03    |
|    n_updates            | 852         |
|    policy_gradient_loss | -0.00124    |
|    value_loss           | 3.65e+03    |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 361      |
| time/              |          |
|    fps             | 1592     |
|    iterations      | 214      |
|    time_elapsed    | 2201     |
|    total_timesteps | 3506176  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 411          |
| time/                   |              |
|    fps                  | 1592         |
|    iterations           | 215          |
|    time_elapsed         | 2211         |
|    total_timesteps      | 3522560      |
| train/                  |              |
|    approx_kl            | 0.0042628404 |
|    clip_fraction        | 0.0152       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.738       |
|    explained_variance   | 0.837        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.93e+03     |
|    n_updates            | 856          |
|    policy_gradient_loss | -0.000966    |
|    value_loss           | 5.43e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 370          |
| time/                   |              |
|    fps                  | 1593         |
|    iterations           | 216          |
|    time_elapsed         | 2221         |
|    total_timesteps      | 3538944      |
| train/                  |              |
|    approx_kl            | 0.0024414202 |
|    clip_fraction        | 0.0061       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.773       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.41e+03     |
|    n_updates            | 860          |
|    policy_gradient_loss | -0.000163    |
|    value_loss           | 3.93e+03     |
------------------------------------------

Eval num_timesteps=3550000, episode_reward=442.32 +/- 254.65

Episode length: 109.00 +/- 25.44

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | 442          |
| time/                   |              |
|    total_timesteps      | 3550000      |
| train/                  |              |
|    approx_kl            | 0.0039050672 |
|    clip_fraction        | 0.00401      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.764       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 864          |
|    policy_gradient_loss | -0.000618    |
|    value_loss           | 4.19e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 382          |
| time/                   |              |
|    fps                  | 1593         |
|    iterations           | 218          |
|    time_elapsed         | 2240         |
|    total_timesteps      | 3571712      |
| train/                  |              |
|    approx_kl            | 0.0059884535 |
|    clip_fraction        | 0.0201       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.814        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.58e+03     |
|    n_updates            | 868          |
|    policy_gradient_loss | -0.00196     |
|    value_loss           | 6.52e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 426          |
| time/                   |              |
|    fps                  | 1594         |
|    iterations           | 219          |
|    time_elapsed         | 2250         |
|    total_timesteps      | 3588096      |
| train/                  |              |
|    approx_kl            | 0.0023137461 |
|    clip_fraction        | 0.0112       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.764       |
|    explained_variance   | 0.867        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.03e+03     |
|    n_updates            | 872          |
|    policy_gradient_loss | -0.00134     |
|    value_loss           | 4.9e+03      |
------------------------------------------

Eval num_timesteps=3600000, episode_reward=420.92 +/- 171.49

Episode length: 119.85 +/- 24.94

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 421          |
| time/                   |              |
|    total_timesteps      | 3600000      |
| train/                  |              |
|    approx_kl            | 0.0026755643 |
|    clip_fraction        | 0.00577      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.767       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.64e+03     |
|    n_updates            | 876          |
|    policy_gradient_loss | -0.000431    |
|    value_loss           | 3.11e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 381      |
| time/              |          |
|    fps             | 1593     |
|    iterations      | 220      |
|    time_elapsed    | 2261     |
|    total_timesteps | 3604480  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 426          |
| time/                   |              |
|    fps                  | 1594         |
|    iterations           | 221          |
|    time_elapsed         | 2270         |
|    total_timesteps      | 3620864      |
| train/                  |              |
|    approx_kl            | 0.0059933634 |
|    clip_fraction        | 0.0239       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.752       |
|    explained_variance   | 0.916        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.98e+03     |
|    n_updates            | 880          |
|    policy_gradient_loss | -0.00243     |
|    value_loss           | 3.04e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 396          |
| time/                   |              |
|    fps                  | 1595         |
|    iterations           | 222          |
|    time_elapsed         | 2280         |
|    total_timesteps      | 3637248      |
| train/                  |              |
|    approx_kl            | 0.0031198384 |
|    clip_fraction        | 0.0141       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.903        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.96e+03     |
|    n_updates            | 884          |
|    policy_gradient_loss | -0.00037     |
|    value_loss           | 3.1e+03      |
------------------------------------------

Eval num_timesteps=3650000, episode_reward=456.86 +/- 195.25

Episode length: 120.10 +/- 30.42

-------------------------------------------
| eval/                   |               |
|    mean_ep_length       | 120           |
|    mean_reward          | 457           |
| time/                   |               |
|    total_timesteps      | 3650000       |
| train/                  |               |
|    approx_kl            | 0.00090741576 |
|    clip_fraction        | 0.00655       |
|    clip_range           | 0.2           |
|    entropy_loss         | -0.75         |
|    explained_variance   | 0.808         |
|    learning_rate        | 0.0003        |
|    loss                 | 2.44e+03      |
|    n_updates            | 888           |
|    policy_gradient_loss | -0.00142      |
|    value_loss           | 5.64e+03      |
-------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 401      |
| time/              |          |
|    fps             | 1594     |
|    iterations      | 223      |
|    time_elapsed    | 2292     |
|    total_timesteps | 3653632  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 370          |
| time/                   |              |
|    fps                  | 1594         |
|    iterations           | 224          |
|    time_elapsed         | 2301         |
|    total_timesteps      | 3670016      |
| train/                  |              |
|    approx_kl            | 0.0033068715 |
|    clip_fraction        | 0.00746      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 892          |
|    policy_gradient_loss | -0.000194    |
|    value_loss           | 3.6e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 404         |
| time/                   |             |
|    fps                  | 1595        |
|    iterations           | 225         |
|    time_elapsed         | 2310        |
|    total_timesteps      | 3686400     |
| train/                  |             |
|    approx_kl            | 0.004631481 |
|    clip_fraction        | 0.00565     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.769      |
|    explained_variance   | 0.838       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.23e+03    |
|    n_updates            | 896         |
|    policy_gradient_loss | -0.0014     |
|    value_loss           | 5.26e+03    |
-----------------------------------------

Eval num_timesteps=3700000, episode_reward=410.81 +/- 160.86

Episode length: 124.95 +/- 29.74

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 125         |
|    mean_reward          | 411         |
| time/                   |             |
|    total_timesteps      | 3700000     |
| train/                  |             |
|    approx_kl            | 0.003258078 |
|    clip_fraction        | 0.00961     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.782      |
|    explained_variance   | 0.855       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.54e+03    |
|    n_updates            | 900         |
|    policy_gradient_loss | -0.00188    |
|    value_loss           | 5.17e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 389      |
| time/              |          |
|    fps             | 1594     |
|    iterations      | 226      |
|    time_elapsed    | 2321     |
|    total_timesteps | 3702784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 394          |
| time/                   |              |
|    fps                  | 1595         |
|    iterations           | 227          |
|    time_elapsed         | 2331         |
|    total_timesteps      | 3719168      |
| train/                  |              |
|    approx_kl            | 0.0054224473 |
|    clip_fraction        | 0.0196       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.744       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.7e+03      |
|    n_updates            | 904          |
|    policy_gradient_loss | -0.00215     |
|    value_loss           | 3.02e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 400          |
| time/                   |              |
|    fps                  | 1595         |
|    iterations           | 228          |
|    time_elapsed         | 2341         |
|    total_timesteps      | 3735552      |
| train/                  |              |
|    approx_kl            | 0.0013926463 |
|    clip_fraction        | 0.00598      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.874        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.16e+03     |
|    n_updates            | 908          |
|    policy_gradient_loss | -0.00068     |
|    value_loss           | 3.26e+03     |
------------------------------------------

Eval num_timesteps=3750000, episode_reward=452.48 +/- 261.51

Episode length: 112.05 +/- 26.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 452          |
| time/                   |              |
|    total_timesteps      | 3750000      |
| train/                  |              |
|    approx_kl            | 0.0034574359 |
|    clip_fraction        | 0.012        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.882        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.62e+03     |
|    n_updates            | 912          |
|    policy_gradient_loss | -0.000643    |
|    value_loss           | 4.13e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 414      |
| time/              |          |
|    fps             | 1595     |
|    iterations      | 229      |
|    time_elapsed    | 2351     |
|    total_timesteps | 3751936  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 126        |
|    ep_rew_mean          | 376        |
| time/                   |            |
|    fps                  | 1596       |
|    iterations           | 230        |
|    time_elapsed         | 2361       |
|    total_timesteps      | 3768320    |
| train/                  |            |
|    approx_kl            | 0.00449441 |
|    clip_fraction        | 0.00761    |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.753     |
|    explained_variance   | 0.867      |
|    learning_rate        | 0.0003     |
|    loss                 | 3.44e+03   |
|    n_updates            | 916        |
|    policy_gradient_loss | -0.00103   |
|    value_loss           | 4.58e+03   |
----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 123        |
|    ep_rew_mean          | 404        |
| time/                   |            |
|    fps                  | 1596       |
|    iterations           | 231        |
|    time_elapsed         | 2370       |
|    total_timesteps      | 3784704    |
| train/                  |            |
|    approx_kl            | 0.00306257 |
|    clip_fraction        | 0.0052     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.754     |
|    explained_variance   | 0.89       |
|    learning_rate        | 0.0003     |
|    loss                 | 1.31e+03   |
|    n_updates            | 920        |
|    policy_gradient_loss | -0.00132   |
|    value_loss           | 3.45e+03   |
----------------------------------------

Eval num_timesteps=3800000, episode_reward=425.67 +/- 215.94

Episode length: 119.35 +/- 26.64

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 119         |
|    mean_reward          | 426         |
| time/                   |             |
|    total_timesteps      | 3800000     |
| train/                  |             |
|    approx_kl            | 0.003931641 |
|    clip_fraction        | 0.00998     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.765      |
|    explained_variance   | 0.899       |
|    learning_rate        | 0.0003      |
|    loss                 | 915         |
|    n_updates            | 924         |
|    policy_gradient_loss | -0.000449   |
|    value_loss           | 3.66e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 416      |
| time/              |          |
|    fps             | 1595     |
|    iterations      | 232      |
|    time_elapsed    | 2382     |
|    total_timesteps | 3801088  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 421          |
| time/                   |              |
|    fps                  | 1596         |
|    iterations           | 233          |
|    time_elapsed         | 2390         |
|    total_timesteps      | 3817472      |
| train/                  |              |
|    approx_kl            | 0.0029303145 |
|    clip_fraction        | 0.00249      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.773       |
|    explained_variance   | 0.832        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.66e+03     |
|    n_updates            | 928          |
|    policy_gradient_loss | -0.000825    |
|    value_loss           | 5.24e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 393         |
| time/                   |             |
|    fps                  | 1597        |
|    iterations           | 234         |
|    time_elapsed         | 2400        |
|    total_timesteps      | 3833856     |
| train/                  |             |
|    approx_kl            | 0.004525688 |
|    clip_fraction        | 0.0197      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.777      |
|    explained_variance   | 0.899       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.67e+03    |
|    n_updates            | 932         |
|    policy_gradient_loss | -0.00037    |
|    value_loss           | 3.35e+03    |
-----------------------------------------

Eval num_timesteps=3850000, episode_reward=509.49 +/- 157.39

Episode length: 112.65 +/- 25.08

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | 509          |
| time/                   |              |
|    total_timesteps      | 3850000      |
| train/                  |              |
|    approx_kl            | 0.0026011255 |
|    clip_fraction        | 0.007        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.793        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.29e+03     |
|    n_updates            | 936          |
|    policy_gradient_loss | -4.71e-05    |
|    value_loss           | 6.94e+03     |
------------------------------------------

New best mean reward!

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 414          |
| time/                   |              |
|    fps                  | 1597         |
|    iterations           | 236          |
|    time_elapsed         | 2421         |
|    total_timesteps      | 3866624      |
| train/                  |              |
|    approx_kl            | 0.0036076764 |
|    clip_fraction        | 0.0139       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.774       |
|    explained_variance   | 0.838        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.96e+03     |
|    n_updates            | 940          |
|    policy_gradient_loss | -0.00207     |
|    value_loss           | 5.75e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 428          |
| time/                   |              |
|    fps                  | 1598         |
|    iterations           | 237          |
|    time_elapsed         | 2429         |
|    total_timesteps      | 3883008      |
| train/                  |              |
|    approx_kl            | 0.0025080354 |
|    clip_fraction        | 0.0076       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.799       |
|    explained_variance   | 0.844        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.57e+03     |
|    n_updates            | 944          |
|    policy_gradient_loss | -0.0011      |
|    value_loss           | 4.59e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 374          |
| time/                   |              |
|    fps                  | 1598         |
|    iterations           | 238          |
|    time_elapsed         | 2439         |
|    total_timesteps      | 3899392      |
| train/                  |              |
|    approx_kl            | 0.0038991135 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.805       |
|    explained_variance   | 0.884        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.21e+03     |
|    n_updates            | 948          |
|    policy_gradient_loss | -0.00114     |
|    value_loss           | 3.16e+03     |
------------------------------------------

Eval num_timesteps=3900000, episode_reward=408.42 +/- 196.72

Episode length: 131.05 +/- 31.58

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 408          |
| time/                   |              |
|    total_timesteps      | 3900000      |
| train/                  |              |
|    approx_kl            | 0.0057170903 |
|    clip_fraction        | 0.0349       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.784       |
|    explained_variance   | 0.806        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.38e+03     |
|    n_updates            | 952          |
|    policy_gradient_loss | -0.00291     |
|    value_loss           | 5.06e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_3900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 437      |
| time/              |          |
|    fps             | 1598     |
|    iterations      | 239      |
|    time_elapsed    | 2450     |
|    total_timesteps | 3915776  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 450          |
| time/                   |              |
|    fps                  | 1598         |
|    iterations           | 240          |
|    time_elapsed         | 2459         |
|    total_timesteps      | 3932160      |
| train/                  |              |
|    approx_kl            | 0.0035413043 |
|    clip_fraction        | 0.00671      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.84e+03     |
|    n_updates            | 956          |
|    policy_gradient_loss | -0.000474    |
|    value_loss           | 4.89e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 411         |
| time/                   |             |
|    fps                  | 1599        |
|    iterations           | 241         |
|    time_elapsed         | 2468        |
|    total_timesteps      | 3948544     |
| train/                  |             |
|    approx_kl            | 0.006415135 |
|    clip_fraction        | 0.0271      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.805      |
|    explained_variance   | 0.851       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.43e+03    |
|    n_updates            | 960         |
|    policy_gradient_loss | -0.002      |
|    value_loss           | 3.91e+03    |
-----------------------------------------

Eval num_timesteps=3950000, episode_reward=428.94 +/- 160.20

Episode length: 119.95 +/- 28.36

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 120         |
|    mean_reward          | 429         |
| time/                   |             |
|    total_timesteps      | 3950000     |
| train/                  |             |
|    approx_kl            | 0.004519473 |
|    clip_fraction        | 0.0127      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.774      |
|    explained_variance   | 0.864       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.29e+03    |
|    n_updates            | 964         |
|    policy_gradient_loss | -0.00113    |
|    value_loss           | 4.36e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 395      |
| time/              |          |
|    fps             | 1598     |
|    iterations      | 242      |
|    time_elapsed    | 2479     |
|    total_timesteps | 3964928  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 128        |
|    ep_rew_mean          | 434        |
| time/                   |            |
|    fps                  | 1599       |
|    iterations           | 243        |
|    time_elapsed         | 2489       |
|    total_timesteps      | 3981312    |
| train/                  |            |
|    approx_kl            | 0.00483788 |
|    clip_fraction        | 0.0143     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.78      |
|    explained_variance   | 0.875      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.8e+03    |
|    n_updates            | 968        |
|    policy_gradient_loss | -0.000979  |
|    value_loss           | 3.65e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 412         |
| time/                   |             |
|    fps                  | 1600        |
|    iterations           | 244         |
|    time_elapsed         | 2498        |
|    total_timesteps      | 3997696     |
| train/                  |             |
|    approx_kl            | 0.003855075 |
|    clip_fraction        | 0.00621     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.768      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.24e+03    |
|    n_updates            | 972         |
|    policy_gradient_loss | -0.000964   |
|    value_loss           | 3.77e+03    |
-----------------------------------------

Eval num_timesteps=4000000, episode_reward=361.37 +/- 154.08

Episode length: 127.50 +/- 27.93

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 361          |
| time/                   |              |
|    total_timesteps      | 4000000      |
| train/                  |              |
|    approx_kl            | 0.0046713073 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.774       |
|    explained_variance   | 0.833        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.75e+03     |
|    n_updates            | 976          |
|    policy_gradient_loss | -0.00208     |
|    value_loss           | 4.66e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 4,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 409      |
| time/              |          |
|    fps             | 1596     |
|    iterations      | 245      |
|    time_elapsed    | 2514     |
|    total_timesteps | 4014080  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 393         |
| time/                   |             |
|    fps                  | 1597        |
|    iterations           | 246         |
|    time_elapsed         | 2523        |
|    total_timesteps      | 4030464     |
| train/                  |             |
|    approx_kl            | 0.001747789 |
|    clip_fraction        | 0.0114      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.785      |
|    explained_variance   | 0.879       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.58e+03    |
|    n_updates            | 980         |
|    policy_gradient_loss | -0.000119   |
|    value_loss           | 2.83e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 400         |
| time/                   |             |
|    fps                  | 1597        |
|    iterations           | 247         |
|    time_elapsed         | 2532        |
|    total_timesteps      | 4046848     |
| train/                  |             |
|    approx_kl            | 0.004143489 |
|    clip_fraction        | 0.0228      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.775      |
|    explained_variance   | 0.895       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.25e+03    |
|    n_updates            | 984         |
|    policy_gradient_loss | -0.000625   |
|    value_loss           | 3.19e+03    |
-----------------------------------------

Eval num_timesteps=4050000, episode_reward=416.28 +/- 208.34

Episode length: 122.80 +/- 26.37

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 416          |
| time/                   |              |
|    total_timesteps      | 4050000      |
| train/                  |              |
|    approx_kl            | 0.0034723748 |
|    clip_fraction        | 0.00627      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.861        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.49e+03     |
|    n_updates            | 988          |
|    policy_gradient_loss | -0.000996    |
|    value_loss           | 4.38e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 419      |
| time/              |          |
|    fps             | 1597     |
|    iterations      | 248      |
|    time_elapsed    | 2544     |
|    total_timesteps | 4063232  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 438         |
| time/                   |             |
|    fps                  | 1597        |
|    iterations           | 249         |
|    time_elapsed         | 2553        |
|    total_timesteps      | 4079616     |
| train/                  |             |
|    approx_kl            | 0.004301104 |
|    clip_fraction        | 0.0122      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.26e+03    |
|    n_updates            | 992         |
|    policy_gradient_loss | -0.00129    |
|    value_loss           | 5.13e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 435          |
| time/                   |              |
|    fps                  | 1598         |
|    iterations           | 250          |
|    time_elapsed         | 2562         |
|    total_timesteps      | 4096000      |
| train/                  |              |
|    approx_kl            | 0.0054070004 |
|    clip_fraction        | 0.023        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.48e+03     |
|    n_updates            | 996          |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 3.38e+03     |
------------------------------------------

Eval num_timesteps=4100000, episode_reward=538.16 +/- 116.32

Episode length: 119.10 +/- 24.96

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 119         |
|    mean_reward          | 538         |
| time/                   |             |
|    total_timesteps      | 4100000     |
| train/                  |             |
|    approx_kl            | 0.005752446 |
|    clip_fraction        | 0.0555      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.774      |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.12e+03    |
|    n_updates            | 1000        |
|    policy_gradient_loss | -0.00202    |
|    value_loss           | 3.14e+03    |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 446      |
| time/              |          |
|    fps             | 1597     |
|    iterations      | 251      |
|    time_elapsed    | 2573     |
|    total_timesteps | 4112384  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 403          |
| time/                   |              |
|    fps                  | 1598         |
|    iterations           | 252          |
|    time_elapsed         | 2583         |
|    total_timesteps      | 4128768      |
| train/                  |              |
|    approx_kl            | 0.0044335155 |
|    clip_fraction        | 0.0135       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.876        |
|    learning_rate        | 0.0003       |
|    loss                 | 1e+03        |
|    n_updates            | 1004         |
|    policy_gradient_loss | -0.00137     |
|    value_loss           | 3.49e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 404          |
| time/                   |              |
|    fps                  | 1599         |
|    iterations           | 253          |
|    time_elapsed         | 2592         |
|    total_timesteps      | 4145152      |
| train/                  |              |
|    approx_kl            | 0.0025976123 |
|    clip_fraction        | 0.00505      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.81        |
|    explained_variance   | 0.864        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.45e+03     |
|    n_updates            | 1008         |
|    policy_gradient_loss | -0.000233    |
|    value_loss           | 4.53e+03     |
------------------------------------------

Eval num_timesteps=4150000, episode_reward=442.72 +/- 225.88

Episode length: 103.65 +/- 24.33

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | 443          |
| time/                   |              |
|    total_timesteps      | 4150000      |
| train/                  |              |
|    approx_kl            | 0.0025032493 |
|    clip_fraction        | 0.00943      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.65e+03     |
|    n_updates            | 1012         |
|    policy_gradient_loss | -0.00153     |
|    value_loss           | 5.77e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 405      |
| time/              |          |
|    fps             | 1598     |
|    iterations      | 254      |
|    time_elapsed    | 2602     |
|    total_timesteps | 4161536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 444          |
| time/                   |              |
|    fps                  | 1599         |
|    iterations           | 255          |
|    time_elapsed         | 2612         |
|    total_timesteps      | 4177920      |
| train/                  |              |
|    approx_kl            | 0.0025453365 |
|    clip_fraction        | 0.00645      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.876        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.17e+03     |
|    n_updates            | 1016         |
|    policy_gradient_loss | -0.00132     |
|    value_loss           | 3.57e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 417          |
| time/                   |              |
|    fps                  | 1599         |
|    iterations           | 256          |
|    time_elapsed         | 2621         |
|    total_timesteps      | 4194304      |
| train/                  |              |
|    approx_kl            | 0.0029710792 |
|    clip_fraction        | 0.00815      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.93e+03     |
|    n_updates            | 1020         |
|    policy_gradient_loss | -3.22e-05    |
|    value_loss           | 3.86e+03     |
------------------------------------------

Eval num_timesteps=4200000, episode_reward=465.90 +/- 155.42

Episode length: 129.70 +/- 32.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 130          |
|    mean_reward          | 466          |
| time/                   |              |
|    total_timesteps      | 4200000      |
| train/                  |              |
|    approx_kl            | 0.0020530846 |
|    clip_fraction        | 0.00345      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.868        |
|    learning_rate        | 0.0003       |
|    loss                 | 832          |
|    n_updates            | 1024         |
|    policy_gradient_loss | -1.27e-05    |
|    value_loss           | 4.5e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 408      |
| time/              |          |
|    fps             | 1599     |
|    iterations      | 257      |
|    time_elapsed    | 2633     |
|    total_timesteps | 4210688  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 423          |
| time/                   |              |
|    fps                  | 1600         |
|    iterations           | 258          |
|    time_elapsed         | 2641         |
|    total_timesteps      | 4227072      |
| train/                  |              |
|    approx_kl            | 0.0034146924 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.65e+03     |
|    n_updates            | 1028         |
|    policy_gradient_loss | -0.000721    |
|    value_loss           | 3.93e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 407         |
| time/                   |             |
|    fps                  | 1600        |
|    iterations           | 259         |
|    time_elapsed         | 2651        |
|    total_timesteps      | 4243456     |
| train/                  |             |
|    approx_kl            | 0.003476813 |
|    clip_fraction        | 0.0106      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.876       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.39e+03    |
|    n_updates            | 1032        |
|    policy_gradient_loss | -0.000149   |
|    value_loss           | 3.55e+03    |
-----------------------------------------

Eval num_timesteps=4250000, episode_reward=524.79 +/- 82.08

Episode length: 123.50 +/- 25.86

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 124          |
|    mean_reward          | 525          |
| time/                   |              |
|    total_timesteps      | 4250000      |
| train/                  |              |
|    approx_kl            | 0.0027803383 |
|    clip_fraction        | 0.0141       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.784       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.46e+03     |
|    n_updates            | 1036         |
|    policy_gradient_loss | -0.00217     |
|    value_loss           | 4.92e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 392      |
| time/              |          |
|    fps             | 1599     |
|    iterations      | 260      |
|    time_elapsed    | 2662     |
|    total_timesteps | 4259840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 422          |
| time/                   |              |
|    fps                  | 1600         |
|    iterations           | 261          |
|    time_elapsed         | 2671         |
|    total_timesteps      | 4276224      |
| train/                  |              |
|    approx_kl            | 0.0046815905 |
|    clip_fraction        | 0.0112       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.772       |
|    explained_variance   | 0.851        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.74e+03     |
|    n_updates            | 1040         |
|    policy_gradient_loss | -0.00136     |
|    value_loss           | 5.11e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 406          |
| time/                   |              |
|    fps                  | 1601         |
|    iterations           | 262          |
|    time_elapsed         | 2680         |
|    total_timesteps      | 4292608      |
| train/                  |              |
|    approx_kl            | 0.0038128272 |
|    clip_fraction        | 0.0192       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.29e+03     |
|    n_updates            | 1044         |
|    policy_gradient_loss | -0.000739    |
|    value_loss           | 3.33e+03     |
------------------------------------------

Eval num_timesteps=4300000, episode_reward=510.22 +/- 171.41

Episode length: 113.15 +/- 23.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | 510          |
| time/                   |              |
|    total_timesteps      | 4300000      |
| train/                  |              |
|    approx_kl            | 0.0011914633 |
|    clip_fraction        | 0.00139      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.54e+03     |
|    n_updates            | 1048         |
|    policy_gradient_loss | 6.8e-05      |
|    value_loss           | 4.64e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 397      |
| time/              |          |
|    fps             | 1600     |
|    iterations      | 263      |
|    time_elapsed    | 2692     |
|    total_timesteps | 4308992  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 468         |
| time/                   |             |
|    fps                  | 1600        |
|    iterations           | 264         |
|    time_elapsed         | 2701        |
|    total_timesteps      | 4325376     |
| train/                  |             |
|    approx_kl            | 0.004402534 |
|    clip_fraction        | 0.00916     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.779      |
|    explained_variance   | 0.799       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.32e+03    |
|    n_updates            | 1052        |
|    policy_gradient_loss | -0.00148    |
|    value_loss           | 6.36e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 478          |
| time/                   |              |
|    fps                  | 1601         |
|    iterations           | 265          |
|    time_elapsed         | 2710         |
|    total_timesteps      | 4341760      |
| train/                  |              |
|    approx_kl            | 0.0018921121 |
|    clip_fraction        | 0.00215      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 1056         |
|    policy_gradient_loss | -3.71e-06    |
|    value_loss           | 3.13e+03     |
------------------------------------------

Eval num_timesteps=4350000, episode_reward=435.68 +/- 180.08

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 121          |
|    mean_reward          | 436          |
| time/                   |              |
|    total_timesteps      | 4350000      |
| train/                  |              |
|    approx_kl            | 0.0047839587 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 640          |
|    n_updates            | 1060         |
|    policy_gradient_loss | -0.00134     |
|    value_loss           | 2.76e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 403      |
| time/              |          |
|    fps             | 1601     |
|    iterations      | 266      |
|    time_elapsed    | 2721     |
|    total_timesteps | 4358144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 376         |
| time/                   |             |
|    fps                  | 1601        |
|    iterations           | 267         |
|    time_elapsed         | 2731        |
|    total_timesteps      | 4374528     |
| train/                  |             |
|    approx_kl            | 0.005963946 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.769      |
|    explained_variance   | 0.811       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.17e+03    |
|    n_updates            | 1064        |
|    policy_gradient_loss | -0.00286    |
|    value_loss           | 6.22e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 406         |
| time/                   |             |
|    fps                  | 1601        |
|    iterations           | 268         |
|    time_elapsed         | 2741        |
|    total_timesteps      | 4390912     |
| train/                  |             |
|    approx_kl            | 0.004255755 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.775      |
|    explained_variance   | 0.907       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.41e+03    |
|    n_updates            | 1068        |
|    policy_gradient_loss | -0.00163    |
|    value_loss           | 3.05e+03    |
-----------------------------------------

Eval num_timesteps=4400000, episode_reward=378.68 +/- 229.88

Episode length: 116.90 +/- 31.65

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 379          |
| time/                   |              |
|    total_timesteps      | 4400000      |
| train/                  |              |
|    approx_kl            | 0.0022997982 |
|    clip_fraction        | 0.00891      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.53e+03     |
|    n_updates            | 1072         |
|    policy_gradient_loss | -0.00071     |
|    value_loss           | 4.32e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 441      |
| time/              |          |
|    fps             | 1601     |
|    iterations      | 269      |
|    time_elapsed    | 2751     |
|    total_timesteps | 4407296  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 418         |
| time/                   |             |
|    fps                  | 1602        |
|    iterations           | 270         |
|    time_elapsed         | 2760        |
|    total_timesteps      | 4423680     |
| train/                  |             |
|    approx_kl            | 0.006742833 |
|    clip_fraction        | 0.0235      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.769      |
|    explained_variance   | 0.84        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.21e+03    |
|    n_updates            | 1076        |
|    policy_gradient_loss | -0.00219    |
|    value_loss           | 5.29e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 443          |
| time/                   |              |
|    fps                  | 1602         |
|    iterations           | 271          |
|    time_elapsed         | 2770         |
|    total_timesteps      | 4440064      |
| train/                  |              |
|    approx_kl            | 0.0027965172 |
|    clip_fraction        | 0.00847      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.837        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 1080         |
|    policy_gradient_loss | -9.25e-05    |
|    value_loss           | 4.46e+03     |
------------------------------------------

Eval num_timesteps=4450000, episode_reward=478.56 +/- 185.72

Episode length: 118.75 +/- 33.95

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 119         |
|    mean_reward          | 479         |
| time/                   |             |
|    total_timesteps      | 4450000     |
| train/                  |             |
|    approx_kl            | 0.005422455 |
|    clip_fraction        | 0.0343      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.786      |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | 868         |
|    n_updates            | 1084        |
|    policy_gradient_loss | -0.00147    |
|    value_loss           | 2.15e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 403      |
| time/              |          |
|    fps             | 1602     |
|    iterations      | 272      |
|    time_elapsed    | 2781     |
|    total_timesteps | 4456448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 391          |
| time/                   |              |
|    fps                  | 1603         |
|    iterations           | 273          |
|    time_elapsed         | 2790         |
|    total_timesteps      | 4472832      |
| train/                  |              |
|    approx_kl            | 0.0033216872 |
|    clip_fraction        | 0.00616      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.8          |
|    learning_rate        | 0.0003       |
|    loss                 | 4.52e+03     |
|    n_updates            | 1088         |
|    policy_gradient_loss | -0.00161     |
|    value_loss           | 6.44e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 425         |
| time/                   |             |
|    fps                  | 1603        |
|    iterations           | 274         |
|    time_elapsed         | 2799        |
|    total_timesteps      | 4489216     |
| train/                  |             |
|    approx_kl            | 0.004086614 |
|    clip_fraction        | 0.011       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.787      |
|    explained_variance   | 0.851       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.07e+03    |
|    n_updates            | 1092        |
|    policy_gradient_loss | -0.000959   |
|    value_loss           | 5.05e+03    |
-----------------------------------------

Eval num_timesteps=4500000, episode_reward=503.14 +/- 167.46

Episode length: 115.95 +/- 32.30

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 116         |
|    mean_reward          | 503         |
| time/                   |             |
|    total_timesteps      | 4500000     |
| train/                  |             |
|    approx_kl            | 0.005013125 |
|    clip_fraction        | 0.0134      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.798      |
|    explained_variance   | 0.864       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.26e+03    |
|    n_updates            | 1096        |
|    policy_gradient_loss | -0.00128    |
|    value_loss           | 4.08e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 420      |
| time/              |          |
|    fps             | 1602     |
|    iterations      | 275      |
|    time_elapsed    | 2811     |
|    total_timesteps | 4505600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 468          |
| time/                   |              |
|    fps                  | 1603         |
|    iterations           | 276          |
|    time_elapsed         | 2820         |
|    total_timesteps      | 4521984      |
| train/                  |              |
|    approx_kl            | 0.0027301777 |
|    clip_fraction        | 0.00613      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.772       |
|    explained_variance   | 0.842        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.39e+03     |
|    n_updates            | 1100         |
|    policy_gradient_loss | -0.000947    |
|    value_loss           | 5.45e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 427         |
| time/                   |             |
|    fps                  | 1604        |
|    iterations           | 277         |
|    time_elapsed         | 2829        |
|    total_timesteps      | 4538368     |
| train/                  |             |
|    approx_kl            | 0.003598799 |
|    clip_fraction        | 0.0213      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.918       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08e+03    |
|    n_updates            | 1104        |
|    policy_gradient_loss | -0.00155    |
|    value_loss           | 2.09e+03    |
-----------------------------------------

Eval num_timesteps=4550000, episode_reward=424.03 +/- 194.23

Episode length: 116.90 +/- 26.94

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 424          |
| time/                   |              |
|    total_timesteps      | 4550000      |
| train/                  |              |
|    approx_kl            | 0.0037323083 |
|    clip_fraction        | 0.0125       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.847        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.8e+03      |
|    n_updates            | 1108         |
|    policy_gradient_loss | -0.0016      |
|    value_loss           | 3.85e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 422      |
| time/              |          |
|    fps             | 1603     |
|    iterations      | 278      |
|    time_elapsed    | 2840     |
|    total_timesteps | 4554752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 413          |
| time/                   |              |
|    fps                  | 1603         |
|    iterations           | 279          |
|    time_elapsed         | 2850         |
|    total_timesteps      | 4571136      |
| train/                  |              |
|    approx_kl            | 0.0016126828 |
|    clip_fraction        | 0.00478      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 620          |
|    n_updates            | 1112         |
|    policy_gradient_loss | 0.000202     |
|    value_loss           | 3.2e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 389          |
| time/                   |              |
|    fps                  | 1604         |
|    iterations           | 280          |
|    time_elapsed         | 2859         |
|    total_timesteps      | 4587520      |
| train/                  |              |
|    approx_kl            | 0.0042746766 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.813        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.08e+03     |
|    n_updates            | 1116         |
|    policy_gradient_loss | -0.00238     |
|    value_loss           | 5.46e+03     |
------------------------------------------

Eval num_timesteps=4600000, episode_reward=480.59 +/- 158.87

Episode length: 113.75 +/- 19.65

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 114         |
|    mean_reward          | 481         |
| time/                   |             |
|    total_timesteps      | 4600000     |
| train/                  |             |
|    approx_kl            | 0.004848925 |
|    clip_fraction        | 0.0122      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.761      |
|    explained_variance   | 0.826       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.76e+03    |
|    n_updates            | 1120        |
|    policy_gradient_loss | -0.00142    |
|    value_loss           | 5.96e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 423      |
| time/              |          |
|    fps             | 1603     |
|    iterations      | 281      |
|    time_elapsed    | 2870     |
|    total_timesteps | 4603904  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 478         |
| time/                   |             |
|    fps                  | 1604        |
|    iterations           | 282         |
|    time_elapsed         | 2880        |
|    total_timesteps      | 4620288     |
| train/                  |             |
|    approx_kl            | 0.004936955 |
|    clip_fraction        | 0.0206      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.776      |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.8e+03     |
|    n_updates            | 1124        |
|    policy_gradient_loss | -0.000876   |
|    value_loss           | 4.08e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 425          |
| time/                   |              |
|    fps                  | 1604         |
|    iterations           | 283          |
|    time_elapsed         | 2889         |
|    total_timesteps      | 4636672      |
| train/                  |              |
|    approx_kl            | 0.0023184272 |
|    clip_fraction        | 0.00227      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.813        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.97e+03     |
|    n_updates            | 1128         |
|    policy_gradient_loss | -0.000369    |
|    value_loss           | 5.26e+03     |
------------------------------------------

Eval num_timesteps=4650000, episode_reward=524.55 +/- 122.23

Episode length: 110.40 +/- 23.56

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 525          |
| time/                   |              |
|    total_timesteps      | 4650000      |
| train/                  |              |
|    approx_kl            | 0.0037015933 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.741       |
|    explained_variance   | 0.836        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.69e+03     |
|    n_updates            | 1132         |
|    policy_gradient_loss | -0.00135     |
|    value_loss           | 4.84e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 448      |
| time/              |          |
|    fps             | 1603     |
|    iterations      | 284      |
|    time_elapsed    | 2900     |
|    total_timesteps | 4653056  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 445         |
| time/                   |             |
|    fps                  | 1604        |
|    iterations           | 285         |
|    time_elapsed         | 2909        |
|    total_timesteps      | 4669440     |
| train/                  |             |
|    approx_kl            | 0.001113416 |
|    clip_fraction        | 0.00299     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.735      |
|    explained_variance   | 0.839       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.23e+03    |
|    n_updates            | 1136        |
|    policy_gradient_loss | 0.000345    |
|    value_loss           | 4.04e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 428          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 286          |
|    time_elapsed         | 2919         |
|    total_timesteps      | 4685824      |
| train/                  |              |
|    approx_kl            | 0.0019733766 |
|    clip_fraction        | 0.0097       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.746       |
|    explained_variance   | 0.884        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.77e+03     |
|    n_updates            | 1140         |
|    policy_gradient_loss | -0.000345    |
|    value_loss           | 3.5e+03      |
------------------------------------------

Eval num_timesteps=4700000, episode_reward=579.72 +/- 52.71

Episode length: 123.60 +/- 29.64

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 124          |
|    mean_reward          | 580          |
| time/                   |              |
|    total_timesteps      | 4700000      |
| train/                  |              |
|    approx_kl            | 0.0035395296 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.747       |
|    explained_variance   | 0.864        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.63e+03     |
|    n_updates            | 1144         |
|    policy_gradient_loss | -0.000643    |
|    value_loss           | 4.39e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 448      |
| time/              |          |
|    fps             | 1604     |
|    iterations      | 287      |
|    time_elapsed    | 2930     |
|    total_timesteps | 4702208  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 454          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 289          |
|    time_elapsed         | 2949         |
|    total_timesteps      | 4734976      |
| train/                  |              |
|    approx_kl            | 0.0055428804 |
|    clip_fraction        | 0.0381       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.747       |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55e+03     |
|    n_updates            | 1152         |
|    policy_gradient_loss | -0.00243     |
|    value_loss           | 3.56e+03     |
------------------------------------------

Eval num_timesteps=4750000, episode_reward=436.07 +/- 218.55

Episode length: 117.50 +/- 28.14

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | 436          |
| time/                   |              |
|    total_timesteps      | 4750000      |
| train/                  |              |
|    approx_kl            | 0.0042339102 |
|    clip_fraction        | 0.017        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.8          |
|    learning_rate        | 0.0003       |
|    loss                 | 3.68e+03     |
|    n_updates            | 1156         |
|    policy_gradient_loss | -0.0014      |
|    value_loss           | 5.21e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 474      |
| time/              |          |
|    fps             | 1604     |
|    iterations      | 290      |
|    time_elapsed    | 2960     |
|    total_timesteps | 4751360  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 124        |
|    ep_rew_mean          | 428        |
| time/                   |            |
|    fps                  | 1605       |
|    iterations           | 291        |
|    time_elapsed         | 2970       |
|    total_timesteps      | 4767744    |
| train/                  |            |
|    approx_kl            | 0.00482482 |
|    clip_fraction        | 0.0268     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.763     |
|    explained_variance   | 0.9        |
|    learning_rate        | 0.0003     |
|    loss                 | 819        |
|    n_updates            | 1160       |
|    policy_gradient_loss | -0.00153   |
|    value_loss           | 3.29e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 467          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 292          |
|    time_elapsed         | 2979         |
|    total_timesteps      | 4784128      |
| train/                  |              |
|    approx_kl            | 0.0034075603 |
|    clip_fraction        | 0.0203       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.758       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 692          |
|    n_updates            | 1164         |
|    policy_gradient_loss | -0.00249     |
|    value_loss           | 4.02e+03     |
------------------------------------------

Eval num_timesteps=4800000, episode_reward=540.74 +/- 173.26

Episode length: 111.20 +/- 19.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 541          |
| time/                   |              |
|    total_timesteps      | 4800000      |
| train/                  |              |
|    approx_kl            | 0.0055610663 |
|    clip_fraction        | 0.0398       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.794       |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 371          |
|    n_updates            | 1168         |
|    policy_gradient_loss | -0.00243     |
|    value_loss           | 2.61e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 422      |
| time/              |          |
|    fps             | 1605     |
|    iterations      | 293      |
|    time_elapsed    | 2990     |
|    total_timesteps | 4800512  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 437          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 294          |
|    time_elapsed         | 3000         |
|    total_timesteps      | 4816896      |
| train/                  |              |
|    approx_kl            | 0.0050872825 |
|    clip_fraction        | 0.0144       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.761       |
|    explained_variance   | 0.811        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.39e+03     |
|    n_updates            | 1172         |
|    policy_gradient_loss | -0.00166     |
|    value_loss           | 5.86e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 449          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 295          |
|    time_elapsed         | 3009         |
|    total_timesteps      | 4833280      |
| train/                  |              |
|    approx_kl            | 0.0029386273 |
|    clip_fraction        | 0.0061       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.754       |
|    explained_variance   | 0.866        |
|    learning_rate        | 0.0003       |
|    loss                 | 914          |
|    n_updates            | 1176         |
|    policy_gradient_loss | -0.000508    |
|    value_loss           | 3.72e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 453          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 296          |
|    time_elapsed         | 3017         |
|    total_timesteps      | 4849664      |
| train/                  |              |
|    approx_kl            | 0.0026539825 |
|    clip_fraction        | 0.0141       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.882        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.32e+03     |
|    n_updates            | 1180         |
|    policy_gradient_loss | -0.00117     |
|    value_loss           | 2.9e+03      |
------------------------------------------

Eval num_timesteps=4850000, episode_reward=554.80 +/- 56.95

Episode length: 124.60 +/- 32.38

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 125         |
|    mean_reward          | 555         |
| time/                   |             |
|    total_timesteps      | 4850000     |
| train/                  |             |
|    approx_kl            | 0.002548607 |
|    clip_fraction        | 0.0104      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.775      |
|    explained_variance   | 0.924       |
|    learning_rate        | 0.0003      |
|    loss                 | 357         |
|    n_updates            | 1184        |
|    policy_gradient_loss | -0.000669   |
|    value_loss           | 1.55e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 410      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 297      |
|    time_elapsed    | 3029     |
|    total_timesteps | 4866048  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 464         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 298         |
|    time_elapsed         | 3039        |
|    total_timesteps      | 4882432     |
| train/                  |             |
|    approx_kl            | 0.004302638 |
|    clip_fraction        | 0.0126      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.74       |
|    explained_variance   | 0.843       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.16e+03    |
|    n_updates            | 1188        |
|    policy_gradient_loss | -0.000511   |
|    value_loss           | 3.95e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 456          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 299          |
|    time_elapsed         | 3048         |
|    total_timesteps      | 4898816      |
| train/                  |              |
|    approx_kl            | 0.0025715097 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.767       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.62e+03     |
|    n_updates            | 1192         |
|    policy_gradient_loss | -0.00281     |
|    value_loss           | 5.6e+03      |
------------------------------------------

Eval num_timesteps=4900000, episode_reward=481.44 +/- 181.88

Episode length: 119.05 +/- 32.88

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 119         |
|    mean_reward          | 481         |
| time/                   |             |
|    total_timesteps      | 4900000     |
| train/                  |             |
|    approx_kl            | 0.003087656 |
|    clip_fraction        | 0.00177     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.767      |
|    explained_variance   | 0.855       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.77e+03    |
|    n_updates            | 1196        |
|    policy_gradient_loss | 3.83e-05    |
|    value_loss           | 4.24e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_4900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 449      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 300      |
|    time_elapsed    | 3059     |
|    total_timesteps | 4915200  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 439          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 301          |
|    time_elapsed         | 3068         |
|    total_timesteps      | 4931584      |
| train/                  |              |
|    approx_kl            | 0.0045156525 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.751       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.04e+03     |
|    n_updates            | 1200         |
|    policy_gradient_loss | -0.000749    |
|    value_loss           | 3.04e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 454          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 302          |
|    time_elapsed         | 3078         |
|    total_timesteps      | 4947968      |
| train/                  |              |
|    approx_kl            | 0.0026926203 |
|    clip_fraction        | 0.00761      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.759       |
|    explained_variance   | 0.844        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.5e+03      |
|    n_updates            | 1204         |
|    policy_gradient_loss | -1.81e-05    |
|    value_loss           | 4.75e+03     |
------------------------------------------

Eval num_timesteps=4950000, episode_reward=524.02 +/- 151.77

Episode length: 120.20 +/- 22.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 524          |
| time/                   |              |
|    total_timesteps      | 4950000      |
| train/                  |              |
|    approx_kl            | 0.0031367831 |
|    clip_fraction        | 0.00691      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.737       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.09e+03     |
|    n_updates            | 1208         |
|    policy_gradient_loss | -0.000681    |
|    value_loss           | 4.82e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 457      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 303      |
|    time_elapsed    | 3089     |
|    total_timesteps | 4964352  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 454          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 304          |
|    time_elapsed         | 3098         |
|    total_timesteps      | 4980736      |
| train/                  |              |
|    approx_kl            | 0.0037180213 |
|    clip_fraction        | 0.00818      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.756       |
|    explained_variance   | 0.826        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.77e+03     |
|    n_updates            | 1212         |
|    policy_gradient_loss | -0.00168     |
|    value_loss           | 5.06e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 412         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 305         |
|    time_elapsed         | 3107        |
|    total_timesteps      | 4997120     |
| train/                  |             |
|    approx_kl            | 0.003066257 |
|    clip_fraction        | 0.00795     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.736      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.1e+03     |
|    n_updates            | 1216        |
|    policy_gradient_loss | -0.000635   |
|    value_loss           | 3.65e+03    |
-----------------------------------------

Eval num_timesteps=5000000, episode_reward=498.34 +/- 125.41

Episode length: 130.85 +/- 38.08

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 131         |
|    mean_reward          | 498         |
| time/                   |             |
|    total_timesteps      | 5000000     |
| train/                  |             |
|    approx_kl            | 0.006599929 |
|    clip_fraction        | 0.0242      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.747      |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.18e+03    |
|    n_updates            | 1220        |
|    policy_gradient_loss | -0.00193    |
|    value_loss           | 5.36e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 5,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 425      |
| time/              |          |
|    fps             | 1605     |
|    iterations      | 306      |
|    time_elapsed    | 3123     |
|    total_timesteps | 5013504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 447          |
| time/                   |              |
|    fps                  | 1605         |
|    iterations           | 307          |
|    time_elapsed         | 3132         |
|    total_timesteps      | 5029888      |
| train/                  |              |
|    approx_kl            | 0.0052292915 |
|    clip_fraction        | 0.0127       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.734       |
|    explained_variance   | 0.857        |
|    learning_rate        | 0.0003       |
|    loss                 | 891          |
|    n_updates            | 1224         |
|    policy_gradient_loss | -0.000714    |
|    value_loss           | 4.76e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 451         |
| time/                   |             |
|    fps                  | 1605        |
|    iterations           | 308         |
|    time_elapsed         | 3142        |
|    total_timesteps      | 5046272     |
| train/                  |             |
|    approx_kl            | 0.003776352 |
|    clip_fraction        | 0.021       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.761      |
|    explained_variance   | 0.899       |
|    learning_rate        | 0.0003      |
|    loss                 | 765         |
|    n_updates            | 1228        |
|    policy_gradient_loss | -0.000841   |
|    value_loss           | 2.43e+03    |
-----------------------------------------

Eval num_timesteps=5050000, episode_reward=500.12 +/- 221.48

Episode length: 112.05 +/- 22.03

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 500          |
| time/                   |              |
|    total_timesteps      | 5050000      |
| train/                  |              |
|    approx_kl            | 0.0022822255 |
|    clip_fraction        | 0.00563      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.914        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.1e+03      |
|    n_updates            | 1232         |
|    policy_gradient_loss | 0.000112     |
|    value_loss           | 2.8e+03      |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 434      |
| time/              |          |
|    fps             | 1605     |
|    iterations      | 309      |
|    time_elapsed    | 3153     |
|    total_timesteps | 5062656  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 409          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 310          |
|    time_elapsed         | 3162         |
|    total_timesteps      | 5079040      |
| train/                  |              |
|    approx_kl            | 0.0029966866 |
|    clip_fraction        | 0.009        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.729       |
|    explained_variance   | 0.835        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.43e+03     |
|    n_updates            | 1236         |
|    policy_gradient_loss | -0.00113     |
|    value_loss           | 5.53e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 436          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 311          |
|    time_elapsed         | 3171         |
|    total_timesteps      | 5095424      |
| train/                  |              |
|    approx_kl            | 0.0049857134 |
|    clip_fraction        | 0.0122       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.75        |
|    explained_variance   | 0.841        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.87e+03     |
|    n_updates            | 1240         |
|    policy_gradient_loss | -0.000987    |
|    value_loss           | 4.86e+03     |
------------------------------------------

Eval num_timesteps=5100000, episode_reward=496.72 +/- 189.24

Episode length: 112.35 +/- 24.42

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 112         |
|    mean_reward          | 497         |
| time/                   |             |
|    total_timesteps      | 5100000     |
| train/                  |             |
|    approx_kl            | 0.004109851 |
|    clip_fraction        | 0.0132      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.762      |
|    explained_variance   | 0.873       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.01e+03    |
|    n_updates            | 1244        |
|    policy_gradient_loss | -0.000425   |
|    value_loss           | 3.45e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 455      |
| time/              |          |
|    fps             | 1605     |
|    iterations      | 312      |
|    time_elapsed    | 3183     |
|    total_timesteps | 5111808  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 446         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 313         |
|    time_elapsed         | 3191        |
|    total_timesteps      | 5128192     |
| train/                  |             |
|    approx_kl            | 0.003342703 |
|    clip_fraction        | 0.00851     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.774      |
|    explained_variance   | 0.879       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.97e+03    |
|    n_updates            | 1248        |
|    policy_gradient_loss | -0.00075    |
|    value_loss           | 4.38e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 465          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 314          |
|    time_elapsed         | 3201         |
|    total_timesteps      | 5144576      |
| train/                  |              |
|    approx_kl            | 0.0049055386 |
|    clip_fraction        | 0.027        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.756       |
|    explained_variance   | 0.904        |
|    learning_rate        | 0.0003       |
|    loss                 | 689          |
|    n_updates            | 1252         |
|    policy_gradient_loss | -0.00101     |
|    value_loss           | 2.1e+03      |
------------------------------------------

Eval num_timesteps=5150000, episode_reward=517.72 +/- 224.00

Episode length: 114.35 +/- 23.65

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 114         |
|    mean_reward          | 518         |
| time/                   |             |
|    total_timesteps      | 5150000     |
| train/                  |             |
|    approx_kl            | 0.005783084 |
|    clip_fraction        | 0.0382      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.783      |
|    explained_variance   | 0.877       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.03e+03    |
|    n_updates            | 1256        |
|    policy_gradient_loss | -0.00184    |
|    value_loss           | 3.32e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 445      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 315      |
|    time_elapsed    | 3212     |
|    total_timesteps | 5160960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 473          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 316          |
|    time_elapsed         | 3222         |
|    total_timesteps      | 5177344      |
| train/                  |              |
|    approx_kl            | 0.0026563162 |
|    clip_fraction        | 0.00641      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.75        |
|    explained_variance   | 0.772        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 1260         |
|    policy_gradient_loss | -0.00118     |
|    value_loss           | 5.97e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 441          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 317          |
|    time_elapsed         | 3230         |
|    total_timesteps      | 5193728      |
| train/                  |              |
|    approx_kl            | 0.0016927158 |
|    clip_fraction        | 0.00444      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.841        |
|    learning_rate        | 0.0003       |
|    loss                 | 3e+03        |
|    n_updates            | 1264         |
|    policy_gradient_loss | 0.000242     |
|    value_loss           | 4.55e+03     |
------------------------------------------

Eval num_timesteps=5200000, episode_reward=515.08 +/- 152.57

Episode length: 127.80 +/- 25.88

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 515          |
| time/                   |              |
|    total_timesteps      | 5200000      |
| train/                  |              |
|    approx_kl            | 0.0032774387 |
|    clip_fraction        | 0.0152       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.764       |
|    explained_variance   | 0.862        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.04e+03     |
|    n_updates            | 1268         |
|    policy_gradient_loss | -0.000973    |
|    value_loss           | 3.9e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 464      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 318      |
|    time_elapsed    | 3242     |
|    total_timesteps | 5210112  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 456          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 319          |
|    time_elapsed         | 3251         |
|    total_timesteps      | 5226496      |
| train/                  |              |
|    approx_kl            | 0.0021167693 |
|    clip_fraction        | 0.0139       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.754       |
|    explained_variance   | 0.817        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.8e+03      |
|    n_updates            | 1272         |
|    policy_gradient_loss | -0.00142     |
|    value_loss           | 5.03e+03     |
------------------------------------------

Eval num_timesteps=5250000, episode_reward=560.06 +/- 123.68

Episode length: 136.60 +/- 35.16

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 137          |
|    mean_reward          | 560          |
| time/                   |              |
|    total_timesteps      | 5250000      |
| train/                  |              |
|    approx_kl            | 0.0021063485 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.749       |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 1280         |
|    policy_gradient_loss | -0.000493    |
|    value_loss           | 3.39e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 428      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 321      |
|    time_elapsed    | 3272     |
|    total_timesteps | 5259264  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 449          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 322          |
|    time_elapsed         | 3281         |
|    total_timesteps      | 5275648      |
| train/                  |              |
|    approx_kl            | 0.0047834814 |
|    clip_fraction        | 0.0213       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.772       |
|    explained_variance   | 0.895        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.04e+03     |
|    n_updates            | 1284         |
|    policy_gradient_loss | -0.000992    |
|    value_loss           | 3.33e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 429          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 323          |
|    time_elapsed         | 3291         |
|    total_timesteps      | 5292032      |
| train/                  |              |
|    approx_kl            | 0.0035758785 |
|    clip_fraction        | 0.0129       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.82         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.95e+03     |
|    n_updates            | 1288         |
|    policy_gradient_loss | -0.00168     |
|    value_loss           | 5.19e+03     |
------------------------------------------

Eval num_timesteps=5300000, episode_reward=389.94 +/- 310.53

Episode length: 112.35 +/- 22.27

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 390          |
| time/                   |              |
|    total_timesteps      | 5300000      |
| train/                  |              |
|    approx_kl            | 0.0030062478 |
|    clip_fraction        | 0.00922      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.742       |
|    explained_variance   | 0.903        |
|    learning_rate        | 0.0003       |
|    loss                 | 526          |
|    n_updates            | 1292         |
|    policy_gradient_loss | 0.000126     |
|    value_loss           | 2.78e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 404      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 324      |
|    time_elapsed    | 3302     |
|    total_timesteps | 5308416  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 436         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 325         |
|    time_elapsed         | 3311        |
|    total_timesteps      | 5324800     |
| train/                  |             |
|    approx_kl            | 0.002856964 |
|    clip_fraction        | 0.00822     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.775      |
|    explained_variance   | 0.825       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.94e+03    |
|    n_updates            | 1296        |
|    policy_gradient_loss | -0.000815   |
|    value_loss           | 4.63e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 428          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 326          |
|    time_elapsed         | 3321         |
|    total_timesteps      | 5341184      |
| train/                  |              |
|    approx_kl            | 0.0058970423 |
|    clip_fraction        | 0.039        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.4e+03      |
|    n_updates            | 1300         |
|    policy_gradient_loss | -0.0016      |
|    value_loss           | 3.71e+03     |
------------------------------------------

Eval num_timesteps=5350000, episode_reward=509.97 +/- 121.25

Episode length: 127.90 +/- 29.47

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 510          |
| time/                   |              |
|    total_timesteps      | 5350000      |
| train/                  |              |
|    approx_kl            | 0.0056595905 |
|    clip_fraction        | 0.0176       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.801        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.09e+03     |
|    n_updates            | 1304         |
|    policy_gradient_loss | -0.00202     |
|    value_loss           | 5.47e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 417      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 327      |
|    time_elapsed    | 3333     |
|    total_timesteps | 5357568  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 463          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 328          |
|    time_elapsed         | 3342         |
|    total_timesteps      | 5373952      |
| train/                  |              |
|    approx_kl            | 0.0041277315 |
|    clip_fraction        | 0.0185       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.746       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 1308         |
|    policy_gradient_loss | -0.00144     |
|    value_loss           | 3.55e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 438         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 329         |
|    time_elapsed         | 3351        |
|    total_timesteps      | 5390336     |
| train/                  |             |
|    approx_kl            | 0.004157671 |
|    clip_fraction        | 0.0335      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.773      |
|    explained_variance   | 0.906       |
|    learning_rate        | 0.0003      |
|    loss                 | 756         |
|    n_updates            | 1312        |
|    policy_gradient_loss | -0.00156    |
|    value_loss           | 2.24e+03    |
-----------------------------------------

Eval num_timesteps=5400000, episode_reward=468.36 +/- 234.80

Episode length: 121.95 +/- 27.14

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | 468          |
| time/                   |              |
|    total_timesteps      | 5400000      |
| train/                  |              |
|    approx_kl            | 0.0049921153 |
|    clip_fraction        | 0.0231       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 911          |
|    n_updates            | 1316         |
|    policy_gradient_loss | -0.000828    |
|    value_loss           | 3.88e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 398      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 330      |
|    time_elapsed    | 3363     |
|    total_timesteps | 5406720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 468          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 331          |
|    time_elapsed         | 3372         |
|    total_timesteps      | 5423104      |
| train/                  |              |
|    approx_kl            | 0.0036811694 |
|    clip_fraction        | 0.00485      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.797        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.62e+03     |
|    n_updates            | 1320         |
|    policy_gradient_loss | -0.00069     |
|    value_loss           | 5.5e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 439         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 332         |
|    time_elapsed         | 3382        |
|    total_timesteps      | 5439488     |
| train/                  |             |
|    approx_kl            | 0.004025328 |
|    clip_fraction        | 0.00706     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.781      |
|    explained_variance   | 0.862       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.41e+03    |
|    n_updates            | 1324        |
|    policy_gradient_loss | 0.000181    |
|    value_loss           | 3.7e+03     |
-----------------------------------------

Eval num_timesteps=5450000, episode_reward=531.21 +/- 205.38

Episode length: 130.25 +/- 26.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 130          |
|    mean_reward          | 531          |
| time/                   |              |
|    total_timesteps      | 5450000      |
| train/                  |              |
|    approx_kl            | 0.0007750343 |
|    clip_fraction        | 0.00246      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.769       |
|    explained_variance   | 0.868        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.74e+03     |
|    n_updates            | 1328         |
|    policy_gradient_loss | -0.00038     |
|    value_loss           | 3.96e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 462      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 333      |
|    time_elapsed    | 3394     |
|    total_timesteps | 5455872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 458          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 334          |
|    time_elapsed         | 3403         |
|    total_timesteps      | 5472256      |
| train/                  |              |
|    approx_kl            | 0.0018687204 |
|    clip_fraction        | 0.00415      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.765       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.41e+03     |
|    n_updates            | 1332         |
|    policy_gradient_loss | -6.34e-05    |
|    value_loss           | 3.39e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 448          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 335          |
|    time_elapsed         | 3413         |
|    total_timesteps      | 5488640      |
| train/                  |              |
|    approx_kl            | 0.0031540645 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.767       |
|    explained_variance   | 0.807        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 1336         |
|    policy_gradient_loss | -0.00211     |
|    value_loss           | 4.38e+03     |
------------------------------------------

Eval num_timesteps=5500000, episode_reward=556.56 +/- 37.56

Episode length: 134.30 +/- 26.18

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 134         |
|    mean_reward          | 557         |
| time/                   |             |
|    total_timesteps      | 5500000     |
| train/                  |             |
|    approx_kl            | 0.002466475 |
|    clip_fraction        | 0.0103      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.806      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.17e+03    |
|    n_updates            | 1340        |
|    policy_gradient_loss | -0.000422   |
|    value_loss           | 3.51e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 460      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 336      |
|    time_elapsed    | 3425     |
|    total_timesteps | 5505024  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 430         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 337         |
|    time_elapsed         | 3434        |
|    total_timesteps      | 5521408     |
| train/                  |             |
|    approx_kl            | 0.004806291 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.801      |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.43e+03    |
|    n_updates            | 1344        |
|    policy_gradient_loss | -0.00118    |
|    value_loss           | 2.68e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 462          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 338          |
|    time_elapsed         | 3443         |
|    total_timesteps      | 5537792      |
| train/                  |              |
|    approx_kl            | 0.0018804567 |
|    clip_fraction        | 0.00317      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 838          |
|    n_updates            | 1348         |
|    policy_gradient_loss | 0.000237     |
|    value_loss           | 4.38e+03     |
------------------------------------------

Eval num_timesteps=5550000, episode_reward=520.36 +/- 192.69

Episode length: 118.95 +/- 18.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 520          |
| time/                   |              |
|    total_timesteps      | 5550000      |
| train/                  |              |
|    approx_kl            | 0.0032407725 |
|    clip_fraction        | 0.0192       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.794        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.42e+03     |
|    n_updates            | 1352         |
|    policy_gradient_loss | -0.00181     |
|    value_loss           | 6.04e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 411      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 339      |
|    time_elapsed    | 3455     |
|    total_timesteps | 5554176  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 476         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 340         |
|    time_elapsed         | 3465        |
|    total_timesteps      | 5570560     |
| train/                  |             |
|    approx_kl            | 0.005109258 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.743      |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.87e+03    |
|    n_updates            | 1356        |
|    policy_gradient_loss | -0.00233    |
|    value_loss           | 4.27e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 450          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 341          |
|    time_elapsed         | 3475         |
|    total_timesteps      | 5586944      |
| train/                  |              |
|    approx_kl            | 0.0037418806 |
|    clip_fraction        | 0.0234       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.785       |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 1360         |
|    policy_gradient_loss | -0.000619    |
|    value_loss           | 2.96e+03     |
------------------------------------------

Eval num_timesteps=5600000, episode_reward=531.62 +/- 198.43

Episode length: 120.60 +/- 23.84

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 121          |
|    mean_reward          | 532          |
| time/                   |              |
|    total_timesteps      | 5600000      |
| train/                  |              |
|    approx_kl            | 0.0035848566 |
|    clip_fraction        | 0.0141       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.847        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.83e+03     |
|    n_updates            | 1364         |
|    policy_gradient_loss | -0.00141     |
|    value_loss           | 5.46e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 484      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 342      |
|    time_elapsed    | 3486     |
|    total_timesteps | 5603328  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 471          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 343          |
|    time_elapsed         | 3495         |
|    total_timesteps      | 5619712      |
| train/                  |              |
|    approx_kl            | 0.0041157072 |
|    clip_fraction        | 0.024        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 793          |
|    n_updates            | 1368         |
|    policy_gradient_loss | -0.000215    |
|    value_loss           | 3.54e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 452          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 344          |
|    time_elapsed         | 3505         |
|    total_timesteps      | 5636096      |
| train/                  |              |
|    approx_kl            | 0.0054774834 |
|    clip_fraction        | 0.0181       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.77        |
|    explained_variance   | 0.816        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.31e+03     |
|    n_updates            | 1372         |
|    policy_gradient_loss | -0.00173     |
|    value_loss           | 4.61e+03     |
------------------------------------------

Eval num_timesteps=5650000, episode_reward=513.10 +/- 192.23

Episode length: 113.60 +/- 24.64

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | 513          |
| time/                   |              |
|    total_timesteps      | 5650000      |
| train/                  |              |
|    approx_kl            | 0.0035810075 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.769       |
|    explained_variance   | 0.899        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23e+03     |
|    n_updates            | 1376         |
|    policy_gradient_loss | -0.000748    |
|    value_loss           | 3.11e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 501      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 345      |
|    time_elapsed    | 3516     |
|    total_timesteps | 5652480  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 423          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 346          |
|    time_elapsed         | 3525         |
|    total_timesteps      | 5668864      |
| train/                  |              |
|    approx_kl            | 0.0027402933 |
|    clip_fraction        | 0.00493      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.852        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.05e+03     |
|    n_updates            | 1380         |
|    policy_gradient_loss | 0.000138     |
|    value_loss           | 4.18e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 462          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 347          |
|    time_elapsed         | 3534         |
|    total_timesteps      | 5685248      |
| train/                  |              |
|    approx_kl            | 0.0043596933 |
|    clip_fraction        | 0.0145       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.83e+03     |
|    n_updates            | 1384         |
|    policy_gradient_loss | -0.00127     |
|    value_loss           | 5.2e+03      |
------------------------------------------

Eval num_timesteps=5700000, episode_reward=514.07 +/- 155.49

Episode length: 127.75 +/- 26.48

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 514          |
| time/                   |              |
|    total_timesteps      | 5700000      |
| train/                  |              |
|    approx_kl            | 0.0036842627 |
|    clip_fraction        | 0.0124       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.842        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.14e+03     |
|    n_updates            | 1388         |
|    policy_gradient_loss | -0.00158     |
|    value_loss           | 4.27e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 489      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 348      |
|    time_elapsed    | 3546     |
|    total_timesteps | 5701632  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 442          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 349          |
|    time_elapsed         | 3556         |
|    total_timesteps      | 5718016      |
| train/                  |              |
|    approx_kl            | 0.0034826915 |
|    clip_fraction        | 0.0199       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.903        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.37e+03     |
|    n_updates            | 1392         |
|    policy_gradient_loss | -0.000714    |
|    value_loss           | 2.48e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 461          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 350          |
|    time_elapsed         | 3565         |
|    total_timesteps      | 5734400      |
| train/                  |              |
|    approx_kl            | 0.0053873854 |
|    clip_fraction        | 0.0271       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.76        |
|    explained_variance   | 0.809        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.88e+03     |
|    n_updates            | 1396         |
|    policy_gradient_loss | -0.00276     |
|    value_loss           | 5.07e+03     |
------------------------------------------

Eval num_timesteps=5750000, episode_reward=564.17 +/- 58.18

Episode length: 123.65 +/- 27.70

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 124          |
|    mean_reward          | 564          |
| time/                   |              |
|    total_timesteps      | 5750000      |
| train/                  |              |
|    approx_kl            | 0.0029178031 |
|    clip_fraction        | 0.00893      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.882        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.32e+03     |
|    n_updates            | 1400         |
|    policy_gradient_loss | -0.000511    |
|    value_loss           | 3.97e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 470      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 351      |
|    time_elapsed    | 3576     |
|    total_timesteps | 5750784  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 425         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 352         |
|    time_elapsed         | 3586        |
|    total_timesteps      | 5767168     |
| train/                  |             |
|    approx_kl            | 0.005038017 |
|    clip_fraction        | 0.0202      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.792      |
|    explained_variance   | 0.89        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.17e+03    |
|    n_updates            | 1404        |
|    policy_gradient_loss | -0.000247   |
|    value_loss           | 3.49e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 472          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 353          |
|    time_elapsed         | 3596         |
|    total_timesteps      | 5783552      |
| train/                  |              |
|    approx_kl            | 0.0024480168 |
|    clip_fraction        | 0.00284      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.812        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.58e+03     |
|    n_updates            | 1408         |
|    policy_gradient_loss | -0.000221    |
|    value_loss           | 5.55e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 481          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 354          |
|    time_elapsed         | 3604         |
|    total_timesteps      | 5799936      |
| train/                  |              |
|    approx_kl            | 0.0028545656 |
|    clip_fraction        | 0.00807      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.79e+03     |
|    n_updates            | 1412         |
|    policy_gradient_loss | -0.000257    |
|    value_loss           | 3.9e+03      |
------------------------------------------

Eval num_timesteps=5800000, episode_reward=606.94 +/- 78.90

Episode length: 125.65 +/- 30.10

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 607          |
| time/                   |              |
|    total_timesteps      | 5800000      |
| train/                  |              |
|    approx_kl            | 0.0063514933 |
|    clip_fraction        | 0.0353       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.816       |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45e+03     |
|    n_updates            | 1416         |
|    policy_gradient_loss | -0.00178     |
|    value_loss           | 2.85e+03     |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 435      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 355      |
|    time_elapsed    | 3616     |
|    total_timesteps | 5816320  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 479          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 356          |
|    time_elapsed         | 3626         |
|    total_timesteps      | 5832704      |
| train/                  |              |
|    approx_kl            | 0.0026857574 |
|    clip_fraction        | 0.0063       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.812       |
|    explained_variance   | 0.802        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 1420         |
|    policy_gradient_loss | -0.000512    |
|    value_loss           | 4.44e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 448         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 357         |
|    time_elapsed         | 3636        |
|    total_timesteps      | 5849088     |
| train/                  |             |
|    approx_kl            | 0.004300965 |
|    clip_fraction        | 0.0107      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.819      |
|    explained_variance   | 0.88        |
|    learning_rate        | 0.0003      |
|    loss                 | 3.34e+03    |
|    n_updates            | 1424        |
|    policy_gradient_loss | -0.00117    |
|    value_loss           | 4.12e+03    |
-----------------------------------------

Eval num_timesteps=5850000, episode_reward=489.68 +/- 209.82

Episode length: 131.15 +/- 29.70

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 490          |
| time/                   |              |
|    total_timesteps      | 5850000      |
| train/                  |              |
|    approx_kl            | 0.0030314508 |
|    clip_fraction        | 0.00581      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.784       |
|    explained_variance   | 0.866        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.25e+03     |
|    n_updates            | 1428         |
|    policy_gradient_loss | -0.000885    |
|    value_loss           | 3.59e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 470      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 358      |
|    time_elapsed    | 3647     |
|    total_timesteps | 5865472  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 437          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 359          |
|    time_elapsed         | 3656         |
|    total_timesteps      | 5881856      |
| train/                  |              |
|    approx_kl            | 0.0021201328 |
|    clip_fraction        | 0.0029       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.883        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.81e+03     |
|    n_updates            | 1432         |
|    policy_gradient_loss | 0.00016      |
|    value_loss           | 3.01e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 453         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 360         |
|    time_elapsed         | 3666        |
|    total_timesteps      | 5898240     |
| train/                  |             |
|    approx_kl            | 0.002480466 |
|    clip_fraction        | 0.0159      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.795      |
|    explained_variance   | 0.884       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.26e+03    |
|    n_updates            | 1436        |
|    policy_gradient_loss | -0.000557   |
|    value_loss           | 3.32e+03    |
-----------------------------------------

Eval num_timesteps=5900000, episode_reward=413.30 +/- 245.21

Episode length: 120.15 +/- 30.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 413          |
| time/                   |              |
|    total_timesteps      | 5900000      |
| train/                  |              |
|    approx_kl            | 0.0033859704 |
|    clip_fraction        | 0.00888      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.807       |
|    explained_variance   | 0.892        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.59e+03     |
|    n_updates            | 1440         |
|    policy_gradient_loss | -0.000207    |
|    value_loss           | 2.86e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 431      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 361      |
|    time_elapsed    | 3677     |
|    total_timesteps | 5914624  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 128        |
|    ep_rew_mean          | 463        |
| time/                   |            |
|    fps                  | 1608       |
|    iterations           | 362        |
|    time_elapsed         | 3686       |
|    total_timesteps      | 5931008    |
| train/                  |            |
|    approx_kl            | 0.00595437 |
|    clip_fraction        | 0.0304     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.812     |
|    explained_variance   | 0.872      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.64e+03   |
|    n_updates            | 1444       |
|    policy_gradient_loss | -0.00195   |
|    value_loss           | 4.23e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 469          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 363          |
|    time_elapsed         | 3696         |
|    total_timesteps      | 5947392      |
| train/                  |              |
|    approx_kl            | 0.0053144693 |
|    clip_fraction        | 0.0179       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.775       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.78e+03     |
|    n_updates            | 1448         |
|    policy_gradient_loss | -0.00257     |
|    value_loss           | 4.28e+03     |
------------------------------------------

Eval num_timesteps=5950000, episode_reward=471.27 +/- 205.70

Episode length: 127.25 +/- 38.77

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 127          |
|    mean_reward          | 471          |
| time/                   |              |
|    total_timesteps      | 5950000      |
| train/                  |              |
|    approx_kl            | 0.0051184194 |
|    clip_fraction        | 0.0327       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.912        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.25e+03     |
|    n_updates            | 1452         |
|    policy_gradient_loss | -0.00173     |
|    value_loss           | 2.54e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 471      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 364      |
|    time_elapsed    | 3707     |
|    total_timesteps | 5963776  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 471          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 365          |
|    time_elapsed         | 3717         |
|    total_timesteps      | 5980160      |
| train/                  |              |
|    approx_kl            | 0.0028736745 |
|    clip_fraction        | 0.0171       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.28e+03     |
|    n_updates            | 1456         |
|    policy_gradient_loss | -0.00102     |
|    value_loss           | 3.51e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 444          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 366          |
|    time_elapsed         | 3726         |
|    total_timesteps      | 5996544      |
| train/                  |              |
|    approx_kl            | 0.0026689903 |
|    clip_fraction        | 0.00363      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.841        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.62e+03     |
|    n_updates            | 1460         |
|    policy_gradient_loss | 0.000109     |
|    value_loss           | 4.02e+03     |
------------------------------------------

Eval num_timesteps=6000000, episode_reward=492.90 +/- 219.37

Episode length: 118.20 +/- 23.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | 493          |
| time/                   |              |
|    total_timesteps      | 6000000      |
| train/                  |              |
|    approx_kl            | 0.0029868933 |
|    clip_fraction        | 0.0169       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.873        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.66e+03     |
|    n_updates            | 1464         |
|    policy_gradient_loss | -0.000488    |
|    value_loss           | 2.95e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 6,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 399      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 367      |
|    time_elapsed    | 3742     |
|    total_timesteps | 6012928  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 482          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 368          |
|    time_elapsed         | 3751         |
|    total_timesteps      | 6029312      |
| train/                  |              |
|    approx_kl            | 0.0020162687 |
|    clip_fraction        | 0.0143       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.08e+03     |
|    n_updates            | 1468         |
|    policy_gradient_loss | -0.00119     |
|    value_loss           | 5.46e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 461          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 369          |
|    time_elapsed         | 3760         |
|    total_timesteps      | 6045696      |
| train/                  |              |
|    approx_kl            | 0.0043457877 |
|    clip_fraction        | 0.025        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.902        |
|    learning_rate        | 0.0003       |
|    loss                 | 885          |
|    n_updates            | 1472         |
|    policy_gradient_loss | -0.000899    |
|    value_loss           | 2.02e+03     |
------------------------------------------

Eval num_timesteps=6050000, episode_reward=500.94 +/- 223.89

Episode length: 119.15 +/- 27.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 501          |
| time/                   |              |
|    total_timesteps      | 6050000      |
| train/                  |              |
|    approx_kl            | 0.0043387925 |
|    clip_fraction        | 0.0162       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.92e+03     |
|    n_updates            | 1476         |
|    policy_gradient_loss | -0.000239    |
|    value_loss           | 3.75e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 471      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 370      |
|    time_elapsed    | 3772     |
|    total_timesteps | 6062080  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 462          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 371          |
|    time_elapsed         | 3781         |
|    total_timesteps      | 6078464      |
| train/                  |              |
|    approx_kl            | 0.0028995508 |
|    clip_fraction        | 0.015        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.816       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.96e+03     |
|    n_updates            | 1480         |
|    policy_gradient_loss | -0.00168     |
|    value_loss           | 4.21e+03     |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 133        |
|    ep_rew_mean          | 490        |
| time/                   |            |
|    fps                  | 1608       |
|    iterations           | 372        |
|    time_elapsed         | 3790       |
|    total_timesteps      | 6094848    |
| train/                  |            |
|    approx_kl            | 0.00453673 |
|    clip_fraction        | 0.0184     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.814     |
|    explained_variance   | 0.854      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.79e+03   |
|    n_updates            | 1484       |
|    policy_gradient_loss | -0.000503  |
|    value_loss           | 3.72e+03   |
----------------------------------------

Eval num_timesteps=6100000, episode_reward=551.39 +/- 127.92

Episode length: 121.50 +/- 32.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | 551          |
| time/                   |              |
|    total_timesteps      | 6100000      |
| train/                  |              |
|    approx_kl            | 0.0060970746 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.02e+03     |
|    n_updates            | 1488         |
|    policy_gradient_loss | -0.00125     |
|    value_loss           | 2.4e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 491      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 373      |
|    time_elapsed    | 3802     |
|    total_timesteps | 6111232  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 436          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 374          |
|    time_elapsed         | 3812         |
|    total_timesteps      | 6127616      |
| train/                  |              |
|    approx_kl            | 0.0023076094 |
|    clip_fraction        | 0.0169       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.847        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.37e+03     |
|    n_updates            | 1492         |
|    policy_gradient_loss | -0.000784    |
|    value_loss           | 3.7e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 466          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 375          |
|    time_elapsed         | 3821         |
|    total_timesteps      | 6144000      |
| train/                  |              |
|    approx_kl            | 0.0049954066 |
|    clip_fraction        | 0.0277       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.764       |
|    explained_variance   | 0.819        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.36e+03     |
|    n_updates            | 1496         |
|    policy_gradient_loss | -0.00207     |
|    value_loss           | 4.9e+03      |
------------------------------------------

Eval num_timesteps=6150000, episode_reward=423.50 +/- 258.34

Episode length: 111.25 +/- 24.30

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 111         |
|    mean_reward          | 424         |
| time/                   |             |
|    total_timesteps      | 6150000     |
| train/                  |             |
|    approx_kl            | 0.004438599 |
|    clip_fraction        | 0.0153      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.785      |
|    explained_variance   | 0.858       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.32e+03    |
|    n_updates            | 1500        |
|    policy_gradient_loss | -0.000516   |
|    value_loss           | 3.97e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 478      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 376      |
|    time_elapsed    | 3832     |
|    total_timesteps | 6160384  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 498          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 377          |
|    time_elapsed         | 3842         |
|    total_timesteps      | 6176768      |
| train/                  |              |
|    approx_kl            | 0.0053410484 |
|    clip_fraction        | 0.0373       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.775       |
|    explained_variance   | 0.83         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.26e+03     |
|    n_updates            | 1504         |
|    policy_gradient_loss | -0.00183     |
|    value_loss           | 4.24e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 459         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 378         |
|    time_elapsed         | 3852        |
|    total_timesteps      | 6193152     |
| train/                  |             |
|    approx_kl            | 0.004430757 |
|    clip_fraction        | 0.0174      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.787      |
|    explained_variance   | 0.786       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.61e+03    |
|    n_updates            | 1508        |
|    policy_gradient_loss | -0.0013     |
|    value_loss           | 4.38e+03    |
-----------------------------------------

Eval num_timesteps=6200000, episode_reward=432.24 +/- 239.09

Episode length: 133.30 +/- 35.17

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 133         |
|    mean_reward          | 432         |
| time/                   |             |
|    total_timesteps      | 6200000     |
| train/                  |             |
|    approx_kl            | 0.004474223 |
|    clip_fraction        | 0.0164      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.752      |
|    explained_variance   | 0.835       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.23e+03    |
|    n_updates            | 1512        |
|    policy_gradient_loss | -0.0012     |
|    value_loss           | 2.89e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 452      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 379      |
|    time_elapsed    | 3864     |
|    total_timesteps | 6209536  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 124        |
|    ep_rew_mean          | 494        |
| time/                   |            |
|    fps                  | 1607       |
|    iterations           | 380        |
|    time_elapsed         | 3873       |
|    total_timesteps      | 6225920    |
| train/                  |            |
|    approx_kl            | 0.00476038 |
|    clip_fraction        | 0.0262     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.783     |
|    explained_variance   | 0.858      |
|    learning_rate        | 0.0003     |
|    loss                 | 2.57e+03   |
|    n_updates            | 1516       |
|    policy_gradient_loss | -0.000717  |
|    value_loss           | 3.29e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 472          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 381          |
|    time_elapsed         | 3883         |
|    total_timesteps      | 6242304      |
| train/                  |              |
|    approx_kl            | 0.0039114277 |
|    clip_fraction        | 0.0196       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.772       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.78e+03     |
|    n_updates            | 1520         |
|    policy_gradient_loss | -0.00022     |
|    value_loss           | 3.45e+03     |
------------------------------------------

Eval num_timesteps=6250000, episode_reward=562.25 +/- 173.41

Episode length: 117.15 +/- 22.78

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 562         |
| time/                   |             |
|    total_timesteps      | 6250000     |
| train/                  |             |
|    approx_kl            | 0.004448152 |
|    clip_fraction        | 0.0413      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.767      |
|    explained_variance   | 0.897       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.57e+03    |
|    n_updates            | 1524        |
|    policy_gradient_loss | -0.00203    |
|    value_loss           | 2.4e+03     |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 511      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 382      |
|    time_elapsed    | 3895     |
|    total_timesteps | 6258688  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 506          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 383          |
|    time_elapsed         | 3905         |
|    total_timesteps      | 6275072      |
| train/                  |              |
|    approx_kl            | 0.0061220964 |
|    clip_fraction        | 0.0463       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.817       |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 908          |
|    n_updates            | 1528         |
|    policy_gradient_loss | -0.00175     |
|    value_loss           | 2.87e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 442          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 384          |
|    time_elapsed         | 3914         |
|    total_timesteps      | 6291456      |
| train/                  |              |
|    approx_kl            | 0.0030214041 |
|    clip_fraction        | 0.0157       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.76         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.79e+03     |
|    n_updates            | 1532         |
|    policy_gradient_loss | 1.45e-07     |
|    value_loss           | 3.93e+03     |
------------------------------------------

Eval num_timesteps=6300000, episode_reward=553.28 +/- 60.46

Episode length: 140.70 +/- 31.07

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 141         |
|    mean_reward          | 553         |
| time/                   |             |
|    total_timesteps      | 6300000     |
| train/                  |             |
|    approx_kl            | 0.005675911 |
|    clip_fraction        | 0.0239      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.777      |
|    explained_variance   | 0.776       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.36e+03    |
|    n_updates            | 1536        |
|    policy_gradient_loss | -0.00203    |
|    value_loss           | 6.3e+03     |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 459      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 385      |
|    time_elapsed    | 3926     |
|    total_timesteps | 6307840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 480          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 386          |
|    time_elapsed         | 3936         |
|    total_timesteps      | 6324224      |
| train/                  |              |
|    approx_kl            | 0.0025646945 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.777       |
|    explained_variance   | 0.863        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.17e+03     |
|    n_updates            | 1540         |
|    policy_gradient_loss | -0.000364    |
|    value_loss           | 3.63e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 435          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 387          |
|    time_elapsed         | 3946         |
|    total_timesteps      | 6340608      |
| train/                  |              |
|    approx_kl            | 0.0030899718 |
|    clip_fraction        | 0.00955      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.763       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.71e+03     |
|    n_updates            | 1544         |
|    policy_gradient_loss | -0.00011     |
|    value_loss           | 3.71e+03     |
------------------------------------------

Eval num_timesteps=6350000, episode_reward=521.80 +/- 174.23

Episode length: 117.15 +/- 25.72

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 457      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 388      |
|    time_elapsed    | 3957     |
|    total_timesteps | 6356992  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 475          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 389          |
|    time_elapsed         | 3966         |
|    total_timesteps      | 6373376      |
| train/                  |              |
|    approx_kl            | 0.0051037995 |
|    clip_fraction        | 0.0243       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.19e+03     |
|    n_updates            | 1552         |
|    policy_gradient_loss | -0.00247     |
|    value_loss           | 4.35e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 456          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 390          |
|    time_elapsed         | 3976         |
|    total_timesteps      | 6389760      |
| train/                  |              |
|    approx_kl            | 0.0025469013 |
|    clip_fraction        | 0.0215       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.804       |
|    explained_variance   | 0.911        |
|    learning_rate        | 0.0003       |
|    loss                 | 650          |
|    n_updates            | 1556         |
|    policy_gradient_loss | -0.000845    |
|    value_loss           | 2.19e+03     |
------------------------------------------

Eval num_timesteps=6400000, episode_reward=505.39 +/- 169.36

Episode length: 114.10 +/- 29.81

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | 505          |
| time/                   |              |
|    total_timesteps      | 6400000      |
| train/                  |              |
|    approx_kl            | 0.0032871459 |
|    clip_fraction        | 0.01         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.803        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23e+03     |
|    n_updates            | 1560         |
|    policy_gradient_loss | -0.00098     |
|    value_loss           | 4.47e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 136      |
|    ep_rew_mean     | 448      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 391      |
|    time_elapsed    | 3988     |
|    total_timesteps | 6406144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 468         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 392         |
|    time_elapsed         | 3998        |
|    total_timesteps      | 6422528     |
| train/                  |             |
|    approx_kl            | 0.003407426 |
|    clip_fraction        | 0.00804     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.824      |
|    explained_variance   | 0.876       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.91e+03    |
|    n_updates            | 1564        |
|    policy_gradient_loss | -0.000469   |
|    value_loss           | 3.62e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 472          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 393          |
|    time_elapsed         | 4006         |
|    total_timesteps      | 6438912      |
| train/                  |              |
|    approx_kl            | 0.0035122065 |
|    clip_fraction        | 0.0107       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.837       |
|    explained_variance   | 0.848        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.46e+03     |
|    n_updates            | 1568         |
|    policy_gradient_loss | -0.000104    |
|    value_loss           | 3.81e+03     |
------------------------------------------

Eval num_timesteps=6450000, episode_reward=523.36 +/- 120.62

Episode length: 140.65 +/- 34.71

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 141         |
|    mean_reward          | 523         |
| time/                   |             |
|    total_timesteps      | 6450000     |
| train/                  |             |
|    approx_kl            | 0.004540708 |
|    clip_fraction        | 0.0169      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.828      |
|    explained_variance   | 0.841       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.14e+03    |
|    n_updates            | 1572        |
|    policy_gradient_loss | -0.000815   |
|    value_loss           | 4.51e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 448      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 394      |
|    time_elapsed    | 4018     |
|    total_timesteps | 6455296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 477          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 395          |
|    time_elapsed         | 4028         |
|    total_timesteps      | 6471680      |
| train/                  |              |
|    approx_kl            | 0.0026495652 |
|    clip_fraction        | 0.00903      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.827       |
|    explained_variance   | 0.851        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.42e+03     |
|    n_updates            | 1576         |
|    policy_gradient_loss | -0.000863    |
|    value_loss           | 3.77e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 449          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 396          |
|    time_elapsed         | 4038         |
|    total_timesteps      | 6488064      |
| train/                  |              |
|    approx_kl            | 0.0038424032 |
|    clip_fraction        | 0.00975      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.843       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.82e+03     |
|    n_updates            | 1580         |
|    policy_gradient_loss | 0.000139     |
|    value_loss           | 3.3e+03      |
------------------------------------------

Eval num_timesteps=6500000, episode_reward=477.40 +/- 165.97

Episode length: 119.65 +/- 28.67

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 477          |
| time/                   |              |
|    total_timesteps      | 6500000      |
| train/                  |              |
|    approx_kl            | 0.0025787721 |
|    clip_fraction        | 0.0105       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.811       |
|    explained_variance   | 0.764        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.98e+03     |
|    n_updates            | 1584         |
|    policy_gradient_loss | -0.00122     |
|    value_loss           | 6.09e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 478      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 397      |
|    time_elapsed    | 4049     |
|    total_timesteps | 6504448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 442          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 398          |
|    time_elapsed         | 4058         |
|    total_timesteps      | 6520832      |
| train/                  |              |
|    approx_kl            | 0.0055020656 |
|    clip_fraction        | 0.0181       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.812        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.06e+03     |
|    n_updates            | 1588         |
|    policy_gradient_loss | -0.00167     |
|    value_loss           | 4.41e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 468         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 399         |
|    time_elapsed         | 4068        |
|    total_timesteps      | 6537216     |
| train/                  |             |
|    approx_kl            | 0.004393842 |
|    clip_fraction        | 0.0171      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.795      |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.6e+03     |
|    n_updates            | 1592        |
|    policy_gradient_loss | 0.000149    |
|    value_loss           | 3.8e+03     |
-----------------------------------------

Eval num_timesteps=6550000, episode_reward=578.89 +/- 61.68

Episode length: 132.35 +/- 28.04

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | 579          |
| time/                   |              |
|    total_timesteps      | 6550000      |
| train/                  |              |
|    approx_kl            | 0.0021321918 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.817       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.6e+03      |
|    n_updates            | 1596         |
|    policy_gradient_loss | -0.000921    |
|    value_loss           | 3.57e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 458      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 400      |
|    time_elapsed    | 4080     |
|    total_timesteps | 6553600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 434          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 401          |
|    time_elapsed         | 4089         |
|    total_timesteps      | 6569984      |
| train/                  |              |
|    approx_kl            | 0.0024544136 |
|    clip_fraction        | 0.00966      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.838        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.28e+03     |
|    n_updates            | 1600         |
|    policy_gradient_loss | -0.000438    |
|    value_loss           | 3.72e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 489          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 402          |
|    time_elapsed         | 4098         |
|    total_timesteps      | 6586368      |
| train/                  |              |
|    approx_kl            | 0.0043955147 |
|    clip_fraction        | 0.0125       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.837        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.89e+03     |
|    n_updates            | 1604         |
|    policy_gradient_loss | -0.000849    |
|    value_loss           | 5.13e+03     |
------------------------------------------

Eval num_timesteps=6600000, episode_reward=560.46 +/- 118.04

Episode length: 137.85 +/- 38.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 138         |
|    mean_reward          | 560         |
| time/                   |             |
|    total_timesteps      | 6600000     |
| train/                  |             |
|    approx_kl            | 0.003563664 |
|    clip_fraction        | 0.0225      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.832      |
|    explained_variance   | 0.895       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.01e+03    |
|    n_updates            | 1608        |
|    policy_gradient_loss | 0.000159    |
|    value_loss           | 3.05e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 479      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 403      |
|    time_elapsed    | 4110     |
|    total_timesteps | 6602752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 467          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 404          |
|    time_elapsed         | 4120         |
|    total_timesteps      | 6619136      |
| train/                  |              |
|    approx_kl            | 0.0045886314 |
|    clip_fraction        | 0.0162       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 1612         |
|    policy_gradient_loss | -0.00069     |
|    value_loss           | 3.48e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 431         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 405         |
|    time_elapsed         | 4129        |
|    total_timesteps      | 6635520     |
| train/                  |             |
|    approx_kl            | 0.006224434 |
|    clip_fraction        | 0.0398      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.83       |
|    explained_variance   | 0.859       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.2e+03     |
|    n_updates            | 1616        |
|    policy_gradient_loss | -0.00146    |
|    value_loss           | 3.74e+03    |
-----------------------------------------

Eval num_timesteps=6650000, episode_reward=555.15 +/- 29.91

Episode length: 130.80 +/- 30.94

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 555          |
| time/                   |              |
|    total_timesteps      | 6650000      |
| train/                  |              |
|    approx_kl            | 0.0039589712 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.818       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.03e+03     |
|    n_updates            | 1620         |
|    policy_gradient_loss | -0.00142     |
|    value_loss           | 4.75e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 442      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 406      |
|    time_elapsed    | 4141     |
|    total_timesteps | 6651904  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 486          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 407          |
|    time_elapsed         | 4151         |
|    total_timesteps      | 6668288      |
| train/                  |              |
|    approx_kl            | 0.0018762383 |
|    clip_fraction        | 0.00616      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.806       |
|    explained_variance   | 0.835        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.24e+03     |
|    n_updates            | 1624         |
|    policy_gradient_loss | -0.000535    |
|    value_loss           | 4.72e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 135         |
|    ep_rew_mean          | 459         |
| time/                   |             |
|    fps                  | 1606        |
|    iterations           | 408         |
|    time_elapsed         | 4160        |
|    total_timesteps      | 6684672     |
| train/                  |             |
|    approx_kl            | 0.002983823 |
|    clip_fraction        | 0.00754     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.807      |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | 864         |
|    n_updates            | 1628        |
|    policy_gradient_loss | -0.000533   |
|    value_loss           | 3.25e+03    |
-----------------------------------------

Eval num_timesteps=6700000, episode_reward=501.83 +/- 194.77

Episode length: 108.35 +/- 23.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | 502          |
| time/                   |              |
|    total_timesteps      | 6700000      |
| train/                  |              |
|    approx_kl            | 0.0039258925 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.819       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 702          |
|    n_updates            | 1632         |
|    policy_gradient_loss | -0.000761    |
|    value_loss           | 2.35e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 459      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 409      |
|    time_elapsed    | 4172     |
|    total_timesteps | 6701056  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 447          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 410          |
|    time_elapsed         | 4180         |
|    total_timesteps      | 6717440      |
| train/                  |              |
|    approx_kl            | 0.0036566933 |
|    clip_fraction        | 0.0346       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.843       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 1636         |
|    policy_gradient_loss | -0.000237    |
|    value_loss           | 2.76e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 499          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 411          |
|    time_elapsed         | 4190         |
|    total_timesteps      | 6733824      |
| train/                  |              |
|    approx_kl            | 0.0033170343 |
|    clip_fraction        | 0.0145       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.817       |
|    explained_variance   | 0.805        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.36e+03     |
|    n_updates            | 1640         |
|    policy_gradient_loss | -0.0019      |
|    value_loss           | 4.89e+03     |
------------------------------------------

Eval num_timesteps=6750000, episode_reward=416.69 +/- 282.39

Episode length: 129.55 +/- 29.73

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 130         |
|    mean_reward          | 417         |
| time/                   |             |
|    total_timesteps      | 6750000     |
| train/                  |             |
|    approx_kl            | 0.003035151 |
|    clip_fraction        | 0.0135      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.848      |
|    explained_variance   | 0.812       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.51e+03    |
|    n_updates            | 1644        |
|    policy_gradient_loss | 0.00039     |
|    value_loss           | 3.73e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 486      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 412      |
|    time_elapsed    | 4202     |
|    total_timesteps | 6750208  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 477          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 413          |
|    time_elapsed         | 4211         |
|    total_timesteps      | 6766592      |
| train/                  |              |
|    approx_kl            | 0.0054479386 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.771        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.58e+03     |
|    n_updates            | 1648         |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 4.74e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 500          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 414          |
|    time_elapsed         | 4220         |
|    total_timesteps      | 6782976      |
| train/                  |              |
|    approx_kl            | 0.0025564362 |
|    clip_fraction        | 0.0174       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.13e+03     |
|    n_updates            | 1652         |
|    policy_gradient_loss | -0.00078     |
|    value_loss           | 4.2e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 480         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 415         |
|    time_elapsed         | 4229        |
|    total_timesteps      | 6799360     |
| train/                  |             |
|    approx_kl            | 0.003868664 |
|    clip_fraction        | 0.0187      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.837      |
|    explained_variance   | 0.908       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.28e+03    |
|    n_updates            | 1656        |
|    policy_gradient_loss | 0.000311    |
|    value_loss           | 3.15e+03    |
-----------------------------------------

Eval num_timesteps=6800000, episode_reward=565.66 +/- 120.60

Episode length: 118.55 +/- 27.44

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 566          |
| time/                   |              |
|    total_timesteps      | 6800000      |
| train/                  |              |
|    approx_kl            | 0.0018530498 |
|    clip_fraction        | 0.00923      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.811       |
|    explained_variance   | 0.831        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.27e+03     |
|    n_updates            | 1660         |
|    policy_gradient_loss | -0.0009      |
|    value_loss           | 4.19e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 505      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 416      |
|    time_elapsed    | 4241     |
|    total_timesteps | 6815744  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 429         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 417         |
|    time_elapsed         | 4250        |
|    total_timesteps      | 6832128     |
| train/                  |             |
|    approx_kl            | 0.002406758 |
|    clip_fraction        | 0.0122      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.836      |
|    explained_variance   | 0.822       |
|    learning_rate        | 0.0003      |
|    loss                 | 670         |
|    n_updates            | 1664        |
|    policy_gradient_loss | 0.000154    |
|    value_loss           | 3.6e+03     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 487          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 418          |
|    time_elapsed         | 4259         |
|    total_timesteps      | 6848512      |
| train/                  |              |
|    approx_kl            | 0.0032214706 |
|    clip_fraction        | 0.00693      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.862        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.94e+03     |
|    n_updates            | 1668         |
|    policy_gradient_loss | 0.000143     |
|    value_loss           | 3.81e+03     |
------------------------------------------

Eval num_timesteps=6850000, episode_reward=536.06 +/- 167.23

Episode length: 126.65 +/- 26.99

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 127          |
|    mean_reward          | 536          |
| time/                   |              |
|    total_timesteps      | 6850000      |
| train/                  |              |
|    approx_kl            | 0.0056869593 |
|    clip_fraction        | 0.058        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.83        |
|    explained_variance   | 0.904        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.06e+03     |
|    n_updates            | 1672         |
|    policy_gradient_loss | -0.00145     |
|    value_loss           | 2.36e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 458      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 419      |
|    time_elapsed    | 4271     |
|    total_timesteps | 6864896  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 441          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 420          |
|    time_elapsed         | 4280         |
|    total_timesteps      | 6881280      |
| train/                  |              |
|    approx_kl            | 0.0038365494 |
|    clip_fraction        | 0.0163       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.804       |
|    explained_variance   | 0.781        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.24e+03     |
|    n_updates            | 1676         |
|    policy_gradient_loss | -0.00145     |
|    value_loss           | 5.32e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 473          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 421          |
|    time_elapsed         | 4289         |
|    total_timesteps      | 6897664      |
| train/                  |              |
|    approx_kl            | 0.0020957715 |
|    clip_fraction        | 0.00354      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.19e+03     |
|    n_updates            | 1680         |
|    policy_gradient_loss | -0.000217    |
|    value_loss           | 4.31e+03     |
------------------------------------------

Eval num_timesteps=6900000, episode_reward=506.14 +/- 189.70

Episode length: 131.95 +/- 31.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | 506          |
| time/                   |              |
|    total_timesteps      | 6900000      |
| train/                  |              |
|    approx_kl            | 0.0044867396 |
|    clip_fraction        | 0.0294       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.802       |
|    explained_variance   | 0.912        |
|    learning_rate        | 0.0003       |
|    loss                 | 486          |
|    n_updates            | 1684         |
|    policy_gradient_loss | -0.000873    |
|    value_loss           | 1.93e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_6900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 448      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 422      |
|    time_elapsed    | 4301     |
|    total_timesteps | 6914048  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 504          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 423          |
|    time_elapsed         | 4310         |
|    total_timesteps      | 6930432      |
| train/                  |              |
|    approx_kl            | 0.0038629177 |
|    clip_fraction        | 0.0295       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.828        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.68e+03     |
|    n_updates            | 1688         |
|    policy_gradient_loss | -0.00126     |
|    value_loss           | 4.09e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 440         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 424         |
|    time_elapsed         | 4320        |
|    total_timesteps      | 6946816     |
| train/                  |             |
|    approx_kl            | 0.003470803 |
|    clip_fraction        | 0.0164      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.787      |
|    explained_variance   | 0.835       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.82e+03    |
|    n_updates            | 1692        |
|    policy_gradient_loss | -0.000847   |
|    value_loss           | 3.88e+03    |
-----------------------------------------

Eval num_timesteps=6950000, episode_reward=547.36 +/- 173.23

Episode length: 135.30 +/- 34.97

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 135         |
|    mean_reward          | 547         |
| time/                   |             |
|    total_timesteps      | 6950000     |
| train/                  |             |
|    approx_kl            | 0.004308387 |
|    clip_fraction        | 0.0189      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.767      |
|    explained_variance   | 0.759       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.4e+03     |
|    n_updates            | 1696        |
|    policy_gradient_loss | -0.00172    |
|    value_loss           | 5.41e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 493      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 425      |
|    time_elapsed    | 4332     |
|    total_timesteps | 6963200  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 467          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 426          |
|    time_elapsed         | 4340         |
|    total_timesteps      | 6979584      |
| train/                  |              |
|    approx_kl            | 0.0027241076 |
|    clip_fraction        | 0.0104       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 999          |
|    n_updates            | 1700         |
|    policy_gradient_loss | -9.8e-05     |
|    value_loss           | 2.52e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 495         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 427         |
|    time_elapsed         | 4350        |
|    total_timesteps      | 6995968     |
| train/                  |             |
|    approx_kl            | 0.003319229 |
|    clip_fraction        | 0.0284      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.79       |
|    explained_variance   | 0.926       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.81e+03    |
|    n_updates            | 1704        |
|    policy_gradient_loss | -0.00136    |
|    value_loss           | 1.65e+03    |
-----------------------------------------

Eval num_timesteps=7000000, episode_reward=507.86 +/- 198.20

Episode length: 116.50 +/- 24.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 508          |
| time/                   |              |
|    total_timesteps      | 7000000      |
| train/                  |              |
|    approx_kl            | 0.0027004504 |
|    clip_fraction        | 0.0149       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 1708         |
|    policy_gradient_loss | -0.00023     |
|    value_loss           | 3.53e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 7,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 477      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 428      |
|    time_elapsed    | 4365     |
|    total_timesteps | 7012352  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 446          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 429          |
|    time_elapsed         | 4375         |
|    total_timesteps      | 7028736      |
| train/                  |              |
|    approx_kl            | 0.0041654357 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.805       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.13e+03     |
|    n_updates            | 1712         |
|    policy_gradient_loss | -0.000834    |
|    value_loss           | 4.27e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 429          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 430          |
|    time_elapsed         | 4384         |
|    total_timesteps      | 7045120      |
| train/                  |              |
|    approx_kl            | 0.0032491907 |
|    clip_fraction        | 0.0132       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.775       |
|    explained_variance   | 0.787        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.67e+03     |
|    n_updates            | 1716         |
|    policy_gradient_loss | -0.0017      |
|    value_loss           | 5.79e+03     |
------------------------------------------

Eval num_timesteps=7050000, episode_reward=498.23 +/- 188.36

Episode length: 138.75 +/- 30.77

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 139         |
|    mean_reward          | 498         |
| time/                   |             |
|    total_timesteps      | 7050000     |
| train/                  |             |
|    approx_kl            | 0.005519349 |
|    clip_fraction        | 0.0176      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.747      |
|    explained_variance   | 0.841       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.28e+03    |
|    n_updates            | 1720        |
|    policy_gradient_loss | -0.00194    |
|    value_loss           | 4.74e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 456      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 431      |
|    time_elapsed    | 4395     |
|    total_timesteps | 7061504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 485          |
| time/                   |              |
|    fps                  | 1606         |
|    iterations           | 432          |
|    time_elapsed         | 4404         |
|    total_timesteps      | 7077888      |
| train/                  |              |
|    approx_kl            | 0.0036846364 |
|    clip_fraction        | 0.0302       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.911        |
|    learning_rate        | 0.0003       |
|    loss                 | 276          |
|    n_updates            | 1724         |
|    policy_gradient_loss | -0.00186     |
|    value_loss           | 2.49e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 478         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 433         |
|    time_elapsed         | 4414        |
|    total_timesteps      | 7094272     |
| train/                  |             |
|    approx_kl            | 0.005201721 |
|    clip_fraction        | 0.0198      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.804      |
|    explained_variance   | 0.741       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.24e+03    |
|    n_updates            | 1728        |
|    policy_gradient_loss | -0.00145    |
|    value_loss           | 5.54e+03    |
-----------------------------------------

Eval num_timesteps=7100000, episode_reward=528.38 +/- 152.98

Episode length: 134.85 +/- 24.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 135          |
|    mean_reward          | 528          |
| time/                   |              |
|    total_timesteps      | 7100000      |
| train/                  |              |
|    approx_kl            | 0.0039601005 |
|    clip_fraction        | 0.0392       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.825       |
|    explained_variance   | 0.906        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.99e+03     |
|    n_updates            | 1732         |
|    policy_gradient_loss | -0.0021      |
|    value_loss           | 2.34e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 441      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 434      |
|    time_elapsed    | 4426     |
|    total_timesteps | 7110656  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 403          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 435          |
|    time_elapsed         | 4434         |
|    total_timesteps      | 7127040      |
| train/                  |              |
|    approx_kl            | 0.0017921182 |
|    clip_fraction        | 0.00131      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.819       |
|    explained_variance   | 0.791        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.52e+03     |
|    n_updates            | 1736         |
|    policy_gradient_loss | 0.000194     |
|    value_loss           | 5.4e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 442         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 436         |
|    time_elapsed         | 4444        |
|    total_timesteps      | 7143424     |
| train/                  |             |
|    approx_kl            | 0.004365364 |
|    clip_fraction        | 0.0179      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.8        |
|    explained_variance   | 0.738       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.38e+03    |
|    n_updates            | 1740        |
|    policy_gradient_loss | -0.0021     |
|    value_loss           | 6.93e+03    |
-----------------------------------------

Eval num_timesteps=7150000, episode_reward=469.40 +/- 200.22

Episode length: 133.60 +/- 36.19

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 134          |
|    mean_reward          | 469          |
| time/                   |              |
|    total_timesteps      | 7150000      |
| train/                  |              |
|    approx_kl            | 0.0043381434 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.822       |
|    explained_variance   | 0.836        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.38e+03     |
|    n_updates            | 1744         |
|    policy_gradient_loss | -0.00042     |
|    value_loss           | 5.42e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 135      |
|    ep_rew_mean     | 431      |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 437      |
|    time_elapsed    | 4455     |
|    total_timesteps | 7159808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 475          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 438          |
|    time_elapsed         | 4465         |
|    total_timesteps      | 7176192      |
| train/                  |              |
|    approx_kl            | 0.0028759856 |
|    clip_fraction        | 0.0145       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.816       |
|    explained_variance   | 0.818        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.01e+03     |
|    n_updates            | 1748         |
|    policy_gradient_loss | -0.00152     |
|    value_loss           | 4.9e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 150         |
|    ep_rew_mean          | 506         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 439         |
|    time_elapsed         | 4473        |
|    total_timesteps      | 7192576     |
| train/                  |             |
|    approx_kl            | 0.003671093 |
|    clip_fraction        | 0.0207      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.812      |
|    explained_variance   | 0.898       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.5e+03     |
|    n_updates            | 1752        |
|    policy_gradient_loss | -0.00133    |
|    value_loss           | 3.09e+03    |
-----------------------------------------

Eval num_timesteps=7200000, episode_reward=467.20 +/- 225.40

Episode length: 138.20 +/- 34.01

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 138          |
|    mean_reward          | 467          |
| time/                   |              |
|    total_timesteps      | 7200000      |
| train/                  |              |
|    approx_kl            | 0.0030767396 |
|    clip_fraction        | 0.0162       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.897        |
|    learning_rate        | 0.0003       |
|    loss                 | 982          |
|    n_updates            | 1756         |
|    policy_gradient_loss | -0.000741    |
|    value_loss           | 2.73e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 474      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 440      |
|    time_elapsed    | 4485     |
|    total_timesteps | 7208960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 485          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 441          |
|    time_elapsed         | 4495         |
|    total_timesteps      | 7225344      |
| train/                  |              |
|    approx_kl            | 0.0059790313 |
|    clip_fraction        | 0.0514       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 498          |
|    n_updates            | 1760         |
|    policy_gradient_loss | -0.00222     |
|    value_loss           | 2.42e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 508          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 442          |
|    time_elapsed         | 4504         |
|    total_timesteps      | 7241728      |
| train/                  |              |
|    approx_kl            | 0.0039147036 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.917        |
|    learning_rate        | 0.0003       |
|    loss                 | 748          |
|    n_updates            | 1764         |
|    policy_gradient_loss | -0.00154     |
|    value_loss           | 1.87e+03     |
------------------------------------------

Eval num_timesteps=7250000, episode_reward=548.43 +/- 175.85

Episode length: 120.85 +/- 29.75

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 121         |
|    mean_reward          | 548         |
| time/                   |             |
|    total_timesteps      | 7250000     |
| train/                  |             |
|    approx_kl            | 0.004185001 |
|    clip_fraction        | 0.0222      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.801      |
|    explained_variance   | 0.895       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.53e+03    |
|    n_updates            | 1768        |
|    policy_gradient_loss | 0.000414    |
|    value_loss           | 2.44e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 494      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 443      |
|    time_elapsed    | 4515     |
|    total_timesteps | 7258112  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 480         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 444         |
|    time_elapsed         | 4525        |
|    total_timesteps      | 7274496     |
| train/                  |             |
|    approx_kl            | 0.001099698 |
|    clip_fraction        | 0.00833     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.797      |
|    explained_variance   | 0.833       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.1e+03     |
|    n_updates            | 1772        |
|    policy_gradient_loss | 1.43e-06    |
|    value_loss           | 3.96e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 135         |
|    ep_rew_mean          | 509         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 445         |
|    time_elapsed         | 4534        |
|    total_timesteps      | 7290880     |
| train/                  |             |
|    approx_kl            | 0.003553423 |
|    clip_fraction        | 0.00993     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.777      |
|    explained_variance   | 0.856       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.92e+03    |
|    n_updates            | 1776        |
|    policy_gradient_loss | -0.000615   |
|    value_loss           | 3.44e+03    |
-----------------------------------------

Eval num_timesteps=7300000, episode_reward=460.27 +/- 229.41

Episode length: 119.05 +/- 29.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 460          |
| time/                   |              |
|    total_timesteps      | 7300000      |
| train/                  |              |
|    approx_kl            | 0.0033415055 |
|    clip_fraction        | 0.0338       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.908        |
|    learning_rate        | 0.0003       |
|    loss                 | 497          |
|    n_updates            | 1780         |
|    policy_gradient_loss | -0.000521    |
|    value_loss           | 2.22e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 475      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 446      |
|    time_elapsed    | 4546     |
|    total_timesteps | 7307264  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 506         |
| time/                   |             |
|    fps                  | 1607        |
|    iterations           | 447         |
|    time_elapsed         | 4554        |
|    total_timesteps      | 7323648     |
| train/                  |             |
|    approx_kl            | 0.003092313 |
|    clip_fraction        | 0.0179      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.81       |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | 396         |
|    n_updates            | 1784        |
|    policy_gradient_loss | 0.000479    |
|    value_loss           | 2.17e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 486          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 448          |
|    time_elapsed         | 4564         |
|    total_timesteps      | 7340032      |
| train/                  |              |
|    approx_kl            | 0.0042584036 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.838        |
|    learning_rate        | 0.0003       |
|    loss                 | 832          |
|    n_updates            | 1788         |
|    policy_gradient_loss | -0.00116     |
|    value_loss           | 3.68e+03     |
------------------------------------------

Eval num_timesteps=7350000, episode_reward=565.39 +/- 122.61

Episode length: 131.15 +/- 27.79

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 565          |
| time/                   |              |
|    total_timesteps      | 7350000      |
| train/                  |              |
|    approx_kl            | 0.0032097525 |
|    clip_fraction        | 0.0289       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.908        |
|    learning_rate        | 0.0003       |
|    loss                 | 717          |
|    n_updates            | 1792         |
|    policy_gradient_loss | -0.00155     |
|    value_loss           | 1.99e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 470      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 449      |
|    time_elapsed    | 4576     |
|    total_timesteps | 7356416  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 518          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 450          |
|    time_elapsed         | 4586         |
|    total_timesteps      | 7372800      |
| train/                  |              |
|    approx_kl            | 0.0042125136 |
|    clip_fraction        | 0.0171       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.61e+03     |
|    n_updates            | 1796         |
|    policy_gradient_loss | -0.000331    |
|    value_loss           | 3.53e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 501          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 451          |
|    time_elapsed         | 4594         |
|    total_timesteps      | 7389184      |
| train/                  |              |
|    approx_kl            | 0.0030867658 |
|    clip_fraction        | 0.0155       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.827        |
|    learning_rate        | 0.0003       |
|    loss                 | 925          |
|    n_updates            | 1800         |
|    policy_gradient_loss | -0.000799    |
|    value_loss           | 3.7e+03      |
------------------------------------------

Eval num_timesteps=7400000, episode_reward=559.70 +/- 117.12

Episode length: 122.10 +/- 26.82

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | 560          |
| time/                   |              |
|    total_timesteps      | 7400000      |
| train/                  |              |
|    approx_kl            | 0.0044486104 |
|    clip_fraction        | 0.0227       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.25e+03     |
|    n_updates            | 1804         |
|    policy_gradient_loss | -0.000545    |
|    value_loss           | 2.37e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 497      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 452      |
|    time_elapsed    | 4606     |
|    total_timesteps | 7405568  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 485          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 453          |
|    time_elapsed         | 4615         |
|    total_timesteps      | 7421952      |
| train/                  |              |
|    approx_kl            | 0.0037254672 |
|    clip_fraction        | 0.0201       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.14e+03     |
|    n_updates            | 1808         |
|    policy_gradient_loss | -0.00161     |
|    value_loss           | 3.28e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 525         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 454         |
|    time_elapsed         | 4625        |
|    total_timesteps      | 7438336     |
| train/                  |             |
|    approx_kl            | 0.002283146 |
|    clip_fraction        | 0.0175      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.807      |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.4e+03     |
|    n_updates            | 1812        |
|    policy_gradient_loss | -0.000149   |
|    value_loss           | 2.19e+03    |
-----------------------------------------

Eval num_timesteps=7450000, episode_reward=532.16 +/- 168.36

Episode length: 123.15 +/- 31.85

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 123         |
|    mean_reward          | 532         |
| time/                   |             |
|    total_timesteps      | 7450000     |
| train/                  |             |
|    approx_kl            | 0.003315793 |
|    clip_fraction        | 0.00653     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.818      |
|    explained_variance   | 0.8         |
|    learning_rate        | 0.0003      |
|    loss                 | 713         |
|    n_updates            | 1816        |
|    policy_gradient_loss | 0.000399    |
|    value_loss           | 3.87e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 487      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 455      |
|    time_elapsed    | 4636     |
|    total_timesteps | 7454720  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 129        |
|    ep_rew_mean          | 501        |
| time/                   |            |
|    fps                  | 1608       |
|    iterations           | 456        |
|    time_elapsed         | 4645       |
|    total_timesteps      | 7471104    |
| train/                  |            |
|    approx_kl            | 0.00242128 |
|    clip_fraction        | 0.0183     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.799     |
|    explained_variance   | 0.813      |
|    learning_rate        | 0.0003     |
|    loss                 | 2.39e+03   |
|    n_updates            | 1820       |
|    policy_gradient_loss | -0.000321  |
|    value_loss           | 4.28e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 480          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 457          |
|    time_elapsed         | 4655         |
|    total_timesteps      | 7487488      |
| train/                  |              |
|    approx_kl            | 0.0016978434 |
|    clip_fraction        | 0.00551      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.812       |
|    explained_variance   | 0.791        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.35e+03     |
|    n_updates            | 1824         |
|    policy_gradient_loss | 0.000337     |
|    value_loss           | 4.19e+03     |
------------------------------------------

Eval num_timesteps=7500000, episode_reward=562.67 +/- 50.40

Episode length: 123.25 +/- 30.35

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 563          |
| time/                   |              |
|    total_timesteps      | 7500000      |
| train/                  |              |
|    approx_kl            | 0.0025474608 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 942          |
|    n_updates            | 1828         |
|    policy_gradient_loss | 0.000213     |
|    value_loss           | 2.87e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 447      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 458      |
|    time_elapsed    | 4667     |
|    total_timesteps | 7503872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 465          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 459          |
|    time_elapsed         | 4676         |
|    total_timesteps      | 7520256      |
| train/                  |              |
|    approx_kl            | 0.0027834661 |
|    clip_fraction        | 0.0116       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.767        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.47e+03     |
|    n_updates            | 1832         |
|    policy_gradient_loss | -0.000181    |
|    value_loss           | 5.78e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 478          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 460          |
|    time_elapsed         | 4686         |
|    total_timesteps      | 7536640      |
| train/                  |              |
|    approx_kl            | 0.0019637616 |
|    clip_fraction        | 0.0054       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.809       |
|    explained_variance   | 0.709        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.1e+03      |
|    n_updates            | 1836         |
|    policy_gradient_loss | -0.000702    |
|    value_loss           | 6.32e+03     |
------------------------------------------

Eval num_timesteps=7550000, episode_reward=504.37 +/- 155.38

Episode length: 119.00 +/- 32.76

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 504          |
| time/                   |              |
|    total_timesteps      | 7550000      |
| train/                  |              |
|    approx_kl            | 0.0020418533 |
|    clip_fraction        | 0.0143       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.811       |
|    explained_variance   | 0.812        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.51e+03     |
|    n_updates            | 1840         |
|    policy_gradient_loss | -0.00083     |
|    value_loss           | 4.13e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 468      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 461      |
|    time_elapsed    | 4697     |
|    total_timesteps | 7553024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 507          |
| time/                   |              |
|    fps                  | 1607         |
|    iterations           | 462          |
|    time_elapsed         | 4707         |
|    total_timesteps      | 7569408      |
| train/                  |              |
|    approx_kl            | 0.0016217824 |
|    clip_fraction        | 0.00676      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.863        |
|    learning_rate        | 0.0003       |
|    loss                 | 960          |
|    n_updates            | 1844         |
|    policy_gradient_loss | -0.000132    |
|    value_loss           | 3.29e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 496          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 463          |
|    time_elapsed         | 4716         |
|    total_timesteps      | 7585792      |
| train/                  |              |
|    approx_kl            | 0.0031541917 |
|    clip_fraction        | 0.0226       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.85        |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 620          |
|    n_updates            | 1848         |
|    policy_gradient_loss | -0.000577    |
|    value_loss           | 2.15e+03     |
------------------------------------------

Eval num_timesteps=7600000, episode_reward=487.93 +/- 216.16

Episode length: 126.05 +/- 40.40

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 488          |
| time/                   |              |
|    total_timesteps      | 7600000      |
| train/                  |              |
|    approx_kl            | 0.0040263813 |
|    clip_fraction        | 0.0158       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.821       |
|    explained_variance   | 0.825        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.44e+03     |
|    n_updates            | 1852         |
|    policy_gradient_loss | -0.000718    |
|    value_loss           | 3.74e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 468      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 464      |
|    time_elapsed    | 4728     |
|    total_timesteps | 7602176  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 126        |
|    ep_rew_mean          | 470        |
| time/                   |            |
|    fps                  | 1607       |
|    iterations           | 465        |
|    time_elapsed         | 4737       |
|    total_timesteps      | 7618560    |
| train/                  |            |
|    approx_kl            | 0.00493108 |
|    clip_fraction        | 0.015      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.781     |
|    explained_variance   | 0.792      |
|    learning_rate        | 0.0003     |
|    loss                 | 2.15e+03   |
|    n_updates            | 1856       |
|    policy_gradient_loss | -0.00193   |
|    value_loss           | 5.34e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 476         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 466         |
|    time_elapsed         | 4747        |
|    total_timesteps      | 7634944     |
| train/                  |             |
|    approx_kl            | 0.002310793 |
|    clip_fraction        | 0.00563     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.782      |
|    explained_variance   | 0.811       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.05e+03    |
|    n_updates            | 1860        |
|    policy_gradient_loss | -0.000237   |
|    value_loss           | 4.49e+03    |
-----------------------------------------

Eval num_timesteps=7650000, episode_reward=563.18 +/- 118.97

Episode length: 131.75 +/- 26.46

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | 563          |
| time/                   |              |
|    total_timesteps      | 7650000      |
| train/                  |              |
|    approx_kl            | 0.0016496028 |
|    clip_fraction        | 0.006        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.824       |
|    explained_variance   | 0.795        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.8e+03      |
|    n_updates            | 1864         |
|    policy_gradient_loss | -3.66e-05    |
|    value_loss           | 4.62e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 509      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 467      |
|    time_elapsed    | 4758     |
|    total_timesteps | 7651328  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 423          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 468          |
|    time_elapsed         | 4767         |
|    total_timesteps      | 7667712      |
| train/                  |              |
|    approx_kl            | 0.0020575915 |
|    clip_fraction        | 0.0133       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.44e+03     |
|    n_updates            | 1868         |
|    policy_gradient_loss | 0.000101     |
|    value_loss           | 2.4e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 486          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 469          |
|    time_elapsed         | 4777         |
|    total_timesteps      | 7684096      |
| train/                  |              |
|    approx_kl            | 0.0039232676 |
|    clip_fraction        | 0.0249       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.807        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.06e+03     |
|    n_updates            | 1872         |
|    policy_gradient_loss | -0.00185     |
|    value_loss           | 5.03e+03     |
------------------------------------------

Eval num_timesteps=7700000, episode_reward=561.43 +/- 72.73

Episode length: 129.35 +/- 25.74

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 129          |
|    mean_reward          | 561          |
| time/                   |              |
|    total_timesteps      | 7700000      |
| train/                  |              |
|    approx_kl            | 0.0038454481 |
|    clip_fraction        | 0.0136       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.817        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.2e+03      |
|    n_updates            | 1876         |
|    policy_gradient_loss | -0.000783    |
|    value_loss           | 4.46e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 481      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 470      |
|    time_elapsed    | 4789     |
|    total_timesteps | 7700480  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 449         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 471         |
|    time_elapsed         | 4798        |
|    total_timesteps      | 7716864     |
| train/                  |             |
|    approx_kl            | 0.003510199 |
|    clip_fraction        | 0.0203      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.824      |
|    explained_variance   | 0.875       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.42e+03    |
|    n_updates            | 1880        |
|    policy_gradient_loss | -0.00157    |
|    value_loss           | 3.33e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 444          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 472          |
|    time_elapsed         | 4807         |
|    total_timesteps      | 7733248      |
| train/                  |              |
|    approx_kl            | 0.0028810208 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.773       |
|    explained_variance   | 0.844        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.04e+03     |
|    n_updates            | 1884         |
|    policy_gradient_loss | -0.000212    |
|    value_loss           | 4.01e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 466          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 473          |
|    time_elapsed         | 4817         |
|    total_timesteps      | 7749632      |
| train/                  |              |
|    approx_kl            | 0.0022144783 |
|    clip_fraction        | 0.00819      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.82        |
|    explained_variance   | 0.877        |
|    learning_rate        | 0.0003       |
|    loss                 | 901          |
|    n_updates            | 1888         |
|    policy_gradient_loss | 0.000368     |
|    value_loss           | 2.7e+03      |
------------------------------------------

Eval num_timesteps=7750000, episode_reward=524.55 +/- 197.56

Episode length: 140.10 +/- 41.55

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 140         |
|    mean_reward          | 525         |
| time/                   |             |
|    total_timesteps      | 7750000     |
| train/                  |             |
|    approx_kl            | 0.004935056 |
|    clip_fraction        | 0.0235      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.798      |
|    explained_variance   | 0.862       |
|    learning_rate        | 0.0003      |
|    loss                 | 826         |
|    n_updates            | 1892        |
|    policy_gradient_loss | -0.0011     |
|    value_loss           | 3.69e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 444      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 474      |
|    time_elapsed    | 4829     |
|    total_timesteps | 7766016  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 481         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 475         |
|    time_elapsed         | 4838        |
|    total_timesteps      | 7782400     |
| train/                  |             |
|    approx_kl            | 0.006140213 |
|    clip_fraction        | 0.0361      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.834      |
|    explained_variance   | 0.855       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.24e+03    |
|    n_updates            | 1896        |
|    policy_gradient_loss | -0.00148    |
|    value_loss           | 3.41e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 138         |
|    ep_rew_mean          | 489         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 476         |
|    time_elapsed         | 4847        |
|    total_timesteps      | 7798784     |
| train/                  |             |
|    approx_kl            | 0.002807023 |
|    clip_fraction        | 0.0174      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.826      |
|    explained_variance   | 0.877       |
|    learning_rate        | 0.0003      |
|    loss                 | 836         |
|    n_updates            | 1900        |
|    policy_gradient_loss | -0.000608   |
|    value_loss           | 2.78e+03    |
-----------------------------------------

Eval num_timesteps=7800000, episode_reward=510.32 +/- 198.26

Episode length: 120.75 +/- 22.39

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 121          |
|    mean_reward          | 510          |
| time/                   |              |
|    total_timesteps      | 7800000      |
| train/                  |              |
|    approx_kl            | 0.0020850908 |
|    clip_fraction        | 0.00879      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 483          |
|    n_updates            | 1904         |
|    policy_gradient_loss | 0.000129     |
|    value_loss           | 3.5e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 483      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 477      |
|    time_elapsed    | 4858     |
|    total_timesteps | 7815168  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 138        |
|    ep_rew_mean          | 483        |
| time/                   |            |
|    fps                  | 1608       |
|    iterations           | 478        |
|    time_elapsed         | 4868       |
|    total_timesteps      | 7831552    |
| train/                  |            |
|    approx_kl            | 0.00439296 |
|    clip_fraction        | 0.0208     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.801     |
|    explained_variance   | 0.773      |
|    learning_rate        | 0.0003     |
|    loss                 | 2.4e+03    |
|    n_updates            | 1908       |
|    policy_gradient_loss | -0.00217   |
|    value_loss           | 5.04e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 499         |
| time/                   |             |
|    fps                  | 1609        |
|    iterations           | 479         |
|    time_elapsed         | 4877        |
|    total_timesteps      | 7847936     |
| train/                  |             |
|    approx_kl            | 0.004820028 |
|    clip_fraction        | 0.0321      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.837      |
|    explained_variance   | 0.888       |
|    learning_rate        | 0.0003      |
|    loss                 | 629         |
|    n_updates            | 1912        |
|    policy_gradient_loss | -0.000637   |
|    value_loss           | 2.5e+03     |
-----------------------------------------

Eval num_timesteps=7850000, episode_reward=508.44 +/- 187.84

Episode length: 130.85 +/- 28.95

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 508          |
| time/                   |              |
|    total_timesteps      | 7850000      |
| train/                  |              |
|    approx_kl            | 0.0051096366 |
|    clip_fraction        | 0.0314       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.863        |
|    learning_rate        | 0.0003       |
|    loss                 | 689          |
|    n_updates            | 1916         |
|    policy_gradient_loss | -0.00051     |
|    value_loss           | 2.74e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 457      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 480      |
|    time_elapsed    | 4888     |
|    total_timesteps | 7864320  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 130         |
|    ep_rew_mean          | 472         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 481         |
|    time_elapsed         | 4898        |
|    total_timesteps      | 7880704     |
| train/                  |             |
|    approx_kl            | 0.002148535 |
|    clip_fraction        | 0.00848     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.849      |
|    explained_variance   | 0.703       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.99e+03    |
|    n_updates            | 1920        |
|    policy_gradient_loss | -0.000584   |
|    value_loss           | 7.33e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 434          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 482          |
|    time_elapsed         | 4907         |
|    total_timesteps      | 7897088      |
| train/                  |              |
|    approx_kl            | 0.0025589042 |
|    clip_fraction        | 0.0131       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.811       |
|    explained_variance   | 0.705        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.23e+03     |
|    n_updates            | 1924         |
|    policy_gradient_loss | -0.00142     |
|    value_loss           | 5.75e+03     |
------------------------------------------

Eval num_timesteps=7900000, episode_reward=570.58 +/- 118.75

Episode length: 137.70 +/- 48.52

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 138          |
|    mean_reward          | 571          |
| time/                   |              |
|    total_timesteps      | 7900000      |
| train/                  |              |
|    approx_kl            | 0.0031917277 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.33e+03     |
|    n_updates            | 1928         |
|    policy_gradient_loss | -0.00106     |
|    value_loss           | 4.12e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_7900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 487      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 483      |
|    time_elapsed    | 4919     |
|    total_timesteps | 7913472  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 439          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 484          |
|    time_elapsed         | 4928         |
|    total_timesteps      | 7929856      |
| train/                  |              |
|    approx_kl            | 0.0026720753 |
|    clip_fraction        | 0.011        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.871        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.09e+03     |
|    n_updates            | 1932         |
|    policy_gradient_loss | -0.000489    |
|    value_loss           | 3.32e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 141          |
|    ep_rew_mean          | 474          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 485          |
|    time_elapsed         | 4937         |
|    total_timesteps      | 7946240      |
| train/                  |              |
|    approx_kl            | 0.0024000858 |
|    clip_fraction        | 0.0147       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.808       |
|    explained_variance   | 0.871        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.22e+03     |
|    n_updates            | 1936         |
|    policy_gradient_loss | -0.000674    |
|    value_loss           | 3.59e+03     |
------------------------------------------

Eval num_timesteps=7950000, episode_reward=533.82 +/- 167.20

Episode length: 137.20 +/- 33.02

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 137          |
|    mean_reward          | 534          |
| time/                   |              |
|    total_timesteps      | 7950000      |
| train/                  |              |
|    approx_kl            | 0.0020066518 |
|    clip_fraction        | 0.0139       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.818       |
|    explained_variance   | 0.891        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.73e+03     |
|    n_updates            | 1940         |
|    policy_gradient_loss | 0.000413     |
|    value_loss           | 3.43e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 474      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 486      |
|    time_elapsed    | 4949     |
|    total_timesteps | 7962624  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 481          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 487          |
|    time_elapsed         | 4958         |
|    total_timesteps      | 7979008      |
| train/                  |              |
|    approx_kl            | 0.0010795771 |
|    clip_fraction        | 0.00771      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.806       |
|    explained_variance   | 0.845        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.51e+03     |
|    n_updates            | 1944         |
|    policy_gradient_loss | -4.31e-06    |
|    value_loss           | 3.92e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 139          |
|    ep_rew_mean          | 509          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 488          |
|    time_elapsed         | 4967         |
|    total_timesteps      | 7995392      |
| train/                  |              |
|    approx_kl            | 0.0035205665 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.83        |
|    explained_variance   | 0.846        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.36e+03     |
|    n_updates            | 1948         |
|    policy_gradient_loss | -0.000126    |
|    value_loss           | 3.55e+03     |
------------------------------------------

Eval num_timesteps=8000000, episode_reward=549.35 +/- 162.79

Episode length: 122.40 +/- 20.43

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | 549          |
| time/                   |              |
|    total_timesteps      | 8000000      |
| train/                  |              |
|    approx_kl            | 0.0039025953 |
|    clip_fraction        | 0.0226       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.826       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.47e+03     |
|    n_updates            | 1952         |
|    policy_gradient_loss | -0.000514    |
|    value_loss           | 2.81e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 8,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 463      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 489      |
|    time_elapsed    | 4982     |
|    total_timesteps | 8011776  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 483          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 490          |
|    time_elapsed         | 4992         |
|    total_timesteps      | 8028160      |
| train/                  |              |
|    approx_kl            | 0.0032375008 |
|    clip_fraction        | 0.0101       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.7e+03      |
|    n_updates            | 1956         |
|    policy_gradient_loss | -0.000874    |
|    value_loss           | 5.65e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 513          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 491          |
|    time_elapsed         | 5002         |
|    total_timesteps      | 8044544      |
| train/                  |              |
|    approx_kl            | 0.0028964847 |
|    clip_fraction        | 0.0222       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.873        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 1960         |
|    policy_gradient_loss | -0.000483    |
|    value_loss           | 2.49e+03     |
------------------------------------------

Eval num_timesteps=8050000, episode_reward=516.38 +/- 194.68

Episode length: 120.05 +/- 25.89

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 516          |
| time/                   |              |
|    total_timesteps      | 8050000      |
| train/                  |              |
|    approx_kl            | 0.0038124616 |
|    clip_fraction        | 0.0303       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.817       |
|    explained_variance   | 0.904        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.16e+03     |
|    n_updates            | 1964         |
|    policy_gradient_loss | -0.000659    |
|    value_loss           | 2.47e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 499      |
| time/              |          |
|    fps             | 1607     |
|    iterations      | 492      |
|    time_elapsed    | 5013     |
|    total_timesteps | 8060928  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 484          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 493          |
|    time_elapsed         | 5022         |
|    total_timesteps      | 8077312      |
| train/                  |              |
|    approx_kl            | 0.0034502035 |
|    clip_fraction        | 0.0312       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.827       |
|    explained_variance   | 0.883        |
|    learning_rate        | 0.0003       |
|    loss                 | 498          |
|    n_updates            | 1968         |
|    policy_gradient_loss | 5.86e-05     |
|    value_loss           | 2.13e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 453          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 494          |
|    time_elapsed         | 5031         |
|    total_timesteps      | 8093696      |
| train/                  |              |
|    approx_kl            | 0.0023106774 |
|    clip_fraction        | 0.0072       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.823       |
|    explained_variance   | 0.775        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.94e+03     |
|    n_updates            | 1972         |
|    policy_gradient_loss | 0.000447     |
|    value_loss           | 4.68e+03     |
------------------------------------------

Eval num_timesteps=8100000, episode_reward=490.47 +/- 210.07

Episode length: 127.75 +/- 26.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | 490          |
| time/                   |              |
|    total_timesteps      | 8100000      |
| train/                  |              |
|    approx_kl            | 0.0028497488 |
|    clip_fraction        | 0.00662      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.741        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.12e+03     |
|    n_updates            | 1976         |
|    policy_gradient_loss | -0.000642    |
|    value_loss           | 5.51e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 486      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 495      |
|    time_elapsed    | 5043     |
|    total_timesteps | 8110080  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 493          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 496          |
|    time_elapsed         | 5053         |
|    total_timesteps      | 8126464      |
| train/                  |              |
|    approx_kl            | 0.0031992635 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.789       |
|    explained_variance   | 0.838        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.69e+03     |
|    n_updates            | 1980         |
|    policy_gradient_loss | -0.000995    |
|    value_loss           | 5.44e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 456          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 497          |
|    time_elapsed         | 5061         |
|    total_timesteps      | 8142848      |
| train/                  |              |
|    approx_kl            | 0.0032788347 |
|    clip_fraction        | 0.0171       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.815       |
|    explained_variance   | 0.792        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.16e+03     |
|    n_updates            | 1984         |
|    policy_gradient_loss | -0.000304    |
|    value_loss           | 5.19e+03     |
------------------------------------------

Eval num_timesteps=8150000, episode_reward=571.81 +/- 147.59

Episode length: 130.55 +/- 28.12

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 572          |
| time/                   |              |
|    total_timesteps      | 8150000      |
| train/                  |              |
|    approx_kl            | 0.0024540576 |
|    clip_fraction        | 0.00954      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.915        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.6e+03      |
|    n_updates            | 1988         |
|    policy_gradient_loss | -0.000393    |
|    value_loss           | 3.15e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 489      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 498      |
|    time_elapsed    | 5073     |
|    total_timesteps | 8159232  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 463          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 499          |
|    time_elapsed         | 5083         |
|    total_timesteps      | 8175616      |
| train/                  |              |
|    approx_kl            | 0.0041925516 |
|    clip_fraction        | 0.0185       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.848        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.32e+03     |
|    n_updates            | 1992         |
|    policy_gradient_loss | -0.000187    |
|    value_loss           | 3.61e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 145          |
|    ep_rew_mean          | 493          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 500          |
|    time_elapsed         | 5092         |
|    total_timesteps      | 8192000      |
| train/                  |              |
|    approx_kl            | 0.0038867623 |
|    clip_fraction        | 0.025        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.824       |
|    explained_variance   | 0.855        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 1996         |
|    policy_gradient_loss | -0.000477    |
|    value_loss           | 4.32e+03     |
------------------------------------------

Eval num_timesteps=8200000, episode_reward=561.22 +/- 162.24

Episode length: 149.55 +/- 30.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 150          |
|    mean_reward          | 561          |
| time/                   |              |
|    total_timesteps      | 8200000      |
| train/                  |              |
|    approx_kl            | 0.0015919816 |
|    clip_fraction        | 0.0127       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.831       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.61e+03     |
|    n_updates            | 2000         |
|    policy_gradient_loss | -0.000171    |
|    value_loss           | 4.24e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 478      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 501      |
|    time_elapsed    | 5104     |
|    total_timesteps | 8208384  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 477          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 502          |
|    time_elapsed         | 5113         |
|    total_timesteps      | 8224768      |
| train/                  |              |
|    approx_kl            | 0.0041980008 |
|    clip_fraction        | 0.0235       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.858        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.87e+03     |
|    n_updates            | 2004         |
|    policy_gradient_loss | -0.000899    |
|    value_loss           | 3.03e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 475          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 503          |
|    time_elapsed         | 5123         |
|    total_timesteps      | 8241152      |
| train/                  |              |
|    approx_kl            | 0.0049310997 |
|    clip_fraction        | 0.0485       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.81        |
|    explained_variance   | 0.923        |
|    learning_rate        | 0.0003       |
|    loss                 | 968          |
|    n_updates            | 2008         |
|    policy_gradient_loss | -0.00186     |
|    value_loss           | 1.9e+03      |
------------------------------------------

Eval num_timesteps=8250000, episode_reward=486.40 +/- 209.87

Episode length: 125.65 +/- 24.69

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 486          |
| time/                   |              |
|    total_timesteps      | 8250000      |
| train/                  |              |
|    approx_kl            | 0.0019514894 |
|    clip_fraction        | 0.0103       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.828        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.22e+03     |
|    n_updates            | 2012         |
|    policy_gradient_loss | -0.00033     |
|    value_loss           | 4.41e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 486      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 504      |
|    time_elapsed    | 5134     |
|    total_timesteps | 8257536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 488          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 505          |
|    time_elapsed         | 5143         |
|    total_timesteps      | 8273920      |
| train/                  |              |
|    approx_kl            | 0.0039062072 |
|    clip_fraction        | 0.0248       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.843       |
|    explained_variance   | 0.807        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.12e+03     |
|    n_updates            | 2016         |
|    policy_gradient_loss | -0.00098     |
|    value_loss           | 4.49e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 410         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 506         |
|    time_elapsed         | 5153        |
|    total_timesteps      | 8290304     |
| train/                  |             |
|    approx_kl            | 0.004534079 |
|    clip_fraction        | 0.0277      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.838      |
|    explained_variance   | 0.809       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.75e+03    |
|    n_updates            | 2020        |
|    policy_gradient_loss | 3.78e-05    |
|    value_loss           | 4.23e+03    |
-----------------------------------------

Eval num_timesteps=8300000, episode_reward=549.30 +/- 164.24

Episode length: 134.60 +/- 28.74

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 135          |
|    mean_reward          | 549          |
| time/                   |              |
|    total_timesteps      | 8300000      |
| train/                  |              |
|    approx_kl            | 0.0027020304 |
|    clip_fraction        | 0.0137       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.793       |
|    explained_variance   | 0.731        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.86e+03     |
|    n_updates            | 2024         |
|    policy_gradient_loss | -0.000794    |
|    value_loss           | 6.04e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 136      |
|    ep_rew_mean     | 523      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 507      |
|    time_elapsed    | 5165     |
|    total_timesteps | 8306688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 465         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 508         |
|    time_elapsed         | 5174        |
|    total_timesteps      | 8323072     |
| train/                  |             |
|    approx_kl            | 0.006305627 |
|    clip_fraction        | 0.0402      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.82       |
|    explained_variance   | 0.808       |
|    learning_rate        | 0.0003      |
|    loss                 | 657         |
|    n_updates            | 2028        |
|    policy_gradient_loss | -0.00126    |
|    value_loss           | 2.72e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 495          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 509          |
|    time_elapsed         | 5183         |
|    total_timesteps      | 8339456      |
| train/                  |              |
|    approx_kl            | 0.0042866836 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.837       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.08e+03     |
|    n_updates            | 2032         |
|    policy_gradient_loss | -0.000418    |
|    value_loss           | 3.16e+03     |
------------------------------------------

Eval num_timesteps=8350000, episode_reward=540.28 +/- 149.40

Episode length: 138.00 +/- 30.07

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 138          |
|    mean_reward          | 540          |
| time/                   |              |
|    total_timesteps      | 8350000      |
| train/                  |              |
|    approx_kl            | 0.0032782299 |
|    clip_fraction        | 0.0147       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.836       |
|    explained_variance   | 0.786        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.07e+03     |
|    n_updates            | 2036         |
|    policy_gradient_loss | -0.000714    |
|    value_loss           | 4.18e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 424      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 510      |
|    time_elapsed    | 5195     |
|    total_timesteps | 8355840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 473          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 511          |
|    time_elapsed         | 5204         |
|    total_timesteps      | 8372224      |
| train/                  |              |
|    approx_kl            | 0.0012695855 |
|    clip_fraction        | 0.0062       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.809       |
|    explained_variance   | 0.789        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.27e+03     |
|    n_updates            | 2040         |
|    policy_gradient_loss | -0.000907    |
|    value_loss           | 4.58e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 428         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 512         |
|    time_elapsed         | 5214        |
|    total_timesteps      | 8388608     |
| train/                  |             |
|    approx_kl            | 0.004319043 |
|    clip_fraction        | 0.0241      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.792      |
|    explained_variance   | 0.855       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.53e+03    |
|    n_updates            | 2044        |
|    policy_gradient_loss | -0.00108    |
|    value_loss           | 3.77e+03    |
-----------------------------------------

Eval num_timesteps=8400000, episode_reward=570.31 +/- 88.93

Episode length: 126.00 +/- 24.68

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 126         |
|    mean_reward          | 570         |
| time/                   |             |
|    total_timesteps      | 8400000     |
| train/                  |             |
|    approx_kl            | 0.003390719 |
|    clip_fraction        | 0.0114      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.777      |
|    explained_variance   | 0.862       |
|    learning_rate        | 0.0003      |
|    loss                 | 744         |
|    n_updates            | 2048        |
|    policy_gradient_loss | -0.000331   |
|    value_loss           | 3.46e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 444      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 513      |
|    time_elapsed    | 5225     |
|    total_timesteps | 8404992  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 471          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 514          |
|    time_elapsed         | 5234         |
|    total_timesteps      | 8421376      |
| train/                  |              |
|    approx_kl            | 0.0053546773 |
|    clip_fraction        | 0.0346       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.805       |
|    explained_variance   | 0.892        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.25e+03     |
|    n_updates            | 2052         |
|    policy_gradient_loss | -0.000129    |
|    value_loss           | 2.94e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 130         |
|    ep_rew_mean          | 484         |
| time/                   |             |
|    fps                  | 1608        |
|    iterations           | 515         |
|    time_elapsed         | 5244        |
|    total_timesteps      | 8437760     |
| train/                  |             |
|    approx_kl            | 0.003804925 |
|    clip_fraction        | 0.0121      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.823      |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.33e+03    |
|    n_updates            | 2056        |
|    policy_gradient_loss | 0.00015     |
|    value_loss           | 3.4e+03     |
-----------------------------------------

Eval num_timesteps=8450000, episode_reward=517.48 +/- 167.47

Episode length: 119.85 +/- 26.46

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 517          |
| time/                   |              |
|    total_timesteps      | 8450000      |
| train/                  |              |
|    approx_kl            | 0.0030260994 |
|    clip_fraction        | 0.015        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.801       |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 937          |
|    n_updates            | 2060         |
|    policy_gradient_loss | -0.000289    |
|    value_loss           | 2.55e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 476      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 516      |
|    time_elapsed    | 5255     |
|    total_timesteps | 8454144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 473         |
| time/                   |             |
|    fps                  | 1609        |
|    iterations           | 517         |
|    time_elapsed         | 5264        |
|    total_timesteps      | 8470528     |
| train/                  |             |
|    approx_kl            | 0.002262562 |
|    clip_fraction        | 0.0151      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.786      |
|    explained_variance   | 0.875       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.28e+03    |
|    n_updates            | 2064        |
|    policy_gradient_loss | -0.000437   |
|    value_loss           | 3.77e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 486          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 518          |
|    time_elapsed         | 5273         |
|    total_timesteps      | 8486912      |
| train/                  |              |
|    approx_kl            | 0.0024476242 |
|    clip_fraction        | 0.0139       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.804       |
|    explained_variance   | 0.796        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.6e+03      |
|    n_updates            | 2068         |
|    policy_gradient_loss | 0.00029      |
|    value_loss           | 4.64e+03     |
------------------------------------------

Eval num_timesteps=8500000, episode_reward=477.09 +/- 205.14

Episode length: 116.80 +/- 21.23

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 477          |
| time/                   |              |
|    total_timesteps      | 8500000      |
| train/                  |              |
|    approx_kl            | 0.0025138583 |
|    clip_fraction        | 0.0122       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.8          |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28e+03     |
|    n_updates            | 2072         |
|    policy_gradient_loss | -0.000698    |
|    value_loss           | 4.24e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 432      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 519      |
|    time_elapsed    | 5285     |
|    total_timesteps | 8503296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 502          |
| time/                   |              |
|    fps                  | 1608         |
|    iterations           | 520          |
|    time_elapsed         | 5295         |
|    total_timesteps      | 8519680      |
| train/                  |              |
|    approx_kl            | 0.0032402822 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.762       |
|    explained_variance   | 0.734        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.82e+03     |
|    n_updates            | 2076         |
|    policy_gradient_loss | -0.00149     |
|    value_loss           | 5.91e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 469          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 521          |
|    time_elapsed         | 5303         |
|    total_timesteps      | 8536064      |
| train/                  |              |
|    approx_kl            | 0.0042931368 |
|    clip_fraction        | 0.0379       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.803       |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.55e+03     |
|    n_updates            | 2080         |
|    policy_gradient_loss | -0.000813    |
|    value_loss           | 2.87e+03     |
------------------------------------------

Eval num_timesteps=8550000, episode_reward=581.79 +/- 92.62

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 147         |
|    mean_reward          | 582         |
| time/                   |             |
|    total_timesteps      | 8550000     |
| train/                  |             |
|    approx_kl            | 0.003473606 |
|    clip_fraction        | 0.0237      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.755      |
|    explained_variance   | 0.835       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.05e+03    |
|    n_updates            | 2084        |
|    policy_gradient_loss | -0.00123    |
|    value_loss           | 3.9e+03     |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 135      |
|    ep_rew_mean     | 478      |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 522      |
|    time_elapsed    | 5315     |
|    total_timesteps | 8552448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 463          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 523          |
|    time_elapsed         | 5325         |
|    total_timesteps      | 8568832      |
| train/                  |              |
|    approx_kl            | 0.0042713825 |
|    clip_fraction        | 0.0226       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.818        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.19e+03     |
|    n_updates            | 2088         |
|    policy_gradient_loss | -0.000659    |
|    value_loss           | 3.79e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 491          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 524          |
|    time_elapsed         | 5334         |
|    total_timesteps      | 8585216      |
| train/                  |              |
|    approx_kl            | 0.0018036114 |
|    clip_fraction        | 0.00761      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.734        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.14e+03     |
|    n_updates            | 2092         |
|    policy_gradient_loss | 0.000287     |
|    value_loss           | 5.74e+03     |
------------------------------------------

Eval num_timesteps=8600000, episode_reward=469.10 +/- 194.62

Episode length: 124.10 +/- 24.20

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 124         |
|    mean_reward          | 469         |
| time/                   |             |
|    total_timesteps      | 8600000     |
| train/                  |             |
|    approx_kl            | 0.003618999 |
|    clip_fraction        | 0.00835     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.784      |
|    explained_variance   | 0.774       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.2e+03     |
|    n_updates            | 2096        |
|    policy_gradient_loss | -0.000122   |
|    value_loss           | 4.67e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 475      |
| time/              |          |
|    fps             | 1609     |
|    iterations      | 525      |
|    time_elapsed    | 5345     |
|    total_timesteps | 8601600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 470          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 526          |
|    time_elapsed         | 5354         |
|    total_timesteps      | 8617984      |
| train/                  |              |
|    approx_kl            | 0.0025214804 |
|    clip_fraction        | 0.0135       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.752       |
|    explained_variance   | 0.829        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.77e+03     |
|    n_updates            | 2100         |
|    policy_gradient_loss | -0.000198    |
|    value_loss           | 3.75e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 482          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 527          |
|    time_elapsed         | 5364         |
|    total_timesteps      | 8634368      |
| train/                  |              |
|    approx_kl            | 0.0023175902 |
|    clip_fraction        | 0.019        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.793        |
|    learning_rate        | 0.0003       |
|    loss                 | 809          |
|    n_updates            | 2104         |
|    policy_gradient_loss | -0.000365    |
|    value_loss           | 4.31e+03     |
------------------------------------------

Eval num_timesteps=8650000, episode_reward=541.25 +/- 120.12

Episode length: 125.60 +/- 29.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 541          |
| time/                   |              |
|    total_timesteps      | 8650000      |
| train/                  |              |
|    approx_kl            | 0.0024221176 |
|    clip_fraction        | 0.0135       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.76        |
|    explained_variance   | 0.805        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.01e+03     |
|    n_updates            | 2108         |
|    policy_gradient_loss | 0.00031      |
|    value_loss           | 4.91e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 465      |
| time/              |          |
|    fps             | 1609     |
|    iterations      | 528      |
|    time_elapsed    | 5375     |
|    total_timesteps | 8650752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 456          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 529          |
|    time_elapsed         | 5384         |
|    total_timesteps      | 8667136      |
| train/                  |              |
|    approx_kl            | 0.0038390816 |
|    clip_fraction        | 0.0213       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.755       |
|    explained_variance   | 0.756        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.99e+03     |
|    n_updates            | 2112         |
|    policy_gradient_loss | -0.00159     |
|    value_loss           | 4.87e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 476          |
| time/                   |              |
|    fps                  | 1609         |
|    iterations           | 530          |
|    time_elapsed         | 5393         |
|    total_timesteps      | 8683520      |
| train/                  |              |
|    approx_kl            | 0.0030466986 |
|    clip_fraction        | 0.025        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.21e+03     |
|    n_updates            | 2116         |
|    policy_gradient_loss | -0.00081     |
|    value_loss           | 3.33e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 451          |
| time/                   |              |
|    fps                  | 1610         |
|    iterations           | 531          |
|    time_elapsed         | 5403         |
|    total_timesteps      | 8699904      |
| train/                  |              |
|    approx_kl            | 0.0022028023 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.794       |
|    explained_variance   | 0.813        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.38e+03     |
|    n_updates            | 2120         |
|    policy_gradient_loss | 0.000196     |
|    value_loss           | 3.67e+03     |
------------------------------------------

Eval num_timesteps=8700000, episode_reward=519.91 +/- 195.87

Episode length: 130.15 +/- 36.42

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 130         |
|    mean_reward          | 520         |
| time/                   |             |
|    total_timesteps      | 8700000     |
| train/                  |             |
|    approx_kl            | 0.003738515 |
|    clip_fraction        | 0.0205      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.795      |
|    explained_variance   | 0.79        |
|    learning_rate        | 0.0003      |
|    loss                 | 818         |
|    n_updates            | 2124        |
|    policy_gradient_loss | -0.000206   |
|    value_loss           | 4.68e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 411      |
| time/              |          |
|    fps             | 1609     |
|    iterations      | 532      |
|    time_elapsed    | 5415     |
|    total_timesteps | 8716288  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 471          |
| time/                   |              |
|    fps                  | 1610         |
|    iterations           | 533          |
|    time_elapsed         | 5423         |
|    total_timesteps      | 8732672      |
| train/                  |              |
|    approx_kl            | 0.0027937326 |
|    clip_fraction        | 0.0114       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.701        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.61e+03     |
|    n_updates            | 2128         |
|    policy_gradient_loss | -0.000361    |
|    value_loss           | 7.14e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 466          |
| time/                   |              |
|    fps                  | 1610         |
|    iterations           | 534          |
|    time_elapsed         | 5433         |
|    total_timesteps      | 8749056      |
| train/                  |              |
|    approx_kl            | 0.0033736653 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.82         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.39e+03     |
|    n_updates            | 2132         |
|    policy_gradient_loss | -0.000799    |
|    value_loss           | 4.46e+03     |
------------------------------------------

Eval num_timesteps=8750000, episode_reward=554.47 +/- 113.56

Episode length: 135.55 +/- 37.44

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 136         |
|    mean_reward          | 554         |
| time/                   |             |
|    total_timesteps      | 8750000     |
| train/                  |             |
|    approx_kl            | 0.003175239 |
|    clip_fraction        | 0.0184      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.791      |
|    explained_variance   | 0.802       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.59e+03    |
|    n_updates            | 2136        |
|    policy_gradient_loss | -0.000857   |
|    value_loss           | 5.55e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 468      |
| time/              |          |
|    fps             | 1609     |
|    iterations      | 535      |
|    time_elapsed    | 5444     |
|    total_timesteps | 8765440  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 476         |
| time/                   |             |
|    fps                  | 1610        |
|    iterations           | 536         |
|    time_elapsed         | 5453        |
|    total_timesteps      | 8781824     |
| train/                  |             |
|    approx_kl            | 0.004009743 |
|    clip_fraction        | 0.0123      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.755      |
|    explained_variance   | 0.817       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.61e+03    |
|    n_updates            | 2140        |
|    policy_gradient_loss | -0.000547   |
|    value_loss           | 4.31e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 452          |
| time/                   |              |
|    fps                  | 1610         |
|    iterations           | 537          |
|    time_elapsed         | 5462         |
|    total_timesteps      | 8798208      |
| train/                  |              |
|    approx_kl            | 0.0027491348 |
|    clip_fraction        | 0.00941      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.756       |
|    explained_variance   | 0.821        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.33e+03     |
|    n_updates            | 2144         |
|    policy_gradient_loss | 0.000268     |
|    value_loss           | 4.17e+03     |
------------------------------------------

Eval num_timesteps=8800000, episode_reward=468.20 +/- 254.04

Episode length: 119.40 +/- 30.13

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 468          |
| time/                   |              |
|    total_timesteps      | 8800000      |
| train/                  |              |
|    approx_kl            | 0.0029304102 |
|    clip_fraction        | 0.0107       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.823        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.04e+03     |
|    n_updates            | 2148         |
|    policy_gradient_loss | 0.000188     |
|    value_loss           | 4.34e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 497      |
| time/              |          |
|    fps             | 1610     |
|    iterations      | 538      |
|    time_elapsed    | 5473     |
|    total_timesteps | 8814592  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 502          |
| time/                   |              |
|    fps                  | 1610         |
|    iterations           | 539          |
|    time_elapsed         | 5483         |
|    total_timesteps      | 8830976      |
| train/                  |              |
|    approx_kl            | 0.0038934192 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.783       |
|    explained_variance   | 0.759        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.98e+03     |
|    n_updates            | 2152         |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 5.2e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 480          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 540          |
|    time_elapsed         | 5491         |
|    total_timesteps      | 8847360      |
| train/                  |              |
|    approx_kl            | 0.0033879583 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.793       |
|    explained_variance   | 0.791        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.26e+03     |
|    n_updates            | 2156         |
|    policy_gradient_loss | -0.000335    |
|    value_loss           | 4.86e+03     |
------------------------------------------

Eval num_timesteps=8850000, episode_reward=503.29 +/- 210.01

Episode length: 140.25 +/- 41.86

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 140          |
|    mean_reward          | 503          |
| time/                   |              |
|    total_timesteps      | 8850000      |
| train/                  |              |
|    approx_kl            | 0.0036442424 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.787        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.08e+03     |
|    n_updates            | 2160         |
|    policy_gradient_loss | -0.000805    |
|    value_loss           | 4.54e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 485      |
| time/              |          |
|    fps             | 1610     |
|    iterations      | 541      |
|    time_elapsed    | 5502     |
|    total_timesteps | 8863744  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 136        |
|    ep_rew_mean          | 504        |
| time/                   |            |
|    fps                  | 1611       |
|    iterations           | 542        |
|    time_elapsed         | 5511       |
|    total_timesteps      | 8880128    |
| train/                  |            |
|    approx_kl            | 0.00288093 |
|    clip_fraction        | 0.0214     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.798     |
|    explained_variance   | 0.813      |
|    learning_rate        | 0.0003     |
|    loss                 | 3.38e+03   |
|    n_updates            | 2164       |
|    policy_gradient_loss | -0.000612  |
|    value_loss           | 4.31e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 144          |
|    ep_rew_mean          | 521          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 543          |
|    time_elapsed         | 5521         |
|    total_timesteps      | 8896512      |
| train/                  |              |
|    approx_kl            | 0.0029143745 |
|    clip_fraction        | 0.0227       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.819       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.26e+03     |
|    n_updates            | 2168         |
|    policy_gradient_loss | -0.00041     |
|    value_loss           | 2.56e+03     |
------------------------------------------

Eval num_timesteps=8900000, episode_reward=523.75 +/- 157.98

Episode length: 116.50 +/- 26.42

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 524          |
| time/                   |              |
|    total_timesteps      | 8900000      |
| train/                  |              |
|    approx_kl            | 0.0025994966 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.817       |
|    explained_variance   | 0.883        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.26e+03     |
|    n_updates            | 2172         |
|    policy_gradient_loss | -0.000371    |
|    value_loss           | 3.04e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_8900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 482      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 544      |
|    time_elapsed    | 5531     |
|    total_timesteps | 8912896  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 455         |
| time/                   |             |
|    fps                  | 1611        |
|    iterations           | 545         |
|    time_elapsed         | 5540        |
|    total_timesteps      | 8929280     |
| train/                  |             |
|    approx_kl            | 0.003231401 |
|    clip_fraction        | 0.03        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.833      |
|    explained_variance   | 0.88        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.8e+03     |
|    n_updates            | 2176        |
|    policy_gradient_loss | -0.000157   |
|    value_loss           | 3.27e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 143          |
|    ep_rew_mean          | 493          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 546          |
|    time_elapsed         | 5550         |
|    total_timesteps      | 8945664      |
| train/                  |              |
|    approx_kl            | 0.0035492624 |
|    clip_fraction        | 0.019        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.823       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.12e+03     |
|    n_updates            | 2180         |
|    policy_gradient_loss | -0.000168    |
|    value_loss           | 3.38e+03     |
------------------------------------------

Eval num_timesteps=8950000, episode_reward=584.66 +/- 19.84

Episode length: 130.35 +/- 24.07

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 130          |
|    mean_reward          | 585          |
| time/                   |              |
|    total_timesteps      | 8950000      |
| train/                  |              |
|    approx_kl            | 0.0022706653 |
|    clip_fraction        | 0.0123       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.808       |
|    explained_variance   | 0.815        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.22e+03     |
|    n_updates            | 2184         |
|    policy_gradient_loss | 0.000685     |
|    value_loss           | 4.28e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 435      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 547      |
|    time_elapsed    | 5561     |
|    total_timesteps | 8962048  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 398          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 548          |
|    time_elapsed         | 5570         |
|    total_timesteps      | 8978432      |
| train/                  |              |
|    approx_kl            | 0.0031583132 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.69         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.22e+03     |
|    n_updates            | 2188         |
|    policy_gradient_loss | -0.001       |
|    value_loss           | 7.47e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 478         |
| time/                   |             |
|    fps                  | 1612        |
|    iterations           | 549         |
|    time_elapsed         | 5579        |
|    total_timesteps      | 8994816     |
| train/                  |             |
|    approx_kl            | 0.005485515 |
|    clip_fraction        | 0.035       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.766      |
|    explained_variance   | 0.724       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.59e+03    |
|    n_updates            | 2192        |
|    policy_gradient_loss | -0.00378    |
|    value_loss           | 7.31e+03    |
-----------------------------------------

Eval num_timesteps=9000000, episode_reward=508.27 +/- 200.18

Episode length: 130.50 +/- 32.20

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 130         |
|    mean_reward          | 508         |
| time/                   |             |
|    total_timesteps      | 9000000     |
| train/                  |             |
|    approx_kl            | 0.003940832 |
|    clip_fraction        | 0.0186      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.775      |
|    explained_variance   | 0.755       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.87e+03    |
|    n_updates            | 2196        |
|    policy_gradient_loss | -0.00092    |
|    value_loss           | 5.19e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 9,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 460      |
| time/              |          |
|    fps             | 1610     |
|    iterations      | 550      |
|    time_elapsed    | 5594     |
|    total_timesteps | 9011200  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 141         |
|    ep_rew_mean          | 509         |
| time/                   |             |
|    fps                  | 1610        |
|    iterations           | 551         |
|    time_elapsed         | 5603        |
|    total_timesteps      | 9027584     |
| train/                  |             |
|    approx_kl            | 0.002790736 |
|    clip_fraction        | 0.00774     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.821      |
|    explained_variance   | 0.742       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.55e+03    |
|    n_updates            | 2200        |
|    policy_gradient_loss | 0.000565    |
|    value_loss           | 5.26e+03    |
-----------------------------------------

Eval num_timesteps=9050000, episode_reward=503.81 +/- 154.31

Episode length: 117.30 +/- 26.17

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 504          |
| time/                   |              |
|    total_timesteps      | 9050000      |
| train/                  |              |
|    approx_kl            | 0.0032017804 |
|    clip_fraction        | 0.0149       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.822       |
|    explained_variance   | 0.724        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.15e+03     |
|    n_updates            | 2208         |
|    policy_gradient_loss | -0.00044     |
|    value_loss           | 5.74e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 474      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 553      |
|    time_elapsed    | 5623     |
|    total_timesteps | 9060352  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 442          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 554          |
|    time_elapsed         | 5633         |
|    total_timesteps      | 9076736      |
| train/                  |              |
|    approx_kl            | 0.0034920615 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.845       |
|    explained_variance   | 0.799        |
|    learning_rate        | 0.0003       |
|    loss                 | 980          |
|    n_updates            | 2212         |
|    policy_gradient_loss | 0.000128     |
|    value_loss           | 3.85e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 432          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 555          |
|    time_elapsed         | 5643         |
|    total_timesteps      | 9093120      |
| train/                  |              |
|    approx_kl            | 0.0029709747 |
|    clip_fraction        | 0.0108       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.785       |
|    explained_variance   | 0.803        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.71e+03     |
|    n_updates            | 2216         |
|    policy_gradient_loss | -0.000856    |
|    value_loss           | 4.18e+03     |
------------------------------------------

Eval num_timesteps=9100000, episode_reward=524.13 +/- 187.04

Episode length: 142.70 +/- 38.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 143          |
|    mean_reward          | 524          |
| time/                   |              |
|    total_timesteps      | 9100000      |
| train/                  |              |
|    approx_kl            | 0.0026875492 |
|    clip_fraction        | 0.0166       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.792       |
|    explained_variance   | 0.82         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.87e+03     |
|    n_updates            | 2220         |
|    policy_gradient_loss | -0.000238    |
|    value_loss           | 4.22e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 447      |
| time/              |          |
|    fps             | 1610     |
|    iterations      | 556      |
|    time_elapsed    | 5655     |
|    total_timesteps | 9109504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 474          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 557          |
|    time_elapsed         | 5663         |
|    total_timesteps      | 9125888      |
| train/                  |              |
|    approx_kl            | 0.0042815334 |
|    clip_fraction        | 0.0176       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.776        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.02e+03     |
|    n_updates            | 2224         |
|    policy_gradient_loss | -0.00193     |
|    value_loss           | 4.15e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 406          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 558          |
|    time_elapsed         | 5673         |
|    total_timesteps      | 9142272      |
| train/                  |              |
|    approx_kl            | 0.0056327092 |
|    clip_fraction        | 0.0332       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.813       |
|    explained_variance   | 0.818        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.99e+03     |
|    n_updates            | 2228         |
|    policy_gradient_loss | -0.000321    |
|    value_loss           | 3.49e+03     |
------------------------------------------

Eval num_timesteps=9150000, episode_reward=561.87 +/- 178.16

Episode length: 137.20 +/- 74.33

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 137          |
|    mean_reward          | 562          |
| time/                   |              |
|    total_timesteps      | 9150000      |
| train/                  |              |
|    approx_kl            | 0.0025033643 |
|    clip_fraction        | 0.0085       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.73         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.41e+03     |
|    n_updates            | 2232         |
|    policy_gradient_loss | -1.86e-05    |
|    value_loss           | 5.83e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 432      |
| time/              |          |
|    fps             | 1610     |
|    iterations      | 559      |
|    time_elapsed    | 5685     |
|    total_timesteps | 9158656  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 418         |
| time/                   |             |
|    fps                  | 1611        |
|    iterations           | 560         |
|    time_elapsed         | 5694        |
|    total_timesteps      | 9175040     |
| train/                  |             |
|    approx_kl            | 0.003254625 |
|    clip_fraction        | 0.0181      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.812      |
|    explained_variance   | 0.879       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08e+03    |
|    n_updates            | 2236        |
|    policy_gradient_loss | 0.00022     |
|    value_loss           | 3.07e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 139          |
|    ep_rew_mean          | 487          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 561          |
|    time_elapsed         | 5703         |
|    total_timesteps      | 9191424      |
| train/                  |              |
|    approx_kl            | 0.0032482776 |
|    clip_fraction        | 0.0153       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.799       |
|    explained_variance   | 0.777        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.72e+03     |
|    n_updates            | 2240         |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 6.08e+03     |
------------------------------------------

Eval num_timesteps=9200000, episode_reward=499.46 +/- 227.63

Episode length: 129.05 +/- 45.81

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 129          |
|    mean_reward          | 499          |
| time/                   |              |
|    total_timesteps      | 9200000      |
| train/                  |              |
|    approx_kl            | 0.0033363597 |
|    clip_fraction        | 0.0144       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.816       |
|    explained_variance   | 0.825        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.13e+03     |
|    n_updates            | 2244         |
|    policy_gradient_loss | -0.000384    |
|    value_loss           | 4.49e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 465      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 562      |
|    time_elapsed    | 5715     |
|    total_timesteps | 9207808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 459          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 563          |
|    time_elapsed         | 5724         |
|    total_timesteps      | 9224192      |
| train/                  |              |
|    approx_kl            | 0.0012263956 |
|    clip_fraction        | 0.00697      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.741        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.79e+03     |
|    n_updates            | 2248         |
|    policy_gradient_loss | -0.000169    |
|    value_loss           | 6.04e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 477          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 564          |
|    time_elapsed         | 5734         |
|    total_timesteps      | 9240576      |
| train/                  |              |
|    approx_kl            | 0.0028707203 |
|    clip_fraction        | 0.0129       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.738       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.39e+03     |
|    n_updates            | 2252         |
|    policy_gradient_loss | -0.00115     |
|    value_loss           | 4.28e+03     |
------------------------------------------

Eval num_timesteps=9250000, episode_reward=550.29 +/- 109.95

Episode length: 117.80 +/- 36.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | 550          |
| time/                   |              |
|    total_timesteps      | 9250000      |
| train/                  |              |
|    approx_kl            | 0.0028605633 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.765       |
|    explained_variance   | 0.851        |
|    learning_rate        | 0.0003       |
|    loss                 | 635          |
|    n_updates            | 2256         |
|    policy_gradient_loss | -0.000204    |
|    value_loss           | 3.24e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 463      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 565      |
|    time_elapsed    | 5744     |
|    total_timesteps | 9256960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 457          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 566          |
|    time_elapsed         | 5754         |
|    total_timesteps      | 9273344      |
| train/                  |              |
|    approx_kl            | 0.0035535663 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.858        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.16e+03     |
|    n_updates            | 2260         |
|    policy_gradient_loss | 0.00021      |
|    value_loss           | 3.82e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 473          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 567          |
|    time_elapsed         | 5763         |
|    total_timesteps      | 9289728      |
| train/                  |              |
|    approx_kl            | 0.0024792966 |
|    clip_fraction        | 0.0238       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.758       |
|    explained_variance   | 0.82         |
|    learning_rate        | 0.0003       |
|    loss                 | 610          |
|    n_updates            | 2264         |
|    policy_gradient_loss | -0.000619    |
|    value_loss           | 4.9e+03      |
------------------------------------------

Eval num_timesteps=9300000, episode_reward=523.75 +/- 192.19

Episode length: 116.65 +/- 23.75

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 524         |
| time/                   |             |
|    total_timesteps      | 9300000     |
| train/                  |             |
|    approx_kl            | 0.002881009 |
|    clip_fraction        | 0.00925     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.745      |
|    explained_variance   | 0.801       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.75e+03    |
|    n_updates            | 2268        |
|    policy_gradient_loss | -0.000877   |
|    value_loss           | 5.9e+03     |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 489      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 568      |
|    time_elapsed    | 5775     |
|    total_timesteps | 9306112  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 484          |
| time/                   |              |
|    fps                  | 1611         |
|    iterations           | 569          |
|    time_elapsed         | 5783         |
|    total_timesteps      | 9322496      |
| train/                  |              |
|    approx_kl            | 0.0014754853 |
|    clip_fraction        | 0.0111       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.782       |
|    explained_variance   | 0.801        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69e+03     |
|    n_updates            | 2272         |
|    policy_gradient_loss | 0.000665     |
|    value_loss           | 4.84e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 478         |
| time/                   |             |
|    fps                  | 1612        |
|    iterations           | 570         |
|    time_elapsed         | 5793        |
|    total_timesteps      | 9338880     |
| train/                  |             |
|    approx_kl            | 0.002555524 |
|    clip_fraction        | 0.0197      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.747      |
|    explained_variance   | 0.804       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.71e+03    |
|    n_updates            | 2276        |
|    policy_gradient_loss | -0.000248   |
|    value_loss           | 4.43e+03    |
-----------------------------------------

Eval num_timesteps=9350000, episode_reward=567.15 +/- 29.59

Episode length: 120.50 +/- 23.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 567          |
| time/                   |              |
|    total_timesteps      | 9350000      |
| train/                  |              |
|    approx_kl            | 0.0033152844 |
|    clip_fraction        | 0.0201       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 841          |
|    n_updates            | 2280         |
|    policy_gradient_loss | -0.000113    |
|    value_loss           | 3.04e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 455      |
| time/              |          |
|    fps             | 1611     |
|    iterations      | 571      |
|    time_elapsed    | 5804     |
|    total_timesteps | 9355264  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 502          |
| time/                   |              |
|    fps                  | 1612         |
|    iterations           | 572          |
|    time_elapsed         | 5813         |
|    total_timesteps      | 9371648      |
| train/                  |              |
|    approx_kl            | 0.0027524033 |
|    clip_fraction        | 0.00935      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.752       |
|    explained_variance   | 0.857        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.99e+03     |
|    n_updates            | 2284         |
|    policy_gradient_loss | 9.62e-05     |
|    value_loss           | 5.08e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 436         |
| time/                   |             |
|    fps                  | 1612        |
|    iterations           | 573         |
|    time_elapsed         | 5821        |
|    total_timesteps      | 9388032     |
| train/                  |             |
|    approx_kl            | 0.002384521 |
|    clip_fraction        | 0.0116      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.782      |
|    explained_variance   | 0.83        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.18e+03    |
|    n_updates            | 2288        |
|    policy_gradient_loss | 0.000626    |
|    value_loss           | 3.91e+03    |
-----------------------------------------

Eval num_timesteps=9400000, episode_reward=510.14 +/- 169.43

Episode length: 134.80 +/- 36.24

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 135          |
|    mean_reward          | 510          |
| time/                   |              |
|    total_timesteps      | 9400000      |
| train/                  |              |
|    approx_kl            | 0.0031938404 |
|    clip_fraction        | 0.0193       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.73        |
|    explained_variance   | 0.868        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11e+03     |
|    n_updates            | 2292         |
|    policy_gradient_loss | -0.00102     |
|    value_loss           | 3.88e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 477      |
| time/              |          |
|    fps             | 1612     |
|    iterations      | 574      |
|    time_elapsed    | 5833     |
|    total_timesteps | 9404416  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 461          |
| time/                   |              |
|    fps                  | 1612         |
|    iterations           | 575          |
|    time_elapsed         | 5842         |
|    total_timesteps      | 9420800      |
| train/                  |              |
|    approx_kl            | 0.0030624443 |
|    clip_fraction        | 0.0165       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.754       |
|    explained_variance   | 0.802        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55e+03     |
|    n_updates            | 2296         |
|    policy_gradient_loss | -0.000273    |
|    value_loss           | 4.65e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 459         |
| time/                   |             |
|    fps                  | 1612        |
|    iterations           | 576         |
|    time_elapsed         | 5850        |
|    total_timesteps      | 9437184     |
| train/                  |             |
|    approx_kl            | 0.002212764 |
|    clip_fraction        | 0.0117      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.751      |
|    explained_variance   | 0.818       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.76e+03    |
|    n_updates            | 2300        |
|    policy_gradient_loss | 0.000512    |
|    value_loss           | 4.19e+03    |
-----------------------------------------

Eval num_timesteps=9450000, episode_reward=420.09 +/- 196.65

Episode length: 117.35 +/- 28.21

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 420          |
| time/                   |              |
|    total_timesteps      | 9450000      |
| train/                  |              |
|    approx_kl            | 0.0032285426 |
|    clip_fraction        | 0.0151       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.76        |
|    explained_variance   | 0.738        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.78e+03     |
|    n_updates            | 2304         |
|    policy_gradient_loss | -0.000742    |
|    value_loss           | 5.09e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 462      |
| time/              |          |
|    fps             | 1612     |
|    iterations      | 577      |
|    time_elapsed    | 5862     |
|    total_timesteps | 9453568  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 483          |
| time/                   |              |
|    fps                  | 1612         |
|    iterations           | 578          |
|    time_elapsed         | 5872         |
|    total_timesteps      | 9469952      |
| train/                  |              |
|    approx_kl            | 0.0037300866 |
|    clip_fraction        | 0.021        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.759        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.59e+03     |
|    n_updates            | 2308         |
|    policy_gradient_loss | -0.000784    |
|    value_loss           | 5.34e+03     |
------------------------------------------

Eval num_timesteps=9500000, episode_reward=537.52 +/- 135.24

Episode length: 123.05 +/- 27.58

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 538          |
| time/                   |              |
|    total_timesteps      | 9500000      |
| train/                  |              |
|    approx_kl            | 0.0041626333 |
|    clip_fraction        | 0.0394       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.778       |
|    explained_variance   | 0.847        |
|    learning_rate        | 0.0003       |
|    loss                 | 588          |
|    n_updates            | 2316         |
|    policy_gradient_loss | -0.0011      |
|    value_loss           | 3.17e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 495      |
| time/              |          |
|    fps             | 1612     |
|    iterations      | 580      |
|    time_elapsed    | 5891     |
|    total_timesteps | 9502720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 453          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 581          |
|    time_elapsed         | 5901         |
|    total_timesteps      | 9519104      |
| train/                  |              |
|    approx_kl            | 0.0019335382 |
|    clip_fraction        | 0.0132       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.775       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.76e+03     |
|    n_updates            | 2320         |
|    policy_gradient_loss | -0.00024     |
|    value_loss           | 4.21e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 434          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 582          |
|    time_elapsed         | 5910         |
|    total_timesteps      | 9535488      |
| train/                  |              |
|    approx_kl            | 0.0017218513 |
|    clip_fraction        | 0.0196       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.827        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.4e+03      |
|    n_updates            | 2324         |
|    policy_gradient_loss | -0.000637    |
|    value_loss           | 3.84e+03     |
------------------------------------------

Eval num_timesteps=9550000, episode_reward=556.22 +/- 51.03

Episode length: 115.80 +/- 21.39

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 556          |
| time/                   |              |
|    total_timesteps      | 9550000      |
| train/                  |              |
|    approx_kl            | 0.0044204723 |
|    clip_fraction        | 0.0246       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.763       |
|    explained_variance   | 0.746        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.6e+03      |
|    n_updates            | 2328         |
|    policy_gradient_loss | -0.00233     |
|    value_loss           | 5.51e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 494      |
| time/              |          |
|    fps             | 1612     |
|    iterations      | 583      |
|    time_elapsed    | 5921     |
|    total_timesteps | 9551872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 494          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 584          |
|    time_elapsed         | 5930         |
|    total_timesteps      | 9568256      |
| train/                  |              |
|    approx_kl            | 0.0030537045 |
|    clip_fraction        | 0.0204       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.738       |
|    explained_variance   | 0.867        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 2332         |
|    policy_gradient_loss | -0.00154     |
|    value_loss           | 2.77e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 493         |
| time/                   |             |
|    fps                  | 1613        |
|    iterations           | 585         |
|    time_elapsed         | 5939        |
|    total_timesteps      | 9584640     |
| train/                  |             |
|    approx_kl            | 0.005339491 |
|    clip_fraction        | 0.0475      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.783      |
|    explained_variance   | 0.845       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.6e+03     |
|    n_updates            | 2336        |
|    policy_gradient_loss | -0.000904   |
|    value_loss           | 3.01e+03    |
-----------------------------------------

Eval num_timesteps=9600000, episode_reward=557.26 +/- 127.72

Episode length: 128.10 +/- 28.08

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 128         |
|    mean_reward          | 557         |
| time/                   |             |
|    total_timesteps      | 9600000     |
| train/                  |             |
|    approx_kl            | 0.004252697 |
|    clip_fraction        | 0.036       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.816       |
|    learning_rate        | 0.0003      |
|    loss                 | 540         |
|    n_updates            | 2340        |
|    policy_gradient_loss | -0.00133    |
|    value_loss           | 3.56e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 487      |
| time/              |          |
|    fps             | 1613     |
|    iterations      | 586      |
|    time_elapsed    | 5951     |
|    total_timesteps | 9601024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 496          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 587          |
|    time_elapsed         | 5960         |
|    total_timesteps      | 9617408      |
| train/                  |              |
|    approx_kl            | 0.0033392163 |
|    clip_fraction        | 0.00858      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.764       |
|    explained_variance   | 0.79         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.51e+03     |
|    n_updates            | 2344         |
|    policy_gradient_loss | -0.0005      |
|    value_loss           | 5.6e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 139          |
|    ep_rew_mean          | 458          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 588          |
|    time_elapsed         | 5968         |
|    total_timesteps      | 9633792      |
| train/                  |              |
|    approx_kl            | 0.0013680037 |
|    clip_fraction        | 0.00838      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.765       |
|    explained_variance   | 0.769        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55e+03     |
|    n_updates            | 2348         |
|    policy_gradient_loss | 0.000435     |
|    value_loss           | 5.16e+03     |
------------------------------------------

Eval num_timesteps=9650000, episode_reward=449.09 +/- 214.52

Episode length: 125.15 +/- 26.84

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 125         |
|    mean_reward          | 449         |
| time/                   |             |
|    total_timesteps      | 9650000     |
| train/                  |             |
|    approx_kl            | 0.003041624 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.772      |
|    explained_variance   | 0.894       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.88e+03    |
|    n_updates            | 2352        |
|    policy_gradient_loss | -0.000504   |
|    value_loss           | 3.54e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 136      |
|    ep_rew_mean     | 459      |
| time/              |          |
|    fps             | 1613     |
|    iterations      | 589      |
|    time_elapsed    | 5980     |
|    total_timesteps | 9650176  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 131          |
|    ep_rew_mean          | 486          |
| time/                   |              |
|    fps                  | 1613         |
|    iterations           | 590          |
|    time_elapsed         | 5989         |
|    total_timesteps      | 9666560      |
| train/                  |              |
|    approx_kl            | 0.0030234917 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.779       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.15e+03     |
|    n_updates            | 2356         |
|    policy_gradient_loss | -0.000934    |
|    value_loss           | 3.42e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 141          |
|    ep_rew_mean          | 492          |
| time/                   |              |
|    fps                  | 1614         |
|    iterations           | 591          |
|    time_elapsed         | 5998         |
|    total_timesteps      | 9682944      |
| train/                  |              |
|    approx_kl            | 0.0033325714 |
|    clip_fraction        | 0.00743      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.863        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.52e+03     |
|    n_updates            | 2360         |
|    policy_gradient_loss | -0.000162    |
|    value_loss           | 5.11e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 484         |
| time/                   |             |
|    fps                  | 1614        |
|    iterations           | 592         |
|    time_elapsed         | 6007        |
|    total_timesteps      | 9699328     |
| train/                  |             |
|    approx_kl            | 0.004472336 |
|    clip_fraction        | 0.0113      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.778      |
|    explained_variance   | 0.85        |
|    learning_rate        | 0.0003      |
|    loss                 | 866         |
|    n_updates            | 2364        |
|    policy_gradient_loss | 0.000243    |
|    value_loss           | 5.1e+03     |
-----------------------------------------

Eval num_timesteps=9700000, episode_reward=543.93 +/- 122.51

Episode length: 116.10 +/- 19.95

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 544          |
| time/                   |              |
|    total_timesteps      | 9700000      |
| train/                  |              |
|    approx_kl            | 0.0034738658 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.776       |
|    explained_variance   | 0.836        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.36e+03     |
|    n_updates            | 2368         |
|    policy_gradient_loss | -0.000832    |
|    value_loss           | 3.48e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 475      |
| time/              |          |
|    fps             | 1614     |
|    iterations      | 593      |
|    time_elapsed    | 6018     |
|    total_timesteps | 9715712  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 470          |
| time/                   |              |
|    fps                  | 1614         |
|    iterations           | 594          |
|    time_elapsed         | 6027         |
|    total_timesteps      | 9732096      |
| train/                  |              |
|    approx_kl            | 0.0022681858 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.868        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55e+03     |
|    n_updates            | 2372         |
|    policy_gradient_loss | -0.000401    |
|    value_loss           | 2.86e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 470         |
| time/                   |             |
|    fps                  | 1615        |
|    iterations           | 595         |
|    time_elapsed         | 6036        |
|    total_timesteps      | 9748480     |
| train/                  |             |
|    approx_kl            | 0.004198686 |
|    clip_fraction        | 0.0369      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.789      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.76e+03    |
|    n_updates            | 2376        |
|    policy_gradient_loss | -0.000421   |
|    value_loss           | 2.72e+03    |
-----------------------------------------

Eval num_timesteps=9750000, episode_reward=540.38 +/- 129.11

Episode length: 130.55 +/- 35.65

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 131          |
|    mean_reward          | 540          |
| time/                   |              |
|    total_timesteps      | 9750000      |
| train/                  |              |
|    approx_kl            | 0.0014228378 |
|    clip_fraction        | 0.00763      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.777       |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.34e+03     |
|    n_updates            | 2380         |
|    policy_gradient_loss | 0.000426     |
|    value_loss           | 3.93e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 503      |
| time/              |          |
|    fps             | 1614     |
|    iterations      | 596      |
|    time_elapsed    | 6047     |
|    total_timesteps | 9764864  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 499          |
| time/                   |              |
|    fps                  | 1614         |
|    iterations           | 597          |
|    time_elapsed         | 6056         |
|    total_timesteps      | 9781248      |
| train/                  |              |
|    approx_kl            | 0.0031875079 |
|    clip_fraction        | 0.0126       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.771       |
|    explained_variance   | 0.826        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.87e+03     |
|    n_updates            | 2384         |
|    policy_gradient_loss | -0.000421    |
|    value_loss           | 4.08e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 501          |
| time/                   |              |
|    fps                  | 1615         |
|    iterations           | 598          |
|    time_elapsed         | 6064         |
|    total_timesteps      | 9797632      |
| train/                  |              |
|    approx_kl            | 0.0039443225 |
|    clip_fraction        | 0.0227       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.747       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.71e+03     |
|    n_updates            | 2388         |
|    policy_gradient_loss | -0.000692    |
|    value_loss           | 2.64e+03     |
------------------------------------------

Eval num_timesteps=9800000, episode_reward=545.85 +/- 131.99

Episode length: 110.95 +/- 22.28

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 546          |
| time/                   |              |
|    total_timesteps      | 9800000      |
| train/                  |              |
|    approx_kl            | 0.0034445734 |
|    clip_fraction        | 0.027        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.896        |
|    learning_rate        | 0.0003       |
|    loss                 | 861          |
|    n_updates            | 2392         |
|    policy_gradient_loss | 0.000111     |
|    value_loss           | 2.17e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 491      |
| time/              |          |
|    fps             | 1615     |
|    iterations      | 599      |
|    time_elapsed    | 6076     |
|    total_timesteps | 9814016  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 487          |
| time/                   |              |
|    fps                  | 1615         |
|    iterations           | 600          |
|    time_elapsed         | 6085         |
|    total_timesteps      | 9830400      |
| train/                  |              |
|    approx_kl            | 0.0028158082 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.786       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45e+03     |
|    n_updates            | 2396         |
|    policy_gradient_loss | 0.000171     |
|    value_loss           | 2.34e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 479         |
| time/                   |             |
|    fps                  | 1615        |
|    iterations           | 601         |
|    time_elapsed         | 6095        |
|    total_timesteps      | 9846784     |
| train/                  |             |
|    approx_kl            | 0.002409483 |
|    clip_fraction        | 0.00758     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.768      |
|    explained_variance   | 0.848       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.05e+03    |
|    n_updates            | 2400        |
|    policy_gradient_loss | -2.66e-06   |
|    value_loss           | 3.61e+03    |
-----------------------------------------

Eval num_timesteps=9850000, episode_reward=507.92 +/- 232.30

Episode length: 116.65 +/- 22.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 508          |
| time/                   |              |
|    total_timesteps      | 9850000      |
| train/                  |              |
|    approx_kl            | 0.0034855104 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.787       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 668          |
|    n_updates            | 2404         |
|    policy_gradient_loss | -5.04e-05    |
|    value_loss           | 2.77e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 465         |
| time/                   |             |
|    fps                  | 1615        |
|    iterations           | 603         |
|    time_elapsed         | 6114        |
|    total_timesteps      | 9879552     |
| train/                  |             |
|    approx_kl            | 0.003713504 |
|    clip_fraction        | 0.0283      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.781      |
|    explained_variance   | 0.826       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.51e+03    |
|    n_updates            | 2408        |
|    policy_gradient_loss | -0.00172    |
|    value_loss           | 4.11e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 454          |
| time/                   |              |
|    fps                  | 1615         |
|    iterations           | 604          |
|    time_elapsed         | 6124         |
|    total_timesteps      | 9895936      |
| train/                  |              |
|    approx_kl            | 0.0016123145 |
|    clip_fraction        | 0.00456      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.761       |
|    explained_variance   | 0.784        |
|    learning_rate        | 0.0003       |
|    loss                 | 948          |
|    n_updates            | 2412         |
|    policy_gradient_loss | 0.000291     |
|    value_loss           | 4.62e+03     |
------------------------------------------

Eval num_timesteps=9900000, episode_reward=531.33 +/- 205.98

Episode length: 119.05 +/- 35.61

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 531          |
| time/                   |              |
|    total_timesteps      | 9900000      |
| train/                  |              |
|    approx_kl            | 0.0042812303 |
|    clip_fraction        | 0.0155       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.756       |
|    explained_variance   | 0.884        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 2416         |
|    policy_gradient_loss | -0.00106     |
|    value_loss           | 5.42e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_9900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 491      |
| time/              |          |
|    fps             | 1615     |
|    iterations      | 605      |
|    time_elapsed    | 6135     |
|    total_timesteps | 9912320  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 508          |
| time/                   |              |
|    fps                  | 1616         |
|    iterations           | 606          |
|    time_elapsed         | 6143         |
|    total_timesteps      | 9928704      |
| train/                  |              |
|    approx_kl            | 0.0032585477 |
|    clip_fraction        | 0.01         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.728       |
|    explained_variance   | 0.878        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.51e+03     |
|    n_updates            | 2420         |
|    policy_gradient_loss | -0.000566    |
|    value_loss           | 3.46e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 507          |
| time/                   |              |
|    fps                  | 1616         |
|    iterations           | 607          |
|    time_elapsed         | 6153         |
|    total_timesteps      | 9945088      |
| train/                  |              |
|    approx_kl            | 0.0034809401 |
|    clip_fraction        | 0.0321       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.752       |
|    explained_variance   | 0.914        |
|    learning_rate        | 0.0003       |
|    loss                 | 697          |
|    n_updates            | 2424         |
|    policy_gradient_loss | 4.65e-05     |
|    value_loss           | 1.51e+03     |
------------------------------------------

Eval num_timesteps=9950000, episode_reward=497.99 +/- 223.18

Episode length: 123.60 +/- 24.77

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 124          |
|    mean_reward          | 498          |
| time/                   |              |
|    total_timesteps      | 9950000      |
| train/                  |              |
|    approx_kl            | 0.0039778017 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.766       |
|    explained_variance   | 0.868        |
|    learning_rate        | 0.0003       |
|    loss                 | 934          |
|    n_updates            | 2428         |
|    policy_gradient_loss | 0.000285     |
|    value_loss           | 2.87e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 474      |
| time/              |          |
|    fps             | 1615     |
|    iterations      | 608      |
|    time_elapsed    | 6164     |
|    total_timesteps | 9961472  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 130         |
|    ep_rew_mean          | 502         |
| time/                   |             |
|    fps                  | 1616        |
|    iterations           | 609         |
|    time_elapsed         | 6173        |
|    total_timesteps      | 9977856     |
| train/                  |             |
|    approx_kl            | 0.004947641 |
|    clip_fraction        | 0.0255      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.769      |
|    explained_variance   | 0.838       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.39e+03    |
|    n_updates            | 2432        |
|    policy_gradient_loss | -0.00024    |
|    value_loss           | 4.58e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 488          |
| time/                   |              |
|    fps                  | 1616         |
|    iterations           | 610          |
|    time_elapsed         | 6182         |
|    total_timesteps      | 9994240      |
| train/                  |              |
|    approx_kl            | 0.0016966625 |
|    clip_fraction        | 0.00879      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.747       |
|    explained_variance   | 0.835        |
|    learning_rate        | 0.0003       |
|    loss                 | 961          |
|    n_updates            | 2436         |
|    policy_gradient_loss | 0.000175     |
|    value_loss           | 4.16e+03     |
------------------------------------------

Eval num_timesteps=10000000, episode_reward=544.04 +/- 167.06

Episode length: 120.40 +/- 25.63

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 120         |
|    mean_reward          | 544         |
| time/                   |             |
|    total_timesteps      | 10000000    |
| train/                  |             |
|    approx_kl            | 0.004316005 |
|    clip_fraction        | 0.0182      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.714      |
|    explained_variance   | 0.84        |
|    learning_rate        | 0.0003      |
|    loss                 | 2.69e+03    |
|    n_updates            | 2440        |
|    policy_gradient_loss | -0.000855   |
|    value_loss           | 4.4e+03     |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_10000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 10,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 142      |
|    ep_rew_mean     | 536      |
| time/              |          |
|    fps             | 1615     |
|    iterations      | 611      |
|    time_elapsed    | 6197     |
|    total_timesteps | 10010624 |
---------------------------------

Best model: /content/rl-experiments/ppo_lunarlander_flip_phase_a/best_model/best_model.zip
Final model: /content/rl-experiments/ppo_lunarlander_flip_phase_a/final_model.zip
Configuration: /content/rl-experiments/ppo_lunarlander_flip_phase_a/training_config.json

In [13]:
import re

import pandas as pd


def checkpoint_step(
    path: Path,
) -> int:
    match = re.search(
        r"_(\d+)_steps\.zip$",
        path.name,
    )

    return (
        int(match.group(1))
        if match
        else -1
    )


phase_a_checkpoint_paths = sorted(
    (
        phase_a_run["output_dir"]
        / "checkpoints"
    ).glob("*.zip"),
    key=checkpoint_step,
)

phase_a_candidate_paths = [
    Path(
        phase_a_run["best_model_path"]
    ),
    Path(
        phase_a_run["final_model_path"]
    ),
    *phase_a_checkpoint_paths,
]

phase_a_candidate_paths = list(
    dict.fromkeys(
        path
        for path in phase_a_candidate_paths
        if path.exists()
    )
)

phase_a_rows = []

for candidate_path in (
    phase_a_candidate_paths
):
    candidate_evaluation = (
        evaluate_flip_model(
            candidate_path,
            reward_config=(
                flip_acquisition_config
            ),
            n_episodes=20,
            starting_seed=20_000,
        )
    )

    phase_a_rows.append(
        {
            "model_path": str(
                candidate_path
            ),
            **candidate_evaluation[
                "summary"
            ],
        }
    )

phase_a_results = pd.DataFrame(
    phase_a_rows
)

phase_a_results = (
    phase_a_results
    .sort_values(
        [
            "flip_completion_rate",
            "recovery_given_flip_rate",
            "mean_shaped_reward",
        ],
        ascending=[
            False,
            False,
            False,
        ],
    )
    .reset_index(drop=True)
)

display(
    phase_a_results[
        [
            "model_path",
            "flip_completion_rate",
            "recovery_given_flip_rate",
            "safe_landing_rate",
            "mean_shaped_reward",
        ]
    ]
)

selected_phase_a_model_path = Path(
    phase_a_results.loc[
        0,
        "model_path",
    ]
)

phase_a_flip_rate = float(
    phase_a_results.loc[
        0,
        "flip_completion_rate",
    ]
)

print(
    "Selected Phase A model:",
    selected_phase_a_model_path,
)

print(
    "Phase A flip rate:",
    f"{phase_a_flip_rate:.1%}",
)

if phase_a_flip_rate == 0.0:
    raise RuntimeError(
        "No Phase A checkpoint completed a flip. "
        "Do not start Phase B. Run another Phase A "
        "experiment with a different seed."
    )

if phase_a_flip_rate < 0.30:
    print(
        "Warning: the best Phase A flip rate is "
        "below 30%. Another Phase A seed may provide "
        "a stronger starting checkpoint."
    )

Flip model evaluation
---------------------
Mean shaped reward: 464.67
Mean original reward: -785.54
Completed a full rotation: 75.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 542.82
Mean original reward: -770.32
Completed a full rotation: 90.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.6%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -14.42
Mean original reward: -505.23
Completed a full rotation: 5.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -143.18
Mean original reward: -648.57
Completed a full rotation: 0.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -59.85
Mean original reward: -747.10
Completed a full rotation: 20.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -59.37
Mean original reward: -746.31
Completed a full rotation: 20.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -69.44
Mean original reward: -755.55
Completed a full rotation: 20.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -19.21
Mean original reward: -656.73
Completed a full rotation: 15.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -1.64
Mean original reward: -677.61
Completed a full rotation: 20.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -30.80
Mean original reward: -753.13
Completed a full rotation: 25.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -25.84
Mean original reward: -757.09
Completed a full rotation: 25.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -1.50
Mean original reward: -729.90
Completed a full rotation: 25.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 26.04
Mean original reward: -789.19
Completed a full rotation: 35.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 107.65
Mean original reward: -725.12
Completed a full rotation: 40.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 117.45
Mean original reward: -813.60
Completed a full rotation: 50.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 10.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 102.77
Mean original reward: -776.84
Completed a full rotation: 45.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 11.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 155.17
Mean original reward: -749.02
Completed a full rotation: 45.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 11.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 157.87
Mean original reward: -787.68
Completed a full rotation: 50.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 198.98
Mean original reward: -768.00
Completed a full rotation: 55.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 221.86
Mean original reward: -778.16
Completed a full rotation: 55.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 9.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 199.71
Mean original reward: -795.01
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 246.58
Mean original reward: -767.85
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 281.66
Mean original reward: -751.69
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 277.50
Mean original reward: -804.04
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 287.43
Mean original reward: -764.60
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 257.02
Mean original reward: -767.35
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 248.95
Mean original reward: -841.02
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 327.04
Mean original reward: -831.15
Completed a full rotation: 75.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 268.80
Mean original reward: -821.62
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 383.14
Mean original reward: -777.24
Completed a full rotation: 70.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 397.78
Mean original reward: -763.59
Completed a full rotation: 75.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 354.81
Mean original reward: -801.83
Completed a full rotation: 75.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 336.77
Mean original reward: -817.91
Completed a full rotation: 70.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 358.60
Mean original reward: -834.71
Completed a full rotation: 80.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 420.46
Mean original reward: -794.75
Completed a full rotation: 80.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.2%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 354.79
Mean original reward: -830.10
Completed a full rotation: 80.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 418.73
Mean original reward: -803.02
Completed a full rotation: 80.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 12.5%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 372.19
Mean original reward: -841.36
Completed a full rotation: 80.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.2%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 348.86
Mean original reward: -836.56
Completed a full rotation: 80.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 444.75
Mean original reward: -775.09
Completed a full rotation: 80.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.2%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 397.42
Mean original reward: -849.28
Completed a full rotation: 85.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 352.41
Mean original reward: -902.22
Completed a full rotation: 85.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.9%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 469.58
Mean original reward: -774.59
Completed a full rotation: 80.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 18.8%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 408.33
Mean original reward: -830.96
Completed a full rotation: 85.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 435.47
Mean original reward: -827.18
Completed a full rotation: 85.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.8%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 428.45
Mean original reward: -797.92
Completed a full rotation: 80.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 12.5%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 405.36
Mean original reward: -809.60
Completed a full rotation: 80.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.2%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 452.83
Mean original reward: -860.04
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 522.79
Mean original reward: -804.64
Completed a full rotation: 90.0%
Recovered after the flip: 20.0%
Recovery rate given a flip: 22.2%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 481.93
Mean original reward: -795.36
Completed a full rotation: 80.0%
Recovered after the flip: 20.0%
Recovery rate given a flip: 25.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 451.47
Mean original reward: -838.23
Completed a full rotation: 85.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 17.6%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 463.68
Mean original reward: -808.56
Completed a full rotation: 85.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.9%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 491.92
Mean original reward: -785.60
Completed a full rotation: 85.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.8%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 514.54
Mean original reward: -831.17
Completed a full rotation: 90.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 498.70
Mean original reward: -821.44
Completed a full rotation: 85.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.8%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 530.92
Mean original reward: -819.07
Completed a full rotation: 90.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 16.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 516.68
Mean original reward: -829.78
Completed a full rotation: 90.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 580.55
Mean original reward: -778.51
Completed a full rotation: 90.0%
Recovered after the flip: 45.0%
Recovery rate given a flip: 50.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 503.00
Mean original reward: -833.17
Completed a full rotation: 90.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.6%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 464.67
Mean original reward: -785.54
Completed a full rotation: 75.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 511.47
Mean original reward: -824.08
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 488.74
Mean original reward: -811.13
Completed a full rotation: 80.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 18.8%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 524.26
Mean original reward: -808.74
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 500.10
Mean original reward: -816.36
Completed a full rotation: 85.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.9%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 532.94
Mean original reward: -807.92
Completed a full rotation: 90.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 16.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 535.80
Mean original reward: -791.28
Completed a full rotation: 90.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 11.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 499.95
Mean original reward: -818.57
Completed a full rotation: 90.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 5.6%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 530.28
Mean original reward: -792.94
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 515.86
Mean original reward: -813.74
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 525.45
Mean original reward: -799.07
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 520.03
Mean original reward: -818.63
Completed a full rotation: 90.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,model_path,flip_completion_rate,recovery_given_flip_rate,safe_landing_rate,mean_shaped_reward
0,/content/rl-experiments/ppo_lunarlander_flip_p...,0.90,0.500000,0.0,580.549324
1,/content/rl-experiments/ppo_lunarlander_flip_p...,0.90,0.222222,0.0,542.701826
2,/content/rl-experiments/ppo_lunarlander_flip_p...,0.90,0.222222,0.0,522.788056
3,/content/rl-experiments/ppo_lunarlander_flip_p...,0.90,0.166667,0.0,532.939051
4,/content/rl-experiments/ppo_lunarlander_flip_p...,0.90,0.166667,0.0,530.923108
...,...,...,...,...,...
97,/content/rl-experiments/ppo_lunarlander_flip_p...,0.20,0.000000,0.0,-59.853758
98,/content/rl-experiments/ppo_lunarlander_flip_p...,0.20,0.000000,0.0,-69.435503
99,/content/rl-experiments/ppo_lunarlander_flip_p...,0.15,0.000000,0.0,-19.209961
100,/content/rl-experiments/ppo_lunarlander_flip_p...,0.05,0.000000,0.0,-14.421437
101,/content/rl-experiments/ppo_lunarlander_flip_p...,0.00,0.000000,0.0,-143.178825

Selected Phase A model: /content/rl-experiments/ppo_lunarlander_flip_phase_a/checkpoints/ppo_lunarlander_flip_phase_a_5600000_steps.zip
Phase A flip rate: 90.0%

In [14]:
phase_b_hub_checkpoint_callback = (
    HubCheckpointCallback(
        repo_id=(
            "KaptainKris/"
            "ppo-LunarLander-v3-flip"
        ),
        every_timesteps=1_000_000,
    )
)

#### Train Phase B (landing)

In [15]:
phase_b_run = train_ppo_experiment(
    experiment_name=(
        "ppo_lunarlander_flip_phase_b"
    ),
    total_timesteps=10_000_000,

    env_factory=(
        make_flip_landing_lander
    ),

    initial_model_path=(
        selected_phase_a_model_path
    ),

    n_envs=16,
    seed=42,

    # These document the loaded architecture.
    actor_layers=(128, 128),
    critic_layers=(128, 128),

    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    n_epochs=4,
    gamma=0.999,
    gae_lambda=0.98,
    ent_coef=0.03,
    clip_range=0.2,

    eval_every_timesteps=50_000,
    checkpoint_every_timesteps=100_000,
    n_eval_episodes=20,

    extra_callbacks=[
        phase_b_hub_checkpoint_callback
    ],

    device="cpu",
)

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 5,600,016 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | -149     |
| time/              |          |
|    fps             | 2056     |
|    iterations      | 1        |
|    time_elapsed    | 7        |
|    total_timesteps | 5616384  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | -82          |
| time/                   |              |
|    fps                  | 1844         |
|    iterations           | 2            |
|    time_elapsed         | 17           |
|    total_timesteps      | 5632768      |
| train/                  |              |
|    approx_kl            | 0.0051285173 |
|    clip_fraction        | 0.0344       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.772       |
|    explained_variance   | 0.516        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.25e+03     |
|    n_updates            | 1368         |
|    policy_gradient_loss | -0.0023      |
|    value_loss           | 1.29e+04     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 17.5        |
| time/                   |             |
|    fps                  | 1771        |
|    iterations           | 3           |
|    time_elapsed         | 27          |
|    total_timesteps      | 5649152     |
| train/                  |             |
|    approx_kl            | 0.006012913 |
|    clip_fraction        | 0.0509      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.792      |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.22e+03    |
|    n_updates            | 1372        |
|    policy_gradient_loss | -0.00318    |
|    value_loss           | 6.1e+03     |
-----------------------------------------

Eval num_timesteps=5650000, episode_reward=59.65 +/- 20.56

Episode length: 110.20 +/- 18.44

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 59.6         |
| time/                   |              |
|    total_timesteps      | 5650000      |
| train/                  |              |
|    approx_kl            | 0.0041531157 |
|    clip_fraction        | 0.0409       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.816       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.88e+03     |
|    n_updates            | 1376         |
|    policy_gradient_loss | -0.00136     |
|    value_loss           | 2.93e+03     |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 48       |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 4        |
|    time_elapsed    | 39       |
|    total_timesteps | 5665536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 40.7         |
| time/                   |              |
|    fps                  | 1710         |
|    iterations           | 5            |
|    time_elapsed         | 47           |
|    total_timesteps      | 5681920      |
| train/                  |              |
|    approx_kl            | 0.0061136773 |
|    clip_fraction        | 0.0698       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.847       |
|    explained_variance   | 0.76         |
|    learning_rate        | 0.0003       |
|    loss                 | 668          |
|    n_updates            | 1380         |
|    policy_gradient_loss | -0.00245     |
|    value_loss           | 2.58e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 60.8         |
| time/                   |              |
|    fps                  | 1703         |
|    iterations           | 6            |
|    time_elapsed         | 57           |
|    total_timesteps      | 5698304      |
| train/                  |              |
|    approx_kl            | 0.0072776326 |
|    clip_fraction        | 0.0569       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 606          |
|    n_updates            | 1384         |
|    policy_gradient_loss | -0.000781    |
|    value_loss           | 1.4e+03      |
------------------------------------------

Eval num_timesteps=5700000, episode_reward=50.67 +/- 38.34

Episode length: 107.70 +/- 21.76

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | 50.7         |
| time/                   |              |
|    total_timesteps      | 5700000      |
| train/                  |              |
|    approx_kl            | 0.0043002916 |
|    clip_fraction        | 0.0373       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.773        |
|    learning_rate        | 0.0003       |
|    loss                 | 101          |
|    n_updates            | 1388         |
|    policy_gradient_loss | -0.000783    |
|    value_loss           | 967          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_5700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 54.9     |
| time/              |          |
|    fps             | 1660     |
|    iterations      | 7        |
|    time_elapsed    | 69       |
|    total_timesteps | 5714688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 51.9        |
| time/                   |             |
|    fps                  | 1676        |
|    iterations           | 8           |
|    time_elapsed         | 78          |
|    total_timesteps      | 5731072     |
| train/                  |             |
|    approx_kl            | 0.006324964 |
|    clip_fraction        | 0.063       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.924      |
|    explained_variance   | 0.887       |
|    learning_rate        | 0.0003      |
|    loss                 | 136         |
|    n_updates            | 1392        |
|    policy_gradient_loss | -0.000586   |
|    value_loss           | 308         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 50           |
| time/                   |              |
|    fps                  | 1683         |
|    iterations           | 9            |
|    time_elapsed         | 87           |
|    total_timesteps      | 5747456      |
| train/                  |              |
|    approx_kl            | 0.0061584334 |
|    clip_fraction        | 0.0612       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.893       |
|    explained_variance   | 0.86         |
|    learning_rate        | 0.0003       |
|    loss                 | 261          |
|    n_updates            | 1396         |
|    policy_gradient_loss | -0.0014      |
|    value_loss           | 358          |
------------------------------------------

Eval num_timesteps=5750000, episode_reward=69.63 +/- 59.59

Episode length: 105.70 +/- 27.87

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | 69.6        |
| time/                   |             |
|    total_timesteps      | 5750000     |
| train/                  |             |
|    approx_kl            | 0.004097686 |
|    clip_fraction        | 0.0356      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.864      |
|    explained_variance   | 0.903       |
|    learning_rate        | 0.0003      |
|    loss                 | 41.5        |
|    n_updates            | 1400        |
|    policy_gradient_loss | -0.00041    |
|    value_loss           | 337         |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 54.3     |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 10       |
|    time_elapsed    | 99       |
|    total_timesteps | 5763840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 111          |
|    ep_rew_mean          | 51.1         |
| time/                   |              |
|    fps                  | 1646         |
|    iterations           | 11           |
|    time_elapsed         | 109          |
|    total_timesteps      | 5780224      |
| train/                  |              |
|    approx_kl            | 0.0039878706 |
|    clip_fraction        | 0.0394       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.919       |
|    explained_variance   | 0.908        |
|    learning_rate        | 0.0003       |
|    loss                 | 121          |
|    n_updates            | 1404         |
|    policy_gradient_loss | -5.37e-05    |
|    value_loss           | 310          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 111         |
|    ep_rew_mean          | 50.4        |
| time/                   |             |
|    fps                  | 1650        |
|    iterations           | 12          |
|    time_elapsed         | 119         |
|    total_timesteps      | 5796608     |
| train/                  |             |
|    approx_kl            | 0.004040167 |
|    clip_fraction        | 0.0376      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.901      |
|    explained_variance   | 0.92        |
|    learning_rate        | 0.0003      |
|    loss                 | 108         |
|    n_updates            | 1408        |
|    policy_gradient_loss | -0.000641   |
|    value_loss           | 209         |
-----------------------------------------

Eval num_timesteps=5800000, episode_reward=65.35 +/- 21.41

Episode length: 109.75 +/- 28.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 65.3         |
| time/                   |              |
|    total_timesteps      | 5800000      |
| train/                  |              |
|    approx_kl            | 0.0036661522 |
|    clip_fraction        | 0.0359       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.872       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 79.4         |
|    n_updates            | 1412         |
|    policy_gradient_loss | 0.000136     |
|    value_loss           | 616          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_5800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 53.8     |
| time/              |          |
|    fps             | 1636     |
|    iterations      | 13       |
|    time_elapsed    | 130      |
|    total_timesteps | 5812992  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 58.8        |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 14          |
|    time_elapsed         | 139         |
|    total_timesteps      | 5829376     |
| train/                  |             |
|    approx_kl            | 0.004427121 |
|    clip_fraction        | 0.0345      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.88       |
|    explained_variance   | 0.869       |
|    learning_rate        | 0.0003      |
|    loss                 | 161         |
|    n_updates            | 1416        |
|    policy_gradient_loss | 0.000211    |
|    value_loss           | 590         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 59           |
| time/                   |              |
|    fps                  | 1642         |
|    iterations           | 15           |
|    time_elapsed         | 149          |
|    total_timesteps      | 5845760      |
| train/                  |              |
|    approx_kl            | 0.0033511587 |
|    clip_fraction        | 0.0391       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.897       |
|    explained_variance   | 0.794        |
|    learning_rate        | 0.0003       |
|    loss                 | 114          |
|    n_updates            | 1420         |
|    policy_gradient_loss | 0.000453     |
|    value_loss           | 569          |
------------------------------------------

Eval num_timesteps=5850000, episode_reward=51.27 +/- 44.17

Episode length: 113.80 +/- 30.99

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 114          |
|    mean_reward          | 51.3         |
| time/                   |              |
|    total_timesteps      | 5850000      |
| train/                  |              |
|    approx_kl            | 0.0043699495 |
|    clip_fraction        | 0.0423       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.919        |
|    learning_rate        | 0.0003       |
|    loss                 | 65.4         |
|    n_updates            | 1424         |
|    policy_gradient_loss | 6.79e-05     |
|    value_loss           | 251          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 64.5     |
| time/              |          |
|    fps             | 1625     |
|    iterations      | 16       |
|    time_elapsed    | 161      |
|    total_timesteps | 5862144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 114         |
|    ep_rew_mean          | 62.6        |
| time/                   |             |
|    fps                  | 1638        |
|    iterations           | 17          |
|    time_elapsed         | 169         |
|    total_timesteps      | 5878528     |
| train/                  |             |
|    approx_kl            | 0.003819144 |
|    clip_fraction        | 0.0381      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.887      |
|    explained_variance   | 0.881       |
|    learning_rate        | 0.0003      |
|    loss                 | 279         |
|    n_updates            | 1428        |
|    policy_gradient_loss | -0.00039    |
|    value_loss           | 409         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 58.2        |
| time/                   |             |
|    fps                  | 1640        |
|    iterations           | 18          |
|    time_elapsed         | 179         |
|    total_timesteps      | 5894912     |
| train/                  |             |
|    approx_kl            | 0.005857434 |
|    clip_fraction        | 0.0542      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.862      |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | 58.1        |
|    n_updates            | 1432        |
|    policy_gradient_loss | -0.00126    |
|    value_loss           | 250         |
-----------------------------------------

Eval num_timesteps=5900000, episode_reward=51.06 +/- 41.33

Episode length: 103.65 +/- 36.07

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | 51.1        |
| time/                   |             |
|    total_timesteps      | 5900000     |
| train/                  |             |
|    approx_kl            | 0.004689902 |
|    clip_fraction        | 0.0446      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.87       |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | 73.4        |
|    n_updates            | 1436        |
|    policy_gradient_loss | -0.000311   |
|    value_loss           | 264         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_5900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 113      |
|    ep_rew_mean     | 58.2     |
| time/              |          |
|    fps             | 1626     |
|    iterations      | 19       |
|    time_elapsed    | 191      |
|    total_timesteps | 5911296  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 117         |
|    ep_rew_mean          | 60.5        |
| time/                   |             |
|    fps                  | 1629        |
|    iterations           | 20          |
|    time_elapsed         | 201         |
|    total_timesteps      | 5927680     |
| train/                  |             |
|    approx_kl            | 0.007512261 |
|    clip_fraction        | 0.065       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.911      |
|    explained_variance   | 0.904       |
|    learning_rate        | 0.0003      |
|    loss                 | 118         |
|    n_updates            | 1440        |
|    policy_gradient_loss | -0.00117    |
|    value_loss           | 353         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 57.2        |
| time/                   |             |
|    fps                  | 1641        |
|    iterations           | 21          |
|    time_elapsed         | 209         |
|    total_timesteps      | 5944064     |
| train/                  |             |
|    approx_kl            | 0.005661143 |
|    clip_fraction        | 0.064       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.923      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 192         |
|    n_updates            | 1444        |
|    policy_gradient_loss | -0.00014    |
|    value_loss           | 336         |
-----------------------------------------

Eval num_timesteps=5950000, episode_reward=34.00 +/- 83.09

Episode length: 126.85 +/- 43.64

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 127         |
|    mean_reward          | 34          |
| time/                   |             |
|    total_timesteps      | 5950000     |
| train/                  |             |
|    approx_kl            | 0.004445467 |
|    clip_fraction        | 0.0457      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.94       |
|    explained_variance   | 0.919       |
|    learning_rate        | 0.0003      |
|    loss                 | 58.6        |
|    n_updates            | 1448        |
|    policy_gradient_loss | 0.000399    |
|    value_loss           | 311         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 54.5     |
| time/              |          |
|    fps             | 1630     |
|    iterations      | 22       |
|    time_elapsed    | 221      |
|    total_timesteps | 5960448  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 62.6        |
| time/                   |             |
|    fps                  | 1634        |
|    iterations           | 23          |
|    time_elapsed         | 230         |
|    total_timesteps      | 5976832     |
| train/                  |             |
|    approx_kl            | 0.005223663 |
|    clip_fraction        | 0.0612      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.902      |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | 53.5        |
|    n_updates            | 1452        |
|    policy_gradient_loss | -0.00141    |
|    value_loss           | 109         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 60.9         |
| time/                   |              |
|    fps                  | 1639         |
|    iterations           | 24           |
|    time_elapsed         | 239          |
|    total_timesteps      | 5993216      |
| train/                  |              |
|    approx_kl            | 0.0052249227 |
|    clip_fraction        | 0.0519       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.924       |
|    explained_variance   | 0.913        |
|    learning_rate        | 0.0003       |
|    loss                 | 88.6         |
|    n_updates            | 1456         |
|    policy_gradient_loss | 7.79e-05     |
|    value_loss           | 281          |
------------------------------------------

Eval num_timesteps=6000000, episode_reward=81.50 +/- 54.43

Episode length: 111.45 +/- 28.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 81.5         |
| time/                   |              |
|    total_timesteps      | 6000000      |
| train/                  |              |
|    approx_kl            | 0.0052421046 |
|    clip_fraction        | 0.0598       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.9         |
|    explained_variance   | 0.951        |
|    learning_rate        | 0.0003       |
|    loss                 | 68.4         |
|    n_updates            | 1460         |
|    policy_gradient_loss | -0.000146    |
|    value_loss           | 110          |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 6,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 58.8     |
| time/              |          |
|    fps             | 1608     |
|    iterations      | 25       |
|    time_elapsed    | 254      |
|    total_timesteps | 6009600  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 60.7        |
| time/                   |             |
|    fps                  | 1617        |
|    iterations           | 26          |
|    time_elapsed         | 263         |
|    total_timesteps      | 6025984     |
| train/                  |             |
|    approx_kl            | 0.004365784 |
|    clip_fraction        | 0.039       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.901      |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | 238         |
|    n_updates            | 1464        |
|    policy_gradient_loss | 0.000508    |
|    value_loss           | 313         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 67.7        |
| time/                   |             |
|    fps                  | 1623        |
|    iterations           | 27          |
|    time_elapsed         | 272         |
|    total_timesteps      | 6042368     |
| train/                  |             |
|    approx_kl            | 0.004611818 |
|    clip_fraction        | 0.0484      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.903      |
|    explained_variance   | 0.946       |
|    learning_rate        | 0.0003      |
|    loss                 | 130         |
|    n_updates            | 1468        |
|    policy_gradient_loss | 3.56e-05    |
|    value_loss           | 127         |
-----------------------------------------

Eval num_timesteps=6050000, episode_reward=32.65 +/- 122.27

Episode length: 116.70 +/- 30.01

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 32.7        |
| time/                   |             |
|    total_timesteps      | 6050000     |
| train/                  |             |
|    approx_kl            | 0.004975139 |
|    clip_fraction        | 0.0459      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.915      |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | 119         |
|    n_updates            | 1472        |
|    policy_gradient_loss | 0.0007      |
|    value_loss           | 290         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 64.2     |
| time/              |          |
|    fps             | 1615     |
|    iterations      | 28       |
|    time_elapsed    | 284      |
|    total_timesteps | 6058752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 61.8         |
| time/                   |              |
|    fps                  | 1618         |
|    iterations           | 29           |
|    time_elapsed         | 293          |
|    total_timesteps      | 6075136      |
| train/                  |              |
|    approx_kl            | 0.0055897883 |
|    clip_fraction        | 0.0516       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.933       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 189          |
|    n_updates            | 1476         |
|    policy_gradient_loss | -2.18e-05    |
|    value_loss           | 390          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 59.1         |
| time/                   |              |
|    fps                  | 1628         |
|    iterations           | 30           |
|    time_elapsed         | 301          |
|    total_timesteps      | 6091520      |
| train/                  |              |
|    approx_kl            | 0.0048227524 |
|    clip_fraction        | 0.0574       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.917       |
|    explained_variance   | 0.934        |
|    learning_rate        | 0.0003       |
|    loss                 | 90.8         |
|    n_updates            | 1480         |
|    policy_gradient_loss | 0.000509     |
|    value_loss           | 168          |
------------------------------------------

Eval num_timesteps=6100000, episode_reward=35.48 +/- 146.99

Episode length: 116.60 +/- 23.56

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 35.5         |
| time/                   |              |
|    total_timesteps      | 6100000      |
| train/                  |              |
|    approx_kl            | 0.0056666317 |
|    clip_fraction        | 0.0756       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.931       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 28.9         |
|    n_updates            | 1484         |
|    policy_gradient_loss | 0.000784     |
|    value_loss           | 55.6         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 58.9     |
| time/              |          |
|    fps             | 1622     |
|    iterations      | 31       |
|    time_elapsed    | 313      |
|    total_timesteps | 6107904  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 56.3         |
| time/                   |              |
|    fps                  | 1624         |
|    iterations           | 32           |
|    time_elapsed         | 322          |
|    total_timesteps      | 6124288      |
| train/                  |              |
|    approx_kl            | 0.0050791954 |
|    clip_fraction        | 0.0505       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | 0.922        |
|    learning_rate        | 0.0003       |
|    loss                 | 34.4         |
|    n_updates            | 1488         |
|    policy_gradient_loss | -0.00115     |
|    value_loss           | 222          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 65           |
| time/                   |              |
|    fps                  | 1629         |
|    iterations           | 33           |
|    time_elapsed         | 331          |
|    total_timesteps      | 6140672      |
| train/                  |              |
|    approx_kl            | 0.0051299753 |
|    clip_fraction        | 0.0517       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.932       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 32.2         |
|    n_updates            | 1492         |
|    policy_gradient_loss | -0.000337    |
|    value_loss           | 114          |
------------------------------------------

Eval num_timesteps=6150000, episode_reward=21.05 +/- 144.84

Episode length: 117.65 +/- 33.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | 21.1         |
| time/                   |              |
|    total_timesteps      | 6150000      |
| train/                  |              |
|    approx_kl            | 0.0065236874 |
|    clip_fraction        | 0.068        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.936       |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 152          |
|    n_updates            | 1496         |
|    policy_gradient_loss | -0.000425    |
|    value_loss           | 227          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 69.5     |
| time/              |          |
|    fps             | 1625     |
|    iterations      | 34       |
|    time_elapsed    | 342      |
|    total_timesteps | 6157056  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 65.5         |
| time/                   |              |
|    fps                  | 1628         |
|    iterations           | 35           |
|    time_elapsed         | 352          |
|    total_timesteps      | 6173440      |
| train/                  |              |
|    approx_kl            | 0.0054343957 |
|    clip_fraction        | 0.0581       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.904       |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 65.8         |
|    n_updates            | 1500         |
|    policy_gradient_loss | -0.00221     |
|    value_loss           | 296          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 60.7         |
| time/                   |              |
|    fps                  | 1630         |
|    iterations           | 36           |
|    time_elapsed         | 361          |
|    total_timesteps      | 6189824      |
| train/                  |              |
|    approx_kl            | 0.0052698916 |
|    clip_fraction        | 0.069        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.925        |
|    learning_rate        | 0.0003       |
|    loss                 | 69.9         |
|    n_updates            | 1504         |
|    policy_gradient_loss | -0.00028     |
|    value_loss           | 221          |
------------------------------------------

Eval num_timesteps=6200000, episode_reward=81.20 +/- 98.65

Episode length: 106.95 +/- 20.08

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 107         |
|    mean_reward          | 81.2        |
| time/                   |             |
|    total_timesteps      | 6200000     |
| train/                  |             |
|    approx_kl            | 0.004983478 |
|    clip_fraction        | 0.0507      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.884      |
|    explained_variance   | 0.851       |
|    learning_rate        | 0.0003      |
|    loss                 | 235         |
|    n_updates            | 1508        |
|    policy_gradient_loss | -0.000585   |
|    value_loss           | 457         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 77.2     |
| time/              |          |
|    fps             | 1626     |
|    iterations      | 37       |
|    time_elapsed    | 372      |
|    total_timesteps | 6206208  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 62.2         |
| time/                   |              |
|    fps                  | 1633         |
|    iterations           | 38           |
|    time_elapsed         | 381          |
|    total_timesteps      | 6222592      |
| train/                  |              |
|    approx_kl            | 0.0042038737 |
|    clip_fraction        | 0.0341       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.893       |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 185          |
|    n_updates            | 1512         |
|    policy_gradient_loss | 8.18e-05     |
|    value_loss           | 538          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 72.1         |
| time/                   |              |
|    fps                  | 1636         |
|    iterations           | 39           |
|    time_elapsed         | 390          |
|    total_timesteps      | 6238976      |
| train/                  |              |
|    approx_kl            | 0.0040757754 |
|    clip_fraction        | 0.0444       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.874       |
|    explained_variance   | 0.872        |
|    learning_rate        | 0.0003       |
|    loss                 | 157          |
|    n_updates            | 1516         |
|    policy_gradient_loss | -0.000494    |
|    value_loss           | 423          |
------------------------------------------

Eval num_timesteps=6250000, episode_reward=-182.73 +/- 317.49

Episode length: 123.65 +/- 33.38

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 124          |
|    mean_reward          | -183         |
| time/                   |              |
|    total_timesteps      | 6250000      |
| train/                  |              |
|    approx_kl            | 0.0052298615 |
|    clip_fraction        | 0.041        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.893       |
|    explained_variance   | 0.826        |
|    learning_rate        | 0.0003       |
|    loss                 | 502          |
|    n_updates            | 1520         |
|    policy_gradient_loss | -0.000168    |
|    value_loss           | 722          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 81.3     |
| time/              |          |
|    fps             | 1630     |
|    iterations      | 40       |
|    time_elapsed    | 402      |
|    total_timesteps | 6255360  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 65           |
| time/                   |              |
|    fps                  | 1634         |
|    iterations           | 41           |
|    time_elapsed         | 410          |
|    total_timesteps      | 6271744      |
| train/                  |              |
|    approx_kl            | 0.0037558759 |
|    clip_fraction        | 0.0344       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.819        |
|    learning_rate        | 0.0003       |
|    loss                 | 408          |
|    n_updates            | 1524         |
|    policy_gradient_loss | -0.00037     |
|    value_loss           | 763          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 117         |
|    ep_rew_mean          | 63.8        |
| time/                   |             |
|    fps                  | 1638        |
|    iterations           | 42          |
|    time_elapsed         | 420         |
|    total_timesteps      | 6288128     |
| train/                  |             |
|    approx_kl            | 0.004286011 |
|    clip_fraction        | 0.0403      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.878      |
|    explained_variance   | 0.85        |
|    learning_rate        | 0.0003      |
|    loss                 | 597         |
|    n_updates            | 1528        |
|    policy_gradient_loss | 0.000595    |
|    value_loss           | 642         |
-----------------------------------------

Eval num_timesteps=6300000, episode_reward=-71.40 +/- 219.89

Episode length: 116.45 +/- 30.35

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | -71.4        |
| time/                   |              |
|    total_timesteps      | 6300000      |
| train/                  |              |
|    approx_kl            | 0.0051222397 |
|    clip_fraction        | 0.0474       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.894       |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 434          |
|    n_updates            | 1532         |
|    policy_gradient_loss | -0.000916    |
|    value_loss           | 634          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 86.7     |
| time/              |          |
|    fps             | 1631     |
|    iterations      | 43       |
|    time_elapsed    | 431      |
|    total_timesteps | 6304512  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 63.1        |
| time/                   |             |
|    fps                  | 1633        |
|    iterations           | 44          |
|    time_elapsed         | 441         |
|    total_timesteps      | 6320896     |
| train/                  |             |
|    approx_kl            | 0.004059169 |
|    clip_fraction        | 0.032       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.891      |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | 303         |
|    n_updates            | 1536        |
|    policy_gradient_loss | -4.2e-05    |
|    value_loss           | 806         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 65.7         |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 45           |
|    time_elapsed         | 449          |
|    total_timesteps      | 6337280      |
| train/                  |              |
|    approx_kl            | 0.0040954016 |
|    clip_fraction        | 0.0295       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.872       |
|    explained_variance   | 0.851        |
|    learning_rate        | 0.0003       |
|    loss                 | 184          |
|    n_updates            | 1540         |
|    policy_gradient_loss | 0.000127     |
|    value_loss           | 493          |
------------------------------------------

Eval num_timesteps=6350000, episode_reward=-34.93 +/- 198.62

Episode length: 111.60 +/- 27.28

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -34.9        |
| time/                   |              |
|    total_timesteps      | 6350000      |
| train/                  |              |
|    approx_kl            | 0.0045729345 |
|    clip_fraction        | 0.037        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.855        |
|    learning_rate        | 0.0003       |
|    loss                 | 169          |
|    n_updates            | 1544         |
|    policy_gradient_loss | -0.000362    |
|    value_loss           | 608          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 55.1     |
| time/              |          |
|    fps             | 1635     |
|    iterations      | 46       |
|    time_elapsed    | 460      |
|    total_timesteps | 6353664  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 68.4         |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 47           |
|    time_elapsed         | 470          |
|    total_timesteps      | 6370048      |
| train/                  |              |
|    approx_kl            | 0.0038850987 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.901       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 480          |
|    n_updates            | 1548         |
|    policy_gradient_loss | 0.000984     |
|    value_loss           | 744          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 66.7         |
| time/                   |              |
|    fps                  | 1639         |
|    iterations           | 48           |
|    time_elapsed         | 479          |
|    total_timesteps      | 6386432      |
| train/                  |              |
|    approx_kl            | 0.0038941929 |
|    clip_fraction        | 0.0288       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 372          |
|    n_updates            | 1552         |
|    policy_gradient_loss | 0.000597     |
|    value_loss           | 832          |
------------------------------------------

Eval num_timesteps=6400000, episode_reward=91.97 +/- 64.25

Episode length: 90.50 +/- 12.75

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 90.5        |
|    mean_reward          | 92          |
| time/                   |             |
|    total_timesteps      | 6400000     |
| train/                  |             |
|    approx_kl            | 0.003524147 |
|    clip_fraction        | 0.0356      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.889      |
|    explained_variance   | 0.878       |
|    learning_rate        | 0.0003      |
|    loss                 | 216         |
|    n_updates            | 1556        |
|    policy_gradient_loss | 0.000805    |
|    value_loss           | 406         |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 79.2     |
| time/              |          |
|    fps             | 1639     |
|    iterations      | 49       |
|    time_elapsed    | 489      |
|    total_timesteps | 6402816  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 69.7         |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 50           |
|    time_elapsed         | 499          |
|    total_timesteps      | 6419200      |
| train/                  |              |
|    approx_kl            | 0.0030700245 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.866       |
|    explained_variance   | 0.848        |
|    learning_rate        | 0.0003       |
|    loss                 | 178          |
|    n_updates            | 1560         |
|    policy_gradient_loss | 0.000973     |
|    value_loss           | 559          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 63.5         |
| time/                   |              |
|    fps                  | 1641         |
|    iterations           | 51           |
|    time_elapsed         | 508          |
|    total_timesteps      | 6435584      |
| train/                  |              |
|    approx_kl            | 0.0027457005 |
|    clip_fraction        | 0.0282       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.869        |
|    learning_rate        | 0.0003       |
|    loss                 | 241          |
|    n_updates            | 1564         |
|    policy_gradient_loss | -1.29e-05    |
|    value_loss           | 565          |
------------------------------------------

Eval num_timesteps=6450000, episode_reward=91.36 +/- 106.38

Episode length: 103.55 +/- 24.48

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | 91.4        |
| time/                   |             |
|    total_timesteps      | 6450000     |
| train/                  |             |
|    approx_kl            | 0.003000001 |
|    clip_fraction        | 0.0373      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.873      |
|    explained_variance   | 0.884       |
|    learning_rate        | 0.0003      |
|    loss                 | 268         |
|    n_updates            | 1568        |
|    policy_gradient_loss | 0.000553    |
|    value_loss           | 467         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 82.2     |
| time/              |          |
|    fps             | 1639     |
|    iterations      | 52       |
|    time_elapsed    | 519      |
|    total_timesteps | 6451968  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 71.7        |
| time/                   |             |
|    fps                  | 1644        |
|    iterations           | 53          |
|    time_elapsed         | 527         |
|    total_timesteps      | 6468352     |
| train/                  |             |
|    approx_kl            | 0.003983779 |
|    clip_fraction        | 0.0393      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.877      |
|    explained_variance   | 0.824       |
|    learning_rate        | 0.0003      |
|    loss                 | 159         |
|    n_updates            | 1572        |
|    policy_gradient_loss | 0.000597    |
|    value_loss           | 534         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 85.1        |
| time/                   |             |
|    fps                  | 1647        |
|    iterations           | 54          |
|    time_elapsed         | 537         |
|    total_timesteps      | 6484736     |
| train/                  |             |
|    approx_kl            | 0.004665751 |
|    clip_fraction        | 0.0485      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.839      |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | 90.8        |
|    n_updates            | 1576        |
|    policy_gradient_loss | -0.00162    |
|    value_loss           | 432         |
-----------------------------------------

Eval num_timesteps=6500000, episode_reward=19.06 +/- 93.42

Episode length: 116.90 +/- 39.47

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 19.1        |
| time/                   |             |
|    total_timesteps      | 6500000     |
| train/                  |             |
|    approx_kl            | 0.004478287 |
|    clip_fraction        | 0.0406      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.864      |
|    explained_variance   | 0.85        |
|    learning_rate        | 0.0003      |
|    loss                 | 155         |
|    n_updates            | 1580        |
|    policy_gradient_loss | -0.00043    |
|    value_loss           | 542         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 77.9     |
| time/              |          |
|    fps             | 1643     |
|    iterations      | 55       |
|    time_elapsed    | 548      |
|    total_timesteps | 6501120  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 73.9         |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 56           |
|    time_elapsed         | 556          |
|    total_timesteps      | 6517504      |
| train/                  |              |
|    approx_kl            | 0.0041174833 |
|    clip_fraction        | 0.0246       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | -0.166       |
|    learning_rate        | 0.0003       |
|    loss                 | 389          |
|    n_updates            | 1584         |
|    policy_gradient_loss | -0.000289    |
|    value_loss           | 5.86e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 65.6        |
| time/                   |             |
|    fps                  | 1649        |
|    iterations           | 57          |
|    time_elapsed         | 566         |
|    total_timesteps      | 6533888     |
| train/                  |             |
|    approx_kl            | 0.004189196 |
|    clip_fraction        | 0.0395      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.904      |
|    explained_variance   | 0.866       |
|    learning_rate        | 0.0003      |
|    loss                 | 103         |
|    n_updates            | 1588        |
|    policy_gradient_loss | -8.42e-05   |
|    value_loss           | 387         |
-----------------------------------------

Eval num_timesteps=6550000, episode_reward=55.03 +/- 143.01

Episode length: 111.10 +/- 26.29

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 55           |
| time/                   |              |
|    total_timesteps      | 6550000      |
| train/                  |              |
|    approx_kl            | 0.0049502607 |
|    clip_fraction        | 0.0602       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.888       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 267          |
|    n_updates            | 1592         |
|    policy_gradient_loss | -0.000578    |
|    value_loss           | 352          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 73.8     |
| time/              |          |
|    fps             | 1644     |
|    iterations      | 58       |
|    time_elapsed    | 577      |
|    total_timesteps | 6550272  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 77           |
| time/                   |              |
|    fps                  | 1645         |
|    iterations           | 59           |
|    time_elapsed         | 587          |
|    total_timesteps      | 6566656      |
| train/                  |              |
|    approx_kl            | 0.0037213494 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.912       |
|    explained_variance   | 0.816        |
|    learning_rate        | 0.0003       |
|    loss                 | 426          |
|    n_updates            | 1596         |
|    policy_gradient_loss | 0.000339     |
|    value_loss           | 885          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 114          |
|    ep_rew_mean          | 65.8         |
| time/                   |              |
|    fps                  | 1650         |
|    iterations           | 60           |
|    time_elapsed         | 595          |
|    total_timesteps      | 6583040      |
| train/                  |              |
|    approx_kl            | 0.0036555838 |
|    clip_fraction        | 0.0387       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.914       |
|    explained_variance   | 0.865        |
|    learning_rate        | 0.0003       |
|    loss                 | 214          |
|    n_updates            | 1600         |
|    policy_gradient_loss | -0.000427    |
|    value_loss           | 469          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 82.9         |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 61           |
|    time_elapsed         | 605          |
|    total_timesteps      | 6599424      |
| train/                  |              |
|    approx_kl            | 0.0050541395 |
|    clip_fraction        | 0.0505       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.855       |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 41.5         |
|    n_updates            | 1604         |
|    policy_gradient_loss | -0.000682    |
|    value_loss           | 349          |
------------------------------------------

Eval num_timesteps=6600000, episode_reward=58.98 +/- 102.88

Episode length: 122.95 +/- 35.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 123          |
|    mean_reward          | 59           |
| time/                   |              |
|    total_timesteps      | 6600000      |
| train/                  |              |
|    approx_kl            | 0.0037132706 |
|    clip_fraction        | 0.0287       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.867       |
|    explained_variance   | 0.818        |
|    learning_rate        | 0.0003       |
|    loss                 | 135          |
|    n_updates            | 1608         |
|    policy_gradient_loss | -0.000234    |
|    value_loss           | 715          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 60.4     |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 62       |
|    time_elapsed    | 616      |
|    total_timesteps | 6615808  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 60.3        |
| time/                   |             |
|    fps                  | 1650        |
|    iterations           | 63          |
|    time_elapsed         | 625         |
|    total_timesteps      | 6632192     |
| train/                  |             |
|    approx_kl            | 0.004439608 |
|    clip_fraction        | 0.0368      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.881      |
|    explained_variance   | 0.86        |
|    learning_rate        | 0.0003      |
|    loss                 | 168         |
|    n_updates            | 1612        |
|    policy_gradient_loss | 5.42e-05    |
|    value_loss           | 560         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 66.3        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 64          |
|    time_elapsed         | 634         |
|    total_timesteps      | 6648576     |
| train/                  |             |
|    approx_kl            | 0.005952221 |
|    clip_fraction        | 0.0577      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.872      |
|    explained_variance   | 0.902       |
|    learning_rate        | 0.0003      |
|    loss                 | 46.3        |
|    n_updates            | 1616        |
|    policy_gradient_loss | -0.00211    |
|    value_loss           | 298         |
-----------------------------------------

Eval num_timesteps=6650000, episode_reward=70.95 +/- 192.22

Episode length: 117.55 +/- 28.24

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | 70.9         |
| time/                   |              |
|    total_timesteps      | 6650000      |
| train/                  |              |
|    approx_kl            | 0.0045209825 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.925       |
|    explained_variance   | 0.899        |
|    learning_rate        | 0.0003       |
|    loss                 | 344          |
|    n_updates            | 1620         |
|    policy_gradient_loss | -0.00113     |
|    value_loss           | 912          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 85.8     |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 65       |
|    time_elapsed    | 645      |
|    total_timesteps | 6664960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 114          |
|    ep_rew_mean          | 71.1         |
| time/                   |              |
|    fps                  | 1649         |
|    iterations           | 66           |
|    time_elapsed         | 655          |
|    total_timesteps      | 6681344      |
| train/                  |              |
|    approx_kl            | 0.0055331183 |
|    clip_fraction        | 0.047        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.91        |
|    explained_variance   | 0.921        |
|    learning_rate        | 0.0003       |
|    loss                 | 214          |
|    n_updates            | 1624         |
|    policy_gradient_loss | -0.00149     |
|    value_loss           | 634          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 111         |
|    ep_rew_mean          | 73.2        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 67          |
|    time_elapsed         | 663         |
|    total_timesteps      | 6697728     |
| train/                  |             |
|    approx_kl            | 0.005290713 |
|    clip_fraction        | 0.0439      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.87        |
|    learning_rate        | 0.0003      |
|    loss                 | 117         |
|    n_updates            | 1628        |
|    policy_gradient_loss | -0.00054    |
|    value_loss           | 423         |
-----------------------------------------

Eval num_timesteps=6700000, episode_reward=-30.29 +/- 101.12

Episode length: 106.20 +/- 19.38

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | -30.3       |
| time/                   |             |
|    total_timesteps      | 6700000     |
| train/                  |             |
|    approx_kl            | 0.006061624 |
|    clip_fraction        | 0.0757      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.884      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 329         |
|    n_updates            | 1632        |
|    policy_gradient_loss | -0.0026     |
|    value_loss           | 439         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 66       |
| time/              |          |
|    fps             | 1650     |
|    iterations      | 68       |
|    time_elapsed    | 675      |
|    total_timesteps | 6714112  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 50.3        |
| time/                   |             |
|    fps                  | 1650        |
|    iterations           | 69          |
|    time_elapsed         | 684         |
|    total_timesteps      | 6730496     |
| train/                  |             |
|    approx_kl            | 0.004519161 |
|    clip_fraction        | 0.03        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.884      |
|    explained_variance   | 0.921       |
|    learning_rate        | 0.0003      |
|    loss                 | 542         |
|    n_updates            | 1636        |
|    policy_gradient_loss | -0.000413   |
|    value_loss           | 910         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 75.5         |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 70           |
|    time_elapsed         | 694          |
|    total_timesteps      | 6746880      |
| train/                  |              |
|    approx_kl            | 0.0048747053 |
|    clip_fraction        | 0.0486       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.942       |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23e+03     |
|    n_updates            | 1640         |
|    policy_gradient_loss | -0.000509    |
|    value_loss           | 1.67e+03     |
------------------------------------------

Eval num_timesteps=6750000, episode_reward=43.77 +/- 112.52

Episode length: 104.75 +/- 16.56

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 105          |
|    mean_reward          | 43.8         |
| time/                   |              |
|    total_timesteps      | 6750000      |
| train/                  |              |
|    approx_kl            | 0.0055758543 |
|    clip_fraction        | 0.0512       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.972       |
|    explained_variance   | 0.879        |
|    learning_rate        | 0.0003       |
|    loss                 | 127          |
|    n_updates            | 1644         |
|    policy_gradient_loss | -0.000474    |
|    value_loss           | 813          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 67.1     |
| time/              |          |
|    fps             | 1650     |
|    iterations      | 71       |
|    time_elapsed    | 704      |
|    total_timesteps | 6763264  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 58.3        |
| time/                   |             |
|    fps                  | 1652        |
|    iterations           | 72          |
|    time_elapsed         | 713         |
|    total_timesteps      | 6779648     |
| train/                  |             |
|    approx_kl            | 0.003038676 |
|    clip_fraction        | 0.0295      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.879      |
|    explained_variance   | 0.915       |
|    learning_rate        | 0.0003      |
|    loss                 | 198         |
|    n_updates            | 1648        |
|    policy_gradient_loss | 0.000211    |
|    value_loss           | 482         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 67.4        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 73          |
|    time_elapsed         | 723         |
|    total_timesteps      | 6796032     |
| train/                  |             |
|    approx_kl            | 0.004012673 |
|    clip_fraction        | 0.0383      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.887      |
|    explained_variance   | 0.857       |
|    learning_rate        | 0.0003      |
|    loss                 | 387         |
|    n_updates            | 1652        |
|    policy_gradient_loss | -0.000461   |
|    value_loss           | 523         |
-----------------------------------------

Eval num_timesteps=6800000, episode_reward=17.68 +/- 148.02

Episode length: 116.70 +/- 30.26

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 17.7        |
| time/                   |             |
|    total_timesteps      | 6800000     |
| train/                  |             |
|    approx_kl            | 0.003366774 |
|    clip_fraction        | 0.0314      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.851      |
|    explained_variance   | 0.942       |
|    learning_rate        | 0.0003      |
|    loss                 | 327         |
|    n_updates            | 1656        |
|    policy_gradient_loss | -0.000394   |
|    value_loss           | 571         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 75.6     |
| time/              |          |
|    fps             | 1649     |
|    iterations      | 74       |
|    time_elapsed    | 734      |
|    total_timesteps | 6812416  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 68.1        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 75          |
|    time_elapsed         | 743         |
|    total_timesteps      | 6828800     |
| train/                  |             |
|    approx_kl            | 0.004949821 |
|    clip_fraction        | 0.0437      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.904      |
|    explained_variance   | 0.84        |
|    learning_rate        | 0.0003      |
|    loss                 | 139         |
|    n_updates            | 1660        |
|    policy_gradient_loss | -0.00076    |
|    value_loss           | 750         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 81.4        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 76          |
|    time_elapsed         | 752         |
|    total_timesteps      | 6845184     |
| train/                  |             |
|    approx_kl            | 0.004169711 |
|    clip_fraction        | 0.0378      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.891      |
|    explained_variance   | 0.906       |
|    learning_rate        | 0.0003      |
|    loss                 | 151         |
|    n_updates            | 1664        |
|    policy_gradient_loss | -8.62e-05   |
|    value_loss           | 655         |
-----------------------------------------

Eval num_timesteps=6850000, episode_reward=-46.91 +/- 102.03

Episode length: 109.20 +/- 22.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | -46.9        |
| time/                   |              |
|    total_timesteps      | 6850000      |
| train/                  |              |
|    approx_kl            | 0.0039459076 |
|    clip_fraction        | 0.0378       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 308          |
|    n_updates            | 1668         |
|    policy_gradient_loss | -0.000699    |
|    value_loss           | 590          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 69.2     |
| time/              |          |
|    fps             | 1651     |
|    iterations      | 77       |
|    time_elapsed    | 764      |
|    total_timesteps | 6861568  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 57.3        |
| time/                   |             |
|    fps                  | 1652        |
|    iterations           | 78          |
|    time_elapsed         | 773         |
|    total_timesteps      | 6877952     |
| train/                  |             |
|    approx_kl            | 0.004188287 |
|    clip_fraction        | 0.0323      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.855      |
|    explained_variance   | 0.844       |
|    learning_rate        | 0.0003      |
|    loss                 | 166         |
|    n_updates            | 1672        |
|    policy_gradient_loss | -0.000292   |
|    value_loss           | 524         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 88.1         |
| time/                   |              |
|    fps                  | 1656         |
|    iterations           | 79           |
|    time_elapsed         | 781          |
|    total_timesteps      | 6894336      |
| train/                  |              |
|    approx_kl            | 0.0035173227 |
|    clip_fraction        | 0.0223       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.927        |
|    learning_rate        | 0.0003       |
|    loss                 | 291          |
|    n_updates            | 1676         |
|    policy_gradient_loss | 9.77e-05     |
|    value_loss           | 1.12e+03     |
------------------------------------------

Eval num_timesteps=6900000, episode_reward=10.15 +/- 148.23

Episode length: 108.10 +/- 25.27

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | 10.1         |
| time/                   |              |
|    total_timesteps      | 6900000      |
| train/                  |              |
|    approx_kl            | 0.0032780673 |
|    clip_fraction        | 0.0302       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | 0.923        |
|    learning_rate        | 0.0003       |
|    loss                 | 367          |
|    n_updates            | 1680         |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 741          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_6900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 85.6     |
| time/              |          |
|    fps             | 1653     |
|    iterations      | 80       |
|    time_elapsed    | 792      |
|    total_timesteps | 6910720  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 140         |
|    ep_rew_mean          | 88.2        |
| time/                   |             |
|    fps                  | 1654        |
|    iterations           | 81          |
|    time_elapsed         | 802         |
|    total_timesteps      | 6927104     |
| train/                  |             |
|    approx_kl            | 0.003939521 |
|    clip_fraction        | 0.0226      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.836      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 298         |
|    n_updates            | 1684        |
|    policy_gradient_loss | -0.00112    |
|    value_loss           | 644         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 113         |
|    ep_rew_mean          | 71.8        |
| time/                   |             |
|    fps                  | 1657        |
|    iterations           | 82          |
|    time_elapsed         | 810         |
|    total_timesteps      | 6943488     |
| train/                  |             |
|    approx_kl            | 0.003043453 |
|    clip_fraction        | 0.0167      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.874      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.35e+03    |
|    n_updates            | 1688        |
|    policy_gradient_loss | -0.000163   |
|    value_loss           | 1.63e+03    |
-----------------------------------------

Eval num_timesteps=6950000, episode_reward=57.10 +/- 105.76

Episode length: 92.60 +/- 14.92

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 92.6       |
|    mean_reward          | 57.1       |
| time/                   |            |
|    total_timesteps      | 6950000    |
| train/                  |            |
|    approx_kl            | 0.00421797 |
|    clip_fraction        | 0.0303     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.84      |
|    explained_variance   | 0.866      |
|    learning_rate        | 0.0003     |
|    loss                 | 782        |
|    n_updates            | 1692       |
|    policy_gradient_loss | -0.00126   |
|    value_loss           | 1.19e+03   |
----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 69       |
| time/              |          |
|    fps             | 1656     |
|    iterations      | 83       |
|    time_elapsed    | 821      |
|    total_timesteps | 6959872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 71.3         |
| time/                   |              |
|    fps                  | 1657         |
|    iterations           | 84           |
|    time_elapsed         | 830          |
|    total_timesteps      | 6976256      |
| train/                  |              |
|    approx_kl            | 0.0034027824 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 659          |
|    n_updates            | 1696         |
|    policy_gradient_loss | -0.00154     |
|    value_loss           | 1.15e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 112         |
|    ep_rew_mean          | 68.7        |
| time/                   |             |
|    fps                  | 1659        |
|    iterations           | 85          |
|    time_elapsed         | 839         |
|    total_timesteps      | 6992640     |
| train/                  |             |
|    approx_kl            | 0.003655945 |
|    clip_fraction        | 0.0333      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.858      |
|    explained_variance   | 0.86        |
|    learning_rate        | 0.0003      |
|    loss                 | 219         |
|    n_updates            | 1700        |
|    policy_gradient_loss | -1.61e-05   |
|    value_loss           | 493         |
-----------------------------------------

Eval num_timesteps=7000000, episode_reward=-72.69 +/- 98.42

Episode length: 101.55 +/- 18.85

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 102         |
|    mean_reward          | -72.7       |
| time/                   |             |
|    total_timesteps      | 7000000     |
| train/                  |             |
|    approx_kl            | 0.004720561 |
|    clip_fraction        | 0.0359      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.814      |
|    explained_variance   | 0.853       |
|    learning_rate        | 0.0003      |
|    loss                 | 248         |
|    n_updates            | 1704        |
|    policy_gradient_loss | -0.000122   |
|    value_loss           | 495         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 7,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 77       |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 86       |
|    time_elapsed    | 854      |
|    total_timesteps | 7009024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 67.3         |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 87           |
|    time_elapsed         | 862          |
|    total_timesteps      | 7025408      |
| train/                  |              |
|    approx_kl            | 0.0054668253 |
|    clip_fraction        | 0.0396       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.858       |
|    explained_variance   | 0.774        |
|    learning_rate        | 0.0003       |
|    loss                 | 464          |
|    n_updates            | 1708         |
|    policy_gradient_loss | -0.0016      |
|    value_loss           | 1.36e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 114         |
|    ep_rew_mean          | 79.4        |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 88          |
|    time_elapsed         | 872         |
|    total_timesteps      | 7041792     |
| train/                  |             |
|    approx_kl            | 0.003881986 |
|    clip_fraction        | 0.0392      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.858       |
|    learning_rate        | 0.0003      |
|    loss                 | 227         |
|    n_updates            | 1712        |
|    policy_gradient_loss | -0.000596   |
|    value_loss           | 736         |
-----------------------------------------

Eval num_timesteps=7050000, episode_reward=2.03 +/- 194.92

Episode length: 104.40 +/- 30.88

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | 2.03        |
| time/                   |             |
|    total_timesteps      | 7050000     |
| train/                  |             |
|    approx_kl            | 0.004125242 |
|    clip_fraction        | 0.0262      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.856      |
|    explained_variance   | 0.817       |
|    learning_rate        | 0.0003      |
|    loss                 | 348         |
|    n_updates            | 1716        |
|    policy_gradient_loss | -0.000188   |
|    value_loss           | 556         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 112      |
|    ep_rew_mean     | 85.1     |
| time/              |          |
|    fps             | 1651     |
|    iterations      | 89       |
|    time_elapsed    | 883      |
|    total_timesteps | 7058176  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 56.1        |
| time/                   |             |
|    fps                  | 1652        |
|    iterations           | 90          |
|    time_elapsed         | 892         |
|    total_timesteps      | 7074560     |
| train/                  |             |
|    approx_kl            | 0.004123227 |
|    clip_fraction        | 0.0272      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.835      |
|    explained_variance   | 0.851       |
|    learning_rate        | 0.0003      |
|    loss                 | 285         |
|    n_updates            | 1720        |
|    policy_gradient_loss | 0.000175    |
|    value_loss           | 581         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 89.2        |
| time/                   |             |
|    fps                  | 1655        |
|    iterations           | 91          |
|    time_elapsed         | 900         |
|    total_timesteps      | 7090944     |
| train/                  |             |
|    approx_kl            | 0.004020787 |
|    clip_fraction        | 0.0324      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.888      |
|    explained_variance   | 0.826       |
|    learning_rate        | 0.0003      |
|    loss                 | 324         |
|    n_updates            | 1724        |
|    policy_gradient_loss | 0.000585    |
|    value_loss           | 760         |
-----------------------------------------

Eval num_timesteps=7100000, episode_reward=36.10 +/- 141.13

Episode length: 95.55 +/- 19.71

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 95.5         |
|    mean_reward          | 36.1         |
| time/                   |              |
|    total_timesteps      | 7100000      |
| train/                  |              |
|    approx_kl            | 0.0036861817 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.823        |
|    learning_rate        | 0.0003       |
|    loss                 | 244          |
|    n_updates            | 1728         |
|    policy_gradient_loss | -0.000923    |
|    value_loss           | 664          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 85.3     |
| time/              |          |
|    fps             | 1653     |
|    iterations      | 92       |
|    time_elapsed    | 911      |
|    total_timesteps | 7107328  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 82.1         |
| time/                   |              |
|    fps                  | 1654         |
|    iterations           | 93           |
|    time_elapsed         | 920          |
|    total_timesteps      | 7123712      |
| train/                  |              |
|    approx_kl            | 0.0034344036 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.863       |
|    explained_variance   | 0.788        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.5e+03      |
|    n_updates            | 1732         |
|    policy_gradient_loss | -0.000162    |
|    value_loss           | 1.05e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 77.7         |
| time/                   |              |
|    fps                  | 1657         |
|    iterations           | 94           |
|    time_elapsed         | 928          |
|    total_timesteps      | 7140096      |
| train/                  |              |
|    approx_kl            | 0.0042288816 |
|    clip_fraction        | 0.0342       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.925       |
|    explained_variance   | 0.801        |
|    learning_rate        | 0.0003       |
|    loss                 | 947          |
|    n_updates            | 1736         |
|    policy_gradient_loss | -0.000427    |
|    value_loss           | 1.41e+03     |
------------------------------------------

Eval num_timesteps=7150000, episode_reward=69.80 +/- 121.98

Episode length: 102.85 +/- 23.57

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | 69.8         |
| time/                   |              |
|    total_timesteps      | 7150000      |
| train/                  |              |
|    approx_kl            | 0.0045460374 |
|    clip_fraction        | 0.0498       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.905       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 207          |
|    n_updates            | 1740         |
|    policy_gradient_loss | -0.000659    |
|    value_loss           | 589          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 80       |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 95       |
|    time_elapsed    | 940      |
|    total_timesteps | 7156480  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 67           |
| time/                   |              |
|    fps                  | 1656         |
|    iterations           | 96           |
|    time_elapsed         | 949          |
|    total_timesteps      | 7172864      |
| train/                  |              |
|    approx_kl            | 0.0034151755 |
|    clip_fraction        | 0.0354       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.895       |
|    explained_variance   | 0.83         |
|    learning_rate        | 0.0003       |
|    loss                 | 172          |
|    n_updates            | 1744         |
|    policy_gradient_loss | -0.00134     |
|    value_loss           | 700          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 52.2        |
| time/                   |             |
|    fps                  | 1658        |
|    iterations           | 97          |
|    time_elapsed         | 958         |
|    total_timesteps      | 7189248     |
| train/                  |             |
|    approx_kl            | 0.003290757 |
|    clip_fraction        | 0.0311      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.839      |
|    explained_variance   | 0.881       |
|    learning_rate        | 0.0003      |
|    loss                 | 177         |
|    n_updates            | 1748        |
|    policy_gradient_loss | -0.000721   |
|    value_loss           | 358         |
-----------------------------------------

Eval num_timesteps=7200000, episode_reward=77.17 +/- 81.43

Episode length: 103.25 +/- 17.77

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | 77.2         |
| time/                   |              |
|    total_timesteps      | 7200000      |
| train/                  |              |
|    approx_kl            | 0.0033018284 |
|    clip_fraction        | 0.0249       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.864       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 425          |
|    n_updates            | 1752         |
|    policy_gradient_loss | -0.000164    |
|    value_loss           | 741          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 77.4     |
| time/              |          |
|    fps             | 1657     |
|    iterations      | 98       |
|    time_elapsed    | 968      |
|    total_timesteps | 7205632  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 70.7        |
| time/                   |             |
|    fps                  | 1658        |
|    iterations           | 99          |
|    time_elapsed         | 977         |
|    total_timesteps      | 7222016     |
| train/                  |             |
|    approx_kl            | 0.002912927 |
|    clip_fraction        | 0.0254      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.891      |
|    explained_variance   | 0.825       |
|    learning_rate        | 0.0003      |
|    loss                 | 803         |
|    n_updates            | 1756        |
|    policy_gradient_loss | 5.8e-05     |
|    value_loss           | 798         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 67.7        |
| time/                   |             |
|    fps                  | 1659        |
|    iterations           | 100         |
|    time_elapsed         | 987         |
|    total_timesteps      | 7238400     |
| train/                  |             |
|    approx_kl            | 0.004884463 |
|    clip_fraction        | 0.0445      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.928      |
|    explained_variance   | 0.798       |
|    learning_rate        | 0.0003      |
|    loss                 | 792         |
|    n_updates            | 1760        |
|    policy_gradient_loss | -0.00141    |
|    value_loss           | 1.43e+03    |
-----------------------------------------

Eval num_timesteps=7250000, episode_reward=45.72 +/- 90.22

Episode length: 99.90 +/- 24.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99.9         |
|    mean_reward          | 45.7         |
| time/                   |              |
|    total_timesteps      | 7250000      |
| train/                  |              |
|    approx_kl            | 0.0034577693 |
|    clip_fraction        | 0.0244       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.855        |
|    learning_rate        | 0.0003       |
|    loss                 | 256          |
|    n_updates            | 1764         |
|    policy_gradient_loss | -0.000122    |
|    value_loss           | 467          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 67.9     |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 101      |
|    time_elapsed    | 997      |
|    total_timesteps | 7254784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 68.5         |
| time/                   |              |
|    fps                  | 1660         |
|    iterations           | 102          |
|    time_elapsed         | 1006         |
|    total_timesteps      | 7271168      |
| train/                  |              |
|    approx_kl            | 0.0055039763 |
|    clip_fraction        | 0.0684       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.867       |
|    explained_variance   | 0.896        |
|    learning_rate        | 0.0003       |
|    loss                 | 41.6         |
|    n_updates            | 1768         |
|    policy_gradient_loss | -0.00169     |
|    value_loss           | 150          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 69.1         |
| time/                   |              |
|    fps                  | 1661         |
|    iterations           | 103          |
|    time_elapsed         | 1015         |
|    total_timesteps      | 7287552      |
| train/                  |              |
|    approx_kl            | 0.0055007115 |
|    clip_fraction        | 0.0469       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 167          |
|    n_updates            | 1772         |
|    policy_gradient_loss | -0.00175     |
|    value_loss           | 413          |
------------------------------------------

Eval num_timesteps=7300000, episode_reward=-130.77 +/- 224.71

Episode length: 118.00 +/- 29.21

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | -131         |
| time/                   |              |
|    total_timesteps      | 7300000      |
| train/                  |              |
|    approx_kl            | 0.0058802227 |
|    clip_fraction        | 0.0471       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.921       |
|    explained_variance   | 0.866        |
|    learning_rate        | 0.0003       |
|    loss                 | 237          |
|    n_updates            | 1776         |
|    policy_gradient_loss | -0.00229     |
|    value_loss           | 419          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 57.2     |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 104      |
|    time_elapsed    | 1026     |
|    total_timesteps | 7303936  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 58.2        |
| time/                   |             |
|    fps                  | 1661        |
|    iterations           | 105         |
|    time_elapsed         | 1035        |
|    total_timesteps      | 7320320     |
| train/                  |             |
|    approx_kl            | 0.003312556 |
|    clip_fraction        | 0.0317      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.923      |
|    explained_variance   | 0.804       |
|    learning_rate        | 0.0003      |
|    loss                 | 378         |
|    n_updates            | 1780        |
|    policy_gradient_loss | -0.000893   |
|    value_loss           | 591         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 138         |
|    ep_rew_mean          | 69.4        |
| time/                   |             |
|    fps                  | 1662        |
|    iterations           | 106         |
|    time_elapsed         | 1044        |
|    total_timesteps      | 7336704     |
| train/                  |             |
|    approx_kl            | 0.004888494 |
|    clip_fraction        | 0.0509      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.959      |
|    explained_variance   | 0.849       |
|    learning_rate        | 0.0003      |
|    loss                 | 215         |
|    n_updates            | 1784        |
|    policy_gradient_loss | -0.00142    |
|    value_loss           | 804         |
-----------------------------------------

Eval num_timesteps=7350000, episode_reward=-39.47 +/- 126.25

Episode length: 108.95 +/- 21.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | -39.5        |
| time/                   |              |
|    total_timesteps      | 7350000      |
| train/                  |              |
|    approx_kl            | 0.0047391905 |
|    clip_fraction        | 0.0444       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.973       |
|    explained_variance   | 0.829        |
|    learning_rate        | 0.0003       |
|    loss                 | 568          |
|    n_updates            | 1788         |
|    policy_gradient_loss | -0.000731    |
|    value_loss           | 1.03e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 70.5     |
| time/              |          |
|    fps             | 1660     |
|    iterations      | 107      |
|    time_elapsed    | 1055     |
|    total_timesteps | 7353088  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 79           |
| time/                   |              |
|    fps                  | 1662         |
|    iterations           | 108          |
|    time_elapsed         | 1064         |
|    total_timesteps      | 7369472      |
| train/                  |              |
|    approx_kl            | 0.0041769645 |
|    clip_fraction        | 0.0376       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.928       |
|    explained_variance   | 0.856        |
|    learning_rate        | 0.0003       |
|    loss                 | 75.4         |
|    n_updates            | 1792         |
|    policy_gradient_loss | -0.000178    |
|    value_loss           | 386          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 66           |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 109          |
|    time_elapsed         | 1073         |
|    total_timesteps      | 7385856      |
| train/                  |              |
|    approx_kl            | 0.0040409183 |
|    clip_fraction        | 0.0294       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.961       |
|    explained_variance   | 0.855        |
|    learning_rate        | 0.0003       |
|    loss                 | 94.8         |
|    n_updates            | 1796         |
|    policy_gradient_loss | 0.000676     |
|    value_loss           | 463          |
------------------------------------------

Eval num_timesteps=7400000, episode_reward=23.89 +/- 202.68

Episode length: 118.10 +/- 34.19

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 118         |
|    mean_reward          | 23.9        |
| time/                   |             |
|    total_timesteps      | 7400000     |
| train/                  |             |
|    approx_kl            | 0.004299687 |
|    clip_fraction        | 0.0468      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.938      |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | 114         |
|    n_updates            | 1800        |
|    policy_gradient_loss | -0.000127   |
|    value_loss           | 307         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 74.8     |
| time/              |          |
|    fps             | 1661     |
|    iterations      | 110      |
|    time_elapsed    | 1084     |
|    total_timesteps | 7402240  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 67.1        |
| time/                   |             |
|    fps                  | 1662        |
|    iterations           | 111         |
|    time_elapsed         | 1093        |
|    total_timesteps      | 7418624     |
| train/                  |             |
|    approx_kl            | 0.005389834 |
|    clip_fraction        | 0.05        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.938      |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | 124         |
|    n_updates            | 1804        |
|    policy_gradient_loss | -0.00251    |
|    value_loss           | 441         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 67.7        |
| time/                   |             |
|    fps                  | 1665        |
|    iterations           | 112         |
|    time_elapsed         | 1102        |
|    total_timesteps      | 7435008     |
| train/                  |             |
|    approx_kl            | 0.004045178 |
|    clip_fraction        | 0.0253      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.948      |
|    explained_variance   | 0.838       |
|    learning_rate        | 0.0003      |
|    loss                 | 174         |
|    n_updates            | 1808        |
|    policy_gradient_loss | 0.000601    |
|    value_loss           | 696         |
-----------------------------------------

Eval num_timesteps=7450000, episode_reward=4.35 +/- 107.55

Episode length: 109.30 +/- 25.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | 4.35         |
| time/                   |              |
|    total_timesteps      | 7450000      |
| train/                  |              |
|    approx_kl            | 0.0054726955 |
|    clip_fraction        | 0.0598       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.917       |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 42.9         |
|    n_updates            | 1812         |
|    policy_gradient_loss | -0.000981    |
|    value_loss           | 279          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 74.8     |
| time/              |          |
|    fps             | 1663     |
|    iterations      | 113      |
|    time_elapsed    | 1113     |
|    total_timesteps | 7451392  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 61.6        |
| time/                   |             |
|    fps                  | 1664        |
|    iterations           | 114         |
|    time_elapsed         | 1122        |
|    total_timesteps      | 7467776     |
| train/                  |             |
|    approx_kl            | 0.002469889 |
|    clip_fraction        | 0.0192      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.986      |
|    explained_variance   | 0.827       |
|    learning_rate        | 0.0003      |
|    loss                 | 247         |
|    n_updates            | 1816        |
|    policy_gradient_loss | -0.000332   |
|    value_loss           | 711         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 81.2        |
| time/                   |             |
|    fps                  | 1666        |
|    iterations           | 115         |
|    time_elapsed         | 1130        |
|    total_timesteps      | 7484160     |
| train/                  |             |
|    approx_kl            | 0.004594651 |
|    clip_fraction        | 0.0339      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.985      |
|    explained_variance   | 0.852       |
|    learning_rate        | 0.0003      |
|    loss                 | 234         |
|    n_updates            | 1820        |
|    policy_gradient_loss | -0.000408   |
|    value_loss           | 734         |
-----------------------------------------

Eval num_timesteps=7500000, episode_reward=-31.65 +/- 171.99

Episode length: 103.85 +/- 24.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | -31.7        |
| time/                   |              |
|    total_timesteps      | 7500000      |
| train/                  |              |
|    approx_kl            | 0.0044192495 |
|    clip_fraction        | 0.0331       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.923       |
|    explained_variance   | 0.835        |
|    learning_rate        | 0.0003       |
|    loss                 | 183          |
|    n_updates            | 1824         |
|    policy_gradient_loss | -0.000964    |
|    value_loss           | 627          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 73.1     |
| time/              |          |
|    fps             | 1664     |
|    iterations      | 116      |
|    time_elapsed    | 1141     |
|    total_timesteps | 7500544  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 81           |
| time/                   |              |
|    fps                  | 1665         |
|    iterations           | 117          |
|    time_elapsed         | 1151         |
|    total_timesteps      | 7516928      |
| train/                  |              |
|    approx_kl            | 0.0034181667 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.95        |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 556          |
|    n_updates            | 1828         |
|    policy_gradient_loss | 0.000382     |
|    value_loss           | 1.22e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 78.2         |
| time/                   |              |
|    fps                  | 1665         |
|    iterations           | 118          |
|    time_elapsed         | 1160         |
|    total_timesteps      | 7533312      |
| train/                  |              |
|    approx_kl            | 0.0058219964 |
|    clip_fraction        | 0.0537       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.917       |
|    explained_variance   | 0.831        |
|    learning_rate        | 0.0003       |
|    loss                 | 142          |
|    n_updates            | 1832         |
|    policy_gradient_loss | -0.00161     |
|    value_loss           | 427          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 74.9        |
| time/                   |             |
|    fps                  | 1668        |
|    iterations           | 119         |
|    time_elapsed         | 1168        |
|    total_timesteps      | 7549696     |
| train/                  |             |
|    approx_kl            | 0.003804598 |
|    clip_fraction        | 0.0202      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.913      |
|    explained_variance   | 0.815       |
|    learning_rate        | 0.0003      |
|    loss                 | 215         |
|    n_updates            | 1836        |
|    policy_gradient_loss | -0.000457   |
|    value_loss           | 772         |
-----------------------------------------

Eval num_timesteps=7550000, episode_reward=24.54 +/- 149.61

Episode length: 108.50 +/- 17.93

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | 24.5         |
| time/                   |              |
|    total_timesteps      | 7550000      |
| train/                  |              |
|    approx_kl            | 0.0027942422 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.918       |
|    explained_variance   | 0.858        |
|    learning_rate        | 0.0003       |
|    loss                 | 198          |
|    n_updates            | 1840         |
|    policy_gradient_loss | 0.000345     |
|    value_loss           | 895          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 78.6     |
| time/              |          |
|    fps             | 1665     |
|    iterations      | 120      |
|    time_elapsed    | 1180     |
|    total_timesteps | 7566080  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 64.5         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 121          |
|    time_elapsed         | 1189         |
|    total_timesteps      | 7582464      |
| train/                  |              |
|    approx_kl            | 0.0029791463 |
|    clip_fraction        | 0.0228       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.89        |
|    explained_variance   | 0.859        |
|    learning_rate        | 0.0003       |
|    loss                 | 602          |
|    n_updates            | 1844         |
|    policy_gradient_loss | -0.000226    |
|    value_loss           | 649          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 135         |
|    ep_rew_mean          | 87.8        |
| time/                   |             |
|    fps                  | 1667        |
|    iterations           | 122         |
|    time_elapsed         | 1198        |
|    total_timesteps      | 7598848     |
| train/                  |             |
|    approx_kl            | 0.004056833 |
|    clip_fraction        | 0.0336      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.944      |
|    explained_variance   | 0.928       |
|    learning_rate        | 0.0003      |
|    loss                 | 593         |
|    n_updates            | 1848        |
|    policy_gradient_loss | -0.000167   |
|    value_loss           | 889         |
-----------------------------------------

Eval num_timesteps=7600000, episode_reward=-34.61 +/- 172.39

Episode length: 113.20 +/- 25.18

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 113         |
|    mean_reward          | -34.6       |
| time/                   |             |
|    total_timesteps      | 7600000     |
| train/                  |             |
|    approx_kl            | 0.003968524 |
|    clip_fraction        | 0.0251      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.937      |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 520         |
|    n_updates            | 1852        |
|    policy_gradient_loss | -0.000614   |
|    value_loss           | 1.02e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 69.7     |
| time/              |          |
|    fps             | 1666     |
|    iterations      | 123      |
|    time_elapsed    | 1209     |
|    total_timesteps | 7615232  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 86.4        |
| time/                   |             |
|    fps                  | 1667        |
|    iterations           | 124         |
|    time_elapsed         | 1218        |
|    total_timesteps      | 7631616     |
| train/                  |             |
|    approx_kl            | 0.004396586 |
|    clip_fraction        | 0.0456      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.877      |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | 171         |
|    n_updates            | 1856        |
|    policy_gradient_loss | -0.00141    |
|    value_loss           | 401         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 70.3         |
| time/                   |              |
|    fps                  | 1667         |
|    iterations           | 125          |
|    time_elapsed         | 1228         |
|    total_timesteps      | 7648000      |
| train/                  |              |
|    approx_kl            | 0.0035995417 |
|    clip_fraction        | 0.0224       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.884       |
|    explained_variance   | 0.798        |
|    learning_rate        | 0.0003       |
|    loss                 | 452          |
|    n_updates            | 1860         |
|    policy_gradient_loss | -0.000953    |
|    value_loss           | 849          |
------------------------------------------

Eval num_timesteps=7650000, episode_reward=-119.16 +/- 205.66

Episode length: 115.35 +/- 25.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 115          |
|    mean_reward          | -119         |
| time/                   |              |
|    total_timesteps      | 7650000      |
| train/                  |              |
|    approx_kl            | 0.0042842505 |
|    clip_fraction        | 0.0414       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.913       |
|    explained_variance   | 0.911        |
|    learning_rate        | 0.0003       |
|    loss                 | 661          |
|    n_updates            | 1864         |
|    policy_gradient_loss | -0.00171     |
|    value_loss           | 1.04e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 71.3         |
| time/                   |              |
|    fps                  | 1667         |
|    iterations           | 127          |
|    time_elapsed         | 1247         |
|    total_timesteps      | 7680768      |
| train/                  |              |
|    approx_kl            | 0.0024495807 |
|    clip_fraction        | 0.0171       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.885       |
|    explained_variance   | 0.941        |
|    learning_rate        | 0.0003       |
|    loss                 | 302          |
|    n_updates            | 1868         |
|    policy_gradient_loss | -6.3e-05     |
|    value_loss           | 779          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 88.8         |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 128          |
|    time_elapsed         | 1257         |
|    total_timesteps      | 7697152      |
| train/                  |              |
|    approx_kl            | 0.0036882185 |
|    clip_fraction        | 0.0293       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.914       |
|    explained_variance   | 0.827        |
|    learning_rate        | 0.0003       |
|    loss                 | 338          |
|    n_updates            | 1872         |
|    policy_gradient_loss | -0.000562    |
|    value_loss           | 863          |
------------------------------------------

Eval num_timesteps=7700000, episode_reward=-66.15 +/- 166.44

Episode length: 104.90 +/- 25.11

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 105         |
|    mean_reward          | -66.2       |
| time/                   |             |
|    total_timesteps      | 7700000     |
| train/                  |             |
|    approx_kl            | 0.003146925 |
|    clip_fraction        | 0.0161      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.888      |
|    explained_variance   | 0.792       |
|    learning_rate        | 0.0003      |
|    loss                 | 346         |
|    n_updates            | 1876        |
|    policy_gradient_loss | 6.77e-06    |
|    value_loss           | 1.04e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 77.5     |
| time/              |          |
|    fps             | 1666     |
|    iterations      | 129      |
|    time_elapsed    | 1268     |
|    total_timesteps | 7713536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 71.3         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 130          |
|    time_elapsed         | 1276         |
|    total_timesteps      | 7729920      |
| train/                  |              |
|    approx_kl            | 0.0020165246 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.902       |
|    explained_variance   | 0.814        |
|    learning_rate        | 0.0003       |
|    loss                 | 363          |
|    n_updates            | 1880         |
|    policy_gradient_loss | -7.69e-05    |
|    value_loss           | 849          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 75           |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 131          |
|    time_elapsed         | 1285         |
|    total_timesteps      | 7746304      |
| train/                  |              |
|    approx_kl            | 0.0036541226 |
|    clip_fraction        | 0.0257       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.902       |
|    explained_variance   | 0.812        |
|    learning_rate        | 0.0003       |
|    loss                 | 130          |
|    n_updates            | 1884         |
|    policy_gradient_loss | -0.000749    |
|    value_loss           | 566          |
------------------------------------------

Eval num_timesteps=7750000, episode_reward=-5.29 +/- 138.71

Episode length: 106.60 +/- 22.48

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -5.29        |
| time/                   |              |
|    total_timesteps      | 7750000      |
| train/                  |              |
|    approx_kl            | 0.0048238602 |
|    clip_fraction        | 0.039        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.855        |
|    learning_rate        | 0.0003       |
|    loss                 | 264          |
|    n_updates            | 1888         |
|    policy_gradient_loss | -0.00196     |
|    value_loss           | 493          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 62.9     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 132      |
|    time_elapsed    | 1296     |
|    total_timesteps | 7762688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 75.9        |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 133         |
|    time_elapsed         | 1304        |
|    total_timesteps      | 7779072     |
| train/                  |             |
|    approx_kl            | 0.004002272 |
|    clip_fraction        | 0.0395      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.884      |
|    explained_variance   | 0.885       |
|    learning_rate        | 0.0003      |
|    loss                 | 329         |
|    n_updates            | 1892        |
|    policy_gradient_loss | -0.00126    |
|    value_loss           | 376         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 89           |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 134          |
|    time_elapsed         | 1313         |
|    total_timesteps      | 7795456      |
| train/                  |              |
|    approx_kl            | 0.0044741556 |
|    clip_fraction        | 0.0322       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.897       |
|    explained_variance   | 0.864        |
|    learning_rate        | 0.0003       |
|    loss                 | 151          |
|    n_updates            | 1896         |
|    policy_gradient_loss | -0.000585    |
|    value_loss           | 401          |
------------------------------------------

Eval num_timesteps=7800000, episode_reward=56.37 +/- 132.57

Episode length: 97.75 +/- 18.58

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.8        |
|    mean_reward          | 56.4        |
| time/                   |             |
|    total_timesteps      | 7800000     |
| train/                  |             |
|    approx_kl            | 0.004157107 |
|    clip_fraction        | 0.0408      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.931      |
|    explained_variance   | 0.811       |
|    learning_rate        | 0.0003      |
|    loss                 | 433         |
|    n_updates            | 1900        |
|    policy_gradient_loss | -0.00115    |
|    value_loss           | 868         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 80.7     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 135      |
|    time_elapsed    | 1324     |
|    total_timesteps | 7811840  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 114         |
|    ep_rew_mean          | 81.8        |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 136         |
|    time_elapsed         | 1334        |
|    total_timesteps      | 7828224     |
| train/                  |             |
|    approx_kl            | 0.004807306 |
|    clip_fraction        | 0.034       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.881      |
|    explained_variance   | 0.823       |
|    learning_rate        | 0.0003      |
|    loss                 | 426         |
|    n_updates            | 1904        |
|    policy_gradient_loss | -0.000766   |
|    value_loss           | 568         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 66          |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 137         |
|    time_elapsed         | 1342        |
|    total_timesteps      | 7844608     |
| train/                  |             |
|    approx_kl            | 0.005087178 |
|    clip_fraction        | 0.0366      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.882      |
|    explained_variance   | 0.819       |
|    learning_rate        | 0.0003      |
|    loss                 | 446         |
|    n_updates            | 1908        |
|    policy_gradient_loss | -0.00181    |
|    value_loss           | 689         |
-----------------------------------------

Eval num_timesteps=7850000, episode_reward=-29.65 +/- 122.11

Episode length: 97.10 +/- 15.83

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97.1         |
|    mean_reward          | -29.7        |
| time/                   |              |
|    total_timesteps      | 7850000      |
| train/                  |              |
|    approx_kl            | 0.0028629126 |
|    clip_fraction        | 0.0273       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.918       |
|    explained_variance   | 0.803        |
|    learning_rate        | 0.0003       |
|    loss                 | 552          |
|    n_updates            | 1912         |
|    policy_gradient_loss | 8.53e-05     |
|    value_loss           | 1.23e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 74       |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 138      |
|    time_elapsed    | 1353     |
|    total_timesteps | 7860992  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 63.1        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 139         |
|    time_elapsed         | 1362        |
|    total_timesteps      | 7877376     |
| train/                  |             |
|    approx_kl            | 0.004716918 |
|    clip_fraction        | 0.0381      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.952      |
|    explained_variance   | 0.812       |
|    learning_rate        | 0.0003      |
|    loss                 | 439         |
|    n_updates            | 1916        |
|    policy_gradient_loss | -0.000442   |
|    value_loss           | 1.22e+03    |
-----------------------------------------

Eval num_timesteps=7900000, episode_reward=74.47 +/- 130.06

Episode length: 99.75 +/- 18.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99.8         |
|    mean_reward          | 74.5         |
| time/                   |              |
|    total_timesteps      | 7900000      |
| train/                  |              |
|    approx_kl            | 0.0046185576 |
|    clip_fraction        | 0.0345       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.924       |
|    explained_variance   | 0.949        |
|    learning_rate        | 0.0003       |
|    loss                 | 714          |
|    n_updates            | 1924         |
|    policy_gradient_loss | -0.000851    |
|    value_loss           | 382          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_7900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 69.1     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 141      |
|    time_elapsed    | 1381     |
|    total_timesteps | 7910144  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 75.5         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 142          |
|    time_elapsed         | 1390         |
|    total_timesteps      | 7926528      |
| train/                  |              |
|    approx_kl            | 0.0043034023 |
|    clip_fraction        | 0.039        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.865       |
|    explained_variance   | 0.908        |
|    learning_rate        | 0.0003       |
|    loss                 | 212          |
|    n_updates            | 1928         |
|    policy_gradient_loss | -0.000814    |
|    value_loss           | 470          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 81.8        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 143         |
|    time_elapsed         | 1400        |
|    total_timesteps      | 7942912     |
| train/                  |             |
|    approx_kl            | 0.003029063 |
|    clip_fraction        | 0.0176      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.878      |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | 373         |
|    n_updates            | 1932        |
|    policy_gradient_loss | -0.00106    |
|    value_loss           | 860         |
-----------------------------------------

Eval num_timesteps=7950000, episode_reward=1.96 +/- 157.94

Episode length: 102.75 +/- 20.69

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | 1.96         |
| time/                   |              |
|    total_timesteps      | 7950000      |
| train/                  |              |
|    approx_kl            | 0.0045328243 |
|    clip_fraction        | 0.0211       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.931       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.09e+03     |
|    n_updates            | 1936         |
|    policy_gradient_loss | -0.000492    |
|    value_loss           | 1.42e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 74.4     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 144      |
|    time_elapsed    | 1410     |
|    total_timesteps | 7959296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 76.2         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 145          |
|    time_elapsed         | 1419         |
|    total_timesteps      | 7975680      |
| train/                  |              |
|    approx_kl            | 0.0040726485 |
|    clip_fraction        | 0.0272       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.887       |
|    explained_variance   | 0.909        |
|    learning_rate        | 0.0003       |
|    loss                 | 192          |
|    n_updates            | 1940         |
|    policy_gradient_loss | -0.000609    |
|    value_loss           | 779          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 77.2        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 146         |
|    time_elapsed         | 1429        |
|    total_timesteps      | 7992064     |
| train/                  |             |
|    approx_kl            | 0.002615618 |
|    clip_fraction        | 0.0174      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.907      |
|    explained_variance   | 0.823       |
|    learning_rate        | 0.0003      |
|    loss                 | 470         |
|    n_updates            | 1944        |
|    policy_gradient_loss | 0.00135     |
|    value_loss           | 790         |
-----------------------------------------

Eval num_timesteps=8000000, episode_reward=-49.05 +/- 174.92

Episode length: 104.10 +/- 27.54

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | -49          |
| time/                   |              |
|    total_timesteps      | 8000000      |
| train/                  |              |
|    approx_kl            | 0.0031799595 |
|    clip_fraction        | 0.0184       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.894       |
|    explained_variance   | 0.943        |
|    learning_rate        | 0.0003       |
|    loss                 | 442          |
|    n_updates            | 1948         |
|    policy_gradient_loss | 0.000629     |
|    value_loss           | 792          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 8,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 86.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 147      |
|    time_elapsed    | 1443     |
|    total_timesteps | 8008448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 83.7         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 148          |
|    time_elapsed         | 1452         |
|    total_timesteps      | 8024832      |
| train/                  |              |
|    approx_kl            | 0.0058729947 |
|    clip_fraction        | 0.0408       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.909       |
|    explained_variance   | 0.815        |
|    learning_rate        | 0.0003       |
|    loss                 | 407          |
|    n_updates            | 1952         |
|    policy_gradient_loss | -0.000851    |
|    value_loss           | 794          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 78.5         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 149          |
|    time_elapsed         | 1461         |
|    total_timesteps      | 8041216      |
| train/                  |              |
|    approx_kl            | 0.0033917502 |
|    clip_fraction        | 0.0156       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 473          |
|    n_updates            | 1956         |
|    policy_gradient_loss | 0.00063      |
|    value_loss           | 649          |
------------------------------------------

Eval num_timesteps=8050000, episode_reward=-111.71 +/- 260.31

Episode length: 101.30 +/- 27.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 101          |
|    mean_reward          | -112         |
| time/                   |              |
|    total_timesteps      | 8050000      |
| train/                  |              |
|    approx_kl            | 0.0050402335 |
|    clip_fraction        | 0.0307       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.814        |
|    learning_rate        | 0.0003       |
|    loss                 | 649          |
|    n_updates            | 1960         |
|    policy_gradient_loss | -0.000325    |
|    value_loss           | 831          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 72       |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 150      |
|    time_elapsed    | 1472     |
|    total_timesteps | 8057600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 115          |
|    ep_rew_mean          | 67           |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 151          |
|    time_elapsed         | 1481         |
|    total_timesteps      | 8073984      |
| train/                  |              |
|    approx_kl            | 0.0031130968 |
|    clip_fraction        | 0.0283       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.887       |
|    explained_variance   | 0.851        |
|    learning_rate        | 0.0003       |
|    loss                 | 341          |
|    n_updates            | 1964         |
|    policy_gradient_loss | -0.000259    |
|    value_loss           | 629          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 91.6         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 152          |
|    time_elapsed         | 1490         |
|    total_timesteps      | 8090368      |
| train/                  |              |
|    approx_kl            | 0.0051876316 |
|    clip_fraction        | 0.059        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.904       |
|    explained_variance   | 0.884        |
|    learning_rate        | 0.0003       |
|    loss                 | 70.9         |
|    n_updates            | 1968         |
|    policy_gradient_loss | -0.000943    |
|    value_loss           | 363          |
------------------------------------------

Eval num_timesteps=8100000, episode_reward=-60.17 +/- 267.40

Episode length: 104.40 +/- 28.37

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | -60.2        |
| time/                   |              |
|    total_timesteps      | 8100000      |
| train/                  |              |
|    approx_kl            | 0.0032780217 |
|    clip_fraction        | 0.027        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.879       |
|    explained_variance   | 0.796        |
|    learning_rate        | 0.0003       |
|    loss                 | 547          |
|    n_updates            | 1972         |
|    policy_gradient_loss | -0.000453    |
|    value_loss           | 801          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 86.3     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 153      |
|    time_elapsed    | 1501     |
|    total_timesteps | 8106752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 79.1         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 154          |
|    time_elapsed         | 1510         |
|    total_timesteps      | 8123136      |
| train/                  |              |
|    approx_kl            | 0.0030380317 |
|    clip_fraction        | 0.0122       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.891       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 436          |
|    n_updates            | 1976         |
|    policy_gradient_loss | 0.00037      |
|    value_loss           | 838          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 118         |
|    ep_rew_mean          | 75.2        |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 155         |
|    time_elapsed         | 1520        |
|    total_timesteps      | 8139520     |
| train/                  |             |
|    approx_kl            | 0.004392175 |
|    clip_fraction        | 0.037       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.913      |
|    explained_variance   | 0.943       |
|    learning_rate        | 0.0003      |
|    loss                 | 430         |
|    n_updates            | 1980        |
|    policy_gradient_loss | -0.00114    |
|    value_loss           | 1.12e+03    |
-----------------------------------------

Eval num_timesteps=8150000, episode_reward=-111.43 +/- 209.56

Episode length: 112.65 +/- 29.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | -111         |
| time/                   |              |
|    total_timesteps      | 8150000      |
| train/                  |              |
|    approx_kl            | 0.0039560497 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.884       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 773          |
|    n_updates            | 1984         |
|    policy_gradient_loss | 0.000125     |
|    value_loss           | 866          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 79.6     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 156      |
|    time_elapsed    | 1531     |
|    total_timesteps | 8155904  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 118        |
|    ep_rew_mean          | 62.2       |
| time/                   |            |
|    fps                  | 1669       |
|    iterations           | 157        |
|    time_elapsed         | 1540       |
|    total_timesteps      | 8172288    |
| train/                  |            |
|    approx_kl            | 0.00428169 |
|    clip_fraction        | 0.0309     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.919     |
|    explained_variance   | 0.956      |
|    learning_rate        | 0.0003     |
|    loss                 | 923        |
|    n_updates            | 1988       |
|    policy_gradient_loss | -0.000952  |
|    value_loss           | 1.26e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 130         |
|    ep_rew_mean          | 76.7        |
| time/                   |             |
|    fps                  | 1669        |
|    iterations           | 158         |
|    time_elapsed         | 1550        |
|    total_timesteps      | 8188672     |
| train/                  |             |
|    approx_kl            | 0.004654569 |
|    clip_fraction        | 0.0363      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.906      |
|    explained_variance   | 0.895       |
|    learning_rate        | 0.0003      |
|    loss                 | 302         |
|    n_updates            | 1992        |
|    policy_gradient_loss | -0.000929   |
|    value_loss           | 661         |
-----------------------------------------

Eval num_timesteps=8200000, episode_reward=-13.28 +/- 184.19

Episode length: 106.45 +/- 34.68

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | -13.3       |
| time/                   |             |
|    total_timesteps      | 8200000     |
| train/                  |             |
|    approx_kl            | 0.004116852 |
|    clip_fraction        | 0.0239      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.86       |
|    explained_variance   | 0.969       |
|    learning_rate        | 0.0003      |
|    loss                 | 241         |
|    n_updates            | 1996        |
|    policy_gradient_loss | -0.000594   |
|    value_loss           | 964         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 75       |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 159      |
|    time_elapsed    | 1561     |
|    total_timesteps | 8205056  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 102          |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 160          |
|    time_elapsed         | 1570         |
|    total_timesteps      | 8221440      |
| train/                  |              |
|    approx_kl            | 0.0036916037 |
|    clip_fraction        | 0.03         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.868       |
|    explained_variance   | 0.934        |
|    learning_rate        | 0.0003       |
|    loss                 | 328          |
|    n_updates            | 2000         |
|    policy_gradient_loss | -0.000727    |
|    value_loss           | 788          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 62.7         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 161          |
|    time_elapsed         | 1579         |
|    total_timesteps      | 8237824      |
| train/                  |              |
|    approx_kl            | 0.0029732576 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.797        |
|    learning_rate        | 0.0003       |
|    loss                 | 573          |
|    n_updates            | 2004         |
|    policy_gradient_loss | -0.000788    |
|    value_loss           | 1.1e+03      |
------------------------------------------

Eval num_timesteps=8250000, episode_reward=-132.12 +/- 351.52

Episode length: 113.20 +/- 34.09

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 113         |
|    mean_reward          | -132        |
| time/                   |             |
|    total_timesteps      | 8250000     |
| train/                  |             |
|    approx_kl            | 0.003937903 |
|    clip_fraction        | 0.027       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.847      |
|    explained_variance   | 0.927       |
|    learning_rate        | 0.0003      |
|    loss                 | 434         |
|    n_updates            | 2008        |
|    policy_gradient_loss | -7.84e-05   |
|    value_loss           | 785         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 135      |
|    ep_rew_mean     | 79.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 162      |
|    time_elapsed    | 1590     |
|    total_timesteps | 8254208  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 75.4        |
| time/                   |             |
|    fps                  | 1668        |
|    iterations           | 163         |
|    time_elapsed         | 1600        |
|    total_timesteps      | 8270592     |
| train/                  |             |
|    approx_kl            | 0.004478787 |
|    clip_fraction        | 0.0302      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.893      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 465         |
|    n_updates            | 2012        |
|    policy_gradient_loss | -0.000414   |
|    value_loss           | 1.09e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 81.2         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 164          |
|    time_elapsed         | 1608         |
|    total_timesteps      | 8286976      |
| train/                  |              |
|    approx_kl            | 0.0045477473 |
|    clip_fraction        | 0.0453       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.908       |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 365          |
|    n_updates            | 2016         |
|    policy_gradient_loss | -0.00134     |
|    value_loss           | 679          |
------------------------------------------

Eval num_timesteps=8300000, episode_reward=15.78 +/- 130.11

Episode length: 108.15 +/- 32.29

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | 15.8         |
| time/                   |              |
|    total_timesteps      | 8300000      |
| train/                  |              |
|    approx_kl            | 0.0033225846 |
|    clip_fraction        | 0.0322       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.981        |
|    learning_rate        | 0.0003       |
|    loss                 | 102          |
|    n_updates            | 2020         |
|    policy_gradient_loss | 0.000145     |
|    value_loss           | 754          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 71.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 165      |
|    time_elapsed    | 1620     |
|    total_timesteps | 8303360  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 92.4         |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 166          |
|    time_elapsed         | 1629         |
|    total_timesteps      | 8319744      |
| train/                  |              |
|    approx_kl            | 0.0032241489 |
|    clip_fraction        | 0.0229       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.897       |
|    explained_variance   | 0.84         |
|    learning_rate        | 0.0003       |
|    loss                 | 280          |
|    n_updates            | 2024         |
|    policy_gradient_loss | 0.000366     |
|    value_loss           | 558          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 79.2        |
| time/                   |             |
|    fps                  | 1669        |
|    iterations           | 167         |
|    time_elapsed         | 1638        |
|    total_timesteps      | 8336128     |
| train/                  |             |
|    approx_kl            | 0.002306961 |
|    clip_fraction        | 0.0249      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.906      |
|    explained_variance   | 0.776       |
|    learning_rate        | 0.0003      |
|    loss                 | 390         |
|    n_updates            | 2028        |
|    policy_gradient_loss | 1.47e-05    |
|    value_loss           | 607         |
-----------------------------------------

Eval num_timesteps=8350000, episode_reward=61.39 +/- 87.21

Episode length: 110.65 +/- 22.34

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 111        |
|    mean_reward          | 61.4       |
| time/                   |            |
|    total_timesteps      | 8350000    |
| train/                  |            |
|    approx_kl            | 0.00434399 |
|    clip_fraction        | 0.0345     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.901     |
|    explained_variance   | 0.846      |
|    learning_rate        | 0.0003     |
|    loss                 | 152        |
|    n_updates            | 2032       |
|    policy_gradient_loss | -0.000503  |
|    value_loss           | 459        |
----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 85.7     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 168      |
|    time_elapsed    | 1649     |
|    total_timesteps | 8352512  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 81.1        |
| time/                   |             |
|    fps                  | 1669        |
|    iterations           | 169         |
|    time_elapsed         | 1658        |
|    total_timesteps      | 8368896     |
| train/                  |             |
|    approx_kl            | 0.003687088 |
|    clip_fraction        | 0.0257      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.893      |
|    explained_variance   | 0.832       |
|    learning_rate        | 0.0003      |
|    loss                 | 232         |
|    n_updates            | 2036        |
|    policy_gradient_loss | 2.17e-05    |
|    value_loss           | 540         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 82.1         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 170          |
|    time_elapsed         | 1668         |
|    total_timesteps      | 8385280      |
| train/                  |              |
|    approx_kl            | 0.0040699868 |
|    clip_fraction        | 0.0232       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.89        |
|    explained_variance   | 0.762        |
|    learning_rate        | 0.0003       |
|    loss                 | 511          |
|    n_updates            | 2040         |
|    policy_gradient_loss | -0.000181    |
|    value_loss           | 946          |
------------------------------------------

Eval num_timesteps=8400000, episode_reward=77.26 +/- 46.84

Episode length: 102.20 +/- 19.37

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 102          |
|    mean_reward          | 77.3         |
| time/                   |              |
|    total_timesteps      | 8400000      |
| train/                  |              |
|    approx_kl            | 0.0021205794 |
|    clip_fraction        | 0.014        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.887       |
|    explained_variance   | 0.8          |
|    learning_rate        | 0.0003       |
|    loss                 | 321          |
|    n_updates            | 2044         |
|    policy_gradient_loss | 0.000356     |
|    value_loss           | 858          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 82.2     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 171      |
|    time_elapsed    | 1679     |
|    total_timesteps | 8401664  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 71.6         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 172          |
|    time_elapsed         | 1687         |
|    total_timesteps      | 8418048      |
| train/                  |              |
|    approx_kl            | 0.0052982043 |
|    clip_fraction        | 0.0345       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.833        |
|    learning_rate        | 0.0003       |
|    loss                 | 267          |
|    n_updates            | 2048         |
|    policy_gradient_loss | -0.000833    |
|    value_loss           | 811          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 82.9         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 173          |
|    time_elapsed         | 1697         |
|    total_timesteps      | 8434432      |
| train/                  |              |
|    approx_kl            | 0.0031871484 |
|    clip_fraction        | 0.0255       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.918       |
|    explained_variance   | 0.846        |
|    learning_rate        | 0.0003       |
|    loss                 | 333          |
|    n_updates            | 2052         |
|    policy_gradient_loss | -0.000351    |
|    value_loss           | 861          |
------------------------------------------

Eval num_timesteps=8450000, episode_reward=59.36 +/- 34.04

Episode length: 115.90 +/- 24.43

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 59.4         |
| time/                   |              |
|    total_timesteps      | 8450000      |
| train/                  |              |
|    approx_kl            | 0.0042544096 |
|    clip_fraction        | 0.0341       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.92        |
|    explained_variance   | 0.813        |
|    learning_rate        | 0.0003       |
|    loss                 | 160          |
|    n_updates            | 2056         |
|    policy_gradient_loss | -0.0011      |
|    value_loss           | 596          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 71.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 174      |
|    time_elapsed    | 1708     |
|    total_timesteps | 8450816  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 86          |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 176         |
|    time_elapsed         | 1726        |
|    total_timesteps      | 8483584     |
| train/                  |             |
|    approx_kl            | 0.004373907 |
|    clip_fraction        | 0.0329      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.941      |
|    explained_variance   | 0.832       |
|    learning_rate        | 0.0003      |
|    loss                 | 313         |
|    n_updates            | 2064        |
|    policy_gradient_loss | -0.000556   |
|    value_loss           | 733         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 86.8         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 177          |
|    time_elapsed         | 1735         |
|    total_timesteps      | 8499968      |
| train/                  |              |
|    approx_kl            | 0.0039370693 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.908       |
|    explained_variance   | 0.827        |
|    learning_rate        | 0.0003       |
|    loss                 | 326          |
|    n_updates            | 2068         |
|    policy_gradient_loss | -3.07e-06    |
|    value_loss           | 697          |
------------------------------------------

Eval num_timesteps=8500000, episode_reward=80.50 +/- 108.74

Episode length: 110.15 +/- 25.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | 80.5         |
| time/                   |              |
|    total_timesteps      | 8500000      |
| train/                  |              |
|    approx_kl            | 0.0046773027 |
|    clip_fraction        | 0.0406       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.839        |
|    learning_rate        | 0.0003       |
|    loss                 | 463          |
|    n_updates            | 2072         |
|    policy_gradient_loss | -0.00247     |
|    value_loss           | 665          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 78.5     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 178      |
|    time_elapsed    | 1746     |
|    total_timesteps | 8516352  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 83.7        |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 179         |
|    time_elapsed         | 1755        |
|    total_timesteps      | 8532736     |
| train/                  |             |
|    approx_kl            | 0.004012315 |
|    clip_fraction        | 0.0266      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.923      |
|    explained_variance   | 0.78        |
|    learning_rate        | 0.0003      |
|    loss                 | 673         |
|    n_updates            | 2076        |
|    policy_gradient_loss | 0.000205    |
|    value_loss           | 1.02e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 121         |
|    ep_rew_mean          | 91.1        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 180         |
|    time_elapsed         | 1764        |
|    total_timesteps      | 8549120     |
| train/                  |             |
|    approx_kl            | 0.004808766 |
|    clip_fraction        | 0.0371      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.871      |
|    explained_variance   | 0.859       |
|    learning_rate        | 0.0003      |
|    loss                 | 151         |
|    n_updates            | 2080        |
|    policy_gradient_loss | -0.000594   |
|    value_loss           | 445         |
-----------------------------------------

Eval num_timesteps=8550000, episode_reward=-55.21 +/- 167.83

Episode length: 120.05 +/- 25.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | -55.2        |
| time/                   |              |
|    total_timesteps      | 8550000      |
| train/                  |              |
|    approx_kl            | 0.0038278345 |
|    clip_fraction        | 0.0261       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.791        |
|    learning_rate        | 0.0003       |
|    loss                 | 301          |
|    n_updates            | 2084         |
|    policy_gradient_loss | -0.0023      |
|    value_loss           | 842          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 122      |
|    ep_rew_mean     | 78.9     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 181      |
|    time_elapsed    | 1775     |
|    total_timesteps | 8565504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 88.2         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 182          |
|    time_elapsed         | 1784         |
|    total_timesteps      | 8581888      |
| train/                  |              |
|    approx_kl            | 0.0025632044 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.849        |
|    learning_rate        | 0.0003       |
|    loss                 | 194          |
|    n_updates            | 2088         |
|    policy_gradient_loss | -0.000404    |
|    value_loss           | 703          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 83.5         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 183          |
|    time_elapsed         | 1793         |
|    total_timesteps      | 8598272      |
| train/                  |              |
|    approx_kl            | 0.0042185327 |
|    clip_fraction        | 0.0211       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.866       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 654          |
|    n_updates            | 2092         |
|    policy_gradient_loss | 3.88e-05     |
|    value_loss           | 886          |
------------------------------------------

Eval num_timesteps=8600000, episode_reward=73.21 +/- 103.13

Episode length: 104.80 +/- 19.01

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 105          |
|    mean_reward          | 73.2         |
| time/                   |              |
|    total_timesteps      | 8600000      |
| train/                  |              |
|    approx_kl            | 0.0034614848 |
|    clip_fraction        | 0.0245       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.864       |
|    explained_variance   | 0.809        |
|    learning_rate        | 0.0003       |
|    loss                 | 319          |
|    n_updates            | 2096         |
|    policy_gradient_loss | -0.00096     |
|    value_loss           | 1.06e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 79.9     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 184      |
|    time_elapsed    | 1804     |
|    total_timesteps | 8614656  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 75.1         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 185          |
|    time_elapsed         | 1814         |
|    total_timesteps      | 8631040      |
| train/                  |              |
|    approx_kl            | 0.0046345494 |
|    clip_fraction        | 0.0401       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.913       |
|    explained_variance   | 0.805        |
|    learning_rate        | 0.0003       |
|    loss                 | 740          |
|    n_updates            | 2100         |
|    policy_gradient_loss | 5.22e-05     |
|    value_loss           | 1.04e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 114         |
|    ep_rew_mean          | 76.4        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 186         |
|    time_elapsed         | 1822        |
|    total_timesteps      | 8647424     |
| train/                  |             |
|    approx_kl            | 0.004973054 |
|    clip_fraction        | 0.0395      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.913      |
|    explained_variance   | 0.804       |
|    learning_rate        | 0.0003      |
|    loss                 | 230         |
|    n_updates            | 2104        |
|    policy_gradient_loss | -6.9e-05    |
|    value_loss           | 916         |
-----------------------------------------

Eval num_timesteps=8650000, episode_reward=49.23 +/- 96.45

Episode length: 97.70 +/- 24.21

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.7        |
|    mean_reward          | 49.2        |
| time/                   |             |
|    total_timesteps      | 8650000     |
| train/                  |             |
|    approx_kl            | 0.003431519 |
|    clip_fraction        | 0.0348      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.894      |
|    explained_variance   | 0.822       |
|    learning_rate        | 0.0003      |
|    loss                 | 210         |
|    n_updates            | 2108        |
|    policy_gradient_loss | -0.000638   |
|    value_loss           | 492         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 85.9     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 187      |
|    time_elapsed    | 1833     |
|    total_timesteps | 8663808  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 117         |
|    ep_rew_mean          | 72.4        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 188         |
|    time_elapsed         | 1843        |
|    total_timesteps      | 8680192     |
| train/                  |             |
|    approx_kl            | 0.004910697 |
|    clip_fraction        | 0.0471      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.83       |
|    explained_variance   | 0.808       |
|    learning_rate        | 0.0003      |
|    loss                 | 293         |
|    n_updates            | 2112        |
|    policy_gradient_loss | -0.00227    |
|    value_loss           | 587         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 82.5        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 189         |
|    time_elapsed         | 1852        |
|    total_timesteps      | 8696576     |
| train/                  |             |
|    approx_kl            | 0.003718582 |
|    clip_fraction        | 0.0303      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.852      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 150         |
|    n_updates            | 2116        |
|    policy_gradient_loss | -0.000757   |
|    value_loss           | 698         |
-----------------------------------------

Eval num_timesteps=8700000, episode_reward=35.44 +/- 83.35

Episode length: 100.45 +/- 22.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 100          |
|    mean_reward          | 35.4         |
| time/                   |              |
|    total_timesteps      | 8700000      |
| train/                  |              |
|    approx_kl            | 0.0026228935 |
|    clip_fraction        | 0.0221       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.921        |
|    learning_rate        | 0.0003       |
|    loss                 | 233          |
|    n_updates            | 2120         |
|    policy_gradient_loss | -0.000325    |
|    value_loss           | 900          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 70.5     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 190      |
|    time_elapsed    | 1862     |
|    total_timesteps | 8712960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 89.3         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 191          |
|    time_elapsed         | 1871         |
|    total_timesteps      | 8729344      |
| train/                  |              |
|    approx_kl            | 0.0024661783 |
|    clip_fraction        | 0.0258       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.874       |
|    explained_variance   | 0.918        |
|    learning_rate        | 0.0003       |
|    loss                 | 469          |
|    n_updates            | 2124         |
|    policy_gradient_loss | -0.000479    |
|    value_loss           | 882          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 84.1         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 192          |
|    time_elapsed         | 1881         |
|    total_timesteps      | 8745728      |
| train/                  |              |
|    approx_kl            | 0.0031325617 |
|    clip_fraction        | 0.0295       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.839       |
|    explained_variance   | 0.805        |
|    learning_rate        | 0.0003       |
|    loss                 | 187          |
|    n_updates            | 2128         |
|    policy_gradient_loss | -0.00102     |
|    value_loss           | 539          |
------------------------------------------

Eval num_timesteps=8750000, episode_reward=87.67 +/- 130.62

Episode length: 108.75 +/- 19.28

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 109         |
|    mean_reward          | 87.7        |
| time/                   |             |
|    total_timesteps      | 8750000     |
| train/                  |             |
|    approx_kl            | 0.004460565 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.851      |
|    explained_variance   | 0.827       |
|    learning_rate        | 0.0003      |
|    loss                 | 336         |
|    n_updates            | 2132        |
|    policy_gradient_loss | -0.00102    |
|    value_loss           | 689         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 85.6         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 194          |
|    time_elapsed         | 1900         |
|    total_timesteps      | 8778496      |
| train/                  |              |
|    approx_kl            | 0.0032480392 |
|    clip_fraction        | 0.0311       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.865        |
|    learning_rate        | 0.0003       |
|    loss                 | 237          |
|    n_updates            | 2136         |
|    policy_gradient_loss | -0.00126     |
|    value_loss           | 558          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 94.3         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 195          |
|    time_elapsed         | 1910         |
|    total_timesteps      | 8794880      |
| train/                  |              |
|    approx_kl            | 0.0028933953 |
|    clip_fraction        | 0.0135       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.818       |
|    explained_variance   | 0.737        |
|    learning_rate        | 0.0003       |
|    loss                 | 468          |
|    n_updates            | 2140         |
|    policy_gradient_loss | 3.07e-05     |
|    value_loss           | 1.03e+03     |
------------------------------------------

Eval num_timesteps=8800000, episode_reward=29.30 +/- 105.65

Episode length: 101.05 +/- 20.12

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 101          |
|    mean_reward          | 29.3         |
| time/                   |              |
|    total_timesteps      | 8800000      |
| train/                  |              |
|    approx_kl            | 0.0033326652 |
|    clip_fraction        | 0.0206       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.862       |
|    explained_variance   | 0.94         |
|    learning_rate        | 0.0003       |
|    loss                 | 375          |
|    n_updates            | 2144         |
|    policy_gradient_loss | -0.000276    |
|    value_loss           | 978          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 84.5     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 196      |
|    time_elapsed    | 1921     |
|    total_timesteps | 8811264  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 112         |
|    ep_rew_mean          | 82.1        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 197         |
|    time_elapsed         | 1929        |
|    total_timesteps      | 8827648     |
| train/                  |             |
|    approx_kl            | 0.002011718 |
|    clip_fraction        | 0.0126      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.838      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 257         |
|    n_updates            | 2148        |
|    policy_gradient_loss | 9.84e-05    |
|    value_loss           | 1.02e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 86.6         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 198          |
|    time_elapsed         | 1939         |
|    total_timesteps      | 8844032      |
| train/                  |              |
|    approx_kl            | 0.0033051912 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.83        |
|    explained_variance   | 0.901        |
|    learning_rate        | 0.0003       |
|    loss                 | 548          |
|    n_updates            | 2152         |
|    policy_gradient_loss | -0.00064     |
|    value_loss           | 985          |
------------------------------------------

Eval num_timesteps=8850000, episode_reward=-70.23 +/- 152.76

Episode length: 107.70 +/- 28.74

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | -70.2        |
| time/                   |              |
|    total_timesteps      | 8850000      |
| train/                  |              |
|    approx_kl            | 0.0028962314 |
|    clip_fraction        | 0.014        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.824       |
|    explained_variance   | 0.944        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.33e+03     |
|    n_updates            | 2156         |
|    policy_gradient_loss | -2.6e-05     |
|    value_loss           | 1.18e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 87.9     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 199      |
|    time_elapsed    | 1950     |
|    total_timesteps | 8860416  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 112         |
|    ep_rew_mean          | 86.9        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 200         |
|    time_elapsed         | 1960        |
|    total_timesteps      | 8876800     |
| train/                  |             |
|    approx_kl            | 0.002514245 |
|    clip_fraction        | 0.0166      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.837      |
|    explained_variance   | 0.81        |
|    learning_rate        | 0.0003      |
|    loss                 | 267         |
|    n_updates            | 2160        |
|    policy_gradient_loss | 0.000459    |
|    value_loss           | 760         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 101          |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 201          |
|    time_elapsed         | 1968         |
|    total_timesteps      | 8893184      |
| train/                  |              |
|    approx_kl            | 0.0028262315 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.828       |
|    explained_variance   | 0.78         |
|    learning_rate        | 0.0003       |
|    loss                 | 463          |
|    n_updates            | 2164         |
|    policy_gradient_loss | 0.000426     |
|    value_loss           | 1.24e+03     |
------------------------------------------

Eval num_timesteps=8900000, episode_reward=18.88 +/- 256.03

Episode length: 116.65 +/- 30.36

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | 18.9        |
| time/                   |             |
|    total_timesteps      | 8900000     |
| train/                  |             |
|    approx_kl            | 0.003327161 |
|    clip_fraction        | 0.0165      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.848      |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | 411         |
|    n_updates            | 2168        |
|    policy_gradient_loss | -9.21e-05   |
|    value_loss           | 1.05e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_8900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 83.4     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 202      |
|    time_elapsed    | 1980     |
|    total_timesteps | 8909568  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 127         |
|    ep_rew_mean          | 77.7        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 203         |
|    time_elapsed         | 1989        |
|    total_timesteps      | 8925952     |
| train/                  |             |
|    approx_kl            | 0.004278127 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.841      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 343         |
|    n_updates            | 2172        |
|    policy_gradient_loss | 2.11e-05    |
|    value_loss           | 913         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 90.2         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 204          |
|    time_elapsed         | 1998         |
|    total_timesteps      | 8942336      |
| train/                  |              |
|    approx_kl            | 0.0044257804 |
|    clip_fraction        | 0.0398       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 361          |
|    n_updates            | 2176         |
|    policy_gradient_loss | -0.000663    |
|    value_loss           | 830          |
------------------------------------------

Eval num_timesteps=8950000, episode_reward=-39.43 +/- 166.27

Episode length: 101.55 +/- 21.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 102          |
|    mean_reward          | -39.4        |
| time/                   |              |
|    total_timesteps      | 8950000      |
| train/                  |              |
|    approx_kl            | 0.0031074344 |
|    clip_fraction        | 0.0169       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.853        |
|    learning_rate        | 0.0003       |
|    loss                 | 345          |
|    n_updates            | 2180         |
|    policy_gradient_loss | -0.000348    |
|    value_loss           | 926          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 121      |
|    ep_rew_mean     | 71.8     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 205      |
|    time_elapsed    | 2009     |
|    total_timesteps | 8958720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 77.6         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 206          |
|    time_elapsed         | 2018         |
|    total_timesteps      | 8975104      |
| train/                  |              |
|    approx_kl            | 0.0017177612 |
|    clip_fraction        | 0.0108       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 551          |
|    n_updates            | 2184         |
|    policy_gradient_loss | 0.000405     |
|    value_loss           | 1.34e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 72.7         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 207          |
|    time_elapsed         | 2028         |
|    total_timesteps      | 8991488      |
| train/                  |              |
|    approx_kl            | 0.0040169777 |
|    clip_fraction        | 0.0259       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 680          |
|    n_updates            | 2188         |
|    policy_gradient_loss | 0.00028      |
|    value_loss           | 782          |
------------------------------------------

Eval num_timesteps=9000000, episode_reward=17.28 +/- 190.98

Episode length: 101.10 +/- 20.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 101          |
|    mean_reward          | 17.3         |
| time/                   |              |
|    total_timesteps      | 9000000      |
| train/                  |              |
|    approx_kl            | 0.0037832567 |
|    clip_fraction        | 0.0293       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 126          |
|    n_updates            | 2192         |
|    policy_gradient_loss | 0.000203     |
|    value_loss           | 612          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 78.4     |
| time/              |          |
|    fps             | 1667     |
|    iterations      | 208      |
|    time_elapsed    | 2043     |
|    total_timesteps | 9007872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 78.5         |
| time/                   |              |
|    fps                  | 1667         |
|    iterations           | 209          |
|    time_elapsed         | 2053         |
|    total_timesteps      | 9024256      |
| train/                  |              |
|    approx_kl            | 0.0026606407 |
|    clip_fraction        | 0.0316       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.851       |
|    explained_variance   | 0.914        |
|    learning_rate        | 0.0003       |
|    loss                 | 514          |
|    n_updates            | 2196         |
|    policy_gradient_loss | 0.000397     |
|    value_loss           | 727          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 139          |
|    ep_rew_mean          | 85           |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 210          |
|    time_elapsed         | 2061         |
|    total_timesteps      | 9040640      |
| train/                  |              |
|    approx_kl            | 0.0046344073 |
|    clip_fraction        | 0.0449       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 139          |
|    n_updates            | 2200         |
|    policy_gradient_loss | -0.0011      |
|    value_loss           | 381          |
------------------------------------------

Eval num_timesteps=9050000, episode_reward=26.21 +/- 58.66

Episode length: 102.70 +/- 17.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | 26.2         |
| time/                   |              |
|    total_timesteps      | 9050000      |
| train/                  |              |
|    approx_kl            | 0.0043000393 |
|    clip_fraction        | 0.0239       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 632          |
|    n_updates            | 2204         |
|    policy_gradient_loss | -0.00204     |
|    value_loss           | 1.33e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 112      |
|    ep_rew_mean     | 65.4     |
| time/              |          |
|    fps             | 1667     |
|    iterations      | 211      |
|    time_elapsed    | 2072     |
|    total_timesteps | 9057024  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 110          |
|    ep_rew_mean          | 82.4         |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 212          |
|    time_elapsed         | 2082         |
|    total_timesteps      | 9073408      |
| train/                  |              |
|    approx_kl            | 0.0053575383 |
|    clip_fraction        | 0.0504       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 113          |
|    n_updates            | 2208         |
|    policy_gradient_loss | -0.000985    |
|    value_loss           | 316          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 84.4         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 213          |
|    time_elapsed         | 2090         |
|    total_timesteps      | 9089792      |
| train/                  |              |
|    approx_kl            | 0.0037833909 |
|    clip_fraction        | 0.0189       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.854       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 313          |
|    n_updates            | 2212         |
|    policy_gradient_loss | -0.000408    |
|    value_loss           | 973          |
------------------------------------------

Eval num_timesteps=9100000, episode_reward=-50.78 +/- 209.79

Episode length: 106.55 +/- 29.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -50.8        |
| time/                   |              |
|    total_timesteps      | 9100000      |
| train/                  |              |
|    approx_kl            | 0.0036859582 |
|    clip_fraction        | 0.0152       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.862       |
|    explained_variance   | 0.95         |
|    learning_rate        | 0.0003       |
|    loss                 | 478          |
|    n_updates            | 2216         |
|    policy_gradient_loss | -0.000888    |
|    value_loss           | 1.24e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 93.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 214      |
|    time_elapsed    | 2101     |
|    total_timesteps | 9106176  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 76.3         |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 215          |
|    time_elapsed         | 2111         |
|    total_timesteps      | 9122560      |
| train/                  |              |
|    approx_kl            | 0.0038165352 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.9         |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 549          |
|    n_updates            | 2220         |
|    policy_gradient_loss | -0.000672    |
|    value_loss           | 1.32e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 85.7        |
| time/                   |             |
|    fps                  | 1668        |
|    iterations           | 216         |
|    time_elapsed         | 2120        |
|    total_timesteps      | 9138944     |
| train/                  |             |
|    approx_kl            | 0.004045119 |
|    clip_fraction        | 0.0302      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.894      |
|    explained_variance   | 0.941       |
|    learning_rate        | 0.0003      |
|    loss                 | 879         |
|    n_updates            | 2224        |
|    policy_gradient_loss | -0.00157    |
|    value_loss           | 1.37e+03    |
-----------------------------------------

Eval num_timesteps=9150000, episode_reward=9.24 +/- 169.28

Episode length: 107.45 +/- 19.28

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | 9.24         |
| time/                   |              |
|    total_timesteps      | 9150000      |
| train/                  |              |
|    approx_kl            | 0.0038708353 |
|    clip_fraction        | 0.026        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 458          |
|    n_updates            | 2228         |
|    policy_gradient_loss | -0.00133     |
|    value_loss           | 863          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 79.5     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 217      |
|    time_elapsed    | 2131     |
|    total_timesteps | 9155328  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 78.1        |
| time/                   |             |
|    fps                  | 1668        |
|    iterations           | 218         |
|    time_elapsed         | 2140        |
|    total_timesteps      | 9171712     |
| train/                  |             |
|    approx_kl            | 0.004015264 |
|    clip_fraction        | 0.0386      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.836      |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | 506         |
|    n_updates            | 2232        |
|    policy_gradient_loss | -0.00146    |
|    value_loss           | 936         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 85.7         |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 219          |
|    time_elapsed         | 2149         |
|    total_timesteps      | 9188096      |
| train/                  |              |
|    approx_kl            | 0.0045659407 |
|    clip_fraction        | 0.0302       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.86        |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 535          |
|    n_updates            | 2236         |
|    policy_gradient_loss | -0.000177    |
|    value_loss           | 1.06e+03     |
------------------------------------------

Eval num_timesteps=9200000, episode_reward=-20.63 +/- 151.87

Episode length: 102.55 +/- 24.34

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 103         |
|    mean_reward          | -20.6       |
| time/                   |             |
|    total_timesteps      | 9200000     |
| train/                  |             |
|    approx_kl            | 0.004365032 |
|    clip_fraction        | 0.0274      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.822      |
|    explained_variance   | 0.941       |
|    learning_rate        | 0.0003      |
|    loss                 | 93.4        |
|    n_updates            | 2240        |
|    policy_gradient_loss | -0.00121    |
|    value_loss           | 707         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 87.8     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 220      |
|    time_elapsed    | 2160     |
|    total_timesteps | 9204480  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 85.4         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 221          |
|    time_elapsed         | 2169         |
|    total_timesteps      | 9220864      |
| train/                  |              |
|    approx_kl            | 0.0033346098 |
|    clip_fraction        | 0.0097       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 331          |
|    n_updates            | 2244         |
|    policy_gradient_loss | 8.61e-05     |
|    value_loss           | 1.48e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 75.4         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 222          |
|    time_elapsed         | 2178         |
|    total_timesteps      | 9237248      |
| train/                  |              |
|    approx_kl            | 0.0032425104 |
|    clip_fraction        | 0.0195       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.981        |
|    learning_rate        | 0.0003       |
|    loss                 | 368          |
|    n_updates            | 2248         |
|    policy_gradient_loss | -0.000743    |
|    value_loss           | 1.03e+03     |
------------------------------------------

Eval num_timesteps=9250000, episode_reward=7.71 +/- 81.76

Episode length: 105.60 +/- 23.07

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 106          |
|    mean_reward          | 7.71         |
| time/                   |              |
|    total_timesteps      | 9250000      |
| train/                  |              |
|    approx_kl            | 0.0026453198 |
|    clip_fraction        | 0.0159       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 906          |
|    n_updates            | 2252         |
|    policy_gradient_loss | 0.000116     |
|    value_loss           | 1.04e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 88       |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 223      |
|    time_elapsed    | 2190     |
|    total_timesteps | 9253632  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 120        |
|    ep_rew_mean          | 88.2       |
| time/                   |            |
|    fps                  | 1669       |
|    iterations           | 225        |
|    time_elapsed         | 2207       |
|    total_timesteps      | 9286400    |
| train/                  |            |
|    approx_kl            | 0.00429585 |
|    clip_fraction        | 0.0303     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.823     |
|    explained_variance   | 0.937      |
|    learning_rate        | 0.0003     |
|    loss                 | 730        |
|    n_updates            | 2260       |
|    policy_gradient_loss | -0.00059   |
|    value_loss           | 972        |
----------------------------------------

Eval num_timesteps=9300000, episode_reward=-10.22 +/- 117.40

Episode length: 96.40 +/- 17.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.4         |
|    mean_reward          | -10.2        |
| time/                   |              |
|    total_timesteps      | 9300000      |
| train/                  |              |
|    approx_kl            | 0.0028525507 |
|    clip_fraction        | 0.0221       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.747        |
|    learning_rate        | 0.0003       |
|    loss                 | 698          |
|    n_updates            | 2264         |
|    policy_gradient_loss | -0.000531    |
|    value_loss           | 1.19e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 120      |
|    ep_rew_mean     | 68.6     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 226      |
|    time_elapsed    | 2219     |
|    total_timesteps | 9302784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 79           |
| time/                   |              |
|    fps                  | 1668         |
|    iterations           | 227          |
|    time_elapsed         | 2228         |
|    total_timesteps      | 9319168      |
| train/                  |              |
|    approx_kl            | 0.0036748142 |
|    clip_fraction        | 0.0308       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.824        |
|    learning_rate        | 0.0003       |
|    loss                 | 491          |
|    n_updates            | 2268         |
|    policy_gradient_loss | -0.00148     |
|    value_loss           | 1.02e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 81.3        |
| time/                   |             |
|    fps                  | 1669        |
|    iterations           | 228         |
|    time_elapsed         | 2237        |
|    total_timesteps      | 9335552     |
| train/                  |             |
|    approx_kl            | 0.003823563 |
|    clip_fraction        | 0.0343      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.903      |
|    explained_variance   | 0.841       |
|    learning_rate        | 0.0003      |
|    loss                 | 588         |
|    n_updates            | 2272        |
|    policy_gradient_loss | -0.000128   |
|    value_loss           | 923         |
-----------------------------------------

Eval num_timesteps=9350000, episode_reward=25.69 +/- 85.28

Episode length: 95.95 +/- 13.76

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96           |
|    mean_reward          | 25.7         |
| time/                   |              |
|    total_timesteps      | 9350000      |
| train/                  |              |
|    approx_kl            | 0.0034329505 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.804        |
|    learning_rate        | 0.0003       |
|    loss                 | 395          |
|    n_updates            | 2276         |
|    policy_gradient_loss | -0.000129    |
|    value_loss           | 921          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 72.8     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 229      |
|    time_elapsed    | 2247     |
|    total_timesteps | 9351936  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 83.4         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 230          |
|    time_elapsed         | 2257         |
|    total_timesteps      | 9368320      |
| train/                  |              |
|    approx_kl            | 0.0054343366 |
|    clip_fraction        | 0.0413       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.83        |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 339          |
|    n_updates            | 2280         |
|    policy_gradient_loss | -0.00158     |
|    value_loss           | 389          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 88.8         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 231          |
|    time_elapsed         | 2266         |
|    total_timesteps      | 9384704      |
| train/                  |              |
|    approx_kl            | 0.0017207252 |
|    clip_fraction        | 0.00961      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.844       |
|    explained_variance   | 0.813        |
|    learning_rate        | 0.0003       |
|    loss                 | 626          |
|    n_updates            | 2284         |
|    policy_gradient_loss | 0.000662     |
|    value_loss           | 822          |
------------------------------------------

Eval num_timesteps=9400000, episode_reward=-45.47 +/- 209.49

Episode length: 101.40 +/- 24.61

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 101          |
|    mean_reward          | -45.5        |
| time/                   |              |
|    total_timesteps      | 9400000      |
| train/                  |              |
|    approx_kl            | 0.0045848745 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.828       |
|    explained_variance   | 0.85         |
|    learning_rate        | 0.0003       |
|    loss                 | 534          |
|    n_updates            | 2288         |
|    policy_gradient_loss | -0.00188     |
|    value_loss           | 707          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 118      |
|    ep_rew_mean     | 87.3     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 232      |
|    time_elapsed    | 2276     |
|    total_timesteps | 9401088  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 102         |
| time/                   |             |
|    fps                  | 1669        |
|    iterations           | 233         |
|    time_elapsed         | 2286        |
|    total_timesteps      | 9417472     |
| train/                  |             |
|    approx_kl            | 0.005170201 |
|    clip_fraction        | 0.0399      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.851      |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 509         |
|    n_updates            | 2292        |
|    policy_gradient_loss | -0.00225    |
|    value_loss           | 1.2e+03     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 77           |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 234          |
|    time_elapsed         | 2295         |
|    total_timesteps      | 9433856      |
| train/                  |              |
|    approx_kl            | 0.0031248482 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 302          |
|    n_updates            | 2296         |
|    policy_gradient_loss | -0.00079     |
|    value_loss           | 1.05e+03     |
------------------------------------------

Eval num_timesteps=9450000, episode_reward=-4.69 +/- 113.81

Episode length: 92.05 +/- 27.33

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 92          |
|    mean_reward          | -4.69       |
| time/                   |             |
|    total_timesteps      | 9450000     |
| train/                  |             |
|    approx_kl            | 0.003161362 |
|    clip_fraction        | 0.0189      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.828      |
|    explained_variance   | 0.958       |
|    learning_rate        | 0.0003      |
|    loss                 | 224         |
|    n_updates            | 2300        |
|    policy_gradient_loss | -0.000899   |
|    value_loss           | 829         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 78.1     |
| time/              |          |
|    fps             | 1669     |
|    iterations      | 235      |
|    time_elapsed    | 2305     |
|    total_timesteps | 9450240  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 118          |
|    ep_rew_mean          | 70.2         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 236          |
|    time_elapsed         | 2314         |
|    total_timesteps      | 9466624      |
| train/                  |              |
|    approx_kl            | 0.0032931739 |
|    clip_fraction        | 0.0313       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.825       |
|    explained_variance   | 0.934        |
|    learning_rate        | 0.0003       |
|    loss                 | 257          |
|    n_updates            | 2304         |
|    policy_gradient_loss | -9.8e-05     |
|    value_loss           | 1.01e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 77.8        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 237         |
|    time_elapsed         | 2323        |
|    total_timesteps      | 9483008     |
| train/                  |             |
|    approx_kl            | 0.003101862 |
|    clip_fraction        | 0.0262      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.843      |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 223         |
|    n_updates            | 2308        |
|    policy_gradient_loss | -0.00062    |
|    value_loss           | 795         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 110         |
|    ep_rew_mean          | 77.5        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 238         |
|    time_elapsed         | 2332        |
|    total_timesteps      | 9499392     |
| train/                  |             |
|    approx_kl            | 0.002420586 |
|    clip_fraction        | 0.015       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.823      |
|    explained_variance   | 0.96        |
|    learning_rate        | 0.0003      |
|    loss                 | 516         |
|    n_updates            | 2312        |
|    policy_gradient_loss | -0.000891   |
|    value_loss           | 954         |
-----------------------------------------

Eval num_timesteps=9500000, episode_reward=-37.82 +/- 232.09

Episode length: 104.10 +/- 30.97

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | -37.8       |
| time/                   |             |
|    total_timesteps      | 9500000     |
| train/                  |             |
|    approx_kl            | 0.003887826 |
|    clip_fraction        | 0.0344      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.838      |
|    explained_variance   | 0.836       |
|    learning_rate        | 0.0003      |
|    loss                 | 208         |
|    n_updates            | 2316        |
|    policy_gradient_loss | 0.00052     |
|    value_loss           | 854         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 68.2     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 239      |
|    time_elapsed    | 2342     |
|    total_timesteps | 9515776  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 112          |
|    ep_rew_mean          | 75.7         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 240          |
|    time_elapsed         | 2352         |
|    total_timesteps      | 9532160      |
| train/                  |              |
|    approx_kl            | 0.0040129237 |
|    clip_fraction        | 0.028        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 407          |
|    n_updates            | 2320         |
|    policy_gradient_loss | -0.000691    |
|    value_loss           | 1.22e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 112         |
|    ep_rew_mean          | 76.3        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 241         |
|    time_elapsed         | 2361        |
|    total_timesteps      | 9548544     |
| train/                  |             |
|    approx_kl            | 0.003140982 |
|    clip_fraction        | 0.0253      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.843      |
|    explained_variance   | 0.837       |
|    learning_rate        | 0.0003      |
|    loss                 | 381         |
|    n_updates            | 2324        |
|    policy_gradient_loss | -0.00072    |
|    value_loss           | 703         |
-----------------------------------------

Eval num_timesteps=9550000, episode_reward=3.69 +/- 114.34

Episode length: 96.50 +/- 17.09

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.5         |
|    mean_reward          | 3.69         |
| time/                   |              |
|    total_timesteps      | 9550000      |
| train/                  |              |
|    approx_kl            | 0.0032417132 |
|    clip_fraction        | 0.0213       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.832       |
|    explained_variance   | 0.927        |
|    learning_rate        | 0.0003       |
|    loss                 | 348          |
|    n_updates            | 2328         |
|    policy_gradient_loss | -0.000388    |
|    value_loss           | 845          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 91.8     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 242      |
|    time_elapsed    | 2371     |
|    total_timesteps | 9564928  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 113         |
|    ep_rew_mean          | 70.5        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 243         |
|    time_elapsed         | 2380        |
|    total_timesteps      | 9581312     |
| train/                  |             |
|    approx_kl            | 0.003925988 |
|    clip_fraction        | 0.0263      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.892      |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | 997         |
|    n_updates            | 2332        |
|    policy_gradient_loss | -0.00051    |
|    value_loss           | 1.3e+03     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 83.4        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 244         |
|    time_elapsed         | 2389        |
|    total_timesteps      | 9597696     |
| train/                  |             |
|    approx_kl            | 0.003117424 |
|    clip_fraction        | 0.0248      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.852      |
|    explained_variance   | 0.86        |
|    learning_rate        | 0.0003      |
|    loss                 | 139         |
|    n_updates            | 2336        |
|    policy_gradient_loss | 0.000153    |
|    value_loss           | 537         |
-----------------------------------------

Eval num_timesteps=9600000, episode_reward=23.40 +/- 89.10

Episode length: 100.10 +/- 19.92

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 100          |
|    mean_reward          | 23.4         |
| time/                   |              |
|    total_timesteps      | 9600000      |
| train/                  |              |
|    approx_kl            | 0.0044907546 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.952        |
|    learning_rate        | 0.0003       |
|    loss                 | 677          |
|    n_updates            | 2340         |
|    policy_gradient_loss | -4.53e-06    |
|    value_loss           | 1.14e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 81.8     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 245      |
|    time_elapsed    | 2400     |
|    total_timesteps | 9614080  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 115         |
|    ep_rew_mean          | 81.1        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 246         |
|    time_elapsed         | 2408        |
|    total_timesteps      | 9630464     |
| train/                  |             |
|    approx_kl            | 0.003902804 |
|    clip_fraction        | 0.0312      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.811      |
|    explained_variance   | 0.774       |
|    learning_rate        | 0.0003      |
|    loss                 | 423         |
|    n_updates            | 2344        |
|    policy_gradient_loss | -0.00125    |
|    value_loss           | 728         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 87.1        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 247         |
|    time_elapsed         | 2418        |
|    total_timesteps      | 9646848     |
| train/                  |             |
|    approx_kl            | 0.001892383 |
|    clip_fraction        | 0.0115      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.83       |
|    explained_variance   | 0.852       |
|    learning_rate        | 0.0003      |
|    loss                 | 357         |
|    n_updates            | 2348        |
|    policy_gradient_loss | 0.000425    |
|    value_loss           | 1.08e+03    |
-----------------------------------------

Eval num_timesteps=9650000, episode_reward=-3.70 +/- 135.93

Episode length: 105.15 +/- 20.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 105         |
|    mean_reward          | -3.7        |
| time/                   |             |
|    total_timesteps      | 9650000     |
| train/                  |             |
|    approx_kl            | 0.005609905 |
|    clip_fraction        | 0.0385      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.867      |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | 303         |
|    n_updates            | 2352        |
|    policy_gradient_loss | -0.00123    |
|    value_loss           | 1.16e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 78.3     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 248      |
|    time_elapsed    | 2429     |
|    total_timesteps | 9663232  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 122          |
|    ep_rew_mean          | 97.4         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 249          |
|    time_elapsed         | 2437         |
|    total_timesteps      | 9679616      |
| train/                  |              |
|    approx_kl            | 0.0048588132 |
|    clip_fraction        | 0.0289       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 881          |
|    n_updates            | 2356         |
|    policy_gradient_loss | -0.000829    |
|    value_loss           | 1.19e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 84          |
| time/                   |             |
|    fps                  | 1674        |
|    iterations           | 250         |
|    time_elapsed         | 2446        |
|    total_timesteps      | 9696000     |
| train/                  |             |
|    approx_kl            | 0.003290092 |
|    clip_fraction        | 0.021       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.859      |
|    explained_variance   | 0.94        |
|    learning_rate        | 0.0003      |
|    loss                 | 746         |
|    n_updates            | 2360        |
|    policy_gradient_loss | -0.000495   |
|    value_loss           | 1.37e+03    |
-----------------------------------------

Eval num_timesteps=9700000, episode_reward=-6.64 +/- 305.53

Episode length: 109.85 +/- 37.55

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 110          |
|    mean_reward          | -6.64        |
| time/                   |              |
|    total_timesteps      | 9700000      |
| train/                  |              |
|    approx_kl            | 0.0027125275 |
|    clip_fraction        | 0.0246       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.823       |
|    explained_variance   | 0.958        |
|    learning_rate        | 0.0003       |
|    loss                 | 249          |
|    n_updates            | 2364         |
|    policy_gradient_loss | 9.06e-05     |
|    value_loss           | 769          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 112      |
|    ep_rew_mean     | 68.1     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 251      |
|    time_elapsed    | 2457     |
|    total_timesteps | 9712384  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 80.6        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 252         |
|    time_elapsed         | 2467        |
|    total_timesteps      | 9728768     |
| train/                  |             |
|    approx_kl            | 0.004018769 |
|    clip_fraction        | 0.0255      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.874      |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 384         |
|    n_updates            | 2368        |
|    policy_gradient_loss | 0.000107    |
|    value_loss           | 916         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 73.7         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 253          |
|    time_elapsed         | 2475         |
|    total_timesteps      | 9745152      |
| train/                  |              |
|    approx_kl            | 0.0032858173 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.795       |
|    explained_variance   | 0.947        |
|    learning_rate        | 0.0003       |
|    loss                 | 357          |
|    n_updates            | 2372         |
|    policy_gradient_loss | -0.00194     |
|    value_loss           | 1.04e+03     |
------------------------------------------

Eval num_timesteps=9750000, episode_reward=18.04 +/- 163.60

Episode length: 91.95 +/- 15.73

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 92          |
|    mean_reward          | 18          |
| time/                   |             |
|    total_timesteps      | 9750000     |
| train/                  |             |
|    approx_kl            | 0.002564819 |
|    clip_fraction        | 0.0149      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.819      |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | 472         |
|    n_updates            | 2376        |
|    policy_gradient_loss | -0.000372   |
|    value_loss           | 1.11e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 96.1     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 254      |
|    time_elapsed    | 2486     |
|    total_timesteps | 9761536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 121          |
|    ep_rew_mean          | 88.9         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 255          |
|    time_elapsed         | 2495         |
|    total_timesteps      | 9777920      |
| train/                  |              |
|    approx_kl            | 0.0034900506 |
|    clip_fraction        | 0.013        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 288          |
|    n_updates            | 2380         |
|    policy_gradient_loss | 0.00016      |
|    value_loss           | 1.4e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 110          |
|    ep_rew_mean          | 78.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 256          |
|    time_elapsed         | 2503         |
|    total_timesteps      | 9794304      |
| train/                  |              |
|    approx_kl            | 0.0030686285 |
|    clip_fraction        | 0.0256       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.809       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 204          |
|    n_updates            | 2384         |
|    policy_gradient_loss | -0.00107     |
|    value_loss           | 844          |
------------------------------------------

Eval num_timesteps=9800000, episode_reward=26.21 +/- 121.32

Episode length: 98.45 +/- 21.37

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98.5         |
|    mean_reward          | 26.2         |
| time/                   |              |
|    total_timesteps      | 9800000      |
| train/                  |              |
|    approx_kl            | 0.0028866793 |
|    clip_fraction        | 0.0138       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.778        |
|    learning_rate        | 0.0003       |
|    loss                 | 490          |
|    n_updates            | 2388         |
|    policy_gradient_loss | 0.00123      |
|    value_loss           | 1.07e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 90       |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 257      |
|    time_elapsed    | 2514     |
|    total_timesteps | 9810688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 75.5        |
| time/                   |             |
|    fps                  | 1674        |
|    iterations           | 258         |
|    time_elapsed         | 2524        |
|    total_timesteps      | 9827072     |
| train/                  |             |
|    approx_kl            | 0.003995804 |
|    clip_fraction        | 0.0226      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.887      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 192         |
|    n_updates            | 2392        |
|    policy_gradient_loss | 0.000427    |
|    value_loss           | 2.19e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 128         |
|    ep_rew_mean          | 74.3        |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 259         |
|    time_elapsed         | 2533        |
|    total_timesteps      | 9843456     |
| train/                  |             |
|    approx_kl            | 0.003334866 |
|    clip_fraction        | 0.0262      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.832      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 581         |
|    n_updates            | 2396        |
|    policy_gradient_loss | -0.000437   |
|    value_loss           | 901         |
-----------------------------------------

Eval num_timesteps=9850000, episode_reward=7.76 +/- 100.33

Episode length: 103.65 +/- 18.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | 7.76         |
| time/                   |              |
|    total_timesteps      | 9850000      |
| train/                  |              |
|    approx_kl            | 0.0039787176 |
|    clip_fraction        | 0.0313       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.836       |
|    explained_variance   | 0.948        |
|    learning_rate        | 0.0003       |
|    loss                 | 319          |
|    n_updates            | 2400         |
|    policy_gradient_loss | -0.000591    |
|    value_loss           | 1.33e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 93.2     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 260      |
|    time_elapsed    | 2543     |
|    total_timesteps | 9859840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 104          |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 261          |
|    time_elapsed         | 2553         |
|    total_timesteps      | 9876224      |
| train/                  |              |
|    approx_kl            | 0.0040518977 |
|    clip_fraction        | 0.0297       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 706          |
|    n_updates            | 2404         |
|    policy_gradient_loss | -0.000346    |
|    value_loss           | 1.21e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 126          |
|    ep_rew_mean          | 88.1         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 262          |
|    time_elapsed         | 2562         |
|    total_timesteps      | 9892608      |
| train/                  |              |
|    approx_kl            | 0.0029538109 |
|    clip_fraction        | 0.0188       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 697          |
|    n_updates            | 2408         |
|    policy_gradient_loss | 0.000269     |
|    value_loss           | 1.39e+03     |
------------------------------------------

Eval num_timesteps=9900000, episode_reward=-29.29 +/- 153.08

Episode length: 99.20 +/- 23.41

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99.2         |
|    mean_reward          | -29.3        |
| time/                   |              |
|    total_timesteps      | 9900000      |
| train/                  |              |
|    approx_kl            | 0.0031242578 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 299          |
|    n_updates            | 2412         |
|    policy_gradient_loss | -0.000472    |
|    value_loss           | 1.27e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_9900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | 81.2     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 263      |
|    time_elapsed    | 2573     |
|    total_timesteps | 9908992  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 113          |
|    ep_rew_mean          | 80.2         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 264          |
|    time_elapsed         | 2581         |
|    total_timesteps      | 9925376      |
| train/                  |              |
|    approx_kl            | 0.0025355318 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.908        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 2416         |
|    policy_gradient_loss | -9.43e-05    |
|    value_loss           | 1.63e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 74.9        |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 265         |
|    time_elapsed         | 2591        |
|    total_timesteps      | 9941760     |
| train/                  |             |
|    approx_kl            | 0.004346755 |
|    clip_fraction        | 0.0315      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.826      |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | 436         |
|    n_updates            | 2420        |
|    policy_gradient_loss | -0.00112    |
|    value_loss           | 694         |
-----------------------------------------

Eval num_timesteps=9950000, episode_reward=-48.78 +/- 136.25

Episode length: 98.40 +/- 20.14

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98.4        |
|    mean_reward          | -48.8       |
| time/                   |             |
|    total_timesteps      | 9950000     |
| train/                  |             |
|    approx_kl            | 0.002542168 |
|    clip_fraction        | 0.0185      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.79       |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | 653         |
|    n_updates            | 2424        |
|    policy_gradient_loss | -0.000397   |
|    value_loss           | 1.22e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 116      |
|    ep_rew_mean     | 85.7     |
| time/              |          |
|    fps             | 1675     |
|    iterations      | 266      |
|    time_elapsed    | 2601     |
|    total_timesteps | 9958144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 116         |
|    ep_rew_mean          | 79          |
| time/                   |             |
|    fps                  | 1676        |
|    iterations           | 267         |
|    time_elapsed         | 2609        |
|    total_timesteps      | 9974528     |
| train/                  |             |
|    approx_kl            | 0.004702801 |
|    clip_fraction        | 0.041       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.832      |
|    explained_variance   | 0.736       |
|    learning_rate        | 0.0003      |
|    loss                 | 536         |
|    n_updates            | 2428        |
|    policy_gradient_loss | -0.000586   |
|    value_loss           | 1.76e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 76.9        |
| time/                   |             |
|    fps                  | 1676        |
|    iterations           | 268         |
|    time_elapsed         | 2619        |
|    total_timesteps      | 9990912     |
| train/                  |             |
|    approx_kl            | 0.004059945 |
|    clip_fraction        | 0.0363      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.852      |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | 434         |
|    n_updates            | 2432        |
|    policy_gradient_loss | -0.000432   |
|    value_loss           | 987         |
-----------------------------------------

Eval num_timesteps=10000000, episode_reward=91.58 +/- 125.68

Episode length: 97.00 +/- 19.53

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97           |
|    mean_reward          | 91.6         |
| time/                   |              |
|    total_timesteps      | 10000000     |
| train/                  |              |
|    approx_kl            | 0.0048615346 |
|    clip_fraction        | 0.0386       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 456          |
|    n_updates            | 2436         |
|    policy_gradient_loss | -0.0015      |
|    value_loss           | 1.15e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 10,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 79.4     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 269      |
|    time_elapsed    | 2635     |
|    total_timesteps | 10007296 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 72.7        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 270         |
|    time_elapsed         | 2644        |
|    total_timesteps      | 10023680    |
| train/                  |             |
|    approx_kl            | 0.004176459 |
|    clip_fraction        | 0.0351      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.792      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 434         |
|    n_updates            | 2440        |
|    policy_gradient_loss | -0.00111    |
|    value_loss           | 759         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 120         |
|    ep_rew_mean          | 76.1        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 271         |
|    time_elapsed         | 2654        |
|    total_timesteps      | 10040064    |
| train/                  |             |
|    approx_kl            | 0.004942566 |
|    clip_fraction        | 0.049       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.834      |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.0003      |
|    loss                 | 139         |
|    n_updates            | 2444        |
|    policy_gradient_loss | -0.000968   |
|    value_loss           | 421         |
-----------------------------------------

Eval num_timesteps=10050000, episode_reward=85.17 +/- 145.51

Episode length: 107.00 +/- 25.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | 85.2         |
| time/                   |              |
|    total_timesteps      | 10050000     |
| train/                  |              |
|    approx_kl            | 0.0036916074 |
|    clip_fraction        | 0.0236       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.885       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 158          |
|    n_updates            | 2448         |
|    policy_gradient_loss | -0.000283    |
|    value_loss           | 823          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 124      |
|    ep_rew_mean     | 74.2     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 272      |
|    time_elapsed    | 2664     |
|    total_timesteps | 10056448 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 117          |
|    ep_rew_mean          | 74.9         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 273          |
|    time_elapsed         | 2673         |
|    total_timesteps      | 10072832     |
| train/                  |              |
|    approx_kl            | 0.0052062776 |
|    clip_fraction        | 0.0435       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 664          |
|    n_updates            | 2452         |
|    policy_gradient_loss | -0.000904    |
|    value_loss           | 831          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 79.9         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 274          |
|    time_elapsed         | 2683         |
|    total_timesteps      | 10089216     |
| train/                  |              |
|    approx_kl            | 0.0035402416 |
|    clip_fraction        | 0.032        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.943        |
|    learning_rate        | 0.0003       |
|    loss                 | 119          |
|    n_updates            | 2456         |
|    policy_gradient_loss | -0.00148     |
|    value_loss           | 799          |
------------------------------------------

Eval num_timesteps=10100000, episode_reward=-30.93 +/- 187.95

Episode length: 99.20 +/- 17.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.2        |
|    mean_reward          | -30.9       |
| time/                   |             |
|    total_timesteps      | 10100000    |
| train/                  |             |
|    approx_kl            | 0.003908015 |
|    clip_fraction        | 0.0285      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | 355         |
|    n_updates            | 2460        |
|    policy_gradient_loss | -0.000775   |
|    value_loss           | 854         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 114      |
|    ep_rew_mean     | 73.5     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 275      |
|    time_elapsed    | 2693     |
|    total_timesteps | 10105600 |
---------------------------------
---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 123       |
|    ep_rew_mean          | 93.3      |
| time/                   |           |
|    fps                  | 1673      |
|    iterations           | 276       |
|    time_elapsed         | 2702      |
|    total_timesteps      | 10121984  |
| train/                  |           |
|    approx_kl            | 0.0034955 |
|    clip_fraction        | 0.021     |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.878    |
|    explained_variance   | 0.915     |
|    learning_rate        | 0.0003    |
|    loss                 | 185       |
|    n_updates            | 2464      |
|    policy_gradient_loss | 0.000523  |
|    value_loss           | 716       |
---------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 76.8        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 277         |
|    time_elapsed         | 2711        |
|    total_timesteps      | 10138368    |
| train/                  |             |
|    approx_kl            | 0.002767459 |
|    clip_fraction        | 0.0155      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.854      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 491         |
|    n_updates            | 2468        |
|    policy_gradient_loss | -0.000477   |
|    value_loss           | 1.12e+03    |
-----------------------------------------

Eval num_timesteps=10150000, episode_reward=59.14 +/- 60.78

Episode length: 93.00 +/- 23.63

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 93           |
|    mean_reward          | 59.1         |
| time/                   |              |
|    total_timesteps      | 10150000     |
| train/                  |              |
|    approx_kl            | 0.0038078947 |
|    clip_fraction        | 0.0143       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 267          |
|    n_updates            | 2472         |
|    policy_gradient_loss | 0.000408     |
|    value_loss           | 1.19e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 99.8     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 278      |
|    time_elapsed    | 2722     |
|    total_timesteps | 10154752 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 122         |
|    ep_rew_mean          | 78.4        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 279         |
|    time_elapsed         | 2730        |
|    total_timesteps      | 10171136    |
| train/                  |             |
|    approx_kl            | 0.004135776 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.914      |
|    explained_variance   | 0.974       |
|    learning_rate        | 0.0003      |
|    loss                 | 517         |
|    n_updates            | 2476        |
|    policy_gradient_loss | 4.58e-05    |
|    value_loss           | 1.73e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 84.1         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 280          |
|    time_elapsed         | 2740         |
|    total_timesteps      | 10187520     |
| train/                  |              |
|    approx_kl            | 0.0037923092 |
|    clip_fraction        | 0.0331       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.911       |
|    explained_variance   | 0.906        |
|    learning_rate        | 0.0003       |
|    loss                 | 507          |
|    n_updates            | 2480         |
|    policy_gradient_loss | 0.000587     |
|    value_loss           | 960          |
------------------------------------------

Eval num_timesteps=10200000, episode_reward=-31.04 +/- 138.57

Episode length: 113.45 +/- 33.42

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 113         |
|    mean_reward          | -31         |
| time/                   |             |
|    total_timesteps      | 10200000    |
| train/                  |             |
|    approx_kl            | 0.004710472 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.877      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 613         |
|    n_updates            | 2484        |
|    policy_gradient_loss | -0.000295   |
|    value_loss           | 1.01e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 115      |
|    ep_rew_mean     | 81.6     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 281      |
|    time_elapsed    | 2751     |
|    total_timesteps | 10203904 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 125         |
|    ep_rew_mean          | 79.4        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 282         |
|    time_elapsed         | 2760        |
|    total_timesteps      | 10220288    |
| train/                  |             |
|    approx_kl            | 0.005754434 |
|    clip_fraction        | 0.0584      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.865      |
|    explained_variance   | 0.936       |
|    learning_rate        | 0.0003      |
|    loss                 | 779         |
|    n_updates            | 2488        |
|    policy_gradient_loss | -0.00162    |
|    value_loss           | 931         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 81.7         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 283          |
|    time_elapsed         | 2768         |
|    total_timesteps      | 10236672     |
| train/                  |              |
|    approx_kl            | 0.0038964346 |
|    clip_fraction        | 0.0278       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.868       |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 164          |
|    n_updates            | 2492         |
|    policy_gradient_loss | -0.000689    |
|    value_loss           | 867          |
------------------------------------------

Eval num_timesteps=10250000, episode_reward=-9.48 +/- 221.40

Episode length: 112.10 +/- 28.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -9.48        |
| time/                   |              |
|    total_timesteps      | 10250000     |
| train/                  |              |
|    approx_kl            | 0.0032910835 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.939        |
|    learning_rate        | 0.0003       |
|    loss                 | 337          |
|    n_updates            | 2496         |
|    policy_gradient_loss | -0.000742    |
|    value_loss           | 1.23e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 69.4     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 284      |
|    time_elapsed    | 2779     |
|    total_timesteps | 10253056 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 143          |
|    ep_rew_mean          | 71.2         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 285          |
|    time_elapsed         | 2789         |
|    total_timesteps      | 10269440     |
| train/                  |              |
|    approx_kl            | 0.0041349404 |
|    clip_fraction        | 0.0381       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.946       |
|    explained_variance   | 0.846        |
|    learning_rate        | 0.0003       |
|    loss                 | 535          |
|    n_updates            | 2500         |
|    policy_gradient_loss | -0.00124     |
|    value_loss           | 879          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 69.1         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 286          |
|    time_elapsed         | 2797         |
|    total_timesteps      | 10285824     |
| train/                  |              |
|    approx_kl            | 0.0040072184 |
|    clip_fraction        | 0.0391       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.96        |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 223          |
|    n_updates            | 2504         |
|    policy_gradient_loss | 0.000626     |
|    value_loss           | 719          |
------------------------------------------

Eval num_timesteps=10300000, episode_reward=-19.19 +/- 497.61

Episode length: 117.15 +/- 23.54

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 117         |
|    mean_reward          | -19.2       |
| time/                   |             |
|    total_timesteps      | 10300000    |
| train/                  |             |
|    approx_kl            | 0.004816645 |
|    clip_fraction        | 0.0464      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.936      |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | 98.1        |
|    n_updates            | 2508        |
|    policy_gradient_loss | 0.000237    |
|    value_loss           | 671         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 66.3     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 287      |
|    time_elapsed    | 2808     |
|    total_timesteps | 10302208 |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 138        |
|    ep_rew_mean          | 73.4       |
| time/                   |            |
|    fps                  | 1674       |
|    iterations           | 288        |
|    time_elapsed         | 2817       |
|    total_timesteps      | 10318592   |
| train/                  |            |
|    approx_kl            | 0.00384131 |
|    clip_fraction        | 0.0311     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.931     |
|    explained_variance   | 0.942      |
|    learning_rate        | 0.0003     |
|    loss                 | 88.1       |
|    n_updates            | 2512       |
|    policy_gradient_loss | -0.000367  |
|    value_loss           | 799        |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 146         |
|    ep_rew_mean          | 86.2        |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 289         |
|    time_elapsed         | 2826        |
|    total_timesteps      | 10334976    |
| train/                  |             |
|    approx_kl            | 0.004918594 |
|    clip_fraction        | 0.0318      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.917      |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | 289         |
|    n_updates            | 2516        |
|    policy_gradient_loss | -0.00194    |
|    value_loss           | 889         |
-----------------------------------------

Eval num_timesteps=10350000, episode_reward=39.09 +/- 157.55

Episode length: 126.85 +/- 39.78

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 127          |
|    mean_reward          | 39.1         |
| time/                   |              |
|    total_timesteps      | 10350000     |
| train/                  |              |
|    approx_kl            | 0.0042814948 |
|    clip_fraction        | 0.0336       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.953       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 118          |
|    n_updates            | 2520         |
|    policy_gradient_loss | 1.59e-05     |
|    value_loss           | 799          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 70.5     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 290      |
|    time_elapsed    | 2837     |
|    total_timesteps | 10351360 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 138          |
|    ep_rew_mean          | 70.7         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 291          |
|    time_elapsed         | 2846         |
|    total_timesteps      | 10367744     |
| train/                  |              |
|    approx_kl            | 0.0035140056 |
|    clip_fraction        | 0.029        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.94        |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 298          |
|    n_updates            | 2524         |
|    policy_gradient_loss | -8.69e-05    |
|    value_loss           | 513          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 61          |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 292         |
|    time_elapsed         | 2855        |
|    total_timesteps      | 10384128    |
| train/                  |             |
|    approx_kl            | 0.006155749 |
|    clip_fraction        | 0.0623      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.935      |
|    explained_variance   | 0.96        |
|    learning_rate        | 0.0003      |
|    loss                 | 80.3        |
|    n_updates            | 2528        |
|    policy_gradient_loss | -0.00158    |
|    value_loss           | 399         |
-----------------------------------------

Eval num_timesteps=10400000, episode_reward=-32.46 +/- 176.69

Episode length: 109.70 +/- 32.57

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 110         |
|    mean_reward          | -32.5       |
| time/                   |             |
|    total_timesteps      | 10400000    |
| train/                  |             |
|    approx_kl            | 0.005177851 |
|    clip_fraction        | 0.0431      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.9        |
|    explained_variance   | 0.913       |
|    learning_rate        | 0.0003      |
|    loss                 | 74.6        |
|    n_updates            | 2532        |
|    policy_gradient_loss | -0.00166    |
|    value_loss           | 449         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10400000_steps.zip

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 146          |
|    ep_rew_mean          | 79.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 294          |
|    time_elapsed         | 2875         |
|    total_timesteps      | 10416896     |
| train/                  |              |
|    approx_kl            | 0.0027484414 |
|    clip_fraction        | 0.0212       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | 0.928        |
|    learning_rate        | 0.0003       |
|    loss                 | 121          |
|    n_updates            | 2536         |
|    policy_gradient_loss | -0.000719    |
|    value_loss           | 787          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 148          |
|    ep_rew_mean          | 73.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 295          |
|    time_elapsed         | 2884         |
|    total_timesteps      | 10433280     |
| train/                  |              |
|    approx_kl            | 0.0060156602 |
|    clip_fraction        | 0.036        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.973       |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 417          |
|    n_updates            | 2540         |
|    policy_gradient_loss | -0.000556    |
|    value_loss           | 1.05e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 127          |
|    ep_rew_mean          | 54.6         |
| time/                   |              |
|    fps                  | 1676         |
|    iterations           | 296          |
|    time_elapsed         | 2892         |
|    total_timesteps      | 10449664     |
| train/                  |              |
|    approx_kl            | 0.0044887085 |
|    clip_fraction        | 0.0356       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.961       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 380          |
|    n_updates            | 2544         |
|    policy_gradient_loss | -0.000915    |
|    value_loss           | 927          |
------------------------------------------

Eval num_timesteps=10450000, episode_reward=-39.39 +/- 158.89

Episode length: 103.50 +/- 27.58

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | -39.4        |
| time/                   |              |
|    total_timesteps      | 10450000     |
| train/                  |              |
|    approx_kl            | 0.0059891148 |
|    clip_fraction        | 0.0621       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.9          |
|    learning_rate        | 0.0003       |
|    loss                 | 3.27e+03     |
|    n_updates            | 2548         |
|    policy_gradient_loss | -0.00173     |
|    value_loss           | 2.98e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 147      |
|    ep_rew_mean     | 50.9     |
| time/              |          |
|    fps             | 1675     |
|    iterations      | 297      |
|    time_elapsed    | 2903     |
|    total_timesteps | 10466048 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 75.4        |
| time/                   |             |
|    fps                  | 1676        |
|    iterations           | 298         |
|    time_elapsed         | 2912        |
|    total_timesteps      | 10482432    |
| train/                  |             |
|    approx_kl            | 0.002715846 |
|    clip_fraction        | 0.0284      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.969      |
|    explained_variance   | 0.88        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.76e+03    |
|    n_updates            | 2552        |
|    policy_gradient_loss | -0.00214    |
|    value_loss           | 6.38e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 88.7         |
| time/                   |              |
|    fps                  | 1676         |
|    iterations           | 299          |
|    time_elapsed         | 2921         |
|    total_timesteps      | 10498816     |
| train/                  |              |
|    approx_kl            | 0.0039003927 |
|    clip_fraction        | 0.0347       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.921       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 168          |
|    n_updates            | 2556         |
|    policy_gradient_loss | -0.000393    |
|    value_loss           | 716          |
------------------------------------------

Eval num_timesteps=10500000, episode_reward=-32.12 +/- 210.61

Episode length: 103.05 +/- 29.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 103         |
|    mean_reward          | -32.1       |
| time/                   |             |
|    total_timesteps      | 10500000    |
| train/                  |             |
|    approx_kl            | 0.004683979 |
|    clip_fraction        | 0.0335      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.905      |
|    explained_variance   | 0.877       |
|    learning_rate        | 0.0003      |
|    loss                 | 302         |
|    n_updates            | 2560        |
|    policy_gradient_loss | -0.00074    |
|    value_loss           | 760         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 89.1     |
| time/              |          |
|    fps             | 1676     |
|    iterations      | 300      |
|    time_elapsed    | 2932     |
|    total_timesteps | 10515200 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 53.3         |
| time/                   |              |
|    fps                  | 1676         |
|    iterations           | 301          |
|    time_elapsed         | 2941         |
|    total_timesteps      | 10531584     |
| train/                  |              |
|    approx_kl            | 0.0044449284 |
|    clip_fraction        | 0.0333       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.888       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 288          |
|    n_updates            | 2564         |
|    policy_gradient_loss | -0.00102     |
|    value_loss           | 1.35e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 85           |
| time/                   |              |
|    fps                  | 1676         |
|    iterations           | 302          |
|    time_elapsed         | 2950         |
|    total_timesteps      | 10547968     |
| train/                  |              |
|    approx_kl            | 0.0054729003 |
|    clip_fraction        | 0.0486       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.907       |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 273          |
|    n_updates            | 2568         |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 843          |
------------------------------------------

Eval num_timesteps=10550000, episode_reward=-4.16 +/- 117.08

Episode length: 106.95 +/- 20.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -4.16        |
| time/                   |              |
|    total_timesteps      | 10550000     |
| train/                  |              |
|    approx_kl            | 0.0029365867 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.92        |
|    explained_variance   | 0.937        |
|    learning_rate        | 0.0003       |
|    loss                 | 824          |
|    n_updates            | 2572         |
|    policy_gradient_loss | -0.000257    |
|    value_loss           | 1.01e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 119      |
|    ep_rew_mean     | 84.5     |
| time/              |          |
|    fps             | 1676     |
|    iterations      | 303      |
|    time_elapsed    | 2961     |
|    total_timesteps | 10564352 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 124          |
|    ep_rew_mean          | 109          |
| time/                   |              |
|    fps                  | 1676         |
|    iterations           | 304          |
|    time_elapsed         | 2970         |
|    total_timesteps      | 10580736     |
| train/                  |              |
|    approx_kl            | 0.0029265229 |
|    clip_fraction        | 0.0269       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.87         |
|    learning_rate        | 0.0003       |
|    loss                 | 588          |
|    n_updates            | 2576         |
|    policy_gradient_loss | -0.000661    |
|    value_loss           | 1.12e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 72.7        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 305         |
|    time_elapsed         | 2979        |
|    total_timesteps      | 10597120    |
| train/                  |             |
|    approx_kl            | 0.004211931 |
|    clip_fraction        | 0.0326      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.87       |
|    explained_variance   | 0.578       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.21e+03    |
|    n_updates            | 2580        |
|    policy_gradient_loss | -0.000353   |
|    value_loss           | 7.26e+03    |
-----------------------------------------

Eval num_timesteps=10600000, episode_reward=58.05 +/- 115.14

Episode length: 109.65 +/- 26.40

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 110         |
|    mean_reward          | 58.1        |
| time/                   |             |
|    total_timesteps      | 10600000    |
| train/                  |             |
|    approx_kl            | 0.005277038 |
|    clip_fraction        | 0.0358      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.937      |
|    explained_variance   | 0.801       |
|    learning_rate        | 0.0003      |
|    loss                 | 322         |
|    n_updates            | 2584        |
|    policy_gradient_loss | -0.000794   |
|    value_loss           | 685         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 117      |
|    ep_rew_mean     | 68.3     |
| time/              |          |
|    fps             | 1676     |
|    iterations      | 306      |
|    time_elapsed    | 2990     |
|    total_timesteps | 10613504 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 93.2        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 307         |
|    time_elapsed         | 2999        |
|    total_timesteps      | 10629888    |
| train/                  |             |
|    approx_kl            | 0.004394665 |
|    clip_fraction        | 0.0238      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.901      |
|    explained_variance   | 0.916       |
|    learning_rate        | 0.0003      |
|    loss                 | 932         |
|    n_updates            | 2588        |
|    policy_gradient_loss | -0.00118    |
|    value_loss           | 840         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 119         |
|    ep_rew_mean          | 83.8        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 308         |
|    time_elapsed         | 3008        |
|    total_timesteps      | 10646272    |
| train/                  |             |
|    approx_kl            | 0.006081192 |
|    clip_fraction        | 0.0371      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.882      |
|    explained_variance   | 0.937       |
|    learning_rate        | 0.0003      |
|    loss                 | 432         |
|    n_updates            | 2592        |
|    policy_gradient_loss | -0.00154    |
|    value_loss           | 977         |
-----------------------------------------

Eval num_timesteps=10650000, episode_reward=-46.92 +/- 257.03

Episode length: 112.75 +/- 29.29

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 113         |
|    mean_reward          | -46.9       |
| time/                   |             |
|    total_timesteps      | 10650000    |
| train/                  |             |
|    approx_kl            | 0.003534538 |
|    clip_fraction        | 0.0107      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.9        |
|    explained_variance   | 0.906       |
|    learning_rate        | 0.0003      |
|    loss                 | 610         |
|    n_updates            | 2596        |
|    policy_gradient_loss | -0.000391   |
|    value_loss           | 1.22e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 102      |
| time/              |          |
|    fps             | 1676     |
|    iterations      | 309      |
|    time_elapsed    | 3019     |
|    total_timesteps | 10662656 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 126         |
|    ep_rew_mean          | 73.2        |
| time/                   |             |
|    fps                  | 1676        |
|    iterations           | 310         |
|    time_elapsed         | 3028        |
|    total_timesteps      | 10679040    |
| train/                  |             |
|    approx_kl            | 0.003877801 |
|    clip_fraction        | 0.0392      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.939      |
|    explained_variance   | 0.922       |
|    learning_rate        | 0.0003      |
|    loss                 | 286         |
|    n_updates            | 2600        |
|    policy_gradient_loss | -0.000873   |
|    value_loss           | 1.65e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 92.3         |
| time/                   |              |
|    fps                  | 1677         |
|    iterations           | 311          |
|    time_elapsed         | 3036         |
|    total_timesteps      | 10695424     |
| train/                  |              |
|    approx_kl            | 0.0033175964 |
|    clip_fraction        | 0.0165       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.938       |
|    explained_variance   | 0.93         |
|    learning_rate        | 0.0003       |
|    loss                 | 692          |
|    n_updates            | 2604         |
|    policy_gradient_loss | 0.000368     |
|    value_loss           | 1.65e+03     |
------------------------------------------

Eval num_timesteps=10700000, episode_reward=-15.50 +/- 107.69

Episode length: 113.05 +/- 23.69

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | -15.5        |
| time/                   |              |
|    total_timesteps      | 10700000     |
| train/                  |              |
|    approx_kl            | 0.0038198265 |
|    clip_fraction        | 0.0231       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.945       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.32e+03     |
|    n_updates            | 2608         |
|    policy_gradient_loss | 9.14e-05     |
|    value_loss           | 1.46e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 138      |
|    ep_rew_mean     | 74.8     |
| time/              |          |
|    fps             | 1676     |
|    iterations      | 312      |
|    time_elapsed    | 3048     |
|    total_timesteps | 10711808 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 64.8         |
| time/                   |              |
|    fps                  | 1677         |
|    iterations           | 313          |
|    time_elapsed         | 3057         |
|    total_timesteps      | 10728192     |
| train/                  |              |
|    approx_kl            | 0.0038895963 |
|    clip_fraction        | 0.0289       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.98        |
|    explained_variance   | 0.911        |
|    learning_rate        | 0.0003       |
|    loss                 | 130          |
|    n_updates            | 2612         |
|    policy_gradient_loss | 0.000469     |
|    value_loss           | 1.24e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 135         |
|    ep_rew_mean          | 58.8        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 314         |
|    time_elapsed         | 3066        |
|    total_timesteps      | 10744576    |
| train/                  |             |
|    approx_kl            | 0.003768291 |
|    clip_fraction        | 0.0256      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.968      |
|    explained_variance   | 0.941       |
|    learning_rate        | 0.0003      |
|    loss                 | 705         |
|    n_updates            | 2616        |
|    policy_gradient_loss | -0.00103    |
|    value_loss           | 1.2e+03     |
-----------------------------------------

Eval num_timesteps=10750000, episode_reward=-92.29 +/- 429.05

Episode length: 107.60 +/- 35.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | -92.3        |
| time/                   |              |
|    total_timesteps      | 10750000     |
| train/                  |              |
|    approx_kl            | 0.0049427934 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.966       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 322          |
|    n_updates            | 2620         |
|    policy_gradient_loss | -0.000254    |
|    value_loss           | 748          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 140      |
|    ep_rew_mean     | 83.3     |
| time/              |          |
|    fps             | 1677     |
|    iterations      | 315      |
|    time_elapsed    | 3077     |
|    total_timesteps | 10760960 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 59.6         |
| time/                   |              |
|    fps                  | 1677         |
|    iterations           | 316          |
|    time_elapsed         | 3086         |
|    total_timesteps      | 10777344     |
| train/                  |              |
|    approx_kl            | 0.0033166697 |
|    clip_fraction        | 0.0125       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.992       |
|    explained_variance   | 0.949        |
|    learning_rate        | 0.0003       |
|    loss                 | 427          |
|    n_updates            | 2624         |
|    policy_gradient_loss | 0.000763     |
|    value_loss           | 1.64e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 146         |
|    ep_rew_mean          | 78.5        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 317         |
|    time_elapsed         | 3095        |
|    total_timesteps      | 10793728    |
| train/                  |             |
|    approx_kl            | 0.004797724 |
|    clip_fraction        | 0.053       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.929      |
|    explained_variance   | 0.946       |
|    learning_rate        | 0.0003      |
|    loss                 | 118         |
|    n_updates            | 2628        |
|    policy_gradient_loss | -0.000885   |
|    value_loss           | 418         |
-----------------------------------------

Eval num_timesteps=10800000, episode_reward=-38.91 +/- 166.75

Episode length: 116.65 +/- 25.57

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | -38.9        |
| time/                   |              |
|    total_timesteps      | 10800000     |
| train/                  |              |
|    approx_kl            | 0.0032347268 |
|    clip_fraction        | 0.0259       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.947       |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 279          |
|    n_updates            | 2632         |
|    policy_gradient_loss | -0.00101     |
|    value_loss           | 617          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 159      |
|    ep_rew_mean     | 82.8     |
| time/              |          |
|    fps             | 1677     |
|    iterations      | 318      |
|    time_elapsed    | 3106     |
|    total_timesteps | 10810112 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 154          |
|    ep_rew_mean          | 77.2         |
| time/                   |              |
|    fps                  | 1677         |
|    iterations           | 319          |
|    time_elapsed         | 3115         |
|    total_timesteps      | 10826496     |
| train/                  |              |
|    approx_kl            | 0.0049076118 |
|    clip_fraction        | 0.0277       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.983       |
|    explained_variance   | 0.947        |
|    learning_rate        | 0.0003       |
|    loss                 | 353          |
|    n_updates            | 2636         |
|    policy_gradient_loss | -0.000116    |
|    value_loss           | 1.3e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | 73.5        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 320         |
|    time_elapsed         | 3124        |
|    total_timesteps      | 10842880    |
| train/                  |             |
|    approx_kl            | 0.004537277 |
|    clip_fraction        | 0.0329      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.951      |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | 357         |
|    n_updates            | 2640        |
|    policy_gradient_loss | -0.000553   |
|    value_loss           | 2.11e+03    |
-----------------------------------------

Eval num_timesteps=10850000, episode_reward=-82.46 +/- 175.09

Episode length: 106.20 +/- 23.74

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | -82.5       |
| time/                   |             |
|    total_timesteps      | 10850000    |
| train/                  |             |
|    approx_kl            | 0.003063975 |
|    clip_fraction        | 0.0242      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.913      |
|    explained_variance   | 0.894       |
|    learning_rate        | 0.0003      |
|    loss                 | 432         |
|    n_updates            | 2644        |
|    policy_gradient_loss | 8.82e-05    |
|    value_loss           | 713         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 126      |
|    ep_rew_mean     | 70.3     |
| time/              |          |
|    fps             | 1677     |
|    iterations      | 321      |
|    time_elapsed    | 3135     |
|    total_timesteps | 10859264 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 140         |
|    ep_rew_mean          | 81.5        |
| time/                   |             |
|    fps                  | 1677        |
|    iterations           | 322         |
|    time_elapsed         | 3144        |
|    total_timesteps      | 10875648    |
| train/                  |             |
|    approx_kl            | 0.002809174 |
|    clip_fraction        | 0.0335      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.88       |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | 612         |
|    n_updates            | 2648        |
|    policy_gradient_loss | -0.000224   |
|    value_loss           | 594         |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 139        |
|    ep_rew_mean          | 84.7       |
| time/                   |            |
|    fps                  | 1678       |
|    iterations           | 323        |
|    time_elapsed         | 3153       |
|    total_timesteps      | 10892032   |
| train/                  |            |
|    approx_kl            | 0.00400768 |
|    clip_fraction        | 0.0213     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.964     |
|    explained_variance   | 0.966      |
|    learning_rate        | 0.0003     |
|    loss                 | 264        |
|    n_updates            | 2652       |
|    policy_gradient_loss | 0.000431   |
|    value_loss           | 1.12e+03   |
----------------------------------------

Eval num_timesteps=10900000, episode_reward=-47.33 +/- 128.90

Episode length: 107.90 +/- 31.79

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 108          |
|    mean_reward          | -47.3        |
| time/                   |              |
|    total_timesteps      | 10900000     |
| train/                  |              |
|    approx_kl            | 0.0051473174 |
|    clip_fraction        | 0.0359       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.923       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 194          |
|    n_updates            | 2656         |
|    policy_gradient_loss | -0.00165     |
|    value_loss           | 1.04e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_10900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 151      |
|    ep_rew_mean     | 86.3     |
| time/              |          |
|    fps             | 1677     |
|    iterations      | 324      |
|    time_elapsed    | 3164     |
|    total_timesteps | 10908416 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 72.9        |
| time/                   |             |
|    fps                  | 1678        |
|    iterations           | 325         |
|    time_elapsed         | 3173        |
|    total_timesteps      | 10924800    |
| train/                  |             |
|    approx_kl            | 0.004669062 |
|    clip_fraction        | 0.0237      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.921      |
|    explained_variance   | 0.954       |
|    learning_rate        | 0.0003      |
|    loss                 | 168         |
|    n_updates            | 2660        |
|    policy_gradient_loss | -0.000613   |
|    value_loss           | 931         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 166          |
|    ep_rew_mean          | 83.7         |
| time/                   |              |
|    fps                  | 1678         |
|    iterations           | 326          |
|    time_elapsed         | 3182         |
|    total_timesteps      | 10941184     |
| train/                  |              |
|    approx_kl            | 0.0040033003 |
|    clip_fraction        | 0.0273       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.954       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 272          |
|    n_updates            | 2664         |
|    policy_gradient_loss | -0.000591    |
|    value_loss           | 726          |
------------------------------------------

Eval num_timesteps=10950000, episode_reward=-134.54 +/- 498.81

Episode length: 121.85 +/- 41.17

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 122        |
|    mean_reward          | -135       |
| time/                   |            |
|    total_timesteps      | 10950000   |
| train/                  |            |
|    approx_kl            | 0.00537431 |
|    clip_fraction        | 0.0296     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.02      |
|    explained_variance   | 0.979      |
|    learning_rate        | 0.0003     |
|    loss                 | 511        |
|    n_updates            | 2668       |
|    policy_gradient_loss | -0.000273  |
|    value_loss           | 1.65e+03   |
----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 179      |
|    ep_rew_mean     | 89.4     |
| time/              |          |
|    fps             | 1677     |
|    iterations      | 327      |
|    time_elapsed    | 3193     |
|    total_timesteps | 10957568 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 77.5         |
| time/                   |              |
|    fps                  | 1677         |
|    iterations           | 328          |
|    time_elapsed         | 3203         |
|    total_timesteps      | 10973952     |
| train/                  |              |
|    approx_kl            | 0.0038406707 |
|    clip_fraction        | 0.0257       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.984       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 965          |
|    n_updates            | 2672         |
|    policy_gradient_loss | 0.000114     |
|    value_loss           | 1.76e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 138         |
|    ep_rew_mean          | 75.1        |
| time/                   |             |
|    fps                  | 1678        |
|    iterations           | 329         |
|    time_elapsed         | 3211        |
|    total_timesteps      | 10990336    |
| train/                  |             |
|    approx_kl            | 0.004052705 |
|    clip_fraction        | 0.0332      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.965      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 146         |
|    n_updates            | 2676        |
|    policy_gradient_loss | 0.000391    |
|    value_loss           | 606         |
-----------------------------------------

Eval num_timesteps=11000000, episode_reward=-31.98 +/- 190.66

Episode length: 119.15 +/- 31.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | -32          |
| time/                   |              |
|    total_timesteps      | 11000000     |
| train/                  |              |
|    approx_kl            | 0.0028940283 |
|    clip_fraction        | 0.0339       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.934       |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 94.2         |
|    n_updates            | 2680         |
|    policy_gradient_loss | 0.000261     |
|    value_loss           | 830          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 11,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 151      |
|    ep_rew_mean     | 90.2     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 330      |
|    time_elapsed    | 3228     |
|    total_timesteps | 11006720 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 144          |
|    ep_rew_mean          | 78.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 331          |
|    time_elapsed         | 3237         |
|    total_timesteps      | 11023104     |
| train/                  |              |
|    approx_kl            | 0.0038903458 |
|    clip_fraction        | 0.0254       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.925       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 249          |
|    n_updates            | 2684         |
|    policy_gradient_loss | -0.000865    |
|    value_loss           | 1.46e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 124         |
|    ep_rew_mean          | 71.7        |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 332         |
|    time_elapsed         | 3246        |
|    total_timesteps      | 11039488    |
| train/                  |             |
|    approx_kl            | 0.004002322 |
|    clip_fraction        | 0.0261      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.886      |
|    explained_variance   | 0.907       |
|    learning_rate        | 0.0003      |
|    loss                 | 308         |
|    n_updates            | 2688        |
|    policy_gradient_loss | -0.000419   |
|    value_loss           | 1.17e+03    |
-----------------------------------------

Eval num_timesteps=11050000, episode_reward=-122.80 +/- 309.06

Episode length: 104.30 +/- 23.32

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | -123        |
| time/                   |             |
|    total_timesteps      | 11050000    |
| train/                  |             |
|    approx_kl            | 0.004132756 |
|    clip_fraction        | 0.0345      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.853      |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | 129         |
|    n_updates            | 2692        |
|    policy_gradient_loss | -0.00165    |
|    value_loss           | 1.01e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 94.9     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 333      |
|    time_elapsed    | 3258     |
|    total_timesteps | 11055872 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 143          |
|    ep_rew_mean          | 89.5         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 334          |
|    time_elapsed         | 3267         |
|    total_timesteps      | 11072256     |
| train/                  |              |
|    approx_kl            | 0.0032954586 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.93        |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 567          |
|    n_updates            | 2696         |
|    policy_gradient_loss | -3.62e-05    |
|    value_loss           | 1.68e+03     |
------------------------------------------

Eval num_timesteps=11100000, episode_reward=-150.84 +/- 244.76

Episode length: 112.20 +/- 34.09

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -151         |
| time/                   |              |
|    total_timesteps      | 11100000     |
| train/                  |              |
|    approx_kl            | 0.0046787555 |
|    clip_fraction        | 0.0243       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 347          |
|    n_updates            | 2704         |
|    policy_gradient_loss | -0.00101     |
|    value_loss           | 1.18e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 91.1     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 336      |
|    time_elapsed    | 3287     |
|    total_timesteps | 11105024 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 74.8         |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 337          |
|    time_elapsed         | 3297         |
|    total_timesteps      | 11121408     |
| train/                  |              |
|    approx_kl            | 0.0043966724 |
|    clip_fraction        | 0.0278       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.94        |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.6e+03      |
|    n_updates            | 2708         |
|    policy_gradient_loss | -0.000489    |
|    value_loss           | 1.45e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 91.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 338          |
|    time_elapsed         | 3305         |
|    total_timesteps      | 11137792     |
| train/                  |              |
|    approx_kl            | 0.0030108844 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.874       |
|    explained_variance   | 0.951        |
|    learning_rate        | 0.0003       |
|    loss                 | 320          |
|    n_updates            | 2712         |
|    policy_gradient_loss | -0.000585    |
|    value_loss           | 974          |
------------------------------------------

Eval num_timesteps=11150000, episode_reward=-9.03 +/- 85.45

Episode length: 90.35 +/- 18.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 90.3         |
|    mean_reward          | -9.03        |
| time/                   |              |
|    total_timesteps      | 11150000     |
| train/                  |              |
|    approx_kl            | 0.0028666875 |
|    clip_fraction        | 0.0158       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.952        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45e+03     |
|    n_updates            | 2716         |
|    policy_gradient_loss | -0.000176    |
|    value_loss           | 1.46e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 85.2     |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 339      |
|    time_elapsed    | 3316     |
|    total_timesteps | 11154176 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 96.3        |
| time/                   |             |
|    fps                  | 1674        |
|    iterations           | 340         |
|    time_elapsed         | 3325        |
|    total_timesteps      | 11170560    |
| train/                  |             |
|    approx_kl            | 0.003993827 |
|    clip_fraction        | 0.0258      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.894      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 168         |
|    n_updates            | 2720        |
|    policy_gradient_loss | -0.000847   |
|    value_loss           | 1.29e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 74.4         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 341          |
|    time_elapsed         | 3335         |
|    total_timesteps      | 11186944     |
| train/                  |              |
|    approx_kl            | 0.0020811148 |
|    clip_fraction        | 0.00853      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.889       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 309          |
|    n_updates            | 2724         |
|    policy_gradient_loss | 0.000463     |
|    value_loss           | 1.5e+03      |
------------------------------------------

Eval num_timesteps=11200000, episode_reward=-106.87 +/- 228.15

Episode length: 102.30 +/- 19.80

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 102          |
|    mean_reward          | -107         |
| time/                   |              |
|    total_timesteps      | 11200000     |
| train/                  |              |
|    approx_kl            | 0.0042454833 |
|    clip_fraction        | 0.0258       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 131          |
|    n_updates            | 2728         |
|    policy_gradient_loss | -0.000748    |
|    value_loss           | 1.32e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 132      |
|    ep_rew_mean     | 93.1     |
| time/              |          |
|    fps             | 1675     |
|    iterations      | 342      |
|    time_elapsed    | 3345     |
|    total_timesteps | 11203328 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 148          |
|    ep_rew_mean          | 97.3         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 343          |
|    time_elapsed         | 3354         |
|    total_timesteps      | 11219712     |
| train/                  |              |
|    approx_kl            | 0.0044206805 |
|    clip_fraction        | 0.0237       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.894       |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 905          |
|    n_updates            | 2732         |
|    policy_gradient_loss | -0.000995    |
|    value_loss           | 1.58e+03     |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 133        |
|    ep_rew_mean          | 94         |
| time/                   |            |
|    fps                  | 1675       |
|    iterations           | 344        |
|    time_elapsed         | 3363       |
|    total_timesteps      | 11236096   |
| train/                  |            |
|    approx_kl            | 0.00247079 |
|    clip_fraction        | 0.0122     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.934     |
|    explained_variance   | 0.961      |
|    learning_rate        | 0.0003     |
|    loss                 | 739        |
|    n_updates            | 2736       |
|    policy_gradient_loss | 0.000535   |
|    value_loss           | 1.9e+03    |
----------------------------------------

Eval num_timesteps=11250000, episode_reward=-22.10 +/- 388.03

Episode length: 115.20 +/- 44.29

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 115          |
|    mean_reward          | -22.1        |
| time/                   |              |
|    total_timesteps      | 11250000     |
| train/                  |              |
|    approx_kl            | 0.0034179445 |
|    clip_fraction        | 0.0343       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 231          |
|    n_updates            | 2740         |
|    policy_gradient_loss | -0.000685    |
|    value_loss           | 1.19e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 90       |
| time/              |          |
|    fps             | 1674     |
|    iterations      | 345      |
|    time_elapsed    | 3374     |
|    total_timesteps | 11252480 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 96.7        |
| time/                   |             |
|    fps                  | 1675        |
|    iterations           | 346         |
|    time_elapsed         | 3383        |
|    total_timesteps      | 11268864    |
| train/                  |             |
|    approx_kl            | 0.004431219 |
|    clip_fraction        | 0.0238      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.896      |
|    explained_variance   | 0.979       |
|    learning_rate        | 0.0003      |
|    loss                 | 901         |
|    n_updates            | 2744        |
|    policy_gradient_loss | -0.00158    |
|    value_loss           | 1.06e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 145          |
|    ep_rew_mean          | 97.8         |
| time/                   |              |
|    fps                  | 1675         |
|    iterations           | 347          |
|    time_elapsed         | 3392         |
|    total_timesteps      | 11285248     |
| train/                  |              |
|    approx_kl            | 0.0038574175 |
|    clip_fraction        | 0.0227       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.948       |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 974          |
|    n_updates            | 2748         |
|    policy_gradient_loss | -0.000651    |
|    value_loss           | 1.89e+03     |
------------------------------------------

Eval num_timesteps=11300000, episode_reward=-213.66 +/- 340.85

Episode length: 118.30 +/- 31.95

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 118          |
|    mean_reward          | -214         |
| time/                   |              |
|    total_timesteps      | 11300000     |
| train/                  |              |
|    approx_kl            | 0.0057491325 |
|    clip_fraction        | 0.0383       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.995       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 495          |
|    n_updates            | 2752         |
|    policy_gradient_loss | -0.0011      |
|    value_loss           | 2.08e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 81.2     |
| time/              |          |
|    fps             | 1675     |
|    iterations      | 348      |
|    time_elapsed    | 3403     |
|    total_timesteps | 11301632 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 147          |
|    ep_rew_mean          | 100          |
| time/                   |              |
|    fps                  | 1674         |
|    iterations           | 349          |
|    time_elapsed         | 3414         |
|    total_timesteps      | 11318016     |
| train/                  |              |
|    approx_kl            | 0.0038170053 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.959       |
|    explained_variance   | 0.945        |
|    learning_rate        | 0.0003       |
|    loss                 | 428          |
|    n_updates            | 2756         |
|    policy_gradient_loss | 0.000104     |
|    value_loss           | 1.44e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 116          |
|    ep_rew_mean          | 76.8         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 350          |
|    time_elapsed         | 3425         |
|    total_timesteps      | 11334400     |
| train/                  |              |
|    approx_kl            | 0.0020500799 |
|    clip_fraction        | 0.00925      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.928       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 922          |
|    n_updates            | 2760         |
|    policy_gradient_loss | 8.38e-05     |
|    value_loss           | 1.38e+03     |
------------------------------------------

Eval num_timesteps=11350000, episode_reward=-134.38 +/- 308.02

Episode length: 104.15 +/- 24.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 104         |
|    mean_reward          | -134        |
| time/                   |             |
|    total_timesteps      | 11350000    |
| train/                  |             |
|    approx_kl            | 0.005254744 |
|    clip_fraction        | 0.0295      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.908      |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | 342         |
|    n_updates            | 2764        |
|    policy_gradient_loss | -0.000688   |
|    value_loss           | 970         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 162      |
|    ep_rew_mean     | 90.7     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 351      |
|    time_elapsed    | 3437     |
|    total_timesteps | 11350784 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 159          |
|    ep_rew_mean          | 92.4         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 352          |
|    time_elapsed         | 3446         |
|    total_timesteps      | 11367168     |
| train/                  |              |
|    approx_kl            | 0.0044388743 |
|    clip_fraction        | 0.0204       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.918       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.9e+03      |
|    n_updates            | 2768         |
|    policy_gradient_loss | -0.000418    |
|    value_loss           | 1.51e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 141         |
|    ep_rew_mean          | 91.8        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 353         |
|    time_elapsed         | 3455        |
|    total_timesteps      | 11383552    |
| train/                  |             |
|    approx_kl            | 0.002703941 |
|    clip_fraction        | 0.0153      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.941      |
|    explained_variance   | 0.968       |
|    learning_rate        | 0.0003      |
|    loss                 | 708         |
|    n_updates            | 2772        |
|    policy_gradient_loss | 0.00071     |
|    value_loss           | 1.8e+03     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 139         |
|    ep_rew_mean          | 84.8        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 354         |
|    time_elapsed         | 3464        |
|    total_timesteps      | 11399936    |
| train/                  |             |
|    approx_kl            | 0.002640969 |
|    clip_fraction        | 0.0142      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.864      |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | 589         |
|    n_updates            | 2776        |
|    policy_gradient_loss | -0.000586   |
|    value_loss           | 1.41e+03    |
-----------------------------------------

Eval num_timesteps=11400000, episode_reward=-81.43 +/- 289.88

Episode length: 99.85 +/- 24.17

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.8        |
|    mean_reward          | -81.4       |
| time/                   |             |
|    total_timesteps      | 11400000    |
| train/                  |             |
|    approx_kl            | 0.004380691 |
|    clip_fraction        | 0.0244      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.852      |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | 643         |
|    n_updates            | 2780        |
|    policy_gradient_loss | -0.000558   |
|    value_loss           | 1.57e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 67.7     |
| time/              |          |
|    fps             | 1673     |
|    iterations      | 355      |
|    time_elapsed    | 3475     |
|    total_timesteps | 11416320 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 138         |
|    ep_rew_mean          | 86.5        |
| time/                   |             |
|    fps                  | 1673        |
|    iterations           | 356         |
|    time_elapsed         | 3485        |
|    total_timesteps      | 11432704    |
| train/                  |             |
|    approx_kl            | 0.003933643 |
|    clip_fraction        | 0.0417      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.876      |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | 432         |
|    n_updates            | 2784        |
|    policy_gradient_loss | -0.000643   |
|    value_loss           | 1.46e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 155          |
|    ep_rew_mean          | 93.5         |
| time/                   |              |
|    fps                  | 1673         |
|    iterations           | 357          |
|    time_elapsed         | 3494         |
|    total_timesteps      | 11449088     |
| train/                  |              |
|    approx_kl            | 0.0042244904 |
|    clip_fraction        | 0.0256       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.904       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 968          |
|    n_updates            | 2788         |
|    policy_gradient_loss | -0.00133     |
|    value_loss           | 2.03e+03     |
------------------------------------------

Eval num_timesteps=11450000, episode_reward=-86.94 +/- 192.43

Episode length: 107.00 +/- 24.91

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 107         |
|    mean_reward          | -86.9       |
| time/                   |             |
|    total_timesteps      | 11450000    |
| train/                  |             |
|    approx_kl            | 0.003935008 |
|    clip_fraction        | 0.0179      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.936      |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | 683         |
|    n_updates            | 2792        |
|    policy_gradient_loss | -0.000348   |
|    value_loss           | 1.91e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 72.6     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 358      |
|    time_elapsed    | 3506     |
|    total_timesteps | 11465472 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 136         |
|    ep_rew_mean          | 91.9        |
| time/                   |             |
|    fps                  | 1672        |
|    iterations           | 359         |
|    time_elapsed         | 3516        |
|    total_timesteps      | 11481856    |
| train/                  |             |
|    approx_kl            | 0.002937797 |
|    clip_fraction        | 0.015       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.845      |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | 324         |
|    n_updates            | 2796        |
|    policy_gradient_loss | 0.000365    |
|    value_loss           | 915         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 90.6         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 360          |
|    time_elapsed         | 3526         |
|    total_timesteps      | 11498240     |
| train/                  |              |
|    approx_kl            | 0.0027580126 |
|    clip_fraction        | 0.0175       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.903       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 569          |
|    n_updates            | 2800         |
|    policy_gradient_loss | -0.000268    |
|    value_loss           | 1.61e+03     |
------------------------------------------

Eval num_timesteps=11500000, episode_reward=-45.48 +/- 432.65

Episode length: 100.55 +/- 22.79

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 101          |
|    mean_reward          | -45.5        |
| time/                   |              |
|    total_timesteps      | 11500000     |
| train/                  |              |
|    approx_kl            | 0.0042732237 |
|    clip_fraction        | 0.0238       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.911       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 287          |
|    n_updates            | 2804         |
|    policy_gradient_loss | 0.000203     |
|    value_loss           | 1.5e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 133      |
|    ep_rew_mean     | 80.7     |
| time/              |          |
|    fps             | 1672     |
|    iterations      | 361      |
|    time_elapsed    | 3537     |
|    total_timesteps | 11514624 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 119          |
|    ep_rew_mean          | 83.7         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 362          |
|    time_elapsed         | 3546         |
|    total_timesteps      | 11531008     |
| train/                  |              |
|    approx_kl            | 0.0033797193 |
|    clip_fraction        | 0.0175       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 133          |
|    n_updates            | 2808         |
|    policy_gradient_loss | -0.000441    |
|    value_loss           | 981          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 84           |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 363          |
|    time_elapsed         | 3556         |
|    total_timesteps      | 11547392     |
| train/                  |              |
|    approx_kl            | 0.0040166825 |
|    clip_fraction        | 0.035        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 170          |
|    n_updates            | 2812         |
|    policy_gradient_loss | -0.000718    |
|    value_loss           | 839          |
------------------------------------------

Eval num_timesteps=11550000, episode_reward=-21.38 +/- 225.91

Episode length: 105.40 +/- 25.88

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 105        |
|    mean_reward          | -21.4      |
| time/                   |            |
|    total_timesteps      | 11550000   |
| train/                  |            |
|    approx_kl            | 0.00294937 |
|    clip_fraction        | 0.0168     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.936     |
|    explained_variance   | 0.948      |
|    learning_rate        | 0.0003     |
|    loss                 | 841        |
|    n_updates            | 2816       |
|    policy_gradient_loss | 0.000106   |
|    value_loss           | 2.49e+03   |
----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 94.3     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 364      |
|    time_elapsed    | 3567     |
|    total_timesteps | 11563776 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 71.5         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 365          |
|    time_elapsed         | 3575         |
|    total_timesteps      | 11580160     |
| train/                  |              |
|    approx_kl            | 0.0044058645 |
|    clip_fraction        | 0.0327       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.919       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 378          |
|    n_updates            | 2820         |
|    policy_gradient_loss | -0.000592    |
|    value_loss           | 1.2e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 125          |
|    ep_rew_mean          | 72.9         |
| time/                   |              |
|    fps                  | 1672         |
|    iterations           | 366          |
|    time_elapsed         | 3585         |
|    total_timesteps      | 11596544     |
| train/                  |              |
|    approx_kl            | 0.0042694868 |
|    clip_fraction        | 0.035        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.884       |
|    explained_variance   | 0.876        |
|    learning_rate        | 0.0003       |
|    loss                 | 351          |
|    n_updates            | 2824         |
|    policy_gradient_loss | -0.00224     |
|    value_loss           | 917          |
------------------------------------------

Eval num_timesteps=11600000, episode_reward=-107.47 +/- 330.08

Episode length: 105.50 +/- 26.52

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 106          |
|    mean_reward          | -107         |
| time/                   |              |
|    total_timesteps      | 11600000     |
| train/                  |              |
|    approx_kl            | 0.0046626823 |
|    clip_fraction        | 0.0355       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.936       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 2828         |
|    policy_gradient_loss | -0.000671    |
|    value_loss           | 1.01e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 86.9     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 367      |
|    time_elapsed    | 3596     |
|    total_timesteps | 11612928 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 114          |
|    ep_rew_mean          | 65.9         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 368          |
|    time_elapsed         | 3607         |
|    total_timesteps      | 11629312     |
| train/                  |              |
|    approx_kl            | 0.0046842033 |
|    clip_fraction        | 0.0252       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.934       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 197          |
|    n_updates            | 2832         |
|    policy_gradient_loss | 0.00015      |
|    value_loss           | 1e+03        |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 132         |
|    ep_rew_mean          | 92.8        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 369         |
|    time_elapsed         | 3616        |
|    total_timesteps      | 11645696    |
| train/                  |             |
|    approx_kl            | 0.004108279 |
|    clip_fraction        | 0.0315      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.912      |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | 422         |
|    n_updates            | 2836        |
|    policy_gradient_loss | -0.00118    |
|    value_loss           | 596         |
-----------------------------------------

Eval num_timesteps=11650000, episode_reward=14.70 +/- 123.95

Episode length: 111.05 +/- 30.26

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 14.7         |
| time/                   |              |
|    total_timesteps      | 11650000     |
| train/                  |              |
|    approx_kl            | 0.0033690415 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.955       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 532          |
|    n_updates            | 2840         |
|    policy_gradient_loss | -0.000605    |
|    value_loss           | 943          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 151      |
|    ep_rew_mean     | 83.7     |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 370      |
|    time_elapsed    | 3627     |
|    total_timesteps | 11662080 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 130         |
|    ep_rew_mean          | 66.7        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 371         |
|    time_elapsed         | 3637        |
|    total_timesteps      | 11678464    |
| train/                  |             |
|    approx_kl            | 0.004584508 |
|    clip_fraction        | 0.0268      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.99       |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 468         |
|    n_updates            | 2844        |
|    policy_gradient_loss | 0.000658    |
|    value_loss           | 949         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 130          |
|    ep_rew_mean          | 90.9         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 372          |
|    time_elapsed         | 3646         |
|    total_timesteps      | 11694848     |
| train/                  |              |
|    approx_kl            | 0.0048654443 |
|    clip_fraction        | 0.0418       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.92        |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 134          |
|    n_updates            | 2848         |
|    policy_gradient_loss | -0.00123     |
|    value_loss           | 550          |
------------------------------------------

Eval num_timesteps=11700000, episode_reward=-72.78 +/- 203.19

Episode length: 107.10 +/- 25.17

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -72.8        |
| time/                   |              |
|    total_timesteps      | 11700000     |
| train/                  |              |
|    approx_kl            | 0.0029638284 |
|    clip_fraction        | 0.0286       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.35e+03     |
|    n_updates            | 2852         |
|    policy_gradient_loss | -0.000827    |
|    value_loss           | 1.12e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 136      |
|    ep_rew_mean     | 101      |
| time/              |          |
|    fps             | 1671     |
|    iterations      | 373      |
|    time_elapsed    | 3656     |
|    total_timesteps | 11711232 |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 148        |
|    ep_rew_mean          | 79         |
| time/                   |            |
|    fps                  | 1671       |
|    iterations           | 374        |
|    time_elapsed         | 3666       |
|    total_timesteps      | 11727616   |
| train/                  |            |
|    approx_kl            | 0.00457192 |
|    clip_fraction        | 0.0278     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.92      |
|    explained_variance   | 0.954      |
|    learning_rate        | 0.0003     |
|    loss                 | 350        |
|    n_updates            | 2856       |
|    policy_gradient_loss | -0.000804  |
|    value_loss           | 1.21e+03   |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 80.4         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 375          |
|    time_elapsed         | 3675         |
|    total_timesteps      | 11744000     |
| train/                  |              |
|    approx_kl            | 0.0029071304 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.953       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 321          |
|    n_updates            | 2860         |
|    policy_gradient_loss | -3.05e-05    |
|    value_loss           | 1.06e+03     |
------------------------------------------

Eval num_timesteps=11750000, episode_reward=110.78 +/- 252.86

Episode length: 146.20 +/- 143.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 146          |
|    mean_reward          | 111          |
| time/                   |              |
|    total_timesteps      | 11750000     |
| train/                  |              |
|    approx_kl            | 0.0029205563 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.927       |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 434          |
|    n_updates            | 2864         |
|    policy_gradient_loss | -0.000114    |
|    value_loss           | 803          |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 144      |
|    ep_rew_mean     | 75.5     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 376      |
|    time_elapsed    | 3687     |
|    total_timesteps | 11760384 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 163         |
|    ep_rew_mean          | 90.3        |
| time/                   |             |
|    fps                  | 1671        |
|    iterations           | 377         |
|    time_elapsed         | 3696        |
|    total_timesteps      | 11776768    |
| train/                  |             |
|    approx_kl            | 0.003207519 |
|    clip_fraction        | 0.0202      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.965      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.55e+03    |
|    n_updates            | 2868        |
|    policy_gradient_loss | 0.000625    |
|    value_loss           | 1.02e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 157          |
|    ep_rew_mean          | 90.2         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 378          |
|    time_elapsed         | 3705         |
|    total_timesteps      | 11793152     |
| train/                  |              |
|    approx_kl            | 0.0046095774 |
|    clip_fraction        | 0.0212       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 726          |
|    n_updates            | 2872         |
|    policy_gradient_loss | -0.000415    |
|    value_loss           | 1.47e+03     |
------------------------------------------

Eval num_timesteps=11800000, episode_reward=-41.90 +/- 131.52

Episode length: 112.50 +/- 34.78

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 112         |
|    mean_reward          | -41.9       |
| time/                   |             |
|    total_timesteps      | 11800000    |
| train/                  |             |
|    approx_kl            | 0.003499622 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.904      |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.23e+03    |
|    n_updates            | 2876        |
|    policy_gradient_loss | -0.000365   |
|    value_loss           | 1.16e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 84.8     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 379      |
|    time_elapsed    | 3716     |
|    total_timesteps | 11809536 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 123         |
|    ep_rew_mean          | 74.7        |
| time/                   |             |
|    fps                  | 1670        |
|    iterations           | 380         |
|    time_elapsed         | 3726        |
|    total_timesteps      | 11825920    |
| train/                  |             |
|    approx_kl            | 0.004840852 |
|    clip_fraction        | 0.0412      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.873      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 606         |
|    n_updates            | 2880        |
|    policy_gradient_loss | -0.00105    |
|    value_loss           | 712         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 89.4         |
| time/                   |              |
|    fps                  | 1671         |
|    iterations           | 381          |
|    time_elapsed         | 3734         |
|    total_timesteps      | 11842304     |
| train/                  |              |
|    approx_kl            | 0.0041187955 |
|    clip_fraction        | 0.0306       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.879       |
|    explained_variance   | 0.883        |
|    learning_rate        | 0.0003       |
|    loss                 | 250          |
|    n_updates            | 2884         |
|    policy_gradient_loss | -0.00159     |
|    value_loss           | 739          |
------------------------------------------

Eval num_timesteps=11850000, episode_reward=32.40 +/- 119.66

Episode length: 99.05 +/- 23.36

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99          |
|    mean_reward          | 32.4        |
| time/                   |             |
|    total_timesteps      | 11850000    |
| train/                  |             |
|    approx_kl            | 0.003752927 |
|    clip_fraction        | 0.0239      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.961      |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | 388         |
|    n_updates            | 2888        |
|    policy_gradient_loss | 3.1e-05     |
|    value_loss           | 1.2e+03     |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 153      |
|    ep_rew_mean     | 93.9     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 382      |
|    time_elapsed    | 3746     |
|    total_timesteps | 11858688 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 94.4         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 383          |
|    time_elapsed         | 3756         |
|    total_timesteps      | 11875072     |
| train/                  |              |
|    approx_kl            | 0.0044679437 |
|    clip_fraction        | 0.03         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 562          |
|    n_updates            | 2892         |
|    policy_gradient_loss | -0.00142     |
|    value_loss           | 1.17e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 146          |
|    ep_rew_mean          | 91.3         |
| time/                   |              |
|    fps                  | 1670         |
|    iterations           | 384          |
|    time_elapsed         | 3765         |
|    total_timesteps      | 11891456     |
| train/                  |              |
|    approx_kl            | 0.0044668145 |
|    clip_fraction        | 0.0306       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.924        |
|    learning_rate        | 0.0003       |
|    loss                 | 393          |
|    n_updates            | 2896         |
|    policy_gradient_loss | -0.00087     |
|    value_loss           | 909          |
------------------------------------------

Eval num_timesteps=11900000, episode_reward=-24.68 +/- 169.86

Episode length: 108.90 +/- 25.67

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | -24.7        |
| time/                   |              |
|    total_timesteps      | 11900000     |
| train/                  |              |
|    approx_kl            | 0.0052074334 |
|    clip_fraction        | 0.0441       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.91        |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 400          |
|    n_updates            | 2900         |
|    policy_gradient_loss | -0.00292     |
|    value_loss           | 1.24e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_11900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 96.8     |
| time/              |          |
|    fps             | 1670     |
|    iterations      | 385      |
|    time_elapsed    | 3776     |
|    total_timesteps | 11907840 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 66.6         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 386          |
|    time_elapsed         | 3787         |
|    total_timesteps      | 11924224     |
| train/                  |              |
|    approx_kl            | 0.0030520689 |
|    clip_fraction        | 0.0266       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.907       |
|    explained_variance   | 0.959        |
|    learning_rate        | 0.0003       |
|    loss                 | 421          |
|    n_updates            | 2904         |
|    policy_gradient_loss | -0.000714    |
|    value_loss           | 1.2e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 142          |
|    ep_rew_mean          | 75.3         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 387          |
|    time_elapsed         | 3797         |
|    total_timesteps      | 11940608     |
| train/                  |              |
|    approx_kl            | 0.0031396868 |
|    clip_fraction        | 0.0239       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.927       |
|    explained_variance   | 0.933        |
|    learning_rate        | 0.0003       |
|    loss                 | 143          |
|    n_updates            | 2908         |
|    policy_gradient_loss | 0.000107     |
|    value_loss           | 1.06e+03     |
------------------------------------------

Eval num_timesteps=11950000, episode_reward=8.10 +/- 75.18

Episode length: 119.00 +/- 39.50

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | 8.1          |
| time/                   |              |
|    total_timesteps      | 11950000     |
| train/                  |              |
|    approx_kl            | 0.0058405558 |
|    clip_fraction        | 0.0516       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.962       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03e+03     |
|    n_updates            | 2912         |
|    policy_gradient_loss | -0.000311    |
|    value_loss           | 2.05e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 161      |
|    ep_rew_mean     | 89.1     |
| time/              |          |
|    fps             | 1668     |
|    iterations      | 388      |
|    time_elapsed    | 3809     |
|    total_timesteps | 11956992 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 143          |
|    ep_rew_mean          | 81.1         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 389          |
|    time_elapsed         | 3817         |
|    total_timesteps      | 11973376     |
| train/                  |              |
|    approx_kl            | 0.0059721707 |
|    clip_fraction        | 0.0572       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.976       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 405          |
|    n_updates            | 2916         |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 1.15e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 147          |
|    ep_rew_mean          | 85.5         |
| time/                   |              |
|    fps                  | 1669         |
|    iterations           | 390          |
|    time_elapsed         | 3827         |
|    total_timesteps      | 11989760     |
| train/                  |              |
|    approx_kl            | 0.0051484164 |
|    clip_fraction        | 0.0317       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.922       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 383          |
|    n_updates            | 2920         |
|    policy_gradient_loss | 0.0005       |
|    value_loss           | 1.15e+03     |
------------------------------------------

Eval num_timesteps=12000000, episode_reward=-20.53 +/- 115.06

Episode length: 108.95 +/- 19.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | -20.5        |
| time/                   |              |
|    total_timesteps      | 12000000     |
| train/                  |              |
|    approx_kl            | 0.0033019227 |
|    clip_fraction        | 0.0286       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.938       |
|    explained_variance   | 0.982        |
|    learning_rate        | 0.0003       |
|    loss                 | 171          |
|    n_updates            | 2924         |
|    policy_gradient_loss | -5.68e-05    |
|    value_loss           | 982          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 12,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 128      |
|    ep_rew_mean     | 58.4     |
| time/              |          |
|    fps             | 1666     |
|    iterations      | 391      |
|    time_elapsed    | 3843     |
|    total_timesteps | 12006144 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 150          |
|    ep_rew_mean          | 87.5         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 392          |
|    time_elapsed         | 3853         |
|    total_timesteps      | 12022528     |
| train/                  |              |
|    approx_kl            | 0.0035211947 |
|    clip_fraction        | 0.0306       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.847       |
|    explained_variance   | 0.891        |
|    learning_rate        | 0.0003       |
|    loss                 | 436          |
|    n_updates            | 2928         |
|    policy_gradient_loss | -0.00113     |
|    value_loss           | 1.54e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 150          |
|    ep_rew_mean          | 83.9         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 393          |
|    time_elapsed         | 3862         |
|    total_timesteps      | 12038912     |
| train/                  |              |
|    approx_kl            | 0.0031169294 |
|    clip_fraction        | 0.0197       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.891       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.72e+03     |
|    n_updates            | 2932         |
|    policy_gradient_loss | -0.000166    |
|    value_loss           | 1.25e+03     |
------------------------------------------

Eval num_timesteps=12050000, episode_reward=-12.12 +/- 325.64

Episode length: 109.85 +/- 22.93

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 110         |
|    mean_reward          | -12.1       |
| time/                   |             |
|    total_timesteps      | 12050000    |
| train/                  |             |
|    approx_kl            | 0.003422493 |
|    clip_fraction        | 0.0267      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.946      |
|    explained_variance   | 0.974       |
|    learning_rate        | 0.0003      |
|    loss                 | 338         |
|    n_updates            | 2936        |
|    policy_gradient_loss | 0.000244    |
|    value_loss           | 1.36e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 97.1         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 395          |
|    time_elapsed         | 3883         |
|    total_timesteps      | 12071680     |
| train/                  |              |
|    approx_kl            | 0.0044739535 |
|    clip_fraction        | 0.0415       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.897       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 347          |
|    n_updates            | 2940         |
|    policy_gradient_loss | -0.000573    |
|    value_loss           | 910          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 151          |
|    ep_rew_mean          | 73.9         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 396          |
|    time_elapsed         | 3892         |
|    total_timesteps      | 12088064     |
| train/                  |              |
|    approx_kl            | 0.0036679911 |
|    clip_fraction        | 0.0235       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.912       |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 653          |
|    n_updates            | 2944         |
|    policy_gradient_loss | -0.000824    |
|    value_loss           | 1.16e+03     |
------------------------------------------

Eval num_timesteps=12100000, episode_reward=-91.11 +/- 218.64

Episode length: 113.00 +/- 32.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | -91.1        |
| time/                   |              |
|    total_timesteps      | 12100000     |
| train/                  |              |
|    approx_kl            | 0.0047446294 |
|    clip_fraction        | 0.0347       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.94        |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 185          |
|    n_updates            | 2948         |
|    policy_gradient_loss | -0.00179     |
|    value_loss           | 921          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 154      |
|    ep_rew_mean     | 89.9     |
| time/              |          |
|    fps             | 1666     |
|    iterations      | 397      |
|    time_elapsed    | 3904     |
|    total_timesteps | 12104448 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 153         |
|    ep_rew_mean          | 101         |
| time/                   |             |
|    fps                  | 1666        |
|    iterations           | 398         |
|    time_elapsed         | 3913        |
|    total_timesteps      | 12120832    |
| train/                  |             |
|    approx_kl            | 0.005141499 |
|    clip_fraction        | 0.0339      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.936      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 427         |
|    n_updates            | 2952        |
|    policy_gradient_loss | -0.000334   |
|    value_loss           | 1.59e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 139         |
|    ep_rew_mean          | 70.7        |
| time/                   |             |
|    fps                  | 1666        |
|    iterations           | 399         |
|    time_elapsed         | 3922        |
|    total_timesteps      | 12137216    |
| train/                  |             |
|    approx_kl            | 0.004408663 |
|    clip_fraction        | 0.0329      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.923      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 840         |
|    n_updates            | 2956        |
|    policy_gradient_loss | -0.000468   |
|    value_loss           | 1.44e+03    |
-----------------------------------------

Eval num_timesteps=12150000, episode_reward=-17.46 +/- 133.37

Episode length: 117.00 +/- 59.04

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | -17.5        |
| time/                   |              |
|    total_timesteps      | 12150000     |
| train/                  |              |
|    approx_kl            | 0.0042737937 |
|    clip_fraction        | 0.032        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | 0.943        |
|    learning_rate        | 0.0003       |
|    loss                 | 189          |
|    n_updates            | 2960         |
|    policy_gradient_loss | -0.00112     |
|    value_loss           | 2.26e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 91.3     |
| time/              |          |
|    fps             | 1665     |
|    iterations      | 400      |
|    time_elapsed    | 3933     |
|    total_timesteps | 12153600 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 168         |
|    ep_rew_mean          | 106         |
| time/                   |             |
|    fps                  | 1665        |
|    iterations           | 401         |
|    time_elapsed         | 3943        |
|    total_timesteps      | 12169984    |
| train/                  |             |
|    approx_kl            | 0.003597775 |
|    clip_fraction        | 0.014       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.902      |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | 436         |
|    n_updates            | 2964        |
|    policy_gradient_loss | 0.000357    |
|    value_loss           | 1.41e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 90.7         |
| time/                   |              |
|    fps                  | 1666         |
|    iterations           | 402          |
|    time_elapsed         | 3952         |
|    total_timesteps      | 12186368     |
| train/                  |              |
|    approx_kl            | 0.0035738288 |
|    clip_fraction        | 0.0154       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.925       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 366          |
|    n_updates            | 2968         |
|    policy_gradient_loss | -0.000183    |
|    value_loss           | 1.76e+03     |
------------------------------------------

Eval num_timesteps=12200000, episode_reward=-15.79 +/- 170.38

Episode length: 113.30 +/- 29.51

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 113          |
|    mean_reward          | -15.8        |
| time/                   |              |
|    total_timesteps      | 12200000     |
| train/                  |              |
|    approx_kl            | 0.0038389543 |
|    clip_fraction        | 0.0364       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 438          |
|    n_updates            | 2972         |
|    policy_gradient_loss | -0.00153     |
|    value_loss           | 1.09e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 148      |
|    ep_rew_mean     | 96.9     |
| time/              |          |
|    fps             | 1665     |
|    iterations      | 403      |
|    time_elapsed    | 3963     |
|    total_timesteps | 12202752 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 120          |
|    ep_rew_mean          | 77.6         |
| time/                   |              |
|    fps                  | 1665         |
|    iterations           | 404          |
|    time_elapsed         | 3973         |
|    total_timesteps      | 12219136     |
| train/                  |              |
|    approx_kl            | 0.0040179547 |
|    clip_fraction        | 0.0275       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.942       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 539          |
|    n_updates            | 2976         |
|    policy_gradient_loss | -0.00028     |
|    value_loss           | 1.26e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 141         |
|    ep_rew_mean          | 92.8        |
| time/                   |             |
|    fps                  | 1665        |
|    iterations           | 405         |
|    time_elapsed         | 3983        |
|    total_timesteps      | 12235520    |
| train/                  |             |
|    approx_kl            | 0.003932142 |
|    clip_fraction        | 0.026       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.9        |
|    explained_variance   | 0.954       |
|    learning_rate        | 0.0003      |
|    loss                 | 148         |
|    n_updates            | 2980        |
|    policy_gradient_loss | -0.00103    |
|    value_loss           | 923         |
-----------------------------------------

Eval num_timesteps=12250000, episode_reward=-98.70 +/- 245.64

Episode length: 111.70 +/- 26.77

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -98.7        |
| time/                   |              |
|    total_timesteps      | 12250000     |
| train/                  |              |
|    approx_kl            | 0.0035412398 |
|    clip_fraction        | 0.0181       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.952       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 247          |
|    n_updates            | 2984         |
|    policy_gradient_loss | -0.000268    |
|    value_loss           | 1.23e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 131      |
|    ep_rew_mean     | 104      |
| time/              |          |
|    fps             | 1665     |
|    iterations      | 406      |
|    time_elapsed    | 3994     |
|    total_timesteps | 12251904 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 90.4         |
| time/                   |              |
|    fps                  | 1665         |
|    iterations           | 407          |
|    time_elapsed         | 4003         |
|    total_timesteps      | 12268288     |
| train/                  |              |
|    approx_kl            | 0.0034228708 |
|    clip_fraction        | 0.0187       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.957       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 683          |
|    n_updates            | 2988         |
|    policy_gradient_loss | 0.000151     |
|    value_loss           | 1.37e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 123          |
|    ep_rew_mean          | 73.3         |
| time/                   |              |
|    fps                  | 1665         |
|    iterations           | 408          |
|    time_elapsed         | 4012         |
|    total_timesteps      | 12284672     |
| train/                  |              |
|    approx_kl            | 0.0036497577 |
|    clip_fraction        | 0.0249       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.946       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 205          |
|    n_updates            | 2992         |
|    policy_gradient_loss | -0.000772    |
|    value_loss           | 1.18e+03     |
------------------------------------------

Eval num_timesteps=12300000, episode_reward=-102.63 +/- 238.04

Episode length: 116.50 +/- 28.67

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | -103         |
| time/                   |              |
|    total_timesteps      | 12300000     |
| train/                  |              |
|    approx_kl            | 0.0040660156 |
|    clip_fraction        | 0.0276       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.911       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 212          |
|    n_updates            | 2996         |
|    policy_gradient_loss | -0.000606    |
|    value_loss           | 798          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 158      |
|    ep_rew_mean     | 119      |
| time/              |          |
|    fps             | 1663     |
|    iterations      | 409      |
|    time_elapsed    | 4027     |
|    total_timesteps | 12301056 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 85.6         |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 410          |
|    time_elapsed         | 4038         |
|    total_timesteps      | 12317440     |
| train/                  |              |
|    approx_kl            | 0.0054454934 |
|    clip_fraction        | 0.0362       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.926       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 876          |
|    n_updates            | 3000         |
|    policy_gradient_loss | -0.00252     |
|    value_loss           | 1.57e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 138          |
|    ep_rew_mean          | 108          |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 411          |
|    time_elapsed         | 4046         |
|    total_timesteps      | 12333824     |
| train/                  |              |
|    approx_kl            | 0.0047988165 |
|    clip_fraction        | 0.0347       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.95        |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 987          |
|    n_updates            | 3004         |
|    policy_gradient_loss | -0.000336    |
|    value_loss           | 1.29e+03     |
------------------------------------------

Eval num_timesteps=12350000, episode_reward=-34.97 +/- 123.51

Episode length: 109.70 +/- 23.64

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 110         |
|    mean_reward          | -35         |
| time/                   |             |
|    total_timesteps      | 12350000    |
| train/                  |             |
|    approx_kl            | 0.003531919 |
|    clip_fraction        | 0.0369      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.96       |
|    explained_variance   | 0.96        |
|    learning_rate        | 0.0003      |
|    loss                 | 552         |
|    n_updates            | 3008        |
|    policy_gradient_loss | -0.0012     |
|    value_loss           | 1.24e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 141      |
|    ep_rew_mean     | 79.8     |
| time/              |          |
|    fps             | 1663     |
|    iterations      | 412      |
|    time_elapsed    | 4058     |
|    total_timesteps | 12350208 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 128          |
|    ep_rew_mean          | 89.4         |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 413          |
|    time_elapsed         | 4068         |
|    total_timesteps      | 12366592     |
| train/                  |              |
|    approx_kl            | 0.0051416364 |
|    clip_fraction        | 0.0311       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.93        |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 344          |
|    n_updates            | 3012         |
|    policy_gradient_loss | -0.00156     |
|    value_loss           | 1.16e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 164          |
|    ep_rew_mean          | 116          |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 414          |
|    time_elapsed         | 4078         |
|    total_timesteps      | 12382976     |
| train/                  |              |
|    approx_kl            | 0.0044063656 |
|    clip_fraction        | 0.0271       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.96        |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 582          |
|    n_updates            | 3016         |
|    policy_gradient_loss | -0.00159     |
|    value_loss           | 1.6e+03      |
------------------------------------------

Eval num_timesteps=12400000, episode_reward=-117.01 +/- 492.17

Episode length: 104.45 +/- 24.93

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 104          |
|    mean_reward          | -117         |
| time/                   |              |
|    total_timesteps      | 12400000     |
| train/                  |              |
|    approx_kl            | 0.0046696956 |
|    clip_fraction        | 0.0365       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.959       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11e+03     |
|    n_updates            | 3024         |
|    policy_gradient_loss | -0.00142     |
|    value_loss           | 1.09e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 161      |
|    ep_rew_mean     | 114      |
| time/              |          |
|    fps             | 1663     |
|    iterations      | 416      |
|    time_elapsed    | 4098     |
|    total_timesteps | 12415744 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 142         |
|    ep_rew_mean          | 94          |
| time/                   |             |
|    fps                  | 1663        |
|    iterations           | 417         |
|    time_elapsed         | 4108        |
|    total_timesteps      | 12432128    |
| train/                  |             |
|    approx_kl            | 0.004181157 |
|    clip_fraction        | 0.0197      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.974      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 307         |
|    n_updates            | 3028        |
|    policy_gradient_loss | 0.000204    |
|    value_loss           | 1.66e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 154          |
|    ep_rew_mean          | 88.3         |
| time/                   |              |
|    fps                  | 1663         |
|    iterations           | 418          |
|    time_elapsed         | 4118         |
|    total_timesteps      | 12448512     |
| train/                  |              |
|    approx_kl            | 0.0040855575 |
|    clip_fraction        | 0.0191       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.927       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.13e+03     |
|    n_updates            | 3032         |
|    policy_gradient_loss | -0.000347    |
|    value_loss           | 1.54e+03     |
------------------------------------------

Eval num_timesteps=12450000, episode_reward=19.10 +/- 146.91

Episode length: 109.05 +/- 26.77

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 109        |
|    mean_reward          | 19.1       |
| time/                   |            |
|    total_timesteps      | 12450000   |
| train/                  |            |
|    approx_kl            | 0.00501701 |
|    clip_fraction        | 0.037      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.996     |
|    explained_variance   | 0.979      |
|    learning_rate        | 0.0003     |
|    loss                 | 147        |
|    n_updates            | 3036       |
|    policy_gradient_loss | -0.000599  |
|    value_loss           | 1.31e+03   |
----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 144      |
|    ep_rew_mean     | 78.7     |
| time/              |          |
|    fps             | 1662     |
|    iterations      | 419      |
|    time_elapsed    | 4129     |
|    total_timesteps | 12464896 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 195          |
|    ep_rew_mean          | 135          |
| time/                   |              |
|    fps                  | 1662         |
|    iterations           | 420          |
|    time_elapsed         | 4138         |
|    total_timesteps      | 12481280     |
| train/                  |              |
|    approx_kl            | 0.0035995366 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.99        |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.1e+03      |
|    n_updates            | 3040         |
|    policy_gradient_loss | -0.000496    |
|    value_loss           | 1.51e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 86.6         |
| time/                   |              |
|    fps                  | 1662         |
|    iterations           | 421          |
|    time_elapsed         | 4148         |
|    total_timesteps      | 12497664     |
| train/                  |              |
|    approx_kl            | 0.0034239185 |
|    clip_fraction        | 0.0202       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.968       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.01e+03     |
|    n_updates            | 3044         |
|    policy_gradient_loss | -0.000724    |
|    value_loss           | 2.41e+03     |
------------------------------------------

Eval num_timesteps=12500000, episode_reward=-24.75 +/- 349.40

Episode length: 107.10 +/- 28.71

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -24.7        |
| time/                   |              |
|    total_timesteps      | 12500000     |
| train/                  |              |
|    approx_kl            | 0.0047844825 |
|    clip_fraction        | 0.0396       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.914       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 989          |
|    n_updates            | 3048         |
|    policy_gradient_loss | -0.000646    |
|    value_loss           | 1.28e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 129      |
|    ep_rew_mean     | 60.6     |
| time/              |          |
|    fps             | 1662     |
|    iterations      | 422      |
|    time_elapsed    | 4159     |
|    total_timesteps | 12514048 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 80.6         |
| time/                   |              |
|    fps                  | 1662         |
|    iterations           | 424          |
|    time_elapsed         | 4178         |
|    total_timesteps      | 12546816     |
| train/                  |              |
|    approx_kl            | 0.0027295742 |
|    clip_fraction        | 0.0163       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.928       |
|    explained_variance   | 0.954        |
|    learning_rate        | 0.0003       |
|    loss                 | 182          |
|    n_updates            | 3056         |
|    policy_gradient_loss | -0.000491    |
|    value_loss           | 1.51e+03     |
------------------------------------------

Eval num_timesteps=12550000, episode_reward=-114.96 +/- 405.87

Episode length: 115.05 +/- 29.35

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 115          |
|    mean_reward          | -115         |
| time/                   |              |
|    total_timesteps      | 12550000     |
| train/                  |              |
|    approx_kl            | 0.0043138666 |
|    clip_fraction        | 0.0407       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 292          |
|    n_updates            | 3060         |
|    policy_gradient_loss | -0.00101     |
|    value_loss           | 905          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 81.6     |
| time/              |          |
|    fps             | 1661     |
|    iterations      | 425      |
|    time_elapsed    | 4190     |
|    total_timesteps | 12563200 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 160          |
|    ep_rew_mean          | 89.1         |
| time/                   |              |
|    fps                  | 1661         |
|    iterations           | 426          |
|    time_elapsed         | 4200         |
|    total_timesteps      | 12579584     |
| train/                  |              |
|    approx_kl            | 0.0032137258 |
|    clip_fraction        | 0.0314       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.845       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 375          |
|    n_updates            | 3064         |
|    policy_gradient_loss | -0.00108     |
|    value_loss           | 1.14e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 146          |
|    ep_rew_mean          | 95.2         |
| time/                   |              |
|    fps                  | 1661         |
|    iterations           | 427          |
|    time_elapsed         | 4210         |
|    total_timesteps      | 12595968     |
| train/                  |              |
|    approx_kl            | 0.0028769244 |
|    clip_fraction        | 0.0202       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.906       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23e+03     |
|    n_updates            | 3068         |
|    policy_gradient_loss | 0.000768     |
|    value_loss           | 1.7e+03      |
------------------------------------------

Eval num_timesteps=12600000, episode_reward=-8.35 +/- 144.29

Episode length: 106.00 +/- 21.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 106          |
|    mean_reward          | -8.35        |
| time/                   |              |
|    total_timesteps      | 12600000     |
| train/                  |              |
|    approx_kl            | 0.0019429042 |
|    clip_fraction        | 0.0165       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.899       |
|    explained_variance   | 0.951        |
|    learning_rate        | 0.0003       |
|    loss                 | 175          |
|    n_updates            | 3072         |
|    policy_gradient_loss | 0.000311     |
|    value_loss           | 1.33e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 148      |
|    ep_rew_mean     | 93.8     |
| time/              |          |
|    fps             | 1661     |
|    iterations      | 428      |
|    time_elapsed    | 4221     |
|    total_timesteps | 12612352 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 144          |
|    ep_rew_mean          | 87.1         |
| time/                   |              |
|    fps                  | 1661         |
|    iterations           | 429          |
|    time_elapsed         | 4231         |
|    total_timesteps      | 12628736     |
| train/                  |              |
|    approx_kl            | 0.0041010627 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | 0.931        |
|    learning_rate        | 0.0003       |
|    loss                 | 387          |
|    n_updates            | 3076         |
|    policy_gradient_loss | -0.00121     |
|    value_loss           | 1.24e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 129          |
|    ep_rew_mean          | 97.2         |
| time/                   |              |
|    fps                  | 1661         |
|    iterations           | 430          |
|    time_elapsed         | 4241         |
|    total_timesteps      | 12645120     |
| train/                  |              |
|    approx_kl            | 0.0028275358 |
|    clip_fraction        | 0.0207       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 482          |
|    n_updates            | 3080         |
|    policy_gradient_loss | 0.000781     |
|    value_loss           | 1.62e+03     |
------------------------------------------

Eval num_timesteps=12650000, episode_reward=-27.59 +/- 131.60

Episode length: 105.25 +/- 23.92

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 105          |
|    mean_reward          | -27.6        |
| time/                   |              |
|    total_timesteps      | 12650000     |
| train/                  |              |
|    approx_kl            | 0.0042029736 |
|    clip_fraction        | 0.0277       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.94         |
|    learning_rate        | 0.0003       |
|    loss                 | 450          |
|    n_updates            | 3084         |
|    policy_gradient_loss | -0.00031     |
|    value_loss           | 1.67e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 123      |
|    ep_rew_mean     | 63.5     |
| time/              |          |
|    fps             | 1660     |
|    iterations      | 431      |
|    time_elapsed    | 4252     |
|    total_timesteps | 12661504 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 91.3         |
| time/                   |              |
|    fps                  | 1660         |
|    iterations           | 432          |
|    time_elapsed         | 4261         |
|    total_timesteps      | 12677888     |
| train/                  |              |
|    approx_kl            | 0.0034338618 |
|    clip_fraction        | 0.0229       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.889        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 3088         |
|    policy_gradient_loss | 6.9e-05      |
|    value_loss           | 2.3e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 149         |
|    ep_rew_mean          | 81.3        |
| time/                   |             |
|    fps                  | 1660        |
|    iterations           | 433         |
|    time_elapsed         | 4271        |
|    total_timesteps      | 12694272    |
| train/                  |             |
|    approx_kl            | 0.003673222 |
|    clip_fraction        | 0.0153      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.904      |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | 189         |
|    n_updates            | 3092        |
|    policy_gradient_loss | 7.93e-05    |
|    value_loss           | 1.09e+03    |
-----------------------------------------

Eval num_timesteps=12700000, episode_reward=-28.61 +/- 236.09

Episode length: 102.65 +/- 24.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | -28.6        |
| time/                   |              |
|    total_timesteps      | 12700000     |
| train/                  |              |
|    approx_kl            | 0.0021317662 |
|    clip_fraction        | 0.00803      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.9         |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 3096         |
|    policy_gradient_loss | -0.000133    |
|    value_loss           | 1.33e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 150      |
|    ep_rew_mean     | 87.4     |
| time/              |          |
|    fps             | 1660     |
|    iterations      | 434      |
|    time_elapsed    | 4283     |
|    total_timesteps | 12710656 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 157          |
|    ep_rew_mean          | 93.6         |
| time/                   |              |
|    fps                  | 1660         |
|    iterations           | 435          |
|    time_elapsed         | 4293         |
|    total_timesteps      | 12727040     |
| train/                  |              |
|    approx_kl            | 0.0035798491 |
|    clip_fraction        | 0.0292       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.931       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 478          |
|    n_updates            | 3100         |
|    policy_gradient_loss | -0.000806    |
|    value_loss           | 1.52e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 76.9         |
| time/                   |              |
|    fps                  | 1660         |
|    iterations           | 436          |
|    time_elapsed         | 4301         |
|    total_timesteps      | 12743424     |
| train/                  |              |
|    approx_kl            | 0.0025998377 |
|    clip_fraction        | 0.0182       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.935       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.18e+03     |
|    n_updates            | 3104         |
|    policy_gradient_loss | 0.000404     |
|    value_loss           | 1.92e+03     |
------------------------------------------

Eval num_timesteps=12750000, episode_reward=-29.26 +/- 160.58

Episode length: 106.65 +/- 27.07

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 107         |
|    mean_reward          | -29.3       |
| time/                   |             |
|    total_timesteps      | 12750000    |
| train/                  |             |
|    approx_kl            | 0.003842028 |
|    clip_fraction        | 0.0311      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.875      |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.23e+03    |
|    n_updates            | 3108        |
|    policy_gradient_loss | -0.000571   |
|    value_loss           | 1.08e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 149      |
|    ep_rew_mean     | 87.2     |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 437      |
|    time_elapsed    | 4313     |
|    total_timesteps | 12759808 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 138          |
|    ep_rew_mean          | 79.2         |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 438          |
|    time_elapsed         | 4323         |
|    total_timesteps      | 12776192     |
| train/                  |              |
|    approx_kl            | 0.0036313224 |
|    clip_fraction        | 0.0222       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.937       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 946          |
|    n_updates            | 3112         |
|    policy_gradient_loss | -0.000467    |
|    value_loss           | 1.59e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 132          |
|    ep_rew_mean          | 74.4         |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 439          |
|    time_elapsed         | 4333         |
|    total_timesteps      | 12792576     |
| train/                  |              |
|    approx_kl            | 0.0026038312 |
|    clip_fraction        | 0.0185       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.901       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 242          |
|    n_updates            | 3116         |
|    policy_gradient_loss | 2.64e-05     |
|    value_loss           | 1.67e+03     |
------------------------------------------

Eval num_timesteps=12800000, episode_reward=89.89 +/- 119.62

Episode length: 101.90 +/- 22.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 102          |
|    mean_reward          | 89.9         |
| time/                   |              |
|    total_timesteps      | 12800000     |
| train/                  |              |
|    approx_kl            | 0.0057283486 |
|    clip_fraction        | 0.0466       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.921       |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 283          |
|    n_updates            | 3120         |
|    policy_gradient_loss | -0.000104    |
|    value_loss           | 912          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 130      |
|    ep_rew_mean     | 79.4     |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 440      |
|    time_elapsed    | 4344     |
|    total_timesteps | 12808960 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 96           |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 441          |
|    time_elapsed         | 4353         |
|    total_timesteps      | 12825344     |
| train/                  |              |
|    approx_kl            | 0.0048950133 |
|    clip_fraction        | 0.0393       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.913       |
|    explained_variance   | 0.854        |
|    learning_rate        | 0.0003       |
|    loss                 | 604          |
|    n_updates            | 3124         |
|    policy_gradient_loss | -0.00217     |
|    value_loss           | 942          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 145          |
|    ep_rew_mean          | 97.3         |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 442          |
|    time_elapsed         | 4363         |
|    total_timesteps      | 12841728     |
| train/                  |              |
|    approx_kl            | 0.0022822153 |
|    clip_fraction        | 0.0118       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45e+03     |
|    n_updates            | 3128         |
|    policy_gradient_loss | 0.000136     |
|    value_loss           | 1.22e+03     |
------------------------------------------

Eval num_timesteps=12850000, episode_reward=-21.38 +/- 80.46

Episode length: 106.50 +/- 22.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 106          |
|    mean_reward          | -21.4        |
| time/                   |              |
|    total_timesteps      | 12850000     |
| train/                  |              |
|    approx_kl            | 0.0038816181 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.896       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 478          |
|    n_updates            | 3132         |
|    policy_gradient_loss | -0.0008      |
|    value_loss           | 1.29e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 136      |
|    ep_rew_mean     | 78.1     |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 443      |
|    time_elapsed    | 4374     |
|    total_timesteps | 12858112 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 88          |
| time/                   |             |
|    fps                  | 1659        |
|    iterations           | 444         |
|    time_elapsed         | 4383        |
|    total_timesteps      | 12874496    |
| train/                  |             |
|    approx_kl            | 0.004396923 |
|    clip_fraction        | 0.0394      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.911      |
|    explained_variance   | 0.905       |
|    learning_rate        | 0.0003      |
|    loss                 | 139         |
|    n_updates            | 3136        |
|    policy_gradient_loss | -0.000571   |
|    value_loss           | 833         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 151         |
|    ep_rew_mean          | 116         |
| time/                   |             |
|    fps                  | 1659        |
|    iterations           | 445         |
|    time_elapsed         | 4392        |
|    total_timesteps      | 12890880    |
| train/                  |             |
|    approx_kl            | 0.004498626 |
|    clip_fraction        | 0.026       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.899      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 423         |
|    n_updates            | 3140        |
|    policy_gradient_loss | -0.00146    |
|    value_loss           | 1.28e+03    |
-----------------------------------------

Eval num_timesteps=12900000, episode_reward=-68.29 +/- 137.29

Episode length: 115.70 +/- 24.43

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | -68.3        |
| time/                   |              |
|    total_timesteps      | 12900000     |
| train/                  |              |
|    approx_kl            | 0.0024175353 |
|    clip_fraction        | 0.0232       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.885       |
|    explained_variance   | 0.825        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.16e+04     |
|    n_updates            | 3144         |
|    policy_gradient_loss | -0.000324    |
|    value_loss           | 1.08e+04     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_12900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 103      |
| time/              |          |
|    fps             | 1659     |
|    iterations      | 446      |
|    time_elapsed    | 4404     |
|    total_timesteps | 12907264 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 148          |
|    ep_rew_mean          | 85.6         |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 447          |
|    time_elapsed         | 4414         |
|    total_timesteps      | 12923648     |
| train/                  |              |
|    approx_kl            | 0.0058115944 |
|    clip_fraction        | 0.0415       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.92        |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 374          |
|    n_updates            | 3148         |
|    policy_gradient_loss | -0.00133     |
|    value_loss           | 1.51e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 133          |
|    ep_rew_mean          | 66.8         |
| time/                   |              |
|    fps                  | 1659         |
|    iterations           | 448          |
|    time_elapsed         | 4423         |
|    total_timesteps      | 12940032     |
| train/                  |              |
|    approx_kl            | 0.0046158927 |
|    clip_fraction        | 0.0311       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.928       |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 585          |
|    n_updates            | 3152         |
|    policy_gradient_loss | -0.00105     |
|    value_loss           | 1.7e+03      |
------------------------------------------

Eval num_timesteps=12950000, episode_reward=-7.17 +/- 73.52

Episode length: 107.30 +/- 19.52

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 107          |
|    mean_reward          | -7.17        |
| time/                   |              |
|    total_timesteps      | 12950000     |
| train/                  |              |
|    approx_kl            | 0.0027047049 |
|    clip_fraction        | 0.0165       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.905       |
|    explained_variance   | 0.95         |
|    learning_rate        | 0.0003       |
|    loss                 | 488          |
|    n_updates            | 3156         |
|    policy_gradient_loss | 0.000274     |
|    value_loss           | 1.34e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 151      |
|    ep_rew_mean     | 85.8     |
| time/              |          |
|    fps             | 1658     |
|    iterations      | 449      |
|    time_elapsed    | 4434     |
|    total_timesteps | 12956416 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 133         |
|    ep_rew_mean          | 82          |
| time/                   |             |
|    fps                  | 1658        |
|    iterations           | 450         |
|    time_elapsed         | 4444        |
|    total_timesteps      | 12972800    |
| train/                  |             |
|    approx_kl            | 0.003145748 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.894      |
|    explained_variance   | 0.984       |
|    learning_rate        | 0.0003      |
|    loss                 | 529         |
|    n_updates            | 3160        |
|    policy_gradient_loss | -0.000634   |
|    value_loss           | 1.04e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 164         |
|    ep_rew_mean          | 95.5        |
| time/                   |             |
|    fps                  | 1658        |
|    iterations           | 451         |
|    time_elapsed         | 4454        |
|    total_timesteps      | 12989184    |
| train/                  |             |
|    approx_kl            | 0.004436878 |
|    clip_fraction        | 0.037       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.925      |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 759         |
|    n_updates            | 3164        |
|    policy_gradient_loss | -0.00123    |
|    value_loss           | 1.06e+03    |
-----------------------------------------

Eval num_timesteps=13000000, episode_reward=-8.48 +/- 103.38

Episode length: 118.70 +/- 29.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | -8.48        |
| time/                   |              |
|    total_timesteps      | 13000000     |
| train/                  |              |
|    approx_kl            | 0.0041971034 |
|    clip_fraction        | 0.0315       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.978       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 499          |
|    n_updates            | 3168         |
|    policy_gradient_loss | 0.000347     |
|    value_loss           | 1.55e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 13,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 179      |
|    ep_rew_mean     | 119      |
| time/              |          |
|    fps             | 1656     |
|    iterations      | 452      |
|    time_elapsed    | 4470     |
|    total_timesteps | 13005568 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 56.6         |
| time/                   |              |
|    fps                  | 1656         |
|    iterations           | 453          |
|    time_elapsed         | 4480         |
|    total_timesteps      | 13021952     |
| train/                  |              |
|    approx_kl            | 0.0030837753 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.94        |
|    explained_variance   | 0.852        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.83e+03     |
|    n_updates            | 3172         |
|    policy_gradient_loss | 9.33e-05     |
|    value_loss           | 9.5e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 164         |
|    ep_rew_mean          | 78.5        |
| time/                   |             |
|    fps                  | 1657        |
|    iterations           | 454         |
|    time_elapsed         | 4488        |
|    total_timesteps      | 13038336    |
| train/                  |             |
|    approx_kl            | 0.004862494 |
|    clip_fraction        | 0.035       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.939      |
|    explained_variance   | 0.969       |
|    learning_rate        | 0.0003      |
|    loss                 | 965         |
|    n_updates            | 3176        |
|    policy_gradient_loss | -0.000672   |
|    value_loss           | 994         |
-----------------------------------------

Eval num_timesteps=13050000, episode_reward=54.36 +/- 127.36

Episode length: 111.55 +/- 28.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | 54.4         |
| time/                   |              |
|    total_timesteps      | 13050000     |
| train/                  |              |
|    approx_kl            | 0.0051740734 |
|    clip_fraction        | 0.0294       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.973       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 315          |
|    n_updates            | 3180         |
|    policy_gradient_loss | -0.000377    |
|    value_loss           | 1.19e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 169      |
|    ep_rew_mean     | 87.7     |
| time/              |          |
|    fps             | 1656     |
|    iterations      | 455      |
|    time_elapsed    | 4500     |
|    total_timesteps | 13054720 |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 181        |
|    ep_rew_mean          | 89.1       |
| time/                   |            |
|    fps                  | 1656       |
|    iterations           | 456        |
|    time_elapsed         | 4510       |
|    total_timesteps      | 13071104   |
| train/                  |            |
|    approx_kl            | 0.00522687 |
|    clip_fraction        | 0.0415     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.948     |
|    explained_variance   | 0.983      |
|    learning_rate        | 0.0003     |
|    loss                 | 180        |
|    n_updates            | 3184       |
|    policy_gradient_loss | 0.000228   |
|    value_loss           | 1.22e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 131         |
|    ep_rew_mean          | 57.9        |
| time/                   |             |
|    fps                  | 1656        |
|    iterations           | 457         |
|    time_elapsed         | 4520        |
|    total_timesteps      | 13087488    |
| train/                  |             |
|    approx_kl            | 0.003973283 |
|    clip_fraction        | 0.0189      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.938      |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.89e+03    |
|    n_updates            | 3188        |
|    policy_gradient_loss | -8.32e-06   |
|    value_loss           | 2.81e+03    |
-----------------------------------------

Eval num_timesteps=13100000, episode_reward=66.79 +/- 105.99

Episode length: 102.85 +/- 17.69

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 103          |
|    mean_reward          | 66.8         |
| time/                   |              |
|    total_timesteps      | 13100000     |
| train/                  |              |
|    approx_kl            | 0.0039195665 |
|    clip_fraction        | 0.0455       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.883       |
|    explained_variance   | 0.943        |
|    learning_rate        | 0.0003       |
|    loss                 | 358          |
|    n_updates            | 3192         |
|    policy_gradient_loss | -0.00166     |
|    value_loss           | 782          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 72.4     |
| time/              |          |
|    fps             | 1656     |
|    iterations      | 458      |
|    time_elapsed    | 4531     |
|    total_timesteps | 13103872 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 152          |
|    ep_rew_mean          | 77.1         |
| time/                   |              |
|    fps                  | 1656         |
|    iterations           | 459          |
|    time_elapsed         | 4540         |
|    total_timesteps      | 13120256     |
| train/                  |              |
|    approx_kl            | 0.0036018346 |
|    clip_fraction        | 0.0268       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.904       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 120          |
|    n_updates            | 3196         |
|    policy_gradient_loss | -0.000192    |
|    value_loss           | 825          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 140         |
|    ep_rew_mean          | 77.3        |
| time/                   |             |
|    fps                  | 1656        |
|    iterations           | 460         |
|    time_elapsed         | 4550        |
|    total_timesteps      | 13136640    |
| train/                  |             |
|    approx_kl            | 0.005033912 |
|    clip_fraction        | 0.0652      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.895      |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | 403         |
|    n_updates            | 3200        |
|    policy_gradient_loss | -0.00153    |
|    value_loss           | 1.83e+03    |
-----------------------------------------

Eval num_timesteps=13150000, episode_reward=72.53 +/- 126.40

Episode length: 112.40 +/- 23.52

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 112         |
|    mean_reward          | 72.5        |
| time/                   |             |
|    total_timesteps      | 13150000    |
| train/                  |             |
|    approx_kl            | 0.004014547 |
|    clip_fraction        | 0.0331      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.881      |
|    explained_variance   | 0.974       |
|    learning_rate        | 0.0003      |
|    loss                 | 162         |
|    n_updates            | 3204        |
|    policy_gradient_loss | -0.00025    |
|    value_loss           | 709         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 140      |
|    ep_rew_mean     | 70.1     |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 461      |
|    time_elapsed    | 4561     |
|    total_timesteps | 13153024 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 150          |
|    ep_rew_mean          | 71.3         |
| time/                   |              |
|    fps                  | 1656         |
|    iterations           | 463          |
|    time_elapsed         | 4580         |
|    total_timesteps      | 13185792     |
| train/                  |              |
|    approx_kl            | 0.0042390185 |
|    clip_fraction        | 0.0328       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.21e+03     |
|    n_updates            | 3212         |
|    policy_gradient_loss | -0.000273    |
|    value_loss           | 1.44e+03     |
------------------------------------------

Eval num_timesteps=13200000, episode_reward=84.00 +/- 91.44

Episode length: 96.70 +/- 19.02

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96.7        |
|    mean_reward          | 84          |
| time/                   |             |
|    total_timesteps      | 13200000    |
| train/                  |             |
|    approx_kl            | 0.003951936 |
|    clip_fraction        | 0.0321      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.886      |
|    explained_variance   | 0.903       |
|    learning_rate        | 0.0003      |
|    loss                 | 637         |
|    n_updates            | 3216        |
|    policy_gradient_loss | -0.00123    |
|    value_loss           | 1.93e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 155      |
|    ep_rew_mean     | 79.1     |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 464      |
|    time_elapsed    | 4591     |
|    total_timesteps | 13202176 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 145          |
|    ep_rew_mean          | 92.8         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 465          |
|    time_elapsed         | 4601         |
|    total_timesteps      | 13218560     |
| train/                  |              |
|    approx_kl            | 0.0045499885 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 184          |
|    n_updates            | 3220         |
|    policy_gradient_loss | -0.000717    |
|    value_loss           | 1.03e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 161          |
|    ep_rew_mean          | 95.1         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 466          |
|    time_elapsed         | 4610         |
|    total_timesteps      | 13234944     |
| train/                  |              |
|    approx_kl            | 0.0028003464 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.865       |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 527          |
|    n_updates            | 3224         |
|    policy_gradient_loss | -0.00031     |
|    value_loss           | 1.24e+03     |
------------------------------------------

Eval num_timesteps=13250000, episode_reward=19.73 +/- 124.16

Episode length: 126.20 +/- 33.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | 19.7         |
| time/                   |              |
|    total_timesteps      | 13250000     |
| train/                  |              |
|    approx_kl            | 0.0038153436 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.864       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 600          |
|    n_updates            | 3228         |
|    policy_gradient_loss | -0.000739    |
|    value_loss           | 1.12e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 135      |
|    ep_rew_mean     | 65.8     |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 467      |
|    time_elapsed    | 4622     |
|    total_timesteps | 13251328 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 150          |
|    ep_rew_mean          | 91.2         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 468          |
|    time_elapsed         | 4631         |
|    total_timesteps      | 13267712     |
| train/                  |              |
|    approx_kl            | 0.0047371713 |
|    clip_fraction        | 0.0542       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.862       |
|    explained_variance   | 0.807        |
|    learning_rate        | 0.0003       |
|    loss                 | 776          |
|    n_updates            | 3232         |
|    policy_gradient_loss | -0.00208     |
|    value_loss           | 1.24e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 164          |
|    ep_rew_mean          | 83.1         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 469          |
|    time_elapsed         | 4641         |
|    total_timesteps      | 13284096     |
| train/                  |              |
|    approx_kl            | 0.0038480903 |
|    clip_fraction        | 0.023        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.911       |
|    explained_variance   | 0.958        |
|    learning_rate        | 0.0003       |
|    loss                 | 221          |
|    n_updates            | 3236         |
|    policy_gradient_loss | -0.000744    |
|    value_loss           | 936          |
------------------------------------------

Eval num_timesteps=13300000, episode_reward=44.09 +/- 102.75

Episode length: 111.00 +/- 28.89

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 111          |
|    mean_reward          | 44.1         |
| time/                   |              |
|    total_timesteps      | 13300000     |
| train/                  |              |
|    approx_kl            | 0.0030480125 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.887       |
|    explained_variance   | 0.896        |
|    learning_rate        | 0.0003       |
|    loss                 | 344          |
|    n_updates            | 3240         |
|    policy_gradient_loss | -0.000567    |
|    value_loss           | 4.54e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 137      |
|    ep_rew_mean     | 90       |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 470      |
|    time_elapsed    | 4652     |
|    total_timesteps | 13300480 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 138          |
|    ep_rew_mean          | 77.4         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 471          |
|    time_elapsed         | 4661         |
|    total_timesteps      | 13316864     |
| train/                  |              |
|    approx_kl            | 0.0045079673 |
|    clip_fraction        | 0.0363       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.827       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 527          |
|    n_updates            | 3244         |
|    policy_gradient_loss | -0.00121     |
|    value_loss           | 1.06e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 165         |
|    ep_rew_mean          | 131         |
| time/                   |             |
|    fps                  | 1655        |
|    iterations           | 472         |
|    time_elapsed         | 4671        |
|    total_timesteps      | 13333248    |
| train/                  |             |
|    approx_kl            | 0.004025725 |
|    clip_fraction        | 0.0285      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.87       |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | 812         |
|    n_updates            | 3248        |
|    policy_gradient_loss | -0.00011    |
|    value_loss           | 1.03e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 147          |
|    ep_rew_mean          | 87.4         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 473          |
|    time_elapsed         | 4681         |
|    total_timesteps      | 13349632     |
| train/                  |              |
|    approx_kl            | 0.0030088378 |
|    clip_fraction        | 0.0237       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.916       |
|    explained_variance   | 0.88         |
|    learning_rate        | 0.0003       |
|    loss                 | 4.27e+04     |
|    n_updates            | 3252         |
|    policy_gradient_loss | 2.42e-05     |
|    value_loss           | 8.84e+03     |
------------------------------------------

Eval num_timesteps=13350000, episode_reward=71.74 +/- 109.13

Episode length: 108.55 +/- 29.63

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 109          |
|    mean_reward          | 71.7         |
| time/                   |              |
|    total_timesteps      | 13350000     |
| train/                  |              |
|    approx_kl            | 0.0028651964 |
|    clip_fraction        | 0.0174       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.945        |
|    learning_rate        | 0.0003       |
|    loss                 | 583          |
|    n_updates            | 3256         |
|    policy_gradient_loss | -7.86e-05    |
|    value_loss           | 1.66e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 147      |
|    ep_rew_mean     | 73.7     |
| time/              |          |
|    fps             | 1655     |
|    iterations      | 474      |
|    time_elapsed    | 4692     |
|    total_timesteps | 13366016 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 138          |
|    ep_rew_mean          | 79.1         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 475          |
|    time_elapsed         | 4701         |
|    total_timesteps      | 13382400     |
| train/                  |              |
|    approx_kl            | 0.0025727572 |
|    clip_fraction        | 0.0237       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.881       |
|    explained_variance   | 0.944        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.17e+03     |
|    n_updates            | 3260         |
|    policy_gradient_loss | -0.0004      |
|    value_loss           | 2.28e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 135          |
|    ep_rew_mean          | 72.9         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 476          |
|    time_elapsed         | 4711         |
|    total_timesteps      | 13398784     |
| train/                  |              |
|    approx_kl            | 0.0028454338 |
|    clip_fraction        | 0.0177       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 344          |
|    n_updates            | 3264         |
|    policy_gradient_loss | 0.000151     |
|    value_loss           | 1.15e+03     |
------------------------------------------

Eval num_timesteps=13400000, episode_reward=25.86 +/- 96.30

Episode length: 144.30 +/- 41.28

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 144          |
|    mean_reward          | 25.9         |
| time/                   |              |
|    total_timesteps      | 13400000     |
| train/                  |              |
|    approx_kl            | 0.0025515296 |
|    clip_fraction        | 0.0189       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.862       |
|    explained_variance   | 0.929        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.96e+03     |
|    n_updates            | 3268         |
|    policy_gradient_loss | 0.000145     |
|    value_loss           | 2.64e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 161      |
|    ep_rew_mean     | 100      |
| time/              |          |
|    fps             | 1654     |
|    iterations      | 477      |
|    time_elapsed    | 4723     |
|    total_timesteps | 13415168 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 89.5         |
| time/                   |              |
|    fps                  | 1655         |
|    iterations           | 479          |
|    time_elapsed         | 4741         |
|    total_timesteps      | 13447936     |
| train/                  |              |
|    approx_kl            | 0.0035034583 |
|    clip_fraction        | 0.0301       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.891       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 295          |
|    n_updates            | 3276         |
|    policy_gradient_loss | -0.000511    |
|    value_loss           | 1.36e+03     |
------------------------------------------

Eval num_timesteps=13450000, episode_reward=2.78 +/- 116.94

Episode length: 116.25 +/- 26.27

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 116          |
|    mean_reward          | 2.78         |
| time/                   |              |
|    total_timesteps      | 13450000     |
| train/                  |              |
|    approx_kl            | 0.0033964142 |
|    clip_fraction        | 0.0304       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.73e+03     |
|    n_updates            | 3280         |
|    policy_gradient_loss | -0.000176    |
|    value_loss           | 2.03e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 156      |
|    ep_rew_mean     | 90.8     |
| time/              |          |
|    fps             | 1654     |
|    iterations      | 480      |
|    time_elapsed    | 4753     |
|    total_timesteps | 13464320 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 161          |
|    ep_rew_mean          | 91.8         |
| time/                   |              |
|    fps                  | 1654         |
|    iterations           | 481          |
|    time_elapsed         | 4762         |
|    total_timesteps      | 13480704     |
| train/                  |              |
|    approx_kl            | 0.0048951637 |
|    clip_fraction        | 0.028        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.885       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 225          |
|    n_updates            | 3284         |
|    policy_gradient_loss | -0.000305    |
|    value_loss           | 1.12e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 143         |
|    ep_rew_mean          | 110         |
| time/                   |             |
|    fps                  | 1655        |
|    iterations           | 482         |
|    time_elapsed         | 4771        |
|    total_timesteps      | 13497088    |
| train/                  |             |
|    approx_kl            | 0.002880341 |
|    clip_fraction        | 0.022       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.887      |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 274         |
|    n_updates            | 3288        |
|    policy_gradient_loss | -0.000203   |
|    value_loss           | 1.39e+03    |
-----------------------------------------

Eval num_timesteps=13500000, episode_reward=40.97 +/- 89.06

Episode length: 117.30 +/- 30.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 117          |
|    mean_reward          | 41           |
| time/                   |              |
|    total_timesteps      | 13500000     |
| train/                  |              |
|    approx_kl            | 0.0027511325 |
|    clip_fraction        | 0.0222       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.88        |
|    explained_variance   | 0.822        |
|    learning_rate        | 0.0003       |
|    loss                 | 763          |
|    n_updates            | 3292         |
|    policy_gradient_loss | 0.000203     |
|    value_loss           | 9.79e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 147      |
|    ep_rew_mean     | 89.8     |
| time/              |          |
|    fps             | 1654     |
|    iterations      | 483      |
|    time_elapsed    | 4783     |
|    total_timesteps | 13513472 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 160          |
|    ep_rew_mean          | 90.6         |
| time/                   |              |
|    fps                  | 1654         |
|    iterations           | 484          |
|    time_elapsed         | 4793         |
|    total_timesteps      | 13529856     |
| train/                  |              |
|    approx_kl            | 0.0034201532 |
|    clip_fraction        | 0.0269       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.852       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 517          |
|    n_updates            | 3296         |
|    policy_gradient_loss | -0.00158     |
|    value_loss           | 1.43e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 160          |
|    ep_rew_mean          | 107          |
| time/                   |              |
|    fps                  | 1654         |
|    iterations           | 485          |
|    time_elapsed         | 4803         |
|    total_timesteps      | 13546240     |
| train/                  |              |
|    approx_kl            | 0.0037056091 |
|    clip_fraction        | 0.0246       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.914       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 283          |
|    n_updates            | 3300         |
|    policy_gradient_loss | -0.000261    |
|    value_loss           | 1.36e+03     |
------------------------------------------

Eval num_timesteps=13550000, episode_reward=27.15 +/- 267.50

Episode length: 155.30 +/- 67.90

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 155          |
|    mean_reward          | 27.2         |
| time/                   |              |
|    total_timesteps      | 13550000     |
| train/                  |              |
|    approx_kl            | 0.0033815606 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.893       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 911          |
|    n_updates            | 3304         |
|    policy_gradient_loss | -6.09e-05    |
|    value_loss           | 1.4e+03      |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 142      |
|    ep_rew_mean     | 67.9     |
| time/              |          |
|    fps             | 1653     |
|    iterations      | 486      |
|    time_elapsed    | 4815     |
|    total_timesteps | 13562624 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 155          |
|    ep_rew_mean          | 98.7         |
| time/                   |              |
|    fps                  | 1653         |
|    iterations           | 487          |
|    time_elapsed         | 4824         |
|    total_timesteps      | 13579008     |
| train/                  |              |
|    approx_kl            | 0.0030060813 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.87        |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 402          |
|    n_updates            | 3308         |
|    policy_gradient_loss | -1.86e-05    |
|    value_loss           | 735          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 169         |
|    ep_rew_mean          | 119         |
| time/                   |             |
|    fps                  | 1653        |
|    iterations           | 488         |
|    time_elapsed         | 4834        |
|    total_timesteps      | 13595392    |
| train/                  |             |
|    approx_kl            | 0.004446051 |
|    clip_fraction        | 0.0341      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.864      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 294         |
|    n_updates            | 3312        |
|    policy_gradient_loss | -0.002      |
|    value_loss           | 1.27e+03    |
-----------------------------------------

Eval num_timesteps=13600000, episode_reward=57.66 +/- 98.16

Episode length: 120.05 +/- 39.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 57.7         |
| time/                   |              |
|    total_timesteps      | 13600000     |
| train/                  |              |
|    approx_kl            | 0.0047069015 |
|    clip_fraction        | 0.0397       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.87        |
|    explained_variance   | 0.858        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.57e+03     |
|    n_updates            | 3316         |
|    policy_gradient_loss | -0.000588    |
|    value_loss           | 1.01e+04     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 142      |
|    ep_rew_mean     | 68.4     |
| time/              |          |
|    fps             | 1653     |
|    iterations      | 489      |
|    time_elapsed    | 4845     |
|    total_timesteps | 13611776 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 136          |
|    ep_rew_mean          | 80.7         |
| time/                   |              |
|    fps                  | 1653         |
|    iterations           | 490          |
|    time_elapsed         | 4855         |
|    total_timesteps      | 13628160     |
| train/                  |              |
|    approx_kl            | 0.0034441294 |
|    clip_fraction        | 0.0236       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.875        |
|    learning_rate        | 0.0003       |
|    loss                 | 395          |
|    n_updates            | 3320         |
|    policy_gradient_loss | -0.000158    |
|    value_loss           | 3.85e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 150          |
|    ep_rew_mean          | 97           |
| time/                   |              |
|    fps                  | 1653         |
|    iterations           | 491          |
|    time_elapsed         | 4864         |
|    total_timesteps      | 13644544     |
| train/                  |              |
|    approx_kl            | 0.0039305827 |
|    clip_fraction        | 0.0268       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 768          |
|    n_updates            | 3324         |
|    policy_gradient_loss | -0.000663    |
|    value_loss           | 1.03e+03     |
------------------------------------------

Eval num_timesteps=13650000, episode_reward=8.26 +/- 101.12

Episode length: 141.70 +/- 56.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 142          |
|    mean_reward          | 8.26         |
| time/                   |              |
|    total_timesteps      | 13650000     |
| train/                  |              |
|    approx_kl            | 0.0026563308 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.952        |
|    learning_rate        | 0.0003       |
|    loss                 | 466          |
|    n_updates            | 3328         |
|    policy_gradient_loss | 0.000722     |
|    value_loss           | 1.29e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 139      |
|    ep_rew_mean     | 71.2     |
| time/              |          |
|    fps             | 1652     |
|    iterations      | 492      |
|    time_elapsed    | 4876     |
|    total_timesteps | 13660928 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 165          |
|    ep_rew_mean          | 80.6         |
| time/                   |              |
|    fps                  | 1652         |
|    iterations           | 493          |
|    time_elapsed         | 4886         |
|    total_timesteps      | 13677312     |
| train/                  |              |
|    approx_kl            | 0.0025105127 |
|    clip_fraction        | 0.0176       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.849       |
|    explained_variance   | 0.94         |
|    learning_rate        | 0.0003       |
|    loss                 | 520          |
|    n_updates            | 3332         |
|    policy_gradient_loss | -3.81e-05    |
|    value_loss           | 1.49e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 191          |
|    ep_rew_mean          | 104          |
| time/                   |              |
|    fps                  | 1652         |
|    iterations           | 494          |
|    time_elapsed         | 4896         |
|    total_timesteps      | 13693696     |
| train/                  |              |
|    approx_kl            | 0.0042471294 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 557          |
|    n_updates            | 3336         |
|    policy_gradient_loss | -0.000235    |
|    value_loss           | 2.03e+03     |
------------------------------------------

Eval num_timesteps=13700000, episode_reward=1.30 +/- 76.58

Episode length: 133.05 +/- 58.23

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 133          |
|    mean_reward          | 1.3          |
| time/                   |              |
|    total_timesteps      | 13700000     |
| train/                  |              |
|    approx_kl            | 0.0039521293 |
|    clip_fraction        | 0.0301       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.908       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.53e+03     |
|    n_updates            | 3340         |
|    policy_gradient_loss | 0.000282     |
|    value_loss           | 2.9e+03      |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 151      |
|    ep_rew_mean     | 87.6     |
| time/              |          |
|    fps             | 1652     |
|    iterations      | 495      |
|    time_elapsed    | 4908     |
|    total_timesteps | 13710080 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 190         |
|    ep_rew_mean          | 101         |
| time/                   |             |
|    fps                  | 1652        |
|    iterations           | 496         |
|    time_elapsed         | 4917        |
|    total_timesteps      | 13726464    |
| train/                  |             |
|    approx_kl            | 0.004408055 |
|    clip_fraction        | 0.0373      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.896      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 251         |
|    n_updates            | 3344        |
|    policy_gradient_loss | -0.000254   |
|    value_loss           | 1.29e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 70.7         |
| time/                   |              |
|    fps                  | 1652         |
|    iterations           | 497          |
|    time_elapsed         | 4927         |
|    total_timesteps      | 13742848     |
| train/                  |              |
|    approx_kl            | 0.0037035437 |
|    clip_fraction        | 0.0244       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.911       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.44e+03     |
|    n_updates            | 3348         |
|    policy_gradient_loss | -0.000606    |
|    value_loss           | 1.69e+03     |
------------------------------------------

Eval num_timesteps=13750000, episode_reward=5.33 +/- 87.24

Episode length: 131.80 +/- 48.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | 5.33         |
| time/                   |              |
|    total_timesteps      | 13750000     |
| train/                  |              |
|    approx_kl            | 0.0044087213 |
|    clip_fraction        | 0.0297       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.879       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 458          |
|    n_updates            | 3352         |
|    policy_gradient_loss | -0.00148     |
|    value_loss           | 1.1e+03      |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 189      |
|    ep_rew_mean     | 129      |
| time/              |          |
|    fps             | 1651     |
|    iterations      | 498      |
|    time_elapsed    | 4939     |
|    total_timesteps | 13759232 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 156          |
|    ep_rew_mean          | 69.3         |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 499          |
|    time_elapsed         | 4949         |
|    total_timesteps      | 13775616     |
| train/                  |              |
|    approx_kl            | 0.0028644402 |
|    clip_fraction        | 0.0148       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.843        |
|    learning_rate        | 0.0003       |
|    loss                 | 867          |
|    n_updates            | 3356         |
|    policy_gradient_loss | -0.000727    |
|    value_loss           | 8.68e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 160          |
|    ep_rew_mean          | 80.6         |
| time/                   |              |
|    fps                  | 1652         |
|    iterations           | 500          |
|    time_elapsed         | 4958         |
|    total_timesteps      | 13792000     |
| train/                  |              |
|    approx_kl            | 0.0042754835 |
|    clip_fraction        | 0.0267       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.821       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.54e+03     |
|    n_updates            | 3360         |
|    policy_gradient_loss | -0.00167     |
|    value_loss           | 1.35e+03     |
------------------------------------------

Eval num_timesteps=13800000, episode_reward=-9.79 +/- 113.64

Episode length: 151.60 +/- 58.70

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 152         |
|    mean_reward          | -9.79       |
| time/                   |             |
|    total_timesteps      | 13800000    |
| train/                  |             |
|    approx_kl            | 0.004182238 |
|    clip_fraction        | 0.0385      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.851      |
|    explained_variance   | 0.977       |
|    learning_rate        | 0.0003      |
|    loss                 | 199         |
|    n_updates            | 3364        |
|    policy_gradient_loss | -0.000718   |
|    value_loss           | 960         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 156      |
|    ep_rew_mean     | 79.5     |
| time/              |          |
|    fps             | 1651     |
|    iterations      | 501      |
|    time_elapsed    | 4970     |
|    total_timesteps | 13808384 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 168          |
|    ep_rew_mean          | 96           |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 502          |
|    time_elapsed         | 4980         |
|    total_timesteps      | 13824768     |
| train/                  |              |
|    approx_kl            | 0.0046874043 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23e+03     |
|    n_updates            | 3368         |
|    policy_gradient_loss | -0.000955    |
|    value_loss           | 1.28e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 187          |
|    ep_rew_mean          | 99.5         |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 503          |
|    time_elapsed         | 4990         |
|    total_timesteps      | 13841152     |
| train/                  |              |
|    approx_kl            | 0.0028099837 |
|    clip_fraction        | 0.0186       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 608          |
|    n_updates            | 3372         |
|    policy_gradient_loss | 0.000454     |
|    value_loss           | 1.57e+03     |
------------------------------------------

Eval num_timesteps=13850000, episode_reward=-16.82 +/- 101.01

Episode length: 127.80 +/- 53.31

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 128          |
|    mean_reward          | -16.8        |
| time/                   |              |
|    total_timesteps      | 13850000     |
| train/                  |              |
|    approx_kl            | 0.0037500851 |
|    clip_fraction        | 0.024        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.861       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 282          |
|    n_updates            | 3376         |
|    policy_gradient_loss | -0.00127     |
|    value_loss           | 1.8e+03      |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 134      |
|    ep_rew_mean     | 59.9     |
| time/              |          |
|    fps             | 1650     |
|    iterations      | 504      |
|    time_elapsed    | 5002     |
|    total_timesteps | 13857536 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 147         |
|    ep_rew_mean          | 59.2        |
| time/                   |             |
|    fps                  | 1651        |
|    iterations           | 505         |
|    time_elapsed         | 5011        |
|    total_timesteps      | 13873920    |
| train/                  |             |
|    approx_kl            | 0.004137663 |
|    clip_fraction        | 0.0379      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.809      |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | 740         |
|    n_updates            | 3380        |
|    policy_gradient_loss | -0.00103    |
|    value_loss           | 848         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 166          |
|    ep_rew_mean          | 111          |
| time/                   |              |
|    fps                  | 1651         |
|    iterations           | 506          |
|    time_elapsed         | 5021         |
|    total_timesteps      | 13890304     |
| train/                  |              |
|    approx_kl            | 0.0036908775 |
|    clip_fraction        | 0.0298       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.856       |
|    explained_variance   | 0.919        |
|    learning_rate        | 0.0003       |
|    loss                 | 6.93e+03     |
|    n_updates            | 3384         |
|    policy_gradient_loss | -0.000107    |
|    value_loss           | 4.76e+03     |
------------------------------------------

Eval num_timesteps=13900000, episode_reward=-5.42 +/- 121.56

Episode length: 129.25 +/- 45.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 129         |
|    mean_reward          | -5.42       |
| time/                   |             |
|    total_timesteps      | 13900000    |
| train/                  |             |
|    approx_kl            | 0.005222532 |
|    clip_fraction        | 0.0367      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.879      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 313         |
|    n_updates            | 3388        |
|    policy_gradient_loss | -0.000994   |
|    value_loss           | 1.68e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_13900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 146      |
|    ep_rew_mean     | 80.8     |
| time/              |          |
|    fps             | 1650     |
|    iterations      | 507      |
|    time_elapsed    | 5033     |
|    total_timesteps | 13906688 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 153         |
|    ep_rew_mean          | 59.6        |
| time/                   |             |
|    fps                  | 1650        |
|    iterations           | 508         |
|    time_elapsed         | 5043        |
|    total_timesteps      | 13923072    |
| train/                  |             |
|    approx_kl            | 0.004185183 |
|    clip_fraction        | 0.0369      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.86       |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | 171         |
|    n_updates            | 3392        |
|    policy_gradient_loss | -0.00129    |
|    value_loss           | 868         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 184          |
|    ep_rew_mean          | 109          |
| time/                   |              |
|    fps                  | 1650         |
|    iterations           | 509          |
|    time_elapsed         | 5051         |
|    total_timesteps      | 13939456     |
| train/                  |              |
|    approx_kl            | 0.0028318628 |
|    clip_fraction        | 0.0264       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.839       |
|    explained_variance   | 0.939        |
|    learning_rate        | 0.0003       |
|    loss                 | 374          |
|    n_updates            | 3396         |
|    policy_gradient_loss | 8.87e-05     |
|    value_loss           | 1.66e+03     |
------------------------------------------

Eval num_timesteps=13950000, episode_reward=-97.98 +/- 207.75

Episode length: 142.40 +/- 69.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 142          |
|    mean_reward          | -98          |
| time/                   |              |
|    total_timesteps      | 13950000     |
| train/                  |              |
|    approx_kl            | 0.0026521005 |
|    clip_fraction        | 0.0163       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.969        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.21e+03     |
|    n_updates            | 3400         |
|    policy_gradient_loss | 0.000303     |
|    value_loss           | 1.59e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 155      |
|    ep_rew_mean     | 88.1     |
| time/              |          |
|    fps             | 1649     |
|    iterations      | 510      |
|    time_elapsed    | 5064     |
|    total_timesteps | 13955840 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 152          |
|    ep_rew_mean          | 83.5         |
| time/                   |              |
|    fps                  | 1650         |
|    iterations           | 511          |
|    time_elapsed         | 5074         |
|    total_timesteps      | 13972224     |
| train/                  |              |
|    approx_kl            | 0.0031382134 |
|    clip_fraction        | 0.0193       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.807       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 289          |
|    n_updates            | 3404         |
|    policy_gradient_loss | -0.000948    |
|    value_loss           | 1.13e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 174          |
|    ep_rew_mean          | 92.5         |
| time/                   |              |
|    fps                  | 1650         |
|    iterations           | 512          |
|    time_elapsed         | 5083         |
|    total_timesteps      | 13988608     |
| train/                  |              |
|    approx_kl            | 0.0024435152 |
|    clip_fraction        | 0.0214       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.855       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 760          |
|    n_updates            | 3408         |
|    policy_gradient_loss | -0.00137     |
|    value_loss           | 2.13e+03     |
------------------------------------------

Eval num_timesteps=14000000, episode_reward=23.34 +/- 72.36

Episode length: 106.35 +/- 25.76

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 106         |
|    mean_reward          | 23.3        |
| time/                   |             |
|    total_timesteps      | 14000000    |
| train/                  |             |
|    approx_kl            | 0.003162689 |
|    clip_fraction        | 0.0158      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.862      |
|    explained_variance   | 0.978       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.5e+03     |
|    n_updates            | 3412        |
|    policy_gradient_loss | -0.000162   |
|    value_loss           | 1.49e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 14,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 145      |
|    ep_rew_mean     | 90.9     |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 513      |
|    time_elapsed    | 5099     |
|    total_timesteps | 14004992 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 162         |
|    ep_rew_mean          | 93.6        |
| time/                   |             |
|    fps                  | 1648        |
|    iterations           | 514         |
|    time_elapsed         | 5109        |
|    total_timesteps      | 14021376    |
| train/                  |             |
|    approx_kl            | 0.005570427 |
|    clip_fraction        | 0.0299      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.892      |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | 350         |
|    n_updates            | 3416        |
|    policy_gradient_loss | -0.000315   |
|    value_loss           | 1.61e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 81.6         |
| time/                   |              |
|    fps                  | 1648         |
|    iterations           | 515          |
|    time_elapsed         | 5117         |
|    total_timesteps      | 14037760     |
| train/                  |              |
|    approx_kl            | 0.0047303406 |
|    clip_fraction        | 0.0412       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.865       |
|    explained_variance   | 0.951        |
|    learning_rate        | 0.0003       |
|    loss                 | 352          |
|    n_updates            | 3420         |
|    policy_gradient_loss | -0.00144     |
|    value_loss           | 1.51e+03     |
------------------------------------------

Eval num_timesteps=14050000, episode_reward=48.72 +/- 130.87

Episode length: 102.30 +/- 23.03

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 102          |
|    mean_reward          | 48.7         |
| time/                   |              |
|    total_timesteps      | 14050000     |
| train/                  |              |
|    approx_kl            | 0.0038133734 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.88        |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 147          |
|    n_updates            | 3424         |
|    policy_gradient_loss | -0.00132     |
|    value_loss           | 1.09e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 163      |
|    ep_rew_mean     | 85       |
| time/              |          |
|    fps             | 1648     |
|    iterations      | 516      |
|    time_elapsed    | 5129     |
|    total_timesteps | 14054144 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 156         |
|    ep_rew_mean          | 78.6        |
| time/                   |             |
|    fps                  | 1648        |
|    iterations           | 517         |
|    time_elapsed         | 5139        |
|    total_timesteps      | 14070528    |
| train/                  |             |
|    approx_kl            | 0.002755102 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.904      |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | 1e+03       |
|    n_updates            | 3428        |
|    policy_gradient_loss | 0.000805    |
|    value_loss           | 1.58e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 164          |
|    ep_rew_mean          | 48           |
| time/                   |              |
|    fps                  | 1648         |
|    iterations           | 518          |
|    time_elapsed         | 5149         |
|    total_timesteps      | 14086912     |
| train/                  |              |
|    approx_kl            | 0.0027488521 |
|    clip_fraction        | 0.026        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.851       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 151          |
|    n_updates            | 3432         |
|    policy_gradient_loss | -0.000938    |
|    value_loss           | 1.09e+03     |
------------------------------------------

Eval num_timesteps=14100000, episode_reward=2.40 +/- 84.41

Episode length: 124.90 +/- 38.84

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 125          |
|    mean_reward          | 2.4          |
| time/                   |              |
|    total_timesteps      | 14100000     |
| train/                  |              |
|    approx_kl            | 0.0023575216 |
|    clip_fraction        | 0.0201       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.89e+03     |
|    n_updates            | 3436         |
|    policy_gradient_loss | -0.000302    |
|    value_loss           | 3.48e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 166      |
|    ep_rew_mean     | 92.1     |
| time/              |          |
|    fps             | 1647     |
|    iterations      | 519      |
|    time_elapsed    | 5160     |
|    total_timesteps | 14103296 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 76.9         |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 520          |
|    time_elapsed         | 5169         |
|    total_timesteps      | 14119680     |
| train/                  |              |
|    approx_kl            | 0.0023449915 |
|    clip_fraction        | 0.017        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.893       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 706          |
|    n_updates            | 3440         |
|    policy_gradient_loss | 0.000292     |
|    value_loss           | 1.43e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 151          |
|    ep_rew_mean          | 85.8         |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 521          |
|    time_elapsed         | 5179         |
|    total_timesteps      | 14136064     |
| train/                  |              |
|    approx_kl            | 0.0034427857 |
|    clip_fraction        | 0.0193       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 737          |
|    n_updates            | 3444         |
|    policy_gradient_loss | -0.000825    |
|    value_loss           | 1.43e+03     |
------------------------------------------

Eval num_timesteps=14150000, episode_reward=19.70 +/- 96.46

Episode length: 119.60 +/- 43.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 19.7         |
| time/                   |              |
|    total_timesteps      | 14150000     |
| train/                  |              |
|    approx_kl            | 0.0030179191 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 935          |
|    n_updates            | 3448         |
|    policy_gradient_loss | -0.000827    |
|    value_loss           | 1.32e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 163      |
|    ep_rew_mean     | 88.7     |
| time/              |          |
|    fps             | 1647     |
|    iterations      | 522      |
|    time_elapsed    | 5191     |
|    total_timesteps | 14152448 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 149          |
|    ep_rew_mean          | 85.7         |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 523          |
|    time_elapsed         | 5201         |
|    total_timesteps      | 14168832     |
| train/                  |              |
|    approx_kl            | 0.0035265733 |
|    clip_fraction        | 0.0131       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.895       |
|    explained_variance   | 0.916        |
|    learning_rate        | 0.0003       |
|    loss                 | 526          |
|    n_updates            | 3452         |
|    policy_gradient_loss | 0.000127     |
|    value_loss           | 4.6e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 134         |
|    ep_rew_mean          | 72.8        |
| time/                   |             |
|    fps                  | 1647        |
|    iterations           | 524         |
|    time_elapsed         | 5210        |
|    total_timesteps      | 14185216    |
| train/                  |             |
|    approx_kl            | 0.004884088 |
|    clip_fraction        | 0.0394      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.86       |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.04e+03    |
|    n_updates            | 3456        |
|    policy_gradient_loss | -5.74e-05   |
|    value_loss           | 727         |
-----------------------------------------

Eval num_timesteps=14200000, episode_reward=-122.38 +/- 249.80

Episode length: 119.45 +/- 40.18

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | -122         |
| time/                   |              |
|    total_timesteps      | 14200000     |
| train/                  |              |
|    approx_kl            | 0.0032877638 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.945        |
|    learning_rate        | 0.0003       |
|    loss                 | 514          |
|    n_updates            | 3460         |
|    policy_gradient_loss | 0.000343     |
|    value_loss           | 804          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14200000_steps.zip

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 147          |
|    ep_rew_mean          | 77.3         |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 526          |
|    time_elapsed         | 5232         |
|    total_timesteps      | 14217984     |
| train/                  |              |
|    approx_kl            | 0.0045132954 |
|    clip_fraction        | 0.0315       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.855       |
|    explained_variance   | 0.944        |
|    learning_rate        | 0.0003       |
|    loss                 | 319          |
|    n_updates            | 3464         |
|    policy_gradient_loss | -0.000377    |
|    value_loss           | 1.08e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 185          |
|    ep_rew_mean          | 110          |
| time/                   |              |
|    fps                  | 1647         |
|    iterations           | 527          |
|    time_elapsed         | 5242         |
|    total_timesteps      | 14234368     |
| train/                  |              |
|    approx_kl            | 0.0046264757 |
|    clip_fraction        | 0.0416       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.934        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.02e+03     |
|    n_updates            | 3468         |
|    policy_gradient_loss | -0.000347    |
|    value_loss           | 3.25e+03     |
------------------------------------------

Eval num_timesteps=14250000, episode_reward=-53.43 +/- 134.86

Episode length: 127.40 +/- 37.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 127          |
|    mean_reward          | -53.4        |
| time/                   |              |
|    total_timesteps      | 14250000     |
| train/                  |              |
|    approx_kl            | 0.0034578082 |
|    clip_fraction        | 0.0196       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.872       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 401          |
|    n_updates            | 3472         |
|    policy_gradient_loss | -3.53e-05    |
|    value_loss           | 2.12e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 171      |
|    ep_rew_mean     | 68.1     |
| time/              |          |
|    fps             | 1646     |
|    iterations      | 528      |
|    time_elapsed    | 5253     |
|    total_timesteps | 14250752 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 156         |
|    ep_rew_mean          | 86.9        |
| time/                   |             |
|    fps                  | 1646        |
|    iterations           | 529         |
|    time_elapsed         | 5263        |
|    total_timesteps      | 14267136    |
| train/                  |             |
|    approx_kl            | 0.002013278 |
|    clip_fraction        | 0.0126      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.846      |
|    explained_variance   | 0.858       |
|    learning_rate        | 0.0003      |
|    loss                 | 351         |
|    n_updates            | 3476        |
|    policy_gradient_loss | 0.000132    |
|    value_loss           | 5.06e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 137          |
|    ep_rew_mean          | 83.7         |
| time/                   |              |
|    fps                  | 1646         |
|    iterations           | 530          |
|    time_elapsed         | 5272         |
|    total_timesteps      | 14283520     |
| train/                  |              |
|    approx_kl            | 0.0025607464 |
|    clip_fraction        | 0.0213       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.788       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 446          |
|    n_updates            | 3480         |
|    policy_gradient_loss | -0.000101    |
|    value_loss           | 1.1e+03      |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 155        |
|    ep_rew_mean          | 89.9       |
| time/                   |            |
|    fps                  | 1646       |
|    iterations           | 531        |
|    time_elapsed         | 5282       |
|    total_timesteps      | 14299904   |
| train/                  |            |
|    approx_kl            | 0.00377617 |
|    clip_fraction        | 0.0296     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.737     |
|    explained_variance   | 0.863      |
|    learning_rate        | 0.0003     |
|    loss                 | 358        |
|    n_updates            | 3484       |
|    policy_gradient_loss | -0.00137   |
|    value_loss           | 973        |
----------------------------------------

Eval num_timesteps=14300000, episode_reward=-69.60 +/- 307.86

Episode length: 100.35 +/- 30.91

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 100          |
|    mean_reward          | -69.6        |
| time/                   |              |
|    total_timesteps      | 14300000     |
| train/                  |              |
|    approx_kl            | 0.0039294166 |
|    clip_fraction        | 0.021        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.805       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 230          |
|    n_updates            | 3488         |
|    policy_gradient_loss | -0.000628    |
|    value_loss           | 1.45e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 152      |
|    ep_rew_mean     | 96.8     |
| time/              |          |
|    fps             | 1646     |
|    iterations      | 532      |
|    time_elapsed    | 5294     |
|    total_timesteps | 14316288 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 144          |
|    ep_rew_mean          | 108          |
| time/                   |              |
|    fps                  | 1646         |
|    iterations           | 533          |
|    time_elapsed         | 5303         |
|    total_timesteps      | 14332672     |
| train/                  |              |
|    approx_kl            | 0.0034585446 |
|    clip_fraction        | 0.0205       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 393          |
|    n_updates            | 3492         |
|    policy_gradient_loss | -0.000857    |
|    value_loss           | 1.42e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 141         |
|    ep_rew_mean          | 85.3        |
| time/                   |             |
|    fps                  | 1646        |
|    iterations           | 534         |
|    time_elapsed         | 5313        |
|    total_timesteps      | 14349056    |
| train/                  |             |
|    approx_kl            | 0.002148241 |
|    clip_fraction        | 0.00963     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.787      |
|    explained_variance   | 0.921       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.58e+03    |
|    n_updates            | 3496        |
|    policy_gradient_loss | 0.000373    |
|    value_loss           | 1.83e+03    |
-----------------------------------------

Eval num_timesteps=14350000, episode_reward=-144.68 +/- 281.87

Episode length: 121.55 +/- 41.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 122          |
|    mean_reward          | -145         |
| time/                   |              |
|    total_timesteps      | 14350000     |
| train/                  |              |
|    approx_kl            | 0.0039826185 |
|    clip_fraction        | 0.024        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.826       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.06e+03     |
|    n_updates            | 3500         |
|    policy_gradient_loss | 0.000159     |
|    value_loss           | 1.02e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 175      |
|    ep_rew_mean     | 105      |
| time/              |          |
|    fps             | 1646     |
|    iterations      | 535      |
|    time_elapsed    | 5325     |
|    total_timesteps | 14365440 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 192          |
|    ep_rew_mean          | 107          |
| time/                   |              |
|    fps                  | 1646         |
|    iterations           | 536          |
|    time_elapsed         | 5334         |
|    total_timesteps      | 14381824     |
| train/                  |              |
|    approx_kl            | 0.0021931403 |
|    clip_fraction        | 0.0158       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.888       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.14e+03     |
|    n_updates            | 3504         |
|    policy_gradient_loss | -0.000415    |
|    value_loss           | 2.01e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 163          |
|    ep_rew_mean          | 102          |
| time/                   |              |
|    fps                  | 1646         |
|    iterations           | 537          |
|    time_elapsed         | 5343         |
|    total_timesteps      | 14398208     |
| train/                  |              |
|    approx_kl            | 0.0031672562 |
|    clip_fraction        | 0.0209       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 212          |
|    n_updates            | 3508         |
|    policy_gradient_loss | -0.000735    |
|    value_loss           | 1.93e+03     |
------------------------------------------

Eval num_timesteps=14400000, episode_reward=-37.46 +/- 108.95

Episode length: 111.90 +/- 38.12

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 112          |
|    mean_reward          | -37.5        |
| time/                   |              |
|    total_timesteps      | 14400000     |
| train/                  |              |
|    approx_kl            | 0.0041758446 |
|    clip_fraction        | 0.0307       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.824       |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.2e+03      |
|    n_updates            | 3512         |
|    policy_gradient_loss | -0.00212     |
|    value_loss           | 1.56e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 127      |
|    ep_rew_mean     | 82       |
| time/              |          |
|    fps             | 1645     |
|    iterations      | 538      |
|    time_elapsed    | 5355     |
|    total_timesteps | 14414592 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 168          |
|    ep_rew_mean          | 97.2         |
| time/                   |              |
|    fps                  | 1645         |
|    iterations           | 539          |
|    time_elapsed         | 5365         |
|    total_timesteps      | 14430976     |
| train/                  |              |
|    approx_kl            | 0.0039851023 |
|    clip_fraction        | 0.0281       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.8         |
|    explained_variance   | 0.917        |
|    learning_rate        | 0.0003       |
|    loss                 | 245          |
|    n_updates            | 3516         |
|    policy_gradient_loss | -0.000866    |
|    value_loss           | 1.01e+03     |
------------------------------------------

Eval num_timesteps=14450000, episode_reward=-24.69 +/- 159.12

Episode length: 120.15 +/- 42.15

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 120         |
|    mean_reward          | -24.7       |
| time/                   |             |
|    total_timesteps      | 14450000    |
| train/                  |             |
|    approx_kl            | 0.004013248 |
|    clip_fraction        | 0.0168      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.89       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.33e+03    |
|    n_updates            | 3524        |
|    policy_gradient_loss | -0.000153   |
|    value_loss           | 1.73e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 166      |
|    ep_rew_mean     | 73.5     |
| time/              |          |
|    fps             | 1645     |
|    iterations      | 541      |
|    time_elapsed    | 5386     |
|    total_timesteps | 14463744 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 170          |
|    ep_rew_mean          | 93.6         |
| time/                   |              |
|    fps                  | 1645         |
|    iterations           | 542          |
|    time_elapsed         | 5396         |
|    total_timesteps      | 14480128     |
| train/                  |              |
|    approx_kl            | 0.0026610608 |
|    clip_fraction        | 0.0126       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.878       |
|    explained_variance   | 0.942        |
|    learning_rate        | 0.0003       |
|    loss                 | 744          |
|    n_updates            | 3528         |
|    policy_gradient_loss | 0.000352     |
|    value_loss           | 2.6e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 180         |
|    ep_rew_mean          | 117         |
| time/                   |             |
|    fps                  | 1645        |
|    iterations           | 543         |
|    time_elapsed         | 5405        |
|    total_timesteps      | 14496512    |
| train/                  |             |
|    approx_kl            | 0.003410454 |
|    clip_fraction        | 0.0147      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.891      |
|    explained_variance   | 0.974       |
|    learning_rate        | 0.0003      |
|    loss                 | 490         |
|    n_updates            | 3532        |
|    policy_gradient_loss | -0.000761   |
|    value_loss           | 1.7e+03     |
-----------------------------------------

Eval num_timesteps=14500000, episode_reward=-10.21 +/- 104.08

Episode length: 141.50 +/- 52.78

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 142         |
|    mean_reward          | -10.2       |
| time/                   |             |
|    total_timesteps      | 14500000    |
| train/                  |             |
|    approx_kl            | 0.004868724 |
|    clip_fraction        | 0.0514      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.909      |
|    explained_variance   | 0.968       |
|    learning_rate        | 0.0003      |
|    loss                 | 331         |
|    n_updates            | 3536        |
|    policy_gradient_loss | -0.000475   |
|    value_loss           | 1.56e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 155      |
|    ep_rew_mean     | 95.1     |
| time/              |          |
|    fps             | 1645     |
|    iterations      | 544      |
|    time_elapsed    | 5418     |
|    total_timesteps | 14512896 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 182         |
|    ep_rew_mean          | 97.9        |
| time/                   |             |
|    fps                  | 1645        |
|    iterations           | 545         |
|    time_elapsed         | 5427        |
|    total_timesteps      | 14529280    |
| train/                  |             |
|    approx_kl            | 0.005042023 |
|    clip_fraction        | 0.0318      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.926      |
|    explained_variance   | 0.864       |
|    learning_rate        | 0.0003      |
|    loss                 | 812         |
|    n_updates            | 3540        |
|    policy_gradient_loss | -0.00139    |
|    value_loss           | 7.92e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 159          |
|    ep_rew_mean          | 82.3         |
| time/                   |              |
|    fps                  | 1645         |
|    iterations           | 546          |
|    time_elapsed         | 5436         |
|    total_timesteps      | 14545664     |
| train/                  |              |
|    approx_kl            | 0.0028708098 |
|    clip_fraction        | 0.0158       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.964        |
|    learning_rate        | 0.0003       |
|    loss                 | 584          |
|    n_updates            | 3544         |
|    policy_gradient_loss | -0.00102     |
|    value_loss           | 1.39e+03     |
------------------------------------------

Eval num_timesteps=14550000, episode_reward=-232.88 +/- 284.40

Episode length: 133.45 +/- 48.42

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 133         |
|    mean_reward          | -233        |
| time/                   |             |
|    total_timesteps      | 14550000    |
| train/                  |             |
|    approx_kl            | 0.004291882 |
|    clip_fraction        | 0.0324      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.824      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 156         |
|    n_updates            | 3548        |
|    policy_gradient_loss | -0.00247    |
|    value_loss           | 1.18e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 152      |
|    ep_rew_mean     | 78.9     |
| time/              |          |
|    fps             | 1644     |
|    iterations      | 547      |
|    time_elapsed    | 5448     |
|    total_timesteps | 14562048 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 166          |
|    ep_rew_mean          | 100          |
| time/                   |              |
|    fps                  | 1644         |
|    iterations           | 548          |
|    time_elapsed         | 5458         |
|    total_timesteps      | 14578432     |
| train/                  |              |
|    approx_kl            | 0.0042894753 |
|    clip_fraction        | 0.047        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.804       |
|    explained_variance   | 0.907        |
|    learning_rate        | 0.0003       |
|    loss                 | 313          |
|    n_updates            | 3552         |
|    policy_gradient_loss | -0.00141     |
|    value_loss           | 907          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 151          |
|    ep_rew_mean          | 75.4         |
| time/                   |              |
|    fps                  | 1645         |
|    iterations           | 549          |
|    time_elapsed         | 5467         |
|    total_timesteps      | 14594816     |
| train/                  |              |
|    approx_kl            | 0.0038310606 |
|    clip_fraction        | 0.0224       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.898       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 216          |
|    n_updates            | 3556         |
|    policy_gradient_loss | -3.42e-05    |
|    value_loss           | 1.46e+03     |
------------------------------------------

Eval num_timesteps=14600000, episode_reward=-132.76 +/- 332.17

Episode length: 132.50 +/- 58.30

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 132          |
|    mean_reward          | -133         |
| time/                   |              |
|    total_timesteps      | 14600000     |
| train/                  |              |
|    approx_kl            | 0.0029204823 |
|    clip_fraction        | 0.0149       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.83        |
|    explained_variance   | 0.786        |
|    learning_rate        | 0.0003       |
|    loss                 | 996          |
|    n_updates            | 3560         |
|    policy_gradient_loss | -0.000168    |
|    value_loss           | 1.78e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 184      |
|    ep_rew_mean     | 78.5     |
| time/              |          |
|    fps             | 1644     |
|    iterations      | 550      |
|    time_elapsed    | 5479     |
|    total_timesteps | 14611200 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 219         |
|    ep_rew_mean          | 139         |
| time/                   |             |
|    fps                  | 1644        |
|    iterations           | 551         |
|    time_elapsed         | 5489        |
|    total_timesteps      | 14627584    |
| train/                  |             |
|    approx_kl            | 0.003073095 |
|    clip_fraction        | 0.0224      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.873      |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | 608         |
|    n_updates            | 3564        |
|    policy_gradient_loss | -0.000294   |
|    value_loss           | 3.93e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 170          |
|    ep_rew_mean          | 73.1         |
| time/                   |              |
|    fps                  | 1644         |
|    iterations           | 552          |
|    time_elapsed         | 5499         |
|    total_timesteps      | 14643968     |
| train/                  |              |
|    approx_kl            | 0.0037153428 |
|    clip_fraction        | 0.0301       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.9         |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 810          |
|    n_updates            | 3568         |
|    policy_gradient_loss | -0.000492    |
|    value_loss           | 2.24e+03     |
------------------------------------------

Eval num_timesteps=14650000, episode_reward=-181.44 +/- 400.27

Episode length: 144.00 +/- 47.92

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 144         |
|    mean_reward          | -181        |
| time/                   |             |
|    total_timesteps      | 14650000    |
| train/                  |             |
|    approx_kl            | 0.002708118 |
|    clip_fraction        | 0.0149      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.832      |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.05e+03    |
|    n_updates            | 3572        |
|    policy_gradient_loss | -0.000563   |
|    value_loss           | 3.15e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 159      |
|    ep_rew_mean     | 88.5     |
| time/              |          |
|    fps             | 1643     |
|    iterations      | 553      |
|    time_elapsed    | 5511     |
|    total_timesteps | 14660352 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 167         |
|    ep_rew_mean          | 81.1        |
| time/                   |             |
|    fps                  | 1644        |
|    iterations           | 554         |
|    time_elapsed         | 5520        |
|    total_timesteps      | 14676736    |
| train/                  |             |
|    approx_kl            | 0.004310645 |
|    clip_fraction        | 0.0275      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.861      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 379         |
|    n_updates            | 3576        |
|    policy_gradient_loss | -0.00163    |
|    value_loss           | 1.36e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 147          |
|    ep_rew_mean          | 75.9         |
| time/                   |              |
|    fps                  | 1644         |
|    iterations           | 555          |
|    time_elapsed         | 5529         |
|    total_timesteps      | 14693120     |
| train/                  |              |
|    approx_kl            | 0.0035717126 |
|    clip_fraction        | 0.0127       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.858       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 867          |
|    n_updates            | 3580         |
|    policy_gradient_loss | -0.000269    |
|    value_loss           | 933          |
------------------------------------------

Eval num_timesteps=14700000, episode_reward=-191.75 +/- 258.38

Episode length: 125.50 +/- 47.79

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 126          |
|    mean_reward          | -192         |
| time/                   |              |
|    total_timesteps      | 14700000     |
| train/                  |              |
|    approx_kl            | 0.0042857635 |
|    clip_fraction        | 0.0326       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.814       |
|    explained_variance   | 0.929        |
|    learning_rate        | 0.0003       |
|    loss                 | 272          |
|    n_updates            | 3584         |
|    policy_gradient_loss | -0.00247     |
|    value_loss           | 795          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 153      |
|    ep_rew_mean     | 59.4     |
| time/              |          |
|    fps             | 1643     |
|    iterations      | 556      |
|    time_elapsed    | 5541     |
|    total_timesteps | 14709504 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 142          |
|    ep_rew_mean          | 81.9         |
| time/                   |              |
|    fps                  | 1643         |
|    iterations           | 557          |
|    time_elapsed         | 5551         |
|    total_timesteps      | 14725888     |
| train/                  |              |
|    approx_kl            | 0.0030163657 |
|    clip_fraction        | 0.0163       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.808       |
|    explained_variance   | 0.831        |
|    learning_rate        | 0.0003       |
|    loss                 | 203          |
|    n_updates            | 3588         |
|    policy_gradient_loss | -0.000625    |
|    value_loss           | 2.4e+03      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 160         |
|    ep_rew_mean          | 76.4        |
| time/                   |             |
|    fps                  | 1643        |
|    iterations           | 558         |
|    time_elapsed         | 5561        |
|    total_timesteps      | 14742272    |
| train/                  |             |
|    approx_kl            | 0.004543858 |
|    clip_fraction        | 0.0417      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.84       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 398         |
|    n_updates            | 3592        |
|    policy_gradient_loss | -0.00213    |
|    value_loss           | 969         |
-----------------------------------------

Eval num_timesteps=14750000, episode_reward=-203.03 +/- 273.73

Episode length: 149.90 +/- 64.25

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 150         |
|    mean_reward          | -203        |
| time/                   |             |
|    total_timesteps      | 14750000    |
| train/                  |             |
|    approx_kl            | 0.005426382 |
|    clip_fraction        | 0.0373      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.903      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.02e+03    |
|    n_updates            | 3596        |
|    policy_gradient_loss | -0.00108    |
|    value_loss           | 1.66e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 202      |
|    ep_rew_mean     | 113      |
| time/              |          |
|    fps             | 1643     |
|    iterations      | 559      |
|    time_elapsed    | 5573     |
|    total_timesteps | 14758656 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 180         |
|    ep_rew_mean          | 82.6        |
| time/                   |             |
|    fps                  | 1643        |
|    iterations           | 560         |
|    time_elapsed         | 5583        |
|    total_timesteps      | 14775040    |
| train/                  |             |
|    approx_kl            | 0.005713737 |
|    clip_fraction        | 0.0293      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.888      |
|    explained_variance   | 0.864       |
|    learning_rate        | 0.0003      |
|    loss                 | 931         |
|    n_updates            | 3600        |
|    policy_gradient_loss | -0.00057    |
|    value_loss           | 1.26e+04    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 198         |
|    ep_rew_mean          | 86.6        |
| time/                   |             |
|    fps                  | 1643        |
|    iterations           | 561         |
|    time_elapsed         | 5593        |
|    total_timesteps      | 14791424    |
| train/                  |             |
|    approx_kl            | 0.004994335 |
|    clip_fraction        | 0.0285      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.819      |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | 752         |
|    n_updates            | 3604        |
|    policy_gradient_loss | -0.00201    |
|    value_loss           | 1.11e+03    |
-----------------------------------------

Eval num_timesteps=14800000, episode_reward=-25.83 +/- 239.25

Episode length: 141.55 +/- 52.94

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 142         |
|    mean_reward          | -25.8       |
| time/                   |             |
|    total_timesteps      | 14800000    |
| train/                  |             |
|    approx_kl            | 0.004309421 |
|    clip_fraction        | 0.0196      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.841      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 398         |
|    n_updates            | 3608        |
|    policy_gradient_loss | -0.000811   |
|    value_loss           | 1.94e+03    |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 169      |
|    ep_rew_mean     | 84.6     |
| time/              |          |
|    fps             | 1642     |
|    iterations      | 562      |
|    time_elapsed    | 5605     |
|    total_timesteps | 14807808 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 169          |
|    ep_rew_mean          | 88.9         |
| time/                   |              |
|    fps                  | 1643         |
|    iterations           | 564          |
|    time_elapsed         | 5623         |
|    total_timesteps      | 14840576     |
| train/                  |              |
|    approx_kl            | 0.0032712622 |
|    clip_fraction        | 0.0201       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.848       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.19e+03     |
|    n_updates            | 3616         |
|    policy_gradient_loss | -0.000196    |
|    value_loss           | 1.04e+03     |
------------------------------------------

Eval num_timesteps=14850000, episode_reward=10.45 +/- 133.69

Episode length: 119.80 +/- 59.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 120          |
|    mean_reward          | 10.5         |
| time/                   |              |
|    total_timesteps      | 14850000     |
| train/                  |              |
|    approx_kl            | 0.0036940258 |
|    clip_fraction        | 0.0292       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.921       |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 673          |
|    n_updates            | 3620         |
|    policy_gradient_loss | -0.00063     |
|    value_loss           | 1.36e+03     |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 173      |
|    ep_rew_mean     | 91.4     |
| time/              |          |
|    fps             | 1642     |
|    iterations      | 565      |
|    time_elapsed    | 5636     |
|    total_timesteps | 14856960 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 178          |
|    ep_rew_mean          | 93.3         |
| time/                   |              |
|    fps                  | 1642         |
|    iterations           | 566          |
|    time_elapsed         | 5646         |
|    total_timesteps      | 14873344     |
| train/                  |              |
|    approx_kl            | 0.0037947127 |
|    clip_fraction        | 0.0304       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.871       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 251          |
|    n_updates            | 3624         |
|    policy_gradient_loss | -0.00165     |
|    value_loss           | 1.29e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 140          |
|    ep_rew_mean          | 59.4         |
| time/                   |              |
|    fps                  | 1642         |
|    iterations           | 567          |
|    time_elapsed         | 5655         |
|    total_timesteps      | 14889728     |
| train/                  |              |
|    approx_kl            | 0.0034791068 |
|    clip_fraction        | 0.00766      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 338          |
|    n_updates            | 3628         |
|    policy_gradient_loss | -6.16e-06    |
|    value_loss           | 1.8e+03      |
------------------------------------------

Eval num_timesteps=14900000, episode_reward=-28.06 +/- 204.28

Episode length: 118.75 +/- 47.43

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 119          |
|    mean_reward          | -28.1        |
| time/                   |              |
|    total_timesteps      | 14900000     |
| train/                  |              |
|    approx_kl            | 0.0034796651 |
|    clip_fraction        | 0.0298       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.836       |
|    explained_variance   | 0.958        |
|    learning_rate        | 0.0003       |
|    loss                 | 189          |
|    n_updates            | 3632         |
|    policy_gradient_loss | -0.000152    |
|    value_loss           | 657          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 160      |
|    ep_rew_mean     | 68.9     |
| time/              |          |
|    fps             | 1642     |
|    iterations      | 568      |
|    time_elapsed    | 5666     |
|    total_timesteps | 14906112 |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 194        |
|    ep_rew_mean          | 114        |
| time/                   |            |
|    fps                  | 1642       |
|    iterations           | 569        |
|    time_elapsed         | 5676       |
|    total_timesteps      | 14922496   |
| train/                  |            |
|    approx_kl            | 0.00404083 |
|    clip_fraction        | 0.0283     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.878     |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | 702        |
|    n_updates            | 3636       |
|    policy_gradient_loss | -0.000638  |
|    value_loss           | 3.37e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 157         |
|    ep_rew_mean          | 67.7        |
| time/                   |             |
|    fps                  | 1642        |
|    iterations           | 570         |
|    time_elapsed         | 5686        |
|    total_timesteps      | 14938880    |
| train/                  |             |
|    approx_kl            | 0.004891687 |
|    clip_fraction        | 0.0312      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.909      |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.25e+03    |
|    n_updates            | 3640        |
|    policy_gradient_loss | -0.000459   |
|    value_loss           | 1.94e+03    |
-----------------------------------------

Eval num_timesteps=14950000, episode_reward=81.61 +/- 257.70

Episode length: 162.65 +/- 65.10

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 163         |
|    mean_reward          | 81.6        |
| time/                   |             |
|    total_timesteps      | 14950000    |
| train/                  |             |
|    approx_kl            | 0.003046778 |
|    clip_fraction        | 0.0191      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.844      |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | 794         |
|    n_updates            | 3644        |
|    policy_gradient_loss | -0.000302   |
|    value_loss           | 883         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 174      |
|    ep_rew_mean     | 94.3     |
| time/              |          |
|    fps             | 1641     |
|    iterations      | 571      |
|    time_elapsed    | 5698     |
|    total_timesteps | 14955264 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 170          |
|    ep_rew_mean          | 71.4         |
| time/                   |              |
|    fps                  | 1641         |
|    iterations           | 572          |
|    time_elapsed         | 5707         |
|    total_timesteps      | 14971648     |
| train/                  |              |
|    approx_kl            | 0.0028620209 |
|    clip_fraction        | 0.0146       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.854       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.05e+03     |
|    n_updates            | 3648         |
|    policy_gradient_loss | -0.000195    |
|    value_loss           | 1.4e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 162          |
|    ep_rew_mean          | 58.6         |
| time/                   |              |
|    fps                  | 1641         |
|    iterations           | 573          |
|    time_elapsed         | 5717         |
|    total_timesteps      | 14988032     |
| train/                  |              |
|    approx_kl            | 0.0029437386 |
|    clip_fraction        | 0.0121       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.949        |
|    learning_rate        | 0.0003       |
|    loss                 | 624          |
|    n_updates            | 3652         |
|    policy_gradient_loss | 0.000612     |
|    value_loss           | 2.28e+03     |
------------------------------------------

Eval num_timesteps=15000000, episode_reward=-39.32 +/- 285.67

Episode length: 143.00 +/- 55.18

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 143          |
|    mean_reward          | -39.3        |
| time/                   |              |
|    total_timesteps      | 15000000     |
| train/                  |              |
|    approx_kl            | 0.0036384822 |
|    clip_fraction        | 0.0303       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.796       |
|    explained_variance   | 0.774        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.76e+03     |
|    n_updates            | 3656         |
|    policy_gradient_loss | -0.000825    |
|    value_loss           | 2.37e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15000000_steps.zip

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...atest_flip_checkpoint.zip: 100%|##########|  474kB /  474kB

Uploaded Hub checkpoint: 15,000,000 steps

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 168      |
|    ep_rew_mean     | 80.4     |
| time/              |          |
|    fps             | 1640     |
|    iterations      | 574      |
|    time_elapsed    | 5733     |
|    total_timesteps | 15004416 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 158          |
|    ep_rew_mean          | 77.3         |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 575          |
|    time_elapsed         | 5743         |
|    total_timesteps      | 15020800     |
| train/                  |              |
|    approx_kl            | 0.0039242357 |
|    clip_fraction        | 0.0321       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.822       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29e+03     |
|    n_updates            | 3660         |
|    policy_gradient_loss | -0.000968    |
|    value_loss           | 999          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 174          |
|    ep_rew_mean          | 101          |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 576          |
|    time_elapsed         | 5753         |
|    total_timesteps      | 15037184     |
| train/                  |              |
|    approx_kl            | 0.0036927764 |
|    clip_fraction        | 0.0304       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.941        |
|    learning_rate        | 0.0003       |
|    loss                 | 525          |
|    n_updates            | 3664         |
|    policy_gradient_loss | -0.000822    |
|    value_loss           | 1.14e+03     |
------------------------------------------

Eval num_timesteps=15050000, episode_reward=-135.34 +/- 340.06

Episode length: 154.95 +/- 61.64

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 155         |
|    mean_reward          | -135        |
| time/                   |             |
|    total_timesteps      | 15050000    |
| train/                  |             |
|    approx_kl            | 0.002535042 |
|    clip_fraction        | 0.00999     |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.808      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 848         |
|    n_updates            | 3668        |
|    policy_gradient_loss | -0.000492   |
|    value_loss           | 1.59e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 170      |
|    ep_rew_mean     | 114      |
| time/              |          |
|    fps             | 1639     |
|    iterations      | 577      |
|    time_elapsed    | 5765     |
|    total_timesteps | 15053568 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 157          |
|    ep_rew_mean          | 70.2         |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 578          |
|    time_elapsed         | 5774         |
|    total_timesteps      | 15069952     |
| train/                  |              |
|    approx_kl            | 0.0041933362 |
|    clip_fraction        | 0.0347       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.856       |
|    explained_variance   | 0.926        |
|    learning_rate        | 0.0003       |
|    loss                 | 409          |
|    n_updates            | 3672         |
|    policy_gradient_loss | -0.000589    |
|    value_loss           | 2.07e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 185          |
|    ep_rew_mean          | 81.6         |
| time/                   |              |
|    fps                  | 1640         |
|    iterations           | 579          |
|    time_elapsed         | 5784         |
|    total_timesteps      | 15086336     |
| train/                  |              |
|    approx_kl            | 0.0025064808 |
|    clip_fraction        | 0.00993      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.785       |
|    explained_variance   | 0.933        |
|    learning_rate        | 0.0003       |
|    loss                 | 360          |
|    n_updates            | 3676         |
|    policy_gradient_loss | 0.000254     |
|    value_loss           | 1.63e+03     |
------------------------------------------

Eval num_timesteps=15100000, episode_reward=-45.85 +/- 164.39

Episode length: 143.15 +/- 44.18

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 143          |
|    mean_reward          | -45.9        |
| time/                   |              |
|    total_timesteps      | 15100000     |
| train/                  |              |
|    approx_kl            | 0.0032198532 |
|    clip_fraction        | 0.00925      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.854       |
|    explained_variance   | 0.902        |
|    learning_rate        | 0.0003       |
|    loss                 | 538          |
|    n_updates            | 3680         |
|    policy_gradient_loss | -0.000113    |
|    value_loss           | 3.81e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 186      |
|    ep_rew_mean     | 64.4     |
| time/              |          |
|    fps             | 1639     |
|    iterations      | 580      |
|    time_elapsed    | 5796     |
|    total_timesteps | 15102720 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 134          |
|    ep_rew_mean          | 46.1         |
| time/                   |              |
|    fps                  | 1639         |
|    iterations           | 581          |
|    time_elapsed         | 5806         |
|    total_timesteps      | 15119104     |
| train/                  |              |
|    approx_kl            | 0.0038826026 |
|    clip_fraction        | 0.024        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.799       |
|    explained_variance   | 0.885        |
|    learning_rate        | 0.0003       |
|    loss                 | 313          |
|    n_updates            | 3684         |
|    policy_gradient_loss | -0.000904    |
|    value_loss           | 5.35e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 159          |
|    ep_rew_mean          | 50.1         |
| time/                   |              |
|    fps                  | 1639         |
|    iterations           | 582          |
|    time_elapsed         | 5815         |
|    total_timesteps      | 15135488     |
| train/                  |              |
|    approx_kl            | 0.0044698655 |
|    clip_fraction        | 0.0329       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.763       |
|    explained_variance   | 0.79         |
|    learning_rate        | 0.0003       |
|    loss                 | 278          |
|    n_updates            | 3688         |
|    policy_gradient_loss | -0.00125     |
|    value_loss           | 3.29e+03     |
------------------------------------------

Eval num_timesteps=15150000, episode_reward=28.50 +/- 81.64

Episode length: 124.90 +/- 51.02

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 125         |
|    mean_reward          | 28.5        |
| time/                   |             |
|    total_timesteps      | 15150000    |
| train/                  |             |
|    approx_kl            | 0.003504288 |
|    clip_fraction        | 0.0133      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.887       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.02e+03    |
|    n_updates            | 3692        |
|    policy_gradient_loss | -2.6e-05    |
|    value_loss           | 6.56e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 177      |
|    ep_rew_mean     | 98.3     |
| time/              |          |
|    fps             | 1639     |
|    iterations      | 583      |
|    time_elapsed    | 5826     |
|    total_timesteps | 15151872 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 147         |
|    ep_rew_mean          | 75.2        |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 584         |
|    time_elapsed         | 5836        |
|    total_timesteps      | 15168256    |
| train/                  |             |
|    approx_kl            | 0.004291817 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 517         |
|    n_updates            | 3696        |
|    policy_gradient_loss | -0.0004     |
|    value_loss           | 1.36e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 169         |
|    ep_rew_mean          | 70.9        |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 585         |
|    time_elapsed         | 5846        |
|    total_timesteps      | 15184640    |
| train/                  |             |
|    approx_kl            | 0.003826456 |
|    clip_fraction        | 0.022       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.858      |
|    explained_variance   | 0.943       |
|    learning_rate        | 0.0003      |
|    loss                 | 275         |
|    n_updates            | 3700        |
|    policy_gradient_loss | -0.000883   |
|    value_loss           | 1.29e+03    |
-----------------------------------------

Eval num_timesteps=15200000, episode_reward=23.72 +/- 109.74

Episode length: 132.65 +/- 60.34

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 133          |
|    mean_reward          | 23.7         |
| time/                   |              |
|    total_timesteps      | 15200000     |
| train/                  |              |
|    approx_kl            | 0.0042813793 |
|    clip_fraction        | 0.0323       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.845       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 359          |
|    n_updates            | 3704         |
|    policy_gradient_loss | -0.00114     |
|    value_loss           | 891          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 165      |
|    ep_rew_mean     | 54.3     |
| time/              |          |
|    fps             | 1638     |
|    iterations      | 586      |
|    time_elapsed    | 5858     |
|    total_timesteps | 15201024 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 171         |
|    ep_rew_mean          | 94.3        |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 587         |
|    time_elapsed         | 5866        |
|    total_timesteps      | 15217408    |
| train/                  |             |
|    approx_kl            | 0.004303768 |
|    clip_fraction        | 0.0466      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.768      |
|    explained_variance   | 0.894       |
|    learning_rate        | 0.0003      |
|    loss                 | 525         |
|    n_updates            | 3708        |
|    policy_gradient_loss | -0.00138    |
|    value_loss           | 1.45e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 187         |
|    ep_rew_mean          | 109         |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 588         |
|    time_elapsed         | 5876        |
|    total_timesteps      | 15233792    |
| train/                  |             |
|    approx_kl            | 0.003007337 |
|    clip_fraction        | 0.0161      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.857      |
|    explained_variance   | 0.885       |
|    learning_rate        | 0.0003      |
|    loss                 | 890         |
|    n_updates            | 3712        |
|    policy_gradient_loss | 0.000558    |
|    value_loss           | 1.27e+03    |
-----------------------------------------

Eval num_timesteps=15250000, episode_reward=23.12 +/- 165.04

Episode length: 152.00 +/- 70.98

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 152         |
|    mean_reward          | 23.1        |
| time/                   |             |
|    total_timesteps      | 15250000    |
| train/                  |             |
|    approx_kl            | 0.003399196 |
|    clip_fraction        | 0.0152      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.855      |
|    explained_variance   | 0.968       |
|    learning_rate        | 0.0003      |
|    loss                 | 335         |
|    n_updates            | 3716        |
|    policy_gradient_loss | -0.000709   |
|    value_loss           | 1.55e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 188      |
|    ep_rew_mean     | 99.4     |
| time/              |          |
|    fps             | 1638     |
|    iterations      | 589      |
|    time_elapsed    | 5889     |
|    total_timesteps | 15250176 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 189          |
|    ep_rew_mean          | 98.2         |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 590          |
|    time_elapsed         | 5898         |
|    total_timesteps      | 15266560     |
| train/                  |              |
|    approx_kl            | 0.0028381841 |
|    clip_fraction        | 0.0136       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 198          |
|    n_updates            | 3720         |
|    policy_gradient_loss | 0.000529     |
|    value_loss           | 1.57e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 177         |
|    ep_rew_mean          | 95.7        |
| time/                   |             |
|    fps                  | 1639        |
|    iterations           | 591         |
|    time_elapsed         | 5907        |
|    total_timesteps      | 15282944    |
| train/                  |             |
|    approx_kl            | 0.003264633 |
|    clip_fraction        | 0.0258      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.844      |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | 355         |
|    n_updates            | 3724        |
|    policy_gradient_loss | -0.00114    |
|    value_loss           | 1.24e+03    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 159          |
|    ep_rew_mean          | 80.6         |
| time/                   |              |
|    fps                  | 1639         |
|    iterations           | 592          |
|    time_elapsed         | 5917         |
|    total_timesteps      | 15299328     |
| train/                  |              |
|    approx_kl            | 0.0037367535 |
|    clip_fraction        | 0.0388       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 174          |
|    n_updates            | 3728         |
|    policy_gradient_loss | -0.000577    |
|    value_loss           | 1.24e+03     |
------------------------------------------

Eval num_timesteps=15300000, episode_reward=35.62 +/- 208.77

Episode length: 153.80 +/- 55.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 154          |
|    mean_reward          | 35.6         |
| time/                   |              |
|    total_timesteps      | 15300000     |
| train/                  |              |
|    approx_kl            | 0.0026567315 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.942        |
|    learning_rate        | 0.0003       |
|    loss                 | 174          |
|    n_updates            | 3732         |
|    policy_gradient_loss | 0.000298     |
|    value_loss           | 1.07e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 176      |
|    ep_rew_mean     | 84.8     |
| time/              |          |
|    fps             | 1638     |
|    iterations      | 593      |
|    time_elapsed    | 5929     |
|    total_timesteps | 15315712 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 178         |
|    ep_rew_mean          | 86.3        |
| time/                   |             |
|    fps                  | 1638        |
|    iterations           | 594         |
|    time_elapsed         | 5939        |
|    total_timesteps      | 15332096    |
| train/                  |             |
|    approx_kl            | 0.003459656 |
|    clip_fraction        | 0.0283      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.906      |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | 532         |
|    n_updates            | 3736        |
|    policy_gradient_loss | 1.75e-05    |
|    value_loss           | 1.47e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 152         |
|    ep_rew_mean          | 68.8        |
| time/                   |             |
|    fps                  | 1638        |
|    iterations           | 595         |
|    time_elapsed         | 5947        |
|    total_timesteps      | 15348480    |
| train/                  |             |
|    approx_kl            | 0.004474935 |
|    clip_fraction        | 0.0241      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.855      |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08e+04    |
|    n_updates            | 3740        |
|    policy_gradient_loss | -2.15e-05   |
|    value_loss           | 5.51e+03    |
-----------------------------------------

Eval num_timesteps=15350000, episode_reward=-95.93 +/- 283.32

Episode length: 157.25 +/- 55.40

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 157          |
|    mean_reward          | -95.9        |
| time/                   |              |
|    total_timesteps      | 15350000     |
| train/                  |              |
|    approx_kl            | 0.0024999175 |
|    clip_fraction        | 0.0236       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.887       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 235          |
|    n_updates            | 3744         |
|    policy_gradient_loss | 0.000168     |
|    value_loss           | 780          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 161      |
|    ep_rew_mean     | 66.4     |
| time/              |          |
|    fps             | 1638     |
|    iterations      | 596      |
|    time_elapsed    | 5960     |
|    total_timesteps | 15364864 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 185          |
|    ep_rew_mean          | 69.1         |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 597          |
|    time_elapsed         | 5970         |
|    total_timesteps      | 15381248     |
| train/                  |              |
|    approx_kl            | 0.0041276575 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.94         |
|    learning_rate        | 0.0003       |
|    loss                 | 6.52e+03     |
|    n_updates            | 3748         |
|    policy_gradient_loss | -0.000928    |
|    value_loss           | 2.55e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 194          |
|    ep_rew_mean          | 84.4         |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 598          |
|    time_elapsed         | 5980         |
|    total_timesteps      | 15397632     |
| train/                  |              |
|    approx_kl            | 0.0029746783 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.942       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 632          |
|    n_updates            | 3752         |
|    policy_gradient_loss | -0.000102    |
|    value_loss           | 2.06e+03     |
------------------------------------------

Eval num_timesteps=15400000, episode_reward=42.74 +/- 92.01

Episode length: 133.45 +/- 64.98

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 133          |
|    mean_reward          | 42.7         |
| time/                   |              |
|    total_timesteps      | 15400000     |
| train/                  |              |
|    approx_kl            | 0.0034799601 |
|    clip_fraction        | 0.0261       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.928       |
|    explained_variance   | 0.919        |
|    learning_rate        | 0.0003       |
|    loss                 | 435          |
|    n_updates            | 3756         |
|    policy_gradient_loss | -0.000618    |
|    value_loss           | 5.07e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 162      |
|    ep_rew_mean     | 71.6     |
| time/              |          |
|    fps             | 1637     |
|    iterations      | 599      |
|    time_elapsed    | 5992     |
|    total_timesteps | 15414016 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 164          |
|    ep_rew_mean          | 69           |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 600          |
|    time_elapsed         | 6000         |
|    total_timesteps      | 15430400     |
| train/                  |              |
|    approx_kl            | 0.0029932316 |
|    clip_fraction        | 0.0177       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.853       |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.19e+03     |
|    n_updates            | 3760         |
|    policy_gradient_loss | -0.000928    |
|    value_loss           | 1.14e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 161          |
|    ep_rew_mean          | 56.4         |
| time/                   |              |
|    fps                  | 1638         |
|    iterations           | 601          |
|    time_elapsed         | 6010         |
|    total_timesteps      | 15446784     |
| train/                  |              |
|    approx_kl            | 0.0050845863 |
|    clip_fraction        | 0.0387       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.882       |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 643          |
|    n_updates            | 3764         |
|    policy_gradient_loss | -0.00115     |
|    value_loss           | 913          |
------------------------------------------

Eval num_timesteps=15450000, episode_reward=-33.95 +/- 124.49

Episode length: 160.05 +/- 69.83

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 160          |
|    mean_reward          | -34          |
| time/                   |              |
|    total_timesteps      | 15450000     |
| train/                  |              |
|    approx_kl            | 0.0031245477 |
|    clip_fraction        | 0.0149       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.877       |
|    explained_variance   | 0.894        |
|    learning_rate        | 0.0003       |
|    loss                 | 310          |
|    n_updates            | 3768         |
|    policy_gradient_loss | 0.000133     |
|    value_loss           | 2.8e+03      |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 182      |
|    ep_rew_mean     | 101      |
| time/              |          |
|    fps             | 1637     |
|    iterations      | 602      |
|    time_elapsed    | 6023     |
|    total_timesteps | 15463168 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 194          |
|    ep_rew_mean          | 95           |
| time/                   |              |
|    fps                  | 1637         |
|    iterations           | 603          |
|    time_elapsed         | 6033         |
|    total_timesteps      | 15479552     |
| train/                  |              |
|    approx_kl            | 0.0033902866 |
|    clip_fraction        | 0.023        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.856       |
|    explained_variance   | 0.951        |
|    learning_rate        | 0.0003       |
|    loss                 | 790          |
|    n_updates            | 3772         |
|    policy_gradient_loss | -0.00115     |
|    value_loss           | 1.3e+03      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 200          |
|    ep_rew_mean          | 87.9         |
| time/                   |              |
|    fps                  | 1637         |
|    iterations           | 604          |
|    time_elapsed         | 6041         |
|    total_timesteps      | 15495936     |
| train/                  |              |
|    approx_kl            | 0.0027329703 |
|    clip_fraction        | 0.0154       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.943       |
|    explained_variance   | 0.941        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.65e+03     |
|    n_updates            | 3776         |
|    policy_gradient_loss | 0.000159     |
|    value_loss           | 4.25e+03     |
------------------------------------------

Eval num_timesteps=15500000, episode_reward=29.32 +/- 146.37

Episode length: 144.50 +/- 64.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 144          |
|    mean_reward          | 29.3         |
| time/                   |              |
|    total_timesteps      | 15500000     |
| train/                  |              |
|    approx_kl            | 0.0035722172 |
|    clip_fraction        | 0.0206       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.869       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 422          |
|    n_updates            | 3780         |
|    policy_gradient_loss | -0.000863    |
|    value_loss           | 1.61e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 185      |
|    ep_rew_mean     | 77.5     |
| time/              |          |
|    fps             | 1637     |
|    iterations      | 605      |
|    time_elapsed    | 6054     |
|    total_timesteps | 15512320 |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 194          |
|    ep_rew_mean          | 88.9         |
| time/                   |              |
|    fps                  | 1637         |
|    iterations           | 606          |
|    time_elapsed         | 6064         |
|    total_timesteps      | 15528704     |
| train/                  |              |
|    approx_kl            | 0.0025337462 |
|    clip_fraction        | 0.0182       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.844       |
|    explained_variance   | 0.948        |
|    learning_rate        | 0.0003       |
|    loss                 | 541          |
|    n_updates            | 3784         |
|    policy_gradient_loss | 0.000286     |
|    value_loss           | 1.43e+03     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 183          |
|    ep_rew_mean          | 75.5         |
| time/                   |              |
|    fps                  | 1637         |
|    iterations           | 607          |
|    time_elapsed         | 6074         |
|    total_timesteps      | 15545088     |
| train/                  |              |
|    approx_kl            | 0.0030341358 |
|    clip_fraction        | 0.0148       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.915       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 365          |
|    n_updates            | 3788         |
|    policy_gradient_loss | 0.00022      |
|    value_loss           | 1.36e+03     |
------------------------------------------

Eval num_timesteps=15550000, episode_reward=-18.02 +/- 111.52

Episode length: 160.95 +/- 69.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 161         |
|    mean_reward          | -18         |
| time/                   |             |
|    total_timesteps      | 15550000    |
| train/                  |             |
|    approx_kl            | 0.003150232 |
|    clip_fraction        | 0.025       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.842      |
|    explained_variance   | 0.958       |
|    learning_rate        | 0.0003      |
|    loss                 | 589         |
|    n_updates            | 3792        |
|    policy_gradient_loss | -0.000929   |
|    value_loss           | 1.41e+03    |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 172      |
|    ep_rew_mean     | 81.5     |
| time/              |          |
|    fps             | 1636     |
|    iterations      | 608      |
|    time_elapsed    | 6086     |
|    total_timesteps | 15561472 |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 233         |
|    ep_rew_mean          | 105         |
| time/                   |             |
|    fps                  | 1636        |
|    iterations           | 609         |
|    time_elapsed         | 6095        |
|    total_timesteps      | 15577856    |
| train/                  |             |
|    approx_kl            | 0.003332518 |
|    clip_fraction        | 0.0231      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.898      |
|    explained_variance   | 0.959       |
|    learning_rate        | 0.0003      |
|    loss                 | 268         |
|    n_updates            | 3796        |
|    policy_gradient_loss | 0.000594    |
|    value_loss           | 908         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 225          |
|    ep_rew_mean          | 117          |
| time/                   |              |
|    fps                  | 1636         |
|    iterations           | 610          |
|    time_elapsed         | 6105         |
|    total_timesteps      | 15594240     |
| train/                  |              |
|    approx_kl            | 0.0059743766 |
|    clip_fraction        | 0.0354       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.945       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 273          |
|    n_updates            | 3800         |
|    policy_gradient_loss | -0.00117     |
|    value_loss           | 2.53e+03     |
------------------------------------------

Eval num_timesteps=15600000, episode_reward=46.96 +/- 85.12

Episode length: 147.95 +/- 72.73

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 148          |
|    mean_reward          | 47           |
| time/                   |              |
|    total_timesteps      | 15600000     |
| train/                  |              |
|    approx_kl            | 0.0038950015 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 359          |
|    n_updates            | 3804         |
|    policy_gradient_loss | -0.000252    |
|    value_loss           | 1.31e+03     |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_15600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 216      |
|    ep_rew_mean     | 112      |
| time/              |          |
|    fps             | 1636     |
|    iterations      | 611      |
|    time_elapsed    | 6117     |
|    total_timesteps | 15610624 |
---------------------------------

Best model: /content/rl-experiments/ppo_lunarlander_flip_phase_b/best_model/best_model.zip
Final model: /content/rl-experiments/ppo_lunarlander_flip_phase_b/final_model.zip
Configuration: /content/rl-experiments/ppo_lunarlander_flip_phase_b/training_config.json

#### Train Phase C (land in zone)

In [ ]:
phase_c_run = train_ppo_experiment(
    experiment_name=(
        "ppo_lunarlander_"
        "flip_phase_c_in_zone"
    ),

    total_timesteps=3_000_000,

    env_factory=(
        make_flip_in_zone_lander
    ),

    initial_model_path=(
        selected_model_path
    ),

    n_envs=16,
    seed=42,

    actor_layers=(128, 128),
    critic_layers=(128, 128),

    # Smaller updates reduce the risk of destroying
    # the already learned flip policy.
    learning_rate=1e-4,

    n_steps=1024,
    batch_size=64,
    n_epochs=4,

    gamma=0.999,
    gae_lambda=0.98,

    # Retain some exploration, but less than during
    # initial flip acquisition.
    ent_coef=0.01,

    clip_range=0.15,

    eval_every_timesteps=50_000,
    checkpoint_every_timesteps=100_000,
    n_eval_episodes=20,

    device="cpu",
)

### Evaluate model

In [16]:
phase_b_checkpoint_paths = sorted(
    (
        phase_b_run["output_dir"]
        / "checkpoints"
    ).glob("*.zip"),
    key=checkpoint_step,
)

phase_b_candidate_paths = [
    Path(
        phase_b_run["best_model_path"]
    ),
    Path(
        phase_b_run["final_model_path"]
    ),
    *phase_b_checkpoint_paths,
]

phase_b_candidate_paths = list(
    dict.fromkeys(
        path
        for path in phase_b_candidate_paths
        if path.exists()
    )
)

phase_b_rows = []

for candidate_path in (
    phase_b_candidate_paths
):
    candidate_evaluation = (
        evaluate_flip_model(
            candidate_path,
            reward_config=(
                flip_landing_config
            ),
            n_episodes=20,
            starting_seed=20_000,
        )
    )

    phase_b_rows.append(
        {
            "model_path": str(
                candidate_path
            ),
            **candidate_evaluation[
                "summary"
            ],
        }
    )

phase_b_results = pd.DataFrame(
    phase_b_rows
)

phase_b_results = (
    phase_b_results
    .sort_values(
        [
            "flip_landing_rate",
            "landing_given_flip_rate",
            "recovery_given_flip_rate",
            "flip_completion_rate",
            "mean_original_reward",
        ],
        ascending=[
            False,
            False,
            False,
            False,
            False,
        ],
    )
    .reset_index(drop=True)
)

display(
    phase_b_results[
        [
            "model_path",
            "flip_completion_rate",
            "recovery_given_flip_rate",
            "flip_landing_rate",
            "landing_given_flip_rate",
            "mean_original_reward",
        ]
    ]
)

selected_model_path = Path(
    phase_b_results.loc[
        0,
        "model_path",
    ]
)

print(
    "Selected Phase B model:",
    selected_model_path,
)

flip_evaluation = evaluate_flip_model(
    selected_model_path,
    reward_config=flip_landing_config,
    n_episodes=100,
    starting_seed=20_000,
)

display(
    pd.Series(
        flip_evaluation["summary"],
        name="Final flip-and-land model",
    )
)

display(
    flip_evaluation["episodes"]
    .sort_values(
        [
            "flip_and_landed",
            "recovery_completed",
            "flip_completed",
            "original_reward",
        ],
        ascending=[
            False,
            False,
            False,
            False,
        ],
    )
    .head(20)
)

Flip model evaluation
---------------------
Mean shaped reward: -99.35
Mean original reward: -699.73
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 23.42
Mean original reward: -673.88
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 55.13
Mean original reward: -665.07
Completed a full rotation: 0.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 60.54
Mean original reward: -664.02
Completed a full rotation: 10.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 75.49
Mean original reward: -694.06
Completed a full rotation: 30.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 16.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 68.99
Mean original reward: -707.63
Completed a full rotation: 35.0%
Recovered after the flip: 20.0%
Recovery rate given a flip: 57.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 26.78
Mean original reward: -728.75
Completed a full rotation: 45.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 33.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 67.48
Mean original reward: -716.25
Completed a full rotation: 40.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 37.5%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -35.94
Mean original reward: -769.80
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 39.41
Mean original reward: -703.33
Completed a full rotation: 50.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 30.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 34.30
Mean original reward: -707.18
Completed a full rotation: 50.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 20.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 54.72
Mean original reward: -731.73
Completed a full rotation: 60.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 25.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -103.55
Mean original reward: -768.00
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -21.83
Mean original reward: -722.79
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -70.35
Mean original reward: -732.81
Completed a full rotation: 65.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 15.4%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -80.18
Mean original reward: -762.65
Completed a full rotation: 70.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -45.64
Mean original reward: -716.48
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 87.84
Mean original reward: -699.09
Completed a full rotation: 50.0%
Recovered after the flip: 25.0%
Recovery rate given a flip: 50.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -105.41
Mean original reward: -776.51
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -59.97
Mean original reward: -730.90
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -57.84
Mean original reward: -731.68
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -82.98
Mean original reward: -758.01
Completed a full rotation: 55.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -68.67
Mean original reward: -754.58
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -71.60
Mean original reward: -730.75
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -6.56
Mean original reward: -693.07
Completed a full rotation: 55.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -155.12
Mean original reward: -741.44
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -122.36
Mean original reward: -743.46
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -87.88
Mean original reward: -748.16
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -11.17
Mean original reward: -698.52
Completed a full rotation: 50.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 65.58
Mean original reward: -684.46
Completed a full rotation: 30.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 33.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 4.62
Mean original reward: -729.31
Completed a full rotation: 60.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 16.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -5.59
Mean original reward: -719.23
Completed a full rotation: 60.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 16.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -5.91
Mean original reward: -725.96
Completed a full rotation: 55.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -21.22
Mean original reward: -709.57
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -74.28
Mean original reward: -700.07
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -74.28
Mean original reward: -697.36
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -93.18
Mean original reward: -717.36
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -10.35
Mean original reward: -708.87
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -41.79
Mean original reward: -733.21
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -20.34
Mean original reward: -702.07
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -27.75
Mean original reward: -710.04
Completed a full rotation: 70.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 14.33
Mean original reward: -684.62
Completed a full rotation: 50.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 10.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -21.62
Mean original reward: -688.01
Completed a full rotation: 65.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 15.4%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -9.59
Mean original reward: -724.74
Completed a full rotation: 70.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.1%
Landed safely: 5.0%
Flipped and landed safely: 5.0%
Landing rate given a flip: 7.1%
Flip model evaluation
---------------------
Mean shaped reward: -69.94
Mean original reward: -717.58
Completed a full rotation: 70.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 47.27
Mean original reward: -680.57
Completed a full rotation: 55.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 27.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -54.36
Mean original reward: -675.81
Completed a full rotation: 50.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -44.01
Mean original reward: -707.12
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 64.79
Mean original reward: -659.59
Completed a full rotation: 50.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 30.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -247.15
Mean original reward: -759.08
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -228.78
Mean original reward: -742.60
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 5.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 1.29
Mean original reward: -687.97
Completed a full rotation: 65.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 23.1%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -56.55
Mean original reward: -730.14
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -143.96
Mean original reward: -756.75
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -61.83
Mean original reward: -713.55
Completed a full rotation: 65.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 15.4%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -141.19
Mean original reward: -728.55
Completed a full rotation: 70.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -96.93
Mean original reward: -711.55
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -53.09
Mean original reward: -694.93
Completed a full rotation: 65.0%
Recovered after the flip: 10.0%
Recovery rate given a flip: 15.4%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -151.76
Mean original reward: -734.47
Completed a full rotation: 65.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -90.98
Mean original reward: -702.75
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 66.19
Mean original reward: -659.55
Completed a full rotation: 60.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 25.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -122.92
Mean original reward: -719.30
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -65.72
Mean original reward: -707.90
Completed a full rotation: 60.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 8.3%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -66.70
Mean original reward: -717.38
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -31.21
Mean original reward: -698.07
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -3.86
Mean original reward: -673.73
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -54.75
Mean original reward: -727.10
Completed a full rotation: 75.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 6.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -58.29
Mean original reward: -705.85
Completed a full rotation: 60.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 5.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: 0.49
Mean original reward: -703.83
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -87.97
Mean original reward: -743.65
Completed a full rotation: 65.0%
Recovered after the flip: 5.0%
Recovery rate given a flip: 7.7%
Landed safely: 0.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%
Flip model evaluation
---------------------
Mean shaped reward: -61.95
Mean original reward: -730.77
Completed a full rotation: 60.0%
Recovered after the flip: 15.0%
Recovery rate given a flip: 25.0%
Landed safely: 0.0%

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,model_path,flip_completion_rate,recovery_given_flip_rate,flip_landing_rate,landing_given_flip_rate,mean_original_reward
0,/content/rl-experiments/ppo_lunarlander_flip_p...,0.60,0.166667,0.05,0.083333,-705.562614
1,/content/rl-experiments/ppo_lunarlander_flip_p...,0.65,0.076923,0.05,0.076923,-705.900041
2,/content/rl-experiments/ppo_lunarlander_flip_p...,0.70,0.071429,0.05,0.071429,-724.736374
3,/content/rl-experiments/ppo_lunarlander_flip_p...,0.35,0.571429,0.00,0.000000,-707.632096
4,/content/rl-experiments/ppo_lunarlander_flip_p...,0.50,0.500000,0.00,0.000000,-699.094579
...,...,...,...,...,...,...
97,/content/rl-experiments/ppo_lunarlander_flip_p...,0.55,0.000000,0.00,0.000000,-758.013128
98,/content/rl-experiments/ppo_lunarlander_flip_p...,0.50,0.000000,0.00,0.000000,-675.810114
99,/content/rl-experiments/ppo_lunarlander_flip_p...,0.50,0.000000,0.00,0.000000,-698.515854
100,/content/rl-experiments/ppo_lunarlander_flip_p...,0.10,0.000000,0.00,0.000000,-664.018554
101,/content/rl-experiments/ppo_lunarlander_flip_p...,0.00,0.000000,0.00,0.000000,-665.067944

Selected Phase B model: /content/rl-experiments/ppo_lunarlander_flip_phase_b/checkpoints/ppo_lunarlander_flip_phase_b_14000000_steps.zip
Flip model evaluation
---------------------
Mean shaped reward: 52.77
Mean original reward: -703.69
Completed a full rotation: 52.0%
Recovered after the flip: 7.0%
Recovery rate given a flip: 13.5%
Landed safely: 2.0%
Flipped and landed safely: 1.0%
Landing rate given a flip: 1.9%

n_episodes                   100.000000
mean_shaped_reward            52.766248
std_shaped_reward            313.948498
shaped_course_score         -261.182250
min_shaped_reward           -306.158234
max_shaped_reward           3014.455597
mean_original_reward        -703.690106
std_original_reward          120.315376
original_course_score       -824.005482
min_original_reward         -889.608501
max_original_reward         -336.997489
original_reward_200_rate       0.000000
flip_completion_rate           0.520000
recovery_completion_rate       0.070000
recovery_given_flip_rate       0.134615
safe_landing_rate              0.020000
flip_landing_rate              0.010000
landing_given_flip_rate        0.019231
Name: Final flip-and-land model, dtype: float64

,seed,shaped_reward,original_reward,steps,flip_completed,recovery_completed,landed_safely,flip_and_landed,flip_bonus,rotations_completed,terminal_adjustment,custom_outcome
7,20007,3014.455597,-345.666812,267,True,True,True,True,1500.0,0.954216,1500.0,flip_and_safe_landing
84,20084,429.868587,-596.765855,144,True,True,False,False,0.0,0.972376,-400.0,flip_but_failed_landing
50,20050,253.244576,-632.787901,94,True,True,False,False,0.0,1.037844,-400.0,flip_but_failed_landing
43,20043,256.409924,-723.933838,76,True,True,False,False,0.0,1.004938,-400.0,flip_but_failed_landing
62,20062,252.154701,-752.301995,108,True,True,False,False,0.0,1.000178,-400.0,flip_but_failed_landing
93,20093,277.280787,-756.067036,89,True,True,False,False,0.0,1.000001,-400.0,flip_but_failed_landing
5,20005,249.983940,-766.773732,100,True,True,False,False,0.0,1.000141,-400.0,flip_but_failed_landing
41,20041,5.389993,-730.733378,115,True,False,False,False,0.0,1.000151,-400.0,flip_but_failed_landing
92,20092,-5.777972,-732.579159,80,True,False,False,False,0.0,0.987611,-400.0,flip_but_failed_landing
97,20097,25.133454,-745.799587,83,True,False,False,False,0.0,1.010078,-400.0,flip_but_failed_landing
81,20081,45.718712,-749.312828,131,True,False,False,False,0.0,1.014839,-400.0,flip_but_failed_landing
22,20022,5.248533,-751.754731,81,True,False,False,False,0.0,1.050244,-400.0,flip_but_failed_landing
42,20042,36.750597,-752.914760,141,True,False,False,False,0.0,1.033078,-400.0,flip_but_failed_landing
59,20059,-37.316684,-753.158628,86,True,False,False,False,0.0,1.075116,-400.0,flip_but_failed_landing
40,20040,-25.142818,-755.727552,82,True,False,False,False,0.0,1.069236,-400.0,flip_but_failed_landing
70,20070,-15.187336,-772.390397,135,True,False,False,False,0.0,1.053806,-400.0,flip_but_failed_landing
60,20060,-40.757481,-774.111287,127,True,False,False,False,0.0,1.046237,-400.0,flip_but_failed_landing
78,20078,24.218214,-775.535234,128,True,False,False,False,0.0,1.067540,-400.0,flip_but_failed_landing
49,20049,-54.090428,-779.890780,133,True,False,False,False,0.0,1.063570,-400.0,flip_but_failed_landing
37,20037,-23.823509,-781.404218,133,True,False,False,False,0.0,1.017304,-400.0,flip_but_failed_landing

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
phase_c_results = (
    phase_c_results
    .sort_values(
        [
            "flip_landing_rate",
            "flip_completion_rate",
            "recovery_given_flip_rate",
            "outside_zone_landing_rate",
            "mean_original_reward",
        ],
        ascending=[
            False,
            False,
            False,
            True,
            False,
        ],
    )
    .reset_index(drop=True)
)

### Video of best episode

In [17]:
episode_results = (
    flip_evaluation["episodes"]
)

successful_flip_landings = (
    episode_results[
        episode_results[
            "flip_and_landed"
        ]
    ]
    .copy()
)

if successful_flip_landings.empty:
    video_seed = int(
        episode_results
        .sort_values(
            "shaped_reward",
            ascending=False,
        )
        .iloc[0]["seed"]
    )

    print(
        "No successful flip-and-land episode "
        "was found in the evaluation sample."
    )
    print(
        "Using the highest shaped-reward "
        "episode instead."
    )

else:
    video_seed = int(
        successful_flip_landings
        .sort_values(
            "original_reward",
            ascending=False,
        )
        .iloc[0]["seed"]
    )

    print(
        "Selected the successful flip-and-land "
        "episode with the highest original reward."
    )

print("Selected video seed:", video_seed)

Selected the successful flip-and-land episode with the highest original reward.
Selected video seed: 20007

In [18]:
from pathlib import Path
import shutil

import gymnasium as gym


def record_flip_replay(
    model_or_path,
    *,
    output_path: str | Path,
    seed: int,
    reward_config: dict,
    deterministic: bool = True,
):
    """
    Record one complete episode from the custom flip environment.
    """

    model = load_ppo_model(
        model_or_path
    )

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_directory = (
        output_path.parent
        / "_flip_video_recording"
    )

    if temporary_directory.exists():
        shutil.rmtree(
            temporary_directory
        )

    temporary_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    video_env = make_flip_lander(
        render_mode="rgb_array",
        reward_config=reward_config,
    )

    video_env = gym.wrappers.RecordVideo(
        video_env,
        video_folder=str(
            temporary_directory
        ),
        episode_trigger=(
            lambda episode_number:
            episode_number == 0
        ),
        video_length=0,
        name_prefix=(
            "ppo-lunarlander-flip"
        ),
        disable_logger=True,
    )

    shaped_reward_total = 0.0
    original_reward_total = 0.0
    episode_steps = 0

    final_info = {}

    try:
        observation, info = video_env.reset(
            seed=int(seed)
        )

        terminated = False
        truncated = False

        while not (
            terminated or truncated
        ):
            action, _ = model.predict(
                observation,
                deterministic=deterministic,
            )

            action = int(
                np.asarray(
                    action
                ).item()
            )

            (
                observation,
                shaped_reward,
                terminated,
                truncated,
                info,
            ) = video_env.step(action)

            shaped_reward_total += float(
                shaped_reward
            )

            original_reward_total += float(
                info.get(
                    "original_reward",
                    shaped_reward,
                )
            )

            episode_steps += 1
            final_info = dict(info)

    finally:
        video_env.close()

    generated_videos = list(
        temporary_directory.glob(
            "*.mp4"
        )
    )

    if not generated_videos:
        raise FileNotFoundError(
            "Gymnasium did not generate "
            "an MP4 replay."
        )

    generated_video = max(
        generated_videos,
        key=lambda path:
        path.stat().st_mtime,
    )

    shutil.copy2(
        generated_video,
        output_path,
    )

    shutil.rmtree(
        temporary_directory,
        ignore_errors=True,
    )

    replay_details = {
        "path": str(output_path),
        "seed": int(seed),
        "shaped_reward": float(
            shaped_reward_total
        ),
        "original_reward": float(
            original_reward_total
        ),
        "steps": int(
            episode_steps
        ),
        "flip_completed": bool(
            final_info.get(
                "flip_completed",
                False,
            )
        ),
        "landed_safely": bool(
            final_info.get(
                "landed_safely",
                False,
            )
        ),
        "rotations_completed": float(
            final_info.get(
                "rotations_completed",
                0.0,
            )
        ),
        "recovery_completed": bool(
            final_info.get(
                "recovery_completed",
                False,
            )
        ),
        "custom_outcome": str(
            final_info.get(
                "custom_outcome",
                "unknown",
            )
        ),
        "flip_and_landed": (
            final_info.get(
                "custom_outcome"
            )
            == "flip_and_safe_landing"
        ),
    }

    print("Replay saved:", output_path)
    print(
        "Shaped reward:",
        f"{shaped_reward_total:.2f}",
    )
    print(
        "Original reward:",
        f"{original_reward_total:.2f}",
    )
    print(
        "Completed a flip:",
        replay_details[
            "flip_completed"
        ],
    )
    print(
        "Landed safely:",
        replay_details[
            "landed_safely"
        ],
    )
    print(
        "Flipped and landed:",
        replay_details[
            "flip_and_landed"
        ],
    )
    print(
        "Rotations completed:",
        f"{replay_details['rotations_completed']:.2f}",
    )

    return replay_details

In [19]:
flip_replay = record_flip_replay(
    selected_model_path,
    output_path=(
        "/content/"
        "ppo-LunarLander-v3-"
        "flip-replay.mp4"
    ),
    seed=video_seed,
    reward_config=flip_landing_config,
)

flip_replay

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/rendering.py:292: UserWarning: WARN: Overwriting existing videos at /content/_flip_video_recording folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.12/dist-packages/moviepy/config_defaults.py:47: SyntaxWarning: invalid escape sequence '\P'
  IMAGEMAGICK_BINARY = r"C:\Program Files\ImageMagick-6.8.8-Q16\magick.exe"
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Replay saved: /content/ppo-LunarLander-v3-flip-replay.mp4
Shaped reward: 3014.46
Original reward: -345.67
Completed a flip: True
Landed safely: True
Flipped and landed: True
Rotations completed: 0.95

{'path': '/content/ppo-LunarLander-v3-flip-replay.mp4',
 'seed': 20007,
 'shaped_reward': 3014.455597378636,
 'original_reward': -345.66681227085496,
 'steps': 267,
 'flip_completed': True,
 'landed_safely': True,
 'rotations_completed': 0.9542159198654738,
 'recovery_completed': True,
 'custom_outcome': 'flip_and_safe_landing',
 'flip_and_landed': True}

In [20]:
from IPython.display import (
    Video,
    display,
)


display(
    Video(
        flip_replay["path"],
        embed=True,
    )
)

### Upload as new model to Hugging Face

In [21]:
from __future__ import annotations

from pathlib import Path
import json
import shutil
import textwrap

from huggingface_hub import HfApi


DEFAULT_CHANGE_NOTES = [
    (
        "Reduced the combined rotation-progress and flip-completion "
        "reward so a flip followed by a crash is less attractive."
    ),
    (
        "Increased the pre-flip weight on the original LunarLander "
        "reward so the agent is less free to drift far from the pad "
        "while rotating."
    ),
    (
        "Added a one-off recovery reward for becoming upright and "
        "arresting angular velocity after the flip."
    ),
    (
        "Added dense post-flip potential-difference shaping for "
        "horizontal position, horizontal speed, attitude, angular "
        "speed, and leg contact."
    ),
    (
        "Added a failed-landing penalty and increased the terminal "
        "flip-and-safe-landing bonus."
    ),
    (
        "Added a recovery-completed observation flag. The wrapped "
        "observation now contains 11 values rather than the base "
        "environment's 8 values."
    ),
]


def _markdown_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"

    if isinstance(value, float):
        return f"{value:g}"

    return str(value)


def _markdown_table(mapping: dict) -> str:
    rows = [
        "| Parameter | Value |",
        "|---|---:|",
    ]

    for key, value in mapping.items():
        rows.append(
            f"| `{key}` | {_markdown_value(value)} |"
        )

    return "\n".join(rows)


def upload_flip_model_to_hub(
    model_or_path,
    *,
    repo_id: str,
    flip_evaluation: dict,
    replay_details: dict,
    training_config_path: str | Path,
    reward_config: dict,
    reward_wrapper_path: str | Path,
    model_filename: str = (
        "ppo-LunarLander-v3-flip-128x128.zip"
    ),
    reward_version: str = "v2-post-flip-recovery",
    change_notes: list[str] | None = None,
    commit_message: str = (
        "Update PPO agent with post-flip recovery shaping"
    ),
    private: bool = False,
):
    """
    Upload a trained PPO checkpoint and the exact custom environment
    definition used to train and evaluate it.

    Reusing the same repo_id and filenames updates the current Hub
    files in a new commit; previous revisions remain in repository
    history.
    """

    if not reward_config:
        raise ValueError(
            "reward_config must contain the exact configuration "
            "used for training."
        )

    model = load_ppo_model(model_or_path)

    summary = dict(
        flip_evaluation["summary"]
    )
    episode_results = (
        flip_evaluation["episodes"].copy()
    )

    replay_path = Path(
        replay_details["path"]
    )
    training_config_path = Path(
        training_config_path
    )
    reward_wrapper_path = Path(
        reward_wrapper_path
    )

    required_paths = {
        "Replay": replay_path,
        "Training configuration": training_config_path,
        "Reward wrapper": reward_wrapper_path,
    }

    for label, path in required_paths.items():
        if not path.exists():
            raise FileNotFoundError(
                f"{label} not found: {path}"
            )

    training_config = json.loads(
        training_config_path.read_text(
            encoding="utf-8"
        )
    )

    staging_directory = (
        Path("/content/hf-flip-model")
        / repo_id.replace("/", "__")
    )

    if staging_directory.exists():
        shutil.rmtree(staging_directory)

    staging_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    saved_model_path = (
        staging_directory / model_filename
    )
    model.save(str(saved_model_path))

    if not saved_model_path.exists():
        raise FileNotFoundError(
            "The PPO model was not saved at "
            f"{saved_model_path}"
        )

    shutil.copy2(
        replay_path,
        staging_directory / "replay.mp4",
    )
    shutil.copy2(
        training_config_path,
        staging_directory / "training_config.json",
    )
    shutil.copy2(
        reward_wrapper_path,
        staging_directory
        / "flip_landing_reward_wrapper.py",
    )

    (
        staging_directory / "reward_config.json"
    ).write_text(
        json.dumps(
            reward_config,
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )

    episode_results.to_csv(
        staging_directory / "episode_results.csv",
        index=False,
    )

    notes = list(
        change_notes
        if change_notes is not None
        else DEFAULT_CHANGE_NOTES
    )

    results_payload = {
        "environment": {
            "base_environment": "LunarLander-v3",
            "custom_objective": (
                "Complete a full directed rotation, recover to "
                "a stable upright attitude, re-centre, and land "
                "safely."
            ),
            "reward_version": reward_version,
            "observation_space": {
                "base_dimensions": 8,
                "added_dimensions": [
                    "signed_rotation_progress",
                    "flip_completed",
                    "recovery_completed",
                ],
                "wrapped_dimensions": 11,
            },
            "reward_config": reward_config,
            "change_notes": notes,
        },
        "evaluation": summary,
        "evaluation_seeds": (
            episode_results["seed"]
            .astype(int)
            .tolist()
        ),
        "replay": {
            key: value
            for key, value in replay_details.items()
            if key != "path"
        },
    }

    (
        staging_directory / "results.json"
    ).write_text(
        json.dumps(
            results_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    config_payload = {
        "algorithm": "PPO",
        "library": "stable-baselines3",
        "base_environment": "LunarLander-v3",
        "model_filename": model_filename,
        "reward_version": reward_version,
        "reward_config_filename": "reward_config.json",
        "reward_wrapper_filename": (
            "flip_landing_reward_wrapper.py"
        ),
        "observation_dimensions": 11,
        "architecture": {
            "actor_layers": training_config.get(
                "actor_layers"
            ),
            "critic_layers": training_config.get(
                "critic_layers"
            ),
        },
        "evaluation": {
            "mean_shaped_reward": summary.get(
                "mean_shaped_reward"
            ),
            "mean_original_reward": summary.get(
                "mean_original_reward"
            ),
            "flip_completion_rate": summary.get(
                "flip_completion_rate"
            ),
            "recovery_completion_rate": summary.get(
                "recovery_completion_rate"
            ),
            "safe_landing_rate": summary.get(
                "safe_landing_rate"
            ),
            "flip_landing_rate": summary.get(
                "flip_landing_rate"
            ),
        },
    }

    (
        staging_directory / "config.json"
    ).write_text(
        json.dumps(
            config_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    actor_layers = training_config.get(
        "actor_layers",
        "Not supplied",
    )
    critic_layers = training_config.get(
        "critic_layers",
        "Not supplied",
    )

    video_url = (
        f"https://huggingface.co/{repo_id}"
        "/resolve/main/replay.mp4"
    )

    change_notes_markdown = "\n".join(
        f"{index}. {note}"
        for index, note in enumerate(
            notes,
            start=1,
        )
    )

    reward_table = _markdown_table(
        reward_config
    )

    optional_recovery_row = ""

    if (
        summary.get("recovery_completion_rate")
        is not None
    ):
        optional_recovery_row = (
            "| Post-flip recovery rate | "
            f"{summary['recovery_completion_rate']:.1%} |\n"
        )

    readme = textwrap.dedent(
        f"""
        ---
        library_name: stable-baselines3
        pipeline_tag: reinforcement-learning
        tags:
        - stable-baselines3
        - reinforcement-learning
        - deep-reinforcement-learning
        - PPO
        - LunarLander-v3
        - custom-reward
        - reward-shaping
        - actor-critic
        ---

        # PPO LunarLander flip, recover and land agent

        This repository contains a Stable-Baselines3 PPO
        actor-critic agent trained on a customised
        `LunarLander-v3` environment.

        The objective has three stages:

        1. complete one full rotation in a fixed direction;
        2. return upright and arrest the spin;
        3. re-centre, stabilise and land with both legs.

        Reward configuration version: `{reward_version}`.

        ## Changes in this upload

        {change_notes_markdown}

        ## Reward design

        Rotation progress is rewarded only when the agent reaches
        previously unseen progress. After the full rotation, a
        potential-difference reward encourages improvement in:

        - horizontal distance from the pad centre;
        - horizontal speed;
        - orientation;
        - angular speed;
        - leg contact.

        The terminal success bonus is awarded only after a completed
        flip and a safe landing. A completed flip followed by an
        unsuccessful landing receives the configured failed-landing
        penalty.

        {reward_table}

        ## Observation space

        The base `LunarLander-v3` observation contains 8 values.
        This wrapper appends:

        1. signed rotation progress;
        2. flip-completed flag;
        3. recovery-completed flag.

        The policy therefore expects **11 observation values** and
        cannot be used directly with an unwrapped
        `LunarLander-v3` environment.

        ## Evaluation

        Deterministic evaluation over
        {summary['n_episodes']} fixed-seed episodes:

        | Metric | Value |
        |---|---:|
        | Mean shaped reward | {summary['mean_shaped_reward']:.2f} |
        | Shaped reward standard deviation | {summary['std_shaped_reward']:.2f} |
        | Shaped course-style score | {summary['shaped_course_score']:.2f} |
        | Minimum shaped reward | {summary['min_shaped_reward']:.2f} |
        | Maximum shaped reward | {summary['max_shaped_reward']:.2f} |
        | Mean original reward | {summary['mean_original_reward']:.2f} |
        | Original reward standard deviation | {summary['std_original_reward']:.2f} |
        | Original course-style score | {summary['original_course_score']:.2f} |
        | Original reward >= 200 | {summary['original_reward_200_rate']:.1%} |
        | Full-rotation rate | {summary['flip_completion_rate']:.1%} |
        {optional_recovery_row}| Safe-landing rate | {summary['safe_landing_rate']:.1%} |
        | Flip-and-land rate | {summary['flip_landing_rate']:.1%} |
        | Minimum original reward | {summary['min_original_reward']:.2f} |
        | Maximum original reward | {summary['max_original_reward']:.2f} |

        Shaped rewards are not directly comparable with scores from
        the standard LunarLander environment.

        ## Architecture

        - Algorithm: PPO
        - Policy: MLP actor-critic
        - Actor hidden layers: `{actor_layers}`
        - Critic hidden layers: `{critic_layers}`

        ## Training configuration

        | Parameter | Value |
        |---|---:|
        | Training timesteps | {training_config.get('total_timesteps')} |
        | Parallel environments | {training_config.get('n_envs')} |
        | Learning rate | {training_config.get('learning_rate')} |
        | Rollout steps per environment | {training_config.get('n_steps')} |
        | Batch size | {training_config.get('batch_size')} |
        | Optimisation epochs | {training_config.get('n_epochs')} |
        | Gamma | {training_config.get('gamma')} |
        | GAE lambda | {training_config.get('gae_lambda')} |
        | Entropy coefficient | {training_config.get('ent_coef')} |
        | PPO clip range | {training_config.get('clip_range')} |
        | Training seed | {training_config.get('seed')} |

        ## Replay

        - Seed: `{replay_details['seed']}`
        - Original reward:
          `{replay_details['original_reward']:.2f}`
        - Shaped reward:
          `{replay_details['shaped_reward']:.2f}`
        - Rotations completed:
          `{replay_details['rotations_completed']:.2f}`
        - Flip completed:
          `{replay_details['flip_completed']}`
        - Recovery completed:
          `{replay_details.get('recovery_completed', 'Not recorded')}`
        - Landed safely:
          `{replay_details['landed_safely']}`

        <video controls autoplay loop muted width="640">
          <source src="{video_url}" type="video/mp4">
        </video>

        ## Load the model

        The wrapper and reward configuration are included in this
        repository because the policy requires the augmented
        11-value observation.

        ```python
        import json
        import sys
        from pathlib import Path

        from huggingface_hub import hf_hub_download
        from stable_baselines3 import PPO

        checkpoint = hf_hub_download(
            repo_id="{repo_id}",
            filename="{model_filename}",
        )
        wrapper_file = hf_hub_download(
            repo_id="{repo_id}",
            filename="flip_landing_reward_wrapper.py",
        )
        reward_file = hf_hub_download(
            repo_id="{repo_id}",
            filename="reward_config.json",
        )

        sys.path.insert(
            0,
            str(Path(wrapper_file).parent),
        )

        from flip_landing_reward_wrapper import (
            make_flip_lander,
        )

        reward_config = json.loads(
            Path(reward_file).read_text(
                encoding="utf-8"
            )
        )

        env = make_flip_lander(
            reward_config=reward_config
        )

        model = PPO.load(
            checkpoint,
            env=env,
            device="cpu",
        )
        ```
        """
    ).strip()

    (
        staging_directory / "README.md"
    ).write_text(
        readme,
        encoding="utf-8",
    )

    print("Prepared files:")

    for path in sorted(
        staging_directory.iterdir()
    ):
        print(
            "-",
            path.name,
            f"({path.stat().st_size / 1024:.1f} KiB)",
        )

    api = HfApi()

    api.create_repo(
        repo_id=repo_id,
        repo_type="model",
        private=private,
        exist_ok=True,
    )

    upload_result = api.upload_folder(
        folder_path=str(staging_directory),
        repo_id=repo_id,
        repo_type="model",
        commit_message=commit_message,
    )

    print()
    print("Upload complete:", upload_result)
    print(
        "Model repository:",
        f"https://huggingface.co/{repo_id}",
    )

    return {
        "repo_id": repo_id,
        "staging_directory": staging_directory,
        "summary": summary,
        "reward_version": reward_version,
        "upload_result": upload_result,
    }

In [22]:
upload_result = upload_flip_model_to_hub(
    selected_model_path,

    repo_id=(
        "KaptainKris92/"
        "ppo-LunarLander-v3-flip"
    ),

    flip_evaluation=flip_evaluation,
    replay_details=flip_replay,

    training_config_path=(
        phase_b_run["config_path"]
    ),

    reward_config=flip_landing_config,

    reward_wrapper_path=(
        REWARD_WRAPPER_PATH
    ),

    model_filename=(
        "ppo-LunarLander-v3-"
        "flip.zip"
    ),

    change_notes=[
        (
            "Introduced a two-stage curriculum: "
            "Phase A acquires the full rotation and "
            "Phase B continues from the strongest "
            "flip-capable checkpoint."
        ),
        (
            "Penalised safe landing without first "
            "completing the required rotation."
        ),
        (
            "Added vertical-speed control to the "
            "post-flip recovery potential."
        ),
        (
            "Multiplied the original LunarLander "
            "reward by 3 after flip completion."
        ),
        (
            "Selected the final checkpoint using "
            "flip-and-land and recovery metrics "
            "rather than mean shaped reward alone."
        ),
    ],

    commit_message=(
        "Train PPO with flip-acquisition "
        "and post-flip landing curriculum"
    ),
)

Prepared files:
- README.md (6.5 KiB)
- config.json (0.7 KiB)
- episode_results.csv (12.4 KiB)
- flip_landing_reward_wrapper.py (16.8 KiB)
- ppo-LunarLander-v3-flip.zip (462.5 KiB)
- replay.mp4 (40.5 KiB)
- results.json (4.1 KiB)
- reward_config.json (0.8 KiB)
- training_config.json (0.7 KiB)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

HfHubHTTPError: (Request ID: Root=1-6a5760bc-1b806870470f3aee7139f66f;a7b09aaa-a0e7-492e-b784-6f0f09e0be86)

403 Forbidden: You don't have the rights to create a model under the namespace "KaptainKris92".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.