<a href="https://colab.research.google.com/github/KaptainKris92/HuggingFace_RL_Course/blob/main/notebooks/unit1/LunarLander_v3_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LunarLander PPO experiments

This notebook provides a reusable workflow for training, evaluating, comparing and publishing PPO agents for `LunarLander-v3`.

## Core concepts

The environment gives the agent an eight-value observation describing the lander's position, velocity, angle, angular velocity and leg contact. The agent chooses one of four engine actions.

PPO uses an **actor–critic** architecture:

- The **actor** (`pi`) produces a probability distribution over actions.
- The **critic** (`vf`) estimates the expected future return from the current state.
- PPO uses the critic to estimate whether an action performed better or worse than expected, then updates the actor while clipping excessively large policy changes.

Important parameters:

- `gamma`: how strongly future rewards contribute to the return.
- `gae_lambda`: the bias–variance and temporal-credit-assignment trade-off in advantage estimation. It is not the exploration/exploitation setting.
- `ent_coef`: encourages exploration by preventing the actor from becoming deterministic too early.
- `net_arch`: controls the hidden-layer sizes of the actor and critic.

Models are compared on the same fixed evaluation seeds. By default, a candidate replaces the current Hugging Face model only when its fixed-seed mean reward is higher.

#### Installs and imports

In [1]:
!apt-get update -qq
!apt-get install -y -qq swig cmake ffmpeg xvfb libgl1

%pip install -q \
    "stable-baselines3[extra]==2.9.0" \
    "gymnasium[box2d]==1.3.0" \
    "huggingface-hub<2" \
    pyvirtualdisplay

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package swig4.0.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../swig4.0_4.0.2-1ubuntu1_amd64.deb ...
Unpacking swig4.0 (4.0.2-1ubuntu1) ...
Selecting previously unselected package swig.
Preparing to unpack .../swig_4.0.2-1ubuntu1_all.deb ...
Unpacking swig (4.0.2-1ubuntu1) ...
Setting up swig4.0 (4.0.2-1ubuntu1) ...
Setting up swig (4.0.2-1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.6/187.6 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 58.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 64.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 72.5 MB/s eta 0:00:00

In [2]:
from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Sequence
import json
import os
import shutil
import textwrap

import gymnasium as gym
import numpy as np
import pandas as pd

from huggingface_hub import (
    HfApi,
    hf_hub_download,
    notebook_login,
)
from huggingface_hub.utils import (
    EntryNotFoundError,
    RepositoryNotFoundError,
)

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    EvalCallback,
)
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor

from pyvirtualdisplay import Display
from IPython.display import Video, display


if not os.environ.get("DISPLAY"):
    virtual_display = Display(
        visible=False,
        size=(1400, 900),
    )
    virtual_display.start()

    print(
        "Virtual display started:",
        virtual_display.is_alive(),
    )
else:
    print("Using existing display:", os.environ["DISPLAY"])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Virtual display started: True

#### Model loading, evaluation, and comparison functions

In [3]:
def load_ppo_model(
    model_or_path: PPO | str | Path,
    *,
    device: str = "cpu",
) -> PPO:
    """Return an existing PPO object or load one from disk."""

    if isinstance(model_or_path, PPO):
        return model_or_path

    model_path = Path(model_or_path)

    if not model_path.exists():
        raise FileNotFoundError(
            f"Model not found: {model_path}"
        )

    return PPO.load(
        str(model_path),
        device=device,
    )


def normalise_action(action: Any) -> Any:
    """
    Convert a one-element discrete-action array into an integer.

    PPO commonly returns array([2]), while a non-vectorised
    LunarLander environment expects the integer 2.
    """

    action_array = np.asarray(action)

    if action_array.size == 1:
        return int(action_array.item())

    return action


def evaluate_model(
    model_or_path: PPO | str | Path,
    *,
    seeds: Iterable[int],
    env_id: str = "LunarLander-v3",
    env_kwargs: dict[str, Any] | None = None,
    deterministic: bool = True,
    device: str = "cpu",
) -> dict[str, Any]:
    """
    Evaluate a model on an explicit set of episode seeds.

    Explicit seeds make comparisons between models reproducible
    and ensure they face the same landing scenarios.
    """

    model = load_ppo_model(
        model_or_path,
        device=device,
    )

    env_kwargs = dict(env_kwargs or {})
    seed_list = [int(seed) for seed in seeds]

    if not seed_list:
        raise ValueError(
            "At least one evaluation seed is required."
        )

    episode_rewards: list[float] = []
    episode_lengths: list[int] = []

    for seed in seed_list:
        env = Monitor(
            gym.make(
                env_id,
                **env_kwargs,
            )
        )

        try:
            observation, info = env.reset(seed=seed)

            terminated = False
            truncated = False
            total_reward = 0.0
            episode_length = 0

            while not (terminated or truncated):
                action, _ = model.predict(
                    observation,
                    deterministic=deterministic,
                )

                (
                    observation,
                    reward,
                    terminated,
                    truncated,
                    info,
                ) = env.step(
                    normalise_action(action)
                )

                total_reward += float(reward)
                episode_length += 1

            episode_rewards.append(total_reward)
            episode_lengths.append(episode_length)

        finally:
            env.close()

    rewards = np.asarray(
        episode_rewards,
        dtype=float,
    )
    lengths = np.asarray(
        episode_lengths,
        dtype=float,
    )

    mean_reward = float(rewards.mean())
    std_reward = float(rewards.std())

    return {
        "mean_reward": mean_reward,
        "std_reward": std_reward,
        "course_score": mean_reward - std_reward,
        "success_rate_200": float(
            np.mean(rewards >= 200.0)
        ),
        "mean_episode_length": float(
            lengths.mean()
        ),
        "min_reward": float(rewards.min()),
        "max_reward": float(rewards.max()),
        "n_episodes": len(seed_list),
        "rewards": rewards.tolist(),
        "episode_lengths": lengths.astype(int).tolist(),
    }


def metrics_only(
    results: dict[str, Any],
) -> dict[str, float | int]:
    """Return only summary metrics, excluding episode arrays."""

    return {
        "mean_reward": results["mean_reward"],
        "std_reward": results["std_reward"],
        "course_score": results["course_score"],
        "success_rate_200": results["success_rate_200"],
        "mean_episode_length": (
            results["mean_episode_length"]
        ),
        "min_reward": results["min_reward"],
        "max_reward": results["max_reward"],
        "n_episodes": results["n_episodes"],
    }


def compare_candidate_to_hub(
    candidate_model_or_path: PPO | str | Path,
    *,
    repo_id: str,
    hub_model_filename: str,
    evaluation_seeds: Iterable[int],
    env_id: str = "LunarLander-v3",
    env_kwargs: dict[str, Any] | None = None,
    selection_metric: str = "mean_reward",
    min_improvement: float = 0.0,
    device: str = "cpu",
) -> dict[str, Any]:
    """
    Compare a candidate with the current Hub model on the same seeds.

    Valid selection metrics:
    - mean_reward
    - course_score
    - success_rate_200
    """

    valid_metrics = {
        "mean_reward",
        "course_score",
        "success_rate_200",
    }

    if selection_metric not in valid_metrics:
        raise ValueError(
            "selection_metric must be one of "
            f"{sorted(valid_metrics)}."
        )

    seed_list = [
        int(seed)
        for seed in evaluation_seeds
    ]

    candidate_results = evaluate_model(
        candidate_model_or_path,
        seeds=seed_list,
        env_id=env_id,
        env_kwargs=env_kwargs,
        device=device,
    )

    current_results = None
    current_model_path = None

    try:
        current_model_path = hf_hub_download(
            repo_id=repo_id,
            filename=hub_model_filename,
            repo_type="model",
        )

        current_results = evaluate_model(
            current_model_path,
            seeds=seed_list,
            env_id=env_id,
            env_kwargs=env_kwargs,
            device=device,
        )

    except (
        EntryNotFoundError,
        RepositoryNotFoundError,
    ):
        print(
            "No current Hub model was found. "
            "The candidate is eligible for upload."
        )

    rows = [
        {
            "model": "candidate",
            **metrics_only(candidate_results),
        }
    ]

    if current_results is not None:
        rows.append(
            {
                "model": "current_hub",
                **metrics_only(current_results),
            }
        )

    comparison_table = (
        pd.DataFrame(rows)
        .set_index("model")
    )

    if current_results is None:
        improvement = None
        candidate_is_better = True

    else:
        candidate_value = float(
            candidate_results[selection_metric]
        )
        current_value = float(
            current_results[selection_metric]
        )

        improvement = (
            candidate_value - current_value
        )

        candidate_is_better = (
            candidate_value
            > current_value + min_improvement
        )

    display(comparison_table.round(3))

    print("Selection metric:", selection_metric)

    if improvement is not None:
        print(f"Improvement: {improvement:+.3f}")

    print(
        "Candidate is eligible for upload:",
        candidate_is_better,
    )

    return {
        "candidate": candidate_results,
        "current": current_results,
        "current_model_path": current_model_path,
        "selection_metric": selection_metric,
        "min_improvement": min_improvement,
        "improvement": improvement,
        "candidate_is_better": candidate_is_better,
        "table": comparison_table,
    }

#### Train model function

In [4]:
def train_ppo_experiment(
    *,
    experiment_name: str,
    total_timesteps: int,
    env_id: str = "LunarLander-v3",
    env_kwargs: dict[str, Any] | None = None,
    n_envs: int = 16,
    seed: int = 42,
    actor_layers: Sequence[int] = (64, 64),
    critic_layers: Sequence[int] = (64, 64),
    learning_rate: float = 3e-4,
    n_steps: int = 1024,
    batch_size: int = 64,
    n_epochs: int = 4,
    gamma: float = 0.999,
    gae_lambda: float = 0.98,
    ent_coef: float = 0.01,
    clip_range: float = 0.2,
    eval_every_timesteps: int = 50_000,
    checkpoint_every_timesteps: int = 100_000,
    n_eval_episodes: int = 20,
    output_root: str | Path = "/content/rl-experiments",
    device: str = "cpu",
    verbose: int = 1,
) -> dict[str, Any]:
    """
    Train a PPO actor–critic model.

    Saves:
    - periodic safety checkpoints;
    - the checkpoint with the best evaluation mean;
    - the final model;
    - the experiment configuration.
    """

    if not experiment_name.strip():
        raise ValueError(
            "experiment_name must not be empty."
        )

    if total_timesteps <= 0:
        raise ValueError(
            "total_timesteps must be positive."
        )

    env_kwargs = dict(env_kwargs or {})

    output_dir = (
        Path(output_root)
        / experiment_name
    )
    best_model_dir = (
        output_dir
        / "best_model"
    )
    checkpoint_dir = (
        output_dir
        / "checkpoints"
    )
    evaluation_dir = (
        output_dir
        / "evaluations"
    )

    for directory in (
        best_model_dir,
        checkpoint_dir,
        evaluation_dir,
    ):
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    configuration = {
        "experiment_name": experiment_name,
        "env_id": env_id,
        "env_kwargs": env_kwargs,
        "total_timesteps": total_timesteps,
        "n_envs": n_envs,
        "seed": seed,
        "actor_layers": list(actor_layers),
        "critic_layers": list(critic_layers),
        "learning_rate": learning_rate,
        "n_steps": n_steps,
        "batch_size": batch_size,
        "n_epochs": n_epochs,
        "gamma": gamma,
        "gae_lambda": gae_lambda,
        "ent_coef": ent_coef,
        "clip_range": clip_range,
        "eval_every_timesteps": (
            eval_every_timesteps
        ),
        "checkpoint_every_timesteps": (
            checkpoint_every_timesteps
        ),
        "n_eval_episodes": n_eval_episodes,
        "device": device,
    }

    config_path = (
        output_dir
        / "training_config.json"
    )
    config_path.write_text(
        json.dumps(
            configuration,
            indent=2,
        ),
        encoding="utf-8",
    )

    train_env = make_vec_env(
        env_id,
        n_envs=n_envs,
        seed=seed,
        env_kwargs=env_kwargs,
    )

    eval_env = Monitor(
        gym.make(
            env_id,
            **env_kwargs,
        )
    )

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=str(
            best_model_dir
        ),
        log_path=str(evaluation_dir),
        eval_freq=max(
            eval_every_timesteps // n_envs,
            1,
        ),
        n_eval_episodes=n_eval_episodes,
        deterministic=True,
        render=False,
        verbose=1,
    )

    checkpoint_callback = CheckpointCallback(
        save_freq=max(
            checkpoint_every_timesteps // n_envs,
            1,
        ),
        save_path=str(checkpoint_dir),
        name_prefix=experiment_name,
        verbose=2,
    )

    policy_kwargs = {
        "net_arch": {
            "pi": list(actor_layers),
            "vf": list(critic_layers),
        }
    }

    model = PPO(
        policy="MlpPolicy",
        env=train_env,
        learning_rate=learning_rate,
        n_steps=n_steps,
        batch_size=batch_size,
        n_epochs=n_epochs,
        gamma=gamma,
        gae_lambda=gae_lambda,
        ent_coef=ent_coef,
        clip_range=clip_range,
        policy_kwargs=policy_kwargs,
        device=device,
        seed=seed,
        verbose=verbose,
    )

    try:
        model.learn(
            total_timesteps=total_timesteps,
            callbacks = [
                eval_callback,
                checkpoint_callback,
                *(extra_callbacks or []),
            ]

            progress_bar=True,
        )

        final_model_stem = (
            output_dir
            / "final_model"
        )
        model.save(
            str(final_model_stem)
        )

    finally:
        train_env.close()
        eval_env.close()

    best_model_path = (
        best_model_dir
        / "best_model.zip"
    )
    final_model_path = (
        output_dir
        / "final_model.zip"
    )
    evaluations_path = (
        evaluation_dir
        / "evaluations.npz"
    )

    if not best_model_path.exists():
        raise FileNotFoundError(
            "No best_model.zip was created. "
            "Check whether training reached an "
            "evaluation interval."
        )

    print("Best model:", best_model_path)
    print("Final model:", final_model_path)

    return {
        "experiment_name": experiment_name,
        "output_dir": output_dir,
        "best_model_path": best_model_path,
        "final_model_path": final_model_path,
        "evaluations_path": evaluations_path,
        "config_path": config_path,
        "configuration": configuration,
    }

#### Record video function

In [5]:
def record_replay(
    model_or_path: PPO | str | Path,
    *,
    output_path: str | Path,
    env_id: str = "LunarLander-v3",
    env_kwargs: dict[str, Any] | None = None,
    seed: int = 42,
    deterministic: bool = True,
    device: str = "cpu",
) -> dict[str, Any]:
    """Record one complete deterministic episode."""

    model = load_ppo_model(
        model_or_path,
        device=device,
    )

    env_kwargs = dict(env_kwargs or {})
    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    recording_dir = (
        output_path.parent
        / "_temporary_recording"
    )

    if recording_dir.exists():
        shutil.rmtree(recording_dir)

    recording_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    env = gym.make(
        env_id,
        render_mode="rgb_array",
        **env_kwargs,
    )

    env = gym.wrappers.RecordVideo(
        env,
        video_folder=str(recording_dir),
        episode_trigger=(
            lambda episode_number:
            episode_number == 0
        ),
        video_length=0,
        name_prefix=output_path.stem,
        disable_logger=True,
    )

    total_reward = 0.0
    steps = 0

    try:
        observation, info = env.reset(
            seed=seed
        )

        terminated = False
        truncated = False

        while not (terminated or truncated):
            action, _ = model.predict(
                observation,
                deterministic=deterministic,
            )

            (
                observation,
                reward,
                terminated,
                truncated,
                info,
            ) = env.step(
                normalise_action(action)
            )

            total_reward += float(reward)
            steps += 1

    finally:
        env.close()

    generated_videos = list(
        recording_dir.glob("*.mp4")
    )

    if not generated_videos:
        raise FileNotFoundError(
            "No MP4 replay was generated."
        )

    generated_video = max(
        generated_videos,
        key=lambda path:
        path.stat().st_mtime,
    )

    shutil.copy2(
        generated_video,
        output_path,
    )

    shutil.rmtree(
        recording_dir,
        ignore_errors=True,
    )

    print(
        f"Replay saved to {output_path}"
    )
    print(
        f"Replay reward: {total_reward:.2f}"
    )
    print(
        f"Replay length: {steps} steps"
    )

    return {
        "path": str(output_path),
        "seed": seed,
        "reward": total_reward,
        "steps": steps,
    }

#### Model-card and Hugging Face repo upload functions

In [6]:
def build_model_card(
    *,
    repo_id: str,
    env_id: str,
    model_filename: str,
    evaluation: dict[str, Any],
    replay: dict[str, Any],
    training_config: dict[str, Any] | None,
    comparison: dict[str, Any] | None,
) -> str:
    """Generate the repository README/model card."""

    actor_layers = (
        training_config.get("actor_layers")
        if training_config
        else "Not supplied"
    )
    critic_layers = (
        training_config.get("critic_layers")
        if training_config
        else "Not supplied"
    )

    comparison_text = ""

    if (
        comparison is not None
        and comparison["current"] is not None
    ):
        comparison_text = (
            f"The candidate was compared with the "
            f"previous Hub model on the same "
            f"{evaluation['n_episodes']} fixed seeds. "
            f"The selection metric was "
            f"`{comparison['selection_metric']}` and "
            f"the observed improvement was "
            f"{comparison['improvement']:+.3f}."
        )

    replay_url = (
        f"https://huggingface.co/"
        f"{repo_id}/resolve/main/replay.mp4"
    )

    return textwrap.dedent(
        f"""
        ---
        library_name: stable-baselines3
        pipeline_tag: reinforcement-learning
        tags:
        - stable-baselines3
        - reinforcement-learning
        - deep-reinforcement-learning
        - PPO
        - {env_id}
        ---

        # PPO agent for {env_id}

        This repository contains a Stable-Baselines3 PPO actor–critic agent trained on `{env_id}`.

        ## Evaluation

        Deterministic evaluation over {evaluation['n_episodes']} fixed-seed episodes:

        | Metric | Value |
        |---|---:|
        | Mean reward | {evaluation['mean_reward']:.2f} |
        | Standard deviation | {evaluation['std_reward']:.2f} |
        | Course-style score (`mean - std`) | {evaluation['course_score']:.2f} |
        | Episodes scoring at least 200 | {evaluation['success_rate_200']:.1%} |
        | Minimum reward | {evaluation['min_reward']:.2f} |
        | Maximum reward | {evaluation['max_reward']:.2f} |

        {comparison_text}

        ## Architecture

        - Algorithm: PPO
        - Policy: MLP actor–critic
        - Actor hidden layers: `{actor_layers}`
        - Critic hidden layers: `{critic_layers}`

        ## Replay

        Replay seed: `{replay['seed']}`
        Replay reward: `{replay['reward']:.2f}`

        <video controls autoplay loop muted width="640">
          <source src="{replay_url}" type="video/mp4">
        </video>

        ## Load the model

        ```python
        from huggingface_hub import hf_hub_download
        from stable_baselines3 import PPO

        checkpoint = hf_hub_download(
            repo_id="{repo_id}",
            filename="{model_filename}",
        )

        model = PPO.load(checkpoint)
        ```
        """
    ).strip()


def promote_model_to_hub(
    candidate_model_or_path: PPO | str | Path,
    *,
    repo_id: str,
    model_filename: str = "ppo-LunarLander-v3.zip",
    env_id: str = "LunarLander-v3",
    env_kwargs: dict[str, Any] | None = None,
    evaluation_seeds: Iterable[int] = range(
        10_000,
        10_100,
    ),
    compare_to_current: bool = True,
    selection_metric: str = "mean_reward",
    min_improvement: float = 0.0,
    force_upload: bool = False,
    upload: bool = True,
    video_seed: int = 42,
    training_config_path: str | Path | None = None,
    commit_message: str | None = None,
    private: bool = False,
    device: str = "cpu",
) -> dict[str, Any]:
    """
    Evaluate, compare, record and publish a candidate model.

    Parameters
    ----------
    compare_to_current:
        Compare against the model currently stored in the repo.

    selection_metric:
        "mean_reward", "course_score" or "success_rate_200".

    min_improvement:
        Required improvement over the current model.

    force_upload:
        Upload even if the candidate does not win.

    upload:
        Set False for a dry run that creates local staging files.
    """

    candidate_model = load_ppo_model(
        candidate_model_or_path,
        device=device,
    )

    seed_list = [
        int(seed)
        for seed in evaluation_seeds
    ]

    comparison = None

    if compare_to_current:
        comparison = compare_candidate_to_hub(
            candidate_model,
            repo_id=repo_id,
            hub_model_filename=model_filename,
            evaluation_seeds=seed_list,
            env_id=env_id,
            env_kwargs=env_kwargs,
            selection_metric=selection_metric,
            min_improvement=min_improvement,
            device=device,
        )

        candidate_results = (
            comparison["candidate"]
        )
        eligible = (
            comparison["candidate_is_better"]
        )

    else:
        candidate_results = evaluate_model(
            candidate_model,
            seeds=seed_list,
            env_id=env_id,
            env_kwargs=env_kwargs,
            device=device,
        )
        eligible = True

    if not eligible and not force_upload:
        print(
            "The candidate did not meet the "
            "promotion criterion. Nothing was uploaded."
        )

        return {
            "uploaded": False,
            "eligible": False,
            "comparison": comparison,
        }

    staging_dir = (
        Path("/content/hf-staging")
        / repo_id.replace("/", "__")
    )

    if staging_dir.exists():
        shutil.rmtree(staging_dir)

    staging_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    model_stem = (
        staging_dir
        / Path(model_filename).stem
    )

    candidate_model.save(
        str(model_stem)
    )

    saved_model_path = (
        staging_dir
        / model_filename
    )

    if not saved_model_path.exists():
        raise FileNotFoundError(
            f"Expected saved model at "
            f"{saved_model_path}"
        )

    replay = record_replay(
        candidate_model,
        output_path=(
            staging_dir
            / "replay.mp4"
        ),
        env_id=env_id,
        env_kwargs=env_kwargs,
        seed=video_seed,
        device=device,
    )

    training_config = None

    if training_config_path is not None:
        training_config_path = Path(
            training_config_path
        )

        if training_config_path.exists():
            training_config = json.loads(
                training_config_path.read_text(
                    encoding="utf-8"
                )
            )

            shutil.copy2(
                training_config_path,
                staging_dir
                / "training_config.json",
            )

    results_payload = {
        "env_id": env_id,
        "env_kwargs": dict(
            env_kwargs or {}
        ),
        "selection_metric": selection_metric,
        "min_improvement": min_improvement,
        "candidate": metrics_only(
            candidate_results
        ),
        "current_hub": (
            metrics_only(
                comparison["current"]
            )
            if comparison is not None
            and comparison["current"] is not None
            else None
        ),
        "improvement": (
            comparison["improvement"]
            if comparison is not None
            else None
        ),
        "evaluation_seeds": seed_list,
        "replay": replay,
    }

    (
        staging_dir
        / "results.json"
    ).write_text(
        json.dumps(
            results_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    config_payload = {
        "algorithm": "PPO",
        "env_id": env_id,
        "model_name": Path(
            model_filename
        ).stem,
        "mean_reward": (
            candidate_results["mean_reward"]
        ),
        "std_reward": (
            candidate_results["std_reward"]
        ),
    }

    (
        staging_dir
        / "config.json"
    ).write_text(
        json.dumps(
            config_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    readme = build_model_card(
        repo_id=repo_id,
        env_id=env_id,
        model_filename=model_filename,
        evaluation=candidate_results,
        replay=replay,
        training_config=training_config,
        comparison=comparison,
    )

    (
        staging_dir
        / "README.md"
    ).write_text(
        readme,
        encoding="utf-8",
    )

    print(
        "Staging files:",
        sorted(
            path.name
            for path in staging_dir.iterdir()
        ),
    )

    if not upload:
        print(
            "Dry run complete. Nothing was uploaded."
        )

        return {
            "uploaded": False,
            "eligible": True,
            "comparison": comparison,
            "staging_dir": staging_dir,
        }

    api = HfApi()

    api.create_repo(
        repo_id=repo_id,
        repo_type="model",
        private=private,
        exist_ok=True,
    )

    upload_result = api.upload_folder(
        folder_path=str(staging_dir),
        repo_id=repo_id,
        repo_type="model",
        commit_message=(
            commit_message
            or (
                "Promote improved PPO model "
                f"({selection_metric}="
                f"{candidate_results[selection_metric]:.2f})"
            )
        ),
    )

    print("Uploaded:", upload_result)

    return {
        "uploaded": True,
        "eligible": True,
        "comparison": comparison,
        "staging_dir": staging_dir,
        "upload_result": upload_result,
    }

#### Log in to Hugging Face

In [7]:
notebook_login()

## Model training

### 128 x 128 actor-critic model

In [9]:
run_128 = train_ppo_experiment(
    experiment_name="ppo_lunarlander_128x128",
    total_timesteps=5_000_000,
    env_id="LunarLander-v3",
    n_envs=16,
    seed=42,

    # Larger actor and critic
    actor_layers=(128, 128),
    critic_layers=(128, 128),

    # Tuned PPO parameters
    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    n_epochs=4,
    gamma=0.999,
    gae_lambda=0.98,
    ent_coef=0.01,
    clip_range=0.2,

    eval_every_timesteps=50_000,
    checkpoint_every_timesteps=100_000,
    n_eval_episodes=20,

    device="cpu",
)

run_128

<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

Using cpu device

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning:
datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects
to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 91.8     |
|    ep_rew_mean     | -191     |
| time/              |          |
|    fps             | 3617     |
|    iterations      | 1        |
|    time_elapsed    | 4        |
|    total_timesteps | 16384    |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 96.9         |
|    ep_rew_mean          | -144         |
| time/                   |              |
|    fps                  | 2055         |
|    iterations           | 2            |
|    time_elapsed         | 15           |
|    total_timesteps      | 32768        |
| train/                  |              |
|    approx_kl            | 0.0068507656 |
|    clip_fraction        | 0.0449       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.38        |
|    explained_variance   | -0.000167    |
|    learning_rate        | 0.0003       |
|    loss                 | 2.34e+03     |
|    n_updates            | 4            |
|    policy_gradient_loss | -0.00575     |
|    value_loss           | 4.26e+03     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 97          |
|    ep_rew_mean          | -125        |
| time/                   |             |
|    fps                  | 1796        |
|    iterations           | 3           |
|    time_elapsed         | 27          |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.006732185 |
|    clip_fraction        | 0.0467      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.38       |
|    explained_variance   | 0.0646      |
|    learning_rate        | 0.0003      |
|    loss                 | 321         |
|    n_updates            | 8           |
|    policy_gradient_loss | -0.0043     |
|    value_loss           | 1.4e+03     |
-----------------------------------------

Eval num_timesteps=50000, episode_reward=-7.48 +/- 61.85

Episode length: 91.75 +/- 16.29

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 91.8        |
|    mean_reward          | -7.48       |
| time/                   |             |
|    total_timesteps      | 50000       |
| train/                  |             |
|    approx_kl            | 0.006725785 |
|    clip_fraction        | 0.0889      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.37       |
|    explained_variance   | 0.0193      |
|    learning_rate        | 0.0003      |
|    loss                 | 384         |
|    n_updates            | 12          |
|    policy_gradient_loss | -0.000888   |
|    value_loss           | 640         |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 87.6     |
|    ep_rew_mean     | -106     |
| time/              |          |
|    fps             | 1606     |
|    iterations      | 4        |
|    time_elapsed    | 40       |
|    total_timesteps | 65536    |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 94.5         |
|    ep_rew_mean          | -106         |
| time/                   |              |
|    fps                  | 1548         |
|    iterations           | 5            |
|    time_elapsed         | 52           |
|    total_timesteps      | 81920        |
| train/                  |              |
|    approx_kl            | 0.0068007717 |
|    clip_fraction        | 0.055        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.36        |
|    explained_variance   | -0.0439      |
|    learning_rate        | 0.0003       |
|    loss                 | 225          |
|    n_updates            | 16           |
|    policy_gradient_loss | -0.00288     |
|    value_loss           | 673          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 96.4         |
|    ep_rew_mean          | -103         |
| time/                   |              |
|    fps                  | 1423         |
|    iterations           | 6            |
|    time_elapsed         | 69           |
|    total_timesteps      | 98304        |
| train/                  |              |
|    approx_kl            | 0.0069902996 |
|    clip_fraction        | 0.0763       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.35        |
|    explained_variance   | -0.007       |
|    learning_rate        | 0.0003       |
|    loss                 | 320          |
|    n_updates            | 20           |
|    policy_gradient_loss | -0.00463     |
|    value_loss           | 619          |
------------------------------------------

Eval num_timesteps=100000, episode_reward=57.51 +/- 117.47

Episode length: 361.25 +/- 175.28

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 361         |
|    mean_reward          | 57.5        |
| time/                   |             |
|    total_timesteps      | 100000      |
| train/                  |             |
|    approx_kl            | 0.005405112 |
|    clip_fraction        | 0.048       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.34       |
|    explained_variance   | -0.0139     |
|    learning_rate        | 0.0003      |
|    loss                 | 205         |
|    n_updates            | 24          |
|    policy_gradient_loss | -0.00479    |
|    value_loss           | 451         |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 90.8     |
|    ep_rew_mean     | -87.7    |
| time/              |          |
|    fps             | 1277     |
|    iterations      | 7        |
|    time_elapsed    | 89       |
|    total_timesteps | 114688   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 97.7        |
|    ep_rew_mean          | -70.9       |
| time/                   |             |
|    fps                  | 1304        |
|    iterations           | 8           |
|    time_elapsed         | 100         |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.007980425 |
|    clip_fraction        | 0.0739      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.31       |
|    explained_variance   | 0.0226      |
|    learning_rate        | 0.0003      |
|    loss                 | 241         |
|    n_updates            | 28          |
|    policy_gradient_loss | -0.00719    |
|    value_loss           | 381         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 105         |
|    ep_rew_mean          | -49.4       |
| time/                   |             |
|    fps                  | 1302        |
|    iterations           | 9           |
|    time_elapsed         | 113         |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.010318693 |
|    clip_fraction        | 0.0889      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.28       |
|    explained_variance   | 0.0415      |
|    learning_rate        | 0.0003      |
|    loss                 | 88.5        |
|    n_updates            | 32          |
|    policy_gradient_loss | -0.00758    |
|    value_loss           | 257         |
-----------------------------------------

Eval num_timesteps=150000, episode_reward=-190.21 +/- 41.91

Episode length: 490.00 +/- 209.01

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 490         |
|    mean_reward          | -190        |
| time/                   |             |
|    total_timesteps      | 150000      |
| train/                  |             |
|    approx_kl            | 0.009779174 |
|    clip_fraction        | 0.0667      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.25       |
|    explained_variance   | 0.079       |
|    learning_rate        | 0.0003      |
|    loss                 | 152         |
|    n_updates            | 36          |
|    policy_gradient_loss | -0.00658    |
|    value_loss           | 299         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 125      |
|    ep_rew_mean     | -41      |
| time/              |          |
|    fps             | 1196     |
|    iterations      | 10       |
|    time_elapsed    | 136      |
|    total_timesteps | 163840   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 129         |
|    ep_rew_mean          | -25         |
| time/                   |             |
|    fps                  | 1228        |
|    iterations           | 11          |
|    time_elapsed         | 146         |
|    total_timesteps      | 180224      |
| train/                  |             |
|    approx_kl            | 0.009263387 |
|    clip_fraction        | 0.0679      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.2        |
|    explained_variance   | 0.0384      |
|    learning_rate        | 0.0003      |
|    loss                 | 197         |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.00491    |
|    value_loss           | 328         |
-----------------------------------------
---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 154       |
|    ep_rew_mean          | -18.1     |
| time/                   |           |
|    fps                  | 1231      |
|    iterations           | 12        |
|    time_elapsed         | 159       |
|    total_timesteps      | 196608    |
| train/                  |           |
|    approx_kl            | 0.0085264 |
|    clip_fraction        | 0.0523    |
|    clip_range           | 0.2       |
|    entropy_loss         | -1.17     |
|    explained_variance   | 0.04      |
|    learning_rate        | 0.0003    |
|    loss                 | 247       |
|    n_updates            | 44        |
|    policy_gradient_loss | -0.00275  |
|    value_loss           | 420       |
---------------------------------------

Eval num_timesteps=200000, episode_reward=-201.41 +/- 50.05

Episode length: 504.15 +/- 183.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 504         |
|    mean_reward          | -201        |
| time/                   |             |
|    total_timesteps      | 200000      |
| train/                  |             |
|    approx_kl            | 0.008246455 |
|    clip_fraction        | 0.0574      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.13       |
|    explained_variance   | 0.0856      |
|    learning_rate        | 0.0003      |
|    loss                 | 230         |
|    n_updates            | 48          |
|    policy_gradient_loss | -0.00398    |
|    value_loss           | 489         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 213      |
|    ep_rew_mean     | -7.98    |
| time/              |          |
|    fps             | 1146     |
|    iterations      | 13       |
|    time_elapsed    | 185      |
|    total_timesteps | 212992   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 276         |
|    ep_rew_mean          | -2.45       |
| time/                   |             |
|    fps                  | 1061        |
|    iterations           | 14          |
|    time_elapsed         | 215         |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.004868484 |
|    clip_fraction        | 0.0297      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.14       |
|    explained_variance   | 0.115       |
|    learning_rate        | 0.0003      |
|    loss                 | 215         |
|    n_updates            | 52          |
|    policy_gradient_loss | -0.00181    |
|    value_loss           | 479         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 361         |
|    ep_rew_mean          | 1.9         |
| time/                   |             |
|    fps                  | 1022        |
|    iterations           | 15          |
|    time_elapsed         | 240         |
|    total_timesteps      | 245760      |
| train/                  |             |
|    approx_kl            | 0.010561377 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.23       |
|    explained_variance   | 0.149       |
|    learning_rate        | 0.0003      |
|    loss                 | 179         |
|    n_updates            | 56          |
|    policy_gradient_loss | -0.00313    |
|    value_loss           | 276         |
-----------------------------------------

Eval num_timesteps=250000, episode_reward=-151.62 +/- 49.68

Episode length: 472.25 +/- 159.50

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 472         |
|    mean_reward          | -152        |
| time/                   |             |
|    total_timesteps      | 250000      |
| train/                  |             |
|    approx_kl            | 0.005588296 |
|    clip_fraction        | 0.0302      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.22       |
|    explained_variance   | 0.499       |
|    learning_rate        | 0.0003      |
|    loss                 | 241         |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.000727   |
|    value_loss           | 281         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 426      |
|    ep_rew_mean     | 4.85     |
| time/              |          |
|    fps             | 966      |
|    iterations      | 16       |
|    time_elapsed    | 271      |
|    total_timesteps | 262144   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 430         |
|    ep_rew_mean          | 5.14        |
| time/                   |             |
|    fps                  | 932         |
|    iterations           | 17          |
|    time_elapsed         | 298         |
|    total_timesteps      | 278528      |
| train/                  |             |
|    approx_kl            | 0.005184806 |
|    clip_fraction        | 0.0305      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.2        |
|    explained_variance   | 0.635       |
|    learning_rate        | 0.0003      |
|    loss                 | 204         |
|    n_updates            | 64          |
|    policy_gradient_loss | -0.0022     |
|    value_loss           | 276         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 520          |
|    ep_rew_mean          | 14.1         |
| time/                   |              |
|    fps                  | 894          |
|    iterations           | 18           |
|    time_elapsed         | 329          |
|    total_timesteps      | 294912       |
| train/                  |              |
|    approx_kl            | 0.0053126616 |
|    clip_fraction        | 0.0468       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.2         |
|    explained_variance   | 0.777        |
|    learning_rate        | 0.0003       |
|    loss                 | 49.1         |
|    n_updates            | 68           |
|    policy_gradient_loss | -0.00275     |
|    value_loss           | 127          |
------------------------------------------

Eval num_timesteps=300000, episode_reward=-70.96 +/- 92.72

Episode length: 711.95 +/- 196.52

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 712          |
|    mean_reward          | -71          |
| time/                   |              |
|    total_timesteps      | 300000       |
| train/                  |              |
|    approx_kl            | 0.0048435153 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.79         |
|    learning_rate        | 0.0003       |
|    loss                 | 34           |
|    n_updates            | 72           |
|    policy_gradient_loss | -0.000201    |
|    value_loss           | 86.7         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 579      |
|    ep_rew_mean     | 28.8     |
| time/              |          |
|    fps             | 847      |
|    iterations      | 19       |
|    time_elapsed    | 367      |
|    total_timesteps | 311296   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 644          |
|    ep_rew_mean          | 42.2         |
| time/                   |              |
|    fps                  | 831          |
|    iterations           | 20           |
|    time_elapsed         | 394          |
|    total_timesteps      | 327680       |
| train/                  |              |
|    approx_kl            | 0.0053405967 |
|    clip_fraction        | 0.039        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.19        |
|    explained_variance   | 0.811        |
|    learning_rate        | 0.0003       |
|    loss                 | 77.9         |
|    n_updates            | 76           |
|    policy_gradient_loss | -0.000907    |
|    value_loss           | 123          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 677         |
|    ep_rew_mean          | 49          |
| time/                   |             |
|    fps                  | 815         |
|    iterations           | 21          |
|    time_elapsed         | 421         |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.004783748 |
|    clip_fraction        | 0.0531      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.19       |
|    explained_variance   | 0.848       |
|    learning_rate        | 0.0003      |
|    loss                 | 96.9        |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.000806   |
|    value_loss           | 120         |
-----------------------------------------

Eval num_timesteps=350000, episode_reward=-91.04 +/- 118.35

Episode length: 682.00 +/- 136.14

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 682         |
|    mean_reward          | -91         |
| time/                   |             |
|    total_timesteps      | 350000      |
| train/                  |             |
|    approx_kl            | 0.006286347 |
|    clip_fraction        | 0.0461      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.18       |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | 76.1        |
|    n_updates            | 84          |
|    policy_gradient_loss | -0.000951   |
|    value_loss           | 132         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 702      |
|    ep_rew_mean     | 50.5     |
| time/              |          |
|    fps             | 789      |
|    iterations      | 22       |
|    time_elapsed    | 456      |
|    total_timesteps | 360448   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 712         |
|    ep_rew_mean          | 51.3        |
| time/                   |             |
|    fps                  | 783         |
|    iterations           | 23          |
|    time_elapsed         | 481         |
|    total_timesteps      | 376832      |
| train/                  |             |
|    approx_kl            | 0.004965065 |
|    clip_fraction        | 0.0339      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.12       |
|    explained_variance   | 0.862       |
|    learning_rate        | 0.0003      |
|    loss                 | 46.2        |
|    n_updates            | 88          |
|    policy_gradient_loss | -0.00115    |
|    value_loss           | 120         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 746         |
|    ep_rew_mean          | 62.4        |
| time/                   |             |
|    fps                  | 773         |
|    iterations           | 24          |
|    time_elapsed         | 508         |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.002961952 |
|    clip_fraction        | 0.0266      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.12       |
|    explained_variance   | 0.779       |
|    learning_rate        | 0.0003      |
|    loss                 | 107         |
|    n_updates            | 92          |
|    policy_gradient_loss | -0.00123    |
|    value_loss           | 175         |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=111.22 +/- 98.25

Episode length: 609.70 +/- 111.42

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 610          |
|    mean_reward          | 111          |
| time/                   |              |
|    total_timesteps      | 400000       |
| train/                  |              |
|    approx_kl            | 0.0046503614 |
|    clip_fraction        | 0.0394       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.13        |
|    explained_variance   | 0.907        |
|    learning_rate        | 0.0003       |
|    loss                 | 32.8         |
|    n_updates            | 96           |
|    policy_gradient_loss | -0.000576    |
|    value_loss           | 70.8         |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 758      |
|    ep_rew_mean     | 67.3     |
| time/              |          |
|    fps             | 750      |
|    iterations      | 25       |
|    time_elapsed    | 545      |
|    total_timesteps | 409600   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 801          |
|    ep_rew_mean          | 74           |
| time/                   |              |
|    fps                  | 742          |
|    iterations           | 26           |
|    time_elapsed         | 573          |
|    total_timesteps      | 425984       |
| train/                  |              |
|    approx_kl            | 0.0073130075 |
|    clip_fraction        | 0.0627       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.12        |
|    explained_variance   | 0.891        |
|    learning_rate        | 0.0003       |
|    loss                 | 23.6         |
|    n_updates            | 100          |
|    policy_gradient_loss | -0.00109     |
|    value_loss           | 76.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 827          |
|    ep_rew_mean          | 82.8         |
| time/                   |              |
|    fps                  | 734          |
|    iterations           | 27           |
|    time_elapsed         | 601          |
|    total_timesteps      | 442368       |
| train/                  |              |
|    approx_kl            | 0.0039132056 |
|    clip_fraction        | 0.037        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.14        |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 40.8         |
|    n_updates            | 104          |
|    policy_gradient_loss | -0.000677    |
|    value_loss           | 87.2         |
------------------------------------------

Eval num_timesteps=450000, episode_reward=74.24 +/- 95.19

Episode length: 726.05 +/- 185.19

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 726         |
|    mean_reward          | 74.2        |
| time/                   |             |
|    total_timesteps      | 450000      |
| train/                  |             |
|    approx_kl            | 0.004588252 |
|    clip_fraction        | 0.0405      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | 0.923       |
|    learning_rate        | 0.0003      |
|    loss                 | 26.3        |
|    n_updates            | 108         |
|    policy_gradient_loss | -0.000102   |
|    value_loss           | 51.4        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 858      |
|    ep_rew_mean     | 92.7     |
| time/              |          |
|    fps             | 717      |
|    iterations      | 28       |
|    time_elapsed    | 639      |
|    total_timesteps | 458752   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 881         |
|    ep_rew_mean          | 99.2        |
| time/                   |             |
|    fps                  | 714         |
|    iterations           | 29          |
|    time_elapsed         | 664         |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.004202796 |
|    clip_fraction        | 0.0364      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.07       |
|    explained_variance   | 0.931       |
|    learning_rate        | 0.0003      |
|    loss                 | 23          |
|    n_updates            | 112         |
|    policy_gradient_loss | -0.00158    |
|    value_loss           | 58.5        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 878         |
|    ep_rew_mean          | 98.8        |
| time/                   |             |
|    fps                  | 712         |
|    iterations           | 30          |
|    time_elapsed         | 689         |
|    total_timesteps      | 491520      |
| train/                  |             |
|    approx_kl            | 0.004687106 |
|    clip_fraction        | 0.0383      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.1        |
|    explained_variance   | 0.941       |
|    learning_rate        | 0.0003      |
|    loss                 | 50          |
|    n_updates            | 116         |
|    policy_gradient_loss | -0.000429   |
|    value_loss           | 50          |
-----------------------------------------

Eval num_timesteps=500000, episode_reward=187.74 +/- 31.85

Episode length: 627.75 +/- 96.65

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 628          |
|    mean_reward          | 188          |
| time/                   |              |
|    total_timesteps      | 500000       |
| train/                  |              |
|    approx_kl            | 0.0046625575 |
|    clip_fraction        | 0.0238       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.08        |
|    explained_variance   | 0.932        |
|    learning_rate        | 0.0003       |
|    loss                 | 30.1         |
|    n_updates            | 120          |
|    policy_gradient_loss | -0.000422    |
|    value_loss           | 70.4         |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 887      |
|    ep_rew_mean     | 104      |
| time/              |          |
|    fps             | 698      |
|    iterations      | 31       |
|    time_elapsed    | 726      |
|    total_timesteps | 507904   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 872         |
|    ep_rew_mean          | 106         |
| time/                   |             |
|    fps                  | 694         |
|    iterations           | 32          |
|    time_elapsed         | 754         |
|    total_timesteps      | 524288      |
| train/                  |             |
|    approx_kl            | 0.007075958 |
|    clip_fraction        | 0.0743      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | 0.923       |
|    learning_rate        | 0.0003      |
|    loss                 | 7.9         |
|    n_updates            | 124         |
|    policy_gradient_loss | -0.00177    |
|    value_loss           | 76.6        |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 873        |
|    ep_rew_mean          | 111        |
| time/                   |            |
|    fps                  | 691        |
|    iterations           | 33         |
|    time_elapsed         | 782        |
|    total_timesteps      | 540672     |
| train/                  |            |
|    approx_kl            | 0.00836837 |
|    clip_fraction        | 0.0458     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.09      |
|    explained_variance   | 0.945      |
|    learning_rate        | 0.0003     |
|    loss                 | 44.3       |
|    n_updates            | 128        |
|    policy_gradient_loss | -0.00144   |
|    value_loss           | 57.9       |
----------------------------------------

Eval num_timesteps=550000, episode_reward=232.60 +/- 17.31

Episode length: 547.35 +/- 42.82

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 547         |
|    mean_reward          | 233         |
| time/                   |             |
|    total_timesteps      | 550000      |
| train/                  |             |
|    approx_kl            | 0.004566347 |
|    clip_fraction        | 0.0462      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.41        |
|    n_updates            | 132         |
|    policy_gradient_loss | -0.00159    |
|    value_loss           | 42.9        |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 876      |
|    ep_rew_mean     | 118      |
| time/              |          |
|    fps             | 679      |
|    iterations      | 34       |
|    time_elapsed    | 819      |
|    total_timesteps | 557056   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 877         |
|    ep_rew_mean          | 120         |
| time/                   |             |
|    fps                  | 677         |
|    iterations           | 35          |
|    time_elapsed         | 846         |
|    total_timesteps      | 573440      |
| train/                  |             |
|    approx_kl            | 0.008728156 |
|    clip_fraction        | 0.0585      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.84        |
|    n_updates            | 136         |
|    policy_gradient_loss | -0.00148    |
|    value_loss           | 30.3        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 900         |
|    ep_rew_mean          | 126         |
| time/                   |             |
|    fps                  | 674         |
|    iterations           | 36          |
|    time_elapsed         | 874         |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.005916846 |
|    clip_fraction        | 0.0317      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | 7.46        |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.000392   |
|    value_loss           | 38          |
-----------------------------------------

Eval num_timesteps=600000, episode_reward=192.59 +/- 46.52

Episode length: 632.85 +/- 63.96

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 633         |
|    mean_reward          | 193         |
| time/                   |             |
|    total_timesteps      | 600000      |
| train/                  |             |
|    approx_kl            | 0.004843517 |
|    clip_fraction        | 0.0554      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | 0.99        |
|    learning_rate        | 0.0003      |
|    loss                 | 4.24        |
|    n_updates            | 144         |
|    policy_gradient_loss | -0.000589   |
|    value_loss           | 7.92        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 934      |
|    ep_rew_mean     | 130      |
| time/              |          |
|    fps             | 663      |
|    iterations      | 37       |
|    time_elapsed    | 914      |
|    total_timesteps | 606208   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 927         |
|    ep_rew_mean          | 125         |
| time/                   |             |
|    fps                  | 661         |
|    iterations           | 38          |
|    time_elapsed         | 941         |
|    total_timesteps      | 622592      |
| train/                  |             |
|    approx_kl            | 0.010201164 |
|    clip_fraction        | 0.0932      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.06       |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.827       |
|    n_updates            | 148         |
|    policy_gradient_loss | -0.00183    |
|    value_loss           | 3.47        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 935         |
|    ep_rew_mean          | 124         |
| time/                   |             |
|    fps                  | 659         |
|    iterations           | 39          |
|    time_elapsed         | 968         |
|    total_timesteps      | 638976      |
| train/                  |             |
|    approx_kl            | 0.005801108 |
|    clip_fraction        | 0.0416      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.06       |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | 11          |
|    n_updates            | 152         |
|    policy_gradient_loss | -0.00115    |
|    value_loss           | 31.1        |
-----------------------------------------

Eval num_timesteps=650000, episode_reward=229.03 +/- 21.13

Episode length: 484.60 +/- 24.20

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 485          |
|    mean_reward          | 229          |
| time/                   |              |
|    total_timesteps      | 650000       |
| train/                  |              |
|    approx_kl            | 0.0054870574 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.02        |
|    explained_variance   | 0.986        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.49         |
|    n_updates            | 156          |
|    policy_gradient_loss | -0.00221     |
|    value_loss           | 15.1         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 935      |
|    ep_rew_mean     | 125      |
| time/              |          |
|    fps             | 652      |
|    iterations      | 40       |
|    time_elapsed    | 1004     |
|    total_timesteps | 655360   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 957          |
|    ep_rew_mean          | 131          |
| time/                   |              |
|    fps                  | 650          |
|    iterations           | 41           |
|    time_elapsed         | 1032         |
|    total_timesteps      | 671744       |
| train/                  |              |
|    approx_kl            | 0.0053526983 |
|    clip_fraction        | 0.0429       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.04        |
|    explained_variance   | 0.993        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.12         |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.000296    |
|    value_loss           | 7.04         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 957          |
|    ep_rew_mean          | 131          |
| time/                   |              |
|    fps                  | 648          |
|    iterations           | 42           |
|    time_elapsed         | 1061         |
|    total_timesteps      | 688128       |
| train/                  |              |
|    approx_kl            | 0.0058354214 |
|    clip_fraction        | 0.0492       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.03        |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.92         |
|    n_updates            | 164          |
|    policy_gradient_loss | -0.00052     |
|    value_loss           | 3.04         |
------------------------------------------

Eval num_timesteps=700000, episode_reward=222.17 +/- 18.51

Episode length: 477.20 +/- 14.10

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 477         |
|    mean_reward          | 222         |
| time/                   |             |
|    total_timesteps      | 700000      |
| train/                  |             |
|    approx_kl            | 0.008786118 |
|    clip_fraction        | 0.0639      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.01       |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.837       |
|    n_updates            | 168         |
|    policy_gradient_loss | -0.00191    |
|    value_loss           | 3.52        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 957      |
|    ep_rew_mean     | 133      |
| time/              |          |
|    fps             | 641      |
|    iterations      | 43       |
|    time_elapsed    | 1098     |
|    total_timesteps | 704512   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 985          |
|    ep_rew_mean          | 138          |
| time/                   |              |
|    fps                  | 639          |
|    iterations           | 44           |
|    time_elapsed         | 1127         |
|    total_timesteps      | 720896       |
| train/                  |              |
|    approx_kl            | 0.0056549795 |
|    clip_fraction        | 0.0647       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.988       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.3          |
|    n_updates            | 172          |
|    policy_gradient_loss | -0.00146     |
|    value_loss           | 2.56         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 993         |
|    ep_rew_mean          | 142         |
| time/                   |             |
|    fps                  | 637         |
|    iterations           | 45          |
|    time_elapsed         | 1156        |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.005470022 |
|    clip_fraction        | 0.0707      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.963      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.125       |
|    n_updates            | 176         |
|    policy_gradient_loss | -0.00173    |
|    value_loss           | 1.96        |
-----------------------------------------

Eval num_timesteps=750000, episode_reward=235.94 +/- 19.96

Episode length: 412.55 +/- 15.84

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 413          |
|    mean_reward          | 236          |
| time/                   |              |
|    total_timesteps      | 750000       |
| train/                  |              |
|    approx_kl            | 0.0050461586 |
|    clip_fraction        | 0.0378       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.973       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.462        |
|    n_updates            | 180          |
|    policy_gradient_loss | 0.000214     |
|    value_loss           | 1.71         |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 993      |
|    ep_rew_mean     | 144      |
| time/              |          |
|    fps             | 632      |
|    iterations      | 46       |
|    time_elapsed    | 1192     |
|    total_timesteps | 753664   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1e+03        |
|    ep_rew_mean          | 146          |
| time/                   |              |
|    fps                  | 631          |
|    iterations           | 47           |
|    time_elapsed         | 1218         |
|    total_timesteps      | 770048       |
| train/                  |              |
|    approx_kl            | 0.0077415165 |
|    clip_fraction        | 0.0473       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.933       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.24         |
|    n_updates            | 184          |
|    policy_gradient_loss | -0.00219     |
|    value_loss           | 1.44         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | 145         |
| time/                   |             |
|    fps                  | 631         |
|    iterations           | 48          |
|    time_elapsed         | 1245        |
|    total_timesteps      | 786432      |
| train/                  |             |
|    approx_kl            | 0.006228267 |
|    clip_fraction        | 0.0426      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.89       |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.29        |
|    n_updates            | 188         |
|    policy_gradient_loss | -0.00117    |
|    value_loss           | 1.21        |
-----------------------------------------

Eval num_timesteps=800000, episode_reward=252.71 +/- 22.83

Episode length: 378.70 +/- 24.86

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 379        |
|    mean_reward          | 253        |
| time/                   |            |
|    total_timesteps      | 800000     |
| train/                  |            |
|    approx_kl            | 0.00578793 |
|    clip_fraction        | 0.0536     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.822     |
|    explained_variance   | 0.999      |
|    learning_rate        | 0.0003     |
|    loss                 | 0.741      |
|    n_updates            | 192        |
|    policy_gradient_loss | -0.00081   |
|    value_loss           | 1.71       |
----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | 146      |
| time/              |          |
|    fps             | 629      |
|    iterations      | 49       |
|    time_elapsed    | 1275     |
|    total_timesteps | 802816   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1e+03        |
|    ep_rew_mean          | 149          |
| time/                   |              |
|    fps                  | 630          |
|    iterations           | 50           |
|    time_elapsed         | 1300         |
|    total_timesteps      | 819200       |
| train/                  |              |
|    approx_kl            | 0.0042703645 |
|    clip_fraction        | 0.0381       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.824       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.177        |
|    n_updates            | 196          |
|    policy_gradient_loss | -0.000145    |
|    value_loss           | 1.03         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 988          |
|    ep_rew_mean          | 155          |
| time/                   |              |
|    fps                  | 630          |
|    iterations           | 51           |
|    time_elapsed         | 1326         |
|    total_timesteps      | 835584       |
| train/                  |              |
|    approx_kl            | 0.0043008467 |
|    clip_fraction        | 0.0468       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.784       |
|    explained_variance   | 0.986        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.306        |
|    n_updates            | 200          |
|    policy_gradient_loss | -0.00103     |
|    value_loss           | 22.9         |
------------------------------------------

Eval num_timesteps=850000, episode_reward=259.49 +/- 12.89

Episode length: 366.15 +/- 19.88

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 366          |
|    mean_reward          | 259          |
| time/                   |              |
|    total_timesteps      | 850000       |
| train/                  |              |
|    approx_kl            | 0.0034237518 |
|    clip_fraction        | 0.0414       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.751       |
|    explained_variance   | 0.965        |
|    learning_rate        | 0.0003       |
|    loss                 | 89.5         |
|    n_updates            | 204          |
|    policy_gradient_loss | -0.000349    |
|    value_loss           | 67.8         |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 969      |
|    ep_rew_mean     | 161      |
| time/              |          |
|    fps             | 628      |
|    iterations      | 52       |
|    time_elapsed    | 1355     |
|    total_timesteps | 851968   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 924         |
|    ep_rew_mean          | 175         |
| time/                   |             |
|    fps                  | 630         |
|    iterations           | 53          |
|    time_elapsed         | 1378        |
|    total_timesteps      | 868352      |
| train/                  |             |
|    approx_kl            | 0.004023671 |
|    clip_fraction        | 0.0458      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.735      |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.34        |
|    n_updates            | 208         |
|    policy_gradient_loss | -0.00187    |
|    value_loss           | 118         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 867         |
|    ep_rew_mean          | 196         |
| time/                   |             |
|    fps                  | 631         |
|    iterations           | 54          |
|    time_elapsed         | 1401        |
|    total_timesteps      | 884736      |
| train/                  |             |
|    approx_kl            | 0.005868518 |
|    clip_fraction        | 0.0711      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.7        |
|    explained_variance   | 0.886       |
|    learning_rate        | 0.0003      |
|    loss                 | 105         |
|    n_updates            | 212         |
|    policy_gradient_loss | -0.00301    |
|    value_loss           | 238         |
-----------------------------------------

Eval num_timesteps=900000, episode_reward=252.42 +/- 20.15

Episode length: 336.00 +/- 17.09

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 336          |
|    mean_reward          | 252          |
| time/                   |              |
|    total_timesteps      | 900000       |
| train/                  |              |
|    approx_kl            | 0.0084712915 |
|    clip_fraction        | 0.101        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.691       |
|    explained_variance   | 0.838        |
|    learning_rate        | 0.0003       |
|    loss                 | 131          |
|    n_updates            | 216          |
|    policy_gradient_loss | -0.00392     |
|    value_loss           | 267          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 702      |
|    ep_rew_mean     | 228      |
| time/              |          |
|    fps             | 632      |
|    iterations      | 55       |
|    time_elapsed    | 1425     |
|    total_timesteps | 901120   |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 513         |
|    ep_rew_mean          | 252         |
| time/                   |             |
|    fps                  | 636         |
|    iterations           | 56          |
|    time_elapsed         | 1441        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.012339832 |
|    clip_fraction        | 0.0708      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.679      |
|    explained_variance   | 0.781       |
|    learning_rate        | 0.0003      |
|    loss                 | 203         |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.00503    |
|    value_loss           | 348         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 399         |
|    ep_rew_mean          | 240         |
| time/                   |             |
|    fps                  | 640         |
|    iterations           | 57          |
|    time_elapsed         | 1457        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.010219284 |
|    clip_fraction        | 0.078       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.763      |
|    explained_variance   | 0.802       |
|    learning_rate        | 0.0003      |
|    loss                 | 76          |
|    n_updates            | 224         |
|    policy_gradient_loss | -0.00262    |
|    value_loss           | 197         |
-----------------------------------------

Eval num_timesteps=950000, episode_reward=256.75 +/- 23.30

Episode length: 324.20 +/- 11.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 324          |
|    mean_reward          | 257          |
| time/                   |              |
|    total_timesteps      | 950000       |
| train/                  |              |
|    approx_kl            | 0.0042660167 |
|    clip_fraction        | 0.0489       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.773       |
|    explained_variance   | 0.831        |
|    learning_rate        | 0.0003       |
|    loss                 | 35.6         |
|    n_updates            | 228          |
|    policy_gradient_loss | 0.000456     |
|    value_loss           | 247          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 336      |
|    ep_rew_mean     | 249      |
| time/              |          |
|    fps             | 643      |
|    iterations      | 58       |
|    time_elapsed    | 1477     |
|    total_timesteps | 950272   |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 308          |
|    ep_rew_mean          | 255          |
| time/                   |              |
|    fps                  | 647          |
|    iterations           | 59           |
|    time_elapsed         | 1492         |
|    total_timesteps      | 966656       |
| train/                  |              |
|    approx_kl            | 0.0051765516 |
|    clip_fraction        | 0.0608       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.754       |
|    explained_variance   | 0.774        |
|    learning_rate        | 0.0003       |
|    loss                 | 74.2         |
|    n_updates            | 232          |
|    policy_gradient_loss | -0.000828    |
|    value_loss           | 123          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 295          |
|    ep_rew_mean          | 252          |
| time/                   |              |
|    fps                  | 652          |
|    iterations           | 60           |
|    time_elapsed         | 1506         |
|    total_timesteps      | 983040       |
| train/                  |              |
|    approx_kl            | 0.0039297026 |
|    clip_fraction        | 0.0332       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.774       |
|    explained_variance   | 0.695        |
|    learning_rate        | 0.0003       |
|    loss                 | 107          |
|    n_updates            | 236          |
|    policy_gradient_loss | -0.000157    |
|    value_loss           | 306          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 287          |
|    ep_rew_mean          | 248          |
| time/                   |              |
|    fps                  | 657          |
|    iterations           | 61           |
|    time_elapsed         | 1520         |
|    total_timesteps      | 999424       |
| train/                  |              |
|    approx_kl            | 0.0037051393 |
|    clip_fraction        | 0.0292       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.791       |
|    explained_variance   | 0.586        |
|    learning_rate        | 0.0003       |
|    loss                 | 42.4         |
|    n_updates            | 240          |
|    policy_gradient_loss | 3.94e-05     |
|    value_loss           | 354          |
------------------------------------------

Eval num_timesteps=1000000, episode_reward=268.85 +/- 17.16

Episode length: 320.15 +/- 20.55

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 320          |
|    mean_reward          | 269          |
| time/                   |              |
|    total_timesteps      | 1000000      |
| train/                  |              |
|    approx_kl            | 0.0034990383 |
|    clip_fraction        | 0.0423       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.762       |
|    explained_variance   | 0.704        |
|    learning_rate        | 0.0003       |
|    loss                 | 64.1         |
|    n_updates            | 244          |
|    policy_gradient_loss | -0.000264    |
|    value_loss           | 265          |
------------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1000000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 301      |
|    ep_rew_mean     | 253      |
| time/              |          |
|    fps             | 660      |
|    iterations      | 62       |
|    time_elapsed    | 1538     |
|    total_timesteps | 1015808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 319          |
|    ep_rew_mean          | 263          |
| time/                   |              |
|    fps                  | 663          |
|    iterations           | 63           |
|    time_elapsed         | 1554         |
|    total_timesteps      | 1032192      |
| train/                  |              |
|    approx_kl            | 0.0059010326 |
|    clip_fraction        | 0.0596       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.768       |
|    explained_variance   | 0.915        |
|    learning_rate        | 0.0003       |
|    loss                 | 148          |
|    n_updates            | 248          |
|    policy_gradient_loss | 0.000439     |
|    value_loss           | 165          |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 344        |
|    ep_rew_mean          | 262        |
| time/                   |            |
|    fps                  | 667        |
|    iterations           | 64         |
|    time_elapsed         | 1571       |
|    total_timesteps      | 1048576    |
| train/                  |            |
|    approx_kl            | 0.00702555 |
|    clip_fraction        | 0.0632     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.747     |
|    explained_variance   | 0.962      |
|    learning_rate        | 0.0003     |
|    loss                 | 15.3       |
|    n_updates            | 252        |
|    policy_gradient_loss | 0.000211   |
|    value_loss           | 35.8       |
----------------------------------------

Eval num_timesteps=1050000, episode_reward=267.46 +/- 20.93

Episode length: 315.75 +/- 14.39

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 316         |
|    mean_reward          | 267         |
| time/                   |             |
|    total_timesteps      | 1050000     |
| train/                  |             |
|    approx_kl            | 0.005179475 |
|    clip_fraction        | 0.0666      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.743      |
|    explained_variance   | 0.986       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.13        |
|    n_updates            | 256         |
|    policy_gradient_loss | 0.000551    |
|    value_loss           | 9.61        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 365      |
|    ep_rew_mean     | 260      |
| time/              |          |
|    fps             | 668      |
|    iterations      | 65       |
|    time_elapsed    | 1592     |
|    total_timesteps | 1064960  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 354          |
|    ep_rew_mean          | 254          |
| time/                   |              |
|    fps                  | 672          |
|    iterations           | 66           |
|    time_elapsed         | 1608         |
|    total_timesteps      | 1081344      |
| train/                  |              |
|    approx_kl            | 0.0072752163 |
|    clip_fraction        | 0.0423       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.751       |
|    explained_variance   | 0.93         |
|    learning_rate        | 0.0003       |
|    loss                 | 6.21         |
|    n_updates            | 260          |
|    policy_gradient_loss | 0.000335     |
|    value_loss           | 110          |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 341        |
|    ep_rew_mean          | 263        |
| time/                   |            |
|    fps                  | 675        |
|    iterations           | 67         |
|    time_elapsed         | 1624       |
|    total_timesteps      | 1097728    |
| train/                  |            |
|    approx_kl            | 0.00406382 |
|    clip_fraction        | 0.0384     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.729     |
|    explained_variance   | 0.935      |
|    learning_rate        | 0.0003     |
|    loss                 | 27.3       |
|    n_updates            | 264        |
|    policy_gradient_loss | -5.74e-05  |
|    value_loss           | 118        |
----------------------------------------

Eval num_timesteps=1100000, episode_reward=266.36 +/- 22.42

Episode length: 319.55 +/- 23.47

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 320         |
|    mean_reward          | 266         |
| time/                   |             |
|    total_timesteps      | 1100000     |
| train/                  |             |
|    approx_kl            | 0.004809612 |
|    clip_fraction        | 0.0559      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.739      |
|    explained_variance   | 0.992       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.06        |
|    n_updates            | 268         |
|    policy_gradient_loss | 4.83e-05    |
|    value_loss           | 7.65        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 322      |
|    ep_rew_mean     | 266      |
| time/              |          |
|    fps             | 677      |
|    iterations      | 68       |
|    time_elapsed    | 1643     |
|    total_timesteps | 1114112  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 303         |
|    ep_rew_mean          | 266         |
| time/                   |             |
|    fps                  | 681         |
|    iterations           | 69          |
|    time_elapsed         | 1658        |
|    total_timesteps      | 1130496     |
| train/                  |             |
|    approx_kl            | 0.004027331 |
|    clip_fraction        | 0.0439      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.785      |
|    explained_variance   | 0.96        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.96        |
|    n_updates            | 272         |
|    policy_gradient_loss | 0.000315    |
|    value_loss           | 70.2        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 296          |
|    ep_rew_mean          | 269          |
| time/                   |              |
|    fps                  | 685          |
|    iterations           | 70           |
|    time_elapsed         | 1674         |
|    total_timesteps      | 1146880      |
| train/                  |              |
|    approx_kl            | 0.0053320276 |
|    clip_fraction        | 0.0607       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.757       |
|    explained_variance   | 0.996        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.45         |
|    n_updates            | 276          |
|    policy_gradient_loss | 0.00063      |
|    value_loss           | 4.17         |
------------------------------------------

Eval num_timesteps=1150000, episode_reward=266.51 +/- 20.50

Episode length: 294.15 +/- 15.72

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 294          |
|    mean_reward          | 267          |
| time/                   |              |
|    total_timesteps      | 1150000      |
| train/                  |              |
|    approx_kl            | 0.0047895927 |
|    clip_fraction        | 0.0611       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.758       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.69         |
|    n_updates            | 280          |
|    policy_gradient_loss | -0.000951    |
|    value_loss           | 3.39         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 298      |
|    ep_rew_mean     | 263      |
| time/              |          |
|    fps             | 687      |
|    iterations      | 71       |
|    time_elapsed    | 1692     |
|    total_timesteps | 1163264  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 286         |
|    ep_rew_mean          | 265         |
| time/                   |             |
|    fps                  | 691         |
|    iterations           | 72          |
|    time_elapsed         | 1705        |
|    total_timesteps      | 1179648     |
| train/                  |             |
|    approx_kl            | 0.004122763 |
|    clip_fraction        | 0.0457      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.736      |
|    explained_variance   | 0.944       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.32        |
|    n_updates            | 284         |
|    policy_gradient_loss | 0.000585    |
|    value_loss           | 22.8        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 287          |
|    ep_rew_mean          | 271          |
| time/                   |              |
|    fps                  | 695          |
|    iterations           | 73           |
|    time_elapsed         | 1719         |
|    total_timesteps      | 1196032      |
| train/                  |              |
|    approx_kl            | 0.0047180424 |
|    clip_fraction        | 0.0559       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.719       |
|    explained_variance   | 0.986        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.35         |
|    n_updates            | 288          |
|    policy_gradient_loss | 0.00067      |
|    value_loss           | 16.2         |
------------------------------------------

Eval num_timesteps=1200000, episode_reward=265.27 +/- 17.90

Episode length: 288.80 +/- 15.37

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 289         |
|    mean_reward          | 265         |
| time/                   |             |
|    total_timesteps      | 1200000     |
| train/                  |             |
|    approx_kl            | 0.005512296 |
|    clip_fraction        | 0.0667      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.745      |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.15        |
|    n_updates            | 292         |
|    policy_gradient_loss | 0.000734    |
|    value_loss           | 2.99        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 280      |
|    ep_rew_mean     | 266      |
| time/              |          |
|    fps             | 698      |
|    iterations      | 74       |
|    time_elapsed    | 1736     |
|    total_timesteps | 1212416  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 272          |
|    ep_rew_mean          | 262          |
| time/                   |              |
|    fps                  | 701          |
|    iterations           | 75           |
|    time_elapsed         | 1750         |
|    total_timesteps      | 1228800      |
| train/                  |              |
|    approx_kl            | 0.0033464923 |
|    clip_fraction        | 0.03         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.73        |
|    explained_variance   | 0.935        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.82         |
|    n_updates            | 296          |
|    policy_gradient_loss | 0.00036      |
|    value_loss           | 126          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 276         |
|    ep_rew_mean          | 262         |
| time/                   |             |
|    fps                  | 705         |
|    iterations           | 76          |
|    time_elapsed         | 1764        |
|    total_timesteps      | 1245184     |
| train/                  |             |
|    approx_kl            | 0.004643747 |
|    clip_fraction        | 0.0536      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.76       |
|    explained_variance   | 0.931       |
|    learning_rate        | 0.0003      |
|    loss                 | 20.2        |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.00068    |
|    value_loss           | 118         |
-----------------------------------------

Eval num_timesteps=1250000, episode_reward=262.92 +/- 20.41

Episode length: 289.20 +/- 17.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 289          |
|    mean_reward          | 263          |
| time/                   |              |
|    total_timesteps      | 1250000      |
| train/                  |              |
|    approx_kl            | 0.0055122864 |
|    clip_fraction        | 0.0479       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.731       |
|    explained_variance   | 0.91         |
|    learning_rate        | 0.0003       |
|    loss                 | 6.79         |
|    n_updates            | 304          |
|    policy_gradient_loss | 0.000845     |
|    value_loss           | 140          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 277      |
|    ep_rew_mean     | 266      |
| time/              |          |
|    fps             | 707      |
|    iterations      | 77       |
|    time_elapsed    | 1782     |
|    total_timesteps | 1261568  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 270          |
|    ep_rew_mean          | 268          |
| time/                   |              |
|    fps                  | 711          |
|    iterations           | 78           |
|    time_elapsed         | 1795         |
|    total_timesteps      | 1277952      |
| train/                  |              |
|    approx_kl            | 0.0071141073 |
|    clip_fraction        | 0.0608       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.717       |
|    explained_variance   | 0.95         |
|    learning_rate        | 0.0003       |
|    loss                 | 5.27         |
|    n_updates            | 308          |
|    policy_gradient_loss | 0.00116      |
|    value_loss           | 79           |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 277         |
|    ep_rew_mean          | 271         |
| time/                   |             |
|    fps                  | 715         |
|    iterations           | 79          |
|    time_elapsed         | 1809        |
|    total_timesteps      | 1294336     |
| train/                  |             |
|    approx_kl            | 0.005647487 |
|    clip_fraction        | 0.0645      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.716      |
|    explained_variance   | 0.978       |
|    learning_rate        | 0.0003      |
|    loss                 | 85          |
|    n_updates            | 312         |
|    policy_gradient_loss | 0.00129     |
|    value_loss           | 33.4        |
-----------------------------------------

Eval num_timesteps=1300000, episode_reward=271.90 +/- 19.43

Episode length: 285.80 +/- 15.16

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 286         |
|    mean_reward          | 272         |
| time/                   |             |
|    total_timesteps      | 1300000     |
| train/                  |             |
|    approx_kl            | 0.005367443 |
|    clip_fraction        | 0.0767      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.715      |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.753       |
|    n_updates            | 316         |
|    policy_gradient_loss | 0.00192     |
|    value_loss           | 3.82        |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 278      |
|    ep_rew_mean     | 271      |
| time/              |          |
|    fps             | 717      |
|    iterations      | 80       |
|    time_elapsed    | 1826     |
|    total_timesteps | 1310720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 271          |
|    ep_rew_mean          | 273          |
| time/                   |              |
|    fps                  | 721          |
|    iterations           | 81           |
|    time_elapsed         | 1839         |
|    total_timesteps      | 1327104      |
| train/                  |              |
|    approx_kl            | 0.0040351963 |
|    clip_fraction        | 0.0471       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.732       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.25         |
|    n_updates            | 320          |
|    policy_gradient_loss | 0.000495     |
|    value_loss           | 5.16         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 270         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 725         |
|    iterations           | 82          |
|    time_elapsed         | 1852        |
|    total_timesteps      | 1343488     |
| train/                  |             |
|    approx_kl            | 0.005278993 |
|    clip_fraction        | 0.0593      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.704      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.62        |
|    n_updates            | 324         |
|    policy_gradient_loss | 0.00164     |
|    value_loss           | 2.61        |
-----------------------------------------

Eval num_timesteps=1350000, episode_reward=274.68 +/- 20.74

Episode length: 289.25 +/- 19.17

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 289         |
|    mean_reward          | 275         |
| time/                   |             |
|    total_timesteps      | 1350000     |
| train/                  |             |
|    approx_kl            | 0.006467911 |
|    clip_fraction        | 0.0842      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.72       |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 8.07        |
|    n_updates            | 328         |
|    policy_gradient_loss | 0.000365    |
|    value_loss           | 7.49        |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 280      |
|    ep_rew_mean     | 270      |
| time/              |          |
|    fps             | 726      |
|    iterations      | 83       |
|    time_elapsed    | 1872     |
|    total_timesteps | 1359872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 279          |
|    ep_rew_mean          | 269          |
| time/                   |              |
|    fps                  | 730          |
|    iterations           | 84           |
|    time_elapsed         | 1885         |
|    total_timesteps      | 1376256      |
| train/                  |              |
|    approx_kl            | 0.0061504524 |
|    clip_fraction        | 0.0664       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.735       |
|    explained_variance   | 0.984        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.5          |
|    n_updates            | 332          |
|    policy_gradient_loss | 0.000579     |
|    value_loss           | 13           |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 273          |
|    ep_rew_mean          | 273          |
| time/                   |              |
|    fps                  | 733          |
|    iterations           | 85           |
|    time_elapsed         | 1898         |
|    total_timesteps      | 1392640      |
| train/                  |              |
|    approx_kl            | 0.0051569804 |
|    clip_fraction        | 0.0646       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.715       |
|    explained_variance   | 0.996        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.915        |
|    n_updates            | 336          |
|    policy_gradient_loss | 0.000601     |
|    value_loss           | 4.97         |
------------------------------------------

Eval num_timesteps=1400000, episode_reward=272.46 +/- 22.30

Episode length: 277.25 +/- 15.98

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 277          |
|    mean_reward          | 272          |
| time/                   |              |
|    total_timesteps      | 1400000      |
| train/                  |              |
|    approx_kl            | 0.0058980025 |
|    clip_fraction        | 0.0679       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.707       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.43         |
|    n_updates            | 340          |
|    policy_gradient_loss | -8.71e-05    |
|    value_loss           | 2.92         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 276      |
|    ep_rew_mean     | 274      |
| time/              |          |
|    fps             | 735      |
|    iterations      | 86       |
|    time_elapsed    | 1915     |
|    total_timesteps | 1409024  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 279         |
|    ep_rew_mean          | 268         |
| time/                   |             |
|    fps                  | 738         |
|    iterations           | 87          |
|    time_elapsed         | 1929        |
|    total_timesteps      | 1425408     |
| train/                  |             |
|    approx_kl            | 0.006755324 |
|    clip_fraction        | 0.0639      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.682      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.95        |
|    n_updates            | 344         |
|    policy_gradient_loss | 0.000195    |
|    value_loss           | 3.93        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 276          |
|    ep_rew_mean          | 270          |
| time/                   |              |
|    fps                  | 742          |
|    iterations           | 88           |
|    time_elapsed         | 1942         |
|    total_timesteps      | 1441792      |
| train/                  |              |
|    approx_kl            | 0.0045717694 |
|    clip_fraction        | 0.0448       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.696       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.23         |
|    n_updates            | 348          |
|    policy_gradient_loss | 0.00319      |
|    value_loss           | 52.6         |
------------------------------------------

Eval num_timesteps=1450000, episode_reward=273.25 +/- 20.50

Episode length: 276.35 +/- 21.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 276          |
|    mean_reward          | 273          |
| time/                   |              |
|    total_timesteps      | 1450000      |
| train/                  |              |
|    approx_kl            | 0.0052189096 |
|    clip_fraction        | 0.0649       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.696       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.29         |
|    n_updates            | 352          |
|    policy_gradient_loss | 0.000868     |
|    value_loss           | 2.55         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 267      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 744      |
|    iterations      | 89       |
|    time_elapsed    | 1958     |
|    total_timesteps | 1458176  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 264        |
|    ep_rew_mean          | 279        |
| time/                   |            |
|    fps                  | 747        |
|    iterations           | 90         |
|    time_elapsed         | 1971       |
|    total_timesteps      | 1474560    |
| train/                  |            |
|    approx_kl            | 0.00634374 |
|    clip_fraction        | 0.0832     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.708     |
|    explained_variance   | 0.998      |
|    learning_rate        | 0.0003     |
|    loss                 | 0.367      |
|    n_updates            | 356        |
|    policy_gradient_loss | 0.000187   |
|    value_loss           | 2.26       |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 259          |
|    ep_rew_mean          | 275          |
| time/                   |              |
|    fps                  | 751          |
|    iterations           | 91           |
|    time_elapsed         | 1984         |
|    total_timesteps      | 1490944      |
| train/                  |              |
|    approx_kl            | 0.0053976574 |
|    clip_fraction        | 0.0637       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.692       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.22         |
|    n_updates            | 360          |
|    policy_gradient_loss | 0.000277     |
|    value_loss           | 2.21         |
------------------------------------------

Eval num_timesteps=1500000, episode_reward=271.22 +/- 20.09

Episode length: 254.65 +/- 15.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 255         |
|    mean_reward          | 271         |
| time/                   |             |
|    total_timesteps      | 1500000     |
| train/                  |             |
|    approx_kl            | 0.004674295 |
|    clip_fraction        | 0.0502      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.68       |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.27        |
|    n_updates            | 364         |
|    policy_gradient_loss | -0.00079    |
|    value_loss           | 68.4        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 260      |
|    ep_rew_mean     | 272      |
| time/              |          |
|    fps             | 752      |
|    iterations      | 92       |
|    time_elapsed    | 2001     |
|    total_timesteps | 1507328  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 253         |
|    ep_rew_mean          | 276         |
| time/                   |             |
|    fps                  | 756         |
|    iterations           | 93          |
|    time_elapsed         | 2014        |
|    total_timesteps      | 1523712     |
| train/                  |             |
|    approx_kl            | 0.005177456 |
|    clip_fraction        | 0.0613      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.672      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.19        |
|    n_updates            | 368         |
|    policy_gradient_loss | 0.000597    |
|    value_loss           | 29.2        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 265         |
|    ep_rew_mean          | 275         |
| time/                   |             |
|    fps                  | 759         |
|    iterations           | 94          |
|    time_elapsed         | 2027        |
|    total_timesteps      | 1540096     |
| train/                  |             |
|    approx_kl            | 0.005911725 |
|    clip_fraction        | 0.0583      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.676      |
|    explained_variance   | 0.989       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08        |
|    n_updates            | 372         |
|    policy_gradient_loss | 0.00156     |
|    value_loss           | 11.1        |
-----------------------------------------

Eval num_timesteps=1550000, episode_reward=277.94 +/- 25.58

Episode length: 255.30 +/- 16.38

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 255         |
|    mean_reward          | 278         |
| time/                   |             |
|    total_timesteps      | 1550000     |
| train/                  |             |
|    approx_kl            | 0.005223712 |
|    clip_fraction        | 0.0543      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.672      |
|    explained_variance   | 0.99        |
|    learning_rate        | 0.0003      |
|    loss                 | 4.44        |
|    n_updates            | 376         |
|    policy_gradient_loss | 0.000842    |
|    value_loss           | 10.4        |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 272      |
|    ep_rew_mean     | 274      |
| time/              |          |
|    fps             | 761      |
|    iterations      | 95       |
|    time_elapsed    | 2043     |
|    total_timesteps | 1556480  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 248         |
|    ep_rew_mean          | 277         |
| time/                   |             |
|    fps                  | 764         |
|    iterations           | 96          |
|    time_elapsed         | 2056        |
|    total_timesteps      | 1572864     |
| train/                  |             |
|    approx_kl            | 0.005931864 |
|    clip_fraction        | 0.0743      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.664      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.1         |
|    n_updates            | 380         |
|    policy_gradient_loss | 0.000301    |
|    value_loss           | 2.27        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 251          |
|    ep_rew_mean          | 273          |
| time/                   |              |
|    fps                  | 768          |
|    iterations           | 97           |
|    time_elapsed         | 2068         |
|    total_timesteps      | 1589248      |
| train/                  |              |
|    approx_kl            | 0.0057362877 |
|    clip_fraction        | 0.0658       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.665       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.75         |
|    n_updates            | 384          |
|    policy_gradient_loss | 0.000759     |
|    value_loss           | 39.1         |
------------------------------------------

Eval num_timesteps=1600000, episode_reward=284.22 +/- 17.01

Episode length: 246.45 +/- 12.18

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 246         |
|    mean_reward          | 284         |
| time/                   |             |
|    total_timesteps      | 1600000     |
| train/                  |             |
|    approx_kl            | 0.005802314 |
|    clip_fraction        | 0.0693      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.667      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 97.3        |
|    n_updates            | 388         |
|    policy_gradient_loss | 0.000255    |
|    value_loss           | 70.7        |
-----------------------------------------

New best mean reward!

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 247      |
|    ep_rew_mean     | 271      |
| time/              |          |
|    fps             | 770      |
|    iterations      | 98       |
|    time_elapsed    | 2084     |
|    total_timesteps | 1605632  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 251          |
|    ep_rew_mean          | 274          |
| time/                   |              |
|    fps                  | 773          |
|    iterations           | 99           |
|    time_elapsed         | 2096         |
|    total_timesteps      | 1622016      |
| train/                  |              |
|    approx_kl            | 0.0058964733 |
|    clip_fraction        | 0.0461       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.611       |
|    explained_variance   | 0.952        |
|    learning_rate        | 0.0003       |
|    loss                 | 101          |
|    n_updates            | 392          |
|    policy_gradient_loss | 0.000874     |
|    value_loss           | 70.9         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 248         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 777         |
|    iterations           | 100         |
|    time_elapsed         | 2108        |
|    total_timesteps      | 1638400     |
| train/                  |             |
|    approx_kl            | 0.005856948 |
|    clip_fraction        | 0.0805      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.645      |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | 6.2         |
|    n_updates            | 396         |
|    policy_gradient_loss | 0.00208     |
|    value_loss           | 6.21        |
-----------------------------------------

Eval num_timesteps=1650000, episode_reward=277.11 +/- 17.28

Episode length: 241.65 +/- 13.05

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 242          |
|    mean_reward          | 277          |
| time/                   |              |
|    total_timesteps      | 1650000      |
| train/                  |              |
|    approx_kl            | 0.0042968113 |
|    clip_fraction        | 0.0501       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.641       |
|    explained_variance   | 0.958        |
|    learning_rate        | 0.0003       |
|    loss                 | 13.2         |
|    n_updates            | 400          |
|    policy_gradient_loss | 0.00102      |
|    value_loss           | 81.2         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 241      |
|    ep_rew_mean     | 274      |
| time/              |          |
|    fps             | 779      |
|    iterations      | 101      |
|    time_elapsed    | 2123     |
|    total_timesteps | 1654784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 240          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 782          |
|    iterations           | 102          |
|    time_elapsed         | 2135         |
|    total_timesteps      | 1671168      |
| train/                  |              |
|    approx_kl            | 0.0070830034 |
|    clip_fraction        | 0.0818       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.639       |
|    explained_variance   | 0.982        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.22         |
|    n_updates            | 404          |
|    policy_gradient_loss | 0.000837     |
|    value_loss           | 13.4         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 240         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 785         |
|    iterations           | 103         |
|    time_elapsed         | 2148        |
|    total_timesteps      | 1687552     |
| train/                  |             |
|    approx_kl            | 0.005467222 |
|    clip_fraction        | 0.0648      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.647      |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.2         |
|    n_updates            | 408         |
|    policy_gradient_loss | 0.00147     |
|    value_loss           | 3.25        |
-----------------------------------------

Eval num_timesteps=1700000, episode_reward=272.90 +/- 21.07

Episode length: 239.60 +/- 13.31

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 240         |
|    mean_reward          | 273         |
| time/                   |             |
|    total_timesteps      | 1700000     |
| train/                  |             |
|    approx_kl            | 0.003532527 |
|    clip_fraction        | 0.0412      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.619      |
|    explained_variance   | 0.991       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.2         |
|    n_updates            | 412         |
|    policy_gradient_loss | 0.00179     |
|    value_loss           | 17.6        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 260      |
|    ep_rew_mean     | 274      |
| time/              |          |
|    fps             | 787      |
|    iterations      | 104      |
|    time_elapsed    | 2164     |
|    total_timesteps | 1703936  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 255         |
|    ep_rew_mean          | 271         |
| time/                   |             |
|    fps                  | 790         |
|    iterations           | 105         |
|    time_elapsed         | 2177        |
|    total_timesteps      | 1720320     |
| train/                  |             |
|    approx_kl            | 0.006158259 |
|    clip_fraction        | 0.0555      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.647      |
|    explained_variance   | 0.993       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.27        |
|    n_updates            | 416         |
|    policy_gradient_loss | 0.00164     |
|    value_loss           | 8.77        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 258          |
|    ep_rew_mean          | 270          |
| time/                   |              |
|    fps                  | 792          |
|    iterations           | 106          |
|    time_elapsed         | 2190         |
|    total_timesteps      | 1736704      |
| train/                  |              |
|    approx_kl            | 0.0042898236 |
|    clip_fraction        | 0.0333       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.642       |
|    explained_variance   | 0.948        |
|    learning_rate        | 0.0003       |
|    loss                 | 18.1         |
|    n_updates            | 420          |
|    policy_gradient_loss | -0.000163    |
|    value_loss           | 91.1         |
------------------------------------------

Eval num_timesteps=1750000, episode_reward=273.83 +/- 23.78

Episode length: 246.90 +/- 14.32

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 247          |
|    mean_reward          | 274          |
| time/                   |              |
|    total_timesteps      | 1750000      |
| train/                  |              |
|    approx_kl            | 0.0065874527 |
|    clip_fraction        | 0.0739       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.623       |
|    explained_variance   | 0.988        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.06         |
|    n_updates            | 424          |
|    policy_gradient_loss | 0.00156      |
|    value_loss           | 15.2         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 249      |
|    ep_rew_mean     | 273      |
| time/              |          |
|    fps             | 794      |
|    iterations      | 107      |
|    time_elapsed    | 2205     |
|    total_timesteps | 1753088  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 252         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 797         |
|    iterations           | 108         |
|    time_elapsed         | 2218        |
|    total_timesteps      | 1769472     |
| train/                  |             |
|    approx_kl            | 0.005448927 |
|    clip_fraction        | 0.0587      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.646      |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | 171         |
|    n_updates            | 428         |
|    policy_gradient_loss | 0.00178     |
|    value_loss           | 34.7        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 255          |
|    ep_rew_mean          | 263          |
| time/                   |              |
|    fps                  | 800          |
|    iterations           | 109          |
|    time_elapsed         | 2231         |
|    total_timesteps      | 1785856      |
| train/                  |              |
|    approx_kl            | 0.0045086886 |
|    clip_fraction        | 0.0565       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.624       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.729        |
|    n_updates            | 432          |
|    policy_gradient_loss | 0.00119      |
|    value_loss           | 3.95         |
------------------------------------------

Eval num_timesteps=1800000, episode_reward=278.32 +/- 13.46

Episode length: 237.30 +/- 13.74

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 237          |
|    mean_reward          | 278          |
| time/                   |              |
|    total_timesteps      | 1800000      |
| train/                  |              |
|    approx_kl            | 0.0042736847 |
|    clip_fraction        | 0.0367       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.629       |
|    explained_variance   | 0.9          |
|    learning_rate        | 0.0003       |
|    loss                 | 37.2         |
|    n_updates            | 436          |
|    policy_gradient_loss | 0.000687     |
|    value_loss           | 164          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 245      |
|    ep_rew_mean     | 273      |
| time/              |          |
|    fps             | 802      |
|    iterations      | 110      |
|    time_elapsed    | 2246     |
|    total_timesteps | 1802240  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 237          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 805          |
|    iterations           | 111          |
|    time_elapsed         | 2259         |
|    total_timesteps      | 1818624      |
| train/                  |              |
|    approx_kl            | 0.0059137098 |
|    clip_fraction        | 0.0758       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.644       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.973        |
|    n_updates            | 440          |
|    policy_gradient_loss | 0.00214      |
|    value_loss           | 22.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 252          |
|    ep_rew_mean          | 276          |
| time/                   |              |
|    fps                  | 807          |
|    iterations           | 112          |
|    time_elapsed         | 2271         |
|    total_timesteps      | 1835008      |
| train/                  |              |
|    approx_kl            | 0.0070742583 |
|    clip_fraction        | 0.0717       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.625       |
|    explained_variance   | 0.996        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.91         |
|    n_updates            | 444          |
|    policy_gradient_loss | 0.00161      |
|    value_loss           | 4.24         |
------------------------------------------

Eval num_timesteps=1850000, episode_reward=285.40 +/- 25.25

Episode length: 237.55 +/- 15.65

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 238         |
|    mean_reward          | 285         |
| time/                   |             |
|    total_timesteps      | 1850000     |
| train/                  |             |
|    approx_kl            | 0.004261004 |
|    clip_fraction        | 0.057       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.641      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.675       |
|    n_updates            | 448         |
|    policy_gradient_loss | 5.47e-05    |
|    value_loss           | 1.95        |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 241      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 809      |
|    iterations      | 113      |
|    time_elapsed    | 2287     |
|    total_timesteps | 1851392  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 232          |
|    ep_rew_mean          | 263          |
| time/                   |              |
|    fps                  | 812          |
|    iterations           | 114          |
|    time_elapsed         | 2298         |
|    total_timesteps      | 1867776      |
| train/                  |              |
|    approx_kl            | 0.0041183094 |
|    clip_fraction        | 0.051        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.614       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.81         |
|    n_updates            | 452          |
|    policy_gradient_loss | 0.00121      |
|    value_loss           | 2.74         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 232          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 815          |
|    iterations           | 115          |
|    time_elapsed         | 2310         |
|    total_timesteps      | 1884160      |
| train/                  |              |
|    approx_kl            | 0.0024801544 |
|    clip_fraction        | 0.0149       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.612       |
|    explained_variance   | 0.887        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.25         |
|    n_updates            | 456          |
|    policy_gradient_loss | 0.000458     |
|    value_loss           | 193          |
------------------------------------------

Eval num_timesteps=1900000, episode_reward=280.28 +/- 23.54

Episode length: 229.45 +/- 12.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 229          |
|    mean_reward          | 280          |
| time/                   |              |
|    total_timesteps      | 1900000      |
| train/                  |              |
|    approx_kl            | 0.0046991003 |
|    clip_fraction        | 0.0494       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.602       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 4.3          |
|    n_updates            | 460          |
|    policy_gradient_loss | 0.00126      |
|    value_loss           | 34.9         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_1900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 234      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 817      |
|    iterations      | 116      |
|    time_elapsed    | 2325     |
|    total_timesteps | 1900544  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 233          |
|    ep_rew_mean          | 276          |
| time/                   |              |
|    fps                  | 820          |
|    iterations           | 117          |
|    time_elapsed         | 2337         |
|    total_timesteps      | 1916928      |
| train/                  |              |
|    approx_kl            | 0.0047633164 |
|    clip_fraction        | 0.0581       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.621       |
|    explained_variance   | 0.982        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.75         |
|    n_updates            | 464          |
|    policy_gradient_loss | 0.00148      |
|    value_loss           | 34.1         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 231         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 822         |
|    iterations           | 118         |
|    time_elapsed         | 2349        |
|    total_timesteps      | 1933312     |
| train/                  |             |
|    approx_kl            | 0.005473803 |
|    clip_fraction        | 0.0545      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.612      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.03        |
|    n_updates            | 468         |
|    policy_gradient_loss | 0.00204     |
|    value_loss           | 77.8        |
-----------------------------------------

Eval num_timesteps=1950000, episode_reward=275.94 +/- 22.00

Episode length: 241.80 +/- 12.63

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 242          |
|    mean_reward          | 276          |
| time/                   |              |
|    total_timesteps      | 1950000      |
| train/                  |              |
|    approx_kl            | 0.0057230107 |
|    clip_fraction        | 0.0667       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.631       |
|    explained_variance   | 0.995        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.25         |
|    n_updates            | 476          |
|    policy_gradient_loss | 0.00142      |
|    value_loss           | 8.83         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 233      |
|    ep_rew_mean     | 271      |
| time/              |          |
|    fps             | 827      |
|    iterations      | 120      |
|    time_elapsed    | 2376     |
|    total_timesteps | 1966080  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 242          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 829          |
|    iterations           | 121          |
|    time_elapsed         | 2388         |
|    total_timesteps      | 1982464      |
| train/                  |              |
|    approx_kl            | 0.0035545507 |
|    clip_fraction        | 0.034        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.637       |
|    explained_variance   | 0.931        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.28         |
|    n_updates            | 480          |
|    policy_gradient_loss | 0.0012       |
|    value_loss           | 143          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 238         |
|    ep_rew_mean          | 276         |
| time/                   |             |
|    fps                  | 832         |
|    iterations           | 122         |
|    time_elapsed         | 2401        |
|    total_timesteps      | 1998848     |
| train/                  |             |
|    approx_kl            | 0.004898633 |
|    clip_fraction        | 0.0544      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.636      |
|    explained_variance   | 0.987       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.72        |
|    n_updates            | 484         |
|    policy_gradient_loss | 0.00143     |
|    value_loss           | 29          |
-----------------------------------------

Eval num_timesteps=2000000, episode_reward=276.92 +/- 20.61

Episode length: 238.60 +/- 12.24

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 239          |
|    mean_reward          | 277          |
| time/                   |              |
|    total_timesteps      | 2000000      |
| train/                  |              |
|    approx_kl            | 0.0060234647 |
|    clip_fraction        | 0.0762       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.643       |
|    explained_variance   | 0.995        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.531        |
|    n_updates            | 488          |
|    policy_gradient_loss | 0.00224      |
|    value_loss           | 5.52         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2000000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 229      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 834      |
|    iterations      | 123      |
|    time_elapsed    | 2416     |
|    total_timesteps | 2015232  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 233          |
|    ep_rew_mean          | 275          |
| time/                   |              |
|    fps                  | 836          |
|    iterations           | 124          |
|    time_elapsed         | 2427         |
|    total_timesteps      | 2031616      |
| train/                  |              |
|    approx_kl            | 0.0031651147 |
|    clip_fraction        | 0.0418       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.637       |
|    explained_variance   | 0.984        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.28         |
|    n_updates            | 492          |
|    policy_gradient_loss | 0.0014       |
|    value_loss           | 17.7         |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 231        |
|    ep_rew_mean          | 272        |
| time/                   |            |
|    fps                  | 839        |
|    iterations           | 125        |
|    time_elapsed         | 2439       |
|    total_timesteps      | 2048000    |
| train/                  |            |
|    approx_kl            | 0.00611628 |
|    clip_fraction        | 0.0661     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.654     |
|    explained_variance   | 0.968      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.69       |
|    n_updates            | 496        |
|    policy_gradient_loss | 0.000427   |
|    value_loss           | 90.8       |
----------------------------------------

Eval num_timesteps=2050000, episode_reward=278.76 +/- 22.13

Episode length: 229.40 +/- 12.68

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 229          |
|    mean_reward          | 279          |
| time/                   |              |
|    total_timesteps      | 2050000      |
| train/                  |              |
|    approx_kl            | 0.0057021896 |
|    clip_fraction        | 0.0631       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.64        |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.13         |
|    n_updates            | 500          |
|    policy_gradient_loss | 0.000464     |
|    value_loss           | 111          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 232      |
|    ep_rew_mean     | 277      |
| time/              |          |
|    fps             | 841      |
|    iterations      | 126      |
|    time_elapsed    | 2454     |
|    total_timesteps | 2064384  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 232          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 843          |
|    iterations           | 127          |
|    time_elapsed         | 2466         |
|    total_timesteps      | 2080768      |
| train/                  |              |
|    approx_kl            | 0.0069868583 |
|    clip_fraction        | 0.0452       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.637       |
|    explained_variance   | 0.962        |
|    learning_rate        | 0.0003       |
|    loss                 | 9.06         |
|    n_updates            | 504          |
|    policy_gradient_loss | 0.002        |
|    value_loss           | 90.5         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 236         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 846         |
|    iterations           | 128         |
|    time_elapsed         | 2478        |
|    total_timesteps      | 2097152     |
| train/                  |             |
|    approx_kl            | 0.004044351 |
|    clip_fraction        | 0.0616      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.621      |
|    explained_variance   | 0.994       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.73        |
|    n_updates            | 508         |
|    policy_gradient_loss | 0.00105     |
|    value_loss           | 7.14        |
-----------------------------------------

Eval num_timesteps=2100000, episode_reward=280.29 +/- 25.59

Episode length: 235.55 +/- 12.56

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 236         |
|    mean_reward          | 280         |
| time/                   |             |
|    total_timesteps      | 2100000     |
| train/                  |             |
|    approx_kl            | 0.004657459 |
|    clip_fraction        | 0.0521      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.64       |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.24        |
|    n_updates            | 512         |
|    policy_gradient_loss | 0.00153     |
|    value_loss           | 6.02        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 247      |
|    ep_rew_mean     | 270      |
| time/              |          |
|    fps             | 847      |
|    iterations      | 129      |
|    time_elapsed    | 2494     |
|    total_timesteps | 2113536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 236          |
|    ep_rew_mean          | 278          |
| time/                   |              |
|    fps                  | 849          |
|    iterations           | 130          |
|    time_elapsed         | 2505         |
|    total_timesteps      | 2129920      |
| train/                  |              |
|    approx_kl            | 0.0061131306 |
|    clip_fraction        | 0.0625       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.653       |
|    explained_variance   | 0.942        |
|    learning_rate        | 0.0003       |
|    loss                 | 64.9         |
|    n_updates            | 516          |
|    policy_gradient_loss | -9.02e-06    |
|    value_loss           | 164          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 227          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 852          |
|    iterations           | 131          |
|    time_elapsed         | 2517         |
|    total_timesteps      | 2146304      |
| train/                  |              |
|    approx_kl            | 0.0074242074 |
|    clip_fraction        | 0.0619       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.608       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 7.53         |
|    n_updates            | 520          |
|    policy_gradient_loss | 0.000713     |
|    value_loss           | 37           |
------------------------------------------

Eval num_timesteps=2150000, episode_reward=276.32 +/- 22.93

Episode length: 234.40 +/- 13.73

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 234          |
|    mean_reward          | 276          |
| time/                   |              |
|    total_timesteps      | 2150000      |
| train/                  |              |
|    approx_kl            | 0.0044531636 |
|    clip_fraction        | 0.049        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.619       |
|    explained_variance   | 0.963        |
|    learning_rate        | 0.0003       |
|    loss                 | 80.4         |
|    n_updates            | 524          |
|    policy_gradient_loss | 0.00115      |
|    value_loss           | 95.8         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 229      |
|    ep_rew_mean     | 276      |
| time/              |          |
|    fps             | 853      |
|    iterations      | 132      |
|    time_elapsed    | 2532     |
|    total_timesteps | 2162688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 274         |
| time/                   |             |
|    fps                  | 856         |
|    iterations           | 133         |
|    time_elapsed         | 2544        |
|    total_timesteps      | 2179072     |
| train/                  |             |
|    approx_kl            | 0.004733675 |
|    clip_fraction        | 0.0504      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.636      |
|    explained_variance   | 0.958       |
|    learning_rate        | 0.0003      |
|    loss                 | 271         |
|    n_updates            | 528         |
|    policy_gradient_loss | 0.00171     |
|    value_loss           | 96.7        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 228          |
|    ep_rew_mean          | 276          |
| time/                   |              |
|    fps                  | 859          |
|    iterations           | 134          |
|    time_elapsed         | 2555         |
|    total_timesteps      | 2195456      |
| train/                  |              |
|    approx_kl            | 0.0050388426 |
|    clip_fraction        | 0.0678       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.613       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 34.4         |
|    n_updates            | 532          |
|    policy_gradient_loss | 0.0015       |
|    value_loss           | 49.2         |
------------------------------------------

Eval num_timesteps=2200000, episode_reward=276.54 +/- 21.19

Episode length: 249.35 +/- 73.76

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 249          |
|    mean_reward          | 277          |
| time/                   |              |
|    total_timesteps      | 2200000      |
| train/                  |              |
|    approx_kl            | 0.0036362777 |
|    clip_fraction        | 0.0424       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.615       |
|    explained_variance   | 0.955        |
|    learning_rate        | 0.0003       |
|    loss                 | 9.62         |
|    n_updates            | 536          |
|    policy_gradient_loss | 0.00045      |
|    value_loss           | 100          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 223      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 860      |
|    iterations      | 135      |
|    time_elapsed    | 2570     |
|    total_timesteps | 2211840  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 224         |
|    ep_rew_mean          | 281         |
| time/                   |             |
|    fps                  | 862         |
|    iterations           | 136         |
|    time_elapsed         | 2582        |
|    total_timesteps      | 2228224     |
| train/                  |             |
|    approx_kl            | 0.004547866 |
|    clip_fraction        | 0.0721      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.634      |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.918       |
|    n_updates            | 540         |
|    policy_gradient_loss | 0.00219     |
|    value_loss           | 3.35        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 236          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 865          |
|    iterations           | 137          |
|    time_elapsed         | 2594         |
|    total_timesteps      | 2244608      |
| train/                  |              |
|    approx_kl            | 0.0074026096 |
|    clip_fraction        | 0.0628       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.634       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 6.29         |
|    n_updates            | 544          |
|    policy_gradient_loss | 0.000934     |
|    value_loss           | 7.4          |
------------------------------------------

Eval num_timesteps=2250000, episode_reward=275.73 +/- 14.63

Episode length: 237.70 +/- 14.09

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 238         |
|    mean_reward          | 276         |
| time/                   |             |
|    total_timesteps      | 2250000     |
| train/                  |             |
|    approx_kl            | 0.004334989 |
|    clip_fraction        | 0.0656      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.636      |
|    explained_variance   | 0.992       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.18        |
|    n_updates            | 548         |
|    policy_gradient_loss | 0.000678    |
|    value_loss           | 7.96        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 229      |
|    ep_rew_mean     | 283      |
| time/              |          |
|    fps             | 866      |
|    iterations      | 138      |
|    time_elapsed    | 2609     |
|    total_timesteps | 2260992  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 233          |
|    ep_rew_mean          | 272          |
| time/                   |              |
|    fps                  | 868          |
|    iterations           | 139          |
|    time_elapsed         | 2621         |
|    total_timesteps      | 2277376      |
| train/                  |              |
|    approx_kl            | 0.0059329215 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.607       |
|    explained_variance   | 0.983        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.23         |
|    n_updates            | 552          |
|    policy_gradient_loss | 0.000857     |
|    value_loss           | 55.8         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 230         |
|    ep_rew_mean          | 278         |
| time/                   |             |
|    fps                  | 870         |
|    iterations           | 140         |
|    time_elapsed         | 2633        |
|    total_timesteps      | 2293760     |
| train/                  |             |
|    approx_kl            | 0.004745719 |
|    clip_fraction        | 0.029       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.596      |
|    explained_variance   | 0.912       |
|    learning_rate        | 0.0003      |
|    loss                 | 177         |
|    n_updates            | 556         |
|    policy_gradient_loss | -0.00212    |
|    value_loss           | 295         |
-----------------------------------------

Eval num_timesteps=2300000, episode_reward=284.02 +/- 18.45

Episode length: 238.90 +/- 14.83

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 239        |
|    mean_reward          | 284        |
| time/                   |            |
|    total_timesteps      | 2300000    |
| train/                  |            |
|    approx_kl            | 0.00925235 |
|    clip_fraction        | 0.066      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.626     |
|    explained_variance   | 0.962      |
|    learning_rate        | 0.0003     |
|    loss                 | 9.17       |
|    n_updates            | 560        |
|    policy_gradient_loss | 0.00163    |
|    value_loss           | 50         |
----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 243      |
|    ep_rew_mean     | 276      |
| time/              |          |
|    fps             | 872      |
|    iterations      | 141      |
|    time_elapsed    | 2649     |
|    total_timesteps | 2310144  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 228        |
|    ep_rew_mean          | 277        |
| time/                   |            |
|    fps                  | 874        |
|    iterations           | 142        |
|    time_elapsed         | 2660       |
|    total_timesteps      | 2326528    |
| train/                  |            |
|    approx_kl            | 0.00590239 |
|    clip_fraction        | 0.0681     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.623     |
|    explained_variance   | 0.966      |
|    learning_rate        | 0.0003     |
|    loss                 | 9.64       |
|    n_updates            | 564        |
|    policy_gradient_loss | -0.000301  |
|    value_loss           | 64         |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 237          |
|    ep_rew_mean          | 275          |
| time/                   |              |
|    fps                  | 876          |
|    iterations           | 143          |
|    time_elapsed         | 2672         |
|    total_timesteps      | 2342912      |
| train/                  |              |
|    approx_kl            | 0.0045674033 |
|    clip_fraction        | 0.0425       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.625       |
|    explained_variance   | 0.948        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.3          |
|    n_updates            | 568          |
|    policy_gradient_loss | 0.000522     |
|    value_loss           | 98.8         |
------------------------------------------

Eval num_timesteps=2350000, episode_reward=277.41 +/- 18.86

Episode length: 233.55 +/- 17.08

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 234          |
|    mean_reward          | 277          |
| time/                   |              |
|    total_timesteps      | 2350000      |
| train/                  |              |
|    approx_kl            | 0.0049103657 |
|    clip_fraction        | 0.0476       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.581       |
|    explained_variance   | 0.939        |
|    learning_rate        | 0.0003       |
|    loss                 | 6.44         |
|    n_updates            | 572          |
|    policy_gradient_loss | 0.000498     |
|    value_loss           | 150          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 241      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 877      |
|    iterations      | 144      |
|    time_elapsed    | 2688     |
|    total_timesteps | 2359296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 238          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 879          |
|    iterations           | 145          |
|    time_elapsed         | 2699         |
|    total_timesteps      | 2375680      |
| train/                  |              |
|    approx_kl            | 0.0051495256 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.611       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 8.04         |
|    n_updates            | 576          |
|    policy_gradient_loss | 0.00157      |
|    value_loss           | 52.9         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 278         |
| time/                   |             |
|    fps                  | 882         |
|    iterations           | 146         |
|    time_elapsed         | 2710        |
|    total_timesteps      | 2392064     |
| train/                  |             |
|    approx_kl            | 0.005385575 |
|    clip_fraction        | 0.0608      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.579      |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | 12.7        |
|    n_updates            | 580         |
|    policy_gradient_loss | 0.00114     |
|    value_loss           | 138         |
-----------------------------------------

Eval num_timesteps=2400000, episode_reward=279.13 +/- 20.82

Episode length: 231.25 +/- 13.01

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 231          |
|    mean_reward          | 279          |
| time/                   |              |
|    total_timesteps      | 2400000      |
| train/                  |              |
|    approx_kl            | 0.0065820375 |
|    clip_fraction        | 0.0925       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.639       |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 194          |
|    n_updates            | 584          |
|    policy_gradient_loss | 0.000713     |
|    value_loss           | 66.3         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 238      |
|    ep_rew_mean     | 272      |
| time/              |          |
|    fps             | 883      |
|    iterations      | 147      |
|    time_elapsed    | 2727     |
|    total_timesteps | 2408448  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 265         |
| time/                   |             |
|    fps                  | 885         |
|    iterations           | 148         |
|    time_elapsed         | 2737        |
|    total_timesteps      | 2424832     |
| train/                  |             |
|    approx_kl            | 0.004397624 |
|    clip_fraction        | 0.0437      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.61       |
|    explained_variance   | 0.928       |
|    learning_rate        | 0.0003      |
|    loss                 | 60.7        |
|    n_updates            | 588         |
|    policy_gradient_loss | -0.000325   |
|    value_loss           | 206         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 231          |
|    ep_rew_mean          | 272          |
| time/                   |              |
|    fps                  | 887          |
|    iterations           | 149          |
|    time_elapsed         | 2750         |
|    total_timesteps      | 2441216      |
| train/                  |              |
|    approx_kl            | 0.0056502754 |
|    clip_fraction        | 0.0592       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.61        |
|    explained_variance   | 0.92         |
|    learning_rate        | 0.0003       |
|    loss                 | 11           |
|    n_updates            | 592          |
|    policy_gradient_loss | -0.00164     |
|    value_loss           | 232          |
------------------------------------------

Eval num_timesteps=2450000, episode_reward=272.37 +/- 57.31

Episode length: 218.40 +/- 21.84

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 218         |
|    mean_reward          | 272         |
| time/                   |             |
|    total_timesteps      | 2450000     |
| train/                  |             |
|    approx_kl            | 0.007678683 |
|    clip_fraction        | 0.0914      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.632      |
|    explained_variance   | 0.987       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.34        |
|    n_updates            | 596         |
|    policy_gradient_loss | 0.0016      |
|    value_loss           | 14.2        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 249      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 888      |
|    iterations      | 150      |
|    time_elapsed    | 2765     |
|    total_timesteps | 2457600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 227          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 891          |
|    iterations           | 151          |
|    time_elapsed         | 2776         |
|    total_timesteps      | 2473984      |
| train/                  |              |
|    approx_kl            | 0.0049112844 |
|    clip_fraction        | 0.0614       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.571       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.11         |
|    n_updates            | 600          |
|    policy_gradient_loss | 0.00161      |
|    value_loss           | 4.32         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 223          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 893          |
|    iterations           | 152          |
|    time_elapsed         | 2787         |
|    total_timesteps      | 2490368      |
| train/                  |              |
|    approx_kl            | 0.0040093767 |
|    clip_fraction        | 0.0379       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.57        |
|    explained_variance   | 0.988        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.08         |
|    n_updates            | 604          |
|    policy_gradient_loss | -0.000286    |
|    value_loss           | 13.2         |
------------------------------------------

Eval num_timesteps=2500000, episode_reward=266.62 +/- 59.69

Episode length: 223.70 +/- 19.83

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 224        |
|    mean_reward          | 267        |
| time/                   |            |
|    total_timesteps      | 2500000    |
| train/                  |            |
|    approx_kl            | 0.00483327 |
|    clip_fraction        | 0.0663     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.581     |
|    explained_variance   | 0.998      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.14       |
|    n_updates            | 608        |
|    policy_gradient_loss | 0.00114    |
|    value_loss           | 3.84       |
----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 223      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 894      |
|    iterations      | 153      |
|    time_elapsed    | 2803     |
|    total_timesteps | 2506752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 250          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 895          |
|    iterations           | 154          |
|    time_elapsed         | 2817         |
|    total_timesteps      | 2523136      |
| train/                  |              |
|    approx_kl            | 0.0046740826 |
|    clip_fraction        | 0.0539       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.566       |
|    explained_variance   | 0.986        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.66         |
|    n_updates            | 612          |
|    policy_gradient_loss | -0.000307    |
|    value_loss           | 27           |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 243         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 897         |
|    iterations           | 155         |
|    time_elapsed         | 2828        |
|    total_timesteps      | 2539520     |
| train/                  |             |
|    approx_kl            | 0.005491985 |
|    clip_fraction        | 0.0517      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.62       |
|    explained_variance   | 0.984       |
|    learning_rate        | 0.0003      |
|    loss                 | 7.93        |
|    n_updates            | 616         |
|    policy_gradient_loss | 0.000532    |
|    value_loss           | 31.2        |
-----------------------------------------

Eval num_timesteps=2550000, episode_reward=283.08 +/- 20.34

Episode length: 223.95 +/- 10.92

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 224         |
|    mean_reward          | 283         |
| time/                   |             |
|    total_timesteps      | 2550000     |
| train/                  |             |
|    approx_kl            | 0.005381421 |
|    clip_fraction        | 0.0596      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.564      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.28        |
|    n_updates            | 620         |
|    policy_gradient_loss | 0.00106     |
|    value_loss           | 3.61        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 225      |
|    ep_rew_mean     | 272      |
| time/              |          |
|    fps             | 899      |
|    iterations      | 156      |
|    time_elapsed    | 2842     |
|    total_timesteps | 2555904  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 222          |
|    ep_rew_mean          | 276          |
| time/                   |              |
|    fps                  | 901          |
|    iterations           | 157          |
|    time_elapsed         | 2853         |
|    total_timesteps      | 2572288      |
| train/                  |              |
|    approx_kl            | 0.0022561538 |
|    clip_fraction        | 0.021        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.567       |
|    explained_variance   | 0.925        |
|    learning_rate        | 0.0003       |
|    loss                 | 81.1         |
|    n_updates            | 624          |
|    policy_gradient_loss | 1.21e-05     |
|    value_loss           | 242          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 223          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 903          |
|    iterations           | 158          |
|    time_elapsed         | 2865         |
|    total_timesteps      | 2588672      |
| train/                  |              |
|    approx_kl            | 0.0040531624 |
|    clip_fraction        | 0.0468       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.581       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 180          |
|    n_updates            | 628          |
|    policy_gradient_loss | 0.000831     |
|    value_loss           | 79.2         |
------------------------------------------

Eval num_timesteps=2600000, episode_reward=268.61 +/- 47.08

Episode length: 217.10 +/- 20.86

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 217         |
|    mean_reward          | 269         |
| time/                   |             |
|    total_timesteps      | 2600000     |
| train/                  |             |
|    approx_kl            | 0.004475444 |
|    clip_fraction        | 0.0555      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.549      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.04        |
|    n_updates            | 632         |
|    policy_gradient_loss | 0.00103     |
|    value_loss           | 122         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 221      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 904      |
|    iterations      | 159      |
|    time_elapsed    | 2879     |
|    total_timesteps | 2605056  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 224         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 906         |
|    iterations           | 160         |
|    time_elapsed         | 2890        |
|    total_timesteps      | 2621440     |
| train/                  |             |
|    approx_kl            | 0.005600294 |
|    clip_fraction        | 0.0551      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.559      |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.99        |
|    n_updates            | 636         |
|    policy_gradient_loss | 0.00149     |
|    value_loss           | 67.9        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 232         |
|    ep_rew_mean          | 273         |
| time/                   |             |
|    fps                  | 908         |
|    iterations           | 161         |
|    time_elapsed         | 2902        |
|    total_timesteps      | 2637824     |
| train/                  |             |
|    approx_kl            | 0.016296467 |
|    clip_fraction        | 0.064       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.578      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 141         |
|    n_updates            | 640         |
|    policy_gradient_loss | -0.003      |
|    value_loss           | 72.1        |
-----------------------------------------

Eval num_timesteps=2650000, episode_reward=288.09 +/- 20.31

Episode length: 218.15 +/- 12.14

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 218         |
|    mean_reward          | 288         |
| time/                   |             |
|    total_timesteps      | 2650000     |
| train/                  |             |
|    approx_kl            | 0.006666277 |
|    clip_fraction        | 0.0691      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.582      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 8.89        |
|    n_updates            | 644         |
|    policy_gradient_loss | 0.000729    |
|    value_loss           | 114         |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 239      |
|    ep_rew_mean     | 275      |
| time/              |          |
|    fps             | 909      |
|    iterations      | 162      |
|    time_elapsed    | 2918     |
|    total_timesteps | 2654208  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 283         |
| time/                   |             |
|    fps                  | 911         |
|    iterations           | 163         |
|    time_elapsed         | 2929        |
|    total_timesteps      | 2670592     |
| train/                  |             |
|    approx_kl            | 0.005004042 |
|    clip_fraction        | 0.0697      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.578      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.5         |
|    n_updates            | 648         |
|    policy_gradient_loss | -0.000323   |
|    value_loss           | 4.84        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 239          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 913          |
|    iterations           | 164          |
|    time_elapsed         | 2942         |
|    total_timesteps      | 2686976      |
| train/                  |              |
|    approx_kl            | 0.0052152565 |
|    clip_fraction        | 0.0564       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.553       |
|    explained_variance   | 0.996        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.95         |
|    n_updates            | 652          |
|    policy_gradient_loss | 0.000877     |
|    value_loss           | 6.02         |
------------------------------------------

Eval num_timesteps=2700000, episode_reward=281.97 +/- 19.89

Episode length: 222.35 +/- 14.48

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 222         |
|    mean_reward          | 282         |
| time/                   |             |
|    total_timesteps      | 2700000     |
| train/                  |             |
|    approx_kl            | 0.005169236 |
|    clip_fraction        | 0.0499      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.601      |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.91        |
|    n_updates            | 656         |
|    policy_gradient_loss | 0.00061     |
|    value_loss           | 30.7        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 240      |
|    ep_rew_mean     | 273      |
| time/              |          |
|    fps             | 914      |
|    iterations      | 165      |
|    time_elapsed    | 2957     |
|    total_timesteps | 2703360  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 238          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 915          |
|    iterations           | 166          |
|    time_elapsed         | 2969         |
|    total_timesteps      | 2719744      |
| train/                  |              |
|    approx_kl            | 0.0051740194 |
|    clip_fraction        | 0.0536       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.581       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 9.56         |
|    n_updates            | 660          |
|    policy_gradient_loss | 0.0011       |
|    value_loss           | 121          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 222         |
|    ep_rew_mean          | 282         |
| time/                   |             |
|    fps                  | 917         |
|    iterations           | 167         |
|    time_elapsed         | 2980        |
|    total_timesteps      | 2736128     |
| train/                  |             |
|    approx_kl            | 0.005735022 |
|    clip_fraction        | 0.0686      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.577      |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.14        |
|    n_updates            | 664         |
|    policy_gradient_loss | 0.00126     |
|    value_loss           | 2.86        |
-----------------------------------------

Eval num_timesteps=2750000, episode_reward=271.81 +/- 25.98

Episode length: 217.65 +/- 14.96

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 218          |
|    mean_reward          | 272          |
| time/                   |              |
|    total_timesteps      | 2750000      |
| train/                  |              |
|    approx_kl            | 0.0044531766 |
|    clip_fraction        | 0.0455       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.556       |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.14         |
|    n_updates            | 668          |
|    policy_gradient_loss | 8.71e-05     |
|    value_loss           | 60.7         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 224      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 919      |
|    iterations      | 168      |
|    time_elapsed    | 2994     |
|    total_timesteps | 2752512  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 222          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 921          |
|    iterations           | 169          |
|    time_elapsed         | 3005         |
|    total_timesteps      | 2768896      |
| train/                  |              |
|    approx_kl            | 0.0043136925 |
|    clip_fraction        | 0.0651       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.56        |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.751        |
|    n_updates            | 672          |
|    policy_gradient_loss | 0.000539     |
|    value_loss           | 2.18         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 221         |
|    ep_rew_mean          | 284         |
| time/                   |             |
|    fps                  | 923         |
|    iterations           | 170         |
|    time_elapsed         | 3017        |
|    total_timesteps      | 2785280     |
| train/                  |             |
|    approx_kl            | 0.005197647 |
|    clip_fraction        | 0.0623      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.548      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.55        |
|    n_updates            | 676         |
|    policy_gradient_loss | 0.000705    |
|    value_loss           | 2.7         |
-----------------------------------------

Eval num_timesteps=2800000, episode_reward=273.03 +/- 21.04

Episode length: 221.95 +/- 12.04

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 222          |
|    mean_reward          | 273          |
| time/                   |              |
|    total_timesteps      | 2800000      |
| train/                  |              |
|    approx_kl            | 0.0036448124 |
|    clip_fraction        | 0.0392       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.535       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.46         |
|    n_updates            | 680          |
|    policy_gradient_loss | 0.000657     |
|    value_loss           | 64.4         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 223      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 924      |
|    iterations      | 171      |
|    time_elapsed    | 3031     |
|    total_timesteps | 2801664  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 231          |
|    ep_rew_mean          | 275          |
| time/                   |              |
|    fps                  | 926          |
|    iterations           | 172          |
|    time_elapsed         | 3043         |
|    total_timesteps      | 2818048      |
| train/                  |              |
|    approx_kl            | 0.0064654374 |
|    clip_fraction        | 0.0772       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.575       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.381        |
|    n_updates            | 684          |
|    policy_gradient_loss | 0.00133      |
|    value_loss           | 1.63         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 240         |
|    ep_rew_mean          | 272         |
| time/                   |             |
|    fps                  | 928         |
|    iterations           | 173         |
|    time_elapsed         | 3054        |
|    total_timesteps      | 2834432     |
| train/                  |             |
|    approx_kl            | 0.005152127 |
|    clip_fraction        | 0.0631      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.58       |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.626       |
|    n_updates            | 688         |
|    policy_gradient_loss | -0.00074    |
|    value_loss           | 60.1        |
-----------------------------------------

Eval num_timesteps=2850000, episode_reward=279.84 +/- 20.39

Episode length: 218.75 +/- 13.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 219         |
|    mean_reward          | 280         |
| time/                   |             |
|    total_timesteps      | 2850000     |
| train/                  |             |
|    approx_kl            | 0.005712932 |
|    clip_fraction        | 0.0625      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.557      |
|    explained_variance   | 0.982       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.15        |
|    n_updates            | 692         |
|    policy_gradient_loss | 0.00227     |
|    value_loss           | 28.7        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 231      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 929      |
|    iterations      | 174      |
|    time_elapsed    | 3068     |
|    total_timesteps | 2850816  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 224          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 931          |
|    iterations           | 175          |
|    time_elapsed         | 3078         |
|    total_timesteps      | 2867200      |
| train/                  |              |
|    approx_kl            | 0.0046996134 |
|    clip_fraction        | 0.0613       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.57        |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.515        |
|    n_updates            | 696          |
|    policy_gradient_loss | 0.000257     |
|    value_loss           | 74.7         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 218          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 933          |
|    iterations           | 176          |
|    time_elapsed         | 3089         |
|    total_timesteps      | 2883584      |
| train/                  |              |
|    approx_kl            | 0.0048738457 |
|    clip_fraction        | 0.066        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.539       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.633        |
|    n_updates            | 700          |
|    policy_gradient_loss | 0.000317     |
|    value_loss           | 1.35         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 238          |
|    ep_rew_mean          | 285          |
| time/                   |              |
|    fps                  | 934          |
|    iterations           | 177          |
|    time_elapsed         | 3101         |
|    total_timesteps      | 2899968      |
| train/                  |              |
|    approx_kl            | 0.0062543666 |
|    clip_fraction        | 0.0503       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.54        |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 19.3         |
|    n_updates            | 704          |
|    policy_gradient_loss | -8.25e-06    |
|    value_loss           | 60.7         |
------------------------------------------

Eval num_timesteps=2900000, episode_reward=262.85 +/- 62.17

Episode length: 219.75 +/- 15.86

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 220        |
|    mean_reward          | 263        |
| time/                   |            |
|    total_timesteps      | 2900000    |
| train/                  |            |
|    approx_kl            | 0.00459302 |
|    clip_fraction        | 0.0594     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.589     |
|    explained_variance   | 0.993      |
|    learning_rate        | 0.0003     |
|    loss                 | 3.03       |
|    n_updates            | 708        |
|    policy_gradient_loss | 0.00131    |
|    value_loss           | 7.08       |
----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_2900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 246      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 936      |
|    iterations      | 178      |
|    time_elapsed    | 3115     |
|    total_timesteps | 2916352  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 221          |
|    ep_rew_mean          | 274          |
| time/                   |              |
|    fps                  | 937          |
|    iterations           | 179          |
|    time_elapsed         | 3126         |
|    total_timesteps      | 2932736      |
| train/                  |              |
|    approx_kl            | 0.0047625406 |
|    clip_fraction        | 0.0626       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.541       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.701        |
|    n_updates            | 712          |
|    policy_gradient_loss | 0.00152      |
|    value_loss           | 1.26         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 216          |
|    ep_rew_mean          | 272          |
| time/                   |              |
|    fps                  | 939          |
|    iterations           | 180          |
|    time_elapsed         | 3137         |
|    total_timesteps      | 2949120      |
| train/                  |              |
|    approx_kl            | 0.0022790036 |
|    clip_fraction        | 0.0263       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.531       |
|    explained_variance   | 0.93         |
|    learning_rate        | 0.0003       |
|    loss                 | 62.5         |
|    n_updates            | 716          |
|    policy_gradient_loss | -0.000128    |
|    value_loss           | 225          |
------------------------------------------

Eval num_timesteps=2950000, episode_reward=280.30 +/- 18.48

Episode length: 217.60 +/- 14.87

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 218          |
|    mean_reward          | 280          |
| time/                   |              |
|    total_timesteps      | 2950000      |
| train/                  |              |
|    approx_kl            | 0.0031927014 |
|    clip_fraction        | 0.0161       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.538       |
|    explained_variance   | 0.926        |
|    learning_rate        | 0.0003       |
|    loss                 | 15.1         |
|    n_updates            | 720          |
|    policy_gradient_loss | -9.47e-05    |
|    value_loss           | 245          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 227      |
|    ep_rew_mean     | 274      |
| time/              |          |
|    fps             | 939      |
|    iterations      | 181      |
|    time_elapsed    | 3156     |
|    total_timesteps | 2965504  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 219          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 940          |
|    iterations           | 182          |
|    time_elapsed         | 3169         |
|    total_timesteps      | 2981888      |
| train/                  |              |
|    approx_kl            | 0.0056872917 |
|    clip_fraction        | 0.0362       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.551       |
|    explained_variance   | 0.946        |
|    learning_rate        | 0.0003       |
|    loss                 | 6.21         |
|    n_updates            | 724          |
|    policy_gradient_loss | 0.00026      |
|    value_loss           | 168          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 229         |
|    ep_rew_mean          | 278         |
| time/                   |             |
|    fps                  | 942         |
|    iterations           | 183         |
|    time_elapsed         | 3182        |
|    total_timesteps      | 2998272     |
| train/                  |             |
|    approx_kl            | 0.006301406 |
|    clip_fraction        | 0.0715      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.533      |
|    explained_variance   | 0.968       |
|    learning_rate        | 0.0003      |
|    loss                 | 338         |
|    n_updates            | 728         |
|    policy_gradient_loss | 0.00189     |
|    value_loss           | 85          |
-----------------------------------------

Eval num_timesteps=3000000, episode_reward=283.25 +/- 20.48

Episode length: 218.30 +/- 14.95

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 218         |
|    mean_reward          | 283         |
| time/                   |             |
|    total_timesteps      | 3000000     |
| train/                  |             |
|    approx_kl            | 0.004006175 |
|    clip_fraction        | 0.0546      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.529      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 72          |
|    n_updates            | 732         |
|    policy_gradient_loss | 0.00183     |
|    value_loss           | 77          |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3000000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 222      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 942      |
|    iterations      | 184      |
|    time_elapsed    | 3196     |
|    total_timesteps | 3014656  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 222         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 944         |
|    iterations           | 185         |
|    time_elapsed         | 3209        |
|    total_timesteps      | 3031040     |
| train/                  |             |
|    approx_kl            | 0.005633573 |
|    clip_fraction        | 0.0729      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.531      |
|    explained_variance   | 0.982       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.739       |
|    n_updates            | 736         |
|    policy_gradient_loss | 0.00266     |
|    value_loss           | 50.8        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 221          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 946          |
|    iterations           | 186          |
|    time_elapsed         | 3220         |
|    total_timesteps      | 3047424      |
| train/                  |              |
|    approx_kl            | 0.0045971693 |
|    clip_fraction        | 0.0505       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.549       |
|    explained_variance   | 0.976        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.45         |
|    n_updates            | 740          |
|    policy_gradient_loss | 0.000915     |
|    value_loss           | 65           |
------------------------------------------

Eval num_timesteps=3050000, episode_reward=281.93 +/- 18.01

Episode length: 217.40 +/- 17.40

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 217          |
|    mean_reward          | 282          |
| time/                   |              |
|    total_timesteps      | 3050000      |
| train/                  |              |
|    approx_kl            | 0.0035115967 |
|    clip_fraction        | 0.0546       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.537       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 34.4         |
|    n_updates            | 744          |
|    policy_gradient_loss | 0.000579     |
|    value_loss           | 57.7         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 221      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 947      |
|    iterations      | 187      |
|    time_elapsed    | 3234     |
|    total_timesteps | 3063808  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 219          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 948          |
|    iterations           | 188          |
|    time_elapsed         | 3245         |
|    total_timesteps      | 3080192      |
| train/                  |              |
|    approx_kl            | 0.0056046583 |
|    clip_fraction        | 0.0668       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.522       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.89         |
|    n_updates            | 748          |
|    policy_gradient_loss | 0.00145      |
|    value_loss           | 3.64         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 233         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 950         |
|    iterations           | 189         |
|    time_elapsed         | 3258        |
|    total_timesteps      | 3096576     |
| train/                  |             |
|    approx_kl            | 0.006266188 |
|    clip_fraction        | 0.0653      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.527      |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | 3.62        |
|    n_updates            | 752         |
|    policy_gradient_loss | 0.000159    |
|    value_loss           | 32.9        |
-----------------------------------------

Eval num_timesteps=3100000, episode_reward=277.52 +/- 21.03

Episode length: 216.10 +/- 13.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 216         |
|    mean_reward          | 278         |
| time/                   |             |
|    total_timesteps      | 3100000     |
| train/                  |             |
|    approx_kl            | 0.009512026 |
|    clip_fraction        | 0.0761      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.542      |
|    explained_variance   | 0.991       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.23        |
|    n_updates            | 756         |
|    policy_gradient_loss | 0.00142     |
|    value_loss           | 18.8        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 242      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 951      |
|    iterations      | 190      |
|    time_elapsed    | 3272     |
|    total_timesteps | 3112960  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 223         |
|    ep_rew_mean          | 283         |
| time/                   |             |
|    fps                  | 952         |
|    iterations           | 191         |
|    time_elapsed         | 3284        |
|    total_timesteps      | 3129344     |
| train/                  |             |
|    approx_kl            | 0.005344499 |
|    clip_fraction        | 0.0762      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.529      |
|    explained_variance   | 0.992       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.41        |
|    n_updates            | 760         |
|    policy_gradient_loss | 0.00042     |
|    value_loss           | 10.1        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 229         |
|    ep_rew_mean          | 281         |
| time/                   |             |
|    fps                  | 953         |
|    iterations           | 192         |
|    time_elapsed         | 3298        |
|    total_timesteps      | 3145728     |
| train/                  |             |
|    approx_kl            | 0.003778843 |
|    clip_fraction        | 0.0375      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.517      |
|    explained_variance   | 0.983       |
|    learning_rate        | 0.0003      |
|    loss                 | 10.1        |
|    n_updates            | 764         |
|    policy_gradient_loss | 0.000307    |
|    value_loss           | 42.6        |
-----------------------------------------

Eval num_timesteps=3150000, episode_reward=278.10 +/- 19.03

Episode length: 217.80 +/- 13.54

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 218          |
|    mean_reward          | 278          |
| time/                   |              |
|    total_timesteps      | 3150000      |
| train/                  |              |
|    approx_kl            | 0.0057655554 |
|    clip_fraction        | 0.0776       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.532       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.756        |
|    n_updates            | 768          |
|    policy_gradient_loss | 0.00182      |
|    value_loss           | 2.57         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 227      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 953      |
|    iterations      | 193      |
|    time_elapsed    | 3316     |
|    total_timesteps | 3162112  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 229          |
|    ep_rew_mean          | 274          |
| time/                   |              |
|    fps                  | 954          |
|    iterations           | 194          |
|    time_elapsed         | 3329         |
|    total_timesteps      | 3178496      |
| train/                  |              |
|    approx_kl            | 0.0068612676 |
|    clip_fraction        | 0.0647       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.54        |
|    explained_variance   | 0.991        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.7          |
|    n_updates            | 772          |
|    policy_gradient_loss | 0.00133      |
|    value_loss           | 7.41         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 239         |
|    ep_rew_mean          | 278         |
| time/                   |             |
|    fps                  | 955         |
|    iterations           | 195         |
|    time_elapsed         | 3343        |
|    total_timesteps      | 3194880     |
| train/                  |             |
|    approx_kl            | 0.005216634 |
|    clip_fraction        | 0.0584      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.519      |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.47        |
|    n_updates            | 776         |
|    policy_gradient_loss | 0.0018      |
|    value_loss           | 5.13        |
-----------------------------------------

Eval num_timesteps=3200000, episode_reward=283.88 +/- 20.12

Episode length: 226.65 +/- 18.78

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 227         |
|    mean_reward          | 284         |
| time/                   |             |
|    total_timesteps      | 3200000     |
| train/                  |             |
|    approx_kl            | 0.004167665 |
|    clip_fraction        | 0.0518      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.546      |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.34        |
|    n_updates            | 780         |
|    policy_gradient_loss | 0.000148    |
|    value_loss           | 48.8        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 228      |
|    ep_rew_mean     | 277      |
| time/              |          |
|    fps             | 955      |
|    iterations      | 196      |
|    time_elapsed    | 3360     |
|    total_timesteps | 3211264  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 217          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 958          |
|    iterations           | 198          |
|    time_elapsed         | 3383         |
|    total_timesteps      | 3244032      |
| train/                  |              |
|    approx_kl            | 0.0043330016 |
|    clip_fraction        | 0.0381       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.504       |
|    explained_variance   | 0.958        |
|    learning_rate        | 0.0003       |
|    loss                 | 108          |
|    n_updates            | 788          |
|    policy_gradient_loss | 0.000532     |
|    value_loss           | 89           |
------------------------------------------

Eval num_timesteps=3250000, episode_reward=292.62 +/- 15.89

Episode length: 220.95 +/- 13.37

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 221          |
|    mean_reward          | 293          |
| time/                   |              |
|    total_timesteps      | 3250000      |
| train/                  |              |
|    approx_kl            | 0.0055418424 |
|    clip_fraction        | 0.0615       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.525       |
|    explained_variance   | 0.985        |
|    learning_rate        | 0.0003       |
|    loss                 | 125          |
|    n_updates            | 792          |
|    policy_gradient_loss | 0.00144      |
|    value_loss           | 43.2         |
------------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 224      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 958      |
|    iterations      | 199      |
|    time_elapsed    | 3401     |
|    total_timesteps | 3260416  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 276         |
| time/                   |             |
|    fps                  | 960         |
|    iterations           | 200         |
|    time_elapsed         | 3412        |
|    total_timesteps      | 3276800     |
| train/                  |             |
|    approx_kl            | 0.004227355 |
|    clip_fraction        | 0.0526      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.528      |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.564       |
|    n_updates            | 796         |
|    policy_gradient_loss | 0.00147     |
|    value_loss           | 6.41        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 232          |
|    ep_rew_mean          | 274          |
| time/                   |              |
|    fps                  | 961          |
|    iterations           | 201          |
|    time_elapsed         | 3423         |
|    total_timesteps      | 3293184      |
| train/                  |              |
|    approx_kl            | 0.0036194231 |
|    clip_fraction        | 0.0338       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.509       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 18           |
|    n_updates            | 800          |
|    policy_gradient_loss | 0.00155      |
|    value_loss           | 40.4         |
------------------------------------------

Eval num_timesteps=3300000, episode_reward=279.10 +/- 23.51

Episode length: 225.65 +/- 22.62

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 226         |
|    mean_reward          | 279         |
| time/                   |             |
|    total_timesteps      | 3300000     |
| train/                  |             |
|    approx_kl            | 0.005376575 |
|    clip_fraction        | 0.0391      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.516      |
|    explained_variance   | 0.982       |
|    learning_rate        | 0.0003      |
|    loss                 | 6.97        |
|    n_updates            | 804         |
|    policy_gradient_loss | -9.5e-06    |
|    value_loss           | 70.2        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 235      |
|    ep_rew_mean     | 283      |
| time/              |          |
|    fps             | 962      |
|    iterations      | 202      |
|    time_elapsed    | 3438     |
|    total_timesteps | 3309568  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 229         |
|    ep_rew_mean          | 280         |
| time/                   |             |
|    fps                  | 964         |
|    iterations           | 203         |
|    time_elapsed         | 3449        |
|    total_timesteps      | 3325952     |
| train/                  |             |
|    approx_kl            | 0.005058343 |
|    clip_fraction        | 0.0717      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.503      |
|    explained_variance   | 0.988       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.95        |
|    n_updates            | 808         |
|    policy_gradient_loss | 0.00138     |
|    value_loss           | 19.3        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 236         |
|    ep_rew_mean          | 274         |
| time/                   |             |
|    fps                  | 965         |
|    iterations           | 204         |
|    time_elapsed         | 3461        |
|    total_timesteps      | 3342336     |
| train/                  |             |
|    approx_kl            | 0.004981917 |
|    clip_fraction        | 0.0542      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.52       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | 19          |
|    n_updates            | 812         |
|    policy_gradient_loss | 0.000641    |
|    value_loss           | 79.8        |
-----------------------------------------

Eval num_timesteps=3350000, episode_reward=272.97 +/- 19.25

Episode length: 228.00 +/- 10.41

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 228         |
|    mean_reward          | 273         |
| time/                   |             |
|    total_timesteps      | 3350000     |
| train/                  |             |
|    approx_kl            | 0.005888786 |
|    clip_fraction        | 0.0709      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.51       |
|    explained_variance   | 0.998       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.73        |
|    n_updates            | 816         |
|    policy_gradient_loss | 0.00171     |
|    value_loss           | 3.1         |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 220      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 966      |
|    iterations      | 205      |
|    time_elapsed    | 3474     |
|    total_timesteps | 3358720  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 221          |
|    ep_rew_mean          | 278          |
| time/                   |              |
|    fps                  | 968          |
|    iterations           | 206          |
|    time_elapsed         | 3485         |
|    total_timesteps      | 3375104      |
| train/                  |              |
|    approx_kl            | 0.0044889646 |
|    clip_fraction        | 0.0582       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.534       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.04         |
|    n_updates            | 820          |
|    policy_gradient_loss | -5.66e-05    |
|    value_loss           | 75.7         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 225         |
|    ep_rew_mean          | 277         |
| time/                   |             |
|    fps                  | 969         |
|    iterations           | 207         |
|    time_elapsed         | 3497        |
|    total_timesteps      | 3391488     |
| train/                  |             |
|    approx_kl            | 0.004439186 |
|    clip_fraction        | 0.0407      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.531      |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.35        |
|    n_updates            | 824         |
|    policy_gradient_loss | 0.000102    |
|    value_loss           | 120         |
-----------------------------------------

Eval num_timesteps=3400000, episode_reward=265.70 +/- 55.33

Episode length: 220.00 +/- 16.68

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 220          |
|    mean_reward          | 266          |
| time/                   |              |
|    total_timesteps      | 3400000      |
| train/                  |              |
|    approx_kl            | 0.0051366175 |
|    clip_fraction        | 0.0595       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.537       |
|    explained_variance   | 0.952        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.22         |
|    n_updates            | 828          |
|    policy_gradient_loss | -0.00104     |
|    value_loss           | 143          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 227      |
|    ep_rew_mean     | 276      |
| time/              |          |
|    fps             | 970      |
|    iterations      | 208      |
|    time_elapsed    | 3511     |
|    total_timesteps | 3407872  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 229          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 971          |
|    iterations           | 209          |
|    time_elapsed         | 3523         |
|    total_timesteps      | 3424256      |
| train/                  |              |
|    approx_kl            | 0.0042533223 |
|    clip_fraction        | 0.0658       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.545       |
|    explained_variance   | 0.974        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.21         |
|    n_updates            | 832          |
|    policy_gradient_loss | 0.00244      |
|    value_loss           | 76.9         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 228         |
|    ep_rew_mean          | 281         |
| time/                   |             |
|    fps                  | 973         |
|    iterations           | 210         |
|    time_elapsed         | 3534        |
|    total_timesteps      | 3440640     |
| train/                  |             |
|    approx_kl            | 0.004459367 |
|    clip_fraction        | 0.0515      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.519      |
|    explained_variance   | 0.984       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.26        |
|    n_updates            | 836         |
|    policy_gradient_loss | 0.00209     |
|    value_loss           | 24          |
-----------------------------------------

Eval num_timesteps=3450000, episode_reward=285.12 +/- 18.42

Episode length: 219.15 +/- 11.58

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 219          |
|    mean_reward          | 285          |
| time/                   |              |
|    total_timesteps      | 3450000      |
| train/                  |              |
|    approx_kl            | 0.0052124867 |
|    clip_fraction        | 0.0645       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.537       |
|    explained_variance   | 0.992        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.732        |
|    n_updates            | 840          |
|    policy_gradient_loss | 0.00243      |
|    value_loss           | 21           |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 228      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 974      |
|    iterations      | 211      |
|    time_elapsed    | 3548     |
|    total_timesteps | 3457024  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 220        |
|    ep_rew_mean          | 284        |
| time/                   |            |
|    fps                  | 975        |
|    iterations           | 212        |
|    time_elapsed         | 3559       |
|    total_timesteps      | 3473408    |
| train/                  |            |
|    approx_kl            | 0.00431568 |
|    clip_fraction        | 0.0621     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.537     |
|    explained_variance   | 0.999      |
|    learning_rate        | 0.0003     |
|    loss                 | 0.414      |
|    n_updates            | 844        |
|    policy_gradient_loss | 0.00193    |
|    value_loss           | 1.52       |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 232          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 977          |
|    iterations           | 213          |
|    time_elapsed         | 3571         |
|    total_timesteps      | 3489792      |
| train/                  |              |
|    approx_kl            | 0.0048182765 |
|    clip_fraction        | 0.0544       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.521       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.49         |
|    n_updates            | 848          |
|    policy_gradient_loss | 0.000546     |
|    value_loss           | 2.13         |
------------------------------------------

Eval num_timesteps=3500000, episode_reward=283.78 +/- 20.65

Episode length: 222.85 +/- 15.14

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 223         |
|    mean_reward          | 284         |
| time/                   |             |
|    total_timesteps      | 3500000     |
| train/                  |             |
|    approx_kl            | 0.004435638 |
|    clip_fraction        | 0.0505      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.534      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.494       |
|    n_updates            | 852         |
|    policy_gradient_loss | -0.000192   |
|    value_loss           | 1.62        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 225      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 977      |
|    iterations      | 214      |
|    time_elapsed    | 3585     |
|    total_timesteps | 3506176  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 218          |
|    ep_rew_mean          | 275          |
| time/                   |              |
|    fps                  | 979          |
|    iterations           | 215          |
|    time_elapsed         | 3595         |
|    total_timesteps      | 3522560      |
| train/                  |              |
|    approx_kl            | 0.0051957024 |
|    clip_fraction        | 0.0629       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.541       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.625        |
|    n_updates            | 856          |
|    policy_gradient_loss | -3.15e-05    |
|    value_loss           | 1.43         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 226          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 981          |
|    iterations           | 216          |
|    time_elapsed         | 3606         |
|    total_timesteps      | 3538944      |
| train/                  |              |
|    approx_kl            | 0.0030140125 |
|    clip_fraction        | 0.0317       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.531       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 98.5         |
|    n_updates            | 860          |
|    policy_gradient_loss | 0.00128      |
|    value_loss           | 44.7         |
------------------------------------------

Eval num_timesteps=3550000, episode_reward=279.43 +/- 18.54

Episode length: 219.85 +/- 12.59

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 220          |
|    mean_reward          | 279          |
| time/                   |              |
|    total_timesteps      | 3550000      |
| train/                  |              |
|    approx_kl            | 0.0042557823 |
|    clip_fraction        | 0.0555       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.553       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.15         |
|    n_updates            | 864          |
|    policy_gradient_loss | 0.000675     |
|    value_loss           | 6.23         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 218      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 982      |
|    iterations      | 217      |
|    time_elapsed    | 3620     |
|    total_timesteps | 3555328  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 221          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 983          |
|    iterations           | 218          |
|    time_elapsed         | 3631         |
|    total_timesteps      | 3571712      |
| train/                  |              |
|    approx_kl            | 0.0043987045 |
|    clip_fraction        | 0.0531       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.546       |
|    explained_variance   | 0.981        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.979        |
|    n_updates            | 868          |
|    policy_gradient_loss | 0.0014       |
|    value_loss           | 53.8         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 221          |
|    ep_rew_mean          | 283          |
| time/                   |              |
|    fps                  | 984          |
|    iterations           | 219          |
|    time_elapsed         | 3642         |
|    total_timesteps      | 3588096      |
| train/                  |              |
|    approx_kl            | 0.0053293128 |
|    clip_fraction        | 0.0601       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.54        |
|    explained_variance   | 0.975        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.43         |
|    n_updates            | 872          |
|    policy_gradient_loss | 0.00101      |
|    value_loss           | 74.2         |
------------------------------------------

Eval num_timesteps=3600000, episode_reward=283.59 +/- 20.50

Episode length: 219.35 +/- 14.03

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 219          |
|    mean_reward          | 284          |
| time/                   |              |
|    total_timesteps      | 3600000      |
| train/                  |              |
|    approx_kl            | 0.0053394986 |
|    clip_fraction        | 0.0525       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.545       |
|    explained_variance   | 0.992        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.945        |
|    n_updates            | 876          |
|    policy_gradient_loss | 0.00171      |
|    value_loss           | 14.2         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 225      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 985      |
|    iterations      | 220      |
|    time_elapsed    | 3657     |
|    total_timesteps | 3604480  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 217         |
|    ep_rew_mean          | 282         |
| time/                   |             |
|    fps                  | 987         |
|    iterations           | 221         |
|    time_elapsed         | 3668        |
|    total_timesteps      | 3620864     |
| train/                  |             |
|    approx_kl            | 0.004657062 |
|    clip_fraction        | 0.0541      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.534      |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.6         |
|    n_updates            | 880         |
|    policy_gradient_loss | 0.00143     |
|    value_loss           | 4.62        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 221         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 988         |
|    iterations           | 222         |
|    time_elapsed         | 3679        |
|    total_timesteps      | 3637248     |
| train/                  |             |
|    approx_kl            | 0.004846965 |
|    clip_fraction        | 0.0597      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.536      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.87        |
|    n_updates            | 884         |
|    policy_gradient_loss | 0.000344    |
|    value_loss           | 1.99        |
-----------------------------------------

Eval num_timesteps=3650000, episode_reward=282.26 +/- 15.49

Episode length: 216.60 +/- 11.38

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 217          |
|    mean_reward          | 282          |
| time/                   |              |
|    total_timesteps      | 3650000      |
| train/                  |              |
|    approx_kl            | 0.0051047094 |
|    clip_fraction        | 0.0558       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.539       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.475        |
|    n_updates            | 888          |
|    policy_gradient_loss | -4.62e-05    |
|    value_loss           | 1.44         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 224      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 989      |
|    iterations      | 223      |
|    time_elapsed    | 3694     |
|    total_timesteps | 3653632  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 226         |
|    ep_rew_mean          | 280         |
| time/                   |             |
|    fps                  | 990         |
|    iterations           | 224         |
|    time_elapsed         | 3705        |
|    total_timesteps      | 3670016     |
| train/                  |             |
|    approx_kl            | 0.004546824 |
|    clip_fraction        | 0.0479      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.54       |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.667       |
|    n_updates            | 892         |
|    policy_gradient_loss | 0.000742    |
|    value_loss           | 1.33        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 223         |
|    ep_rew_mean          | 283         |
| time/                   |             |
|    fps                  | 992         |
|    iterations           | 225         |
|    time_elapsed         | 3715        |
|    total_timesteps      | 3686400     |
| train/                  |             |
|    approx_kl            | 0.004228472 |
|    clip_fraction        | 0.0535      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.532      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.456       |
|    n_updates            | 896         |
|    policy_gradient_loss | 0.000227    |
|    value_loss           | 1.59        |
-----------------------------------------

Eval num_timesteps=3700000, episode_reward=288.18 +/- 17.32

Episode length: 214.90 +/- 14.41

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 215          |
|    mean_reward          | 288          |
| time/                   |              |
|    total_timesteps      | 3700000      |
| train/                  |              |
|    approx_kl            | 0.0066595487 |
|    clip_fraction        | 0.049        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.535       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.78         |
|    n_updates            | 900          |
|    policy_gradient_loss | 0.000324     |
|    value_loss           | 2.47         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 233      |
|    ep_rew_mean     | 280      |
| time/              |          |
|    fps             | 992      |
|    iterations      | 226      |
|    time_elapsed    | 3730     |
|    total_timesteps | 3702784  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 225          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 994          |
|    iterations           | 227          |
|    time_elapsed         | 3740         |
|    total_timesteps      | 3719168      |
| train/                  |              |
|    approx_kl            | 0.0051965406 |
|    clip_fraction        | 0.0478       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.542       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.804        |
|    n_updates            | 904          |
|    policy_gradient_loss | 0.000848     |
|    value_loss           | 6.11         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 215          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 995          |
|    iterations           | 228          |
|    time_elapsed         | 3751         |
|    total_timesteps      | 3735552      |
| train/                  |              |
|    approx_kl            | 0.0051782867 |
|    clip_fraction        | 0.0602       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.507       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.952        |
|    n_updates            | 908          |
|    policy_gradient_loss | 0.00145      |
|    value_loss           | 1.37         |
------------------------------------------

Eval num_timesteps=3750000, episode_reward=283.70 +/- 22.74

Episode length: 217.55 +/- 10.38

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 218          |
|    mean_reward          | 284          |
| time/                   |              |
|    total_timesteps      | 3750000      |
| train/                  |              |
|    approx_kl            | 0.0047629196 |
|    clip_fraction        | 0.0567       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.517       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 89.2         |
|    n_updates            | 912          |
|    policy_gradient_loss | 0.000214     |
|    value_loss           | 70.5         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 218      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 996      |
|    iterations      | 229      |
|    time_elapsed    | 3765     |
|    total_timesteps | 3751936  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 225          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 997          |
|    iterations           | 230          |
|    time_elapsed         | 3777         |
|    total_timesteps      | 3768320      |
| train/                  |              |
|    approx_kl            | 0.0046917577 |
|    clip_fraction        | 0.0645       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.503       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.483        |
|    n_updates            | 916          |
|    policy_gradient_loss | 0.000352     |
|    value_loss           | 1.11         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 230          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 999          |
|    iterations           | 231          |
|    time_elapsed         | 3788         |
|    total_timesteps      | 3784704      |
| train/                  |              |
|    approx_kl            | 0.0037812917 |
|    clip_fraction        | 0.044        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.522       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.912        |
|    n_updates            | 920          |
|    policy_gradient_loss | -0.000223    |
|    value_loss           | 1.62         |
------------------------------------------

Eval num_timesteps=3800000, episode_reward=271.02 +/- 37.83

Episode length: 252.10 +/- 171.83

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 252         |
|    mean_reward          | 271         |
| time/                   |             |
|    total_timesteps      | 3800000     |
| train/                  |             |
|    approx_kl            | 0.004675319 |
|    clip_fraction        | 0.0553      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.526      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.445       |
|    n_updates            | 924         |
|    policy_gradient_loss | 2.64e-05    |
|    value_loss           | 1.34        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 220      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 999      |
|    iterations      | 232      |
|    time_elapsed    | 3802     |
|    total_timesteps | 3801088  |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 221        |
|    ep_rew_mean          | 281        |
| time/                   |            |
|    fps                  | 1000       |
|    iterations           | 233        |
|    time_elapsed         | 3813       |
|    total_timesteps      | 3817472    |
| train/                  |            |
|    approx_kl            | 0.00452415 |
|    clip_fraction        | 0.0526     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.502     |
|    explained_variance   | 0.999      |
|    learning_rate        | 0.0003     |
|    loss                 | 0.592      |
|    n_updates            | 928        |
|    policy_gradient_loss | 0.00061    |
|    value_loss           | 1.67       |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 224         |
|    ep_rew_mean          | 282         |
| time/                   |             |
|    fps                  | 1002        |
|    iterations           | 234         |
|    time_elapsed         | 3824        |
|    total_timesteps      | 3833856     |
| train/                  |             |
|    approx_kl            | 0.003762405 |
|    clip_fraction        | 0.0496      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.504      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.407       |
|    n_updates            | 932         |
|    policy_gradient_loss | 0.000519    |
|    value_loss           | 1.61        |
-----------------------------------------

Eval num_timesteps=3850000, episode_reward=267.90 +/- 54.44

Episode length: 210.35 +/- 18.93

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 210         |
|    mean_reward          | 268         |
| time/                   |             |
|    total_timesteps      | 3850000     |
| train/                  |             |
|    approx_kl            | 0.005349271 |
|    clip_fraction        | 0.0545      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.492      |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.9         |
|    n_updates            | 936         |
|    policy_gradient_loss | 0.00158     |
|    value_loss           | 22.7        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 213      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1003     |
|    iterations      | 235      |
|    time_elapsed    | 3838     |
|    total_timesteps | 3850240  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 215          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 1004         |
|    iterations           | 236          |
|    time_elapsed         | 3849         |
|    total_timesteps      | 3866624      |
| train/                  |              |
|    approx_kl            | 0.0060836487 |
|    clip_fraction        | 0.0724       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.498       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.433        |
|    n_updates            | 940          |
|    policy_gradient_loss | 0.000608     |
|    value_loss           | 1.28         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 217          |
|    ep_rew_mean          | 286          |
| time/                   |              |
|    fps                  | 1006         |
|    iterations           | 237          |
|    time_elapsed         | 3859         |
|    total_timesteps      | 3883008      |
| train/                  |              |
|    approx_kl            | 0.0044383733 |
|    clip_fraction        | 0.052        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.493       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.399        |
|    n_updates            | 944          |
|    policy_gradient_loss | 0.00178      |
|    value_loss           | 1.38         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 214          |
|    ep_rew_mean          | 283          |
| time/                   |              |
|    fps                  | 1007         |
|    iterations           | 238          |
|    time_elapsed         | 3869         |
|    total_timesteps      | 3899392      |
| train/                  |              |
|    approx_kl            | 0.0046062893 |
|    clip_fraction        | 0.0457       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.5         |
|    explained_variance   | 0.972        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.681        |
|    n_updates            | 948          |
|    policy_gradient_loss | 0.00118      |
|    value_loss           | 36.2         |
------------------------------------------

Eval num_timesteps=3900000, episode_reward=285.04 +/- 22.14

Episode length: 214.40 +/- 12.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 214         |
|    mean_reward          | 285         |
| time/                   |             |
|    total_timesteps      | 3900000     |
| train/                  |             |
|    approx_kl            | 0.003919402 |
|    clip_fraction        | 0.0367      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.487      |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.52        |
|    n_updates            | 952         |
|    policy_gradient_loss | 0.00156     |
|    value_loss           | 80.5        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_3900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 219      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 1007     |
|    iterations      | 239      |
|    time_elapsed    | 3885     |
|    total_timesteps | 3915776  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 228          |
|    ep_rew_mean          | 281          |
| time/                   |              |
|    fps                  | 1009         |
|    iterations           | 240          |
|    time_elapsed         | 3896         |
|    total_timesteps      | 3932160      |
| train/                  |              |
|    approx_kl            | 0.0054320814 |
|    clip_fraction        | 0.0549       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.498       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.896        |
|    n_updates            | 956          |
|    policy_gradient_loss | 0.00133      |
|    value_loss           | 3.3          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 225          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 1010         |
|    iterations           | 241          |
|    time_elapsed         | 3907         |
|    total_timesteps      | 3948544      |
| train/                  |              |
|    approx_kl            | 0.0055007627 |
|    clip_fraction        | 0.0591       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.515       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.87         |
|    n_updates            | 960          |
|    policy_gradient_loss | 0.000967     |
|    value_loss           | 1.6          |
------------------------------------------

Eval num_timesteps=3950000, episode_reward=281.42 +/- 21.76

Episode length: 216.45 +/- 12.48

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 216          |
|    mean_reward          | 281          |
| time/                   |              |
|    total_timesteps      | 3950000      |
| train/                  |              |
|    approx_kl            | 0.0042960336 |
|    clip_fraction        | 0.058        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.503       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.71         |
|    n_updates            | 964          |
|    policy_gradient_loss | 0.00141      |
|    value_loss           | 3.18         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 216      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 1011     |
|    iterations      | 242      |
|    time_elapsed    | 3921     |
|    total_timesteps | 3964928  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 221         |
|    ep_rew_mean          | 282         |
| time/                   |             |
|    fps                  | 1012        |
|    iterations           | 243         |
|    time_elapsed         | 3932        |
|    total_timesteps      | 3981312     |
| train/                  |             |
|    approx_kl            | 0.004485105 |
|    clip_fraction        | 0.0391      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.491      |
|    explained_variance   | 0.979       |
|    learning_rate        | 0.0003      |
|    loss                 | 12          |
|    n_updates            | 968         |
|    policy_gradient_loss | 0.0012      |
|    value_loss           | 66          |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 222          |
|    ep_rew_mean          | 278          |
| time/                   |              |
|    fps                  | 1013         |
|    iterations           | 244          |
|    time_elapsed         | 3943         |
|    total_timesteps      | 3997696      |
| train/                  |              |
|    approx_kl            | 0.0053656464 |
|    clip_fraction        | 0.0494       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.503       |
|    explained_variance   | 0.991        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.43         |
|    n_updates            | 972          |
|    policy_gradient_loss | 0.00129      |
|    value_loss           | 8.36         |
------------------------------------------

Eval num_timesteps=4000000, episode_reward=285.88 +/- 18.63

Episode length: 215.40 +/- 14.93

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 215          |
|    mean_reward          | 286          |
| time/                   |              |
|    total_timesteps      | 4000000      |
| train/                  |              |
|    approx_kl            | 0.0051986873 |
|    clip_fraction        | 0.0617       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.485       |
|    explained_variance   | 0.998        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.69         |
|    n_updates            | 976          |
|    policy_gradient_loss | 0.00135      |
|    value_loss           | 3.98         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4000000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 216      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1014     |
|    iterations      | 245      |
|    time_elapsed    | 3957     |
|    total_timesteps | 4014080  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 213         |
|    ep_rew_mean          | 286         |
| time/                   |             |
|    fps                  | 1015        |
|    iterations           | 246         |
|    time_elapsed         | 3968        |
|    total_timesteps      | 4030464     |
| train/                  |             |
|    approx_kl            | 0.005799886 |
|    clip_fraction        | 0.0669      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.49       |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.909       |
|    n_updates            | 980         |
|    policy_gradient_loss | 0.000209    |
|    value_loss           | 1.6         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 213          |
|    ep_rew_mean          | 286          |
| time/                   |              |
|    fps                  | 1017         |
|    iterations           | 247          |
|    time_elapsed         | 3978         |
|    total_timesteps      | 4046848      |
| train/                  |              |
|    approx_kl            | 0.0051455833 |
|    clip_fraction        | 0.064        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.513       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.713        |
|    n_updates            | 984          |
|    policy_gradient_loss | -0.0004      |
|    value_loss           | 1.81         |
------------------------------------------

Eval num_timesteps=4050000, episode_reward=282.27 +/- 20.44

Episode length: 215.30 +/- 10.14

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 215          |
|    mean_reward          | 282          |
| time/                   |              |
|    total_timesteps      | 4050000      |
| train/                  |              |
|    approx_kl            | 0.0043434696 |
|    clip_fraction        | 0.0493       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.49        |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.721        |
|    n_updates            | 988          |
|    policy_gradient_loss | 0.000632     |
|    value_loss           | 2.6          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 214      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 1017     |
|    iterations      | 248      |
|    time_elapsed    | 3992     |
|    total_timesteps | 4063232  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 210          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 1019         |
|    iterations           | 249          |
|    time_elapsed         | 4001         |
|    total_timesteps      | 4079616      |
| train/                  |              |
|    approx_kl            | 0.0051403316 |
|    clip_fraction        | 0.0569       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.474       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.653        |
|    n_updates            | 992          |
|    policy_gradient_loss | 0.000586     |
|    value_loss           | 2.06         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 217          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 1020         |
|    iterations           | 250          |
|    time_elapsed         | 4012         |
|    total_timesteps      | 4096000      |
| train/                  |              |
|    approx_kl            | 0.0045422157 |
|    clip_fraction        | 0.0496       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.478       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.721        |
|    n_updates            | 996          |
|    policy_gradient_loss | 0.000278     |
|    value_loss           | 6.86         |
------------------------------------------

Eval num_timesteps=4100000, episode_reward=283.49 +/- 18.23

Episode length: 211.90 +/- 12.55

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 212         |
|    mean_reward          | 283         |
| time/                   |             |
|    total_timesteps      | 4100000     |
| train/                  |             |
|    approx_kl            | 0.003916037 |
|    clip_fraction        | 0.042       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.496      |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.8         |
|    n_updates            | 1000        |
|    policy_gradient_loss | -0.000306   |
|    value_loss           | 66.3        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4100000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 220      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 1021     |
|    iterations      | 251      |
|    time_elapsed    | 4026     |
|    total_timesteps | 4112384  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 210         |
|    ep_rew_mean          | 283         |
| time/                   |             |
|    fps                  | 1022        |
|    iterations           | 252         |
|    time_elapsed         | 4036        |
|    total_timesteps      | 4128768     |
| train/                  |             |
|    approx_kl            | 0.005065036 |
|    clip_fraction        | 0.0656      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.49       |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.508       |
|    n_updates            | 1004        |
|    policy_gradient_loss | 0.00028     |
|    value_loss           | 3           |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 210         |
|    ep_rew_mean          | 284         |
| time/                   |             |
|    fps                  | 1024        |
|    iterations           | 253         |
|    time_elapsed         | 4047        |
|    total_timesteps      | 4145152     |
| train/                  |             |
|    approx_kl            | 0.003839793 |
|    clip_fraction        | 0.0493      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.484      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.11        |
|    n_updates            | 1008        |
|    policy_gradient_loss | 0.00119     |
|    value_loss           | 2.07        |
-----------------------------------------

Eval num_timesteps=4150000, episode_reward=279.41 +/- 20.57

Episode length: 207.10 +/- 17.24

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 207          |
|    mean_reward          | 279          |
| time/                   |              |
|    total_timesteps      | 4150000      |
| train/                  |              |
|    approx_kl            | 0.0040315217 |
|    clip_fraction        | 0.0486       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.49        |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 0.464        |
|    n_updates            | 1012         |
|    policy_gradient_loss | 0.000922     |
|    value_loss           | 75.8         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 208      |
|    ep_rew_mean     | 283      |
| time/              |          |
|    fps             | 1024     |
|    iterations      | 254      |
|    time_elapsed    | 4060     |
|    total_timesteps | 4161536  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 209          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 1026         |
|    iterations           | 255          |
|    time_elapsed         | 4071         |
|    total_timesteps      | 4177920      |
| train/                  |              |
|    approx_kl            | 0.0054493146 |
|    clip_fraction        | 0.0701       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.5         |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.93         |
|    n_updates            | 1016         |
|    policy_gradient_loss | 0.000848     |
|    value_loss           | 79.9         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 210          |
|    ep_rew_mean          | 280          |
| time/                   |              |
|    fps                  | 1027         |
|    iterations           | 256          |
|    time_elapsed         | 4081         |
|    total_timesteps      | 4194304      |
| train/                  |              |
|    approx_kl            | 0.0035764035 |
|    clip_fraction        | 0.0351       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.483       |
|    explained_variance   | 0.943        |
|    learning_rate        | 0.0003       |
|    loss                 | 282          |
|    n_updates            | 1020         |
|    policy_gradient_loss | 0.000282     |
|    value_loss           | 216          |
------------------------------------------

Eval num_timesteps=4200000, episode_reward=285.05 +/- 19.38

Episode length: 209.80 +/- 9.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 210          |
|    mean_reward          | 285          |
| time/                   |              |
|    total_timesteps      | 4200000      |
| train/                  |              |
|    approx_kl            | 0.0054473723 |
|    clip_fraction        | 0.0657       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.499       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 295          |
|    n_updates            | 1024         |
|    policy_gradient_loss | -0.000581    |
|    value_loss           | 103          |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4200000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 215      |
|    ep_rew_mean     | 277      |
| time/              |          |
|    fps             | 1028     |
|    iterations      | 257      |
|    time_elapsed    | 4094     |
|    total_timesteps | 4210688  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 211         |
|    ep_rew_mean          | 286         |
| time/                   |             |
|    fps                  | 1029        |
|    iterations           | 258         |
|    time_elapsed         | 4105        |
|    total_timesteps      | 4227072     |
| train/                  |             |
|    approx_kl            | 0.005294144 |
|    clip_fraction        | 0.0634      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.481      |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.845       |
|    n_updates            | 1028        |
|    policy_gradient_loss | 0.000882    |
|    value_loss           | 134         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 207         |
|    ep_rew_mean          | 287         |
| time/                   |             |
|    fps                  | 1030        |
|    iterations           | 259         |
|    time_elapsed         | 4116        |
|    total_timesteps      | 4243456     |
| train/                  |             |
|    approx_kl            | 0.004391283 |
|    clip_fraction        | 0.0618      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.487      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.467       |
|    n_updates            | 1032        |
|    policy_gradient_loss | 0.00161     |
|    value_loss           | 1.1         |
-----------------------------------------

Eval num_timesteps=4250000, episode_reward=279.34 +/- 21.04

Episode length: 204.10 +/- 17.37

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 204         |
|    mean_reward          | 279         |
| time/                   |             |
|    total_timesteps      | 4250000     |
| train/                  |             |
|    approx_kl            | 0.004305415 |
|    clip_fraction        | 0.0482      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.499      |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.33        |
|    n_updates            | 1036        |
|    policy_gradient_loss | 0.000364    |
|    value_loss           | 76.3        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 215      |
|    ep_rew_mean     | 288      |
| time/              |          |
|    fps             | 1031     |
|    iterations      | 260      |
|    time_elapsed    | 4129     |
|    total_timesteps | 4259840  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 206          |
|    ep_rew_mean          | 285          |
| time/                   |              |
|    fps                  | 1032         |
|    iterations           | 261          |
|    time_elapsed         | 4140         |
|    total_timesteps      | 4276224      |
| train/                  |              |
|    approx_kl            | 0.0038648585 |
|    clip_fraction        | 0.0481       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.468       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.588        |
|    n_updates            | 1040         |
|    policy_gradient_loss | 0.000991     |
|    value_loss           | 1.38         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 207         |
|    ep_rew_mean          | 284         |
| time/                   |             |
|    fps                  | 1034        |
|    iterations           | 262         |
|    time_elapsed         | 4150        |
|    total_timesteps      | 4292608     |
| train/                  |             |
|    approx_kl            | 0.006060837 |
|    clip_fraction        | 0.0636      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.482      |
|    explained_variance   | 1           |
|    learning_rate        | 0.0003      |
|    loss                 | 0.804       |
|    n_updates            | 1044        |
|    policy_gradient_loss | -0.000124   |
|    value_loss           | 1.05        |
-----------------------------------------

Eval num_timesteps=4300000, episode_reward=288.25 +/- 13.49

Episode length: 206.20 +/- 13.37

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 206        |
|    mean_reward          | 288        |
| time/                   |            |
|    total_timesteps      | 4300000    |
| train/                  |            |
|    approx_kl            | 0.00390462 |
|    clip_fraction        | 0.0524     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.478     |
|    explained_variance   | 0.999      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.59       |
|    n_updates            | 1048       |
|    policy_gradient_loss | 0.0011     |
|    value_loss           | 1.74       |
----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4300000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 217      |
|    ep_rew_mean     | 284      |
| time/              |          |
|    fps             | 1034     |
|    iterations      | 263      |
|    time_elapsed    | 4164     |
|    total_timesteps | 4308992  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 217         |
|    ep_rew_mean          | 279         |
| time/                   |             |
|    fps                  | 1036        |
|    iterations           | 264         |
|    time_elapsed         | 4174        |
|    total_timesteps      | 4325376     |
| train/                  |             |
|    approx_kl            | 0.003704667 |
|    clip_fraction        | 0.0407      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.499      |
|    explained_variance   | 0.979       |
|    learning_rate        | 0.0003      |
|    loss                 | 256         |
|    n_updates            | 1052        |
|    policy_gradient_loss | 0.000485    |
|    value_loss           | 79.8        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 216          |
|    ep_rew_mean          | 284          |
| time/                   |              |
|    fps                  | 1037         |
|    iterations           | 265          |
|    time_elapsed         | 4185         |
|    total_timesteps      | 4341760      |
| train/                  |              |
|    approx_kl            | 0.0038337677 |
|    clip_fraction        | 0.0462       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.485       |
|    explained_variance   | 0.985        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.16         |
|    n_updates            | 1056         |
|    policy_gradient_loss | 0.000582     |
|    value_loss           | 49.2         |
------------------------------------------

Eval num_timesteps=4350000, episode_reward=286.94 +/- 22.29

Episode length: 211.75 +/- 15.24

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 212         |
|    mean_reward          | 287         |
| time/                   |             |
|    total_timesteps      | 4350000     |
| train/                  |             |
|    approx_kl            | 0.004293643 |
|    clip_fraction        | 0.0448      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.488      |
|    explained_variance   | 0.997       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.957       |
|    n_updates            | 1060        |
|    policy_gradient_loss | -1.4e-05    |
|    value_loss           | 5.99        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 208      |
|    ep_rew_mean     | 285      |
| time/              |          |
|    fps             | 1037     |
|    iterations      | 266      |
|    time_elapsed    | 4199     |
|    total_timesteps | 4358144  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 215         |
|    ep_rew_mean          | 287         |
| time/                   |             |
|    fps                  | 1038        |
|    iterations           | 267         |
|    time_elapsed         | 4210        |
|    total_timesteps      | 4374528     |
| train/                  |             |
|    approx_kl            | 0.003506335 |
|    clip_fraction        | 0.0467      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.472      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.731       |
|    n_updates            | 1064        |
|    policy_gradient_loss | 0.00141     |
|    value_loss           | 1.63        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 210         |
|    ep_rew_mean          | 285         |
| time/                   |             |
|    fps                  | 1040        |
|    iterations           | 268         |
|    time_elapsed         | 4221        |
|    total_timesteps      | 4390912     |
| train/                  |             |
|    approx_kl            | 0.004650349 |
|    clip_fraction        | 0.0542      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.476      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.646       |
|    n_updates            | 1068        |
|    policy_gradient_loss | 0.000309    |
|    value_loss           | 1.71        |
-----------------------------------------

Eval num_timesteps=4400000, episode_reward=280.47 +/- 18.63

Episode length: 208.10 +/- 10.13

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 208         |
|    mean_reward          | 280         |
| time/                   |             |
|    total_timesteps      | 4400000     |
| train/                  |             |
|    approx_kl            | 0.004557787 |
|    clip_fraction        | 0.0506      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.489      |
|    explained_variance   | 0.983       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.59        |
|    n_updates            | 1072        |
|    policy_gradient_loss | 0.000157    |
|    value_loss           | 63          |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4400000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 207      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1040     |
|    iterations      | 269      |
|    time_elapsed    | 4234     |
|    total_timesteps | 4407296  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 208          |
|    ep_rew_mean          | 285          |
| time/                   |              |
|    fps                  | 1041         |
|    iterations           | 270          |
|    time_elapsed         | 4245         |
|    total_timesteps      | 4423680      |
| train/                  |              |
|    approx_kl            | 0.0052596843 |
|    clip_fraction        | 0.063        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.491       |
|    explained_variance   | 1            |
|    learning_rate        | 0.0003       |
|    loss                 | 0.509        |
|    n_updates            | 1076         |
|    policy_gradient_loss | 0.000879     |
|    value_loss           | 1.01         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 216          |
|    ep_rew_mean          | 284          |
| time/                   |              |
|    fps                  | 1043         |
|    iterations           | 271          |
|    time_elapsed         | 4256         |
|    total_timesteps      | 4440064      |
| train/                  |              |
|    approx_kl            | 0.0033727374 |
|    clip_fraction        | 0.0412       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.469       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28         |
|    n_updates            | 1080         |
|    policy_gradient_loss | 0.0013       |
|    value_loss           | 2.89         |
------------------------------------------

Eval num_timesteps=4450000, episode_reward=288.05 +/- 20.28

Episode length: 206.20 +/- 12.41

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 206          |
|    mean_reward          | 288          |
| time/                   |              |
|    total_timesteps      | 4450000      |
| train/                  |              |
|    approx_kl            | 0.0037434301 |
|    clip_fraction        | 0.0399       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.471       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.89         |
|    n_updates            | 1084         |
|    policy_gradient_loss | 0.000204     |
|    value_loss           | 11.7         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 213      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 1043     |
|    iterations      | 272      |
|    time_elapsed    | 4270     |
|    total_timesteps | 4456448  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 203          |
|    ep_rew_mean          | 283          |
| time/                   |              |
|    fps                  | 1044         |
|    iterations           | 273          |
|    time_elapsed         | 4280         |
|    total_timesteps      | 4472832      |
| train/                  |              |
|    approx_kl            | 0.0035750212 |
|    clip_fraction        | 0.0424       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.47        |
|    explained_variance   | 0.968        |
|    learning_rate        | 0.0003       |
|    loss                 | 10.7         |
|    n_updates            | 1088         |
|    policy_gradient_loss | 0.000517     |
|    value_loss           | 114          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 205         |
|    ep_rew_mean          | 284         |
| time/                   |             |
|    fps                  | 1046        |
|    iterations           | 274         |
|    time_elapsed         | 4290        |
|    total_timesteps      | 4489216     |
| train/                  |             |
|    approx_kl            | 0.004069333 |
|    clip_fraction        | 0.066       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.468      |
|    explained_variance   | 0.999       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.934       |
|    n_updates            | 1092        |
|    policy_gradient_loss | 0.00113     |
|    value_loss           | 2.37        |
-----------------------------------------

Eval num_timesteps=4500000, episode_reward=279.66 +/- 22.98

Episode length: 208.05 +/- 12.24

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 208         |
|    mean_reward          | 280         |
| time/                   |             |
|    total_timesteps      | 4500000     |
| train/                  |             |
|    approx_kl            | 0.004655072 |
|    clip_fraction        | 0.0539      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.452      |
|    explained_variance   | 0.983       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.773       |
|    n_updates            | 1096        |
|    policy_gradient_loss | 0.000262    |
|    value_loss           | 66.7        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4500000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 205      |
|    ep_rew_mean     | 287      |
| time/              |          |
|    fps             | 1046     |
|    iterations      | 275      |
|    time_elapsed    | 4303     |
|    total_timesteps | 4505600  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 208          |
|    ep_rew_mean          | 288          |
| time/                   |              |
|    fps                  | 1048         |
|    iterations           | 276          |
|    time_elapsed         | 4314         |
|    total_timesteps      | 4521984      |
| train/                  |              |
|    approx_kl            | 0.0051026656 |
|    clip_fraction        | 0.0614       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.461       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.503        |
|    n_updates            | 1100         |
|    policy_gradient_loss | 0.00101      |
|    value_loss           | 1.79         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 216          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 1049         |
|    iterations           | 277          |
|    time_elapsed         | 4325         |
|    total_timesteps      | 4538368      |
| train/                  |              |
|    approx_kl            | 0.0045961845 |
|    clip_fraction        | 0.0536       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.471       |
|    explained_variance   | 0.997        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.35         |
|    n_updates            | 1104         |
|    policy_gradient_loss | 3.14e-05     |
|    value_loss           | 3.48         |
------------------------------------------

Eval num_timesteps=4550000, episode_reward=279.39 +/- 22.68

Episode length: 201.95 +/- 13.03

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 202         |
|    mean_reward          | 279         |
| time/                   |             |
|    total_timesteps      | 4550000     |
| train/                  |             |
|    approx_kl            | 0.003440144 |
|    clip_fraction        | 0.0465      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.472      |
|    explained_variance   | 0.985       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.2         |
|    n_updates            | 1108        |
|    policy_gradient_loss | -8.48e-05   |
|    value_loss           | 69.3        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 201      |
|    ep_rew_mean     | 279      |
| time/              |          |
|    fps             | 1049     |
|    iterations      | 278      |
|    time_elapsed    | 4338     |
|    total_timesteps | 4554752  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 203          |
|    ep_rew_mean          | 283          |
| time/                   |              |
|    fps                  | 1051         |
|    iterations           | 279          |
|    time_elapsed         | 4349         |
|    total_timesteps      | 4571136      |
| train/                  |              |
|    approx_kl            | 0.0035835328 |
|    clip_fraction        | 0.0393       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.461       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.27         |
|    n_updates            | 1112         |
|    policy_gradient_loss | 0.000969     |
|    value_loss           | 66.2         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 204         |
|    ep_rew_mean          | 283         |
| time/                   |             |
|    fps                  | 1052        |
|    iterations           | 280         |
|    time_elapsed         | 4358        |
|    total_timesteps      | 4587520     |
| train/                  |             |
|    approx_kl            | 0.004398723 |
|    clip_fraction        | 0.0498      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.464      |
|    explained_variance   | 0.996       |
|    learning_rate        | 0.0003      |
|    loss                 | 5.22        |
|    n_updates            | 1116        |
|    policy_gradient_loss | 4.64e-05    |
|    value_loss           | 7.86        |
-----------------------------------------

Eval num_timesteps=4600000, episode_reward=279.18 +/- 20.70

Episode length: 199.25 +/- 11.63

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 199          |
|    mean_reward          | 279          |
| time/                   |              |
|    total_timesteps      | 4600000      |
| train/                  |              |
|    approx_kl            | 0.0032785428 |
|    clip_fraction        | 0.0434       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.472       |
|    explained_variance   | 0.977        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28         |
|    n_updates            | 1120         |
|    policy_gradient_loss | 0.000456     |
|    value_loss           | 69.8         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4600000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 202      |
|    ep_rew_mean     | 275      |
| time/              |          |
|    fps             | 1053     |
|    iterations      | 281      |
|    time_elapsed    | 4371     |
|    total_timesteps | 4603904  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 202         |
|    ep_rew_mean          | 281         |
| time/                   |             |
|    fps                  | 1054        |
|    iterations           | 282         |
|    time_elapsed         | 4382        |
|    total_timesteps      | 4620288     |
| train/                  |             |
|    approx_kl            | 0.005787832 |
|    clip_fraction        | 0.0529      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.48       |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | 6.62        |
|    n_updates            | 1124        |
|    policy_gradient_loss | -0.000411   |
|    value_loss           | 189         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 204          |
|    ep_rew_mean          | 288          |
| time/                   |              |
|    fps                  | 1055         |
|    iterations           | 283          |
|    time_elapsed         | 4392         |
|    total_timesteps      | 4636672      |
| train/                  |              |
|    approx_kl            | 0.0070202197 |
|    clip_fraction        | 0.0809       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.478       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 2.93         |
|    n_updates            | 1128         |
|    policy_gradient_loss | 0.000144     |
|    value_loss           | 69.6         |
------------------------------------------

Eval num_timesteps=4650000, episode_reward=280.19 +/- 27.54

Episode length: 209.95 +/- 31.40

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 210          |
|    mean_reward          | 280          |
| time/                   |              |
|    total_timesteps      | 4650000      |
| train/                  |              |
|    approx_kl            | 0.0052068774 |
|    clip_fraction        | 0.0647       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.455       |
|    explained_variance   | 0.979        |
|    learning_rate        | 0.0003       |
|    loss                 | 36.2         |
|    n_updates            | 1132         |
|    policy_gradient_loss | -0.000222    |
|    value_loss           | 77.8         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 204      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 1056     |
|    iterations      | 284      |
|    time_elapsed    | 4405     |
|    total_timesteps | 4653056  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 207          |
|    ep_rew_mean          | 287          |
| time/                   |              |
|    fps                  | 1057         |
|    iterations           | 285          |
|    time_elapsed         | 4416         |
|    total_timesteps      | 4669440      |
| train/                  |              |
|    approx_kl            | 0.0041604126 |
|    clip_fraction        | 0.0533       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.46        |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 17.7         |
|    n_updates            | 1136         |
|    policy_gradient_loss | 0.000776     |
|    value_loss           | 123          |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 204         |
|    ep_rew_mean          | 281         |
| time/                   |             |
|    fps                  | 1058        |
|    iterations           | 286         |
|    time_elapsed         | 4426        |
|    total_timesteps      | 4685824     |
| train/                  |             |
|    approx_kl            | 0.005297689 |
|    clip_fraction        | 0.0591      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.456      |
|    explained_variance   | 0.982       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.32        |
|    n_updates            | 1140        |
|    policy_gradient_loss | 0.000822    |
|    value_loss           | 62.5        |
-----------------------------------------

Eval num_timesteps=4700000, episode_reward=286.26 +/- 16.02

Episode length: 199.75 +/- 17.28

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 200          |
|    mean_reward          | 286          |
| time/                   |              |
|    total_timesteps      | 4700000      |
| train/                  |              |
|    approx_kl            | 0.0044489745 |
|    clip_fraction        | 0.0476       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.458       |
|    explained_variance   | 0.973        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.73         |
|    n_updates            | 1144         |
|    policy_gradient_loss | 0.00112      |
|    value_loss           | 91.7         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4700000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 203      |
|    ep_rew_mean     | 281      |
| time/              |          |
|    fps             | 1059     |
|    iterations      | 287      |
|    time_elapsed    | 4439     |
|    total_timesteps | 4702208  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 202          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 1060         |
|    iterations           | 288          |
|    time_elapsed         | 4449         |
|    total_timesteps      | 4718592      |
| train/                  |              |
|    approx_kl            | 0.0039417883 |
|    clip_fraction        | 0.0481       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.455       |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 45           |
|    n_updates            | 1148         |
|    policy_gradient_loss | -8.24e-05    |
|    value_loss           | 159          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 201          |
|    ep_rew_mean          | 285          |
| time/                   |              |
|    fps                  | 1061         |
|    iterations           | 289          |
|    time_elapsed         | 4459         |
|    total_timesteps      | 4734976      |
| train/                  |              |
|    approx_kl            | 0.0042344164 |
|    clip_fraction        | 0.0603       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.441       |
|    explained_variance   | 0.983        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.81         |
|    n_updates            | 1152         |
|    policy_gradient_loss | 0.00122      |
|    value_loss           | 70.8         |
------------------------------------------

Eval num_timesteps=4750000, episode_reward=292.31 +/- 22.00

Episode length: 197.95 +/- 15.73

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 198          |
|    mean_reward          | 292          |
| time/                   |              |
|    total_timesteps      | 4750000      |
| train/                  |              |
|    approx_kl            | 0.0060433582 |
|    clip_fraction        | 0.0582       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.447       |
|    explained_variance   | 0.982        |
|    learning_rate        | 0.0003       |
|    loss                 | 11           |
|    n_updates            | 1156         |
|    policy_gradient_loss | 9.92e-05     |
|    value_loss           | 71.9         |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 197      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1062     |
|    iterations      | 290      |
|    time_elapsed    | 4472     |
|    total_timesteps | 4751360  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 200         |
|    ep_rew_mean          | 287         |
| time/                   |             |
|    fps                  | 1063        |
|    iterations           | 291         |
|    time_elapsed         | 4483        |
|    total_timesteps      | 4767744     |
| train/                  |             |
|    approx_kl            | 0.003945359 |
|    clip_fraction        | 0.0558      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.448      |
|    explained_variance   | 0.994       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.802       |
|    n_updates            | 1160        |
|    policy_gradient_loss | 0.00181     |
|    value_loss           | 13.3        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 207          |
|    ep_rew_mean          | 282          |
| time/                   |              |
|    fps                  | 1064         |
|    iterations           | 292          |
|    time_elapsed         | 4494         |
|    total_timesteps      | 4784128      |
| train/                  |              |
|    approx_kl            | 0.0045094085 |
|    clip_fraction        | 0.0523       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.474       |
|    explained_variance   | 0.983        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.17         |
|    n_updates            | 1164         |
|    policy_gradient_loss | 0.000448     |
|    value_loss           | 73.3         |
------------------------------------------

Eval num_timesteps=4800000, episode_reward=282.26 +/- 16.85

Episode length: 195.85 +/- 12.71

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 196         |
|    mean_reward          | 282         |
| time/                   |             |
|    total_timesteps      | 4800000     |
| train/                  |             |
|    approx_kl            | 0.004744456 |
|    clip_fraction        | 0.0641      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.463      |
|    explained_variance   | 0.985       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.74        |
|    n_updates            | 1168        |
|    policy_gradient_loss | 0.00144     |
|    value_loss           | 63.5        |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4800000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 199      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1065     |
|    iterations      | 293      |
|    time_elapsed    | 4507     |
|    total_timesteps | 4800512  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 202         |
|    ep_rew_mean          | 285         |
| time/                   |             |
|    fps                  | 1066        |
|    iterations           | 294         |
|    time_elapsed         | 4517        |
|    total_timesteps      | 4816896     |
| train/                  |             |
|    approx_kl            | 0.005321958 |
|    clip_fraction        | 0.0443      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.451      |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | 69.2        |
|    n_updates            | 1172        |
|    policy_gradient_loss | 0.000773    |
|    value_loss           | 88          |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 205          |
|    ep_rew_mean          | 288          |
| time/                   |              |
|    fps                  | 1067         |
|    iterations           | 295          |
|    time_elapsed         | 4527         |
|    total_timesteps      | 4833280      |
| train/                  |              |
|    approx_kl            | 0.0058773626 |
|    clip_fraction        | 0.0602       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.447       |
|    explained_variance   | 0.966        |
|    learning_rate        | 0.0003       |
|    loss                 | 8.56         |
|    n_updates            | 1176         |
|    policy_gradient_loss | -0.00103     |
|    value_loss           | 126          |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 212          |
|    ep_rew_mean          | 277          |
| time/                   |              |
|    fps                  | 1068         |
|    iterations           | 296          |
|    time_elapsed         | 4538         |
|    total_timesteps      | 4849664      |
| train/                  |              |
|    approx_kl            | 0.0052223825 |
|    clip_fraction        | 0.0624       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.451       |
|    explained_variance   | 0.98         |
|    learning_rate        | 0.0003       |
|    loss                 | 3.54         |
|    n_updates            | 1180         |
|    policy_gradient_loss | 0.00246      |
|    value_loss           | 75.6         |
------------------------------------------

Eval num_timesteps=4850000, episode_reward=290.64 +/- 18.37

Episode length: 198.90 +/- 14.11

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 199          |
|    mean_reward          | 291          |
| time/                   |              |
|    total_timesteps      | 4850000      |
| train/                  |              |
|    approx_kl            | 0.0040848027 |
|    clip_fraction        | 0.0334       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.439       |
|    explained_variance   | 0.95         |
|    learning_rate        | 0.0003       |
|    loss                 | 105          |
|    n_updates            | 1184         |
|    policy_gradient_loss | -1.85e-06    |
|    value_loss           | 206          |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 203      |
|    ep_rew_mean     | 268      |
| time/              |          |
|    fps             | 1069     |
|    iterations      | 297      |
|    time_elapsed    | 4551     |
|    total_timesteps | 4866048  |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 201         |
|    ep_rew_mean          | 270         |
| time/                   |             |
|    fps                  | 1070        |
|    iterations           | 298         |
|    time_elapsed         | 4562        |
|    total_timesteps      | 4882432     |
| train/                  |             |
|    approx_kl            | 0.002829622 |
|    clip_fraction        | 0.0393      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.46       |
|    explained_variance   | 0.929       |
|    learning_rate        | 0.0003      |
|    loss                 | 49.3        |
|    n_updates            | 1188        |
|    policy_gradient_loss | -0.000633   |
|    value_loss           | 300         |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 197          |
|    ep_rew_mean          | 278          |
| time/                   |              |
|    fps                  | 1071         |
|    iterations           | 299          |
|    time_elapsed         | 4572         |
|    total_timesteps      | 4898816      |
| train/                  |              |
|    approx_kl            | 0.0041674767 |
|    clip_fraction        | 0.0556       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.469       |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 46.9         |
|    n_updates            | 1192         |
|    policy_gradient_loss | 0.000957     |
|    value_loss           | 188          |
------------------------------------------

Eval num_timesteps=4900000, episode_reward=281.61 +/- 29.27

Episode length: 236.70 +/- 175.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 237         |
|    mean_reward          | 282         |
| time/                   |             |
|    total_timesteps      | 4900000     |
| train/                  |             |
|    approx_kl            | 0.004440287 |
|    clip_fraction        | 0.0443      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.442      |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | 11.2        |
|    n_updates            | 1196        |
|    policy_gradient_loss | 0.000254    |
|    value_loss           | 272         |
-----------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_4900000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 203      |
|    ep_rew_mean     | 283      |
| time/              |          |
|    fps             | 1071     |
|    iterations      | 300      |
|    time_elapsed    | 4586     |
|    total_timesteps | 4915200  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 208          |
|    ep_rew_mean          | 279          |
| time/                   |              |
|    fps                  | 1072         |
|    iterations           | 301          |
|    time_elapsed         | 4597         |
|    total_timesteps      | 4931584      |
| train/                  |              |
|    approx_kl            | 0.0060898196 |
|    clip_fraction        | 0.0737       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.459       |
|    explained_variance   | 0.994        |
|    learning_rate        | 0.0003       |
|    loss                 | 10.4         |
|    n_updates            | 1200         |
|    policy_gradient_loss | 0.00119      |
|    value_loss           | 8.75         |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 222        |
|    ep_rew_mean          | 282        |
| time/                   |            |
|    fps                  | 1073       |
|    iterations           | 302        |
|    time_elapsed         | 4608       |
|    total_timesteps      | 4947968    |
| train/                  |            |
|    approx_kl            | 0.00434957 |
|    clip_fraction        | 0.0476     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.465     |
|    explained_variance   | 0.971      |
|    learning_rate        | 0.0003     |
|    loss                 | 67.5       |
|    n_updates            | 1204       |
|    policy_gradient_loss | 0.000926   |
|    value_loss           | 108        |
----------------------------------------

Eval num_timesteps=4950000, episode_reward=283.20 +/- 20.78

Episode length: 200.75 +/- 13.43

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 201          |
|    mean_reward          | 283          |
| time/                   |              |
|    total_timesteps      | 4950000      |
| train/                  |              |
|    approx_kl            | 0.0045993496 |
|    clip_fraction        | 0.0581       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.469       |
|    explained_variance   | 0.995        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.61         |
|    n_updates            | 1208         |
|    policy_gradient_loss | 0.00125      |
|    value_loss           | 10           |
------------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 216      |
|    ep_rew_mean     | 278      |
| time/              |          |
|    fps             | 1074     |
|    iterations      | 303      |
|    time_elapsed    | 4622     |
|    total_timesteps | 4964352  |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 214          |
|    ep_rew_mean          | 284          |
| time/                   |              |
|    fps                  | 1075         |
|    iterations           | 304          |
|    time_elapsed         | 4632         |
|    total_timesteps      | 4980736      |
| train/                  |              |
|    approx_kl            | 0.0039312225 |
|    clip_fraction        | 0.06         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.471       |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 6.66         |
|    n_updates            | 1212         |
|    policy_gradient_loss | 0.00025      |
|    value_loss           | 97           |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 200         |
|    ep_rew_mean          | 287         |
| time/                   |             |
|    fps                  | 1076        |
|    iterations           | 305         |
|    time_elapsed         | 4643        |
|    total_timesteps      | 4997120     |
| train/                  |             |
|    approx_kl            | 0.004624467 |
|    clip_fraction        | 0.0465      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.479      |
|    explained_variance   | 0.992       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.18        |
|    n_updates            | 1216        |
|    policy_gradient_loss | 0.000886    |
|    value_loss           | 11.9        |
-----------------------------------------

Eval num_timesteps=5000000, episode_reward=282.31 +/- 17.59

Episode length: 202.80 +/- 12.22

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 203          |
|    mean_reward          | 282          |
| time/                   |              |
|    total_timesteps      | 5000000      |
| train/                  |              |
|    approx_kl            | 0.0049344674 |
|    clip_fraction        | 0.0649       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.462       |
|    explained_variance   | 0.999        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.3          |
|    n_updates            | 1220         |
|    policy_gradient_loss | 0.00144      |
|    value_loss           | 3.29         |
------------------------------------------

Saving model checkpoint to
/content/rl-experiments/ppo_lunarlander_128x128/checkpoints/ppo_lunarlander_128x128_5000000_steps.zip

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 197      |
|    ep_rew_mean     | 282      |
| time/              |          |
|    fps             | 1076     |
|    iterations      | 306      |
|    time_elapsed    | 4656     |
|    total_timesteps | 5013504  |
---------------------------------

Best model: /content/rl-experiments/ppo_lunarlander_128x128/best_model/best_model.zip
Final model: /content/rl-experiments/ppo_lunarlander_128x128/final_model.zip

{'experiment_name': 'ppo_lunarlander_128x128',
 'output_dir': PosixPath('/content/rl-experiments/ppo_lunarlander_128x128'),
 'best_model_path': PosixPath('/content/rl-experiments/ppo_lunarlander_128x128/best_model/best_model.zip'),
 'final_model_path': PosixPath('/content/rl-experiments/ppo_lunarlander_128x128/final_model.zip'),
 'evaluations_path': PosixPath('/content/rl-experiments/ppo_lunarlander_128x128/evaluations/evaluations.npz'),
 'config_path': PosixPath('/content/rl-experiments/ppo_lunarlander_128x128/training_config.json'),
 'configuration': {'experiment_name': 'ppo_lunarlander_128x128',
  'env_id': 'LunarLander-v3',
  'env_kwargs': {},
  'total_timesteps': 5000000,
  'n_envs': 16,
  'seed': 42,
  'actor_layers': [128, 128],
  'critic_layers': [128, 128],
  'learning_rate': 0.0003,
  'n_steps': 1024,
  'batch_size': 64,
  'n_epochs': 4,
  'gamma': 0.999,
  'gae_lambda': 0.98,
  'ent_coef': 0.01,
  'clip_range': 0.2,
  'eval_every_timesteps': 50000,
  'checkpoint_every_timesteps': 100000,
  'n_eval_episodes': 20,
  'device': 'cpu'}}

#### Evaluate new best checkpoint

In [10]:
EVALUATION_SEEDS = list(
    range(10_000, 10_100)
)

results_128 = evaluate_model(
    run_128["best_model_path"],
    seeds=EVALUATION_SEEDS,
    env_id="LunarLander-v3",
)

pd.Series(
    metrics_only(results_128),
    name="128x128 model",
)

mean_reward            280.657026
std_reward              34.314421
course_score           246.342605
success_rate_200         0.990000
mean_episode_length    219.810000
min_reward               4.306383
max_reward             322.048230
n_episodes             100.000000
Name: 128x128 model, dtype: float64

#### Compare with current Hub model

In [14]:
comparison_128 = compare_candidate_to_hub(
    run_128["best_model_path"],
    repo_id="KaptainKris/HuggingFace_RL_Course",
    hub_model_filename="ppo-LunarLander-v3.zip",
    evaluation_seeds=EVALUATION_SEEDS,
    env_id="LunarLander-v3",

    # Compare by mean reward rather than mean - std
    # Alternative selection metric: "course_score"
    selection_metric="mean_reward",

    # Any positive improvement is sufficient
    min_improvement=0.0,
)

ppo-LunarLander-v3.zip:   0%|          | 0.00/464k [00:00<?, ?B/s]

,mean_reward,std_reward,course_score,success_rate_200,mean_episode_length,min_reward,max_reward,n_episodes
model,,,,,,,,
candidate,280.657,34.314,246.343,0.99,219.81,4.306,322.048,100
current_hub,280.657,34.314,246.343,0.99,219.81,4.306,322.048,100

Selection metric: mean_reward
Improvement: +0.000
Candidate is eligible for upload: False

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

#### Upload only if new model is better

In [16]:
promotion_128 = promote_model_to_hub(
    run_128["best_model_path"],

    repo_id="KaptainKris/HuggingFace_RL_Course",
    model_filename="ppo-LunarLander-v3.zip",
    env_id="LunarLander-v3",

    evaluation_seeds=EVALUATION_SEEDS,

    compare_to_current=True,
    selection_metric="mean_reward",
    min_improvement=1.0,

    # Leave False to protect the current model
    force_upload=False,

    # Set False to create files without uploading
    upload=True,

    video_seed=42,
    training_config_path=run_128["config_path"],

    commit_message=(
        "Promote 128x128 PPO LunarLander-v3 model"
    ),
)

promotion_128

,mean_reward,std_reward,course_score,success_rate_200,mean_episode_length,min_reward,max_reward,n_episodes
model,,,,,,,,
candidate,280.657,34.314,246.343,0.99,219.81,4.306,322.048,100
current_hub,280.657,34.314,246.343,0.99,219.81,4.306,322.048,100

Selection metric: mean_reward
Improvement: +0.000
Candidate is eligible for upload: False
The candidate did not meet the promotion criterion. Nothing was uploaded.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{'uploaded': False,
 'eligible': False,
 'comparison': {'candidate': {'mean_reward': 280.65702628540856,
   'std_reward': 34.31442136477228,
   'course_score': 246.3426049206363,
   'success_rate_200': 0.99,
   'mean_episode_length': 219.81,
   'min_reward': 4.306382930665833,
   'max_reward': 322.0482304101894,
   'n_episodes': 100,
   'rewards': [278.95682092028363,
    292.6435450729996,
    315.7611168805777,
    262.50190062260344,
    275.05531675423015,
    264.36260912031486,
    291.7210375695704,
    292.054123501242,
    259.0069320356084,
    304.2247635525612,
    310.2938162318376,
    303.26536872945724,
    296.7189655487642,
    4.306382930665833,
    280.2730755821684,
    264.7696430630234,
    253.6859047047289,
    293.93336211921866,
    279.45448816699536,
    259.5041331167257,
    298.69907094490657,
    308.87209646922054,
    268.05976633884904,
    252.97744485047184,
    303.53768777441405,
    274.1793127025521,
    244.16543420124435,
    279.4639273335066,
    265.1139628007316,
    277.8204773445916,
    288.1341154851691,
    260.9338659098198,
    302.88606672342837,
    295.59006566316714,
    297.49419068926204,
    303.30836189169446,
    291.65619564782594,
    276.4117666401064,
    292.38157894708854,
    295.9492409461043,
    302.3744866045082,
    288.79437913979916,
    284.0999809627908,
    305.866138448255,
    280.56513753580043,
    308.4118098638436,
    269.99630191080314,
    301.11921407511545,
    280.2782188151149,
    314.69308141477916,
    296.7096455991543,
    311.56442100385414,
    254.9051206306109,
    289.79610053969225,
    269.3693334796875,
    283.52956915509185,
    243.23127162823496,
    312.76672710166997,
    266.75508056779125,
    251.84540846309207,
    260.10599997745464,
    309.1370670354429,
    276.3048107006622,
    276.3444145723779,
    260.96062247759096,
    322.0482304101894,
    282.2981869520948,
    264.07278891573264,
    249.87123780139706,
    293.74525203794286,
    282.5314622181063,
    287.97219506784495,
    246.23377298774707,
    299.8598139397111,
    288.07560524519306,
    261.8738389456337,
    281.18147775033276,
    302.65533684353534,
    312.3921067048974,
    311.760065022701,
    307.04430531936475,
    303.38883325878544,
    258.04183976238056,
    266.6516770549666,
    268.25669626956585,
    275.61005111290785,
    294.98414795492454,
    280.30759627046547,
    267.69980438302764,
    285.7275449079219,
    269.7341488631789,
    268.70347557131197,
    303.69181298455214,
    316.75635621002823,
    310.2379162247463,
    255.25770869985203,
    240.91714318593532,
    245.45154303917994,
    303.2757911077619,
    297.7405882859874],
   'episode_lengths': [196,
    217,
    242,
    207,
    250,
    232,
    217,
    247,
    226,
    209,
    223,
    200,
    210,
    155,
    204,
    260,
    220,
    213,
    194,
    198,
    229,
    194,
    245,
    227,
    234,
    227,
    227,
    204,
    211,
    223,
    208,
    205,
    207,
    203,
    195,
    258,
    204,
    204,
    202,
    192,
    239,
    199,
    214,
    200,
    222,
    219,
    207,
    205,
    220,
    220,
    220,
    221,
    208,
    235,
    234,
    221,
    226,
    255,
    209,
    225,
    212,
    210,
    212,
    203,
    230,
    217,
    233,
    239,
    216,
    232,
    215,
    227,
    208,
    229,
    217,
    228,
    241,
    225,
    260,
    247,
    236,
    212,
    208,
    234,
    210,
    218,
    214,
    211,
    201,
    234,
    199,
    213,
    236,
    261,
    260,
    222,
    222,
    233,
    217,
    221]},
  'current': {'mean_reward': 280.65702628540856,
   'std_reward': 34.31442136477228,
   'course_score': 246.3426049206363,
   'success_rate_200': 0.99,
   'mean_episode_length': 219.81,
   'min_reward': 4.306382930665833,
   'max_reward': 322.0482304101894,
   'n_episodes': 100,
   'rewards': [278.95682092028363,
    292.6435450729996,
    315.7611168805777,
    262.50190062260344,
    275.05531675423015,
    264.36260912031486,
    291.7210375695704,
    292.054123501242,
    259.0069320356084,
    304.2247635525612,
    310.2938162318376,
    303.26536872945724,
    296.7189655487642,
    4.306382930665833,
    280.2730755821684,
    264.7696430630234,
    253.6859047047289,
    293.93336211921866,
    279.45448816699536,
    259.5041331167257,
    298.69907094490657,
    308.87209646922054,
    268.05976633884904,
    252.97744485047184,
    303.53768777441405,
    274.1793127025521,
    244.16543420124435,
    279.4639273335066,
    265.1139628007316,
    277.8204773445916,
    288.1341154851691,
    260.9338659098198,
    302.88606672342837,
    295.59006566316714,
    297.49419068926204,
    303.30836189169446,
    291.65619564782594,
    276.4117666401064,
    292.38157894708854,
    295.9492409461043,
    302.3744866045082,
    288.79437913979916,
    284.0999809627908,
    305.866138448255,
    280.56513753580043,
    308.4118098638436,
    269.99630191080314,
    301.11921407511545,
    280.2782188151149,
    314.69308141477916,
    296.7096455991543,
    311.56442100385414,
    254.9051206306109,
    289.79610053969225,
    269.3693334796875,
    283.52956915509185,
    243.23127162823496,
    312.76672710166997,
    266.75508056779125,
    251.84540846309207,
    260.10599997745464,
    309.1370670354429,
    276.3048107006622,
    276.3444145723779,
    260.96062247759096,
    322.0482304101894,
    282.2981869520948,
    264.07278891573264,
    249.87123780139706,
    293.74525203794286,
    282.5314622181063,
    287.97219506784495,
    246.23377298774707,
    299.8598139397111,
    288.07560524519306,
    261.8738389456337,
    281.18147775033276,
    302.65533684353534,
    312.3921067048974,
    311.760065022701,
    307.04430531936475,
    303.38883325878544,
    258.04183976238056,
    266.6516770549666,
    268.25669626956585,
    275.61005111290785,
    294.98414795492454,
    280.30759627046547,
    267.69980438302764,
    285.7275449079219,
    269.7341488631789,
    268.70347557131197,
    303.69181298455214,
    316.75635621002823,
    310.2379162247463,
    255.25770869985203,
    240.91714318593532,
    245.45154303917994,
    303.2757911077619,
    297.7405882859874],
   'episode_lengths': [196,
    217,
    242,
    207,
    250,
    232,
    217,
    247,
    226,
    209,
    223,
    200,
    210,
    155,
    204,
    260,
    220,
    213,
    194,
    198,
    229,
    194,
    245,
    227,
    234,
    227,
    227,
    204,
    211,
    223,
    208,
    205,
    207,
    203,
    195,
    258,
    204,
    204,
    202,
    192,
    239,
    199,
    214,
    200,
    222,
    219,
    207,
    205,
    220,
    220,
    220,
    221,
    208,
    235,
    234,
    221,
    226,
    255,
    209,
    225,
    212,
    210,
    212,
    203,
    230,
    217,
    233,
    239,
    216,
    232,
    215,
    227,
    208,
    229,
    217,
    228,
    241,
    225,
    260,
    247,
    236,
    212,
    208,
    234,
    210,
    218,
    214,
    211,
    201,
    234,
    199,
    213,
    236,
    261,
    260,
    222,
    222,
    233,
    217,
    221]},
  'current_model_path': '/root/.cache/huggingface/hub/models--KaptainKris--HuggingFace_RL_Course/snapshots/bf1b1e59a75563b47119f1409e1bfcb03a3b6eb5/ppo-LunarLander-v3.zip',
  'selection_metric': 'mean_reward',
  'min_improvement': 1.0,
  'improvement': 0.0,
  'candidate_is_better': False,
  'table':              mean_reward  std_reward  course_score  success_rate_200  \
  model
  candidate     280.657026   34.314421    246.342605              0.99
  current_hub   280.657026   34.314421    246.342605              0.99

               mean_episode_length  min_reward  max_reward  n_episodes
  model
  candidate                 219.81    4.306383   322.04823         100
  current_hub               219.81    4.306383   322.04823         100  }}

#### Preview generated video locally

In [12]:
replay_path = (
    promotion_128["staging_dir"]
    / "replay.mp4"
)

display(
    Video(
        str(replay_path),
        embed=True,
    )
)

#### Local backup

In [ ]:
from google.colab import files

files.download(
    str(run_128["best_model_path"])
)

## Flip model

The plan for this model is to have the same architecture as before, but to change the environment's reward function to reward doing a full 360 degree flip before landing safely.

### Reward wrapper

In [19]:
%%writefile /content/flip_landing_reward_wrapper_v2.py

from __future__ import annotations

import math

import gymnasium as gym
import numpy as np


DEFAULT_REWARD_CONFIG = {
    "flip_landing_bonus": 750.0,
    "rotation_progress_bonus": 150.0,
    "flip_completion_bonus": 200.0,
    "recovery_bonus": 100.0,
    "no_flip_terminal_penalty": 0.0,
    "failed_landing_penalty": 150.0,
    "required_rotations": 1.0,
    "upright_tolerance_radians": 0.30,
    "recovery_angular_velocity_tolerance": 0.50,
    "pre_flip_original_reward_weight": 0.25,
    "post_flip_original_reward_weight": 1.0,
    "post_flip_shaping_weight": 1.0,
    "post_flip_shaping_gamma": 0.995,
    "post_flip_shaping_clip": 10.0,
    "post_flip_center_weight": 50.0,
    "post_flip_horizontal_speed_weight": 30.0,
    "post_flip_angle_weight": 20.0,
    "post_flip_angular_speed_weight": 10.0,
    "post_flip_leg_contact_weight": 10.0,
    "rotation_direction": 1,
}


class FlipLandingRewardWrapper(gym.Wrapper):
    """
    Stage-aware LunarLander objective:

    1. Complete one full rotation in the selected direction.
    2. Arrest the spin and recover to an upright attitude.
    3. Re-centre, stabilise and land safely.

    The original eight-value observation is extended with:
    - signed rotation progress in [-1, 1];
    - a flip-completed flag;
    - a post-flip-recovery-completed flag.

    Post-flip recovery uses a potential-difference reward based on
    horizontal position, horizontal speed, attitude, angular speed,
    and leg contact. This rewards improvement rather than repeatedly
    paying the agent simply for occupying a favourable state.
    """

    def __init__(
        self,
        env: gym.Env,
        *,
        flip_landing_bonus: float = 750.0,
        rotation_progress_bonus: float = 150.0,
        flip_completion_bonus: float = 200.0,
        recovery_bonus: float = 100.0,
        no_flip_terminal_penalty: float = 0.0,
        failed_landing_penalty: float = 150.0,
        required_rotations: float = 1.0,
        upright_tolerance_radians: float = 0.30,
        recovery_angular_velocity_tolerance: float = 0.50,
        pre_flip_original_reward_weight: float = 0.25,
        post_flip_original_reward_weight: float = 1.0,
        post_flip_shaping_weight: float = 1.0,
        post_flip_shaping_gamma: float = 0.995,
        post_flip_shaping_clip: float = 10.0,
        post_flip_center_weight: float = 50.0,
        post_flip_horizontal_speed_weight: float = 30.0,
        post_flip_angle_weight: float = 20.0,
        post_flip_angular_speed_weight: float = 10.0,
        post_flip_leg_contact_weight: float = 10.0,
        rotation_direction: int = 1,
    ):
        super().__init__(env)

        if required_rotations <= 0:
            raise ValueError("required_rotations must be positive.")

        if rotation_direction not in (-1, 1):
            raise ValueError(
                "rotation_direction must be either -1 or 1."
            )

        if not 0.0 <= post_flip_shaping_gamma <= 1.0:
            raise ValueError(
                "post_flip_shaping_gamma must be in [0, 1]."
            )

        if post_flip_shaping_clip <= 0:
            raise ValueError(
                "post_flip_shaping_clip must be positive."
            )

        self.flip_landing_bonus = float(flip_landing_bonus)
        self.rotation_progress_bonus = float(
            rotation_progress_bonus
        )
        self.flip_completion_bonus = float(
            flip_completion_bonus
        )
        self.recovery_bonus = float(recovery_bonus)
        self.no_flip_terminal_penalty = float(
            no_flip_terminal_penalty
        )
        self.failed_landing_penalty = float(
            failed_landing_penalty
        )

        self.required_rotation = (
            2.0 * math.pi * float(required_rotations)
        )
        self.required_rotations = float(required_rotations)
        self.upright_tolerance_radians = float(
            upright_tolerance_radians
        )
        self.recovery_angular_velocity_tolerance = float(
            recovery_angular_velocity_tolerance
        )

        self.pre_flip_original_reward_weight = float(
            pre_flip_original_reward_weight
        )
        self.post_flip_original_reward_weight = float(
            post_flip_original_reward_weight
        )

        self.post_flip_shaping_weight = float(
            post_flip_shaping_weight
        )
        self.post_flip_shaping_gamma = float(
            post_flip_shaping_gamma
        )
        self.post_flip_shaping_clip = float(
            post_flip_shaping_clip
        )
        self.post_flip_center_weight = float(
            post_flip_center_weight
        )
        self.post_flip_horizontal_speed_weight = float(
            post_flip_horizontal_speed_weight
        )
        self.post_flip_angle_weight = float(
            post_flip_angle_weight
        )
        self.post_flip_angular_speed_weight = float(
            post_flip_angular_speed_weight
        )
        self.post_flip_leg_contact_weight = float(
            post_flip_leg_contact_weight
        )

        self.rotation_direction = int(rotation_direction)

        self.previous_angle = 0.0
        self.cumulative_rotation = 0.0
        self.maximum_rotation_progress = 0.0
        self.flip_completed = False
        self.recovery_completed = False
        self.previous_post_flip_potential: float | None = None

        base_space = env.observation_space

        if not isinstance(base_space, gym.spaces.Box):
            raise TypeError(
                "The wrapped environment must have a Box "
                "observation space."
            )

        extra_low = np.asarray(
            [-1.0, 0.0, 0.0],
            dtype=np.float32,
        )
        extra_high = np.asarray(
            [1.0, 1.0, 1.0],
            dtype=np.float32,
        )

        self.observation_space = gym.spaces.Box(
            low=np.concatenate(
                [
                    base_space.low.astype(np.float32),
                    extra_low,
                ]
            ),
            high=np.concatenate(
                [
                    base_space.high.astype(np.float32),
                    extra_high,
                ]
            ),
            dtype=np.float32,
        )

    @staticmethod
    def _wrap_angle(angle: float) -> float:
        """Wrap an angle to [-pi, pi]."""

        return float(
            np.arctan2(
                np.sin(angle),
                np.cos(angle),
            )
        )

    def _signed_rotation_progress(self) -> float:
        return float(
            np.clip(
                self.cumulative_rotation
                / self.required_rotation,
                -1.0,
                1.0,
            )
        )

    def _augment_observation(
        self,
        observation: np.ndarray,
    ) -> np.ndarray:
        return np.concatenate(
            [
                np.asarray(
                    observation,
                    dtype=np.float32,
                ),
                np.asarray(
                    [
                        self._signed_rotation_progress(),
                        float(self.flip_completed),
                        float(self.recovery_completed),
                    ],
                    dtype=np.float32,
                ),
            ]
        )

    def _post_flip_potential(
        self,
        observation: np.ndarray,
    ) -> float:
        """
        Higher values represent safer post-flip states.

        LunarLander-v3 observation positions:
        0 x position, 2 x velocity, 4 angle, 5 angular velocity,
        6 left-leg contact and 7 right-leg contact.
        """

        x_position = float(observation[0])
        horizontal_speed = float(observation[2])
        angle = abs(
            self._wrap_angle(
                float(observation[4])
            )
        )
        angular_speed = abs(float(observation[5]))
        leg_contacts = float(observation[6] > 0.5) + float(
            observation[7] > 0.5
        )

        return float(
            -self.post_flip_center_weight
            * abs(x_position)
            -self.post_flip_horizontal_speed_weight
            * abs(horizontal_speed)
            -self.post_flip_angle_weight
            * angle
            -self.post_flip_angular_speed_weight
            * angular_speed
            +self.post_flip_leg_contact_weight
            * leg_contacts
        )

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict | None = None,
    ):
        observation, info = self.env.reset(
            seed=seed,
            options=options,
        )

        self.previous_angle = float(observation[4])
        self.cumulative_rotation = 0.0
        self.maximum_rotation_progress = 0.0
        self.flip_completed = False
        self.recovery_completed = False
        self.previous_post_flip_potential = None

        info = dict(info)
        info.update(
            {
                "flip_completed": False,
                "recovery_completed": False,
                "rotation_progress": 0.0,
                "rotations_completed": 0.0,
                "rotation_progress_reward": 0.0,
                "flip_completion_reward": 0.0,
                "recovery_reward": 0.0,
                "post_flip_shaping_reward": 0.0,
                "flip_landing_bonus": 0.0,
                "terminal_adjustment": 0.0,
            }
        )

        return self._augment_observation(observation), info

    def step(self, action):
        (
            observation,
            original_reward,
            terminated,
            truncated,
            info,
        ) = self.env.step(action)

        current_angle = float(observation[4])
        angular_velocity = float(observation[5])

        angle_change = self._wrap_angle(
            current_angle - self.previous_angle
        )
        self.previous_angle = current_angle

        directed_change = (
            self.rotation_direction * angle_change
        )
        self.cumulative_rotation += directed_change

        rotation_progress = float(
            np.clip(
                self.cumulative_rotation
                / self.required_rotation,
                0.0,
                1.0,
            )
        )

        new_progress = max(
            0.0,
            rotation_progress
            - self.maximum_rotation_progress,
        )
        progress_reward = (
            self.rotation_progress_bonus
            * new_progress
        )
        self.maximum_rotation_progress = max(
            self.maximum_rotation_progress,
            rotation_progress,
        )

        completion_reward = 0.0

        if (
            rotation_progress >= 1.0
            and not self.flip_completed
        ):
            self.flip_completed = True
            completion_reward = (
                self.flip_completion_bonus
            )

        wrapped_angle = abs(
            self._wrap_angle(current_angle)
        )
        upright = (
            wrapped_angle
            <= self.upright_tolerance_radians
        )

        recovery_reward = 0.0

        if (
            self.flip_completed
            and not self.recovery_completed
            and upright
            and abs(angular_velocity)
            <= self.recovery_angular_velocity_tolerance
        ):
            self.recovery_completed = True
            recovery_reward = self.recovery_bonus

        post_flip_shaping_reward = 0.0
        post_flip_potential = None

        if self.flip_completed:
            post_flip_potential = (
                self._post_flip_potential(observation)
            )

            if self.previous_post_flip_potential is None:
                self.previous_post_flip_potential = (
                    post_flip_potential
                )
            else:
                potential_difference = (
                    self.post_flip_shaping_gamma
                    * post_flip_potential
                    - self.previous_post_flip_potential
                )
                post_flip_shaping_reward = float(
                    np.clip(
                        self.post_flip_shaping_weight
                        * potential_difference,
                        -self.post_flip_shaping_clip,
                        self.post_flip_shaping_clip,
                    )
                )
                self.previous_post_flip_potential = (
                    post_flip_potential
                )

        left_leg_contact = bool(observation[6] > 0.5)
        right_leg_contact = bool(observation[7] > 0.5)

        landed_safely = bool(
            terminated
            and float(original_reward) > 0
            and left_leg_contact
            and right_leg_contact
            and upright
        )

        episode_finished = bool(
            terminated or truncated
        )

        terminal_adjustment = 0.0
        outcome = "in_progress"

        if self.flip_completed and landed_safely:
            terminal_adjustment = self.flip_landing_bonus
            outcome = "flip_and_safe_landing"
        elif episode_finished:
            if not self.flip_completed:
                terminal_adjustment = -(
                    self.no_flip_terminal_penalty
                )
                outcome = "episode_ended_without_flip"
            else:
                terminal_adjustment = -(
                    self.failed_landing_penalty
                )
                outcome = "flip_but_failed_landing"

        original_weight = (
            self.post_flip_original_reward_weight
            if self.flip_completed
            else self.pre_flip_original_reward_weight
        )

        modified_reward = (
            original_weight * float(original_reward)
            + progress_reward
            + completion_reward
            + recovery_reward
            + post_flip_shaping_reward
            + terminal_adjustment
        )

        info = dict(info)
        info.update(
            {
                "original_reward": float(original_reward),
                "rotation_progress": rotation_progress,
                "rotation_progress_reward": progress_reward,
                "flip_completion_reward": completion_reward,
                "recovery_reward": recovery_reward,
                "post_flip_shaping_reward": (
                    post_flip_shaping_reward
                ),
                "post_flip_potential": post_flip_potential,
                "cumulative_rotation": (
                    self.cumulative_rotation
                ),
                "rotations_completed": (
                    self.cumulative_rotation
                    / (2.0 * math.pi)
                ),
                "flip_completed": self.flip_completed,
                "recovery_completed": (
                    self.recovery_completed
                ),
                "landed_safely": landed_safely,
                "original_reward_weight": original_weight,
                "terminal_adjustment": (
                    terminal_adjustment
                ),
                "flip_landing_bonus": (
                    self.flip_landing_bonus
                    if outcome
                    == "flip_and_safe_landing"
                    else 0.0
                ),
                "custom_outcome": outcome,
            }
        )

        return (
            self._augment_observation(observation),
            modified_reward,
            terminated,
            truncated,
            info,
        )


def make_flip_lander(
    *,
    render_mode: str | None = None,
    reward_config: dict | None = None,
) -> gym.Env:
    """
    Build the exact environment used for training and evaluation.

    Pass the same reward_config to the uploader so the Hub model card
    records the environment accurately.
    """

    config = {
        **DEFAULT_REWARD_CONFIG,
        **(reward_config or {}),
    }

    base_env = gym.make(
        "LunarLander-v3",
        render_mode=render_mode,
    )

    return FlipLandingRewardWrapper(
        base_env,
        **config,
    )

Overwriting /content/flip_landing_reward_wrapper_v2.py

In [20]:
from copy import deepcopy
from pathlib import Path
import importlib

import flip_landing_reward_wrapper_v2 as flip_wrapper

# Important when the module has previously been imported in this runtime.
importlib.reload(flip_wrapper)

DEFAULT_REWARD_CONFIG = (
    flip_wrapper.DEFAULT_REWARD_CONFIG
)
FlipLandingRewardWrapper = (
    flip_wrapper.FlipLandingRewardWrapper
)
make_flip_lander = (
    flip_wrapper.make_flip_lander
)

REWARD_WRAPPER_PATH = Path(
    "/content/flip_landing_reward_wrapper_v2.py"
)

reward_config = deepcopy(
    DEFAULT_REWARD_CONFIG
)

reward_config[
    "post_flip_shaping_gamma"
] = 0.999


def make_flip_lander_v2(
    *,
    render_mode: str | None = None,
):
    return make_flip_lander(
        render_mode=render_mode,
        reward_config=reward_config,
    )

### Upload checkpoint to HuggingFace

In [21]:
from pathlib import Path

from huggingface_hub import HfApi
from stable_baselines3.common.callbacks import (
    BaseCallback,
)


class HubCheckpointCallback(
    BaseCallback
):
    def __init__(
        self,
        *,
        repo_id: str,
        every_timesteps: int = 1_000_000,
        verbose: int = 1,
    ):
        super().__init__(verbose)

        self.repo_id = repo_id
        self.every_timesteps = int(
            every_timesteps
        )
        self.next_upload = int(
            every_timesteps
        )
        self.api = HfApi()

        self.local_path = Path(
            "/content/"
            "latest_flip_checkpoint.zip"
        )

    def _on_step(self) -> bool:
        if (
            self.num_timesteps
            < self.next_upload
        ):
            return True

        step = int(
            self.num_timesteps
        )

        self.model.save(
            str(self.local_path)
        )

        self.api.upload_file(
            path_or_fileobj=str(
                self.local_path
            ),
            path_in_repo=(
                "training-checkpoints/"
                f"ppo_flip_{step}_steps.zip"
            ),
            repo_id=self.repo_id,
            repo_type="model",
            commit_message=(
                f"Save training checkpoint "
                f"at {step:,} steps"
            ),
        )

        if self.verbose:
            print(
                "Uploaded Hub checkpoint:",
                f"{step:,} steps",
            )

        while (
            self.next_upload
            <= step
        ):
            self.next_upload += (
                self.every_timesteps
            )

        return True

### Training function

In [22]:
# New training function
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any
import json

import gymnasium as gym

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    EvalCallback,
)
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor


def train_ppo_experiment(
    *,
    experiment_name: str,
    total_timesteps: int,
    env_id: str = "LunarLander-v3",
    env_factory: Callable[[], gym.Env] | None = None,
    env_kwargs: dict[str, Any] | None = None,
    n_envs: int = 16,
    seed: int = 42,
    actor_layers: Sequence[int] = (64, 64),
    critic_layers: Sequence[int] = (64, 64),
    learning_rate: float = 3e-4,
    n_steps: int = 1024,
    batch_size: int = 64,
    n_epochs: int = 4,
    gamma: float = 0.999,
    gae_lambda: float = 0.98,
    ent_coef: float = 0.01,
    clip_range: float = 0.2,
    eval_every_timesteps: int = 50_000,
    checkpoint_every_timesteps: int = 100_000,
    n_eval_episodes: int = 20,
    output_root: str | Path = "/content/rl-experiments",
    device: str = "cpu",
    verbose: int = 1,
    extra_callbacks: Sequence[
        BaseCallback
    ] | None = None,
) -> dict[str, Any]:
    """
    Train a PPO actor–critic model.

    env_factory
        Optional callable that returns a custom Gymnasium environment.
        Use this for the flip-reward environment.

    The function saves:
    - periodic safety checkpoints;
    - the checkpoint with the highest evaluation mean;
    - the model from the final training timestep;
    - the complete training configuration.
    """

    if not experiment_name.strip():
        raise ValueError(
            "experiment_name must not be empty."
        )

    if total_timesteps <= 0:
        raise ValueError(
            "total_timesteps must be positive."
        )

    if n_envs <= 0:
        raise ValueError(
            "n_envs must be positive."
        )

    env_kwargs = dict(env_kwargs or {})

    if env_factory is not None and env_kwargs:
        raise ValueError(
            "Use either env_factory or env_kwargs, not both. "
            "Put custom environment arguments inside the factory."
        )

    output_dir = (
        Path(output_root)
        / experiment_name
    )
    best_model_dir = (
        output_dir
        / "best_model"
    )
    checkpoint_dir = (
        output_dir
        / "checkpoints"
    )
    evaluation_dir = (
        output_dir
        / "evaluations"
    )

    for directory in (
        best_model_dir,
        checkpoint_dir,
        evaluation_dir,
    ):
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    configuration = {
        "experiment_name": experiment_name,
        "env_id": env_id,
        "environment_factory": (
            getattr(
                env_factory,
                "__name__",
                None,
            )
            if env_factory is not None
            else None
        ),
        "env_kwargs": env_kwargs,
        "total_timesteps": total_timesteps,
        "n_envs": n_envs,
        "seed": seed,
        "actor_layers": list(actor_layers),
        "critic_layers": list(critic_layers),
        "learning_rate": learning_rate,
        "n_steps": n_steps,
        "batch_size": batch_size,
        "n_epochs": n_epochs,
        "gamma": gamma,
        "gae_lambda": gae_lambda,
        "ent_coef": ent_coef,
        "clip_range": clip_range,
        "eval_every_timesteps": (
            eval_every_timesteps
        ),
        "checkpoint_every_timesteps": (
            checkpoint_every_timesteps
        ),
        "n_eval_episodes": n_eval_episodes,
        "device": device,
    }

    config_path = (
        output_dir
        / "training_config.json"
    )

    config_path.write_text(
        json.dumps(
            configuration,
            indent=2,
        ),
        encoding="utf-8",
    )

    # Create standard or customised environments.
    if env_factory is None:
        train_env = make_vec_env(
            env_id,
            n_envs=n_envs,
            seed=seed,
            env_kwargs=env_kwargs,
        )

        eval_env = Monitor(
            gym.make(
                env_id,
                **env_kwargs,
            )
        )

    else:
        train_env = make_vec_env(
            env_factory,
            n_envs=n_envs,
            seed=seed,
        )

        eval_env = Monitor(
            env_factory()
        )

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=str(
            best_model_dir
        ),
        log_path=str(
            evaluation_dir
        ),
        eval_freq=max(
            eval_every_timesteps // n_envs,
            1,
        ),
        n_eval_episodes=n_eval_episodes,
        deterministic=True,
        render=False,
        verbose=1,
    )

    checkpoint_callback = CheckpointCallback(
        save_freq=max(
            checkpoint_every_timesteps // n_envs,
            1,
        ),
        save_path=str(
            checkpoint_dir
        ),
        name_prefix=experiment_name,
        verbose=2,
    )

    policy_kwargs = {
        "net_arch": {
            "pi": list(actor_layers),
            "vf": list(critic_layers),
        }
    }

    model = PPO(
        policy="MlpPolicy",
        env=train_env,
        learning_rate=learning_rate,
        n_steps=n_steps,
        batch_size=batch_size,
        n_epochs=n_epochs,
        gamma=gamma,
        gae_lambda=gae_lambda,
        ent_coef=ent_coef,
        clip_range=clip_range,
        policy_kwargs=policy_kwargs,
        device=device,
        seed=seed,
        verbose=verbose,
    )

    try:
        model.learn(
            total_timesteps=total_timesteps,
            callback=[
                eval_callback,
                checkpoint_callback,
            ],
            progress_bar=True,
        )

        final_model_stem = (
            output_dir
            / "final_model"
        )

        model.save(
            str(final_model_stem)
        )

    finally:
        train_env.close()
        eval_env.close()

    best_model_path = (
        best_model_dir
        / "best_model.zip"
    )
    final_model_path = (
        output_dir
        / "final_model.zip"
    )
    evaluations_path = (
        evaluation_dir
        / "evaluations.npz"
    )

    if not best_model_path.exists():
        raise FileNotFoundError(
            "EvalCallback did not create best_model.zip. "
            "Check that training reached at least one "
            "evaluation interval."
        )

    print("Best model:", best_model_path)
    print("Final model:", final_model_path)
    print("Configuration:", config_path)

    return {
        "experiment_name": experiment_name,
        "output_dir": output_dir,
        "best_model_path": best_model_path,
        "final_model_path": final_model_path,
        "evaluations_path": evaluations_path,
        "config_path": config_path,
        "configuration": configuration,
    }

### Train model

In [23]:
from huggingface_hub import notebook_login

notebook_login()

In [24]:
# Clean progress display
from rich import get_console

console = get_console()

# Rich versions that store a single active display.
active_live = getattr(console, "_live", None)

if active_live is not None:
    try:
        active_live.stop()
    except Exception:
        try:
            console.clear_live()
        except Exception:
            pass

# Newer Rich versions that store a stack of displays.
live_stack = getattr(console, "_live_stack", None)

if live_stack:
    while live_stack:
        active_live = live_stack[-1]

        try:
            active_live.stop()
        except Exception:
            try:
                console.clear_live()
            except Exception:
                break

print("Rich live display cleared.")

Rich live display cleared.

In [25]:
hub_checkpoint_callback = (
    HubCheckpointCallback(
        repo_id=(
            "KaptainKris92/"
            "ppo-LunarLander-v3-flip"
        ),
        every_timesteps=1_000_000,
    )
)

In [26]:
flip_run = train_ppo_experiment(
    experiment_name="ppo_lunarlander_flip",
    total_timesteps=15_000_000,

    env_factory=make_flip_lander_v2,

    n_envs=16,
    seed=42,

    actor_layers=(64, 64),
    critic_layers=(64, 64),

    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    n_epochs=4,
    gamma=0.999,
    gae_lambda=0.98,
    ent_coef=0.03,
    clip_range=0.2,

    eval_every_timesteps=50_000,
    checkpoint_every_timesteps=100_000,
    n_eval_episodes=20,

    device="cpu",

    extra_callbacks=[
        hub_checkpoint_callback
    ],
)

 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15,007,568/15,000,000  [ 3:04:07 < 0:00:00 , 680 it/s ]

Best model: /content/rl-experiments/ppo_lunarlander_flip/best_model/best_model.zip
Final model: /content/rl-experiments/ppo_lunarlander_flip/final_model.zip
Configuration: /content/rl-experiments/ppo_lunarlander_flip/training_config.json

### Evaluation function

In [27]:
import numpy as np
import pandas as pd


def evaluate_flip_model(
    model_or_path,
    *,
    reward_config: dict,
    n_episodes: int = 100,
    starting_seed: int = 20_000,
    deterministic: bool = True,
):
    """
    Evaluate the flip-recover-land agent over fixed seeds.
    """

    if n_episodes <= 0:
        raise ValueError(
            "n_episodes must be positive."
        )

    model = load_ppo_model(
        model_or_path
    )

    episode_rows = []

    for episode_number in range(
        n_episodes
    ):
        seed = (
            starting_seed
            + episode_number
        )

        env = make_flip_lander(
            reward_config=reward_config
        )

        try:
            observation, _ = env.reset(
                seed=seed
            )

            terminated = False
            truncated = False

            shaped_reward_total = 0.0
            original_reward_total = 0.0
            episode_steps = 0
            final_info = {}

            while not (
                terminated or truncated
            ):
                action, _ = model.predict(
                    observation,
                    deterministic=deterministic,
                )

                # LunarLander-v3 uses Discrete(4).
                action = int(
                    np.asarray(
                        action
                    ).item()
                )

                (
                    observation,
                    shaped_reward,
                    terminated,
                    truncated,
                    info,
                ) = env.step(action)

                shaped_reward_total += float(
                    shaped_reward
                )

                original_reward_total += float(
                    info.get(
                        "original_reward",
                        shaped_reward,
                    )
                )

                episode_steps += 1
                final_info = dict(info)

            flip_completed = bool(
                final_info.get(
                    "flip_completed",
                    False,
                )
            )

            recovery_completed = bool(
                final_info.get(
                    "recovery_completed",
                    False,
                )
            )

            landed_safely = bool(
                final_info.get(
                    "landed_safely",
                    False,
                )
            )

            custom_outcome = str(
                final_info.get(
                    "custom_outcome",
                    "unknown",
                )
            )

            flip_and_landed = (
                custom_outcome
                == "flip_and_safe_landing"
            )

            episode_rows.append(
                {
                    "seed": seed,
                    "shaped_reward": (
                        shaped_reward_total
                    ),
                    "original_reward": (
                        original_reward_total
                    ),
                    "steps": episode_steps,
                    "flip_completed": (
                        flip_completed
                    ),
                    "recovery_completed": (
                        recovery_completed
                    ),
                    "landed_safely": (
                        landed_safely
                    ),
                    "flip_and_landed": (
                        flip_and_landed
                    ),
                    "flip_bonus": float(
                        final_info.get(
                            "flip_landing_bonus",
                            0.0,
                        )
                    ),
                    "rotations_completed": float(
                        final_info.get(
                            "rotations_completed",
                            0.0,
                        )
                    ),
                    "terminal_adjustment": float(
                        final_info.get(
                            "terminal_adjustment",
                            0.0,
                        )
                    ),
                    "custom_outcome": (
                        custom_outcome
                    ),
                }
            )

        finally:
            env.close()

    episodes = pd.DataFrame(
        episode_rows
    )

    shaped_rewards = episodes[
        "shaped_reward"
    ].to_numpy(dtype=float)

    original_rewards = episodes[
        "original_reward"
    ].to_numpy(dtype=float)

    flip_mask = episodes[
        "flip_completed"
    ]

    if flip_mask.any():
        recovery_given_flip_rate = float(
            episodes.loc[
                flip_mask,
                "recovery_completed",
            ].mean()
        )

        landing_given_flip_rate = float(
            episodes.loc[
                flip_mask,
                "flip_and_landed",
            ].mean()
        )
    else:
        recovery_given_flip_rate = 0.0
        landing_given_flip_rate = 0.0

    summary = {
        "n_episodes": int(n_episodes),

        "mean_shaped_reward": float(
            shaped_rewards.mean()
        ),
        "std_shaped_reward": float(
            shaped_rewards.std()
        ),
        "shaped_course_score": float(
            shaped_rewards.mean()
            - shaped_rewards.std()
        ),
        "min_shaped_reward": float(
            shaped_rewards.min()
        ),
        "max_shaped_reward": float(
            shaped_rewards.max()
        ),

        "mean_original_reward": float(
            original_rewards.mean()
        ),
        "std_original_reward": float(
            original_rewards.std()
        ),
        "original_course_score": float(
            original_rewards.mean()
            - original_rewards.std()
        ),
        "min_original_reward": float(
            original_rewards.min()
        ),
        "max_original_reward": float(
            original_rewards.max()
        ),

        "original_reward_200_rate": float(
            np.mean(
                original_rewards >= 200.0
            )
        ),
        "flip_completion_rate": float(
            episodes[
                "flip_completed"
            ].mean()
        ),
        "recovery_completion_rate": float(
            episodes[
                "recovery_completed"
            ].mean()
        ),
        "recovery_given_flip_rate": (
            recovery_given_flip_rate
        ),
        "safe_landing_rate": float(
            episodes[
                "landed_safely"
            ].mean()
        ),
        "flip_landing_rate": float(
            episodes[
                "flip_and_landed"
            ].mean()
        ),
        "landing_given_flip_rate": (
            landing_given_flip_rate
        ),
    }

    print("Flip model evaluation")
    print("---------------------")
    print(
        "Mean shaped reward:",
        f"{summary['mean_shaped_reward']:.2f}",
    )
    print(
        "Mean original reward:",
        f"{summary['mean_original_reward']:.2f}",
    )
    print(
        "Completed a full rotation:",
        f"{summary['flip_completion_rate']:.1%}",
    )
    print(
        "Recovered after the flip:",
        f"{summary['recovery_completion_rate']:.1%}",
    )
    print(
        "Recovery rate given a flip:",
        f"{summary['recovery_given_flip_rate']:.1%}",
    )
    print(
        "Landed safely:",
        f"{summary['safe_landing_rate']:.1%}",
    )
    print(
        "Flipped and landed safely:",
        f"{summary['flip_landing_rate']:.1%}",
    )
    print(
        "Landing rate given a flip:",
        f"{summary['landing_given_flip_rate']:.1%}",
    )

    return {
        "summary": summary,
        "episodes": episodes,
    }

### Evaluate model

In [28]:
selected_model_path = Path(
    flip_run["best_model_path"]
)

flip_evaluation = evaluate_flip_model(
    selected_model_path,
    reward_config=reward_config,
    n_episodes=100,
    starting_seed=20_000,
)

display(
    pd.Series(
        flip_evaluation["summary"],
        name="Flip model",
    )
)

# Episode-level inspection
display(
    flip_evaluation["episodes"]
    .sort_values(
        [
            "flip_and_landed",
            "original_reward",
        ],
        ascending=False,
    )
    .head(20)
)

Flip model evaluation
---------------------
Mean shaped reward: 79.77
Mean original reward: 255.69
Completed a full rotation: 0.0%
Recovered after the flip: 0.0%
Recovery rate given a flip: 0.0%
Landed safely: 82.0%
Flipped and landed safely: 0.0%
Landing rate given a flip: 0.0%

n_episodes                  100.000000
mean_shaped_reward           79.774044
std_shaped_reward            17.942668
shaped_course_score          61.831377
min_shaped_reward            13.327244
max_shaped_reward           104.632743
mean_original_reward        255.693295
std_original_reward          88.322195
original_course_score       167.371100
min_original_reward        -139.815208
max_original_reward         321.217874
original_reward_200_rate      0.880000
flip_completion_rate          0.000000
recovery_completion_rate      0.000000
recovery_given_flip_rate      0.000000
safe_landing_rate             0.820000
flip_landing_rate             0.000000
landing_given_flip_rate       0.000000
Name: Flip model, dtype: float64

,seed,shaped_reward,original_reward,steps,flip_completed,recovery_completed,landed_safely,flip_and_landed,flip_bonus,rotations_completed,terminal_adjustment,custom_outcome
59,20059,103.322336,321.217874,253,False,False,True,False,0.0,-0.001824,-0.0,episode_ended_without_flip
40,20040,99.733086,316.511954,245,False,False,True,False,0.0,-0.001952,-0.0,episode_ended_without_flip
17,20017,104.632743,314.043938,242,False,False,True,False,0.0,-0.001084,-0.0,episode_ended_without_flip
1,20001,96.046611,314.043698,230,False,False,True,False,0.0,-0.000752,-0.0,episode_ended_without_flip
52,20052,98.727986,313.994368,255,False,False,True,False,0.0,-0.001719,-0.0,episode_ended_without_flip
92,20092,101.234974,313.745613,261,False,False,True,False,0.0,-0.001355,-0.0,episode_ended_without_flip
85,20085,97.278570,311.845924,214,False,False,True,False,0.0,-0.000127,-0.0,episode_ended_without_flip
55,20055,101.861607,309.460364,231,False,False,True,False,0.0,-0.001586,-0.0,episode_ended_without_flip
80,20080,102.054389,309.023262,229,False,False,True,False,0.0,-0.001742,-0.0,episode_ended_without_flip
44,20044,95.160997,307.690321,220,False,False,True,False,0.0,-0.001552,-0.0,episode_ended_without_flip
16,20016,99.505751,307.530523,217,False,False,True,False,0.0,-0.002466,-0.0,episode_ended_without_flip
88,20088,84.863689,303.047029,209,False,False,True,False,0.0,0.002043,-0.0,episode_ended_without_flip
60,20060,84.463191,302.833137,219,False,False,True,False,0.0,0.001316,-0.0,episode_ended_without_flip
43,20043,90.504640,302.336654,230,False,False,True,False,0.0,-0.000755,-0.0,episode_ended_without_flip
34,20034,97.375870,302.228668,223,False,False,True,False,0.0,-0.001346,-0.0,episode_ended_without_flip
53,20053,97.683311,301.028581,232,False,False,True,False,0.0,-0.001628,-0.0,episode_ended_without_flip
3,20003,80.864889,299.904395,191,False,False,True,False,0.0,0.000947,-0.0,episode_ended_without_flip
9,20009,81.173137,299.753790,182,False,False,True,False,0.0,0.001717,-0.0,episode_ended_without_flip
0,20000,83.837891,299.528063,202,False,False,True,False,0.0,0.000882,-0.0,episode_ended_without_flip
7,20007,100.777110,299.469396,262,False,False,True,False,0.0,-0.000130,-0.0,episode_ended_without_flip

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

### Video of best episode

In [ ]:
episode_results = (
    flip_evaluation["episodes"]
)

successful_flip_landings = (
    episode_results[
        episode_results[
            "flip_and_landed"
        ]
    ]
    .copy()
)

if successful_flip_landings.empty:
    video_seed = int(
        episode_results
        .sort_values(
            "shaped_reward",
            ascending=False,
        )
        .iloc[0]["seed"]
    )

    print(
        "No successful flip-and-land episode "
        "was found in the evaluation sample."
    )
    print(
        "Using the highest shaped-reward "
        "episode instead."
    )

else:
    video_seed = int(
        successful_flip_landings
        .sort_values(
            "original_reward",
            ascending=False,
        )
        .iloc[0]["seed"]
    )

    print(
        "Selected the successful flip-and-land "
        "episode with the highest original reward."
    )

print("Selected video seed:", video_seed)

In [ ]:
from pathlib import Path
import shutil

import gymnasium as gym


def record_flip_replay(
    model_or_path,
    *,
    output_path: str | Path,
    seed: int,
    reward_config: dict,
    deterministic: bool = True,
):
    """
    Record one complete episode from the custom flip environment.
    """

    model = load_ppo_model(
        model_or_path
    )

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_directory = (
        output_path.parent
        / "_flip_video_recording"
    )

    if temporary_directory.exists():
        shutil.rmtree(
            temporary_directory
        )

    temporary_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    video_env = make_flip_lander(
        render_mode="rgb_array",
        reward_config=reward_config,
    )

    video_env = gym.wrappers.RecordVideo(
        video_env,
        video_folder=str(
            temporary_directory
        ),
        episode_trigger=(
            lambda episode_number:
            episode_number == 0
        ),
        video_length=0,
        name_prefix=(
            "ppo-lunarlander-flip"
        ),
        disable_logger=True,
    )

    shaped_reward_total = 0.0
    original_reward_total = 0.0
    episode_steps = 0

    final_info = {}

    try:
        observation, info = video_env.reset(
            seed=int(seed)
        )

        terminated = False
        truncated = False

        while not (
            terminated or truncated
        ):
            action, _ = model.predict(
                observation,
                deterministic=deterministic,
            )

            action = int(
                np.asarray(
                    action
                ).item()
            )

            (
                observation,
                shaped_reward,
                terminated,
                truncated,
                info,
            ) = video_env.step(action)

            shaped_reward_total += float(
                shaped_reward
            )

            original_reward_total += float(
                info.get(
                    "original_reward",
                    shaped_reward,
                )
            )

            episode_steps += 1
            final_info = dict(info)

    finally:
        video_env.close()

    generated_videos = list(
        temporary_directory.glob(
            "*.mp4"
        )
    )

    if not generated_videos:
        raise FileNotFoundError(
            "Gymnasium did not generate "
            "an MP4 replay."
        )

    generated_video = max(
        generated_videos,
        key=lambda path:
        path.stat().st_mtime,
    )

    shutil.copy2(
        generated_video,
        output_path,
    )

    shutil.rmtree(
        temporary_directory,
        ignore_errors=True,
    )

    replay_details = {
        "path": str(output_path),
        "seed": int(seed),
        "shaped_reward": float(
            shaped_reward_total
        ),
        "original_reward": float(
            original_reward_total
        ),
        "steps": int(
            episode_steps
        ),
        "flip_completed": bool(
            final_info.get(
                "flip_completed",
                False,
            )
        ),
        "landed_safely": bool(
            final_info.get(
                "landed_safely",
                False,
            )
        ),
        "rotations_completed": float(
            final_info.get(
                "rotations_completed",
                0.0,
            )
        ),
        "recovery_completed": bool(
            final_info.get(
                "recovery_completed",
                False,
            )
        ),
        "custom_outcome": str(
            final_info.get(
                "custom_outcome",
                "unknown",
            )
        ),
        "flip_and_landed": (
            final_info.get(
                "custom_outcome"
            )
            == "flip_and_safe_landing"
        ),
    }

    print("Replay saved:", output_path)
    print(
        "Shaped reward:",
        f"{shaped_reward_total:.2f}",
    )
    print(
        "Original reward:",
        f"{original_reward_total:.2f}",
    )
    print(
        "Completed a flip:",
        replay_details[
            "flip_completed"
        ],
    )
    print(
        "Landed safely:",
        replay_details[
            "landed_safely"
        ],
    )
    print(
        "Flipped and landed:",
        replay_details[
            "flip_and_landed"
        ],
    )
    print(
        "Rotations completed:",
        f"{replay_details['rotations_completed']:.2f}",
    )

    return replay_details

In [36]:
flip_replay = record_flip_replay(
    selected_model_path,
    output_path=(
        "/content/"
        "ppo-LunarLander-v3-"
        "flip-replay.mp4"
    ),
    seed=video_seed,
    reward_config=reward_config,
)

flip_replay

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/rendering.py:292: UserWarning: WARN: Overwriting existing videos at /content/_flip_video_recording folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(

Replay saved: /content/ppo-LunarLander-v3-flip-replay.mp4
Shaped reward: 104.63
Original reward: 314.04
Completed a flip: False
Landed safely: True
Flipped and landed: False
Rotations completed: -0.00

{'path': '/content/ppo-LunarLander-v3-flip-replay.mp4',
 'seed': 20017,
 'shaped_reward': 104.6327433268484,
 'original_reward': 314.0439376914249,
 'steps': 242,
 'flip_completed': False,
 'landed_safely': True,
 'rotations_completed': -0.0010841254075127623,
 'recovery_completed': False,
 'custom_outcome': 'episode_ended_without_flip',
 'flip_and_landed': False}

In [37]:
from IPython.display import (
    Video,
    display,
)


display(
    Video(
        flip_replay["path"],
        embed=True,
    )
)

### Upload as new model to Hugging Face

In [33]:
from __future__ import annotations

from pathlib import Path
import json
import shutil
import textwrap

from huggingface_hub import HfApi


DEFAULT_CHANGE_NOTES = [
    (
        "Reduced the combined rotation-progress and flip-completion "
        "reward so a flip followed by a crash is less attractive."
    ),
    (
        "Increased the pre-flip weight on the original LunarLander "
        "reward so the agent is less free to drift far from the pad "
        "while rotating."
    ),
    (
        "Added a one-off recovery reward for becoming upright and "
        "arresting angular velocity after the flip."
    ),
    (
        "Added dense post-flip potential-difference shaping for "
        "horizontal position, horizontal speed, attitude, angular "
        "speed, and leg contact."
    ),
    (
        "Added a failed-landing penalty and increased the terminal "
        "flip-and-safe-landing bonus."
    ),
    (
        "Added a recovery-completed observation flag. The wrapped "
        "observation now contains 11 values rather than the base "
        "environment's 8 values."
    ),
]


def _markdown_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"

    if isinstance(value, float):
        return f"{value:g}"

    return str(value)


def _markdown_table(mapping: dict) -> str:
    rows = [
        "| Parameter | Value |",
        "|---|---:|",
    ]

    for key, value in mapping.items():
        rows.append(
            f"| `{key}` | {_markdown_value(value)} |"
        )

    return "\n".join(rows)


def upload_flip_model_to_hub(
    model_or_path,
    *,
    repo_id: str,
    flip_evaluation: dict,
    replay_details: dict,
    training_config_path: str | Path,
    reward_config: dict,
    reward_wrapper_path: str | Path,
    model_filename: str = (
        "ppo-LunarLander-v3-flip-128x128.zip"
    ),
    reward_version: str = "v2-post-flip-recovery",
    change_notes: list[str] | None = None,
    commit_message: str = (
        "Update PPO agent with post-flip recovery shaping"
    ),
    private: bool = False,
):
    """
    Upload a trained PPO checkpoint and the exact custom environment
    definition used to train and evaluate it.

    Reusing the same repo_id and filenames updates the current Hub
    files in a new commit; previous revisions remain in repository
    history.
    """

    if not reward_config:
        raise ValueError(
            "reward_config must contain the exact configuration "
            "used for training."
        )

    model = load_ppo_model(model_or_path)

    summary = dict(
        flip_evaluation["summary"]
    )
    episode_results = (
        flip_evaluation["episodes"].copy()
    )

    replay_path = Path(
        replay_details["path"]
    )
    training_config_path = Path(
        training_config_path
    )
    reward_wrapper_path = Path(
        reward_wrapper_path
    )

    required_paths = {
        "Replay": replay_path,
        "Training configuration": training_config_path,
        "Reward wrapper": reward_wrapper_path,
    }

    for label, path in required_paths.items():
        if not path.exists():
            raise FileNotFoundError(
                f"{label} not found: {path}"
            )

    training_config = json.loads(
        training_config_path.read_text(
            encoding="utf-8"
        )
    )

    staging_directory = (
        Path("/content/hf-flip-model")
        / repo_id.replace("/", "__")
    )

    if staging_directory.exists():
        shutil.rmtree(staging_directory)

    staging_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    saved_model_path = (
        staging_directory / model_filename
    )
    model.save(str(saved_model_path))

    if not saved_model_path.exists():
        raise FileNotFoundError(
            "The PPO model was not saved at "
            f"{saved_model_path}"
        )

    shutil.copy2(
        replay_path,
        staging_directory / "replay.mp4",
    )
    shutil.copy2(
        training_config_path,
        staging_directory / "training_config.json",
    )
    shutil.copy2(
        reward_wrapper_path,
        staging_directory
        / "flip_landing_reward_wrapper.py",
    )

    (
        staging_directory / "reward_config.json"
    ).write_text(
        json.dumps(
            reward_config,
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )

    episode_results.to_csv(
        staging_directory / "episode_results.csv",
        index=False,
    )

    notes = list(
        change_notes
        if change_notes is not None
        else DEFAULT_CHANGE_NOTES
    )

    results_payload = {
        "environment": {
            "base_environment": "LunarLander-v3",
            "custom_objective": (
                "Complete a full directed rotation, recover to "
                "a stable upright attitude, re-centre, and land "
                "safely."
            ),
            "reward_version": reward_version,
            "observation_space": {
                "base_dimensions": 8,
                "added_dimensions": [
                    "signed_rotation_progress",
                    "flip_completed",
                    "recovery_completed",
                ],
                "wrapped_dimensions": 11,
            },
            "reward_config": reward_config,
            "change_notes": notes,
        },
        "evaluation": summary,
        "evaluation_seeds": (
            episode_results["seed"]
            .astype(int)
            .tolist()
        ),
        "replay": {
            key: value
            for key, value in replay_details.items()
            if key != "path"
        },
    }

    (
        staging_directory / "results.json"
    ).write_text(
        json.dumps(
            results_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    config_payload = {
        "algorithm": "PPO",
        "library": "stable-baselines3",
        "base_environment": "LunarLander-v3",
        "model_filename": model_filename,
        "reward_version": reward_version,
        "reward_config_filename": "reward_config.json",
        "reward_wrapper_filename": (
            "flip_landing_reward_wrapper.py"
        ),
        "observation_dimensions": 11,
        "architecture": {
            "actor_layers": training_config.get(
                "actor_layers"
            ),
            "critic_layers": training_config.get(
                "critic_layers"
            ),
        },
        "evaluation": {
            "mean_shaped_reward": summary.get(
                "mean_shaped_reward"
            ),
            "mean_original_reward": summary.get(
                "mean_original_reward"
            ),
            "flip_completion_rate": summary.get(
                "flip_completion_rate"
            ),
            "recovery_completion_rate": summary.get(
                "recovery_completion_rate"
            ),
            "safe_landing_rate": summary.get(
                "safe_landing_rate"
            ),
            "flip_landing_rate": summary.get(
                "flip_landing_rate"
            ),
        },
    }

    (
        staging_directory / "config.json"
    ).write_text(
        json.dumps(
            config_payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    actor_layers = training_config.get(
        "actor_layers",
        "Not supplied",
    )
    critic_layers = training_config.get(
        "critic_layers",
        "Not supplied",
    )

    video_url = (
        f"https://huggingface.co/{repo_id}"
        "/resolve/main/replay.mp4"
    )

    change_notes_markdown = "\n".join(
        f"{index}. {note}"
        for index, note in enumerate(
            notes,
            start=1,
        )
    )

    reward_table = _markdown_table(
        reward_config
    )

    optional_recovery_row = ""

    if (
        summary.get("recovery_completion_rate")
        is not None
    ):
        optional_recovery_row = (
            "| Post-flip recovery rate | "
            f"{summary['recovery_completion_rate']:.1%} |\n"
        )

    readme = textwrap.dedent(
        f"""
        ---
        library_name: stable-baselines3
        pipeline_tag: reinforcement-learning
        tags:
        - stable-baselines3
        - reinforcement-learning
        - deep-reinforcement-learning
        - PPO
        - LunarLander-v3
        - custom-reward
        - reward-shaping
        - actor-critic
        ---

        # PPO LunarLander flip, recover and land agent

        This repository contains a Stable-Baselines3 PPO
        actor-critic agent trained on a customised
        `LunarLander-v3` environment.

        The objective has three stages:

        1. complete one full rotation in a fixed direction;
        2. return upright and arrest the spin;
        3. re-centre, stabilise and land with both legs.

        Reward configuration version: `{reward_version}`.

        ## Changes in this upload

        {change_notes_markdown}

        ## Reward design

        Rotation progress is rewarded only when the agent reaches
        previously unseen progress. After the full rotation, a
        potential-difference reward encourages improvement in:

        - horizontal distance from the pad centre;
        - horizontal speed;
        - orientation;
        - angular speed;
        - leg contact.

        The terminal success bonus is awarded only after a completed
        flip and a safe landing. A completed flip followed by an
        unsuccessful landing receives the configured failed-landing
        penalty.

        {reward_table}

        ## Observation space

        The base `LunarLander-v3` observation contains 8 values.
        This wrapper appends:

        1. signed rotation progress;
        2. flip-completed flag;
        3. recovery-completed flag.

        The policy therefore expects **11 observation values** and
        cannot be used directly with an unwrapped
        `LunarLander-v3` environment.

        ## Evaluation

        Deterministic evaluation over
        {summary['n_episodes']} fixed-seed episodes:

        | Metric | Value |
        |---|---:|
        | Mean shaped reward | {summary['mean_shaped_reward']:.2f} |
        | Shaped reward standard deviation | {summary['std_shaped_reward']:.2f} |
        | Shaped course-style score | {summary['shaped_course_score']:.2f} |
        | Minimum shaped reward | {summary['min_shaped_reward']:.2f} |
        | Maximum shaped reward | {summary['max_shaped_reward']:.2f} |
        | Mean original reward | {summary['mean_original_reward']:.2f} |
        | Original reward standard deviation | {summary['std_original_reward']:.2f} |
        | Original course-style score | {summary['original_course_score']:.2f} |
        | Original reward >= 200 | {summary['original_reward_200_rate']:.1%} |
        | Full-rotation rate | {summary['flip_completion_rate']:.1%} |
        {optional_recovery_row}| Safe-landing rate | {summary['safe_landing_rate']:.1%} |
        | Flip-and-land rate | {summary['flip_landing_rate']:.1%} |
        | Minimum original reward | {summary['min_original_reward']:.2f} |
        | Maximum original reward | {summary['max_original_reward']:.2f} |

        Shaped rewards are not directly comparable with scores from
        the standard LunarLander environment.

        ## Architecture

        - Algorithm: PPO
        - Policy: MLP actor-critic
        - Actor hidden layers: `{actor_layers}`
        - Critic hidden layers: `{critic_layers}`

        ## Training configuration

        | Parameter | Value |
        |---|---:|
        | Training timesteps | {training_config.get('total_timesteps')} |
        | Parallel environments | {training_config.get('n_envs')} |
        | Learning rate | {training_config.get('learning_rate')} |
        | Rollout steps per environment | {training_config.get('n_steps')} |
        | Batch size | {training_config.get('batch_size')} |
        | Optimisation epochs | {training_config.get('n_epochs')} |
        | Gamma | {training_config.get('gamma')} |
        | GAE lambda | {training_config.get('gae_lambda')} |
        | Entropy coefficient | {training_config.get('ent_coef')} |
        | PPO clip range | {training_config.get('clip_range')} |
        | Training seed | {training_config.get('seed')} |

        ## Replay

        - Seed: `{replay_details['seed']}`
        - Original reward:
          `{replay_details['original_reward']:.2f}`
        - Shaped reward:
          `{replay_details['shaped_reward']:.2f}`
        - Rotations completed:
          `{replay_details['rotations_completed']:.2f}`
        - Flip completed:
          `{replay_details['flip_completed']}`
        - Recovery completed:
          `{replay_details.get('recovery_completed', 'Not recorded')}`
        - Landed safely:
          `{replay_details['landed_safely']}`

        <video controls autoplay loop muted width="640">
          <source src="{video_url}" type="video/mp4">
        </video>

        ## Load the model

        The wrapper and reward configuration are included in this
        repository because the policy requires the augmented
        11-value observation.

        ```python
        import json
        import sys
        from pathlib import Path

        from huggingface_hub import hf_hub_download
        from stable_baselines3 import PPO

        checkpoint = hf_hub_download(
            repo_id="{repo_id}",
            filename="{model_filename}",
        )
        wrapper_file = hf_hub_download(
            repo_id="{repo_id}",
            filename="flip_landing_reward_wrapper.py",
        )
        reward_file = hf_hub_download(
            repo_id="{repo_id}",
            filename="reward_config.json",
        )

        sys.path.insert(
            0,
            str(Path(wrapper_file).parent),
        )

        from flip_landing_reward_wrapper import (
            make_flip_lander,
        )

        reward_config = json.loads(
            Path(reward_file).read_text(
                encoding="utf-8"
            )
        )

        env = make_flip_lander(
            reward_config=reward_config
        )

        model = PPO.load(
            checkpoint,
            env=env,
            device="cpu",
        )
        ```
        """
    ).strip()

    (
        staging_directory / "README.md"
    ).write_text(
        readme,
        encoding="utf-8",
    )

    print("Prepared files:")

    for path in sorted(
        staging_directory.iterdir()
    ):
        print(
            "-",
            path.name,
            f"({path.stat().st_size / 1024:.1f} KiB)",
        )

    api = HfApi()

    api.create_repo(
        repo_id=repo_id,
        repo_type="model",
        private=private,
        exist_ok=True,
    )

    upload_result = api.upload_folder(
        folder_path=str(staging_directory),
        repo_id=repo_id,
        repo_type="model",
        commit_message=commit_message,
    )

    print()
    print("Upload complete:", upload_result)
    print(
        "Model repository:",
        f"https://huggingface.co/{repo_id}",
    )

    return {
        "repo_id": repo_id,
        "staging_directory": staging_directory,
        "summary": summary,
        "reward_version": reward_version,
        "upload_result": upload_result,
    }

In [34]:
upload_result = upload_flip_model_to_hub(
    selected_model_path,

    repo_id=(
        "KaptainKris92/"
        "ppo-LunarLander-v3-flip"
    ),

    flip_evaluation=flip_evaluation,
    replay_details=flip_replay,

    training_config_path=(
        flip_run["config_path"]
    ),

    reward_config=reward_config,
    reward_wrapper_path=(
        REWARD_WRAPPER_PATH
    ),

    model_filename=(
        "ppo-LunarLander-v3-"
        "flip.zip"
    ),

    commit_message=(
        "Retrain PPO flip-and-land agent "
        "with post-flip recovery shaping"
    ),
)

Prepared files:
- README.md (6.6 KiB)
- config.json (0.7 KiB)
- episode_results.csv (12.7 KiB)
- flip_landing_reward_wrapper.py (15.7 KiB)
- ppo-LunarLander-v3-flip.zip (151.4 KiB)
- replay.mp4 (48.6 KiB)
- results.json (4.2 KiB)
- reward_config.json (0.7 KiB)
- training_config.json (0.6 KiB)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

HfHubHTTPError: (Request ID: Root=1-6a54b0bf-15b6c8883d75a74b27bac69c;03705018-bd03-4e3c-9080-af5815001f23)

403 Forbidden: You don't have the rights to create a model under the namespace "KaptainKris92".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.